### ISSUE TITLE
Manual renew refresh token/ silent renew:false is not working

### ISSUE THREAD

**Issue by ebinroy** [damienbod/angular-auth-oidc-client#1001]
Hi All,
       I would like to achieve the below scenario. 
**STS Config (using Identity server4)**
```

new Client
            {
                ClientId = "clientangular",
                ClientName = "Angular Client",
                AllowedGrantTypes = GrantTypes.Code,
                RequireClientSecret = false,
                AllowedScopes = new List<string>
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    "api1",
                    "roles"
                },

                
                RedirectUris = new List<string> { "http://localhost:4200" },
                PostLogoutRedirectUris = new List<string> {"http://localhost:4200" },
                AllowedCorsOrigins = new List<string> { "http://localhost:4200" },

                
                RequireConsent= false,
                RequirePkce = true,
                AllowAccessTokensViaBrowser = true,
                AccessTokenLifetime = 60,  
                AllowOfflineAccess = true,
                //AbsoluteRefreshTokenLifetime = 21600, //6hrs
                

                RefreshTokenExpiration = TokenExpiration.Sliding,   //once refresh token issued then renew the timing of token expiration
                UpdateAccessTokenClaimsOnRefresh = true
            }
```

**Client Side (Angular)**

```
oidcConfigService.withConfig({
      stsServer: 'https://localhost:5001',
      redirectUrl: window.location.origin,
      
      clientId: 'clientangular',
      scope: 'openid profile api1 offline_access',
      responseType: 'code',
      triggerAuthorizationResultEvent: true,
      postLogoutRedirectUri: `${window.location.origin}/unauthorized`,
      
      renewTimeBeforeTokenExpiresInSeconds: 5,
      silentRenew: false,
      
      logLevel: LogLevel.Debug,
      historyCleanupOff: true,
      
    });

```
**Issues**
1) I keep Silent renew as **false**  but it is still calling the  refresh token silently while accessing the API. How to avoid/stop calling refresh token silently?
 

From Angular I want to achieve the below

1) Want to check the access_token is expired or not?
2) Call refreshToken manually , is it correct? But I am getting issue, the error details are attached
                         this.oidcSecurityService.forceRefreshSession().subscribe((result) => console.log(result));
![image](https://user-images.githubusercontent.com/45000952/110098368-10513780-7ddb-11eb-8027-ee6d6a03afa0.png)

**Comment by FabianGosebrink** [comment]
Hey, I am not sure what you want to achieve. Do you want to:

1) turn of refresh tokens?
2) manually refresh your tokens?

or

3) both?

Thanks

**Comment by ebinroy** [comment]
Hi, I would like to manually refresh my token. I don't want to refresh token automatically.

**Comment by damienbod** [comment]
Hi @ebinroy Why do you need to manually implement token refresh? At present this is not supported.

Greetings Damien

**Comment by ebinroy** [comment]
Hi Damien,  what I thought is if the user is inactive for sometime then the popup appears asking whether want to continue or not , if press continue then only do the refresh token otherwise logoff.

**Comment by FabianGosebrink** [comment]
I would then check if the user is inactive (let the lib run as it is) and if the user clicks "no, I don't want to continue" then do the logoff. There is no need to only extend the token if the user clicks yes. So this logic you describe is independent from the lib imho.
