### ISSUE TITLE
CheckSessionService keeps polling after logoffLocal() is invoked.

### ISSUE THREAD

**Issue by krextorix** [damienbod/angular-auth-oidc-client#1002]
**Describe the bug**
When OpenIdConfiguration.startCheckSession property is set to true, CheckSessionService starts pollServerSession using start() method.
When OidcSecurityService.logoffLocal() is invoked, CheckSessionService is still polling checkSessionIframe url but with now null sessionstate.

**To Reproduce**
Steps to reproduce the behaviour:
1. Logon to STS and obtain a valid token.
2. Invoke oidcSecurityService.logoffLocal()
3. Session state polling is still active

**Expected behaviour**
When invoking OidcSecurityService.logoffLocal(), CheckSessionService.stop() method is triggered.
Alternatively expose CheckSessionService api.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.190

**Comment by damienbod** [comment]
We need to add a stop checkSession if activated with a local logout.

**Comment by damienbod** [comment]
also related to this:

https://github.com/damienbod/angular-auth-oidc-client/issues/938

**Comment by damienbod** [comment]
@krextorix thanks for reporting. Will release in version 11.6.3
