### ISSUE TITLE
user not getting authorized after login

### ISSUE THREAD

**Issue by ktandon98** [damienbod/angular-auth-oidc-client#1004]
![image](https://user-images.githubusercontent.com/51206040/110334984-5dd2dc00-8049-11eb-88e3-d1a670c35866.png)

**Comment by ktandon98** [comment]
this is for azurread codeflow

**Comment by damienbod** [comment]
Your STS in not returning a code, please check if the STS is configured correctly, or it returns an error.

Greetings Damien

**Comment by ktandon98** [comment]
https://as-prod.asyncgw.teams.microsoft.com/v1/objects/0-sa-d1-5b50406dde06de4dc4019fef6264c205/views/imgo Hi do you have any suggestions around solving this, also how do i add my client secret to the application?
