### ISSUE TITLE
Is there a silent renew event？

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#1011]
Hello, I now need to do some operations during silent update. When I update silently, is there a silent update event?

**Comment by fengzhihenxs** [comment]
Let me describe my needs. My main site uses the code flow pkce with refresh tokens of angular-auth-oidc-client. The subsite requests the main site to obtain the token. When the subsite requests it, the main site may be silent renew. At this time, the token cannot be requested. I need Do processing in the silent renew event.

**Comment by stefanocke** [comment]
@fengzhihenxs , according to my observations the following event fires after token refresh:
```
{authorizationState: "Authorized", validationResult: "Ok", isRenewProcess: true}
```
But I am not a comitter and don't know if you can rely on this.

**Comment by fengzhihenxs** [comment]
@stefanocke Thank you. But I don't think it is. I found that the "IdTokenExpired" event is triggered before each silent update.

**Comment by JerrettDavis** [comment]
I was looking into the code, and it appears there's a `oidc-silent-renew-init` event that is raised in the `refresh-session-iframe.service` at the beginning of the refresh operation, but nothing is raised during or after.

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25302 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] Is there a silent renew event？ (#1011)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25302>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________

**Comment by damienbod** [comment]
fixed in Version 12
