### ISSUE TITLE
Dynamic redirection post login

### ISSUE THREAD

**Issue by silk-bahamut** [damienbod/angular-auth-oidc-client#1021]
I would like to authenticate and redirect to a dynamic route after the connection.

I have seen the AutoLoginGuard and would like to use something similair but with the function authorize of OidcSecurityService.
I have search and it doesn't seem that the AutoLoginService is available for external use so I cannot reproduce this elsewhere.

After a bit of research, I found [this page](https://auth0.com/docs/protocols/state-parameters#use-the-stored-url-to-redirect-users) of Auth0 that suggest to use the state to store a context before login and restore it after.

I consider using the state parameter as suggested in the above documentation from auth0 but after login, getState always returns null

What is the best way to achieve such a redirection?

**Comment by FabianGosebrink** [comment]
Hey, thanks for the question.

So you can protect a route and redirect to it after you have automatically redirected to the login server and back with the `AuthLoginGuard`. What do you mean by `dynamic route`?

Have you taken a look at the `postLoginRoute` in the config? Maybe you can use this when your sts is configured correctly. But maybe this crashes with your `dynamic route`. Can you evaluate what a `dynamic route` is?

Thanks

**Comment by FabianGosebrink** [comment]
Hey, thanks. That is a nice suggestion but we would have to have kind of a flag to read to set this redirection dynamically. For this moment I do not consider this to be a feature we are taking over in this library in our free time :) I hope you understand. I would give this a low Prio imho. You still have the possibility to store the route based on how you pass the route around and redirect I assume. Thanks!

**Comment by silk-bahamut** [comment]
Hey, no problem, I will stick to a manual store before redirect.

If you ever make it, the context stored with the state as key seems like the best solution since it allows to store anything and link it to state that was resolved and avoid overlapping contexts.
`{
  "xyzABC123" : {
    redirectUrl: '/protectedResource',
    expiresOn: [...]
  }
}`

Thank you for your answers, your time and your great library.
Cheers
