### ISSUE TITLE
Silent Renew (PeriodicallyTokenCheckService) keeps polling after logoffLocal() is invoked

### ISSUE THREAD

**Issue by stefanocke** [damienbod/angular-auth-oidc-client#1023]
**Describe the bug**
After logoffLocal, the silent renew  keeps polling. Log keeps saying:
```
angular-auth-oidc-client.js:212 Wanted to read 'portal2_storageSilentRenewRunning' but nothing was found
angular-auth-oidc-client.js:212 Wanted to read 'portal2_userData' but nothing was found
angular-auth-oidc-client.js:212 Checking: silentRenewRunning: false id_token: false userData: false
angular-auth-oidc-client.js:212 silent renew, periodic check finished!
```

**To Reproduce**

- enable silent renew
- enable debug log
- login
- call logoffLocal()

**Expected Behavior**

If this intentionally (for instance for cases where multiple tabs share their data in local storage instead of session storage), this should probably be documented somewhere.
Otherwise, the polling should stop with logoffLocal().

**Comment by damienbod** [comment]
Hi @stefanocke I'll check this, might have missed this, thanks for reporting

Greetings Damien

**Comment by damienbod** [comment]
Hi @stefanocke Tested this now and it works in the sample; start-sample-code-flow-http-config

This looks good to me.

Greetings Damien
