### ISSUE TITLE
[Enhancement] : Is there any way to update post logout redirect uri after successful login.

### ISSUE THREAD

**Issue by abdullahqudeer** [damienbod/angular-auth-oidc-client#1026]
Is there any way to update post logout redirect URI after successful login.

I have multiple post logout redirect uris in my sts server ... , I need to set post logout redirect uri dynamically based on logged in user. 

Please guide me how can I achieve this.

Thanks,

**Comment by damienbod** [comment]
HI @abdullahqudeer you would have to implement this yourself, we haveing nothing here. You would need to persist something to a local storage and then react as your requirements define this.

**Comment by hadrien-toma** [comment]
@damienbod are you saying this is out of the scope of this library? On my side I would find it very useful to have it mutualized in the authentication library so here.

**Comment by abdullahqudeer** [comment]
@damienbod , Thanks for you reply ... I have managed to update configuration as below.

` this.oidcSecurityService.configuration.configuration.postLogoutRedirectUri="any post logout url"`

But I would suggest to add a proper way to update these kind of configuration in some future release.

**Comment by damienbod** [comment]
Hi @hadrien-toma @abdullahqudeer yes You can only define explicit postLogoutRedirectUri values which are also defined on the OIDC server. So if you can define all th erequired URLs on the STS, then you can use anyone of these. If the URLs can be anything, then you need to implement something yourself.

Greetings Damien

**Comment by hadrien-toma** [comment]
Thank you for your reply @damienbod, this makes sense 🙂. As having a wild card on the SSO configuration isn't recommanded, I will implement this redirection in the component called behind the "/redirect" route.
