### ISSUE TITLE
Angular Router navigations should be (probably) triggered with navigateByUrl() function

### ISSUE THREAD

**Issue by TomaszKasowicz** [damienbod/angular-auth-oidc-client#1028]
**Describe the bug**
Currently all side effects or `catchError` functions use `this.router.navigate()` function to redirect to one of the predefined routes
This works great but fails when users enter URL with query params.
(i.e http://example.com?foo=5&bar=10)

This actually is a known bug in Angular Router
(see https://github.com/angular/angular/issues/28917)

The workaround would be to use `navigateByUrl()` instead.
(for example: `this.router.navigateByUrl(this.configurationProvider.openIDConfiguration.postLoginRoute);`)

**To Reproduce**
1. Go to 'http://example.com?foo=5&bar=10'

2. Set postLoginRoute to '/?foo=5&bar=10

3. See error in console:
**(Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '%3Ffoo%3D5&bar%3D10')**

**Expected behavior**
After navigation there shouldn't be any error in console and the Address bar should contain URL with query params

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 89.0.4389.90 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by eastjie** [comment]
Can you try to set postLoginRoute with "location.path()".  Location from '@angular/common' is normalized. It works for me with long and complex path with many query parameter to set post login route.

**Comment by andrew-landsverk-win** [comment]
I've seen the double encoding issue in the browser at times. I have not nailed down the situation when it occurs though, so this change would be welcome :)

**Comment by Liskron** [comment]
After some checks we found an issue related to encoding.
If you will pass in config: `redirectUrl` an url with query params in the end you will get 400 error from your authentication service 
because in body you will get something like this: 
![image](https://user-images.githubusercontent.com/17430634/114413328-2d351380-9bae-11eb-9f24-fa109ca2904e.png)
In the beginning url was : `https://domainname.com:8443/users?*a*=5&*aware*=test&*code*=somedata&*state*=somedata`

The reason is UrlService method **getRedirectUrl** :
`
getRedirectUrl() {
        var _a;
        const redirectUrl = (_a = this.configurationProvider.openIDConfiguration) === null || _a === void 0 ? void 0 : _a.redirectUrl;
        if (!redirectUrl) {
            this.loggerService.logError(`could not get redirectUrl, was: `, redirectUrl);
            return null;
        }
        return redirectUrl;
    }
`
There is no encoding for using URL in form body in request to the authentication service.

**Comment by TomaszKasowicz** [comment]
@damienbod @FabianGosebrink 
If it is OK with You i can create a PR which switches navigate to navigateByUrl().

**Comment by FabianGosebrink** [comment]
Hey @TomaszKasowicz , sure, that'd be awesome!

**Comment by TomaszKasowicz** [comment]
@FabianGosebrink 
The fix is ready but I cannot push the changes (I'm getting `Please make sure you have the correct access rights`)

**Comment by FabianGosebrink** [comment]
You have to fork this project into you github account and then do a new branch describing your feautre an dcheck in on that. Then from there you can do a PR.
