### ISSUE TITLE
AuthModule.forChild() registering services?

### ISSUE THREAD

**Issue by fdcastel** [damienbod/angular-auth-oidc-client#103]
What's the purpose of re-registering services (`providers:`) in `AuthModule.forChild()` which were already declared in `AuthModule.forRoot()`?

As a general rule, services should be declared only in root injector (in `AppModule`).

As it stands now, the importing of `AuthModule.forChild()` in any secondary module would cause the creation of another instance of all services declared in its `providers` clause. This is by design?

If not, as a suggestion, I believe [this](https://stackoverflow.com/a/39653824) is a better pattern for declaration of angular modules (avoiding completely the need of `.forChild()`)

**Comment by damienbod** [comment]
@fdcastel This is per design, in case you want to use to lib in a child module only.

**Comment by robisim74** [comment]
@damienbod  At the moment they are the same: do you have anything in mind for the lazy loaded modules? otherwise you can remove it in the next major release.

**Comment by damienbod** [comment]
@robisim74 @fdcastel Ok I think we should remove it as well

**Comment by damienbod** [comment]
removed, from release 2.0.1 onwards
