### ISSUE TITLE
Logout from all tabs does not work when deployed to a test environment 

### ISSUE THREAD

**Issue by WorldOnMyFingers** [damienbod/angular-auth-oidc-client#1031]
Hi, 
I have an angular  9 app which uses Azure AD authentication with angular-auth-oidc-client version 11.6.4 and
I have configured it to use session state to log out from all tabs and it successfully logs out from all tabs when I do from one of them on my localhost.
However, when I deploy the angular app to test environment on to aws cloud using cloundfront, I start getting the error 
"OidcSecurityCheckSession not receiving check session response messages. Outstanding messages: 6. Server unreachable?" 
and when I logout from one tab, it does not logout from other tabs but my local host tabs log out. 
So, it seems that it can not reach to the server to check session status, so it cannot proceed to logout if no valid status returned from the server. 

My question is that Why would it differ from localhost to test environment on aws? Could you please tell me if I am missing any point any where?
Please see my console logs attached.

- Tested on desktop, windows os machine.
- Tested on Chrome browser.

Thanks a lot,
Kind Regards,
Emre Babayigit
![ErrorOnAwsTestEnvironment](https://user-images.githubusercontent.com/7997399/112184050-bf24ae80-8bf6-11eb-8c96-bbfc4ff1daf9.PNG)

**Comment by damienbod** [comment]
@WorldOnMyFingers hi this might be a WAF or something on your cloud deployment blocking this?

Greetings Damien

**Comment by alpesh1988** [comment]
@WorldOnMyFingers Can you show me how did you achieve logging out from all tabs ?... for me, User stays logged in even though logging out from one tab. 
I would appreciate your help in this regard.
