### ISSUE TITLE
Dynamic custom parameters while using [AutoLoginGuard]

### ISSUE THREAD

**Issue by ebinroy** [damienbod/angular-auth-oidc-client#1032]
I want to get the parameter from the URL and pass to the STS

**Example**
http://localhost:4200/home/ABC  ( want to read the parameter ABC and pass to the STS as custom parameter)

All the pages having the guard **AutoLoginGuard**

```
const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'home' },  
  { path: 'home', component: AutoLoginComponent ,canActivate: [AutoLoginGuard]},
  { path: 'home/:id', component: AutoLoginComponent ,canActivate: [AutoLoginGuard]} ,
  { path: 'dashboard', component: DashboardComponent,canActivate: [AutoLoginGuard] }
] ;

```
In the document its is mentioned that using below code we can pass but in the above case before hitting the component its redirecting to STS

`this.oidcSecurityService.authorize({ customParams: { ui_locales: 'de-CH' }});`

How this can be achieved?

**Comment by damienbod** [comment]
You could implement the AotuLoginGuard yourself with your specific logic.

Greetings Damien

**Comment by ebinroy** [comment]
@damienbod 
Him Thanks for the suggestion. I have created guard but trying to import AuthStateService,AutoLoginService,CheckAuthService,LoginService I am getting the below error "Module not found" . I am using the version 11.6.4

![image](https://user-images.githubusercontent.com/45000952/112415769-658bc380-8d5f-11eb-8d57-45a7abcdea4d.png)


**In app-module** 

```
import { AuthStateService } from 'angular-auth-oidc-client/lib/authState/auth-state.service';
import { AutoLoginService } from 'angular-auth-oidc-client/lib/auto-login/auto-login-service';
import { CheckAuthService } from 'angular-auth-oidc-client/lib/check-auth.service';
import { LoginService } from 'angular-auth-oidc-client/lib/login/login.service';


 providers: [
    //refresh issue
    {provide: LocationStrategy, useClass: HashLocationStrategy},
    //oidc-client
    OidcConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: configureAuth,
      deps: [OidcConfigService],
      multi: true,
    },
    AuthStateService,
    AutoLoginService,
    CheckAuthService,
    LoginService
  ],
```

**Comment by lufo88ita** [comment]
I apologize to post a comment on an old issue, but I have a solution for this.
I don't know why, but the export seems a bit messed up, so for import that classes I need to do this:

```
import { ɵu as AuthStateService } from "angular-auth-oidc-client";
import { ɵl as CheckAuthService } from "angular-auth-oidc-client";
import { ɵbn as AutoLoginService } from "angular-auth-oidc-client";
import { ɵbq as LoginService } from "angular-auth-oidc-client";
```
You can check the aliases in the file:
<yourAppRoot>\node_modules\angular-auth-oidc-client\angular-auth-oidc-client.d.ts

regards,
