### ISSUE TITLE
401 Unauthorized error after logged in

### ISSUE THREAD

**Issue by smrutiranjan727** [damienbod/angular-auth-oidc-client#1037]
![image](https://user-images.githubusercontent.com/18301541/112825668-acecb980-90a9-11eb-9cf7-d23407cd78ad.png)

Hi @damienbod. Hope you're doing great.
Trying to include the oidc in my Angular client app, but facing problem implementing it. Have attached the Debug log for reference.

My ASP.NET Core Identity server runs on 5001 and the Api on 6001.
It successfully redirects to the Identity server, logs in and returns back with the tokens as you can see in the screenshot attached.
But the Api call returns with a 401 Unauthorized error. Not sure why. My http interceptor already includes the Bearer token.

intercept(request: HttpRequest<any>, next: HttpHandler) {
        const token = this.authService.token; //calls oidcSecurityService.getToken() in authService
        console.log('token', token);
        if (!token) {
            return next.handle(request);
        }
        request = request.clone({
            headers: request.headers.set('Authorization', 'Bearer ' + token)
        })
        return next.handle(request);
    }

- And the Api has Authentication set to Bearer in ConfigureServices.

services.AddAuthentication("Bearer")
               .AddJwtBearer("Bearer", options =>
               {
                   options.Authority = "https://localhost:5001";
                   options.TokenValidationParameters = new TokenValidationParameters
                   {
                       ValidateAudience = false
                   };
               });

Am I missing anything?

**Comment by malled** [comment]
That's a configuration issue on your side. 
Check these examples (I assume that you are using IS4):

https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Clients/src/JsOidc
https://github.com/IdentityServer/IdentityServer4/tree/main/src/IdentityServer4

Your logged token "07.." looks wrong. You need to pass a valid JWT. It should probably begin with "ey..", like explained here: https://jwt.io/introduction.

You can check your token with https://jwt.ms/.

**Comment by malled** [comment]
you have to pass in the access token, not the id token. 
angular has, afaik, no size limit. but there is a general limit in url size, and as the token is part of url, this limit is applied.

are you storing any other information in your access token?

can you provide a minimal runnable example with your IS server, API and client?

**Comment by smrutiranjan727** [comment]
Hi @malled, Thanks for your time.
The logged token **"07.."** is returned by **getToken()** method. **getIdToken()** gives a token starting with **"ey.."**
So, as per your previous comment, I am not sure actually what is the token need to be passed as the Bearer token in the http header.

Please refer to [this repository](https://github.com/smrutiranjan727/AspNetIdServ-AngularClient) that I created to share with you. It has the ASP Net Core Identity Server, Api and the Angular Client Projects. Also I have included the Mvc Client.

**Comment by malled** [comment]
I changed the following to get your example working:
- auth service: use getToken()
- home component: subscribe for userData so that ApiCall is executed after user signed in

most important change:
I did not use reference tokens. Do you need them? I have no experience with reference tokens.
Please see https://identityserver4.readthedocs.io/en/latest/topics/reference_tokens.html for configuration for reference tokens. That's why your token looks like "07..." as it is a reference token and not a JWT. In your example, your api only validates JWTs (AddJwtBearer...)

**Comment by smrutiranjan727** [comment]
But getToken() returns the token that looks like "07..."
I changed it to getIdToken() in my auth service after the following reply.


> That's a configuration issue on your side.
> Check these examples (I assume that you are using IS4):
> 
> https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Clients/src/JsOidc
> https://github.com/IdentityServer/IdentityServer4/tree/main/src/IdentityServer4
> 
> Your logged token "07.." looks wrong. You need to pass a valid JWT. It should probably begin with "ey..", like explained here: https://jwt.io/introduction.
> 
> You can check your token with https://jwt.ms/.

**Comment by malled** [comment]
Please remove this line 
https://github.com/smrutiranjan727/AspNetIdServ-AngularClient/blob/9e4708e63468fbcf45fd62fc19700f7018095e3b/IdentityServerAspNetIdentity/Config.cs#L110

so you Use self contained jwt token and not reference token.
If you want to use reference token you probability need to change your api token handler.

**Comment by smrutiranjan727** [comment]
Thanks. Removing that line works.
