### ISSUE TITLE
How do we control the dimension of the popup that the authorizeWithPopUp method opens?

### ISSUE THREAD

**Issue by Sudharsan-Narayanasamy** [damienbod/angular-auth-oidc-client#1043]
How do we control the dimension of the popup that the authorizeWithPopUp method opens ? Is it possible ?

I see that the LoginService exposes a method called loginWithPopUp that takes in popupOptions as an additional argument. But I am not sure of how to use it. Not much documentation on this. How different is this method compared to authorizeWithPopUp ?

Can you please clarify ?

**Comment by damienbod** [comment]
You can pass the options as a param and the options are set as follows:

https://github.com/damienbod/angular-auth-oidc-client/blob/630f4e7f4eb92e432e540b739d2034e52b0e027b/projects/angular-auth-oidc-client/src/lib/login/popup/popup.service.ts#L59

So just pass what you need.

Greetings Damien

**Comment by FabianGosebrink** [comment]
Maybe we can document this better.

**Comment by Sudharsan-Narayanasamy** [comment]
Thank you @FabianGosebrink  . Will pull the latest package and give it a try.

**Comment by FabianGosebrink** [comment]
Please see the attached PR: It is not merged yet. Please stay tuned here :)

**Comment by damienbod** [comment]
@Sudharsan-Narayanasamy  Will be released in the next minor version, Thanks for reporting.

Greetings Damien

**Comment by Sudharsan-Narayanasamy** [comment]
@damienbod Thanks for the update. Do you have any time frame on when it will be released ?

**Comment by damienbod** [comment]
Hi @Sudharsan-Narayanasamy It will probably be Friday or Saturday, I would like to get 2 other small fixes into the release, hope this is ok

Greetings Damien

**Comment by Sudharsan-Narayanasamy** [comment]
Thank you @damienbod . Absolutely okay.
