### ISSUE TITLE
AutoLogin with RefreshTokens

### ISSUE THREAD

**Issue by ghost** [damienbod/angular-auth-oidc-client#1046]
**Is your feature request related to a problem? Please describe.**
Hi, I'm using your library in my Angular App (I'm using Angular 11)
This is my configuration:
```
oidcConfigService.withConfig({
      stsServer: environment.authUrl,
      redirectUrl: `${window.location.origin}/`,
      postLogoutRedirectUri: `${window.location.origin}/`,
      clientId: 'ayuppieSpa',
      scope: 'openid  profile email offline_access',
      responseType: 'code',
      logLevel: environment.logLevel,
      silentRenew: true,
      silentRenewUrl: `${window.location.origin}/silent.html`,
      autoUserinfo: true,
      renewUserInfoAfterTokenRenew: true,
      
    });
```
As you can see I use silentrefresh to Achieve an auto-login when the app start I call
`checkAuthIncludingServer`

And It works! But I want, if possibile, achieve a better result: 

**Describe the solution you'd like**
- app call checkAuthIncludingServer or similar and use "silentRefresh" only the first time
- when the authToken is about to expire use the refreshToken (and not silentrefresh) to renew the token

**Describe alternatives you've considered**
I simply call checkAuthIncludingServer  while setting useRefreshToken to true, but the library return "No refresh token available" the first time the web app start and the user need to manual login.

**Additional context**
My app has a first page (home) which has no protection, but I want to redirect the user to another page if it is already authorized.

regards, :-)

P.S. A detail: checkAuthIncludingServer print in the console:
"Error: login_required" (angular-auth-oidc-client.js:194) if the user is not authenticated. Is it possible to hide this print? In fact it can happen.

**Comment by damienbod** [comment]
hope this works for you now. You can renew using only the refresh tokens. Please check the docs and the samples

Greetings Damien
