### ISSUE TITLE
All paths with a query string including 'code' or 'state' are being intercepted by angular-auth-oidc-client

### ISSUE THREAD

**Issue by matthewwren** [damienbod/angular-auth-oidc-client#1049]
I know this will be by design, so it is more a general question of how I configure it correctly.  I have noticed that any path with a query string including `code` or `state` is being intercepted by `angular-auth-oidc-client`.  We can't change the query string either, and it is stopping our application from working.  Is there any way to get it to only intercept a specific callback route?

**Comment by FabianGosebrink** [comment]
Hey @matthewwren , thanks for the issue. I understand your concern but have no solution in mind currently. How can we distinguish if the `code` parameter for example is a callback from the sts and _not_ from your app and vice versa? Any ideas?

**Comment by matthewwren** [comment]
Hi Fabian,

I think we are just setting this up incorrectly.  At the moment we put in `app.component.ts` the following:

```
  ngOnInit(): void {
    this.authService.checkAuth().subscribe((isAuthenticated) => {
      this.isUserLoggedIn = isAuthenticated;
      if (isAuthenticated) {
        this.store.dispatch(setUserLoginStatus({ isUserLoggedIn: true }));

        const token = this.authService.token;
        if (token) {
          this.store.dispatch(setAccessToken({ accessToken: token }));
        }
      }
    });
  }
```
Because this is the root of all components it is then I imagine listening for any parameter changes to `code` and `state` in the query string.  So I am imagining that what I need to do is move this code into a different module that is associated with a route like `auth-callback`.  If that is correct then all I need to understand is how to ask the sts to return to `/auth-callback` rather than `\` as it is doing now.

**Comment by FabianGosebrink** [comment]
Ah you are using ngrx. You should better fire a `checkAuth` action which is then checking the authentication (it calls the `checkAuth()` method inside of an effect). With ngrx, you inject the services into the effects. Then you got this separated and the "ngrx-way"

You can define a return url in the config. I think this is `postLoginRoute` [https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/configuration.md](https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/configuration.md) and then you'll land on another component where you can handle the login stuff.

Maybe this helps? Let us know :)

**Comment by ZeSzymi** [comment]
Hello
I think this is a bug or really bad design. Imagine user refreshes the page with query param state (which is very popular) and what am i supposed to do? Save the url, redirect to url to check auth and then redirect back to url stored in memory? Look what you do
`const CALLBACK_PARAMS_TO_CHECK = ['code', 'state', 'token', 'id_token'];`
You check current url if it contains these parameters.
Why not check if this url contains postLogoutRedirectUri also then it will fire only if you were redirected. Not if you refreshed your page with one of those 4 query params.
I know of this now that i can't use state in query params but what if my team mates are going to add it?

**Comment by ZeSzymi** [comment]
For anyone looking for a solution to this problem.
I check the url first if it contains my return url callback path which is "login" and if it does i return whole url if not i return just the origin
`
const url = this.getAuthUrl();
this._userService.checkAuth(url);
`
