### ISSUE TITLE
No token found?

### ISSUE THREAD

**Issue by dyingangel666** [damienbod/angular-auth-oidc-client#1053]
Hey there,

first thing to say, great library, but i'm facing some issues with the token. After a successful login i will get an access token which is obviously successfully stored... When i now try to call getToken() manually, the response is empty. I also tried to use the build-in HttpInterceptor and added my API Url to the secureRoutes... but then, the lib also logs, no token... Does anyone have any idea what i am doing wrong?

<img width="1157" alt="Bildschirmfoto 2021-04-20 um 11 24 13" src="https://user-images.githubusercontent.com/12126337/115372394-1eacb480-a1cb-11eb-9958-633152acac1b.png">

**Comment by damienbod** [comment]
Hi @dyingangel666  Looks like the app has no access to the session storage. Is this disable in your browser, or you have no access rights?

Greetings Damien

**Comment by dyingangel666** [comment]
@damienbod Checked this out and switched to "allow all cookies"... but still the same issue :( In developer console i can see that all values are correctly stored
<img width="902" alt="Bildschirmfoto 2021-04-20 um 12 03 16" src="https://user-images.githubusercontent.com/12126337/115377990-6aae2800-a1d0-11eb-804b-6b2f1b2ca4b9.png">

**Comment by dyingangel666** [comment]
Has no one an idea what else it could be or what I'm doing wrong?

**Comment by FabianGosebrink** [comment]
Do you have a minimum sample repo to reproduce the issue or to see if it is only on your system or not? Have you checked other browsers? For a sample you can use the config from one of our samples.

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25293 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] No token found? (#1053)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25293>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________

**Comment by dyingangel666** [comment]
Always played with other config and also tried with other browsers (Firefox, Safari). Same problem :-/

**Comment by sneaker102** [comment]
I have the same issue, why is this issue closed?

**Comment by FabianGosebrink** [comment]
Hi,
Can you please share a project or a reproduction, even privately? Unfortunately, without a reproduction, we'll be unable to determine the root cause of the problem. A good way to make a minimal repro is to create a new app via ng new repro-app and adding the minimum possible code to show the problem. Then you can push this repository to GitHub and link it here.
Thanks

**Comment by sneaker102** [comment]
Hi, 
I have a simple implementation:
Config object: {
          authority: this.appConfig.authConfigSettings.issuer,
          clientId: this.appConfig.authConfigSettings.clientId,
          responseType: this.appConfig.authConfigSettings.responseType,
          redirectUrl: this.appConfig.authConfigSettings.redirectUri,
          postLogoutRedirectUri:
            this.appConfig.authConfigSettings.postLogoutRedirectUri,
          silentRenew: true,
          useRefreshToken: true,
          scope: 'openid',
          logLevel: LogLevel.Debug,
        };
Auth Config module:
const authFactory = (configService: AppConfigService) => {
  const config$ = configService.loadAppConfig();
  return new StsConfigHttpLoader(config$);
};

@NgModule({
  imports: [
    AuthModule.forRoot({
      loader: {
        provide: StsConfigLoader,
        useFactory: authFactory,
        deps: [AppConfigService],
      },
    }),
  ],
  exports: [AuthModule],
})
export class AuthConfigModule {}

Auth guard:
checkLoggedIn(url: string): boolean {
    if (this.authService.isLoggedIn() || url === 'login') {
      return true;
    } else {
      this.storeService.add({
        key: 'pathAfterLogin',
        value: url,
      });
      this.router.navigate(['/login']);
      return false;
    }
   }
Login component: 
@Component({
  selector: 'app-login',
  template: ``,
  styles: []
})
export class LoginComponent {

  constructor(private authService: AuthService) {
    this.authService.login();
  }

}

Auth service - login : 
login() {
    const pal = this.storeService.get('pathAfterLogin') || '/';
    console.log(pal);
    if (this.isLoggedIn()) {
      this.router.navigateByUrl(pal);
    } else {
      this.storeService.add({
        key: 'pathAfterLogin',
        value: pal,
      });
      this.oidcSecurityService.authorize();
    }
}
Auth service - isLoggedIn: 
 isLoggedIn(): boolean {
    return this.oidcSecurityService.isAuthenticated();
}

isLoggedIn always returns false event if I see the token into the console:
![tokenOIDC](https://user-images.githubusercontent.com/45992275/130448596-ad1c1a58-bb45-405d-ae57-8f5117d90af9.png)

**Comment by sneaker102** [comment]
Hi, I finally managed to get it right. The problem was that my app triggered some http requests before token validation was ended and that made the window to reload canceling the oauth flow from your lib. Awesome work, thank you for sharing it with us!
