### ISSUE TITLE
[Help]How to perform Single Sign Out

### ISSUE THREAD

**Issue by kprasad99** [damienbod/angular-auth-oidc-client#1054]
I've 2 angular applications `app-store` and `employee-app` and using SSO, I can login to directly to `employee-app` or first login to `app-store` and then from a link launch `employee-app`. Now when I tried to logout from `employee-app` or from `app-store` I'm expecting to logout from both apps. However sessions still continue to exist and page doesn't logout. If I refresh the page then it gets redirected to login page. 

In angular client I've enabled `silent-renew` and `startchecksession`, I can see that events are triggered every few seconds however when I logout from other application, the checksession still returns true. 

NOTE: using different `clientId` for respective applications.

**To Reproduce**
1. Code base is uploaded [here](https://github.com/kprasad99/spring-webflux-keycloak-angular)
2. Steps to run using docker-compose is explained in README.adoc
3. Let me know if any additional information required regarding keycloak.

**Expected behavior**
If a user logs out from one application, user must be logged out from all the apps.

**Comment by damienbod** [comment]
Hi @kprasad99 

This is a side effect of refresh tokens I guess. If you use refresh tokens, even though you logged out on the server, the second app still has a valid refresh token and will auto login. Only workaround for this is to use some type of local storage event to inform the second app in the tabs that it should remove it's refresh token, or if you could invalidate all refresh tokens of the server for this user. Both are a bit messy...

Greetings Damien

**Comment by kprasad99** [comment]
I've not enabled refresh token, below is my configuration.

```
{
    "generateBaseUrl": "false",
    "baseUrl": "",
    "appPrefix": "",
    "stsServer": "http://192.168.56.121:18080/auth/realms/universal",
    "redirectUrl": "http://192.168.56.121:4200/",
    "clientId": "kp_appstore",
    "responseType": "code",
    "scope": "openid profile email",
    "postLogoutRedirectUri": "http://192.168.56.121:4200/#/sign-out",
    "startCheckSession": "true",
    "silentRenew": "true",
    "silentRenewUrl": "http://192.168.56.121:4200/assets/silent-renew.html",
    "renewTimeBeforeTokenExpiresInSeconds": 30,
    "postLoginRoute": "/home",
    "forbiddenRoute": "/forbidden",
    "unauthorizedRoute": "/unauthorized",
    "logLevel": "0",
    "maxIdTokenIatOffsetAllowedInSeconds": "60",
    "historyCleanupOff": "true",
    "autoUserinfo": "true",
    "disableIatOffsetValidation": "false"
}
```

Is `refresh token` enabled by default?

**Comment by damienbod** [comment]
no refresh is not enabled by default. The logout will work using the checksession with tabs in the browser and when same site or the browser does not block this. The http Config example is a working example.

Greetings Damien

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25303 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] [Help]How to perform Single Sign Out (#1054)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25303>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________

**Comment by kprasad99** [comment]
@damienbod Thanks alot. It did work. Now single sign out works.

**Comment by RiyaDwiv** [comment]
Hi @kprasad99 I need your help I am struggling with single sign out and not getting any proper solution. Can you plz tell what exactly you did for logout.
