### ISSUE TITLE
[HELP] Example or documentation for Silent Renew Code Flow with PKCE with refresh tokens

### ISSUE THREAD

**Issue by ColeSiegelTR** [damienbod/angular-auth-oidc-client#1055]
**Is your feature request related to a problem? Please describe.**
I am trying to use Silent Renew Code Flow with PKCE with refresh tokens.

Using configuration below I notice that if I refresh the page then a silent renew periodic check begins, after this time a new access token is retrieved. I am trying to determine how I can get `id_token` JWT using the `access_token`.

```    
oidcConfigService.withConfig({
      stsServer: server,
      authWellknownEndpoint: wellKnownEndpoint,
      redirectUrl: window.location.origin,
      postLogoutRedirectUri: window.location.origin,
      clientId: clientId,
      scope: 'openid profile email',
      responseType: 'code',
      useRefreshToken: true,
      renewTimeBeforeTokenExpiresInSeconds: 10,
      silentRenew: true,
      silentRenewTimeoutInSeconds: 20,
      logLevel: LogLevel.Debug,
      postLoginRoute: knownUser ? 'home' : 'documentation'
    });
```

**Describe the solution you'd like**
If there is any example or documentation about how the library suggest to use Silent Renew Code Flow with PKCE with refresh tokens it would be very helpful, on this page it does not have any example: https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/silent-renew.md#silent-renew-code-flow-with-pkce-with-refresh-tokens

**Describe alternatives you've considered**
I need ID token provided in every request to my back-end API, and I don't want the user to have to re-authenticate when the ID token expires. I considered using https://github.com/manfredsteyer/angular-oauth2-oidc library instead because documentation seems more thorough, but I would rather not have to re-do what is already working.

**Additional context**
The authentication server is PingID, please note I don't have access to `offline_access` scope and want to avoid iframe solutions.

**Comment by damienbod** [comment]
Hi @ColeSiegelTR 

Will update the docs which you linked, missed this.

Here's an example of what you want:


https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-refresh-tokens

Greetings Damien

**Comment by ColeSiegelTR** [comment]
Hey @damienbod thanks a lot for your help.

I have a question for you, I am not able to determine how to use the library to silently get a new id token once it has expired. My back end needs id token (not access token or refresh token) with full JWT claims attached. Is there a way to do that with OIDC or is it the wrong approach?

**Comment by damienbod** [comment]
The backend should NEVER use the id_token from the client. Only use access tokens in the backend or switch to BFF. The get a new id_token you have to sign-in again.

Greetings Damien

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25304 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] [HELP] Example or documentation for Silent Renew Code Flow with PKCE with refresh tokens (#1055)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25304>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________

**Comment by ColeSiegelTR** [comment]
Thank you @damienbod 

I have decided to refresh access token on client side, back end API will use access token to get information from OIDC user info endpoint, which has same info as `id_token`.

**Comment by damienbod** [comment]
fixed in V12, thanks for reporting.
