### ISSUE TITLE
Opening a child app from the parent using window.open breaks checkAuth function.

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#1056]
**Describe the bug**

Using version 11.5.0 

I have a parent app which I login in with - this uses the angular-auth-oidc-client library. Once logged in at some point in the workflow i open a second app using window.open.. the second app being opened also uses the angular-auth-oidc-client library, this second app gets redirected to the redirect page but then the auth flow stops there and the access_token is never requested. 

Looking into the console logs I see that the checkAuth function is emitting null instead of a bool like it usually does.. looking into the code from the library I could see that it is being  because of the if statement below. It seems as if this code was added as part of the support for popup auth flows, reverting the library back to version 11.4.4 (i used this version because it had a fix i needed and was before version 11.5.0) seemed to fix the issue:

`if (this.popupService.isCurrentlyInPopup()) {
      this.popupService.sendMessageToMainWindow(currentUrl);
      return of(null);
 }`

**To Reproduce**
1. Open app 1 and authorize in successfully 
2. From inside app 1 open app 2 using window.open
3. App 2 should now get stuck after redirecting back to the redirect url. (it should actually continue on to request an access_token)

**Expected behavior**
App 1 authorizes fine then I open App 2 using window.open and then App 2 should authorize succesfully.

**Comment by damienbod** [comment]
@FabianGosebrink Is this ok in V12

**Comment by damienbod** [comment]
Would it be possible to update to version 12?
