### ISSUE TITLE
Running ng test when including this library with my project throws error

### ISSUE THREAD

**Issue by softwareEngineerFTE** [damienbod/angular-auth-oidc-client#1057]
I have included the angular-auth-oidc-client package version of 11.6.6. 

When I try to run the ng test of my application after integrating with package library (code flow PKCE Auto login) i get the below error.

I have used the same code structure for Forbidden component (https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-auto-login/src/app/forbidden)

NG TEST error

NullInjectorError: R3InjectionError (DynamicTestModule)[OidcSecurityService -> CheckSessionService -> CheckSessionService]: NullInjectorError: No provider for CheckSessionService!
error properties: Object ({ ngTempTokenPath: null, ngTokenPath: ['OidcSecurityService', 'CheckSessionService', 'CheckSessionService'] });
at <Jasmine>

I'm not referring to CheckSessionService anywhere in my code. 

Also I see in your github code even though you have added OidcSecurityService as a constructor in the component.ts file you are not referring it as a provider in the component.spec.ts. Strange of how the test cases are getting passed.

Can you please tell me how to fix this issue?

**Comment by FabianGosebrink** [comment]
Do you have a sample repo with a minimal failing test to reproduce the error?

**Comment by softwareEngineerFTE** [comment]
Hi,

PFA the file attached below. Please change the stsServer to your own url to run the application on your local and then run the ng test.

**Comment by softwareEngineerFTE** [comment]
Hi Team,

Any update on the above question? Are you able to reproduce the error on your end from the sample code?

Awaiting your response.

**Comment by FabianGosebrink** [comment]
Have you added the `AuthModule` to the imports in your Testbed when executing the tests?

**Comment by softwareEngineerFTE** [comment]
Hi Fabian,

Below is the code snippet

import { TestBed, waitForAsync } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';
import {AuthModule, OidcSecurityService} from 'angular-auth-oidc-client';
import { CheckSessionService} from 'angular-auth-oidc-client/lib/iframe/check-session.service';

describe('AppComponent', () => {
  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        AuthModule
      ],
      declarations: [
        AppComponent
      ],
      providers: [
        OidcSecurityService,
        CheckSessionService
      ]
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });
});


If I add AuthModule to the imports then I get error

NullInjectorError: R3InjectorError(DynamicTestModule)[OidcSecurityService -> CheckSessionService -> CheckSessionService]: NullInjector: No Provider for CheckSessionService!

When I add the CheckSessionService as a provider in the TestBed then I get below error

Module not found: Error Can't resolve 'angular-auth-oidc-client/lib/iframe/check-session.service' in 'c:/auth/src/app'.

**Comment by FabianGosebrink** [comment]
Try `AuthModule` --> `AuthModule.forRoot()`

**Comment by FabianGosebrink** [comment]
Did that solve the issue?

**Comment by softwareEngineerFTE** [comment]
Hi Fabian,

Yes, this solved the issue. Thanks for the help. Appreciate it! :)

**Comment by jogaec22** [comment]
> Try `AuthModule` --> `AuthModule.forRoot()`

Works for me, thanks.
