### ISSUE TITLE
silent renew url changed to secureRoute

### ISSUE THREAD

**Issue by hade94** [damienbod/angular-auth-oidc-client#1059]
**Describe the bug**
Hi,
i have noticed a strange behaviour in my angular app regarding silent renew. After some time the library seems to query the wrong url (the protected api) for the silent-renew checks insead of the configured silent renew url. The STS backend is a selfhosted identityserver4. My protected API is a .NET 5 Web API. I am also using the AutoLoginGuard in my routes.

my auth-config.module.ts

export function configureAuth(oidcConfigService: OidcConfigService): () => Promise<any> {
  return () =>
    oidcConfigService.withConfig({
      stsServer: 'https://sts.xx.xx.io',
      redirectUrl: 'http://localhost:4200',
      clientId: 'client',
      scope: 'openid profile customscopeoffline_access', // 'openid profile offline_access ' + your scopes
      responseType: 'code',
      silentRenew: true,
      renewTimeBeforeTokenExpiresInSeconds: 30,
      secureRoutes: ['https://localhost:44367'],
      logLevel: LogLevel.Error,
      silentRenewUrl: `http://localhost:4200/silent-renew.html`,
      startCheckSession:true
    });
}

my app-routing.module.ts

const routes: Routes = [
  {
    path: 'jobs',
    component: JobsComponent,
    canActivate: [AutoLoginGuard],
    canLoad: [AutoLoginGuard],
    loadChildren: () => JobsModule,
    resolve: { customers: JobsResolver },
  },
  { path: 'login', component: LoginComponent, canActivate: [AutoLoginGuard], canLoad: [AutoLoginGuard], },
  { path: 'settings', component: SettingsComponent, canActivate: [AuthGuard], canLoad: [AutoLoginGuard], },
  { path: 'logout', component: LogoutComponent, canActivate: [AutoLoginGuard], canLoad: [AutoLoginGuard], },
  { path: 'forbidden', component: UnauthorizedComponent },
  { path: 'unauthorized', component: UnauthorizedComponent },
  { path: '', redirectTo: '/jobs', pathMatch: 'full'},
];

@NgModule({
  imports: [RouterModule.forRoot(routes, { enableTracing: false })],
  exports: [RouterModule],
})
export class AppRoutingModule {}`

![image](https://user-images.githubusercontent.com/60658900/115708370-307b8c80-a370-11eb-9eeb-631a82157509.png)

**Comment by inloox-dev** [comment]
+1

**Comment by FabianGosebrink** [comment]
Do you have a sample repo for us to reproduce the issue? You can take one of the configs from the samples if you want.

**Comment by hade94** [comment]
`            "assets": [
              "src/silent-renew.html"

            ],`
was missing from angular.json
