### ISSUE TITLE
How to handle 302 to login page within the silent_renew iframe

### ISSUE THREAD

**Issue by stevenvegt** [damienbod/angular-auth-oidc-client#106]
Hi, thanks for this great library! I'm new to OpenID connect and need a bit of help implementing it in my app:

I use the silent renew iframe to renew the openid_token. When the session on the identity server becomes invalid the url automaticaly redirects the browser to the login form, and this happens to the iframe as well. However, the iframe cannot render the page since it is not allowed to be rendered in an iframe. This seems ok to me, but the lib does not handle this error and the following entries appear in the console:

``` 
IsAuthorized: id_token isTokenExpired, start silent renew if active
angular-auth-oidc-client.es5.js:470 BEGIN refresh session Authorize
angular-auth-oidc-client.es5.js:470 RefreshSession created. adding myautostate: 15085048679670.7074999387748764
angular-auth-oidc-client.es5.js:470 startRenew for URL:http://localhost:3000/oauth/authorize?client_id=webclient&redirect_uri=http://localhost:4200&response_type=id_token%20token&scope=openid%20email&nonce=N0.123&state=123
1:1 Refused to display 'http://localhost:3000/accounts/sign_in' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

Do I use the renew method correct, of should my server respond in a different way?

**Comment by adriangarzas** [comment]
I also would like to know how to handle this scenario, do you have any update? @stevenvegt @damienbod

**Comment by damienbod** [comment]
The HTTPS header blocks X-Frame-Options. If you want to use the silent renew, you need to allow this on your server. (just for local clients) You can do this with CSP.

Greetings Damien

**Comment by Benji-Yarmand** [comment]
@damienbod 
Thanks for your answer. Would you please illustrate how to "allow this on my server"?
I'm using IdSrv3.

**Comment by jlouros** [comment]
@Benji-Yarmand I have exactly the same issue. Reading this comment from one of IdentityServer3 authors https://github.com/IdentityServer/IdentityServer3/issues/2764#issuecomment-219672498 it seems there is a way to use an iframe without rendering HTML. I never heard of this before, so I'm still trying to figure out how that would work.

**Comment by damienbod** [comment]
Can I close this?

**Comment by stevenvegt** [comment]
Hi @damienbod, I understand if you want to clean up your issue list, this is not really a issue with the lib and has more to do with documentation.

To reply on your answer, changing the header might fix the `Refused to display 'http://localhost:3000/accounts/sign_in' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` error. But I do not want any browser to render my login page in an I frame. This can introduce security problems. So when I asked this question I was hoping you could tell me a little bit more on how to use the silent renew iframe and how a server should behave in order for this to work.
You can deside for yourself if this explanation is a job for a library developer, or the user of the lib (me) should do its homework and read the protocol ;).

**Comment by damienbod** [comment]
@stevenvegt thanks, good idea, would you like to do a PR and add this to the docs?

**Comment by stevenvegt** [comment]
Well, if I knew the answer I would ;) But havan't it figured out yet. Currently I do not use the silent_renew feature.

**Comment by Benji-Yarmand** [comment]
Yep. Thanks

**Comment by damienbod** [comment]
fix: use CSP ancestors in the HTTP headers or the meta data of the html. Then remove the iFrame headers protection from the server. Only allow the same  origin and the client app to use iframes and the app has the same level of protection as with the iframe HTTPS header.

**Comment by damienbod** [comment]
Added to the readme

**Comment by jdelafon** [comment]
MDN says that [using a `<meta>` has no effect] (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Examples)
So it has to be done on the server side. The same link shows how to configure NginX for it, but what about `ng serve`? And what it the url that we should allow?
I'd happily contribute to the docs once I understand it.

**Comment by jdelafon** [comment]
For dummies like me:

- To understand why we have to do this: we are trying to allow our website to execute JS code that is located on another domain. I guess it is our provider's, e.g. https://accounts.google.com in my case? or does it refer to the JS code we put in silent-renew.html?
- Same question, but to be sure: is "the server" the one that serves the HTML + JS, or the auth provider ?
- in the first case, I would add this to the NginX config that serves my SPA:

```add_header content-security-policy: script-src 'self' 'unsafe-inline';style-src 'self' 'unsafe-inline';img-src 'self' data:;font-src 'self';frame-ancestors 'self' https://localhost:44311 https://localhost:44372 https://localhost:44352;block-all-mixed-content```

the localhost:44311, 44311, 44311 being 3 different locally served SPAs.

- then we also need to add a header to the dev server ("ng serve"), or deactivate the functionality in dev
- If it is the auth provider, I have no idea where I could add a header.
