### ISSUE TITLE
This library will supports ionic framework? 

### ISSUE THREAD

**Issue by bmadhan90** [damienbod/angular-auth-oidc-client#1061]
I am planning to convert my application to android and ios app using ionic mobile framework.

It will support ionic framework? If support can I have any sample implementation. I am struggling in login redirect to sts  from mobile . And how to redirect back to mobile app.

Thanks for this library I am using last 2 years.

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25296 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] This library will supports ionic framework? (#1061)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25296>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________
From: bmadhan90 ***@***.***>
Sent: Saturday, April 24, 2021 12:48:02 PM
To: damienbod/angular-auth-oidc-client ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [damienbod/angular-auth-oidc-client] This library will supports ionic framework? (#1061)


I am planning to convert my application to android and ios app using ionic mobile framework.

It will support ionic framework? If support can I have any sample implementation. I am struggling in login redirect to sts from mobile . And how to redirect back to mobile app.

Thanks for this library I am using last 2 years.

-

**Comment by FabianGosebrink** [comment]
HEy, thanks for this. This should work with a custom url scheme. Details are here which is for cordova, but should be similar https://offering.solutions/blog/articles/2020/09/17/securing-a-cordova-app-implemented-with-angular-using-oidc-and-oauth2/

**Comment by bmadhan90** [comment]
Thanks for quick response. Will try and update
