### ISSUE TITLE
Proposal: Rename StoragePersistanceService to StoragePersistenceService

### ISSUE THREAD

**Issue by JerrettDavis** [damienbod/angular-auth-oidc-client#1063]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a typo in the name of the service.

**Describe the solution you'd like**
Correct the spelling error, and rename `StoragePersistanceService` to `StoragePersistenceService`

**Describe alternatives you've considered**
None

**Additional context**
It's a simple spelling mistake, I'll attach a PR to correct.

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25300 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] Proposal: Rename StoragePersistanceService to StoragePersistenceService (#1063)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25300>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________
From: JD Davis ***@***.***>
Sent: Sunday, April 25, 2021 4:19:46 AM
To: damienbod/angular-auth-oidc-client ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [damienbod/angular-auth-oidc-client] Proposal: Rename StoragePersistanceService to StoragePersistenceService (#1063)


Is your feature request related to a problem? Please describe.
Not a problem, just a typo in the name of the service.

Describe the solution you'd like
Correct the spelling error, and rename StoragePersistanceService to StoragePersistenceService

Describe alternatives you've considered
None

Additional context
It's a simple spelling mistake, I'll attach a PR to correct.

-

**Comment by JerrettDavis** [comment]
See PR #1064

**Comment by damienbod** [comment]
thanks @JerrettDavis
