### ISSUE TITLE
Refresh token not working

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#1065]
Hello, I need your help. I can get the token normally after logging in with identityserver, but when the token expires and refreshes the token silently, the refresh is unsuccessful many times. The http status of the request token is cancelled. The identity server log prompts "Rejecting refresh token because it has been consumed already. Refresh token validation failed. aborting, {"ClientId":"client_angular","ClientName":null,"GrantType":"refresh_token","Scopes": null,"AuthorizationCode":null,"RefreshToken":null,"UserName":null,"AuthenticationContextReferenceClasses":null,"Tenant":null,"IdP":null,"Raw":{"grant_type":"refresh_token" ,"client_id":"client_angular","refresh_token":"***REDACTED***"},"$type":"TokenRequestValidationLog"}".

Here is my configuration: {
        "stsServer": "https://bestmovings.com/IdentityServer",
        "redirectUrl": "https://localhost:4200",
        "postLogoutRedirectUri": "https://localhost:4200",
        "clientId": "client_angular",
        "scope": "openid profile rc.scope ApiOne ApiTwo offline_access",
        "responseType": "code",
        "silentRenew": true,
        "useRefreshToken": true,
        "renewTimeBeforeTokenExpiresInSeconds": 10,
        "maxIdTokenIatOffsetAllowedInSeconds": 600,
        "disableIatOffsetValidation": true,
        "logLevel": 1
    }
Request:
![image](https://user-images.githubusercontent.com/37610470/115984256-b00b9480-a5d8-11eb-8cff-e27b9820ff0a.png)
Console log:
![image](https://user-images.githubusercontent.com/37610470/115984275-c74a8200-a5d8-11eb-8367-992f273a4968.png)
Log:
![image](https://user-images.githubusercontent.com/37610470/115984392-8606a200-a5d9-11eb-8d3d-9fc6eddc4f75.png)

Thank you.

**Comment by FabianGosebrink** [comment]
If you are heaving cancelled requests it could be that an observable fires multiple times either on your code or on our. Do you have a minimum sample project where you can reproduce the issue? You can take a config from our samples. Thanks.

**Comment by fengzhihenxs** [comment]
@FabianGosebrink  First of all thank you for your reply. Sorry, busy with other things and didn't notice the news. Here is a simple example: https://github.com/fengzhihenxs/authentication

**Comment by fengzhihenxs** [comment]
Hi, @FabianGosebrink
I was wondering if there has been any progress on this?
Thanks
