### ISSUE TITLE
OidcSecurityService changes

### ISSUE THREAD

**Issue by tarun04** [damienbod/angular-auth-oidc-client#1068]
Are these obsolete now?
`oidcSecurityService.moduleSetup`
`oidcSecurityService.onModuleSetup`

I'm not able to access it after upgrading the version from 10.0.x to 11.0.x

**Comment by damienbod** [comment]
Hi @tarun04 

here's a migration guide:

https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/migration.md

check out the examples for demos which should also help with the migration.

Greetings Damien

**Comment by tarun04** [comment]
@damienbod Thank you for the update.
