### ISSUE TITLE
Adding JSDoc comments throughout

### ISSUE THREAD

**Issue by JerrettDavis** [damienbod/angular-auth-oidc-client#1071]
**Is your feature request related to a problem? Please describe.**
It appears that while there's excellent documentation for the library, very little of the code itself has attached in-code documentation. This often requires me to look directly in the library's code to really understand what a method is doing. Implementing JSDocs throughout would allow IDE code-completion and code-hints to better help other developers.

**Describe the solution you'd like**
Add JSDocs to all publicly facing methods.

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by FabianGosebrink** [comment]
Hey, thanks for the input. Yes, I would love to do this while we want to keep the documentation to the public `OidcSecurityService` as he provides a facade as entrypoint for the library.

I would like to see this asap, so we can branch from main and do a PR from there. Would you like to help with that?

Thanks

**Comment by JerrettDavis** [comment]
I'm more than happy to start up a branch and get to documenting. I should be able to get on it here in a few hours after I wrap up my day's work.

**Comment by FabianGosebrink** [comment]
Take it easy, no rush. I can definitely review and help you with that. Thanks!
