### ISSUE TITLE
Create a sample for application-wide auto-authentication

### ISSUE THREAD

**Issue by JerrettDavis** [damienbod/angular-auth-oidc-client#1074]
**Is your feature request related to a problem? Please describe.**
It's fairly common for webapps to be internally facing, or to be accessed through some other authorized gateway. The current demos will result in errors if users attempt to expand them for application-wide security. It might be beneficial to provide demos that illustrate application-wide security without the need for landing pages or user interactions.

**Describe the solution you'd like**
The creation of a template that forces authentication immediately upon accessing the site.

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by philjones88** [comment]
I've hit this too, the demo's show a "home" page that is allowed to be viewed without logging in. I want every route to be secured.

**Comment by FabianGosebrink** [comment]
You can easily create a callback component which is open and handles the auth. This is normal in SPAs.

**Comment by damienbod** [comment]
I don't think this is required we have an example for the public route and auto-login and also docs explaining the app wide login

https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/features.md#redirect-route-from-token-server-has-a-guard

good?

**Comment by damienbod** [comment]
PS fixed in version 11.6.11
