### ISSUE TITLE
State and code parameters are not stripped, resulting in 404

### ISSUE THREAD

**Issue by nyvelius** [damienbod/angular-auth-oidc-client#1077]
I'm unsure if this is a bug, something that could be a feature, or if I'm just doing this wrong. But here is goes. :)

**Describe the bug**
`state` and `code` parameters are not stripped for Angular application, leading to router not finding routes.

**To Reproduce**
1. Open a NEW tab in a browser where we are NOT logged in.

2. Navigate to `http://localhost:4200/some-path`.

3. A GET request is sent to the STS server. 
    E.g. `https://sts-server&redirect_uri=http://localhost:4200/some-path...`

4. The STS server responds with a location matching the given `redirect_uri`, but with `code` and `state` parameters added. 
    E.g. `location http://localhost:4200/some-path?state=...&code=...`

**Expected behavior**
The code and state parameters are stripped and Angular opens the route that was given, i.e. `http://localhost:4200/some-path`.

**Actual behavior**
The code and state parameters are not stripped and as a result, the Angular router navigates to a route that include these parameters. Since they do not match any existing route, we get a 404 instead.

Note: If this is redone in an existing tab where we are already logged in, everything works correctly.

**Additional context**

```
  "dependencies": {
    "@angular/core": "~11.0.5",
    "angular-auth-oidc-client": "11.6.6",
    ...
  },
```

```
ngOnInit() {
  // AppComponent
  this.auth.checkAuth();
}

```

**Comment by FabianGosebrink** [comment]
Hey,

**Comment by FabianGosebrink** [comment]
Can you subscribe to the output of `checkAuth`? This is an observable. Please check the samples for sample code. Thanks!

**Comment by nyvelius** [comment]
Sure, here's a slightly refactored version of the code.

```
export class AppComponent implements OnInit {

  constructor(
    private auth: OidcSecurityService,
  ) {
  }

  async ngOnInit() {
    let isAuthenticated = await this.auth.checkAuth().toPromise();
    console.log('Is authenticated', isAuthenticated);
    if (!isAuthenticated) {
      this.auth.authorize();
    }
  }
}
```

And the console output:

```
Is authenticated false 
Is authenticated true
```

The network HTTP traffic displays:

```
304 GET http://localhost:4200/path
302 GET https://sts-server/redirect_uri=http://localhost:4200/path
200 GET http://localhost:4200/path**?state=...&code=...**
```

**Comment by nyvelius** [comment]
Hi again

I think I found the issue and OIDC seems to be working as it should. 

In case anyone else runs into this, the issue seems to be caused by the rapid firing of two navigation events. The first navigation event is triggered and awaits for authentication to finish. This is done by using a `ReplaySubject` as an observable that fires when `oidcSecurityService.checkAuth()` returns true. 

Before this event has finished, a second navigation event is triggered. This time to the same url but with state and code added. This event is declined, from my understanding because the first event hasn't finished.

```
// isAuthenticated is a ReplaySubject returned as an observable
return this.auth.isAuthenticated
    .pipe(
        take(1),
        map((isAuthenticated: boolean) => {
            // auth logic
        })
    );
```

```
// Activating trace logs in the router module
@NgModule({
  imports: [
    RouterModule.forRoot(routes, {enableTracing: true})
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {
}
```

```
// Navigation events
Router Event: NavigationStart
	url: '/some-path'

Router Event: NavigationStart
	url: '/some-path?state=...&code=...'

Router Event: NavigationCancel
	url: '/some-path?state=...&code=...'
	reason: Navigation ID 1 is not equal to the current navigation id 2
```
