### ISSUE TITLE
The value for storageSilentRenewRunning is the only value is that converted to a JSON string before storage; all other values are stored as objects

### ISSUE THREAD

**Issue by Kevat** [damienbod/angular-auth-oidc-client#1081]
**Describe the bug**
The value for storageSilentRenewRunning is the only value is that converted to a JSON string before storage; all other values are stored as objects. When writing custom storage of type AbstractSecurityStorage, we need to account for empty strings since storageSilentRenewRunning's value is set to be an empty string on flows-data.service.ts on line 94.

**To Reproduce**

1. Create your own Storage which reads and writes to session or local storage. Given below is an example
```
import { Injectable } from '@angular/core';
import { AbstractSecurityStorage } from 'angular-auth-oidc-client';

@Injectable()
export class CustomTokenStorage implements AbstractSecurityStorage {

    public read(key: string): any {
        var valueStr;
        valueStr = sessionStorage.getItem(key);

        if (!valueStr)
        {
            return null;
        }
        return JSON.parse(valueStr);
    }

    public write(key: string, value: any): void {
        sessionStorage.setItem(key, JSON.stringify(value));
    }

    public remove(key: string): void {
        localStorage.removeItem(key);
    }
}
```

2. Set the storage for the AuthModule as shown below:
```
@NgModule({
  imports: [AuthModule.forRoot({ storage: CustomTokenStorage })],
```

3. Enable Silent Renew, login, and track the errors shown in the Browser JavaScript Console. An error will be thrown on Line 62 of flows-data.service.ts

**Expected behavior**
There should be no errors when reading from or writing to custom storage.

**Screenshots**
![image](https://user-images.githubusercontent.com/9504224/116733211-d145f980-a9b9-11eb-8841-cc9b9a512e12.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 90.0.4430.93

**Smartphone (please complete the following information):**
None

**Additional context**
Fixing lines 62, 90, 94 of flows-data.service.ts should resolve this issue

**Comment by Kevat** [comment]
In flows-data.service.ts
Line 62 is:
`const storageObject = JSON.parse(this.storagePersistenceService.read('storageSilentRenewRunning'));`

should be:
`const storageObject = this.storagePersistenceService.read('storageSilentRenewRunning');`


Line 90 is:
`this.storagePersistenceService.write('storageSilentRenewRunning', JSON.stringify(storageObject));`

should be:
`this.storagePersistenceService.write('storageSilentRenewRunning', storageObject);`


Line 94 is:
`this.storagePersistenceService.write('storageSilentRenewRunning', '');`

should be"
`this.storagePersistenceService.write('storageSilentRenewRunning', null);`

**Comment by damienbod** [comment]
@Kevat we had to revert the fix for this because the fix here broke the silent renew. We will look at this and fix it next.

**Comment by Kevat** [comment]
Thank you for the quick fixes!!

**Comment by FabianGosebrink** [comment]
This is fixed in V12 as we re-implemented parts of the storage mechanism.
