### ISSUE TITLE
The ****_storageSilentRenewRunning always returns empty string

### ISSUE THREAD

**Issue by tarun04** [damienbod/angular-auth-oidc-client#1084]
The application keeps running into this issue.

![image](https://user-images.githubusercontent.com/14960107/116953988-b34bf380-ac5c-11eb-9aa0-af345ad20ae7.png)

Config settings:
![image](https://user-images.githubusercontent.com/14960107/116954227-5ef54380-ac5d-11eb-95a9-f8c18a6ac830.png)

It is not working even when the silentRenew is set to true

**Comment by damienbod** [comment]
@tarun04 Can you give us some more information?

What version do you use?

Is this a new problem or have you always had it?

You don't use silent renew looking at your configuration, correct?

Greetings Damien

**Comment by damienbod** [comment]
@tarun04  This is broken in version 11.6.7, As a temp workaround you can use version 11.6.6

I will revert this and create a new version 11.6.8

**Comment by tarun04** [comment]
> What version do you use?

I'm on version 11.6.6.

> Is this a new problem or have you always had it?

It's a new problem, it's been a while I worked on this part.

> You don't use silent renew looking at your configuration, correct?

I tried with silent renew enabled as well, no difference.

**Comment by damienbod** [comment]
Now I'm confused, this should work for 11.6.6

**Comment by tarun04** [comment]
And also I get the warning, I passed custom storage as mentioned in the docs.
`AuthModule.forRoot({ storage: CustomStorage }),`

![image](https://user-images.githubusercontent.com/14960107/117040726-2c3c6100-acd8-11eb-9e4d-429a5458beb2.png)

Am I doing something wrong here? I compared with the code examples, seems similar.
