### ISSUE TITLE
ValidateStateFromHashCallback failed, local_state null

### ISSUE THREAD

**Issue by RobertHajbok** [damienbod/angular-auth-oidc-client#1087]
**Describe the bug**
Hey guys! I have a similar issue to [this](https://github.com/damienbod/angular-auth-oidc-client/issues/920), it's happening only on the live website and only sometimes, when I get back to the callback page. On localhost, everything is perfect every single time. I've tried implementing cookie storage instead of session storage, in that case I get the error below on localhost as well, every single time. Any idea why this might happen? Let me know if you need any other details.

**Screenshots**
![Error](https://user-images.githubusercontent.com/5830487/117481479-f824a280-af5a-11eb-828d-2dc82c1afe81.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Chrome

**Comment by damienbod** [comment]
Incorrect state usually happens when you reset the state from your code, or you send two auth requests at the same time for the same client_id
