### ISSUE TITLE
Convert all instances of "Authorized" to "Authenticated"

### ISSUE THREAD

**Issue by JerrettDavis** [damienbod/angular-auth-oidc-client#1088]
**Is your feature request related to a problem? Please describe.**
Traditionally, `authorized` and `authenticated` have been used interchangeably, but they stand for two distinct concepts. As this library deals with authentication, I propose that all instances of the term `authorized` be replaced with `authenticated` throughout the library.

**Describe the solution you'd like**
Find and replace all instances of `authorized` with `authenticated`, and update the documentation and migration docs.

**Describe alternatives you've considered**
_NONE_

**Additional context**
_NONE_

**Comment by damienbod** [comment]
Implemented, will be release in V12
