### ISSUE TITLE
Steam OpenID Connect to obtain Steam ID?

### ISSUE THREAD

**Issue by endigo9740** [damienbod/angular-auth-oidc-client#109]
FYI I'm familiar with oAuth 2.0 but new to OpenID.

I'm hoping to use this library to access a user's Steam ID via OpenID Connect. However, I'm a bit confused on configuration. Following the quickstart guide I see we (potentially) need credentials and keys like: redirect_url, client_id, scope, etc.

All I see is the "Steam's OP Endpoint URL" of https://steamcommunity.com/openid/ and a way to generate a unique API key via my domain. That's it, everything else requires the Steam ID to proceed. Is this all I need to configure in my App Module? If so what keys should I set? Something like:

openIDImplicitFlowConfiguration.stsServer = 'https://steamcommunity.com/openid/';
openIDImplicitFlowConfiguration.client_id = `${steam-api-key}`;

That doesn't seem right, especially using an API key in place of a Client ID. Any help would be most appreciated!

**Comment by damienbod** [comment]
@endigo9740 if the steamcommunity.com/openid supports the OpenID Connect Implicit flow, you just need to configure the client API with the required Implict Flow configurations.  I have not found any docs about the steamcommunity.com/openid

Greetings Damien

**Comment by endigo9740** [comment]
@damienbod Yeah the documentation is very frustrating. It makes several references to what you should be doing, but very little on how to actually do so. They link to official OpenID Connect libraries (including this one) but don't provide any of the credentials it seems you'll actually need, or links to sources that would provide them. I do appreciate the help all the same though.

**Comment by endigo9740** [comment]
We've opted to handle this via our backend server instead. Closing the issue.

**Comment by damienbod** [comment]
@endigo9740 ok, but does an OpenID provider exist? I was checking around, and could not find anything.

**Comment by Trojaner** [comment]
@damienbod now it does: https://github.com/ImperialPlugins/SteamOpenIdConnectProxy
