### ISSUE TITLE
Store tokens in session storage and check if user is still logged in on load

### ISSUE THREAD

**Issue by Kevat** [damienbod/angular-auth-oidc-client#1090]
**Is your feature request related to a problem? Please describe.**
Currently, tokens are stored in local storage. When the user opens a new tab or closes their browser and opens the site again later, the user is not logged in as far as the oidc client is concerned. However, the user is logged in with the identity provider.

**Describe the solution you'd like**
The client should store tokens in session storage and validate that the access and refresh tokens are valid on load. This would let our Angular client know whether or not the user is logged in without having to click the login button. The auto login feature does not suffice here as it forces a redirect to the identity provider if the user is not logged in and also does not work across multiple tabs. The OIDC client would store and retrieve tokens from session storage, try to log the user in on load if tokens exist, and should not redirect to the login page if the user is not logged in at the identity provider. Maybe this entire functionality, as well as the ability to use session storage instead of local storage should be controlled via settings in the OpenIdConfiguration class.

**Describe alternatives you've considered**
I've been able to create my own storage and store tokens in Session Storage. I am considering building out a "IsLoggedIn" point within my Identity provider which I can call using the access token stored in Session Storage to see if the user is logged in. I am also considering mimicking the silent renew code/iFrame for this purpose, but that seems complicated.

**Additional context**
This seems like critical functionality; many sites allow users to remain logged in. Forcing a user to click the login button each time seems like a major drawback, specially if the user has clicked the "Keep me logged in" checkbox when logging in to the identity provider.

**Comment by damienbod** [comment]
Hi @Kevat  The tokens are stored per default in session storage

Greetings Damien

**Comment by fritzwf** [comment]
What was the outcome of this issue?  I am facing the exact thing when a user opens a new tab, and they have to click the login button to login, yet they are already logged-in on their browser.

Regards,
-Fritz
