### ISSUE TITLE
Will be there suport for 'TargetResource' parameter in 'createEndSessionUrl()' function ?

### ISSUE THREAD

**Issue by Liskron** [damienbod/angular-auth-oidc-client#1092]
Hello, I am looking for a possibility to add support for **PingIdentity** standard. To use the PostLogoutRedirectURL parameter, we need to change the parameter name: `TargetResource` instead of `post_logout_redirect_uri`. 

There is a peace of code what I have found in your library ([file](https://github.com/damienbod/angular-auth-oidc-client/blob/b5c16549efb4ad8cb402a2b9d7a4738bca44ce08/projects/angular-auth-oidc-client/src/lib/utils/url/url.service.ts#L95)) : 
```javascript
createEndSessionUrl(idTokenHint: string): string {
    const authWellKnownEndPoints = this.storagePersistanceService.read('authWellKnownEndPoints');
    const endSessionEndpoint = authWellKnownEndPoints?.endSessionEndpoint;

    if (!endSessionEndpoint) {
      return null;
    }

    const urlParts = endSessionEndpoint.split('?');

    const authorizationEndsessionUrl = urlParts[0];

    let params = new HttpParams({
      fromString: urlParts[1],
      encoder: new UriEncoder()
    });
    params = params.set('id_token_hint', idTokenHint);

    const postLogoutRedirectUri = this.getPostLogoutRedirectUrl();

    if (postLogoutRedirectUri) {
      params = params.append('post_logout_redirect_uri', postLogoutRedirectUri);
    }

    return `${authorizationEndsessionUrl}?${params}`;
  }
```

Documentation to PingIdentity [TargetResource ](https://docs.pingidentity.com/bundle/pingfederate-102/page/edg1564003024358.html) parameter in logout process.
Are there any chances for such functionality? Of course, I can help and create a PR

**Comment by damienbod** [comment]
Add custom params to support this:

https://github.com/damienbod/angular-auth-oidc-client/pull/1093

**Comment by Liskron** [comment]
@damienbod Thanks a lot!

**Comment by damienbod** [comment]
thanks, release in version 11.6.9
