### ISSUE TITLE
checkAuthIncludingServer stalling/timeout

### ISSUE THREAD

**Issue by stephenlautier** [damienbod/angular-auth-oidc-client#1094]
**Describe the bug**
Occasionally, when refreshing the page and the token has expired it seems that `checkAuthIncludingServer` never completes, and timeout instead (see screenshots).

Not sure if we miss any config, any indication why this might happen please?

**Screenshots**
#### fail
This is a sample of the log when it fails
![image](https://user-images.githubusercontent.com/3908723/118518654-a4733f80-b738-11eb-802f-50386248c51d.png)

#### succeed
This is a sample of the log when it succeeds
![image](https://user-images.githubusercontent.com/3908723/118519039-092e9a00-b739-11eb-97d5-6701113da766.png)

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser: chrome
 - Version 90

**Additional context**
My configuration looks something like this

![image](https://user-images.githubusercontent.com/3908723/118520955-d08fc000-b73a-11eb-8337-5cd1e02c9084.png)

**Comment by stephenlautier** [comment]
Trying to debug a bit this maybe it helps

From what i understand;

- `checkAuth` is invoked
- eventually it ends up in [refresh-session.service.forceRefreshSession](https://github.com/damienbod/angular-auth-oidc-client/blob/7c31fc9ba3baed05f5f2fc0f8ab309301ee2c1c0/projects/angular-auth-oidc-client/src/lib/callback/refresh-session.service.ts#L55)
- In the `forkJoin` - `this.silentRenewService.refreshSessionWithIFrameCompleted$.pipe(take(1)),` never completes

Dug a bit around that
- The above completes when [SilentRenewService.silentRenewEventHandler](https://github.com/damienbod/angular-auth-oidc-client/blob/6e4fa96de4bc3c744e8d958b6100b0caef5f8149/projects/angular-auth-oidc-client/src/lib/iframe/silent-renew.service.ts#L101) is triggered
- That gets triggered via `'window', 'oidc-silent-renew-message'`  [from here](https://github.com/damienbod/angular-auth-oidc-client/blob/e2afe98646951f3b808e2f8bf9ab9dbe804e0265/projects/angular-auth-oidc-client/src/lib/iframe/refresh-session-iframe.service.ts#L55)
- And it seems that the reason that its not triggering because[ the handler above is destroying it](https://github.com/damienbod/angular-auth-oidc-client/blob/e2afe98646951f3b808e2f8bf9ab9dbe804e0265/projects/angular-auth-oidc-client/src/lib/iframe/refresh-session-iframe.service.ts#L51) (in this specific case)

What seems wrong to me the event listener will be removed from the window, so not just that specific instance, but all will be removed. So i think the handler for the `oidc-silent-renew-message` should be destroyed only after its consumed (and maybe on a timeout so it doesnt keep hanging if nothing is received)


![image](https://user-images.githubusercontent.com/3908723/121199995-ab8ef880-c873-11eb-87c4-3a24cb31c9d7.png)

**Comment by damienbod** [comment]
Would it be possible to update to version 12?

**Comment by stephenlautier** [comment]
Yes (not right now) but unless there are huge breaking changes should be able to. Was there a fix for this?

**Comment by damienbod** [comment]
don't know :) We have a lot of changes here :)

Greetings Damien

**Comment by damienbod** [comment]
Closing this as Angular is now V13
