### ISSUE TITLE
Angular 12 Support

### ISSUE THREAD

**Issue by PartyArk** [damienbod/angular-auth-oidc-client#1096]
Angular 12 is out now, official support would be appreciated. I would be surprised if any code needed changing.

Thank you!

**Comment by damienbod** [comment]
Implemented, will be release in V12

**Comment by busilina** [comment]
When will v12 be released?

**Comment by damienbod** [comment]
@busilina should be soon, we still need to complete the testing and update some docs, then it's ready. We are feature complete now.

**Comment by GarethBlain** [comment]
Where can we watch for the V12 release? All the V12 update issues are closed yet V12 isn't released.
I can't even find a branch or PR for it to monitor.
Would be nice to be able to subscribe to something for updates on this issue. :)

**Comment by 123niel** [comment]
I would really apreceate that!

**Comment by damienbod** [comment]
Hi @GarethBlain @123niel  We hope to be finished by the weekend

- testing the migration now
- validating the docs

Greetings Damien

**Comment by garvraj** [comment]
Do we have a callback kind of method to check for successful login that should only be invoked once we get the token or after successful login
