### ISSUE TITLE
Unable to add AutoLoginGuard to all routes

### ISSUE THREAD

**Issue by LiuCypher** [damienbod/angular-auth-oidc-client#1098]
**Describe the bug**
Problem occured on sample-code-flow-auto-login.
When we try to add an AutoLoginGuard to the home component, the browser starts an infinite loop of redirections.

**To Reproduce**
in app.routes.ts
line 10

Replace the line 
`{ path: 'home', component: HomeComponent }`
by
`{ path: 'home', component: HomeComponent, canActivate: [AutoLoginGuard] },`

**Expected behavior**
After a single redirection to the STS, landing on the home component as a authenticated user.

**Desktop**
 - OS: Win10
 - Browser: Chrome
 - Version 90.0.4430.212 (64 bits)

**Additional context**
We are trying to build an app where the users are auto-logged in, but with an implicit flow. Seeing aproximately the same behavior as described, we tried to modify the sample-code-flow-auto-login to fit our specs. 
(could not find auto-login in implicit flow context)

**Comment by FabianGosebrink** [comment]
Closing as related to #1052

**Comment by LiuCypher** [comment]
Thank's!
Will look into it.
