### ISSUE TITLE
Redirecting to STS many times before login (autologin and refresh token)

### ISSUE THREAD

**Issue by ebinroy** [damienbod/angular-auth-oidc-client#1099]
**Angular client sometimes failed to connect and trying multiple times before forwarding to the login as below. This error is not happening all times. Sometimes only.** 

I used your example to connect with [Code Flow PKCE with Refresh tokens](https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-refresh-tokens)

**Auth-module**
```
export function configureAuth(oidcConfigService: OidcConfigService) {
    let basePath =  getBasePath();
  
    debugger;
    return () =>
      
      oidcConfigService.withConfig({
        stsServer: environment.STSUrl, 
        redirectUrl: window.location.origin + ((basePath == "") ? '': "/" + basePath),
        
  
        clientId: 'TestClient',
        scope: 'openid profile api1 offline_access family api2 TestIdentityResource',
  
        responseType: 'code',
        postLogoutRedirectUri: "http://localhost:4200/#/dashboard",
  
        silentRenew: true,
        useRefreshToken: true,
        
        logLevel: LogLevel.Debug,
        
        //add custom parameters
        customParams: {
          resellerid: basePath,        
        },
      });
  }
  
  export function getBaseLocation() {
    debugger;
    console.log("location --> " , location );
    let paths: string[] = location.pathname.split('/').splice(1, 1);
    let basePath: string = (paths && paths[0]) || ''; // Default route can be give instead of ''
    return '/' + basePath;
  }

  function getBasePath() {
    debugger;
    console.log("location --> " , location );
    let paths: string[] = location.pathname.split('/').splice(1, 1);
    let basePath: string = (paths && paths[0]) || ''; // Default route can be give instead of ''
    return basePath;
  }


@NgModule({
  imports: [AuthModule.forRoot()],
  providers: [
    OidcConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: configureAuth,
      deps: [OidcConfigService],
      multi: true,
    },
    { 
        provide: APP_BASE_HREF, 
        useFactory: getBaseLocation
      },
  ],
  exports: [AuthModule],
})
export class AuthConfigModule {}
```
**App.component**
```
ngOnInit() {

    this.authservice.IsAuthenticated$.subscribe( data => {
      this.isAuthenticated = data;
      if(data){
        this.tokenservice.TokenValue(this.tokenservice.getToken() + "","role"); 

        let clientId = this.oidcSecurityService.configuration.configuration.clientId
        console.log("clientId =" , clientId);

        this.title = "Client-" + sessionStorage.getItem("clientangularSLO_storageCustomRequestParams");
        console.log("Title =" , this.title);
        
      }
    });

  }

```
**failed one**
_https://localhost:5001/connect/authorize?client_id=TestClient&redirect_uri=http%3A%2F%2Flocalhost%3A4200&response_type=code&scope=openid%20profile%20api1%20offline_access%20family%20api2&nonce=edec660bb500dbf8216aac4de72f69daedSTq4mE1&state=ae9917768ccf48c4d8e9a3b3b23e81636f4VoriRF&code_challenge=HMACjmBZwvZa2Mt4Jf3zFnzrQNhrJIs-3GDu9yHpwcw&code_challenge_method=S256&resellerid=

_https://localhost:5001/connect/authorize?client_id=TestClient&redirect_uri=http%3A%2F%2Flocalhost%3A4200&response_type=code&scope=openid%20profile%20api1%20offline_access%20family%20api2&nonce=676ccdb090e89f99244c53c93b33770bc4BbDIcFD&state=ae9917768ccf48c4d8e9a3b3b23e81636f4VoriRF&code_challenge=0ftzr-oPVEtxa569-ku1ft62FJSYnw4FRHFEo1l-rFI&code_challenge_method=S256&resellerid=

**Successful one**

_https://localhost:5001/connect/authorize?client_id=TestClient&redirect_uri=http%3A%2F%2Flocalhost%3A4200&response_type=code&scope=openid%20profile%20api1%20offline_access%20family%20api2&nonce=0cb8c4d4b3cbbce07dd93b9f395e340b2ekvwtUkY&state=ae9917768ccf48c4d8e9a3b3b23e81636f4VoriRF&code_challenge=kZap-9Blix3AmzHLmPIX84cWMkbgaFgYVTiOTnRLQLY&code_challenge_method=S256&resellerid=

```
"angular-auth-oidc-client": "~11.6.6",
"@angular/common": "~11.0.1",
```
Please refer the screenshots for the details 
![IS_log](https://user-images.githubusercontent.com/45000952/118960732-2ca25080-b996-11eb-8ae7-6e7ec942abba.PNG)
![IS_log2](https://user-images.githubusercontent.com/45000952/118960763-32983180-b996-11eb-93a5-8bab75215a18.PNG)
![network1](https://user-images.githubusercontent.com/45000952/118960785-362bb880-b996-11eb-85a3-4a67fbb2dd62.png)
![network2](https://user-images.githubusercontent.com/45000952/118960798-3926a900-b996-11eb-8252-e52fad59e33a.PNG)

I tried with your example by adding below code, Even upgraded the version 11.6.9 also same issue.

{ path: 'home', component: HomeComponent , canActivate: [AutoLoginGuard]},

it also has the same issue as above post

**Comment by ebinroy** [comment]
I tried with your example by adding below code
{ path: 'home', component: HomeComponent , canActivate: [AutoLoginGuard]},

it also has the same issue as above post

**Comment by FabianGosebrink** [comment]
Closing as related to #1098
