### ISSUE TITLE
Dynamically overwrite default configuration (scope, state)?

### ISSUE THREAD

**Issue by joobacca** [damienbod/angular-auth-oidc-client#1103]
In the configuration object of the initial oidcConfigService.withConfig() method, the option scope can be omitted, according to [the configuration documentation](https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/configuration.md).

It then gets a default value (`openid email profile`), which cannot be overriden using the dynamic custom parameter option, as provided [here](https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/features.md#dynamic-custom-parameters). It IS overwritable, but both values get set and only the first one (the default value) is considered. I want to have according scopes when different buttons are clicked. Is there any possibility to achieve this?

Also, the state parameter is used by my backend to transfer data, like email or password, it seems like the it cannot be overridden either. Is my approach wrong?

**Comment by damienbod** [comment]
This will be supported in V12 using multiple IDP configurations

There is also a dynamic configuration issue here which could achieve this. We are investigating if we support this also.

https://github.com/damienbod/angular-auth-oidc-client/issues/923

closing this as we have an implemented  solution in V12

Thanks for reporting, greetings Damien
