### ISSUE TITLE
Code Flow PKCE - Code Verifier become Empty on Token Endpoint

### ISSUE THREAD

**Issue by MuraliTandabany** [damienbod/angular-auth-oidc-client#1104]
Description - I am using v10.0.15. Everything works fine until receiving Authorization code from identity server. After that OIDC library issues a token request to identity server to fetch ID & Access tokens. But the code_verifier parameter is always going as empty in that request and the flow getting failed at that stage. 

**To Reproduce**
1. Open application --> redirect to identity server login page
2. User logs in successfully
3. Identity server callback with authorization code and state
4. OIDC library issues a token request without empty code_verifier and resulting in error

**Expected behavior**
Access and ID token should be retrieved and flow should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/40332490/120460952-35901a80-c3b7-11eb-9893-a02ca2942131.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chrome 
 - Version 90.0.4430.212

**Additional context**
OAuth Configuration
 const config: OpenIdConfiguration = {
        stsServer: '{myIdentityServer}',
        redirect_url: 'http://localhost:4200/home',
        client_id: '{myClientId}',
        response_type: 'code',
        scope: 'openid SSOIntegration',
        trigger_authorization_result_event: true,
        isauthorizedrace_timeout_in_seconds: 300,
        post_logout_redirect_uri: 'http://localhost:4200/unauthorized',
        post_login_route: '/home',
        forbidden_route: '/forbidden',
        unauthorized_route: '/unauthorized'
      };

**Comment by damienbod** [comment]
Hi @MuraliTandabany This should work in v10 but I don't have the time to validate this. Could you try updating to v11? 

Also we release V12 in the next few weeks, which are new breaking changes and improvements.

**Comment by damienbod** [comment]
Hi @MuraliTandabany I'm afraid we don0t have the time to fix issues in version 10. Could you please update to version 11? We will be releasing V12 very soon as well
