### ISSUE TITLE
OidcSecurityService.logoff doesn't redirect to postLogoutRedirectUri, needs setTimeout

### ISSUE THREAD

**Issue by vytautaszGG** [damienbod/angular-auth-oidc-client#1105]
Hello!
I have encountered an issue that OidcSecurityService.logoff function does not redirect to the configured postLogoutRedirectUri after logging out. However, strangely enough, when wrapping the logoff function inside setTimeout, everything works as expected.
I suspect that for some reason without the setTimeout, the logoff function performs only the local logout as I cannot see any redirect happening to my STS. After the logout, page refreshes and user is logged out (as mentioned before, probably just locally), but stays on the same page as before logging out.

**To Reproduce**
I have a regular implicit grant setup on my Angular application.
There is nothing special going on, just a button that when pressed, calls the OidcSecurityService.logoff function. That's it.
My STS is FusionAuth, but I doubt this has anything to do with my STS configurations.

 - OS: Windows 10
 - Browser Chrome
 - Version: latest

**Comment by damienbod** [comment]
Hi @vytautaszGG I'm not sure I understand. Just validated the logoff and this works with different STS. I need more info, but I can reproduce this.

Greetings Damien
