### ISSUE TITLE
logoff results in 404

### ISSUE THREAD

**Issue by okihnjo** [damienbod/angular-auth-oidc-client#1108]
**Problem**
I am not able to logoff. Everytime I call `oidcSecurityService.logoff();`, I get a 404 error. I do have the same postLogoutRedirectUri in my Angular Application as well as in the backend. 
It's requesting the following: 
_**company_url**/Account/Logout?logoutId=CfDJ8PNw__1fDL5D ..._
So when calling `logoff()`, its making a get request to that url and than obviously, after a 404 in the browser, a blank page. No redirect, not being able to access /Account/Logout?logoutId=CfD... 
Everything else works fine.

**Expected behavior**
After calling logoff(), redirect the user to the given redirectUri and delete credentials in cookies/storage, so user has to logIn again.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50614363/120804391-e0820f00-c544-11eb-9c80-bfda030f74c2.png)

**Additional context**
I dont have access to the backend code, but if this is a server side problem, I am able to write a ticket to the responsible team. But for now I dont know if it really is because like I said everything else just works fine, hence I didnt report anything yet.

**Comment by damienbod** [comment]
Hi @okihnjo yes this looks like a server issue. The logout post redirect  url needs to be setup on the STS.
