### ISSUE TITLE
Azure AD B2C requires explicit configuration of well-known endpoints

### ISSUE THREAD

**Issue by jeffreyabecker** [damienbod/angular-auth-oidc-client#1109]
**Describe the bug**
When Utilizing Azure AD B2C as an STS, the endpoints are not correctly read from the .well-known/openid-configuration. Calling `oidcSecurityService.authorize` results in the following exceptions in the console:

`angular-auth-oidc-client.js:178 Can not create an authorize url when authorizationEndpoint is 'undefined'
logError	@	angular-auth-oidc-client.js:178
createAuthorizeUrl	@	angular-auth-oidc-client.js:1297
createUrlCodeFlowAuthorize	@	angular-auth-oidc-client.js:1408
getAuthorizeUrl	@	angular-auth-oidc-client.js:1171
(anonymous)	@	angular-auth-oidc-client.js:3871
__tryOrUnsub	@	Subscriber.js:183
next	@	Subscriber.js:122
_next	@	Subscriber.js:72
next	@	Subscriber.js:49
(anonymous)	@	subscribeToArray.js:3
_trySubscribe	@	Observable.js:42
subscribe	@	Observable.js:28
loginStandard	@	angular-auth-oidc-client.js:3869
login	@	angular-auth-oidc-client.js:3912
authorize	@	angular-auth-oidc-client.js:4115
authorize	@	user.service.ts:78
signIn	@	home-menu.component.ts:120
click	@	home-menu.component.ts:90
HomeMenuComponent_div_0_mat_grid_tile_3_Template_a_click_6_listener	@	home-menu.component.html:12
executeListenerWithErrorHandling	@	core.js:15204
wrapListenerIn_markDirtyAndPreventDefault	@	core.js:15245
(anonymous)	@	platform-browser.js:582
invokeTask	@	zone-evergreen.js:406
onInvokeTask	@	core.js:28497
invokeTask	@	zone-evergreen.js:405
runTask	@	zone-evergreen.js:178
invokeTask	@	zone-evergreen.js:487
invokeTask	@	zone-evergreen.js:1600
globalZoneAwareCallback`

 and

`Could not create url null
logError	@	angular-auth-oidc-client.js:175
(anonymous)	@	angular-auth-oidc-client.js:3873
__tryOrUnsub	@	Subscriber.js:183
next	@	Subscriber.js:122
_next	@	Subscriber.js:72
next	@	Subscriber.js:49
(anonymous)	@	subscribeToArray.js:3
_trySubscribe	@	Observable.js:42
subscribe	@	Observable.js:28
loginStandard	@	angular-auth-oidc-client.js:3869
login	@	angular-auth-oidc-client.js:3912
authorize	@	angular-auth-oidc-client.js:4115
authorize	@	user.service.ts:78
signIn	@	home-menu.component.ts:120
click	@	home-menu.component.ts:90
HomeMenuComponent_div_0_mat_grid_tile_3_Template_a_click_6_listener	@	home-menu.component.html:12
executeListenerWithErrorHandling	@	core.js:15204
wrapListenerIn_markDirtyAndPreventDefault	@	core.js:15245
(anonymous)	@	platform-browser.js:582
invokeTask	@	zone-evergreen.js:406
onInvokeTask	@	core.js:28497
invokeTask	@	zone-evergreen.js:405
runTask	@	zone-evergreen.js:178
invokeTask	@	zone-evergreen.js:487
invokeTask	@	zone-evergreen.js:1600
globalZoneAwareCallback`

and the client is not redirected to the Azure B2C login page

**To Reproduce**
Create an AzureAD B2C instance
Inside that instance create an App Registration
  
Inside that instance create a `Signup or Signin` flow

1)Create a new App Registration, In the App Registration detail page 
  a) add a redirect URI to your debugging app
  b) record the value for `Application (client) ID` for later use
  c) record the value for `Application ID URI` for later use
2) In the Azure AD B2C Console, Under Polices / User Flows click `New User Flow`
  a) Select `Signup and Sign in` and use the recomended version
  b) Enter a flow name
3) In the Azure AD B2C Console, Under Polices / User Flows go to the flow details of your new flow
  a) Click `Run User Flow` 
  b) In the pop-out select your new application in the `Application` selector
  c) record the value of the url that appears above that selector  for later use -- this is your stsServer value

4) Setup an angular app using angular-auth-oidc-client and the following openId config:
`
{
      stsServer:
        '<stsServer from 3c>',
      authWellknownEndpoint: 'https://login.microsoftonline.com/common/v2.0',
      redirectUrl: <your redirect ur from 1A>,
      clientId: <your clientId from 1b>,
      scope:
        'openid profile offline_access email <Application ID URI from 1c>',
      responseType: 'code',
      silentRenew: true,
      useRefreshToken: true,
      maxIdTokenIatOffsetAllowedInSeconds: 600,
      issValidationOff: false,
      autoUserinfo: false,
      customParams: {
        prompt: 'select_account',
      },
    }
`

**Work Around**
This problem seems to go away if I manually configure all endpoints in the openid configuration
  
**Expected behavior**
When invoking `oidcSecurityService.authorize` I expect the browser to be redirected to the azure ad b2c login page

**Desktop**
 - OS: Windows
 - Browser Chrome / Edge

**Comment by damienbod** [comment]
Hi @jeffreyabecker 

Something like this works


```
stsServer: 'https://login.microsoftonline.com/damienbod.onmicrosoft.com/v2.0',
authWellknownEndpointUrl:
  'https://damienbod.b2clogin.com/damienbod.onmicrosoft.com/B2C_1_b2cpolicydamien/v2.0/.well-known/openid-configuration',
redirectUrl: window.location.origin,
postLogoutRedirectUri: window.location.origin,
clientId: 'f1934a6e-958d-4198-9f36-6127cfc4cdb3',
scope: 'openid https://damienbod.onmicrosoft.com/testapi/demo.read',
responseType: 'code',
silentRenew: true,
autoUserInfo: false,
silentRenewUrl: window.location.origin + '/silent-renew.html',
logLevel: LogLevel.Debug,
renewTimeBeforeTokenExpiresInSeconds: 60,
// useRefreshToken: true, // for refresh renew, but revocation and one time usage is missing from server impl.
// ignoreNonceAfterRefresh: true,
// disableRefreshIdTokenAuthTimeValidation: true,
customParamsAuthRequest: {
  prompt: 'select_account', // login, consent
},
```

Would this work for you?

Greetings Damien

PS In V12 we plan support for multiple B2C policies

**Comment by jeffreyabecker** [comment]
I have not been able to make that work by simply replacing the appropriate client id, Azure AD Tenant Name and scope as such:
```
stsServer: 'https://login.microsoftonline.com/myvaccinepassport.onmicrosoft.com/v2.0',
authWellknownEndpointUrl:
  'https://myvaccinepassport.b2clogin.com/myvaccinepassport.onmicrosoft.com/B2C_1_DevClientApp/v2.0/.well-known/openid-configuration',
redirectUrl: window.location.origin,
postLogoutRedirectUri: window.location.origin,
clientId: '9baa8e29-5dcb-4c23-92a3-92e177574d33',
scope: 'openid https://myvaccinepassport.onmicrosoft.com/9baa8e29-5dcb-4c23-92a3-92e177574d33/api',
responseType: 'code',
silentRenew: true,
autoUserInfo: false,
silentRenewUrl: window.location.origin + '/silent-renew.html',
logLevel: LogLevel.Debug,
renewTimeBeforeTokenExpiresInSeconds: 60,
// useRefreshToken: true, // for refresh renew, but revocation and one time usage is missing from server impl.
// ignoreNonceAfterRefresh: true,
// disableRefreshIdTokenAuthTimeValidation: true,
customParamsAuthRequest: {
  prompt: 'select_account', // login, consent
},
```

**Comment by jeffreyabecker** [comment]
This configuration redirects me to the login screen as I'd expect.
```
    openIdConfig: {
      authWellknownEndpoint:'https://myvaccinepassport.b2clogin.com/myvaccinepassport.onmicrosoft.com/B2C_1_DevClientApp/v2.0/.well-known/openid-configuration',
        stsServer: 'https://myvaccinepassport.b2clogin.com/myvaccinepassport.onmicrosoft.com/oauth2/v2.0',
      redirectUrl: window.location.origin,
      clientId: '9baa8e29-5dcb-4c23-92a3-92e177574d33',
      scope:
        'openid profile offline_access email https://myvaccinepassport.onmicrosoft.com/9baa8e29-5dcb-4c23-92a3-92e177574d33/api',
      responseType: 'code',
      silentRenew: true,
      useRefreshToken: true,
      maxIdTokenIatOffsetAllowedInSeconds: 600,
      issValidationOff: false,
      autoUserinfo: false,
      customParams: {
        prompt: 'select_account',
      },
    },
```

 However when I'm returned the token request fails with the following message:
```
{"error":"invalid_request","error_description":"AADB2C90083: The request is missing required parameter: grant_type.\r\nCorrelation ID: 24c3de39-7686-4859-a719-0f1f8b46e5ba\r\nTimestamp: 2021-06-09 00:18:10Z\r\n"}
```

**Comment by damienbod** [comment]
tested this in the V12 branch, updated the examples as well. Please check the config and compare. V12 should be released soon, hopefully this month

Greetings Damien
