### ISSUE TITLE
STS Callback "https://xxx/?code=xx.xxxx" in AzureAD should call "checkAuth" to start automatic token renew process althrough "AutoLoginGuard" is set.

### ISSUE THREAD

**Issue by eastjie** [damienbod/angular-auth-oidc-client#1115]
**Describe the bug**
We have the requirement that we should protect the root route "https://xxx" with "AutoLoginGuard", because some settings should be retrieved before loading the app . But there is a problem, for the callback url from AzureAD, the "checkAuth" must be called, if not, the token can't be refreshed newly, although the route is protected with "AutoLoginGuard", the "checkAuth" is still not called automatically.

**To Reproduce**
It can be reproduced in sample "sample-code-flow-azuread" with the following steps:
1. Add the route "home" with "AutoLoginGuard"
```
const appRoutes: Routes = [
  { path: '', pathMatch: 'full', component: HomeComponent, canActivate: [AuthGuard] },
  { path: 'home', component: HomeComponent, canActivate: [AutoLoginGuard] },
  { path: 'forbidden', component: ForbiddenComponent, canActivate: [AutoLoginGuard] },
  ...
```
2. After "login",  the token can't be refreshed automatically, we have checked, that the item "xxxx_storageSilentRenewRunning" is not saved in  session storage and the following protocol is **NOT** displayed as expected.

```
Checking: silentRenewRunning: false id_token: true userData: true
main.8498428cc13da973f776.js:1 Has id_token expired: false, 1623060316000 > 1623057076000
main.8498428cc13da973f776.js:1 Has access_token expired: false, 1623060314000 > 1623057076000
main.8498428cc13da973f776.js:1 silent renew, periodic check finished!
```
3. After analyse the src of "AutoLoginGuard", in callback from AzureAD in route with code verifier"https://xxx/?code=xx.xxxx", the "checkAuth" is not called.

``` private checkAuth(url: string) {
    return this.authStateService.authorized$.pipe(
      concatMap((isAuthenticatedAlready) => (isAuthenticatedAlready ? of(isAuthenticatedAlready) : this.checkAuthService.checkAuth())),**

      map((isAuthorized) => {
        const storedRoute = this.autoLoginService.getStoredRedirectRoute();

```

4. If the "checkAuth" is called manually "app.component" again, then silent renew process works well. 

**Expected behavior**

I'm not quite sure, if the concatMap is the workaround for "infinite loop" of AutoLogin. https://github.com/damienbod/angular-auth-oidc-client/issues/1052.
1. I have don't quite understand, why "checkAuth" is required for STS callback url in order to start refreshing token process.
2. How to implement AutoLogin globally without workaroud, because STS callback is an special url, should it be dealed differently in library?

**Desktop (please complete the following information):**
 - Browser: chrome, safari, edge
 - "angular-auth-oide-client": 11.6.10
 

**Additional context**
I have found one issue. It seems not the same use case but similar problem without calling "checkAuth".
https://github.com/damienbod/angular-auth-oidc-client/issues/1107

Thanks very much.

**Comment by FabianGosebrink** [comment]
Hey, we made a change in this (or will do) in V12. `concatMap` should be used instead of `switchMap` to have consistent sequential requests.

**Comment by damienbod** [comment]
fixed in V12
