### ISSUE TITLE
Redirection to child path doesn't work with can load

### ISSUE THREAD

**Issue by marcelbarner** [damienbod/angular-auth-oidc-client#1118]
**Describe the bug**
Not the full route path is stored to redirect in the storage.

**To Reproduce**
1. In the example project add a component "DetailsComponent" to the customer module with the path 'details' in the customer routing module
2. Start the app
3. Navigate directly to "http://localhost:4203/customers/details"
4. Login

**Expected behavior**
After successful login I will be redirected to the DetailsComponent.

**Current behavior**
I will be redirected to CustomersComponent.

**Where to find the problem in the code?**
AutoLoginGuard in the method canLoad.

**Possible Solution**
Instead of using `route.path` the solution can be to combine the segements.

**Technical example**
|||
|-|-|
Requested url:|http://localhost:4203/customers/details
route.path:|customers
segments[0].path:|customers
segments[1].path:|details

**Comment by marcelbarner** [comment]
Thanks, do you know, when you want to release it?

**Comment by damienbod** [comment]
V12 should be released in the next 2 to 4 weeks.

Still have so issues to complete, docs and testing
