### ISSUE TITLE
question on authinterceptor

### ISSUE THREAD

**Issue by rtamsatyam** [damienbod/angular-auth-oidc-client#1123]
I had a question regarding sending the Token as part of the header when communicating with the backend. 
The documentation  [here] (https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/using-access-tokens.md#http-interceptor) states that one only needs to include the Authinterceptor provider and define the secureRoutes in the config.
Just doing this did not automatically add the token to the request header. 
I just used a standard piece of code like this 
```
@Injectable()
export class AuthInterceptorService implements HttpInterceptor {

  constructor(private oidcSecurityService: OidcSecurityService) {
  }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const token = this.oidcSecurityService.getToken();
    const modifiedRequest = req.clone({
      headers: req.headers.set('Authorization', 'Bearer ' + token)
    });
    return next.handle(modifiedRequest);
  }
}

```
Only then did it work. But then naturally I am not doing something right. Cause now the Authinterceptor from your package is not being used. Maybe this is a noob question. Sorry, please help.

**Comment by FabianGosebrink** [comment]
Without code, this is very hard to answer. Can you make a repository with a _not working_ version, everything set up like you think it is correct for us to take a look at? You can take a configuration from the samples.

**Comment by rtamsatyam** [comment]
I have created the project, which I use for testing.
Please see https://github.com/rtamsatyam/ngoidcauthtest

We are using keycloak for the identification. In the auth-config.module.ts I have just given a fake url and client id.
I have left out the backend code. Basically when I try to access the backend for user.service.ts, I get a 401 because the authorisation header does not have the token. 

Please let me know what I am missing here. Thank you!

**Comment by rtamsatyam** [comment]
I have updated the project with the source files from https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-refresh-tokens

The call to backend code is under src/app/home/user.service.ts

**Comment by rtamsatyam** [comment]
I tried that too, of no avail. Could you please provide a working example?

**Comment by FabianGosebrink** [comment]
Hey, you are configuring the secure route to 

```
 oidcConfigService.withConfig({
       // ...
      secureRoutes: ['http://localhost:8080']
    });
```

But in your `UserService` you are calling `/api/users/me`. If you do not put the identifier in front, the request goes to the root of the SPA, which is `https://localhost:4200` in this case.

Call goes to `https://localhost:4200/api/users/me` in the network tab, but you configured `http://localhost:8080`. That is why it doesn't work.

**Comment by FabianGosebrink** [comment]
Please let us know if that solved the issue. Thanks.

**Comment by rtamsatyam** [comment]
Yay! This did work in the sense that the Auth Header did have the Token when accessing http://localhost:8080
However, now we get a CORS error. 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/users/me. (Reason: CORS request did not succeed).
```
Which is why the  /api requests to backend were configured in the src/proxy.conf.json file.
So looks like the Authinterceptor works only if there is no proxy configured. 
Hmm, it still doesn't solve the problem fully, because backend requests will always be a proxy, even in production.

**Comment by FabianGosebrink** [comment]
CORS is a server issue. You have to configure your server to allow requests from another source. Because it is pretty normal that your SPA lives on server A and your backend on server B.

**Comment by rtamsatyam** [comment]
The only way i know right now to avoid CORS when I am developing locally is to use the proxy.conf.json  https://angular.io/guide/build#proxying-to-a-backend-server. 
The strange thing is that the intercept works just fine, if I don't use the Authinterceptor and instead just use the code snippet I had pasted in the beginning  of this thread. I even tried setting the secureRoute to http://localhost:4200/api  but that did not help.

**Comment by FabianGosebrink** [comment]
Like said: CORS is a server issue. If you use the `/api/...` route before and the backend AND frontend are running on the same origin, you do not have CORS problems.
