### ISSUE TITLE
AutoLoginGuard fails to find the config if config is provided from an observable source

### ISSUE THREAD

**Issue by ntyrrell** [damienbod/angular-auth-oidc-client#1133]
**Describe the bug**
When the OidcConfigService is provided with a config from an observable source, the AutoLoginGuard attempts `checkAuth` before the observable for config is complete, causing the service to produce the following errors:

![image](https://user-images.githubusercontent.com/4884508/121863632-5849f980-ccfc-11eb-9b11-90b1244be410.png)

**To Reproduce**
Config setup as below;
```typescript
export function configureAuth(oidcConfigService: OidcConfigService, configurationService: ConfigurationService) {
    const setupAction$ = getAuthenticationUrl(configurationService).pipe(
        map(urlObj => urlObj.getUrl()),
        map(url => ({
            stsServer: url,
            redirectUrl: `${window.location.origin}/signin`,
            postLogoutRedirectUri: window.location.origin,
            clientId: '<<REDACTED>>',
            scope: 'openid profile email role <<REDACTED>>',
            responseType: 'id_token token',
            silentRenew: true,
            silentRenewUrl: `${window.location.origin}/signin?silent=true`,
            logLevel: LogLevel.Debug,
          } as OpenIdConfiguration)),
        switchMap((config) => oidcConfigService.withConfig(config))
    );
    return () => setupAction$.toPromise();
}

function getAuthenticationUrl(configurationService: ConfigurationService): Observable<AuthenticationUrl> {
    const client = new Client(configurationService.apiUrl, {
        debug: false,
        transport: grpc.WebsocketTransport(),
    });

    const request = new GetAuthenticationUrlRequest();

    const observable = bindNodeCallback(client.getAuthenticationUrl);

    return observable.call(client, request);
}
```
Where `ConfigurationService.apiUrl` is a simple property for getting a string, depending on the environment and `Client` is a GRPC client using @improbable-eng/grpc-web. Whilst the client is communicating over websockets, I would imagine that this should be respected in the same way as an HTTP request, or any other Observable for retrieving config data.

**Expected behavior**
Whilst the client is communicating over websockets, I would imagine that this should be respected in the same way as an HTTP request, or any other Observable for retrieving config data, such that the config is retrieved before any attempt is made to `checkAuth`.

**Desktop:**
 - OS: Windows 10
 - Browser: chrome
 - Version: 91.0.4472.101 (Official Build) (64-bit)

**Comment by FabianGosebrink** [comment]
Hey thanks for the issue,

as the lib is using the `APP_INITIALIZER` I am not sure how the Angular `APP_INITIALIZER` behaves when working with a value which is pushed via websockets / grpc.

**Comment by ntyrrell** [comment]
This behaviour can also be replicated if adding a delay to the observable source for the config.
e.g.
```typescript
function getAuthenticationUrl(configurationService: ConfigurationService): Observable<AuthenticationUrl> {
    const authenticationUrl = new AuthenticationUrl();
    authenticationUrl.setUrl("<<STS URL>>");

    return of(authenticationUrl);
}
```
works without issue
```typescript
function getAuthenticationUrl(configurationService: ConfigurationService): Observable<AuthenticationUrl> {
    const authenticationUrl = new AuthenticationUrl();
    authenticationUrl.setUrl("<<STS URL>>");

    return of(authenticationUrl)
    .pipe(
        delay(10000)
    );
}
```
encounters the aforementioned issue.

**Comment by FabianGosebrink** [comment]
Have you added the `AutoLoginGuard` to the main route?

**Comment by ntyrrell** [comment]
Not to the main route, but it has been added to the redirect route.

```typescript
const routes: Routes = [
    {
        path: '',
        loadChildren: () => import('./featured/landing/landing.module').then((m) => m.LandingModule),
    },
// other routes redacted
    {
        path: 'signin',
        component: SigninCallbackComponent,
        canActivate: [AutoLoginGuard],
    },
    { path: '**', component: NotFoundComponent }, // Wildcard route for a 404 page
];
```

**Comment by damienbod** [comment]
This has been improved and documented in version 12

**Comment by dartavion** [comment]
We had the exact same issue. In our case the routing configuration was causing the issue.

Changed this:

```imports: [RouterModule.forRoot(routes, { initialNavigation: 'enabled' })],```

To this: 

```imports: [RouterModule.forRoot(routes, {})],```
