### ISSUE TITLE
Missing word in readme.

### ISSUE THREAD

**Issue by fomenkogregory** [damienbod/angular-auth-oidc-client#1134]
**Describe the bug**
The word 'route' is missing in [this](https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/features.md#auto-login) section on docs.

**To Reproduce**
1. Go to https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/features.md#auto-login
2. Read first paragraph.

**Expected behavior**
Word 'route' is there.

**Screenshots**

![image](https://user-images.githubusercontent.com/51916577/121911713-ac72cf00-cd38-11eb-8de9-cd3362ddb221.png)

**Desktop (please complete the following information):**
any

**Smartphone (please complete the following information):**
any

**Comment by damienbod** [comment]
Hi @fomenkogregory thanks for reporting. Would you like to do a PR?

if not we can fix.

Greetings Damien

**Comment by fomenkogregory** [comment]
> Hi @fomenkogregory thanks for reporting. Would you like to do a PR?
> 
> if not we can fix.
> 
> Greetings Damien

Yes, I'll do.
