### ISSUE TITLE
Potentially missing StsConfigHttpLoader and StsConfigHttpLoader

### ISSUE THREAD

**Issue by mac-bhaird** [damienbod/angular-auth-oidc-client#1143]
**Describe the bug**
Potentially missing StsConfigHttpLoader and StsConfigHttpLoader

**To Reproduce**
1.  Create new angular project (v 11.x)
2.  npm install angular-auth-oidc-client
3. Create a copy of this auth-config.module.ts: https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/sample-code-flow-http-config/src/app/auth-config.module.ts
4. See errors:
Module '"angular-auth-oidc-client"' has no exported member 'StsConfigHttpLoader'.
Module '"angular-auth-oidc-client"' has no exported member 'StsConfigLoader'.

**Expected behavior**
Should be able to use the sample code :)

**Comment by FabianGosebrink** [comment]
Hey @mac-bhaird thanks for this. We merged a V12 branch into main. So main is currently on a V12 stand. We will release V12 after a testing phase. You have to stick to the samples with V11. The branch is done, you can find it here. https://github.com/damienbod/angular-auth-oidc-client/tree/version-11

**Comment by mac-bhaird** [comment]
@FabianGosebrink , my apologies.

Does this mean we have to wait for v12? This occurred on 11.6.11.

**Comment by FabianGosebrink** [comment]
Hey @mac-bhaird , sorry for not being exact here. This means that the samples you see currently with the `StsConfigHttpLoader` and `StsConfigHttpLoader` are referring to V12 which is on main but not yet released. If you want the samples and the docs for V11 please check out the branch I posted above.

The StsConfigHttpLoader and StsConfigHttpLoader are coming in V12. Not V11.

**Comment by mac-bhaird** [comment]
@damienbod , Got it, thanks! :)
