### ISSUE TITLE
Silent renew urls with trailing # cause state verification to fail

### ISSUE THREAD

**Issue by jlvarner** [damienbod/angular-auth-oidc-client#1146]
**Describe the bug**
Accounts were getting logged out after idle time with a message on the console like: ValidateStateFromHashCallback failed, state: f4aae400ac1821c71451376ab8d7f7dca2wtluk5S# local_state:f4aae400ac1821c71451376ab8d7f7dca2wtluk5S

**To Reproduce**
1. Login to site (we are using Cognito to Azure Domains, but I don't think that's relevant) with silent renewal enabled and LogLevel.Debug enabled
2. Leave browser idle
3. Call the silent renew url with a trailing # character (not sure why that's happening)
4. Watch the console for failure (or set a break point in TokenValidationService.validateStateFromHashCallback)
5. See error

**Expected behavior**
Silent renewal should succeed.

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Browser: Chrome: Version 91.0.4472.106 (Official Build) (64-bit)
 - Version: 11.6.6 (I checked more recent versions and they appear to have the same issue)
 
**Additional context**
With a breakpoint inside the failed if in ValidateStateFromHashCallback I get the following stack trace:
validateStateFromHashCallback (angular-auth-oidc-client.js:685)
codeFlowCodeRequest (angular-auth-oidc-client.js:1562)
processSilentRenewCodeFlowCallback (angular-auth-oidc-client.js:2540)
codeFlowCallbackSilentRenewIframe (angular-auth-oidc-client.js:2834)
silentRenewEventHandler (angular-auth-oidc-client.js:2849)
(anonymous) (angular-auth-oidc-client.js:2921)
(anonymous) (platform-browser.js:582)
invokeTask (zone-evergreen.js:399)
onInvokeTask (core.js:28540)
invokeTask (zone-evergreen.js:398)
runTask (zone-evergreen.js:167)
invokeTask (zone-evergreen.js:480)
invokeTask (zone-evergreen.js:1621)
globalZoneAwareCallback (zone-evergreen.js:1647)
window.onload (silent-renew.html?code=1a3acc33-501a-41e4-aac9-0319976aa789&state=f4aae400ac1821c71451376ab8d7f7dca2wtluk5S:11)
load (async)
(anonymous) (silent-renew.html?code=1a3acc33-501a-41e4-aac9-0319976aa789&state=f4aae400ac1821c71451376ab8d7f7dca2wtluk5S:6)

Looking at SilentRenewService.silentRenewEventHandler an incoming url of "https://localhost:5001/silent-renew.html?code=1a3acc33-501a-41e4-aac9-0319976aa789&state=f4aae400ac1821c71451376ab8d7f7dca2wtluk5S#" retains the # character after the split on '?' and when that is handed to HttpParams the '#' is retained as part of the state parameter.

I poked at the HttpParams class in the the angular source and neither that class nor its tests contain a '#' character, so it looks like they expect that to be stripped by the caller.

Configuration for module is driven by an API, but is:
{
        stsServer: res.authority,
        redirectUrl: baseUri,
        clientId: res.clientId,
        responseType: 'code',
        scope: 'openid profile email aws.cognito.signin.user.admin',
        postLogoutRedirectUri: baseUri,
        startCheckSession: true,
        postLoginRoute: baseUri,
        maxIdTokenIatOffsetAllowedInSeconds: 25,
        triggerAuthorizationResultEvent: true,
        autoCleanStateAfterAuthentication: false,
        silentRenew: true,
        silentRenewUrl: `${baseUri}/silent-renew.html`,
        logLevel: LogLevel.Debug,
};
where res.authority and res.clientId come from the API and baseUri from a helper class

**Comment by damienbod** [comment]
Would it be possible to update to version 12?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
