### ISSUE TITLE
Reset password - return url - expose get authorizationUrl

### ISSUE THREAD

**Issue by stephenlautier** [damienbod/angular-auth-oidc-client#1147]
**Is your feature request related to a problem? Please describe.**
We are implementing a management UI and we need a feature to request password reset (as admin from our ui) and we require to have a `returnUrl` which we can obtain via `getAuthorizeUrl` (tho its not exposed).

**Describe the solution you'd like**
Expose `UrlService` in order to use `getAuthorizeUrl` directly (or can be provided in `OidcSecurityService` or so) https://github.com/damienbod/angular-auth-oidc-client/blob/d398a4bfc1b6605a3dc8091f0db2e6ae35dc261a/projects/angular-auth-oidc-client/src/lib/utils/url/url.service.ts#L87

**Describe alternatives you've considered**
Found a workaround (which is quite hacky imo) as following:

```ts
private oidc: OidcSecurityService
...
return new Observable(obs$ => {
	this.oidc.authorize({
		urlHandler: url => {
			console.warn(">>> authorize url", url);
			obs$.next(new URL(url));
			obs$.complete();
		}
	});
});
```

**Comment by damienbod** [comment]
@stephenlautier We will expose UrlService  in V12

**Comment by stephenlautier** [comment]
Great news thanks!

**Comment by FabianGosebrink** [comment]
Small correction: We wont expose the complete service but we will expose the method through the facade. This should serve your needs I think :)

**Comment by stephenlautier** [comment]
> Small correction: We wont expose the complete service but we will expose the method through the facade. This should serve your needs I think :)

@FabianGosebrink can you specify which is the facade or link me to the new method please? I thought you referred to `OidcSecurityService` as the facade tho I cannot find it

**Comment by FabianGosebrink** [comment]
Hey, yes. The https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/oidc.security.service.ts will be the place we will provide the method you need, but we did not target it yet. Will do it as soon as I find some time for this. Do you want to review the PR then?

**Comment by stephenlautier** [comment]
Ah oki I thought this is already available in v12. Yes, today created a task to update to v12 hopefully we will update soon

Sure if its done you can link PR here 👍

**Comment by FabianGosebrink** [comment]
Please check :)
