### ISSUE TITLE
Best way to check OIDC server session at start

### ISSUE THREAD

**Issue by Lexa-tech** [damienbod/angular-auth-oidc-client#1150]
Hello, 
It's a question, not a bug. I would like to know the best way to check OIDC session (on the Identity Server).
I know I can use `checkAuth()` to check the session locally, but I have to ask the server if a session has been initialized by another client for the same user.
I tried to use `checkAuthIncludingServer()` but silent-renew process with iFrame must be configured, and our Identity Server does not allow being used in an iFrame (CSP Content Security Policy).
Our Identity Server is configured so we could use refresh tokens (with scope offline_access), but the doc says that we have to use silentRenew with iFrame.
So I guess I have to use `authorize` with prompt: 'none' and get the error code when coming back to my app ? Am I right or is there other ways ?
Thanks for your help.

**Comment by damienbod** [comment]
@Lexa-tech 

yes I see this as the only way possible. iframes are becoming a problem. authorize with prompt: 'none'  would work .

Greetings Damien
