### ISSUE TITLE
AuthInterceptor: Circular dependency in DI detected for InjectionToken HTTP_INTERCEPTORS

### ISSUE THREAD

**Issue by UncleStranger** [damienbod/angular-auth-oidc-client#1151]
After adding AuthInterceptor to app.module
`
  providers: [{
    provide: HTTP_INTERCEPTORS,
    useClass: AuthInterceptor,
    multi: true,
  },
  ],
`
got exception
[ERROR] 0-angularJwtClient - Getting auth well known endpoints failed on start Error: NG0200: Circular dependency in DI detected for InjectionToken HTTP_INTERCEPTORS. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.js:216)
    at R3Injector.hydrate (core.js:11412)
    at R3Injector.get (core.js:11236)

Temporarily fixed for myself by excluding DI ClosestMatchingRouteService from AuthInterceptor 
 constructor and moving the methods getConfigIdForClosestMatchingRoute and getAllConfiguredRoutes inside  class AuthInterceptor.

**Comment by FabianGosebrink** [comment]
You are running with V12 Code which is on main but not yet released. But on the good side, you found a bug, thank you :) Fixed in #1155

**Comment by damienbod** [comment]
merged, thanks for reporting and fixing!

Greetings Damien
