### ISSUE TITLE
Invalid check in getConfigIdForClosestMatchingRoute method of ClosestMatchingRouteService (HTTP_INTERCEPTORS, secureRoutes)

### ISSUE THREAD

**Issue by UncleStranger** [damienbod/angular-auth-oidc-client#1152]
Instead of
`
if (configuredRoute.startsWith(route)) {
`
there should be
`
if(route.startsWith(configuredRoute)) {
`

**Comment by FabianGosebrink** [comment]
Hey @UncleStranger , thanks for mentioning this. Can you explain a bit why you think this should be changed? Thank you.

**Comment by UncleStranger** [comment]
Thank you for the library, later I will ask the question why sometimes there is an infinite loop of requests to idsrv v4, and how i can debug it.

**Comment by UncleStranger** [comment]
Route must start with secured requested route.

**Comment by FabianGosebrink** [comment]
Thanks, this statement already is visible in your first post. Will clarify.
