### ISSUE TITLE
Angular 12 Support (ng add schematic)

### ISSUE THREAD

**Issue by pascalbe-dev** [damienbod/angular-auth-oidc-client#1158]
**Is your feature request related to a problem? Please describe.**
When installing the lib in a new Angular 12 project, the install process fails due to dependency version mismatches:

**Describe the solution you'd like**
No errors, when installing. Upgrading peer deps to v12.

**Describe alternatives you've considered**
None.

**Additional context**
``
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular-keycloak-oidc-sample@0.0.0
npm ERR! Found: @angular/common@12.1.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.5" from angular-auth-oidc-client@11.6.11
npm ERR! node_modules/angular-auth-oidc-client
npm ERR!   angular-auth-oidc-client@"11.6.11" from the root project
``

**Comment by FabianGosebrink** [comment]
Hey, thanks for the issue. Our Version 12 will be Angular 12 compatible. We are in the testing stages and will release then. Thanks.

**Comment by pascalbe-dev** [comment]
Cool. Looking forward :)
