### ISSUE TITLE
Silent renew failing with 404 options.

### ISSUE THREAD

**Issue by evhfla** [damienbod/angular-auth-oidc-client#116]
Initial call to identity server works fine, but the silent renew is failing with a 404 option Cors error.  Don't understand how could it be a Cors error when the initial call during login works successfully.  I am using version 1.3.18 of the library.

**Comment by damienbod** [comment]
If you're getting CORS error, your server is blocking a request. Which request is getting blocked? Then check if the CORS is enabled for this domain. If you have control over the server, you could then configure the CORS to allow this

Greetings Damien

**Comment by evhfla** [comment]
My point is the original request after login is not blocked, once the access token expires after 10 minutes then the issue occurs.  In other words, the call to the same api that works after the initial login to identityserver doesn't work after silentrenew.  So, if it is a Cors issue, it has to be something with the iframe that the silentrenew is using.  Is there a particular setting that I have set on the server side of identityserver in order for silentrenew to work without a 404 Cors Option Error?

**Comment by damienbod** [comment]
@evhfla This is probably CSP protection blocking iframes

**Comment by damienbod** [comment]
closing this, please reopen if it is not solved

Greetings Damien
