### ISSUE TITLE
On-Behalf-Of Flow support

### ISSUE THREAD

**Issue by jbakog** [damienbod/angular-auth-oidc-client#1160]
Does the library support the On-Behalf-Of Flow (as per https://datatracker.ietf.org/doc/html/rfc8693) or will in a feature release?

**Comment by damienbod** [comment]
Hi @jbakog 

No The OBO flow required a secret and so can only be supported on a trusted backend.

I would implement this on you API and use a public app for the UI.

Greetings Damien
