### ISSUE TITLE
Logoff request with custom params

### ISSUE THREAD

**Issue by viswadv** [damienbod/angular-auth-oidc-client#1162]
Is there a tentative date for the next release of the current master code? Our app needs to send custom params on the logoff method.

**Comment by damienbod** [comment]
Hi @viswadv We hope to be finished by the weekend

- testing the migration now
- validating the docs

Greetings Damien

**Comment by viswadv** [comment]
Thanks! Damien.

**Comment by damienbod** [comment]
V12 is released
