### ISSUE TITLE
Did not log out and log in again or the previous logged-in user

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#1163]
Hello, I have a question, if you do not log out, such as closing the browser. When I log in again next time, I automatically log in to the previous user without entering the user name and password. If I am not the previous user, there will be a security problem. I want to know what is the reason for this? How to solve the problem of re-entering the user name and password instead of automatically logging in after logging in next time without logging out?

The version I use is as follows:
   "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2", 
    "angular-auth-oidc-client": "^11.6.10"

Thank you.

**Comment by fengzhihenxs** [comment]
@FabianGosebrink    I'm thinking if it's because I just closed the browser and didn't end the session. The server-side logged-in user does not log out, which causes the default server to have no log-out user when the client logs in again?

**Comment by FabianGosebrink** [comment]
Yes, if you're still logged in on the server and when you login, so ask for the config again, you're logged in automatically.

**Comment by fengzhihenxs** [comment]
@FabianGosebrink   Thank you, is there a way to solve this automatic login?

**Comment by FabianGosebrink** [comment]
If you close the browser the server does not have a clue what was going on as there is no Stateful connection between the server and the client.

**Comment by fengzhihenxs** [comment]
@FabianGosebrink  Yes, I want to call 'OidcSecurityService.logoff()' when the browser is closed, but it doesn't seem to work.

**Comment by FabianGosebrink** [comment]
Maybe you can listen to the `beforeunload` event of the browser.

**Comment by fengzhihenxs** [comment]
Thank you very much, I just use it.
