### ISSUE TITLE
Object is of type 'unknown'

### ISSUE THREAD

**Issue by Toso82** [damienbod/angular-auth-oidc-client#1167]
**Describe the bug**
Object is of type 'unknown'angular template

**Eviroment**

```powershell
Angular CLI: 12.1.1
Node: 16.4.0 (Unsupported)
Package Manager: npm 7.19.1
OS: win32 x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.4
```

**To Reproduce**

app.component.ts

```ts
 constructor(public oidcSecurityService: OidcSecurityService) {}
```

app.component.html
```html
{{(oidcSecurityService.userData$ |async)?.email}
```

**Expected behavior**

Not give error or how can fix the problem.

**Comment by FabianGosebrink** [comment]
Hey, you do not get back the `email` directly.

Please see the docs here https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api#userdata

You get back a 

```
export interface UserDataResult {
  userData: any;
  allUserData: ConfigUserDataResult[];
}
```

result where on the `userData` your email field should be. Have you tried that? Thanks.

**Comment by Toso82** [comment]
@FabianGosebrink  Before update library work and not give error.   So why i can not use email directly?  
I think there is the problem on v12
userData$ returning UserDataResult instead of any only

**Comment by FabianGosebrink** [comment]
Hey, thanks for the quick answer. Yes, this worked before but due to the new Feature of multiple IPDs we increased the major version and semantic versioning describes this as breaking changes. Please refer to the migration guide here https://nice-hill-002425310.azurestaticapps.net/docs/migrations/v11-to-v12#userdata-returning-userdataresult-instead-of-any-only

**Comment by Toso82** [comment]
@FabianGosebrink Thanks ok i see but i have this

```html
{{(oidcSecurityService.userData$ |async)?.email}
```
 On template and not in ts.  And now not compile and i don't find how can modify to work

**Comment by FabianGosebrink** [comment]
`{{(oidcSecurityService.userData$ |async)?userData?.email}}`

**Comment by Toso82** [comment]
@FabianGosebrink Ok thanks now work. I understand what wrong.  I mean work compile this
 
```html
 {{(oidcSecurityService.userData$ |async)?.userData?.email}} 
```

but the same advice 

Object is of type 'unknown'. on userData
