### ISSUE TITLE
Typo in UserService causes error for fetching userdata

### ISSUE THREAD

**Issue by 123niel** [damienbod/angular-auth-oidc-client#1168]
**Describe the bug**
UserService fails while retriving UserInfo from configured `userInfoEndpoint` because it takes `authWellKnownEndPoints.userinfoEndpoint` (with lower 'i')

https://github.com/damienbod/angular-auth-oidc-client/blob/15335bb9676a6ba957e51f561d4367d6a7b5f1db/projects/angular-auth-oidc-client/src/lib/userData/user.service.ts#L123
**To Reproduce**
1. Configure `authWellknownEndpoints`
2. Try to login

**Expected behavior**
Userinfo gets fetched from configured `userInfoEndpoint`

**Screenshots**
![image](https://user-images.githubusercontent.com/24916146/124463116-b49bb880-dd92-11eb-934e-9570576c0af1.png)
![image](https://user-images.githubusercontent.com/24916146/124462925-70a8b380-dd92-11eb-8ea4-b940941c0055.png)

**Desktop (please complete the following information):**
 - OS: macOS catalina
 - Browser chrome
 - Version 91.0.4472.114

**Comment by 123niel** [comment]
Can I fix that and make an PR?

**Comment by FabianGosebrink** [comment]
Hey, thanks for reporting. Sure, glad to review your PR then.
