### ISSUE TITLE
Renew token and session expire time without refresh page and call backurl

### ISSUE THREAD

**Issue by maninder93** [damienbod/angular-auth-oidc-client#1171]
Hi am working on angular 11 project  how can I Renew token and session expire time without refresh page and call backurl.
i am using this.oidcSecurityService.authorize(); but this refresh my page because it went to call back url eventually.

**Comment by FabianGosebrink** [comment]
Could you be a little more precise about what you want to achieve, what you did already and what did not work? Thanks.

**Comment by maninder93** [comment]
I want to extend token expire time or i want new token 1 minute before token is expired I want to implement continue session functionality.

**Comment by FabianGosebrink** [comment]
You can use silent renew either with iFrames or refresh tokens, depending on your configuration. The config can be found in the samples or in the docs [here](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration). If you want to change the time when the token should be renewed, the offset, then take a look at [renewtimebeforetokenexpiresinseconds](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#renewtimebeforetokenexpiresinseconds)

**Comment by maninder93** [comment]
silent renew did not work for me what i want is service which give can  me token and user data which i will store in local storage.

**Comment by FabianGosebrink** [comment]
All of this is in the [public api](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api)

**Comment by maninder93** [comment]
But the problem is that does not renew my token i am having https://session-expiration-alert.netlify.app/ this type of functionality in my web site

**Comment by FabianGosebrink** [comment]
Do you have silent renew configured and copied the `silent-renew.html`? Or are you using refresh-tokens?

**Comment by maninder93** [comment]
Yes silent-renew.html I have copied that but when I call force refresh token that nothing happen or if you can provide me link to how to get token using  refresh token I would be great help

**Comment by FabianGosebrink** [comment]
Your token should get refreshed automatically if you configured this. Can you post your config? (wipe out the sensitive information :-) )

**Comment by maninder93** [comment]
stsServer: customConfig.oidcConfig.stsServer,
        authWellknownEndpoint: customConfig.oidcConfig.authWellknownEndpoint,
        redirectUrl: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        clientId: customConfig.oidcConfig.clientId,
        autoUserinfo: false,
        scope: customConfig.oidcConfig.scope,
        responseType: "code",
        silentRenew: true,
        silentRenewUrl: window.location.origin + "/silent-renew.html",
        logLevel:
        customConfig.logLevel === "Debug" ? LogLevel.Debug : LogLevel.Error,
        unauthorizedRoute: "login/unauthorized",
        storage: localStorage,

**Comment by maninder93** [comment]
this is on silent renew page
 <script>
        window.onload = function () {
            /* The parent window hosts the Angular application */
            var parent = window.parent;
            /* Send the id_token information to the oidc message handler */
            var event = new CustomEvent('oidc-silent-renew-message', { detail: window.location });
            parent.dispatchEvent(event);
        };
    </script>
