### ISSUE TITLE
Error: ./node_modules/angular-auth-oidc-client/fesm2015/angular-auth-oidc-client.js 4790:36-60 "export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'

### ISSUE THREAD

**Issue by garvraj** [damienbod/angular-auth-oidc-client#1172]
My angular version is 11 , and i am using latest version of "angular-auth-oidc-client": "^12.0.1"
It's not working for me, giving me the below error

Error: ./node_modules/angular-auth-oidc-client/fesm2015/angular-auth-oidc-client.js 4835:24-48
"export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'

**Comment by garvraj** [comment]
@damienbod  Can you please help me on this on priority

Thanks in advance

**Comment by FabianGosebrink** [comment]
As I am not @damienbod but have you tried updating your angular app to V12?

**Comment by garvraj** [comment]
> I am not @damienbod but have you tried updating your angular app to V12?

Ahh Sorry for wrong tag,

No I have not updated to V12, my angular was V12 from start , I just installed angular-auth-oidc-client

**Comment by FabianGosebrink** [comment]
Ah then please make sure you use this lib in V12 with Angular in V12.

**Comment by garvraj** [comment]
> Ah then please make sure you use this lib in V12 with Angular in V12.

So if I use V11 angular then i must use angular-auth-oidc-client version 11

**Comment by FabianGosebrink** [comment]
Normally Angular 11 should work with this Lib V12. But you said, that you're on Angular 12, right? 

>my angular was V12 from start

**Comment by garvraj** [comment]
> Normally Angular 11 should work with this Lib V12. But you said, that you're on Angular 12, right?
> 
> > my angular was V12 from start

No I am on Angular 11 and I am using lib V12, which is giving me below error
Error: ./node_modules/angular-auth-oidc-client/fesm2015/angular-auth-oidc-client.js 2722:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

**Comment by damienbod** [comment]
Is this issue related to this one?

https://github.com/damienbod/angular-auth-oidc-client/issues/1178

Greetings Damien

**Comment by garvraj** [comment]
> Is this issue related to this one?
> 
> #1178
> 
> Greetings Damien

Not exactly, My issue is because I was using angular 11 with V12 angular-auth-oidc-client

**Comment by FabianGosebrink** [comment]
Can this be closed then?

**Comment by garvraj** [comment]
Yes this can be closed but still I did not understand why angular 11 with V12 angular-auth-oidc-client cannot be used

**Comment by FabianGosebrink** [comment]
From https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility

> The Angular version used to build an application should always be the same or greater than the Angular versions used to build any of its dependent libraries. For example, if you had a library using Angular version 12, the application that depends on that library should use Angular version 12 or later. Angular does not support using an earlier version for the application.
