### ISSUE TITLE
Automatic redirect to original url after authentication

### ISSUE THREAD

**Issue by marklagendijk** [damienbod/angular-auth-oidc-client#1173]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open a link to a specific page of an app, and then after login I'm redirected to another page. At that point I either have to re-enter the original url, or use the app to navigate to that page.
This is even more annoying for SSO scenarios (which are very common with OIDC), because then you don't even notice that you are being logged in (there is just a half-second flash caused by the redirect to the Authorization Provider and back).

**Describe the solution you'd like**
I would like the library to natively support this use case. An extra configuration option `postLoginRedirectToOriginalRoute: boolean` could be added. This would function like this:
1. In `authorize` when `postLoginRedirectToOriginalRoute` is active the current url would be stored in `sessionStorage`.
2. In the processing of the authentication result when normally the redirect to `postLoginRoute` would happen, it would get (and remove) the stored url from `sessionStorage` and if one was there it would redirect to it.

**Describe alternatives you've considered**
An alternative could be to at least document how to achieve this with the current version of the library.

**Comment by FabianGosebrink** [comment]
Hey, thanks for this. Are you using the `AutoLoginPartialRoutesGuard` to login when entering a route?

**Comment by marklagendijk** [comment]
For my app all routes are protected. So I'm currently using this:
``` ts
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  constructor(private oidcSecurityService: OidcSecurityService) {
  }

  ngOnInit() {
    this.oidcSecurityService
      .checkAuth()
      .subscribe((response) => {
        if (response.errorMessage) {
          console.error(response.errorMessage)
        }

        if (!response.isAuthenticated) {
          this.oidcSecurityService.authorize()
        }
      });
  }
}
```

I'm considering switching to `AutoLoginAllRoutesGuard`, but I'm not yet sure about the pros and cons.

**Comment by FabianGosebrink** [comment]
I think you should give it a try. In the background it should do this login/logout automatically for you and save the redirected route and navigate when you come back. https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/auto-login/auto-login-all-routes.guard.ts .

**Comment by FabianGosebrink** [comment]
Sure, that would really be a nice addition. We have not implemented this yet. Would you like to do a PR for this?

**Comment by marklagendijk** [comment]
Yes, will do.

**Comment by marklagendijk** [comment]
I created the Pull Request: #1174.

Note: I think the documentation / samples should also be adjusted to reflect this. I would remove the `AppComponent` approach, and instead just advise using the guards in all samples / documentation.

Whenever the guard is used on a single route, `canActivate` should be used. When the guard is used on a parent route `canActivateChild` should be used.

**Comment by FabianGosebrink** [comment]
Well the "normal" approach in an SPA is that you have at least one open public accessible route which is exactly for the handling of the auth. Honestly this auto login was just a tryout, we had a lot of bugs with it and worked hard to improve it, because we are still surprised that is is that heavily used. Normally an SPA needs one route to be publicly accessible.  

So the Auto Login Feature is a nice to have one. The method with calling `checkAuth()` and `checkAuthMultiple()` is the one to go normally imho.

**Comment by marklagendijk** [comment]
There are several use cases that can benefit from a pre-login screen. Such as:
- Multiple OIDC Auth Providers => The user must choose one (although you could persist that choice and use it for automatic auth afterwards). Alternatively the selection could live outside the app, and be passed as query param to the app.
- Scenarios where a pre-login landing screen adds value => Things like explanation about the app and why the user needs to login etc. Alternatively this page could live outside the app.

But there are also quite some use cases that benefit from the automatic authentication:
- In some cases there is no interaction needed at the Authorization Provider (the user is already logged in, SSO). In such cases the log in process is nothing more than a half-second-flash.
- When there is interaction needed usually the Authorization Provider will display enough information so that everything is clear to the user. So by getting rid of the pre-login landing page you get rid of an extra step, without it making the user experience worse.

I can't judge which of the two is more common. But I can say that the auto-login use cases aren't rare.

**Comment by FabianGosebrink** [comment]
Without any doubt they are not rare. I totally see the benefits. But SPAs are not built for this. Normally they need one public accessible route for a redirection.

**Comment by marklagendijk** [comment]
Btw, the approach of setting the guard on a parent route, does work with having public routes. You can just put those on the same level as the parent.

export const appRoutes: Routes = [
  {
    path: '', canActivate: [AutoLoginAllRoutesGuard], children: [
      {path: '', component: HomeComponent, pathMatch: 'full'},
      {path: 'fetch-data', component: FetchDataComponent},
    ],
  },
  {path: 'unauthorized', component: UnauthorizedComponent, pathMatch: 'full'},
  {path: 'public', component: PublicComponent, pathMatch: 'full'},
]

**Comment by FabianGosebrink** [comment]
Thanks for the info. Can this be closed then?

**Comment by Drol** [comment]
> Without any doubt they are not rare. I totally see the benefits. But SPAs are not built for this. Normally they need one public accessible route for a redirection.

I don't understand. How are they not built for this?

**Comment by FabianGosebrink** [comment]
An SPA normally needs one public route to handle the auth. That is just how auth in an SPA works. Because the STS sends you back to the sts to setup all the token stuff. Normally this is called "/callback" or something. The auto login guards are only a helper from us that you do not have to do this manually :)

**Comment by Drol** [comment]
> An SPA normally needs one public route to handle the auth. That is just how auth in an SPA works. Because the STS sends you back to the sts to setup all the token stuff. Normally this is called "/callback" or something. The auto login guards are only a helper from us that you do not have to do this manually :)

Ah sorry now I get what you mean. Thought you meant the SPA app have to have a "real" public page like showing a start page for the unauthed user before auth.

**Comment by FabianGosebrink** [comment]
Yes or a callback one which displays a loading bar/spinner/text, whatever.

**Comment by jayachristina** [comment]
Hi, how would this work when I have only one page being protected? 
* I login in from homepage which is not protected and I return back to same page
* but when I login from another public unprotected page, I will be taken back to homepage because there is not authguard
* login from protected page works fine.

Any guidance for this situation please?
