### ISSUE TITLE
Unclear error message when providing improper config to module.

### ISSUE THREAD

**Issue by milo526** [damienbod/angular-auth-oidc-client#1185]
**Describe the bug**
During my upgrade to v12 of the library (using the [upgrade guide](https://nice-hill-002425310.azurestaticapps.net/docs/migrations/v11-to-v12)) I missed one small but critical piece of the guide.
I provided my config object as the root of the object instead of placing it into a config key.

While it is clear in both the upgrade guide as well as the docs that you are supposed to provide an object with the `config` key; The error when you provide an improper object is less than useful. 

> TypeError: Right side of assignment cannot be destructured

**To Reproduce**
```js
const config: OpenIdConfiguration = { /** config object **/}

AuthModule.forRoot(config)
```

**Expected behavior**
A proper error would be very useful, either a type error stating that the provided object is malformed or that the config is missing (since the key is not provided)

**Additional context**

When clearly following the documentation I found out that the object should be provided as follows.

```js
const config: OpenIdConfiguration = { /** config object **/}

AuthModule.forRoot({config: config})
```

Once more, this bug came to be because I failed to properly read the docs but I think it could be helpful for other users to provide us with a friendly error message that indicates what is wrong instead of the vague and unclear error message that we now receive.

**Comment by FabianGosebrink** [comment]
Hey, thanks for this. Do you have a stack trace where the error is thrown?

**Comment by milo526** [comment]
The problem is the destructure in the [`createIdentifierToCheck`](https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/config/validation/rules/ensure-no-duplicated-configs.rule.ts#L5)

The input there - `passedConfig` ` is `undefined` and logically can't be destructured.

**Comment by FabianGosebrink** [comment]
If you want you can review the PR and let me know what you think.

**Comment by milo526** [comment]
Looks good to me!

**Comment by FabianGosebrink** [comment]
Will be in the next release then :)
