### ISSUE TITLE
Version 11.6.11 returns null when retrieving userData$

### ISSUE THREAD

**Issue by Dustin-Mikusko** [damienbod/angular-auth-oidc-client#1187]
In any component, when I call `this.oidcSecurityService.userData` , the return value is `null` while I'm on version 11.6.11. I reverted to 11.6.8 and it works as expected. Those are the only two versions I've dealt with so I don't know exactly which version may have 'broken' it. I'm staying on 11.6.8 for now.

**Comment by FabianGosebrink** [comment]
Do you have a sample repo to reproduce the issue? You can take a config from any of the samples if you like.

**Comment by Dustin-Mikusko** [comment]
We've moved to V12 Angular in our project, and after playing around with lib V12 I think my issue is solved. Thank you
