### ISSUE TITLE
Add peer dependencies to library package.json

### ISSUE THREAD

**Issue by markusfalk** [damienbod/angular-auth-oidc-client#1188]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when libs do not specify their peer dependencies. I would like to know the compatible Angular versions of each of the libs versions. 

**Describe the solution you'd like**
Maybe add a peerDependency section to your package.json (https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies)

**Describe alternatives you've considered**
There is Angular in the dependency section of the package.json (just not sure if this would have to be a peer dependency?). 

Is this library using a lock-step release with Angular? If so maybe documentation would suffice. Or maybe version 12 of this lib is still compatible with version <12 of Angular?

**Additional context**
I would like to use this lib for an Angular 7 app and do not know what version I should use.

**Comment by FabianGosebrink** [comment]
Hey, thanks for this. As we are working with an angular cli workspace the lib itself has its won peer dependency section here https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/package.json

I did not test how many versions back the library works, so would have to do this manually.

**Comment by markusfalk** [comment]
Sorry, didn't realize the workspaces. Thanks for reaching out!
