### ISSUE TITLE
Expose PopupService back in v12

### ISSUE THREAD

**Issue by normandjulian** [damienbod/angular-auth-oidc-client#1189]
**Is your feature request related to a problem? Please describe.**
Hi,
In my team, we have severals projects with oidc and angular-auth-oidc-client. It work nicely.

However one of our project is an Office Excel add-in and we have to use Office function to open a dialog : [Office.context.ui.displayDialogAsync](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=excel-js-preview#displayDialogAsync_startAddress__options__callback_)

In `angular-auth-oidc-client@11.x.x`  the `PopupService` was exposed.
It allow us to provide our own service instead which use the Office.context.ui.displayDialogAsync instead of window.open

But in `angular-auth-oidc-client@12.x.x` the `PopupService` isn't exposed anymore

**Describe the solution you'd like**
If it's possible to expose it back or to choose if we want to use window.open of something else as **Office.context.ui.displayDialogAsync** in my case

**Describe alternatives you've considered**
Forking the project

**Additional context**
Here is some of my codes 

My office-popup.service.ts
```typescript
@Injectable()
export class OfficePopUpService implements IPopUpService {
    // ...
    private connectDialog: Office.Dialog

    async openPopUp(url: string, popupOptions?: PopupOptions): Promise<void> {
        // ...

        await Office.context.ui.displayDialogAsync(url, optionsToPass, (result) => {
            if (result.status === Office.AsyncResultStatus.Failed) {
                console.log(`${result.error.code} ${result.error.message}`)
            } else {
                this.connectDialog = result.value
                this.connectDialog.addEventHandler(
                    Office.EventType.DialogEventReceived,
                    handleDialogEvent
                )
            }
        })

        // ...
    }
}
```

app.module.ts in v11: 

```typescript

/*
    from the file => angular-auth-oidc-client.d.ts  
    export { PopUpService as ɵbm } from './lib/login/popup/popup.service';
*/
import { ɵbm } from 'angular-auth-oidc-client'

@NgModule({
    declarations: [ /* Some Components */ ],
    imports: [ /* Some imports */ ],
    providers: [
        { provide: ɵbm, useClass: OfficePopUpService },
    ],
    bootstrap: [AppComponent],
})
export class AppModule {}
```

app.module.ts in v12: 

```typescript

/*  not anymore the file => angular-auth-oidc-client.d.ts */
import { PopUpService } from 'angular-auth-oidc-client/lib/login/popup/popup.service'

@NgModule({
    declarations: [ /* Some Components */ ],
    imports: [ /* Some imports */ ],
    providers: [
        { provide: PopUpService, useClass: OfficePopUpService },
    ],
    bootstrap: [AppComponent],
})
export class AppModule {}
```

it throw an error => 

> ./xx/xx/xx/app.module.ts - Error: Module not found: Error: Can't resolve 'angular-auth-oidc-client/lib/login/popup/popup.service' in '/xx/xx/xx/src/app'

**Comment by FabianGosebrink** [comment]
Hey thanks. I would love to provide a functionality on the `PopupOptions` to provide your own handler. But I have not tested this. Can you make a sample repo with a custom handler - other than `window.open` where I can run tests against? Like a minimal angular app?

**Comment by normandjulian** [comment]
Hey,

Nice, thank you.
I'll do a sample repository for that.

**Comment by damienbod** [comment]
@normandjulian @FabianGosebrink 

What's the status here? Should we not just add this back to the public export?

Greetings Damien

**Comment by normandjulian** [comment]
Hi,

I really don't mind, it's up to you.
It worked nicely with the export in the version 11.

Can I do a PR for that ?

**Comment by FabianGosebrink** [comment]
Just because I am interested: When the popup closes we tell the lib several information in the internal implementation of the `PopupService`. We have to synchronize what comes out of the popup with the lib holding the state of the auth. How do you handle this in your implementation? Do you even need this? What state has the lib if you overwrite the popupService and the popup closes?

**Comment by normandjulian** [comment]
Hi,

It's moslty the same behavior, but indeed we don't use everything as the `isCurrentlyInPopup` or the `sendMessageToMainWindow` functions which both return false in our case

We don't use the callback from the popup with Excel, instead we check the `checkAuth()` to know if the user is authenticated or not

Here is our [`PopupService.ts`](https://gist.github.com/normandjulian/aefb9f38df6d199160dc497ef9dd1683)
Here is our [`AuthService`](https://gist.github.com/normandjulian/5c1d0debde97b01103a9fa4337f5819a), to check if the user is connected or not.

All the features with the sessionStorage have been commented or removed because we couldn't use it as expected with Office.js.

The main changements are in the `openPopup()`.
- It returns a Promise in our case. 
- We handle the response in the callback of the `Office.context.ui.displayDialogAsync`
- We add the `handleDialogEvent` to handle the end of the communication before cleanup the dialog

I hope it helps, let me know if you need more details.

**Comment by FabianGosebrink** [comment]
Thanks for the answer. Well if we do not control the popup-behavior we can not guarantee that this popup thing works. Because we are opening the popup and setting state on this inside the lib. If you do this for yourselves, the lib may have a different state. So when you provide the wrong options (Maybe like `isCurrentlyInPopup(): boolean { return true }`) the `checkAuth()` maybe does not work anymore. However: We can expose the service. But bugs which results out of this are impossible for us to fix then. I would like to document this then.

**Comment by FabianGosebrink** [comment]
> Can I do a PR for that ?

Of course you can do this. We would really appreciate this :-) Thanks!

**Comment by FabianGosebrink** [comment]
Just as a note: We just merged the PR and did a release, but the APIs we are providing are supported and we believe overwriting the `PopupService` might lead to problems using the lib and we do not recommend this.

**Comment by normandjulian** [comment]
Thank you !
We try to find a better way to do it.

**Comment by FabianGosebrink** [comment]
If it works for you, it works for you :) Feel free to do it. We did not do a release yet, 12.0.2 will provide this :)

**Comment by normandjulian** [comment]
Hi back,

I just realize I fucked up :/
I exposed the wrong service `PopUpLoginService` instead of `PopUpService` ...

I'll recreate another PR, I'm really sorry for that.
