### ISSUE TITLE
prompt parameter sent multiple times with silent renew (azure integration)

### ISSUE THREAD

**Issue by pfeigl** [damienbod/angular-auth-oidc-client#1192]
**Describe the bug**
When integrating with azuread and using silent renew, when the renew is actually executed, the prompt parameter is sent with multiple values.

MS doesn't allow this and gives an error:
> AADSTS9000411: The request is not properly formatted. The parameter 'prompt' is duplicated.

**To Reproduce**
1. Integrate with AzureAD
2. Enable silent renew
3. wait for the silent renew to happen

**Expected behavior**
prompt is only sent once - however i'm actually not sure what value needs to be sent of the two in this case.

**Screenshots**
![image](https://user-images.githubusercontent.com/237891/125586864-c07fdab9-c1a1-4781-b7b7-62000e0c82be.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version  91.0.4472.124 

**Additional context**
The reason is, that the schematic for the azure integration has a prompt pre-defined:
https://github.com/damienbod/angular-auth-oidc-client/blob/9cf4ce4e97b574a1c6a78a51cde7232015ea0f7f/projects/schematics/src/ng-add/actions/configs.ts#L38

But also the `createAuthorizeUrl` here always blindly appends the prompt, when one is provided:
https://github.com/damienbod/angular-auth-oidc-client/blob/3de72d57b53f479f946d30b9b77a5bfa975aec79/projects/angular-auth-oidc-client/src/lib/utils/url/url.service.ts#L332

As for silent-renew the prompt is always defined with the value `none` - see here:
https://github.com/damienbod/angular-auth-oidc-client/blob/3de72d57b53f479f946d30b9b77a5bfa975aec79/projects/angular-auth-oidc-client/src/lib/utils/url/url.service.ts#L388

This results in URLs like the following
`...&prompt=none&prompt=select_account&...`

Probably the right fix is not to append the prompt but use set (https://angular.io/api/common/http/HttpParams#set)

**Comment by FabianGosebrink** [comment]
Hey, thanks for pointing this out. I see in the `createAuthorizeUrl` method we apply all params no matter if they have been applied before. This is a mistake and a bug imho. Do I understand this correctly? Thanks.

**Comment by pfeigl** [comment]
I think you are right, that actually all parameters need to be taken into consideration, not only the prompt. My understanding is also, that it should be none in this specific case, meaning the code should use the local value with higher priority than the default value. I guess it's probably like this for all other parameters, too.

Here's a snippet from our `package.json` in regard to the version used: `"angular-auth-oidc-client": "11.6.4",`

**Comment by FabianGosebrink** [comment]
Ah interesting, so this issue was there in V11 already! Thanks. Will add a fix. Have to discuss with @damienbod if we provide a hotfix for V11 or if the bug is only fixed on V12 of our lib.

**Comment by FabianGosebrink** [comment]
Please check the PR. This is for V12 currently.

**Comment by damienbod** [comment]
This was per design, we decided that the custom params were only for missing parameters or extra parameters which where not already defined. But I don't see a problem with over writing these if they are added

**Comment by FabianGosebrink** [comment]
https://github.com/damienbod/angular-auth-oidc-client/pull/1193
