### ISSUE TITLE
Token Resolver - How do I wait for the token before routing?

### ISSUE THREAD

**Issue by KaneKopetski** [damienbod/angular-auth-oidc-client#1194]
Hello,

My situation is such:

I have a legacy app not written in Angular. Access the app requires a cookie which is retrieved when a user logs in.

My Angular app is iframed into this legacy app, but it is using JWT access token with OpenID and PKCE.

When the app is running in isolation, everything works as expected.

The issue arises when the iframe is loaded. It's automatically routing to a particular component in the Angular app, and the service call to fetch the component data is being made before the app has a chance to fetch the access token.

I have tried adding a resolver to the particular route to wait for the token before the route is loaded, but the call to get the token finishes with no returned value since the code flow hasn't actually finished by the time the component loads, the resolver fires, etc. 

Is this an issue with OIDC or just me missing something obvious? 

Thanks for any help anyone can offer.

**Comment by damienbod** [comment]
Hi @KaneKopetski I don't have enough info the help you here. You seem to ask about how angular loads guards, init and so on. Maybe the angular docs might help?

Closing this as I don't think I can help you here.

Greetings Damien
