### ISSUE TITLE
Question re CreateStaticLoader example

### ISSUE THREAD

**Issue by rickers1** [damienbod/angular-auth-oidc-client#1195]
I have just upgraded from v10 to v12 of angular-auth-oidc-client. 

I need to get some AuthModule config settings from my DI config service, so can't do 
`imports: [AuthModule.forRoot({config:{...}})]`

I see there is a loader option where I can perhaps I can do it, but how do I use it? Or am I misunderstanding something here?

My code in v10 was like this.
```
export function configureAuth(oidcConfigService: OidcConfigService, appConfigService: ConfigService) {
  // Merge defaults and passed in values
  const defaultAuthConfig = {
    UI_URL: window.location.origin,
    SSO_SERVER_URL: AppWellknownUrl.auth_server,,
    SSO_SERVER_RESPONSE_TYPE: 'code',
    SSO_SERVER_SCOPE: 'profile openid offline_access ' + (appConfigService.get().environment.IDSVR4_API_SCOPE || '')
  };
    
  const authConfig = <AuthConfig>{ ...defaultAuthConfig, ...appConfigService.get().environment };

  return () => oidcConfigService.withConfig({
            clientId: authConfig.IDSVR4_API_CLIENT,
            scope: authConfig.SSO_SERVER_SCOPE,
            responseType: authConfig.SSO_SERVER_RESPONSE_TYPE,
            silentRenew: true,
            useRefreshToken: true,
            renewTimeBeforeTokenExpiresInSeconds: 10,
            logLevel: authConfig.AUTH_LOG_LEVEL || LogLevel.None,

            // Paths
            stsServer: authConfig.SSO_SERVER_URL,   // 'stsServer' is now 'authority'
            redirectUrl: authConfig.UI_URL,
            postLogoutRedirectUri: authConfig.UI_URL,
            silentRenewUrl: `${authConfig.UI_URL}/${AppWellknownUrl.silent_renew}`,
          });
}

```
I'm thinking I do it like the Load config from HTTP example you gave?

**Comment by rickers1** [comment]
I changed 
`return () => oidcConfigService.withConfig({`
to
`return new StsConfigStaticLoader({`

Then in the Module
`imports: [AuthModule.forRoot({ 
  // storage: CookieManagerService,
  loader: {
    provide: StsConfigLoader,
    useFactory: configureAuth,
    deps: [ConfigService],
  },
});]` 

It seems to be working fine. Is there a better way?

**Comment by FabianGosebrink** [comment]
Basically that is the way it is designed like it is with the `StsConfigHttpLoader `  [here](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#load-config-from-http). You can also try to load the config before like mentioned in [this blog](https://timdeschryver.dev/blog/angular-build-once-deploy-to-multiple-environments#platformbrowserdynamic).

**Comment by FabianGosebrink** [comment]
*ping*

**Comment by FabianGosebrink** [comment]
I added docs about getting the config from a service [Getting static config from a service (sync)](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#getting-static-config-from-a-service-sync)
