### ISSUE TITLE
Refresh the page and log out

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#1201]
Hello, I encountered an abnormal exit. I turned on silentRenew and refreshed the token. After a period of time after logging in (it may be a long time, but the time may be short, the time is uncertain), but when I refresh the page, isAuthenticated returns false for some reason. Actually, it should be true because there is no logout.
Version  "angular-auth-oidc-client": "^11.6.10"
The configuration is as follows:

```
 oidcConfigService.withConfig({ 
      stsServer: 'Identity server port', 
      redirectUrl: "https://localhost:4200",
      postLogoutRedirectUri: "https://localhost:4200",
      clientId: 'client_angular',
      scope: 'openid profile rc.scope ApiOne ApiTwo offline_access',
      responseType: 'code',
      silentRenew: true,
      useRefreshToken: true,
      renewTimeBeforeTokenExpiresInSeconds: 10,
      tokenRefreshInSeconds: 30,
      logLevel: LogLevel.Debug,
    });
```

**Comment by EmirhanAksoy** [comment]
Same here

**Comment by damienbod** [comment]
Hi @fengzhihenxs @EmirhanAksoy This is most likely when the server session expires on the identity provider .

Next time this happens open the identity provider on a different tab and validate if you still have a session.

Greetings Damien

**Comment by fengzhihenxs** [comment]
@damienbod    Thanks, but I don't understand too much. I have turned it on and updated it silently.  Will the server session be updated?  Why does this happen for a different length of time?
