### ISSUE TITLE
sample-code-flow-http-config issue compiling

### ISSUE THREAD

**Issue by mac-bhaird** [damienbod/angular-auth-oidc-client#1202]
**Describe the bug**
Using the auth-config.module.ts bits from sample-code-flow-http-config project results in compile error

**To Reproduce**
1. Create new Angular 12 project
2. npm install angular-auth-oidc-client
3. Copy this file into project: https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/sample-code-flow-http-config/src/app/auth-config.module.ts
4. Add AuthConfigModule to AppModule
5. See error

`Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:14:5 - error TS2416: Property 'canLoad' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanLoad'.
  Type '(route: Route, segments: UrlSegment[]) => Observable<boolean>' is not assignable to type '(route: Route, segments: UrlSegment[]) => boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree>'.
    Type 'Observable<boolean>' is not assignable to type 'boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree>'.

14     canLoad(route: Route, segments: UrlSegment[]): Observable<boolean>;
       ~~~~~~~


Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:15:5 - error TS2416: Property 'canActivate' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanActivate'.
  Type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => Observable<boolean>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => boolean | UrlTree | Observable<boolean | UrlTree> | Promise<...>'.    Type 'Observable<boolean>' is not assignable to type 'boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree>'.
      Type 'Observable<boolean>' is not assignable to type 'Observable<boolean | UrlTree>'.
        The types of 'source.operator.call' are incompatible between these types.
          Type '(subscriber: import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/angular-auth-oidc-client/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/nod...' is not assignable to type '(subscriber: import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/rxjs/dist/types/internal/Subscriber").Subscriber<any>, source: any) => import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/rxjs/dist/types/i...'.
            Types of parameters 'subscriber' and 'subscriber' are incompatible.
              Type 'Subscriber<any>' is missing the following properties from type 'Subscriber<any>': syncErrorValue, syncErrorThrown, syncErrorThrowable, _unsubscribeAndRecycle, and 2 more.

15     canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean>;
       ~~~~~~~~~~~

Error: node_modules/angular-auth-oidc-client/lib/interceptor/auth.interceptor.d.ts:14:5 - error TS2416: Property 'intercept' in type 'AuthInterceptor' is not assignable to the same property in base type 'HttpInterceptor'.
  Type '(req: import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/@angular/common/http/http").HttpRequest<any>, next: import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/@angular/common/http/http").HttpHandler) =>...' is not assignable to type '(req: import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/@angular/common/http/http").HttpRequest<any>, next: import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/@angular/common/http/http").HttpHandler) =>...'. Two different types with this name exist, but they are unrelated.
    Call signature return types 'Observable<HttpEvent<any>>' and 'Observable<HttpEvent<any>>' are incompatible.
      The types of 'source' are incompatible between these types.
        Type 'import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/angular-auth-oidc-client/node_modules/rxjs/internal/Observable").Observable<any>' is not assignable to type 'import("D:/HCR/repos/experiments/angular-only/oidc-angular-client-spike-v3/oidc-angular-client/node_modules/rxjs/dist/types/internal/Observable").Observable<any>'.

14     intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>;
       ~~~~~~~~~


Error: src/app/auth-config.module.ts:35:34 - error TS2345: Argument of type 'Promise<OpenIdConfiguration | undefined>' is not assignable to parameter of type 'Promise<OpenIdConfiguration> | Promise<OpenIdConfiguration>[]'.
  Type 'Promise<OpenIdConfiguration | undefined>' is not assignable to type 'Promise<OpenIdConfiguration>'.
    Type 'OpenIdConfiguration | undefined' is not assignable to type 'OpenIdConfiguration'.
      Type 'undefined' is not assignable to type 'OpenIdConfiguration'.

35   return new StsConfigHttpLoader(config$);
                                    ~~~~~~~`

**Expected behavior**
Should build successfully

**Comment by FabianGosebrink** [comment]
Duplicate to https://github.com/damienbod/angular-auth-oidc-client/issues/1178

**Comment by mac-bhaird** [comment]
yeps, downgraded rxjs to 6.6.7 and it compiled!
