### ISSUE TITLE
Question: Is it possible on user login, using code flow, automatically to login to all set configurations?

### ISSUE THREAD

**Issue by peterpa90** [damienbod/angular-auth-oidc-client#1205]
I am currently working on Angular application having different modules. Every module represents a different business logic, respectively different backend. To reduce the size of the token (due to roles etc.) I am currently using different clients (clientIds) for every module, where all of the clients are part of the same realm (Keycloak). This means I have several configurations of the Authentication Module (one per client).
Is it possible that on the login I actually create session (and generate tokens for every configuration), using the code flow? Currently I am simply checking into the app.component inside the this.oidcSecurityService.checkAuthMultiple() subscription if all configurations are authenticated and if no I simply trigger the this.oidcSecurityService.authorize() method passing the configId. Due to the fact that there is already a browser session existing the new client will receive its token etc without asking the user for the username and password over and over again. 
The issue is that during this whole process the user will see all of these redirects (for each configuration). Is it possible that this is done somehow in a background, so the user see actually only one redirection (for the first configuration which will create the session)?

**Comment by damienbod** [comment]
Hi @peterpa90 maybe :) 

If you login with the same configuration once, you could add a custom param for the prompt= none and the login will be silent, if you have already consented for the required scope But you still have the redirect. Maybe you could use the popup then so you have no redirects. The only way to get access tokens, is to do an Open ID Connect login using an SPA.

Greetings Damien
