### ISSUE TITLE
Code flow with AutoLogin guard loses query params

### ISSUE THREAD

**Issue by fomenkogregory** [damienbod/angular-auth-oidc-client#1206]
**Describe the bug**
`AutoLogin` guard loses query params when calls `canLoad` method.

**To Reproduce**
Precondition: Application with lazy modules, using codeflow. Route example:
```ts
  {
    path: 'example',
    loadChildren: () => import('./modules/example').then(m => m.ExampleModule),
    canActivate: [AutoLoginGuard],
    canLoad: [AutoLoginGuard]
  }
```

Steps:
1. User in not logged in
2. Go to some url with query params, for example 'localhost:4200/example?param=5'
3. Redirected to login page
4. Fill in credentials, log in.

`canLoad` method is called with `UrlSegment[]` as argument, BUT since `UrlSegment[]` don't contain any query params, when `routeToRedirect` is created, query params are lost. 
(reference in the newest version: `angular-auth-oidc-client/projects/angular-auth-oidc-client/src/lib/auto-login/auto-login-partial-routes.guard.ts:18`)
Then this url is saved to 'redirect' key in localStorage
(reference in the newest version: `angular-auth-oidc-client/projects/angular-auth-oidc-client/src/lib/auto-login/auto-login-partial-routes.guard.ts:41`)
And then when we get this url back it doesn't have any query params :( 

**Expected behavior**
Query params are saved to 'recirect' key in localStorage.

**Screenshots**
The screenshot from my debugging experience. It was taken right before redirecting to `?code=.......` url.
![image](https://user-images.githubusercontent.com/51916577/126340723-4ea019e1-fa34-4c5f-8344-72be98c867c7.png)

**Version of the library**
`"angular-auth-oidc-client": "11.6.11"`

**Comment**
I'm not sure if it was fixed in 12 version, but as far as I can see from this
`angular-auth-oidc-client/projects/angular-auth-oidc-client/src/lib/auto-login/auto-login-all-routes.guard.ts:20`
`angular-auth-oidc-client/projects/angular-auth-oidc-client/src/lib/auto-login/auto-login-partial-routes.guard.ts:18`
it still works the same.

**Comment by MyoMinLin** [comment]
I also facing same issue of missing query params when Url with query params are opened in new tab.

**Comment by FabianGosebrink** [comment]
I just tried it out in Version 12 and for me this works. The route `protected?henlo=furiend` gets written into the storage and is being applied afterwards.

![image](https://user-images.githubusercontent.com/11268349/126876791-6e92b2b1-f003-4e10-9c87-a57329b43f8a.png)

Can you try out V12 please? You have to update Angular to V12 too then.

**Comment by thatsmeta** [comment]
This is definitely still an issue in V12. The query params are lost when **canLoad** is used. As described by @fomenkogregory, canLoad does not seem to receive the query params and therefore is not able to pass them on to the checkAuth() method.

**Comment by MyoMinLin** [comment]
@FabianGosebrink 
I'm sorry as the issue is happening because of our custom code which removes query string.
It is okay now and no issue.
Sorry for being inconvenience.
