### ISSUE TITLE
is not assignable errors after upgrading application to ng12.1.3 + angular-auth-oidc-client v12.0.2

### ISSUE THREAD

**Issue by greyghostbrewery** [damienbod/angular-auth-oidc-client#1209]
After upgrading my application to Angular 12 and the angular-auth-oidc-client package to v12, I get the below errors when compiling. Any help appreciated.

Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:14:5 - error TS2416: Property 'canLoad' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanLoad'.
  Type '(route: Route, segments: UrlSegment[]) => Observable<boolean>' is not assignable to type '(route: Route, segments: UrlSegment[]) => boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree>'.
    Type 'Observable<boolean>' is not assignable to type 'boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree>'.

14     canLoad(route: Route, segments: UrlSegment[]): Observable<boolean>;
       ~~~~~~~


Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:15:5 - error TS2416: Property 'canActivate' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanActivate'.
  Type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => Observable<boolean>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => boolean | UrlTree | Observable<boolean | UrlTree> | Promise<...>'.
    Type 'Observable<boolean>' is not assignable to type 'boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree>'.
      Type 'Observable<boolean>' is missing the following properties from type 'Observable<boolean | UrlTree>': map, flatMap, mergeMap, catch, _catch

15     canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean>;
       ~~~~~~~~~~~

Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:16:5 - error TS2416: Property 'canActivateChild' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanActivateChild'.
  Type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => Observable<boolean>' is not assignable to type '(childRoute: ActivatedRouteSnapshot, state: RouterStateSnapshot) => boolean | UrlTree | Observable<boolean | UrlTree> | Promise<...>'.
    Type 'Observable<boolean>' is not assignable to type 'boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree>'.

16     canActivateChild(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean>;
       ~~~~~~~~~~~~~~~~


Error: node_modules/angular-auth-oidc-client/lib/interceptor/auth.interceptor.d.ts:14:5 - error TS2416: Property 'intercept' in type 'AuthInterceptor' is not assignable to the same property in base type 'HttpInterceptor'.
  Type '(req: import("/node_modules/@angular/common/http/http").HttpRequest<any>, next: import("/node_modules/@angular/common/http/http").HttpHandler) => import("/...' is not assignable to type '(req: import("/node_modules/@angular/common/http/http").HttpRequest<any>, next: import("/node_modules/@angular/common/http/http").HttpHandler) => import("/...'. Two different types with this name exist, but they are unrelated.
    Type 'Observable<HttpEvent<any>>' is missing the following properties from type 'Observable<HttpEvent<any>>': map, flatMap, mergeMap, catch, _catch

14     intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>;
       ~~~~~~~~~

**Comment by FabianGosebrink** [comment]
Hey, please check the rxjs version you are running. Did you upgrade this by yourself? Duplicate as the same in https://github.com/damienbod/angular-auth-oidc-client/issues/1178 and https://github.com/damienbod/angular-auth-oidc-client/issues/1204

**Comment by greyghostbrewery** [comment]
upgrade of rxjs & rxjs-compat to v6.6.7 appears to fix the problem.  I thought I searched thoroughly for an existing issue - obviously didn't search well enough.  Thanks for the help!
