### ISSUE TITLE
Interceptor works, after reload the page in firefox

### ISSUE THREAD

**Issue by gundogduhasan** [damienbod/angular-auth-oidc-client#1211]
Interceptor works fine in chrome. But in firefox it working after one refresh. Here is my interceptor code;

```
 intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        Observable
        const authObservable: any = this.oidcSecurityService.checkAuth();

        return authObservable.pipe(
            switchMap((loginResponse: any) => {

                if (loginResponse.isAuthenticated) {
                    request = request.clone({
                        setHeaders: {
                            Authorization: `Bearer ${loginResponse.accessToken}`
                        }
                    });
                }
                    
                return next.handle(request);
            }));

    }
```

**Comment by FabianGosebrink** [comment]
Hey, are you running the latest version of the lib? Thanks.

**Comment by gundogduhasan** [comment]
Hi. I think its last vesion. Lib version is "12.0.2".

Many thanks.

**Comment by FabianGosebrink** [comment]
Can you reproduce this behavior if you're using the [http-interceptor](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/using-access-tokens#http-interceptor) from the lib?

**Comment by gundogduhasan** [comment]
Thanks for your quick responses. I chanced my interceptor line in app module and configure secure routes like this;
 ```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    CommonModule,
    FormsModule,
    SharedModule,
    MatSidenavModule ,
    AuthModule.forRoot({
      config: {
        authority: environment.api.auth,
        redirectUrl: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        clientId: '<client-id>',
        scope: 'openid profile role api',
        responseType: 'id_token token',
        secureRoutes: ['http://localhost:4200','http://192.168.1.44:4200'],
       // silentRenew: true,
        silentRenewUrl:window.location.origin+"/silent-renew.html",
        useRefreshToken: true, 
        logLevel: LogLevel.Debug,
      },
    }),
    HttpClientModule
  ],
  providers: [
    NgbActiveModal,
   // { provide: HTTP_INTERCEPTORS, useClass: AccessTokenInterceptor, multi: true },
   { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
  ],
  bootstrap: [AppComponent]
})
```
But access token doesn't add to request header. Did i doing something wrong?

**Comment by FabianGosebrink** [comment]
Where are you firing the calls to, or: What is the URL of your backend?

**Comment by gundogduhasan** [comment]
I am working in local right now.

My IDS4 url : http://localhost:5000
My APi url want to protect : http://localhost:50571
My client url : http://localhost:4200

Maybe i misunderstood you. Sorry about that.

**Comment by gundogduhasan** [comment]
@FabianGosebrink  Are these what you want or you ask a different thing?

**Comment by FabianGosebrink** [comment]
No that's fine. But if you want the token to be attached to requests to your backend, you have to pass the backend url to the `secureRoutes` property of the config.

**Comment by gundogduhasan** [comment]
I tried that too. I set secureRootes with my all api url and client url. But still same issue in firefox.

**Comment by FabianGosebrink** [comment]
Can you take a sample from the samples in this lib and reproduce the issue?

**Comment by gundogduhasan** [comment]
Actually i look at samples but i dont find any sample for intercepter. Most of them about refresh token. Can you recommend a sample for interceptor?

**Comment by FabianGosebrink** [comment]
We need any sample repo with a config taken from our samples which shows us the issue you are facing. You can do one on your own if you like. `ng new` and add everything which is needed and then provide us the sample. Thanks!

**Comment by gundogduhasan** [comment]
Okay. I will setup a new sample repo and let you know. Many thanks

**Comment by gundogduhasan** [comment]
I solved this issue changing my interceptor code like this;
   ```
 intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        const token = this.oidcSecurityService.getAccessToken();

        if (!token)
            return next.handle(request);

        request = request.clone({
            setHeaders: {
                Authorization: `Bearer ${token}`
            }
        });

        return next.handle(request);
    }
```
I guess, using an another observable in intercept method causing the problem. Many thanks for your help.

**Comment by FabianGosebrink** [comment]
Glad that this is solved. But your interceptor code makes no sense. If you are not having a token, you want to set it, but you early return before. Maybe you did not post all of your code. But if it works for you, I am glad this is solved :)

**Comment by gundogduhasan** [comment]
Thanks for your help @FabianGosebrink Actually i solve this with this library source code. Libs interceptor doesn't have any observable except next.handle. Only thing missing my interceptor are congfig handlers. Libs source code like this;
```
intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (!this.configurationProvider.hasAsLeastOneConfig()) {
      return next.handle(req);
    }

    const allConfigurations = this.configurationProvider.getAllConfigurations();
    const allRoutesConfigured = allConfigurations.map((x) => x.secureRoutes || []);
    const allRoutesConfiguredFlat = [].concat.apply([], allRoutesConfigured);

    if (allRoutesConfiguredFlat.length === 0) {
      const { configId } = allConfigurations[0];
      this.loggerService.logDebug(configId, `No routes to check configured`);

      return next.handle(req);
    }

    const { matchingConfigId, matchingRoute } = this.closestMatchingRouteService.getConfigIdForClosestMatchingRoute(req.url);

    if (!matchingConfigId) {
      const { configId } = allConfigurations[0];
      this.loggerService.logDebug(configId, `Did not find any configured route for route ${req.url}`);

      return next.handle(req);
    }

    this.loggerService.logDebug(matchingConfigId, `'${req.url}' matches configured route '${matchingRoute}'`);

    const token = this.authStateService.getAccessToken(matchingConfigId);

    if (!token) {
      this.loggerService.logDebug(matchingConfigId, `Wanted to add token to ${req.url} but found no token: '${token}'`);

      return next.handle(req);
    }

    this.loggerService.logDebug(matchingConfigId, `'${req.url}' matches configured route '${matchingRoute}', adding token`);
    req = req.clone({
      headers: req.headers.set('Authorization', 'Bearer ' + token),
    });

    return next.handle(req);
  }

```
I would like to solve this issue with correct way :) If i am doing anything wrong i would like to know

**Comment by FabianGosebrink** [comment]
I am confused. You are using the interceptor of the lib now, and it works? So the code you posted [here](https://github.com/damienbod/angular-auth-oidc-client/issues/1211#issuecomment-886818225) is NOT your current code. Is that correct?

**Comment by gundogduhasan** [comment]
Sorry for the misunderstanding. It is my current code. My old code has observable variable [here](https://github.com/damienbod/angular-auth-oidc-client/issues/1211#issue-952033521). And i look at libs interceptor source code. There is no observable in source code. And i delete observable variable from my code and it works.

I try to use libs "AuthInterceptor" today and i am getting this console message "Did not find any configured route for route" "/Company?$filter= isDeleted.....". I guess its related with the secure routes like you said. But i added my all routes to secure routes. Do i have add routes with all addresses. Like "test-url.com","test-url.com/Company"?
