### ISSUE TITLE
Question: With an existing forRoot, how do I provide a configuration for AuthModule

### ISSUE THREAD

**Issue by mac-bhaird** [damienbod/angular-auth-oidc-client#1215]
Our structure is a library (called LibModule) that we use for multiple internal apps. It already has a forRoot, and in APP_INITIALIZER, we populate a ConfigService from a json file, with the information needed by AuthModule, as well as some other bits (we are currently using another auth library we want to move away from).

How can we get the config information into AuthModule under this scenario?

Here's the base bits at play:

AuthConfigModule
```
@NgModule(
<not sure what to do here or below>,
	exports: [AuthModule]
)
```

LibModule
```
export class LibModule{
	Static forRoot(): ModuleWithProviders<LibModule>{
		return {
			Providers: [
				{
				provide: APP_INITIALIZER,
				useFactory: configServiceFactory,
				deps: [ConfigService,AppConfig],
				multi: true,
				}
			]
		}
	}
}
```

AppModule
```
@NgModule({
	imports: [
		LibModule.forRoot()
	]
})
```

**Comment by FabianGosebrink** [comment]
Hey, thanks for this. Can you provide the AuthMOdule on `AppModule` level?

**Comment by mac-bhaird** [comment]
Correct, the reading of the config is in LibModule and it has what is needed for the auth

**Comment by FabianGosebrink** [comment]
Normally loading a configuration is app responsibility and with the loaded config you can configure the libs imho. But that is just my 2 cents :) I personally read my configuration outside of angular with the fetch api and pass it into the `platformBrowserDynamic` method to avoid any of those issues.

```
fetch('/path/to/config.json')
  .then((response) => response.json())
  .then((config) => {
    if (environment.production) {
      enableProdMode()
    }

    platformBrowserDynamic([{ provide: APP_CONFIG, useValue: config }])
      .bootstrapModule(AppModule)
      .catch((err) => console.error(err))
  })
```

But if you do this you can use the `StsStaticLoader` to provide config which is read from a service.

Something like this

```
imports: [
  AuthModule.forRoot(
    { 
	  loader: 
      { 
        provide: StsConfigLoader, 
        useFactory: configureAuth, 
        deps: [ConfigService], 
      }, 
    });
 ]
```

**Comment by mac-bhaird** [comment]
@FabianGosebrink , thanks for this, digging into it now, will let you know soon how things are looking!

**Comment by FabianGosebrink** [comment]
Added a documentation about this [here](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#getting-static-config-from-a-service-sync)
