### ISSUE TITLE
forceRefreshSession not working with "angular-auth-oidc-client": "^12.0.0"

### ISSUE THREAD

**Issue by garvraj** [damienbod/angular-auth-oidc-client#1216]
I am using "angular-auth-oidc-client": "^12.0.0" with angular 12 and trying to refresh my token explicitly , Its not working 

I am using below method
forceRefreshSession() {
    return this.oidcSecurityService.forceRefreshSession();
  }

**Comment by FabianGosebrink** [comment]
Hey,

the method is returning an observable. Do you subscribe to it? https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api#forcerefreshsessioncustomparams----configid-string

Hint: The text in the template in GitHub here when raising an issue are placeholders which are meant to be filled out 🙂

Thanks

Fabian

**Comment by garvraj** [comment]
> Hey,
> 
> the method is returning an observable. Do you subscribe to it? https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api#forcerefreshsessioncustomparams----configid-string
> 
> Hint: The text in the template in GitHub here when raising an issue are placeholders which are meant to be filled out 🙂
> 
> Thanks
> 
> Fabian

I was trying to call forceRefreshSession without passing any parameter , may be that's the issue

**Comment by FabianGosebrink** [comment]
Hey, thanks for the answer. The method does not need a parameter. You can pass one, but you do not have to. Do you subscribe to it?

**Comment by garvraj** [comment]
Yes I did subscribe, Below is my code 
=======================
    this.authenticationService.forceRefreshSession().subscribe((result) =>
      console.log(result)
    )

And in my authenticationService
==================
 forceRefreshSession() {
    return this.oidcService.forceRefreshSession();
  }

**Comment by FabianGosebrink** [comment]
Hey, thanks. What exactly does not work? Does it not fire a request? Does it not refresh? Can you provide a sample repo with a config from our samples to reproduce the issue?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
