### ISSUE TITLE
After logging in with IDP, Access token is not injected in 1st api call.

### ISSUE THREAD

**Issue by alpesh1988** [damienbod/angular-auth-oidc-client#1218]
**Describe the bug**
The user is redirected to IDP login screen when not logged in. User logs in IDP and coming back to angular application(e.g. URL: host/dashboard). In dashboard page, there is one api call but eventually it is being rejected with 401-Unauthorized even though user is logged in.

**Expected behavior**
Once user is logged in, There should not be 401 unauthorized error in following page after login in.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. Chrome Version 92.0.4515.107 (Official Build) (64-bit)]

**Additional context**
Once the user is logged into IDP and comes back to "/dashboard" page, It throws 401-unauthorized error but if you go to another page "/contact" (includes api call), it works meaning token in injected in api calls. Subsequent api calls work fine including injecting token.

**Comment by FabianGosebrink** [comment]
Can you provide a sample repo for this? The auth has to be set up first before making the call. So what SPAs normally do is to have a callback route, which does exactly this, and then redirects to the dashboard route for example to avoid this issue. Or you fire the request in the subscribe of the `checkauth` call, depending on your code.

**Comment by alpesh1988** [comment]
I used auto-login https://nice-hill-002425310.azurestaticapps.net/docs/documentation/auto-login and then this issue is resolved. Hence, closing this issue 👍
