### ISSUE TITLE
Can't get it run with my own Azure B2C

### ISSUE THREAD

**Issue by mduu** [damienbod/angular-auth-oidc-client#1222]
I tried the 'Quick Start' as well as the sample. But it seems not to work with my own Azure B2C. The best I got was that after a login I gut "userData" set but still "isAuthenticated" set to false. I removed my user-flow (don't need them yet) and tried various configurations but could not get it run.

My main problem is that I don't know what to set up in Azure B2C and what to configure in your library. What Url's to use etc.? Is there any documentation / sample including the Azure B2C part and what values to put where in the library configuration?

Version used:
- angular-auth-oidc-client 12.0.2
- Angular 12.1.0

**Comment by damienbod** [comment]
@mduu I'll improve the Azure B2C config docs then in this blog. Maybe you can see some different to yours already.

https://damienbod.com/2020/05/14/securing-an-angular-application-using-azure-b2c/

I would have time for a while a few days, got a lot on at the moment.

Greetings Damien

**Comment by damienbod** [comment]
Hi @mduu Going through this now and all is working. I use an Azure B2C user flow and the authority and the well known endpoint points need to match this. Have you setup the Azure B2C user flow? 

Greetings Damien

**Comment by mduu** [comment]
@damienbod Yes but just the default one. Tried to remove them but didn’t work either. My main issue is that I am not sure what B2C values to fill in which config fields.

**Comment by damienbod** [comment]
Hi mduu, I'' try to add docs for this then, the default App registration or a Azure B2C user flow requires different settings. If using Azure B2C, you should probably be using a user flow. 

Greetings Damien

**Comment by mduu** [comment]
@damienbod  I think that makes sense. If one seriously use Azure B2C one will probably end using custom-flows.
