### ISSUE TITLE
Custom storage not working

### ISSUE THREAD

**Issue by ZeSzymi** [damienbod/angular-auth-oidc-client#1225]
**Describe the bug**
When I add custom storage to config i get 
```
_a.getItem is not a function at BrowserStorageService.read (browser-storage.service.ts:17)
```

**To Reproduce**
[Stack Blitz](https://stackblitz.com/edit/angular-ivy-o6eegz?file=src/app/app.module.ts)

**Expected behavior**
Oidc client should use custom storage

**Screenshots**
![image](https://user-images.githubusercontent.com/34967702/128728989-195391c1-c701-48ac-a1e5-c95924456f1c.png)

**Comment by FabianGosebrink** [comment]
Hey thanks for reporting. I will take a look at this to make it easier and/or document it better.

Thanks, will keep you posted here.

Fabian

**Comment by FabianGosebrink** [comment]
Okay, I can reproduce the issue and will provide a fix with a PR when I looked into it.

**Comment by FabianGosebrink** [comment]
Is fixed and should be available in the next release. Check the new docs :) [here](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/features#custom-storage)
