### ISSUE TITLE
Guarded page is loaded, while token is null

### ISSUE THREAD

**Issue by KnulstBDH** [damienbod/angular-auth-oidc-client#1232]
Hi,

I'm using the angular-auth-oidc-client guards feature to deny access to the pages for unauthorized users. I've set "canActivate" to AutoLoginAllRoutesGuard on every page except for a redirection route; which routes '' to my first page (let's call it Page1).
When Page1 is loaded, a get request is sent to the server, which looks like this:

```
async get(url: string, params?: any){
    const token = this.oidcSecurityService.getAccessToken();
    
    return await this.http.get<any>(
      this.baseUrl + url, {
      headers:{
        "Authorization": 'Bearer ' + token,
        ...}
        }
       );
}
```

My expectation is that when I open the app, it will try to load Page1. The guard will check whether I am authorized, by checking the token & expiration time. If the time has been exceeded, the OIDCService will refresh it, since silence renew and useRefreshToken are both true in my config. 
Once it has been refreshed or the token was still valid, it will let the user load Page1. Loading Page1 will then automatically execute the get request.

However when I open my app, Page1 is loaded and my log returns unauthorized as a result from my get request, due to the OIDCService.getAccessToken() returning null.

If my accesstoken is null, shouldn't access to my page been denied by the guard (so my get request shouldn't been called, because Page1 wasn't loaded)?

**Comment by FabianGosebrink** [comment]
Hey, do you have _all_ your routes guarded in your application, or do you have only _some_ routes guarded in your app?

**Comment by KnulstBDH** [comment]
Hi Fabian,

Just to make sure, I added the guard to my redirect and to my postlogout page.
I even tried to match the example from the docs, which looks like this:
```
import { AutoLoginAllRoutesGuard } from 'angular-auth-oidc-client';

const appRoutes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'home' },
  { path: 'home', component: HomeComponent, canActivate: [AutoLoginAllRoutesGuard] },
  { path: 'protected', component: ProtectedComponent, canActivate: [AutoLoginAllRoutesGuard] },
  { path: 'forbidden', component: ForbiddenComponent, canActivate: [AutoLoginAllRoutesGuard] },
  {
    path: 'customers',
    loadChildren: () => import('./customers/customers.module').then((m) => m.CustomersModule),
    canLoad: [AutoLoginAllRoutesGuard],
  },
  { path: 'unauthorized', component: UnauthorizedComponent },
];
```

As you can see, the example shows that the redirect and unauthorized paths, do not have a guard.
One other thing I tried was to switch using canLoad instead of canActivate for Page1, because my theory is that the page gets loaded (therefore executing the get request), while it is unauthorized.
However that did not change anything either.

Lastly I've tried all of the above in different combinations, but still the issue occurs regularly.  

I will try AutoLoginPartial after posting this comment and will update on that whether that works or not.

**Comment by FabianGosebrink** [comment]
`CanLoad` is for lazy loading modules, childRoutes, etc., `CanActivate` is for pages which are already loaded. https://angular.io/api/router/CanLoad. Depending on what Guard you use, you have to call `checkAuth()` manually. https://nice-hill-002425310.azurestaticapps.net/docs/documentation/auto-login

**Comment by KnulstBDH** [comment]
Hi Fabian,

The issue was that a service, that was loaded on app.component, injected another service that was responsible for the data of Page1. So the get request got executed before the guard of Page1 could validate and refresh the token. Therefore the get request responded with unauthorized on Page1, but got called again after the guard got the new token.
