### ISSUE TITLE
AAD Mutli-tenant application

### ISSUE THREAD

**Issue by maxcl10** [damienbod/angular-auth-oidc-client#1238]
Hello,
I'm currently using your library using Azure AD with single tenant. (1frontend + 1API).
We need to switch our app to be multi-tenant.
I made some changes according to the Microsoft documentation (MSAL) but I want to continue using your library.
Here is my modified config:

```
 stsServer: 'https://login.microsoftonline.com/organizations/v2.0',
       redirectUrl: window.location.origin,
      clientId: 'xxx',
      scope:
        'openid profile api://yyyyy/.default',

      responseType: 'code',
      silentRenew: true,
      useRefreshToken: true,
      maxIdTokenIatOffsetAllowedInSeconds: 600,
      issValidationOff: true, // this is required for multi tenant app as the issuer is not valid with Azure
      autoUserinfo: false,
      logLevel: LogLevel.Debug,
      

      customParams: {
        prompt: 'select_account', // login, consent, select_account
      },
      secureRoutes: [
        'https://localhost:44319/', 
      ],
```
But it is not working. I'm able to enter the credential from another tenant but then get an error instead of getting the conscent window. 

1 - Does your library support AAD multi-tenant?
2 - If yes do you have any code sample?
3 - If no do you have any idea why it is failing?

Regards

**Comment by damienbod** [comment]
Hi @maxcl10 I think you need to use the common endpoint for the stsServer. If this does work, let me know and I'll get an example, or make it, I have used to with a client 

Greetings Damien

**Comment by maxcl10** [comment]
Thanks Damian. It is working like a charm. Thanks
