### ISSUE TITLE
getting below error while using silent renew 

### ISSUE THREAD

**Issue by maninder93** [damienbod/angular-auth-oidc-client#1239]
<img width="958" alt="error slient renew" src="https://user-images.githubusercontent.com/86960322/130186934-82dae2f7-a656-4d5f-9945-ae774f2d52e5.PNG">

hi getting below error while using silent renew can you please help

no code in url

or 

chromewebdata/:1 Refused to display 'https://lxb2cdev.b2clogin.com/' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by damienbod** [comment]
You try to refresh the session using iframe silent renew. This is disabled on your IDP server. Either you allow iframe access from the Angular client or you use refresh tokens. 

Greetings Damien

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
