### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#124]

**Comment by DooMachine** [comment]
Is it working or just me doing something wrong? Same configuration used in Angular 4.1.2 project and getting error.
Angular 5.x Universal & ASP.NET Core 2.0 advanced starter-kit

`ERROR TypeError: Cannot read property 'split' of null
    at OidcSecurityValidation.getPayloadFromToken (angular-auth-oidc-client.es5.js?8f98:630)
    at OidcSecurityValidation.isTokenExpired (angular-auth-oidc-client.es5.js?8f98:499)
    at SafeSubscriber.eval [as _next] (angular-auth-oidc-client.es5.js?8f98:1777)`

**Comment by damienbod** [comment]
@robisim74 only way to support this is to update with a breaking change, do you see it this way?
 angular 5 onwards dependencies
Greetings Damien

**Comment by robisim74** [comment]
@damienbod Do I have hallucinations? Was there a issue here or not?

However, in my opinion the library should be compatible with Angular v5. If you want switch to Angular v5 with breaking changes, the starter is ready, and I can do the update quickly. Let me know.

**Comment by damienbod** [comment]
ERROR in ./angularApp/main-aot.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in 'C:\git\angular2Tests\angular-auth-oidc-sample-google-openid\src\AngularClient\angularApp'
 @ ./angularApp/main-aot.ts 4:0-64

ERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (C:\git\angular2Tests\angular-auth-oidc-sample-google-openid\src\AngularClient\node_modules\@angular\compiler-cli\src\ngtools_api.js:78:11)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\git\angular2Tests\angular-auth-oidc-sample-google-openid\src\AngularClient\node_modules\@angular\compiler-cli\src\ngtools_api.js:31:15)
    at _donePromise.Promise.resolve.then (C:\git\angular2Tests\angular-auth-oidc-sample-google-openid\src\AngularClient\node_modules\@ngtools\webpack\src\plugin.js:430:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

ERROR in C:/git/angular2Tests/angular-auth-oidc-sample-google-openid/src/AngularClient/angularApp/main-aot.ts (5,36): Cannot find module './app/app.module.ngfactory'.

**Comment by damienbod** [comment]
I would prefer not to switch is this is possible

**Comment by robisim74** [comment]
This error is not related to the library: simply, AoT compilation has not been updated in the host app (for example, using AngularCompilerPlugin)

**Comment by damienbod** [comment]
[0] ./node_modules/html-webpack-plugin/lib/loader.js!./angularApp/index.html 397 bytes {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-webpack-visualstudio@3.0.0 webpack-production: `webpack --env=prod`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-webpack-visualstudio@3.0.0 webpack-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Damien.bowden\AppData\Roaming\npm-cache\_logs\2017-11-03T20_48_29_231Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-webpack-visualstudio@3.0.0 build-production: `npm run webpack-production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-webpack-visualstudio@3.0.0 build-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Damien.bowden\AppData\Roaming\npm-cache\_logs\2017-11-03T20_48_29_284Z-debug.log

**Comment by robisim74** [comment]
Which example are you trying to update?

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-sample-google-openid/tree/dev_5

**Comment by robisim74** [comment]
Give me some minute...

**Comment by DooMachine** [comment]
Using Angular 5.x Universal & ASP.NET Core 2.0 advanced starter-kit
While listening some animal screaming in checkSession iframe, I get an error at console:

> ERROR TypeError: Cannot read property 'config_validate_response_type' of undefined
    at OidcSecurityService.authorize (angular-auth-oidc-client.es5.js?8f98:1341)
    at NavAuthComponent.login (navauth.component.ts?c613:73)
    at SafeSubscriber.eval [as _next] (navauth.component.ts?c613:37)

**Comment by damienbod** [comment]
Thanks, I think I found it, looks like I have build problems due to the typescript upgrade, I making silly mistakes now, time to stop for the day.

**Comment by robisim74** [comment]
@DooMachine you are posting and removing your issues here, but the errors you are getting do not seem to be due to Angular 5. Please open new issues and provide more information.

**Comment by DooMachine** [comment]
@robisim74 ah, sorry about that. But, I could not find any other explanation.

**Comment by robisim74** [comment]
@damienbod 
- you still have the old `main-aot.js` file (which is wrong): https://github.com/damienbod/angular-auth-oidc-sample-google-openid/blob/master/src/AngularClient/angularApp/main-aot.js: remove it
- you are using `"strict": true,` in tsconfig-aot, that means `strictNullChecks`: are you sure you want to use it?

Then the app works.

**Comment by damienbod** [comment]
closing this. Angular 5 is fine. @DooMachine please create a new issue. @robisim74 thanks for yu help.

Greetings Damien
