### ISSUE TITLE
/?code= and /unauthorized when returning back after login

### ISSUE THREAD

**Issue by patolax** [damienbod/angular-auth-oidc-client#1240]
We use identity server 4 and library v12 version.  We observed following behaviour when returning back after login. After successful login from identity server, client is momentarily navigated to `/unauthorized` and  /?code= few times (more than 2) before ending up at the default route.  In our router we use `AutoLoginAllRoutesGuard`.

Is this the desired behaviour? 

**Angular client & IdentityServer4 error logs** 
```

Failed to load resource: the server responded with a status of 400 (Bad Request)
main-es2017.2ccacc5a448992298786.js:1 [ERROR] 0-my_angular_client - OidcService code request https://mysolutions.at/auth 
logErrorWithConfig @ main-es2017.2ccacc5a448992298786.js:1
main-es2017.2ccacc5a448992298786.js:1 [ERROR] 0-my_angular_client - authorizedCallback, token(s) validation failed, resetting. Hash: 



fail: IdentityServer4.Validation.TokenRequestValidator[0]
      Invalid authorization code{ code = qW57yUOtFJNcwk03jT16t_4QgxtcWPWYWLWvGyebBu0 }, details: {
        "ClientId": "my_angular_client",
        "ClientName": "My Client",
        "GrantType": "authorization_code",
        "AuthorizationCode": "qW57yUOtFJNcwk03jT16t_4QgxtcWPWYWLWvGyebBu0",
        "Raw": {
          "grant_type": "authorization_code",
          "client_id": "my_angular_client",
          "code_verifier": "c5c63ca5493d8e0889dfa30fbefd78526acf188edf9727a0b1d8561dd969XyF5QZm",
          "code": "qW57yUOtFJNcwk03jT16t_4QgxtcWPWYWLWvGyebBu0",
          "redirect_uri": "http://localhost:7100/client/"
        }
      }
```

**Comment by FabianGosebrink** [comment]
Have you made sure that the guard is the correct one (check the docs for the info please) and that you do not call `checkAuth()` for yourself if you are using the `...AllRoutesGuard`?

**Comment by patolax** [comment]
if we remove` checkAuth()`, after login application does not load. it redirects rapidly endlessly with /?code= redirects with different hashes.  Behaviour does not change if `AutoLoginPartialRoutesGuard `used.

**Comment by FabianGosebrink** [comment]
Can you provide a sample repo with one if our sample configs?

**Comment by FabianGosebrink** [comment]
Have you solved the issue?

**Comment by patolax** [comment]
No, its not resolved. But I this question is the best way to explain the issue I am facing. Its related to /connect/token request.

**Comment by FabianGosebrink** [comment]
But can you post code or provide a sample repo to reproduce the issue? Maybe then we can solve the issue together.

**Comment by patolax** [comment]
The issue was calling checkAuth() while using AutoLoginAllRoutesGuard. removing it resolved the issue.
