### ISSUE TITLE
nbf claim validation always fails on clients with negative clock drift

### ISSUE THREAD

**Issue by seabass223** [damienbod/angular-auth-oidc-client#1242]
**Is your feature request related to a problem? Please describe.**
clients with negative clock drift cannot receive a valid token because nbf validation always fails on the front end. 

**Describe the solution you'd like**
https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5
rfc states that nbf is optional and can usually be set to a few minutes.  Configuration has maxIdTokenIatOffsetAllowedInSeconds but no maxIdTokenNbfOffsetAllowedInSeconds

**Describe alternatives you've considered**
I could allow for clock drift in my idp code, but i may not always have control of an IDP. leeway is usually handled on the client side.

**Comment by damienbod** [comment]
Hi @seabass223 You can allow a larger window for this validation on the client of the clock skew or you can completely disable it. The nbf claim is not validated, but you can add this yourself if you want as you have access to the id_token.

Greetings Damien

**Comment by seabass223** [comment]
Thanks, I'll give it a go!
