### ISSUE TITLE
/connect/token request fails with 400 (Bad Request) but authentication is successful 

### ISSUE THREAD

**Issue by patolax** [damienbod/angular-auth-oidc-client#1244]
In production and even locally /connect/token request fails with following response. However authentication is successful even though this request fails.

{"error":"invalid_grant"}

![image](https://user-images.githubusercontent.com/29444156/131452050-db219157-a4c1-4b64-adcc-d75834deb536.png)

When this request fails the library redirect the application to /UnauthorizedComponent, but some how manages to authenticate successfully. 

Is this a bug or error in implementation?

**Comment by damienbod** [comment]
invalid_grant => seems like your IDP is not configured for your angular client correctly. You can compare to the examples. For more support, please provide 

-  the module configuration
- The IDP setup and what IDP you are using
- info if you use guards or not

Greetings Damien

**Comment by patolax** [comment]
@damienbod we use Identity server 4.

Only guard that work is AutoLoginAllRoutesGuard, but we also tried AutoLoginPartialRoutesGuard as well. That did not work in prouction.

We are using the latest version of the Lib. 

(this issue popped up only after we upgraded the lib from v7 to v12).

```
export const identityConfigFactory = (configLoader: ConfigLoaderService<IdentityConfig>) => {
  console.log('httpLoaderFactory', environment.identityConfigFile);
  const config$ = new Promise<OpenIdConfiguration>(async (resolve) => {
    const identiyCfg = await configLoader.load(environment.identityConfigFile);
  
    const openIdConfiguration = <OpenIdConfiguration>{
      authority: identiyCfg.authority,
      redirectUrl: identiyCfg.redirect_url,
      clientId: identiyCfg.client_id,
      responseType: 'code',
      scope: identiyCfg.scope,
      postLogoutRedirectUri: identiyCfg.post_logout_redirect_uri,
      startCheckSession: false,
      silentRenew: true,
      silentRenewUrl: identiyCfg.silent_renew_url,
      postLoginRoute: identiyCfg.post_login_route,
      forbiddenRoute: identiyCfg.forbidden_route,
      unauthorizedRoute: identiyCfg.unauthorized_route,
      logLevel: LogLevel.Debug,
      maxIdTokenIatOffsetAllowedInSeconds: 60,
      historyCleanupOff: true,
    };
    console.log('ConfigLoaderService.load end', environment.identityConfigFile, identiyCfg);
    resolve(openIdConfiguration);
  });
  return new StsConfigHttpLoader(config$);
};

@NgModule({
  imports: [
    AuthModule.forRoot({
      loader: {
        provide: StsConfigLoader,
        useFactory: identityConfigFactory,
        deps: [IDENTITY_SERVER_CONFIG],
      },
    }),
  ],
  exports: [AuthModule],
})
export class AuthConfigModule { }

```

**Comment by patolax** [comment]
The issue was calling checkAuth() while using AutoLoginAllRoutesGuard. removing it resolved the issue.
