### ISSUE TITLE
Issues while using refresh tokens v11.6.4

### ISSUE THREAD

**Issue by viswadv** [damienbod/angular-auth-oidc-client#1245]
Hello,
Our app is using v11.6.4, when refresh tokens flag is turned on, we see multiple issues here

Issue1:  If the refresh token value has + character its been replaced with empty space (could be because of oneLineTrim) which causes 400 error(invalid grant).

Issue2:  When token is fine,refresh grant call gets 200 but chrome shows Failed to load Response data, it makes 3 attempts later calls /slo and redirects user to post redirect uri.

Issue3: To test this behavior properly we reduced our token expiry time to 5mins and token call gets successful with response loaded after the first attempt it never makes another attempt with the new refresh token to keep the user active.

@damienbod Please help me understand what to do to make this work correctly.

**Comment by viswadv** [comment]
Issue1: If the refresh token value has + character its been replaced with empty space (could be because of oneLineTrim) which causes 400 error(invalid grant).

This one is sorted for our end.

**Comment by damienbod** [comment]
Closing this as Angular is now V13
