### ISSUE TITLE
Upgrade to RxJs 7.x

### ISSUE THREAD

**Issue by sergiubologa** [damienbod/angular-auth-oidc-client#1246]
**Is your feature request related to a problem? Please describe.**
Angular 12 supports RxJs 7.x and currently this lib works only with the 6 version. Unfortunately, I can't use it in a project that uses RxJs 7.

**Describe the solution you'd like**
Support RxJs 7.x

**Describe alternatives you've considered**
Because I also have other dependencies that require RxJs 7 I don't really have an alternative. One thing that might work is to `// @ts-ignore` the error that might arise.

**Comment by FabianGosebrink** [comment]
Hey, thanks for the issue. If we support rxjs 7 we have to check if it would work with rxjs 6 projects as well. If it does, we can upgrade. Otherwise, we would like to stick to the deps aligning with the deps you get when doing an `ng new ...`

**Comment by FabianGosebrink** [comment]
Updated to Angular 13 and RxJs 7. Enjoy.
