### ISSUE TITLE
Getting claims back

### ISSUE THREAD

**Issue by JT2011** [damienbod/angular-auth-oidc-client#1247]
I am working to upgrade from a different oidc javascript wrapping library, to this one, and one of the things I was able to do was gather the claims from the logged in user to display things like the name in a profile page. With this project, the setup to connect to identity server was pretty simple, but I am having trouble figuring out how to get back a list of the available claims, such as 'name', etc. utilizing the OidcSecurityService.

Any guidance on how that is now possible would be appreciated

**Comment by damienbod** [comment]
Hi @JT2011 The userData can be used for this. If you use the user info endpoint, then the data is returned fro this API call, if you do not use the user info endpoint, the user data is fill with the data from the id_token. You can also use the id_token directly if you prefer. 

Greetings Damien

**Comment by damienbod** [comment]
Here is a link to the docs:

 https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api#getuserdataconfigid-string

**Comment by JT2011** [comment]
Thanks @damienbod! Turns out I had a missing setting in the configuration for using the userInfo endpoint. Got that working
