### ISSUE TITLE
"authorizedCallback incorrect state" in browser console

### ISSUE THREAD

**Issue by bastienJS** [damienbod/angular-auth-oidc-client#125]
Hi guys I have a question!

I use angular 5.0.0 and oidc client 3.0.3

**OIDC setup**

```
export class AppModule { 

  constructor(public oidcSecurityService: OidcSecurityService) {
    
            let openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
            openIDImplicitFlowConfiguration.stsServer = 'http://localhost:65535';
            openIDImplicitFlowConfiguration.redirect_url = 'http://localhost:4200';
            openIDImplicitFlowConfiguration.client_id = 'test_client';
            openIDImplicitFlowConfiguration.response_type = 'id_token token';
            openIDImplicitFlowConfiguration.scope = 'openid';
            openIDImplicitFlowConfiguration.post_logout_redirect_uri = 'https://localhost:4200/Unauthorized';
            openIDImplicitFlowConfiguration.start_checksession = false;
            openIDImplicitFlowConfiguration.silent_renew = true;
            openIDImplicitFlowConfiguration.silent_renew_offset_in_seconds = 0;
            openIDImplicitFlowConfiguration.post_login_route = '/home';
           // openIDImplicitFlowConfiguration.forbidden_route = '/#/Forbidden';
            openIDImplicitFlowConfiguration.unauthorized_route = '/unauthorized';
            openIDImplicitFlowConfiguration.auto_userinfo = true;
            openIDImplicitFlowConfiguration.log_console_warning_active = true;
            openIDImplicitFlowConfiguration.log_console_debug_active = false;
            openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 10;
            openIDImplicitFlowConfiguration.override_well_known_configuration = false;
            openIDImplicitFlowConfiguration.storage = localStorage;
            
            this.oidcSecurityService.setupModule(openIDImplicitFlowConfiguration);
     }
}
```

**AppComponent**

```
export class AppComponent implements OnDestroy {


constructor(public oidcSecurityService: OidcSecurityService) {

		if (this.oidcSecurityService.moduleSetup) {
			this.doCallbackLogicIfRequired();
		} else {
			this.oidcSecurityService.onModuleSetup.subscribe(() => {
			this.doCallbackLogicIfRequired();
			});
		}
	}

	ngOnDestroy(): void {
	this.oidcSecurityService.onModuleSetup.unsubscribe();
	}

	login() {
	this.oidcSecurityService.authorize();
	}

	logout() {
	this.oidcSecurityService.logoff();
	}

	private doCallbackLogicIfRequired() {
	if (window.location.hash) {
		this.oidcSecurityService.authorizedCallback();
	}
	}
}
```
During my application start I get this **warning** message:

_authorizedCallback incorrect state_

That warning

```
 if (_this.oidcSecurityValidation.validateStateFromHashCallback(result.state, _this.oidcSecurityCommon.authStateControl)) {
                    // I never get here !!!
				}
				else
				{
                    _this.oidcSecurityCommon.logWarning('authorizedCallback incorrect state');
				}
```

```
   _this.oidcSecurityCommon.authStateControl
```
returns an "empty string"

```
The result.state
```
 returns undefined
				
The root cause seems to be in the
``` window.location.hash 

if (window.location.hash) {
      this.oidcSecurityService.authorizedCallback();
    }
```

hash is  ``` "" ``` in your app: https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow
hash is ``` #/home ``` in my application

I did a redirectTo /home when the path is '', then I removed that redirectTo route configuration
so I have just this:

``` { path: '', component: HomeComponent }, ```

now the window.location.hash

returns ``` #/ ```				

even then the authorizedCallback function is called.

Now I start to understand that the whole sample:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow

is hardcoded to html5 pushstate and not    ``` LocationStrategy.HashLocationStrategy ```

what I use :-)

Can this somewhere-/how be documented ?

**Comment by robisim74** [comment]
@bastienJS Please see here: https://github.com/damienbod/angular-auth-oidc-client/pull/61

@damienbod Hash location strategy needs to be documented

**Comment by bastienJS** [comment]
@robisim74 Thanks for the link which helped to solve the problem I described above. But now I have the problem, that after login successfully I get redirected to:

```
http://localhost:4200/#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkYxMDhCODA2NUNFMTRBOEEwOTZBODUyMkIxQUNBMkFDMTdEQjQwNEEiLCJ0eXAiOiJKV1QiLCJ4NXQiOiI4UWk0Qmx6aFNvb0phb1Vpc2F5aXJCZmJRRW8ifQ.eyJuYmYiOjE1MTAwODYxMTMsImV4cCI6MTUxMDA4NjQxMywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAwMCIsImF1ZCI6InRlYWNoZXJzX3Rlc3RfY2xpZW50Iiwibm9uY2UiOiJOMC42NTE1NDczODU5MzU3MDc1MTUxMDA4NTgxMTE5NSIsImlhdCI6MTUxMDA4NjExMywiYXRfaGFzaCI6ImgyQWRzWlhoZTU4SFdUbDZ6U2dITGciLCJzaWQiOiIwMzVjY2QxZjZkZjVkYjhjNGUzODc0NTBmMWY1MWNiYiIsInN1YiI6IjZlZDI2NjkzLWIwYTEtNDk3ZS1hYTE0LTdiODgwNTM2OTIwZiIsImF1dGhfdGltZSI6MTUxMDA4NjA1OCwiaWRwIjoibG9jYWwiLCJhbXIiOlsiZXh0ZXJuYWwiXX0.G4KLI4ADeHb7NeNZXfOouc087C0G_pPSYTS86OCY-cGGiWUOqkP0FnkIzPZD6F-3m1fkbNod8QQyNyfp5zGzOZOr7ouH3aVWUe2uIAXoRh122CwoXmvExJ0C2N2t8U-tkB7TeekBkxMJxXf3205bZubGpg9oAcyYXjz297YHUoyPhD2IdFGlGtFcTdM_sQYkP0sL7daHuRD6c-YDFcqStu0hoc6D9P2BOAbB7br986VnI3kGV3JrI8ho9LJqA-x1Gl5bNYOmAgmmCNHUm-5t8ivIxab1IqcV9sLS__6Q0gslbVywfj5ZGtPg8wL8qFAtvtp8aiMgu1Po_G7YXpDKXQ&access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkYxMDhCODA2NUNFMTRBOEEwOTZBODUyMkIxQUNBMkFDMTdEQjQwNEEiLCJ0eXAiOiJKV1QiLCJ4NXQiOiI4UWk0Qmx6aFNvb0phb1Vpc2F5aXJCZmJRRW8ifQ.eyJuYmYiOjE1MTAwODYxMTMsImV4cCI6MTUxMDA4OTcxMywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAwMCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjAwMDAvcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoidGVhY2hlcnNfdGVzdF9jbGllbnQiLCJzdWIiOiI2ZWQyNjY5My1iMGExLTQ5N2UtYWExNC03Yjg4MDUzNjkyMGYiLCJhdXRoX3RpbWUiOjE1MTAwODYwNTgsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIl0sImFtciI6WyJleHRlcm5hbCJdfQ.iUqtKWe23mB8b7YhX7AwTIQlW5Vw-Zc35_pMmso6ZehFahdsY-Ak7jTRyzn5aLzSVwYWqjlJNel8E_flnZzsAOMSk1kOq2PkhnxEsxn57Bm0YNHkGnRPRzEGWQRwmFXobI0MqCbv_T3AnJ2NfqX4IPBzIcmlAIpx6UWi5wk0CaOKr1stbzzopU23BiVJiIZ5V0ZuVBZx1FzR0qwZVVybrEumgQavNTnQdKgdd0yhz3hJd8vPV5kKq6tps5otoX53fAIim6LZNR5chc2hWOE7WZN7bHqmUI8r4meWhAbgtVMmeLv5VFoIwnVm0FmQ79yAzisDdid7lu3afOGpUBjOnw&token_type=Bearer&expires_in=3600&scope=openid&state=15099194157410.8984179421687475&
session_state=WpBFlsLazr2tCGxOgPAV-oZ7zsPcI6YKEU53Kw0LpRQ.9605228d328febc7abccc14a3e3e7c28
```

and angular can not handle/find the route thus a noMatchError is thrown:

```
 Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'id_token'
Error: Cannot match any routes. URL Segment: 'id_token'
    at ApplyRedirects.noMatchError (router.js:1698)
    at CatchSubscriber.eval [as selector] (router.js:1663)
    at CatchSubscriber.error (catchError.js:105)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at LastSubscriber.Subscriber._error (Subscriber.js:130)
```

How should I solve this?

**Comment by robisim74** [comment]
@bastienJS you should not use hash location strategy (there is a solution for each web server, Apache, IIS, Node.js).

However, I think the problem could be in your router config. Try to add this line to it:

` { path: '**', redirectTo: 'home' }
`

Example:

```
const routes: Routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'home', component: HomeComponent },
    ...
    { path: '**', redirectTo: 'home' }
];
```

**Comment by bastienJS** [comment]
@robisim74 

1.) Why not se hash location strategy??? the guy who solved the '#' problem which you pointed me to also used hash location... your advise is illogical to me.
2.) your ** hint did not help now I can not load the STS login site anymore, always the 
http://localhost:4200/#/home is loaded :-)

My question to you is, do you guys really support non-pushstate or do you promote pushstate and you do not want to offer both... **-path is actually also reserved for a /404 site.

**Comment by robisim74** [comment]
1) https://angular.io/guide/router#set-the-base-href and https://angular.io/guide/router#browser-url-styles
2) I tried to find a solution to your problem, sorry if it did not work

The push state is supported, as in the link above (#61)

Greetings

**Comment by bastienJS** [comment]
1.) <base href="/"> is in every anglar cli generated app ;-)
2.) no biggy as I think most support from your site will be for pushState as you sample is using it

I guess you you mean 'The hash is supported, as in the link above ...' , right?

I will then start my project with pushState.

**Comment by robisim74** [comment]
I don't know if others are using different solutions, but for example this works (tested):

```
...
import 'rxjs/add/operator/filter';
...
export class AppComponent implements OnInit {

    hash: string;

    constructor(
        private router: Router,
        private oidcSecurityService: OidcSecurityService
    ) {
        if (this.oidcSecurityService.moduleSetup) {
            this.doCallbackLogicIfRequired();
        } else {
            this.oidcSecurityService.onModuleSetup.subscribe(() => {
                this.doCallbackLogicIfRequired();
            });
        }

        this.router.events.filter((event: any) => event instanceof NavigationStart)
            .subscribe((data: NavigationStart) => {
                if (data.url == "/id_token") {
                    this.hash = window.location.hash;
                    this.router.navigate([]);
                }
            });
    }

    ...

    private getTokenHash() {
        if (typeof location !== 'undefined' && this.hash) {
            const indexHash = this.hash.indexOf('id_token');
            return indexHash > -1 && this.hash.substr(indexHash);
        }
    }

    private doCallbackLogicIfRequired(): void {
        const hash = this.getTokenHash();
        if (hash) {
            this.oidcSecurityService.authorizedCallback(hash);
        }
    }

}
```
The point is that you have to remove the hash of _id_token_ for the router, and pass it to the _authorizedCallback_.

**Comment by robisim74** [comment]
Another solution: if your authorization server supports fragments in the redirect uri, you could try to use a redirect uri that contains the initial route:

`openIDImplicitFlowConfiguration.redirect_url = 'http://localhost:4200/#/home';`

In any case, managing the hash location strategy is a problem of the host app.

**Comment by bastienJS** [comment]
Thank you Roberto for all the samples, you should add them to the documentation on the main page ;-)

As I have the free choice concerning location strategy I went with push state redirecting after login works now successfully.

**Comment by premiumwd** [comment]
@damienbod please help for people using hash location strategy. Latest version doesn't have fix for this.

**Comment by damienbod** [comment]
@premiumwd I'll do an example with hash strategy, a lot are using this.

**Comment by jnewman30** [comment]
I was able to fix this by doing the following:

inside the auth.config.ts or code set the following
```
redirectUri: 'http://localhost:4200/#/home?',
postLogoutRedirectUri: 'http://localhost:4200/#/home',
```
**Note: Make sure the client config values in your identity server match for both redirectUri and postLogoutRedirectUri.**

inside your routeing module set the following:
`imports: [RouterModule.forRoot(routes, { useHash: true, initialNavigation: false })],`

inside your app component do the following:
```
    constructor(
        private oauthService: OAuthService,
        private router: Router
    ) {
        this.oauthService.configure(authConfig);
        this.oauthService.loadDiscoveryDocument().then(o => {
            console.log(o);
            this.oauthService.tryLogin().then(_ => {
                this.router.navigate(['/']);
            });
        });
    }
```

**Comment by ahmedsaidzahran** [comment]
> @robisim74 Thanks for the link which helped to solve the problem I described above. But now I have the problem, that after login successfully I get redirected to:
> 
> ```
> http://localhost:4200/#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkYxMDhCODA2NUNFMTRBOEEwOTZBODUyMkIxQUNBMkFDMTdEQjQwNEEiLCJ0eXAiOiJKV1QiLCJ4NXQiOiI4UWk0Qmx6aFNvb0phb1Vpc2F5aXJCZmJRRW8ifQ.eyJuYmYiOjE1MTAwODYxMTMsImV4cCI6MTUxMDA4NjQxMywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAwMCIsImF1ZCI6InRlYWNoZXJzX3Rlc3RfY2xpZW50Iiwibm9uY2UiOiJOMC42NTE1NDczODU5MzU3MDc1MTUxMDA4NTgxMTE5NSIsImlhdCI6MTUxMDA4NjExMywiYXRfaGFzaCI6ImgyQWRzWlhoZTU4SFdUbDZ6U2dITGciLCJzaWQiOiIwMzVjY2QxZjZkZjVkYjhjNGUzODc0NTBmMWY1MWNiYiIsInN1YiI6IjZlZDI2NjkzLWIwYTEtNDk3ZS1hYTE0LTdiODgwNTM2OTIwZiIsImF1dGhfdGltZSI6MTUxMDA4NjA1OCwiaWRwIjoibG9jYWwiLCJhbXIiOlsiZXh0ZXJuYWwiXX0.G4KLI4ADeHb7NeNZXfOouc087C0G_pPSYTS86OCY-cGGiWUOqkP0FnkIzPZD6F-3m1fkbNod8QQyNyfp5zGzOZOr7ouH3aVWUe2uIAXoRh122CwoXmvExJ0C2N2t8U-tkB7TeekBkxMJxXf3205bZubGpg9oAcyYXjz297YHUoyPhD2IdFGlGtFcTdM_sQYkP0sL7daHuRD6c-YDFcqStu0hoc6D9P2BOAbB7br986VnI3kGV3JrI8ho9LJqA-x1Gl5bNYOmAgmmCNHUm-5t8ivIxab1IqcV9sLS__6Q0gslbVywfj5ZGtPg8wL8qFAtvtp8aiMgu1Po_G7YXpDKXQ&access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkYxMDhCODA2NUNFMTRBOEEwOTZBODUyMkIxQUNBMkFDMTdEQjQwNEEiLCJ0eXAiOiJKV1QiLCJ4NXQiOiI4UWk0Qmx6aFNvb0phb1Vpc2F5aXJCZmJRRW8ifQ.eyJuYmYiOjE1MTAwODYxMTMsImV4cCI6MTUxMDA4OTcxMywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAwMCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjAwMDAvcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoidGVhY2hlcnNfdGVzdF9jbGllbnQiLCJzdWIiOiI2ZWQyNjY5My1iMGExLTQ5N2UtYWExNC03Yjg4MDUzNjkyMGYiLCJhdXRoX3RpbWUiOjE1MTAwODYwNTgsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIl0sImFtciI6WyJleHRlcm5hbCJdfQ.iUqtKWe23mB8b7YhX7AwTIQlW5Vw-Zc35_pMmso6ZehFahdsY-Ak7jTRyzn5aLzSVwYWqjlJNel8E_flnZzsAOMSk1kOq2PkhnxEsxn57Bm0YNHkGnRPRzEGWQRwmFXobI0MqCbv_T3AnJ2NfqX4IPBzIcmlAIpx6UWi5wk0CaOKr1stbzzopU23BiVJiIZ5V0ZuVBZx1FzR0qwZVVybrEumgQavNTnQdKgdd0yhz3hJd8vPV5kKq6tps5otoX53fAIim6LZNR5chc2hWOE7WZN7bHqmUI8r4meWhAbgtVMmeLv5VFoIwnVm0FmQ79yAzisDdid7lu3afOGpUBjOnw&token_type=Bearer&expires_in=3600&scope=openid&state=15099194157410.8984179421687475&
> session_state=WpBFlsLazr2tCGxOgPAV-oZ7zsPcI6YKEU53Kw0LpRQ.9605228d328febc7abccc14a3e3e7c28
> ```
> 
> and angular can not handle/find the route 'id_token' thus a noMatchError is thrown and I do not think I should create a route for 'Id_token'...
> 
> ```
>  Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'id_token'
> Error: Cannot match any routes. URL Segment: 'id_token'
>     at ApplyRedirects.noMatchError (router.js:1698)
>     at CatchSubscriber.eval [as selector] (router.js:1663)
>     at CatchSubscriber.error (catchError.js:105)
>     at MapSubscriber.Subscriber._error (Subscriber.js:130)
>     at MapSubscriber.Subscriber.error (Subscriber.js:104)
>     at MapSubscriber.Subscriber._error (Subscriber.js:130)
>     at MapSubscriber.Subscriber.error (Subscriber.js:104)
>     at MapSubscriber.Subscriber._error (Subscriber.js:130)
>     at MapSubscriber.Subscriber.error (Subscriber.js:104)
>     at LastSubscriber.Subscriber._error (Subscriber.js:130)
> ```
> 
> If I replace the '#' with a '?' in the return url
> 
> http://localhost:4200/?id_token=eyJh...
> 
> then I get no errors on the main page and no authorizeCallback() is called again because no hash exists ;-)
> 
> Interesting to see that just one other guy had this problem too on google...
> 
> [jmurphzyo/Angular2OidcClient#16](https://github.com/jmurphzyo/Angular2OidcClient/issues/16)
> 
> but no solution :/
> 
> Any ideas how I can solve that? Should the id_token query parameter no start with a '?' where after all key/values are appended? :->
> 
> But even that is not all the truth. After the successfull login when the id_token/token is returned the authorizedCallback should be executed to store both token prolly in the user defined storage. Prolly that would happen if there were not the id_token assumption to be a route.

Please I faced the same problem, I don't know exactly what is wrong.
If you fix it (as mentioned with pushState), can provide solution.
