### ISSUE TITLE
Session token in URL vulnerability

### ISSUE THREAD

**Issue by vamshi86** [damienbod/angular-auth-oidc-client#1250]
Hi, our security team ran some scans on our app and came up with couple of issues related to the package.

https://xxx.com:443/silent-renew.html?code=bEptmLlH7R3xiXL5ptW2vfWDczyksbLy1HyvQKNYn8I&scope=openid&state=4f2e11d0aee8c325e90f363cbe050b2743lhhR5il&session_state=iryKopbKKB2zIsSuZeycBOAWOZKIh-w1ANz4XU7y-1U.Xim3Ya_z7MZbFzPfKEKdng

For the above URL, **Session token in URL** vulnerability is reported. I know that this is the internal call done within the package and the URL doesn't contain the token but I just want to understand what are these code, state and session_state parameters and what is the purpose of those. I tried going through the documentation and didn't find any topic regarding this. Is it secure to send those parameters in the URL? Please help me understand this.

Similar issue reported for authorize call as well.

**Comment by damienbod** [comment]
Hi @vamshi86 This is the OIDC code flow parameters definitions as per spec. Your security team is returning incorrect results. Please ask them to read up on the OIDC Code specifications. You can read up on each of the parameters here and it explains why it's required and what it protects against. None of these are session tokens.

Greetings Damien

**Comment by vamshi86** [comment]
Thanks for your response. Can you please share the link where we can read regarding above parameters.

**Comment by damienbod** [comment]
https://openid.net/specs/openid-connect-core-1_0.html

Greetings Damien

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
