### ISSUE TITLE
Getting potential Interceptor issue when trying to tie in a custom interceptor using the OidcSecurityService

### ISSUE THREAD

**Issue by JT2011** [damienbod/angular-auth-oidc-client#1251]
I was able to setup and login using the OidcSecurityService, and have requests go through using my custom interceptor, in a testing app I have tied to a private published library utilizing it. However, when I tried to utilize that same library, with the same registration/imported module, etc, in another app, I am now getting this error:

**[ERROR] 0-dev-local_uplink_exp_pkce - Getting auth well known endpoints failed on start Error: NG0200: Circular dependency in DI detected for InjectionToken HTTP_INTERCEPTORS.**

I saw this previously and was able to at least temporarily resolve it using this to skip certain requests in my interceptor:

```
intercept(request: HttpRequest<any>, next: HttpHandler): Observable<
    HttpSentEvent
    | HttpHeaderResponse
    | HttpProgressEvent
    | HttpResponse<any>
    | HttpUserEvent<any>
| any> {

if (this.skipUrl(request.url)) {
      console.log('request skipped - JwtInterceptor', request.url);
      return next.handle(request);
    }
    console.log('request captured - JwtInterceptor');
    return this.refreshRequestHandled(next, request);
  }

private skipUrl(url: string): boolean {
    if (url.toLowerCase().endsWith('config.json')) {
      return true;
    }
    if (url.toLowerCase().endsWith('.well-known/openid-configuration')) {
      return true;
    }
    if (url.toLowerCase().includes('identity-service.io')) {
      return true;
    }
    return false;
}
```

However, this no longer effects this error, so I'm not sure what I am missing here.

**Comment by JT2011** [comment]
Other difference is that the original testing app is running IISExpress, and the other app is running in Local IIS

**Comment by FabianGosebrink** [comment]
AFAICS the issue is the registration of the `HTTP_INTERCEPTORS` as there is a circular dependency. Did you check that?

**Comment by JT2011** [comment]
Turns out this was related to the way some of the services in my apps were being registered as well as how the interceptors were setup. It was resolved
