### ISSUE TITLE
Custom Storage Errors get swallowed

### ISSUE THREAD

**Issue by jigfox** [damienbod/angular-auth-oidc-client#1252]
**Describe the bug**
Errors in Storage don't bubble up. We try to create a cookie storage because we use angular universal and cookies are the only way for shared storage in universal and browser, but cookies are limited in size so the cookie service throws errors if size is exceeded, but we never saw this error, we just were unauthorised.

**To Reproduce**
use custom storage:

```ts
import { AbstractSecurityStorage } from 'angular-auth-oidc-client';

@Injectable()
export class CustomStorage implements AbstractSecurityStorage {
  read(key: string) {
    return localStorage.getItem(key);
  }

  write(key: string, value: any): void {
    throw new Error("value too long");
    localStorage.setItem(key, value);
  }

  remove(key: string): void {
    localStorage.removeItem(key);
  }

  clear(): void {
    localStorage.clear();
  }
}
```

**Expected behavior**

That the error won't be swallowed and we can see what wen't wrong

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by FabianGosebrink** [comment]
With this PR https://github.com/damienbod/angular-auth-oidc-client/pull/1422 we added abstract logging functionality. 

Is the bug still valid?
