### ISSUE TITLE
Silent renew does not add custom params from the initial authorize() call after upgrade (11 -> 12).

### ISSUE THREAD

**Issue by EdgarsJoja** [damienbod/angular-auth-oidc-client#1256]
**Describe the bug**
Automatic silent renew request does not include custom parameters after upgrade (11 -> 12), that were added initially as part of authorize() call.

**To Reproduce**
1. Call authorize() method and pass custom params. Example: 
```
// Btw, as opposed to docs samples, clientId cannot actually be null, nor does empty string seem to work as well.
this.oidcSecurityService.authorize(undefined, {
  customParams: {
    dealer: '1',
    lang: this.i18nService.language.toLowerCase(),
  },
});
```
2. Observe refresh token request params (dealer, lang params are missing).
```
grant_type=refresh_token&client_id=sample-id&refresh_token=64db69051335d060ee75c686bb2b293d5d1f073b
```

**Expected behavior**
Refresh token requests to include the same custom params, that were used initially for authorization. Example request params:
```
grant_type=refresh_token&client_id=sample-id&refresh_token=64db69051335d060ee75c686bb2b293d5d1f073b&dealer=1&lang=en
```
Reason I'm assuming such expected behavior is because it was working in v11.6.8 and such functionality changes were not mentioned in the migration guide (https://nice-hill-002425310.azurestaticapps.net/docs/migrations/v11-to-v12)

**Desktop:**
 - OS: Pop!_OS 21.04
 - Browser: firefox
 - Version: 92.0

**Additional context**

Related issues:
https://github.com/damienbod/angular-auth-oidc-client/issues/912
https://github.com/damienbod/angular-auth-oidc-client/issues/911
https://github.com/damienbod/angular-auth-oidc-client/issues/795

I'm also trying to workaround this issue by utilizing new multiple configs support, to basically create separate "dealer" config, which so far doesn't seem to work right for me, After authorizing, I'm getting redirected back to authorization again, however, I'm not yet sure if it's an issue with the library, authorization server, or something else. But even, so, such workaround wouldn't be full replacement for previous customParams functionality, as this config is static, as opposed to dynamic values that we can pass to customParams (see "lang" param in the example).

Thanks in advance and let me know if I can help with any additional info :)

**Comment by FabianGosebrink** [comment]
Hey, if you want the params to be on every (refresh) request, set them in the main config with the new properties like https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#customparamsrefreshtokenrequest . Would you like to give that a try?

**Comment by EdgarsJoja** [comment]
Yes, that's what I'm currently trying as a workaround, managed to do it, but I have some related issues with the other code, so still in progress overall.
However, as mentioned, it is not a full replacement of the previous functionality, in my opinion, which had the ability to pass some parameters dynamically that would be re-used in subsequent refresh requests. Those main config parameters are static, it seems. 

I think it would also be good to understand understand if this considered as a legitimate bug (due to how it worked previously) and there is a possibility for a fix or such functionality is cut from the library and we have to find some other ways to emulate that functionality.

**Comment by FabianGosebrink** [comment]
Is this issue still relevant?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
