### ISSUE TITLE
Attempting to create an AuthGuard that doesn't require authenticated status but can check it if already logged in

### ISSUE THREAD

**Issue by JT2011** [damienbod/angular-auth-oidc-client#1259]

**Comment by JT2011** [comment]
So I am working with an app where I need the Home page to be able to provide different content based on authenticated status, but still be accessible without forcing a login so it can also serve as a landing page for the base url of the app.

```
@Injectable({ providedIn: 'root' })
export class NoAuthPermissionGuard implements CanActivate {

  constructor(
    private oidcSecurityService: OidcSecurityService,
    private permissionStorageService: PermissionStorageService,
    private userStorageService: UserStorageService,
    private roleStorageService: RoleStorageService) { }

  async canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    const routeState = route.url.toString() + '-' + state.toString();
    sessionStorage.setItem('routeState', routeState);
    let isAuthenticated = this.oidcSecurityService.isAuthenticated();

    console.log('NoAuthPermissionGuard => isAuthenticated', isAuthenticated);
    if (isAuthenticated) {
      console.log('isAuthenticated = true?', isAuthenticated);
      this.oidcSecurityService.checkAuth().subscribe(async ({ userData }) => {
        const userDataJson = JSON.stringify(userData);

        console.log('Storing UserData in session');
        const userDataStore = JSON.parse(userDataJson) as UserData;
        this.userStorageService.setUserData(userDataStore);

        console.log('Storing User Auth Status in session');
        this.userStorageService.setUserAuthStatus(true);

        console.log('NoAuthPermissionGuard => authenticated')
        await this.permissionStorageService.storePermissions();
        await this.roleStorageService.storeRoles();
      });
    }

    return true;
  }
}
```

I can see the message after logging in that the isAuthenticated variable returns true, however, it errors when trying to return from my auth-callback page to the home page route: '/', with an error message saying there is no unauthorized route configured, which there isn't, because all routes should be allowed in some capacity or another. The purpose of this auth guard for the home page was to update certain services to track roles and permissions if they were logged in, to change the navbar menu and home page content, but always return true.

I am assuming that the error is being cause by this, because I can remove the auth-guard and get into the home page no issues, whether I am logged in or not.

Not sure what I can try to make it pass this route guard.

**Comment by FabianGosebrink** [comment]
Can you provide us a sample repo with that guard please?

**Comment by mac-bhaird** [comment]
For this one, the intent is to log someone in automatically, if they are logged in on the server and not logged in locally, in the case that the particular page they are accessing does not require authentication.

In the previous library, we would run a check against the server to see if they were authenticated there, and then run the authentication flow. This needed to be done in a guard, as for timing issues, we need to retrieve roles and permissions before continuing to app.component as the roles and permissions would control what was visible.

Is there a way to verify if they are logged in on the server without triggering the authentication flow?

**Comment by JT2011** [comment]
Created a separated project in this github repo: https://github.com/JT2011/oidc-angular-client-test

You can use the Logout Locally button to retain login status and then reload the page where I would expect the TestGuard to check the login status against the server and bring it back.

**Comment by mac-bhaird** [comment]
The concept we're looking to duplicate (we had this with a previous library) should be captured with the following two scenarios:

### Scenario: User is authenticated on server, and not authenticated in application

Given

- user is logged into identity provider (for example identity server)
- user is not logged into the current application

When 

- user accesses an 'unprotected' route

Then

- user is authenticated (automatically logged in SSO style) 
- roles and permissions (that are dependent on identity) are loaded before the ui loads
- user is allowed to continue to the 'unprotected' route

### Scenario: User is not authenticated on server, and not authenticated in application

Given

- user is NOT logged into identity provider (for example identity server)
- user is not logged into the current application

When 
- user accesses an 'unprotected' route

Then
- user is allowed to continue to the 'unprotected' route

hope this helps!

**Comment by mac-bhaird** [comment]
FYI, the only thing we need to make this work, is the ability to check with the identity server if the user is logged in.

**Comment by FabianGosebrink** [comment]
Yes, I will clarify if this is a method we will expose as soon as @damienbod is back from holiday.

**Comment by damienbod** [comment]
You should be able to implement this using the **checkAuthIncludingServer** method.  The rest is specific for you application and I believe this logic does not belong in the lib.

Greetings Damien
