### ISSUE TITLE
isAuthorized does not working on refresh in latest release

### ISSUE THREAD

**Issue by robisim74** [damienbod/angular-auth-oidc-client#126]
In version 3.0.3, isAuthorized does not working on refresh. The reason seems to be this commit: https://github.com/damienbod/angular-auth-oidc-client/commit/75b23501c625348138213ecdad07271da15709af and the getter of `isAuthorized` that always returns undefined: https://github.com/damienbod/angular-auth-oidc-client/commit/75b23501c625348138213ecdad07271da15709af#diff-c743ac95d26029d6df975174c80f75d9R42

It should be simply:
```
    public get isAuthorized(): boolean | undefined {
        return this.retrieve(this.storage_is_authorized);
    }
```

**Comment by damienbod** [comment]
thanks for looking into this, will fix it tonight after work
