### ISSUE TITLE
Multiple silent refresh with the same iFrame fire at the same time, only last configuration token gets refreshed

### ISSUE THREAD

**Issue by mihaioprescu** [damienbod/angular-auth-oidc-client#1261]
Hi,

I am working on an app that uses this library, with a config based on the  'Multiple configurations code flow with PKCE basic with iframe renew' sample in the documentation.

My app uses 15+ configurations, and they all have the same silent renew params - renewTimeBeforeTokenExpiresInSeconds and tokenRefreshInSeconds are identical for all configurations.

This means that often I have situations when multiple silent renew processes start at the exact same time and all the responses get back to the silent renew iframe at the same time. As a consequence, only the last event from all those requests gets dispatched to the parent window and a single renew process is completed successfully.

I am talking about this code from the sample in the silent-renew.html:

    /* The parent window hosts the Angular application */

    var parent = window.parent;

    /* Send the id_token information to the oidc message handler */

    var event = new CustomEvent('oidc-silent-renew-message', {detail: window.location});

    console.log(event);

    parent.dispatchEvent(event);

Also a single event is logged in the console, and in the network tab I see all silent renew requests canceled , except the last one.

![damien3](https://user-images.githubusercontent.com/23552672/134212903-dd7a5d62-f11a-4d95-83a2-c410a8e06ab3.jpg)

As you can see the screenshot, I have multiple configurations that fire the silent renew process almost at the same time ( main, home, apps , clusters ), and only the 'clusters' configuration token in this case is being refreshed. 
This happens every X seconds when they all fire together, end eventually the tokens for the other configurations expire.

I am using the latest version of the library 12.0.3, with Angular 12.2.1

Browser : Chrome Version 93.0.4577.82 (Official Build) (64-bit)

I read the documentation and samples, but i fail to understand how the situation above can be avoided when using the same iFrame for the renew of multiple tokens .

Can i get an official opinion on this?

Thank you!

**Comment by WolfspiritM** [comment]
We're having a similar issue with code flow and refresh token rotation. Not sure however if this is related. In some cases it happens that a call to the token endpoint is triggered at the same time with the same old refresh token (even with silentRenewTimeoutInSeconds set to 30 seconds).

This results in the identity server invalidating all refresh tokens so the users ends up being logged out and needs to log in again. Can this be related?

This is a big issue for us right now and very hard to reproduce.

**Comment by damienbod** [comment]
@mihaioprescu You can use different iframe per configuration

**Comment by damienbod** [comment]
@WolfspiritM Yours is a different issue, we would need to investigate this. Could you create a new issue for this?
