### ISSUE TITLE
State doesn't get cleaned from history successfully and causes hard error

### ISSUE THREAD

**Issue by WolfspiritM** [damienbod/angular-auth-oidc-client#1262]
**Describe the bug**
We have an auth guard checking for checkAuth nearly identitcal to the all routes auth guard.
Currently we're facing a problem if the user doesn't yet have a redirect url set from a previous call.
In this case checkAuth is successful but the user doesn't get redirected in the auth guard and in the end the code and state remains in the URL. If the user then navigates to somewhere else checkAuth gets triggered again causing it to not find the state and resulting in an exception: ```could not find matching config for state ...``` that prevents the page to load

I checked and "resetBrowserHistory" gets called. "location.href" after that call is actually set correctly without any query params, however it seems that the angular router then redirects from /home to / in our case and for that it uses the "old" URL including the query params again. I'm not sure if that is caused by a change with Angular 12.

A similar issue happens when trying to log in in two different tabs at the same time.

**To Reproduce**
1. Have a router redirect from /home to / (Not sure if that is required)
2. Call checkAuth without redirect url set from redirect to id provider in auth guard
3. Check URL. It should contain /?code=...
4. Try navigating somewhere else
5. Error appears: ```could not find matching config for state ...```
6. Press F5: Error appears ```could not find matching config for state ...``` and code gets removed from query params
7. Press F5: Works

**Expected behavior**
code and state gets removed from URL correctly and if state is not found no hard error is thrown but instead the query params should just be ignored.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Edge Chromium
 - Version [e.g. 22] latest

**Comment by wcypierre** [comment]
I faced this issue too using AutoLoginAllRoutesGuard in Angular 12.2.6, I cleared the cookies and cache and it is working now but I can't reproduce it anymore
