### ISSUE TITLE
UserData wont update on refresh

### ISSUE THREAD

**Issue by exitxhu** [damienbod/angular-auth-oidc-client#1263]
**Describe the bug**
Hi
I am trying to implement this scenario:
I have an app with its DB and personnel, and an oath server which is separated
1- a user logs in with an OAuth server 
2-in redirect page, user data will be checked for a certain claim (such as personnelId), which will be used in the actual app
3- if that does not exist, an API will be called to append that claim to the user(to map identity user and app user)
4- I can see that new claims are indeed added to the oath server

now when I force refresh the session, I can see claims in the token, but oidc.userData$ and oidc.GetUserData() are not aware of it!

I need to log out and log in again to get the data.

Is there any way to update userdata or add the keys manually to it? like this => userData['prsid'] = response.value?

**Comment by exitxhu** [comment]
Another thing is i changed oidc.security.service.d.ts like this

export declare class OidcSecurityService {
....
    public userService : UserService;
....
}
and used "userService.setUserDataToStore()" directly this helped me to achieve my goal, but it's some what of a deep magic and I really think that it should be done this way

**Comment by WolfspiritM** [comment]
Have you tried:
https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#renewuserinfoaftertokenrenew

**Comment by exitxhu** [comment]
> Have you tried:
> https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#renewuserinfoaftertokenrenew

i literally read docs twice and that wasn't caught my eyes!
 i tested and that is the solution to my dilemma

tnx very much
