### ISSUE TITLE
token userData is not set after idp login redirect back to application

### ISSUE THREAD

**Issue by seabass223** [damienbod/angular-auth-oidc-client#1265]
**Describe the bug**
userData is not set after idp login redirect back to the application. This causes silent renew checks to not run.

**To Reproduce**
1. Login to IDP
2. IDP redirects to angular app
3.  (looking at compiled output)angular-auth-oidc-client.js setUserDataToStore is never called.
4. manually verify the idp sent back a valid id_token and access_token
4. F5, now setUserDataToStore is called and userData is set correctly and silent renew checks begins running successfully.

**Expected behavior**
userData after idp login redirect.

**Desktop (please complete the following information):**
OS: Windows 10 Enterprise build 19043.1237
Browser: Chrome
Version 94.0.4606.61 (64-bit)

**Additional context**
while my configuration is using my own custom localStorage, I was able to verify this issue using the default sessionStorage.

This works as a temporary solution inside of app.component ctor
```    
const idToken =  localStorage.getItem('my-token-name')?.authnResult?.id_token
    if (!!idToken) {
      const userData = JSON.parse(atob(idToken.split('.')[1]));
      const wholeToken = JSON.parse(localStorage.getItem('my-token-name'));
      if (!wholeToken.userData) {
        wholeToken.userData = userData;
        tokenStorageService.write('my-token-name', JSON.stringify(wholeToken));
      }
   }

**Comment by FabianGosebrink** [comment]
Can you reproduce this with using the public API the lib exposes? You can pass the custom storage if you want and use the public API.

[Public API](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api)
[Custom Storage](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/custom-storage)

**Comment by seabass223** [comment]
no, I can't reproduce the issue with a new project and basic setup. investigating target project to find what is misconfigured.

**Comment by seabass223** [comment]
In oidcSecurityService.isAuthenticated$.subscribe() is fired with isAuthenticated = true, before getUserDataOidcFlowAndSave is fired. I was doing a redirect in subscribe if isAuithenticated = true, so getUserDataOidcFlowAndSave never had a chance to be called.
