### ISSUE TITLE
OIDC well known config cannot be loaded from the app, but can be viewed in the browser. 

### ISSUE THREAD

**Issue by StephanBis** [damienbod/angular-auth-oidc-client#1267]
**Describe the bug**
We have the following code in our Ionic Angular app. We're using a OpenIddict .NET backend as identity server.

`AuthModule.forRoot({
      config: {
        authority: 'https://localhost:7296',
        redirectUrl: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        clientId: 'api.mobile',
        scope: 'openid profile email offline_access api',
        responseType: 'id_token token',
        silentRenew: true,
        useRefreshToken: true,
        logLevel: LogLevel.Debug
      }
    }),`

As expected this will try to load the OIDC well known config on app startup. But as soon as it does the following errors are thrown.

![image](https://user-images.githubusercontent.com/10954823/135852790-b2be885f-72cd-48d0-a26c-b169f7cf9997.png)

What we checked:
- CORS has been configured correctly, we even tried AllowAllOrigins. 
- OIDC well known config can be viewed by surfing to 'https://localhost:7296/.well-known/openid-configuration', which the app is trying to GET aswell.
- OpenIddict config is working, we are getting access, ID and refresh tokens from the backend when debugging with Postman

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 94.0.4606.71

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - OS: Android 11
 - Browser: Chrome
 - Version 94.0.4606.71

**Comment by rbalet** [comment]
@StephanBis Old topic, but did you find any solution on your problem ?

**Comment by StephanBis** [comment]
> @StephanBis Old topic, but did you find any solution on your problem ?

Sorry, I can't remember what the exact fix was. I think it had something to do with an incorrect CORS and web.config  configuration.

**Comment by origooo** [comment]
I also ran into this problem this week and I have no control over the server. I talked to the guy who has, and he simply told me I had an error somewhere.

I ended up intercepting the request to redirect it to my node server by setting `authWellknownEndpointUrl: "/fetch-openid-config/.well-known/openid-configuration"`. From that server it works perfectly fine to fetch the configuration from the provider.

[This thread](https://stackoverflow.com/a/55464569/2136957) mentions something about the server not being configured for Javascript web app. I don't know what the difference is on the server, but when e.g. configuring Azure, you have to specify that your application is an SPA. Maybe that is the misconfiguration the thread mentions.

**Comment by damienbod** [comment]
A CORS error is a misconfiguration on the server. This needs to be allowed for your Javascript domain if this is to work.
