### ISSUE TITLE
connect/endsession called twice after logoffAndRevokeTokens

### ISSUE THREAD

**Issue by CsillaPapp** [damienbod/angular-auth-oidc-client#1269]
After calling `this.oidcSecurityService.logoffAndRevokeTokens().subscribe()` on a user click event, we noticed that the `connect/endsession` endpoint of our Identity Server is called twice (however not in 100% of the cases), the first one resulting in cancellation. The first call gets its id_token_hint parameter correctly, but the second one has id_token_hint set as undefined, resulting in an incorrect behavior (which is also logged by Identity Server).

![image](https://user-images.githubusercontent.com/9323260/136237231-53266c7a-48b8-477f-af1c-8b5b7aa0e789.png)

![image](https://user-images.githubusercontent.com/9323260/136237418-bbfb0750-f52e-4f73-956c-e3fbc7ab4fcc.png)

The behavior was reproduced in majority of the cases, however, there were very few cases when the issue did not reproduce (around 2 out of 30 tests, with the same configuration and executed steps).

The issue did not reproduce on a separate test project that does not have a database connection configured for Identity Server (it works with plain in-memory data). I am assuming that the communication speed between Identity Server and the database which affects the amount of time Identity Server responds to the endsession request, might have an impact.

**Desktop:**

OS: Windows 10
Browser: Chrome
Version 94.0.4606.71 (64-bit)

OS: Windows 10
Browser: Firefox
Version 92.0.1 (64-bit)

Tested with 11.6.6 and 11.6.11 versions of angular-auth-oidc-client

**Comment by FabianGosebrink** [comment]
Fixed this bug with https://github.com/damienbod/angular-auth-oidc-client/pull/1307. Saw it in the tests and fixed it with them. Thanks!
