### ISSUE TITLE
How to add ForwardedHeaders options ?

### ISSUE THREAD

**Issue by noumanbhatti** [damienbod/angular-auth-oidc-client#127]
My IdP is running in load balancer  environment and I need to add ForwardedHeaders to my settings. How I'll achieve this using angular-auth-oidc-client ? 

in .net core 2.0 I did it as follow

```
 var forwardedOptions = new ForwardedHeadersOptions {
                ForwardedHeaders = (
                  ForwardedHeaders.XForwardedFor
                | ForwardedHeaders.XForwardedHost
                | ForwardedHeaders.XForwardedProto),

                RequireHeaderSymmetry = false,
                ForwardLimit = null,
            };
            forwardedOptions.KnownProxies.Clear();
            forwardedOptions.KnownNetworks.Clear();
            app.UseForwardedHeaders(forwardedOptions);
```

**Comment by damienbod** [comment]
@noumanbhatti When do you need to add them? Optional for all requests?

**Comment by noumanbhatti** [comment]
In my .net core app I set it only once during configuration.
it works fine after that.

I'm using url localhost:5000 for one app built using .net core and it works
fine with the authentication api

but the same api url when used in angular gives me the following error . I
read it somewhere it may happen when authentication api is behind the load
balancer (which is the case in this scenraio)

Failed to load https://my.xyz.com.au/.well-known/openid-configuration: No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:5000' is therefore not allowed access.



*Regards,*

*Nouman Bhatti*
 Save a tree. Don't print this e-mail unless it's really necessary

**Comment by damienbod** [comment]
@noumanbhatti 

Failed to load https://my.xyz.com.au/.well-known/openid-configuration: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. 

This is a CORS problem which you need to configure on the server. CORS is blocked. Allow CORS for you client IP

**Comment by profet23** [comment]
Can we close this?
