### ISSUE TITLE
Silent redirect url

### ISSUE THREAD

**Issue by timaxapa** [damienbod/angular-auth-oidc-client#128]
Is it possible to set redirect_url for silent renew operation?
For example - On site load, I show SSO form, after login, I redirect to <domain>/auth/success
On this page, I make another request using token and email, for example, and redirect user to page according to his role. But I don't need these operations (get user role by token and email) on silent renew, I need just a new token and I want to have separate redirect_url for silent token renew.

**Comment by damienbod** [comment]
@timaxapa Not yet, but this would be a good improvement.

**Comment by damienbod** [comment]
yes, added in version 4.1.0

https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#silent_renew_url
