### ISSUE TITLE
Add A Sample To Documentation for Refresh Tokens in Mobile Angular and/or Cordova

### ISSUE THREAD

**Issue by wolfpackt99** [damienbod/angular-auth-oidc-client#1280]
**Is your feature request related to a problem? Please describe.**
I am following this article [Securing a Cordova App](https://offering.solutions/blog/articles/2020/09/17/securing-a-cordova-app-implemented-with-angular-using-oidc-and-oauth2/)

**Describe the solution you'd like**
The library has changed and would like to see a best-practice or how-to documentation for mobile. seems the checkAuth needs to behave differently and am not entirely sure how to update/change a guard to behave if we have a custom checkAuth.

**Describe alternatives you've considered**
No other libraries. Custom guards but need access to methods that were previously exposed in v11 (via AuthStateService)

**Comment by wolfpackt99** [comment]
I have everything working now, just unsure if i should be using a custom guard or still use the default provided guards.

**Comment by FabianGosebrink** [comment]
I have added a working example here https://github.com/FabianGosebrink/cordova-angular-oauth2-oidc
