### ISSUE TITLE
Lazy load config via http

### ISSUE THREAD

**Issue by deceptiveSimplicity** [damienbod/angular-auth-oidc-client#1284]
Hello,
is there a way to load a config from an http source like in the [sample-code-flow-http-config](https://github.com/damienbod/angular-auth-oidc-client/tree/f3ff0fb8e99e3db329c8c907249dfbab99384d5a/projects/sample-code-flow-http-config) but doing this in a lazy manner?
The context of my problem is, I want to use some pre-rendering, but can't get it to work when the http call to my auth-config file fails in pre-rendering.

**Comment by FabianGosebrink** [comment]
Is the [eagerLoadAuthWellKnownEndpoints](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#eagerloadauthwellknownendpoints) a config you are searching for?

**Comment by deceptiveSimplicity** [comment]
Unfortunately this option controls loading the oidc-config (in the sample: https://offeringsolutions-sts.azurewebsites.net/.well-known/openid-configuration )
But I mean the other config (in the sample https://offeringsolutions-sts.azurewebsites.net/api/ClientAppSettings)
https://github.com/damienbod/angular-auth-oidc-client/blob/f3ff0fb8e99e3db329c8c907249dfbab99384d5a/projects/sample-code-flow-http-config/src/app/auth-config.module.ts#L8-L32

**Comment by FabianGosebrink** [comment]
You can include the auth module in a module which is loaded when the user clicks and lazy loads it. Does that solve your problem?

**Comment by wolfpackt99** [comment]
This is something i am after as well. I only want the package auth package to load and resolve well-known endpoints after i've told it too. by pre-seeding some url information in storage. Would this 'auth module in a module' solve this use-case?

**Comment by FabianGosebrink** [comment]
I have not tested this, but theoretically it should work.

**Comment by FabianGosebrink** [comment]
Isn't the `eagerLoadAuthWellKnownEndpoints` helping you in this case? Currently thinking about a solution for this issue.

**Comment by wolfpackt99** [comment]
yes. I want to obtain something from the user first. afterwards at any point something 'auth' is attempted, it would first download well-known and begin flow.

**Comment by FabianGosebrink** [comment]
Okay, but why does the `eagerLoadAuthWellKnownEndpoints` does not help you in this case?

**Comment by wolfpackt99** [comment]
I recently upgraded the the latest but was prior using app initializer, and couldn't figure out how to stop it from trying to load endpoints. then its seems, once it was set, I couldn't change or make it reload the endpoints. I could be mistaken.

Here is the general idea.
Have some unauthenticated landing page.
Ask for an identifier which helps form the well-known URL.  http://<identifier>.someurl.com/auth
Save identifier to storage
Tell Auth library to "use this AuthConfig" (with corrected urls) http://mysite.someurl.com/auth
Then:
a. begin auth flow
b. or wait for auth flow until user tries to navigate to a guarded route.

On subsequent app-start, set well-known url if identifier is saved in storage
Ability to 'change' identifiers and notify the library that the well-known endpoints have changed.
1. if logged in, logout, reset urls. follow steps above to begin flow.
2. if not logged in, follow above steps to begin flow

**Comment by FabianGosebrink** [comment]
It is not possible to switch the configs on runtime. Is it that what you are trying?

**Comment by FabianGosebrink** [comment]
Or are you trying to identify the configs with the auth well known endpoint? Or with the auth well known endpoint url?

**Comment by wolfpackt99** [comment]
I don't know the auth url until a user types in some identifying sub-domain piece (identifier).  so was initially hitting a snag where the library was trying to load at app-launch (its a mobile app, btw). So the needs are to not do anything with auth unless we know the identifier that completes the url from storage, or have a customer type it in. At which point the auth flow, discovery documents can load.

Addtionally, someone could change identifiers to re-auth against a different auth url.

**Comment by FabianGosebrink** [comment]
Ahh, I think now we are getting closer. So you want to load an authwellknownendpoint dynamically at runtime, passing in the url, is that correct?

So you have the config in the beginning to start the app (and lib), only the authwellknownurl is not known?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
