### ISSUE TITLE
Running ng add, specifying remote configuration, and AuthHttpConfigModule.

### ISSUE THREAD

**Issue by GrahamDumpleton** [damienbod/angular-auth-oidc-client#1286]
**Describe the bug**

When using `ng add` and specifying that remote HTTP configuration should be used, the `app.module.ts` which is generated uses `AuthHttpConfigModule`.

This is presumably generated from:

* https://github.com/damienbod/angular-auth-oidc-client/blob/bf2dfd5f7253b8fc7ef29060de043fcb9b46b995/projects/schematics/src/ng-add/actions/schema-parser.ts#L7

In `app-http-config.module.ts` however, it uses `AuthConfigModule`.

This is generated from:

* https://github.com/damienbod/angular-auth-oidc-client/blob/9cf4ce4e97b574a1c6a78a51cde7232015ea0f7f/projects/schematics/src/ng-add/files/auth-http-config/auth-http-config.module.__ts__#L48

Thus out of the box they don't match and need to change one or the other.

**To Reproduce**

Use `ng add` to add package to a project. Check the two different files.

**Expected behavior**

Names should match.

Note, entering this from memory so hope got file reference around the right way. :-)

**Comment by damienbod** [comment]
fixed
