### ISSUE TITLE
Angular v13 types errors

### ISSUE THREAD

**Issue by tiberiuzuld** [damienbod/angular-auth-oidc-client#1287]
**Describe the bug**
Library not compatible with the Angular v13 types

```ts 
Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:14:5 - error TS2416: Property 'canLoad' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanLoad'.

Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:15:5 - error TS2416: Property 'canActivate' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanActivate'.

Error: node_modules/angular-auth-oidc-client/lib/auto-login/auto-login-all-routes.guard.d.ts:16:5 - error TS2416: Property 'canActivateChild' in type 'AutoLoginAllRoutesGuard' is not assignable to the same property in base type 'CanActivateChild'.

Error: node_modules/angular-auth-oidc-client/lib/interceptor/auth.interceptor.d.ts:14:5 - error TS2416: Property 'intercept' in type 'AuthInterceptor' is not assignable to the same property in base type 'HttpInterceptor'.

```

**To Reproduce**
1. Update to angular 13
2. Use latest library version
3. See errors

**Expected behavior**
To be compatible with angular 13

**Comment by damienbod** [comment]
@tiberiuzuld Thanks for reporting, looking into this. I was not able to reproduce this, updated some repos to V13-

@FabianGosebrink Do you have an opinion here, should we update this repo to V13?

Greetings Damien

**Comment by FabianGosebrink** [comment]
Yes, we can update to A13, but we have to check the library config first and this would be a new Major version. V13 of the lib as well because of ivy.

**Comment by tbertran** [comment]
I came here to report the same problem on my end.

> Thanks for reporting, looking into this. I was not able to reproduce this, updated some repos to V13-

@damienbod It didn't start happening for me until I blew up my repo's  `node_modules/`, `dist/` and ran `npm cache clean -f` so you might be seeing that same behavior.

FYI I wanted to explore putting in a PR so I cloned the repo and got it building and running locally with a handful of rxjs/Angular fixes but running `ng update @angular/cli @angular/core` to get it to 13 caused some side effects that I wasn't sure how you guys wanted to handle. 
Let me know if I can help in any way.

**Comment by michaelmarcuccio** [comment]
After downgrading Angular from v13 back to v12, I realized that it was actually RXJS v7 that causes this issue as the issue continued to occur. I reverted to RXJS v6 and the issue was resolved.

**Comment by tbertran** [comment]
@FabianGosebrink Did you mean to close this issue? @michaelmarcuccio's comment offers a work-around for the lack of rxjs 7 compatibility. Should I open a new, more rxjs-specific, issue for it?

**Comment by FabianGosebrink** [comment]
The lib is not at A13 at the moment and not at rxjs 7. We will update it to A13 and rxjs 7 when Angular officially supports it imho.

**Comment by michaelmarcuccio** [comment]
It looks like Angular 13 has officially released and uses RxJS 7 as the default version.

**Comment by FabianGosebrink** [comment]
Yes, we are on it and will update to Angular 13 as well as RxJs 7.4 in one go.
