### ISSUE TITLE
Add support for Angular 13

### ISSUE THREAD

**Issue by johnfabian** [damienbod/angular-auth-oidc-client#1295]
I'm unable to update my project to Angular 13, I get the following errors:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-oidc-oauth2@0.0.0
npm ERR! Found: @angular/common@13.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from angular-auth-oidc-client@12.0.3
npm ERR! node_modules/angular-auth-oidc-client
npm ERR!   angular-auth-oidc-client@"12.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by damienbod** [comment]
Yes the lib has not been updated to Angular 13 yet. You could update using the npm install --force, but I am not sure about possible side effects doing this.

Greetings Damien

**Comment by FabianGosebrink** [comment]
The lib is not on A13 yet. Updating is one of our next steps. Check this repo for the PR when it comes :) Thanks for your patience.

**Comment by johnfabian** [comment]
@FabianGosebrink  Ok thank you. I was able to update the library and had some issues with eslint Schematics package but still was able to force it to update but haven't tested it completely yet but no rush, I can wait.  I appreciate your quick response.
