### ISSUE TITLE
Angular 9 build errors

### ISSUE THREAD

**Issue by AihamAR** [damienbod/angular-auth-oidc-client#1299]
node_modules/angular-auth-oidc-client/lib/login/par/par-login.service.d.ts:28:21 - error TS2694: Namespace 'ClientApp/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

28     static ɵfac: i0.ɵɵFactoryDeclaration<ParLoginService, never>;

**Comment by FabianGosebrink** [comment]
Thanks for posting the error message only without any content or description ;). I think that you are trying to use this lib with Angular 9 which is not supported. You have to update your Angular version to A12 to use this lib in the latest version. We are currently working on updating to Angular 13.
