### ISSUE TITLE
Is oidcSecurityService.moduleSetup bool variable really needed

### ISSUE THREAD

**Issue by bastienJS** [damienbod/angular-auth-oidc-client#130]
I am just digging more in the source code of this library as I really have to understand it.

What always bothered me is this if/else in the root component. I thought why? 

```
  if (this.oidcSecurityService.moduleSetup) {
       this.loginCallback();
    } else {
      this.oidcSecurityService.onModuleSetup.subscribe(() => {
           this.loginCallback(); 
      });
    }
```

Then I searched the issues and found this: https://github.com/damienbod/angular-auth-oidc-client/issues/50

"just testing, this doesn't always work because the onModuleSetup event is sometimes before the component subscribes to it. Need to add a moduleSetup boolean check."

I removed the if check on moduleSetup, ran my app loaded data, refreshed, entered protected route directly.

I can not see a difference to before.

The onModuleSetup is emitted from code which is again triggered from the root component. Thus I do not understand  how the above statement from Damien can be true.

I would like to resign on this if-check, but you guys know your library more.

What do you think?

**Comment by damienbod** [comment]
@bastienJS Depending when the application loads, the event might be missed, and so the check is required. Normally, the app never hits this.
