### ISSUE TITLE
Renew token not used on initial load if access token is expired

### ISSUE THREAD

**Issue by liamkeaton** [damienbod/angular-auth-oidc-client#1300]
**Describe the bug**
I'm experiencing an issue where if an access token is expired on initial load of the page the user is redirected. My expectation would be that a refresh flow would be attempted before this as our refresh tokens expiry is far longer than the access token.

I am using the configuration `responseType:code` `silentRenew:true` with `useRefreshToken:true` and the `autoLoginGuard`.

**To Reproduce**
1. Let your access token expire but not the refresh token
2. Go to an authenticated route on the site with a full page load
3. Get redirected to the authentication site

**Expected behavior**
A refresh flow is triggered and the access token refreshed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: PopOS
 - Browser: Chrome
 - Version: 96

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by damienbod** [comment]
Added configuration in version 14.2.0 which you can disabel the id_token expiry check

**Comment by davidsarkany** [comment]
@damienbod  Which parameter is this?

**Comment by FabianGosebrink** [comment]
https://www.angular-auth-oidc-client.com/docs/migrations/v14-to-v15
