### ISSUE TITLE
is response type 'code id_token' is supported?

### ISSUE THREAD

**Issue by noumanbhatti** [damienbod/angular-auth-oidc-client#131]

**Comment by bastienJS** [comment]
from the main site: "...At present only the id_token token flow is supported..."

**Comment by damienbod** [comment]
Only the 'id_token token' and the 'id_token' flows are supported.

The 'code id_token' flow should not be used together with an Anguar applicaiton.

Greetings Damien

**Comment by pedosoul** [comment]
How do we use the "id_token token" receive into our application (angular2) to request an securised .net core API ?

**Comment by damienbod** [comment]
@noumanbhatti @bastienJS 

Closing this. If your using an MVC application, then the hybrid flow would be a good option, but not for SPAs
