### ISSUE TITLE
Redirect Loop after expired session

### ISSUE THREAD

**Issue by hade94** [damienbod/angular-auth-oidc-client#1311]
Hi,

i am using the latest version of this library with identity server 4. After some time the library tries to relogin wtih the sts service but gets stuck in an infinite loop. 

On the Identity Server Side this error has been logged:

` Transformed code verifier does not match code challenge, `
[config.txt](https://github.com/damienbod/angular-auth-oidc-client/files/7610053/config.txt)
authorizedCallback, token(s) validation failed, resetting. Hash: 

Navigated to https://host.host/?code=90E6C2A651C3F339178FD4899CEE12B3B22B75D9CC159CD18300136F00938EB7&scope=openid%20profile%20defaultscope%20roles&state=0077b544d7b44350fe2b7a2bd88f0eb792ZLF9mim&session_state=six0kCb_cOmty91uWyGcI3YHSjCd5FG7-qxj3LGI08E.045A353C0D98A608253FF80335C3D9D7`

Any idea what i am doing wrong?

**Comment by damienbod** [comment]
The validation fails on the client after a callback. My guess it to you send more than one result to the STS and the callback does not match and hence fails. You should only call the checkAuth once and the callback should be handled before you do the isAuthorized check. If the validation fails you should probably navigate to a non protected route. The logs should show you the reason why it failed (Debug logs in theF12 console)

Greetings Damien

**Comment by hade94** [comment]
It was actually a time screw error. I adjusted the maxTimeScrew property in the config and voila, it worked!

Thanks anyways!
