### ISSUE TITLE
Custom Interceptor

### ISSUE THREAD

**Issue by olaisen81** [damienbod/angular-auth-oidc-client#1313]
Hi guys, as per doc, "The lib provides an own interceptor implementation which you can register like any other HTTP interceptor: and use the interceptor the lib provides you", but how can I implements my custom interceptor disabling lib defaults?

Trying to use custom interceptor defined in appmodule.ts of my app, I fall into circular dependency!

Thanks in advance.

**Comment by FabianGosebrink** [comment]
Hey, that depends on how you use it. Do you have a Stackblitz to reproduce the issue?

**Comment by olaisen81** [comment]
I've resolved it, thanks.
