### ISSUE TITLE
How to handle scenario where users bookmark the login page of the authorization server?

### ISSUE THREAD

**Issue by robinvanderknaap** [damienbod/angular-auth-oidc-client#1317]
We have some users who bookmark the login page of our authorization server. 
When using this bookmark and filling out their credentials, the authorization server redirects the user back to the client application. The client application throws the following error `could not find matching config for state`.
This error is obviously correct, because the authorization flow was not initiated by the client application and the `state` query parameter is stale.

To solve this issue, I've added a redirect in the checkAuth error handler which will trigger the authorization flow again:

```
this.oidcSecurityService.checkAuth().subscribe(_ => {}, (error:any) => {

    this.router.navigate([`/`]);
});
```

My question is if this is a correct method to handle this scenario, or is there a better solution for this problem. I'm a little worried users will be stuck in an infinite loop if some other error occurs.

Some extra information:
I'm using Angular 13 and v13.1.0 of this library.
Prior to this we used Angular 11 and the v11.x package of your library, and strangely the problem did not occur then.

**Comment by michaelmarcuccio** [comment]
I have this same concern using the same versions.

**Comment by Le-JV** [comment]
Same problem here as well. We worked around it in a similar fashion, we added a few checks to avoid landing in an infinite reload.

First we check if the error has to do with an invalid/stale state token:
```
if (err.indexOf('could not find matching config for state') > -1) {
  console.log("Stale or invalid state found, attempting redirect...");

  const reloaded = 0; // get reload amount from query param.
  if (reloaded < 1) {
    window.location.replace(window.location.origin + `?rl=${reloaded + 1}`);
  } else {
    // redirect to error page.
  }
}
```
Then we also keep track of the times we have redirected by simply adding a query token to the URL. In our case we make sure to redirect just once and if that doesn't fix it, we redirect instead to a generic error page.

This feels a bit hacky, but we have not found a better solution given the current auth flow.

**Comment by FabianGosebrink** [comment]
Hey, imho this problem can not be solved from the lib itself. The login process starts with your application and not on the auth server. So your app needs to know that a login is in process and then can match the redirection back to the app to the current login process. The only thing we could do is introduce like an error enum or something, that you do not have to do the string check. Other than that, bookmarking the auth server page is technically not a valid login process for your app and therefore not for the lib.

**Comment by robinvanderknaap** [comment]
Hey Fabian,

Thanks for your response. I agree with you. I've seen a similar solution in another library (can't remember which one). Would be great to have something like an error code, which is less brittle than examining the entire error message.

**Comment by FabianGosebrink** [comment]
Is this related to #976 ?

**Comment by robinvanderknaap** [comment]
> Is this related to #976 ?

Yes, this would solve the issue. The author mentions `invalid_state_validation` as one of the possible error codes. This would be perfect to handle the scenario of users bookmarking the login page. Based on this error code we can trigger the authentication flow again. Other errors can be handled differently, to avoid an infinite loop.
