### ISSUE TITLE
Cannot run application with latest version of angular-auth-oidc-client with Angular 11

### ISSUE THREAD

**Issue by SudeepSagar** [damienbod/angular-auth-oidc-client#1319]
**Describe the bug**

**To Reproduce**
1. Go to 'npm i angular-auth-oidc-client'
2. run ng s or npm start
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18627183/144998986-bd165dfa-33ad-4c05-ac29-23c72b7819f0.png)
![image](https://user-images.githubusercontent.com/18627183/144999257-c93fbfc0-5274-4b67-9ff8-4d90e209bb60.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 96

**Comment by FabianGosebrink** [comment]
Please refer to V11 of the lib when you want to ride with Angular 11. Or update your Angular App to V13 to run with the latest version of the lib.

**Comment by SudeepSagar** [comment]
> Please refer to V11 of the lib when you want to ride with Angular 11. Or update your Angular App to V13 to run with the latest version of the lib.

Can we use v12 of auth client lib with Angular 11?

**Comment by FabianGosebrink** [comment]
We weakened the versions a bit. You can see which version to use in the https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/package.json and check the different versions of this lib to find the correct one for your Angular version.
