### ISSUE TITLE
Error: codeFlowCodeRequest incorrect state

### ISSUE THREAD

**Issue by DevOnBike** [damienbod/angular-auth-oidc-client#1322]
**Describe the bug**
We have angular 11 app with .net core backend and config as follow:
```
{
  "$id": "1",
  "stsServer": "https://localhost:5001",
  "redirectUrl": "https://localhost:4200/afterlogin",
  "postLogoutRedirectUri": "https://localhost:4200",
  "clientId": "spa",
  "responseType": "code",
  "scope": "openid profile email ar_tokenizer_api",
  "startCheckSession": true,
  "silentRenew": true,
  "silentRenewUrl": "https://localhost:4200/silent-renew.html",
  "postLoginRoute": "/afterlogin",
  "forbiddenRoute": "/forbidden",
  "unauthorizedRoute": "/unauthorized",
  "logLevel": 1,
  "maxIdTokenIatOffsetAllowedInSeconds": 60,
  "triggerAuthorizationResultEvent": true
}
```

web library version: 11.6.11

We are using silent renew logic.

**To Reproduce**
1. user logged in to identity server 4
2. web app confirmed authorization and authentication of user
2. in random moments user gets _**ValidateStateFromHashCallback failed, state: ea7b607ebdb0372bc9b82ea28791143fe4FJBPurQ local_state:null**

**Expected behavior**
Remove unstable behavior

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Docker/Windows
 - Browser: chrome 96

**Additional context**
N/A

**Comment by FabianGosebrink** [comment]
Can you reproduce that with a sample? Either one of ours or with a repo that we can see what is going on? Thanks!

**Comment by michaelmarcuccio** [comment]
I figured out how to reproduce this(or maybe this is another error/issue?).
 
1. Bookmark the login page of your identity server with the url of a client login request.
2. Login
3. Click the bookmark that takes you back to login page with stale login.
4. Login again even though already logged in technically

At this point you are now back in your client app with successful authentication, but you get the error in your console:
[ERROR] 0-FoxxwareBilling.Client - Error: codeFlowCodeRequest incorrect state

Also, this causes my users to be directed to the unauthorized page.


P.S. There is another scenario to get an error 'could not find matching config for state' error that occurs if you do this same exact thing but in between steps 2 and 3 you logout. I handle this in my checkAuth with a catchError and reload page.

**Comment by FabianGosebrink** [comment]
The URL has a state in it which is only valid one time. Bookmarking this is not a good idea, imho. Does the bookmark contain such a value? Can you check?

**Comment by michaelmarcuccio** [comment]
Yes it does. This is what causes the state to be invalid. Users bookmark whatever they want to sadly. In my experience, over 30% of my users bookmarked the login page naturally. This seems to end up causing two issues that need to be solved in different ways on the client app side based on if the user clicking the bookmark was already logged in or not.

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
