### ISSUE TITLE
Kerberos with fallback to interactive/normal auth

### ISSUE THREAD

**Issue by swythan** [damienbod/angular-auth-oidc-client#1324]
Hi. Thanks so much for your work on this library. It's very helpful, and is working perfectly for our normal login/auth process.

Would it be possible to configure/arrange `angular-auth-oidc-client` to attempt to get a token using `kerberos` as the `grant_type`, and if that returns a error (especially 401) then to repeat the attempt using the defaults?

For context: We've got some users that are enabled to use kerberos (to avoid passwords), but most users need to be directed to the "normal" page with username, password, MFA, etc.  

Thanks again.

**Comment by damienbod** [comment]
Hi @swythan thanks, kerberos is not supported with this lib. and I don't see this being supported. This would be a medium to large effort and not many use this.

Greetings Damien

**Comment by swythan** [comment]
Fair enough, @damienbod. Thanks for replying. Always good to get definitive answer.
