### ISSUE TITLE
After upgrade from version 12 to 13 checkAuth() returns isAuthenticated = false, but access token is created

### ISSUE THREAD

**Issue by imolinelli** [damienbod/angular-auth-oidc-client#1329]
After upgrade from version 12 to 13 checkAuth() returns isAuthenticated = false, but access token is created

1. Auto login for all routes guard configuration
2. Call to checkAuth method

Token is created, and stored in session storage, but checkAuth() returns isAuthenticated = false.

Differences between v12 and v13 tokens:

v12

![image](https://user-images.githubusercontent.com/9979212/147157506-cc8c40a9-95fd-4997-bf6c-81f65eaa9287.png)

v13
![image](https://user-images.githubusercontent.com/9979212/147157539-b4cc500c-83a2-45a3-9da5-9ffe6ffe5986.png)

I have Angular 13.1.2 version

**Comment by FabianGosebrink** [comment]
You do not need to call `checkAuth()` when using the all routes guard. This is documented [here](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/auto-login#auto-login-when-all-routes-are-guarded)

**Comment by imolinelli** [comment]
I know. I only call checkAuth() to know why is not authenticated. Using all routes guard, the library redirects me to unauthorizedRoute, but there is no 401 error. Authentication returns 200 and the token is stored in session storage, but I always redirected to unauthorizedRoute ...

**Comment by imolinelli** [comment]
If I force the installation of angular-auth-oidc-client v12 with Angular 13, everything works fine.

**Comment by FabianGosebrink** [comment]
You can check if you are authenticated with other methods from the API. Closing this, but calling `checkAuth()` in combination with the Guard you are using is causing the issues here.
