### ISSUE TITLE
Version 10 Logoff before route to another component

### ISSUE THREAD

**Issue by nedevskig** [damienbod/angular-auth-oidc-client#1330]
Hi. I am using version 10. This is the situation.
1.  home.component.ts calls oidcSecurityService.authorize() on a button click.
2. After successful authorization I am calling the sts server and getting the data I need .
3.  At this point I need to manually  route to another component, but before that do a logoff. But I don't want to use the post_logout_redirect_uri  to route to the new component, I need to do that manually.
Is there a way in version 10 (there is no logofflocal) that I can do this ?
I can not omit the post_logout_redirect_uri  in the config, and I set that to route back to the home component, but then I am redirected there instead of the other component. Basically  I need to unauthorize the app before proceeding to the other component.
Thanks.

**Comment by FabianGosebrink** [comment]
I do not think we will run fixes for V10 as we are currently running towards V14.
