### ISSUE TITLE
[Bug]: Error refreshing access token (OP without refresh token rotation)

### ISSUE THREAD

**Issue by mduriancik** [damienbod/angular-auth-oidc-client#1338]
*Description:*

After 2nd access token refresh, refreshing stops with the error :
`[ERROR] - no refresh token found, please login`

---

version: 13.1.0
version Angular: 13.1.0
browser: Firefox, Chrome, Chrome Canary (Windows 10)
OIDC server: MS Active Directory Federation Services (ADFS) 2019
flow: authorization code

---

I am evaluating angular-auth-oidc-client for our angular applications authenticating with ADFS 2019 and having the following configuration:

```
{
  ...
  scope: 'openid profile offline_access',
  responseType: 'code',
  silentRenew: true,
  silentRenewUrl: `${window.location.origin}/assets/silent-renew.html`,
  renewTimeBeforeTokenExpiresInSeconds: 30,
  useRefreshToken: true,  
  ...
}
```

The refresh token lifetime is longer than the expiration of the access token (access token expiration: 1h / refresh expiration: 24h).

The first refresh is OK, but during the second refresh I get the following error:

<img width="777" alt="error-js-01" src="https://user-images.githubusercontent.com/1773459/147672689-8de255e5-3ce5-43b7-afd3-b28ec42a9f50.png">

In my opinion the problem is that when refreshing the access token, angular-auth-oidc-client looses the refresh token, ADFS 2019 does not rotate refresh tokens (if valid) and does not send with the refresh response a new refresh token.
The next time the token is refreshed there's no refresh token and I get the error.

It looks like the OP behavior (ADFS) is normal, in fact the rotation of the refresh token is optional as specified by The OAuth 2.0 RFC:

[rfc6749, 1.5 Refresh Token, step H](https://datatracker.ietf.org/doc/html/rfc6749#section-1.5)
"The authorization server authenticates the client and validates the refresh token, and if valid, issues a new access token (and, **optionally**, a new refresh token)."

---

Here's a more precise description of Client/OP interactions:

1. **Getting token**

  - request:

    GET .../token
    content: grant_type=authorization_code&client_id=07...a3913&code_verifier=e4...Am12Z&code=iS...vBJAA&redirect_uri=http%3A%2F%2Flocalhost%3A4200

  - response:

```
    {
      "access_token":"ey...UKDPg",
      "token_type":"bearer",
      "expires_in":3600,*
      "resource":"07...a3913",
      "refresh_token":"iV...mdL6g",
      "refresh_token_expires_in":28800,
      "scope":"profile openid",
      "id_token":"eyJ...D8nMw"
    }
```    

2. **1st refresh:**

  - request:

      GET .../token
      content: grant_type=refresh_token&client_id=07...a3913&refresh_token=iV...mdL6g

  - response:

     {"access_token":"ey...ONA","token_type":"bearer","expires_in":3600,"id_token":"ey...hw"}

**2nd refresh:**

Error JS

**Comment by damienbod** [comment]
When using refresh tokens in the browser, the refresh token should only be used once and rotated. Re-using refresh tokens in the browser is dangerous.

Greetings Damien

**Comment by mduriancik** [comment]
I agree that this is less secure nevertheless it is compliant with the oauth2 standard (RFC). This is the behavior of our OIDC Provider (ADFS) and I cannot change this.

I think that even if this is not supported a more correct behavior would be to raise an event (for example, isAuthenticated$ with result.isAuthenticated==false) and/or initiate a silent authentication renew. The problem is that I cannot catch this error and attempt/force a reauthentication.

We have evaluated 3 other oidc clients and for me angular-auth-oidc-client is the best but this issue is kind of annoying for us.
