### ISSUE TITLE
[Refactoring]: Expose required methods through public API

### ISSUE THREAD

**Issue by FabianGosebrink** [damienbod/angular-auth-oidc-client#1340]
Not sure if we want to do this, because I do not see the need to validate a token explicitly. The lib should take care of this internally.

`LoggerService`, `OidcConfigService` are candidates which are used but maybe can be exposed through the facade.

**Comment by FabianGosebrink** [comment]
I see the purpose of `OidcConfigService`. We will add it back in V14. Why is the `LoggerService` needed?

**Comment by timdeschryver** [comment]
I was able to remove the `OidcConfigService` import, this was a left-over from an older version.
We have the same implementation of the `LoggerService`, but we're logging the messages to our logging service (not to the console). We also have a filter in place to remove some of the logs e.g. `Error: login_required`.

**Comment by gbenthomas** [comment]
We are using a custom implementation of LoggerService similar to what @timdeschryver mentioned. 

Looks like LoggerService was exposed due to https://github.com/damienbod/angular-auth-oidc-client/issues/487

**Comment by FabianGosebrink** [comment]
Is it okay for you both to just provide your custom implementation, or do you think like an abstract logger which you can overwrite like the storage service would be better?

**Comment by FabianGosebrink** [comment]
Thanks for the feedback. I think we have to implement that and make it to land in V14. FYI. @damienbod
