### ISSUE TITLE
[Question]: Missing refresh token

### ISSUE THREAD

**Issue by diegomaceira** [damienbod/angular-auth-oidc-client#1343]
**What Version of the libraray are you using?**
"angular-auth-oidc-client": "^13.1.0"
"@angular/cli": "~12.2.11",
java: 11 auth server
...

**Question**
Hi @damienbod how are you?, im working in angular spa aplication with a java oauth2 authentication server. 
Im using your library to make the conection between both, and its working very good. 
But im having a trouble with the refresh token scenario:

1-If i execute the auth server from my angular aplication with the ClientAuthenticationMethod.NONE the callback doesnt return the refresh_token.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/22207809/148106489-fbcdbc17-e7f2-4a9a-9933-b01188dcbc66.png">

![imagen](https://user-images.githubusercontent.com/22207809/148216122-5a3a5440-7481-4a4c-a8fe-8ba8d8d54839.png)

<img width="350" alt="image" src="https://user-images.githubusercontent.com/22207809/148107295-1737eca4-3a57-49a6-bdcf-e4e020567df4.png">

2-If i execute the auth server from postman aplication with the ClientAuthenticationMethod.BASIC the callback return the refresh_token. But this case would be insecure for the spa aplication.

Do you have any idea about the ClientAuthenticationMethod configuration who i need to use for this case? or should I choose to use a silent refresh.

Thanks for your time! 
Cordially Diego,

**Comment by FabianGosebrink** [comment]
Can you provide a specific Question in the title please?
