### ISSUE TITLE
[Documentation] Loader example with promises

### ISSUE THREAD

**Issue by geromegrignon** [damienbod/angular-auth-oidc-client#1345]
## Description

The StsConfigHttpLoader documentation [example](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#load-config-from-http-async) uses the deprecated Promise version by using `toPromise()`.

```ts
export const httpLoaderFactory = (httpClient: HttpClient) => {
  const config$ = httpClient
    .get<any>(`https://...`)
    .pipe(
      map((customConfig: any) => {
        return {
          authority: customConfig.authority,
          /* Your config mapping here */
        };
      })
    )
    .toPromise();

  return new StsConfigHttpLoader(config$);
};
```

The API changed from Promise to Observable with this [example](https://github.com/damienbod/angular-auth-oidc-client/commit/9cff6ce850288cf6a4c5b67bcbcb9b5eca5baf40)

## Proposal

I can submit a related PR to fix it by removing the `toPromise()` part of the example.

**Comment by FabianGosebrink** [comment]
Hey, thanks for this. Sure, a PR would be great! Thank you for your help!
