### ISSUE TITLE
[Bug]: All paths with a query string including 'code' or 'state' are being intercepted by angular-auth-oidc-client

### ISSUE THREAD

**Issue by ZeSzymi** [damienbod/angular-auth-oidc-client#1349]
Hi 
This is a follow up to issue:  #1049

Basically I am trying to update library to newest version and there was an issue of OIDC-client intercepting the url with query params: `code` or `state`. But I have found a workaround which was providing my own `url` to `OidcSecurityService.CheckAuth(url)`.

But now you have changed the library and code looks like that
```
  checkAuth(configuration: OpenIdConfiguration, allConfigs: OpenIdConfiguration[], url?: string): Observable<LoginResponse> {
    if (this.currentUrlService.currentUrlHasStateParam()) {
      const stateParamFromUrl = this.currentUrlService.getStateParamFromCurrentUrl();
      const config = this.getConfigurationWithUrlState([configuration], stateParamFromUrl);

      if (!config) {
        return throwError(() => new Error(`could not find matching config for state ${stateParamFromUrl}`));
      }

      return this.checkAuthWithConfig(config, allConfigs, url);
    }

    return this.checkAuthWithConfig(configuration, allConfigs, url);
  }
```
And this particular method `this.currentUrlService.currentUrlHasStateParam()` is not taking into consideration provided url and takes url from:

```
  getCurrentUrl(): string {
    return this.doc.defaultView.location.toString();
  }
```

And then takes state which is totally not related with login flow and throws an error
```
return throwError(() => new Error(`could not find matching config for state ${stateParamFromUrl}`));
```

It is a bad design from the start to chech every route for query parameters state and code but that's not the issue here. Could you change it so there is posibility for `getStateParamFromCurrentUrl()` to use `url? :string` as a param and then based on if it's null or not return state?

Something like

```
  currentUrlHasStateParam(url?: string): boolean {
    return !!this.getStateParamFromCurrentUrl(url);
  }

  getStateParamFromCurrentUrl(url?: string): string {
    const currentUrl = url ?? this.getCurrentUrl();
    const parsedUrl = new URL(currentUrl);
    const urlParams = new URLSearchParams(parsedUrl.search);
    const stateFromUrl = urlParams.get('state');

    return stateFromUrl;
  }
```

Regards
Thank you for your work!

**Comment by charsleysa** [comment]
Is there any progress on this?

**Comment by nader-eloshaiker** [comment]
Unfortunately, I'm in this boat as well. Interestingly, I am unable to get it working even with the suggested `redirectTo` changes and `historyCleanupOff: false`

**Comment by nader-eloshaiker** [comment]
I have solved my issue by switching from my AuthGaurd to using ` AutoLoginPartialRoutesGuard`

**Comment by FabianGosebrink** [comment]
Could the others fix the issue with the given guard as well? I do not see a way to figure out if a parameter called "state" or "code" is from the url of the sts-redirect or inside the client's app.

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Comment by SebastienAgnez** [comment]
Hi, 
I wanted to reopen this issue #1349, because i still can't find solutions to the error "Error: could not find matching config for state ######". Have there been any new solutions found?

**Comment by piotradamczyk89** [comment]
I believe I found another possible solution. I received this error also but because of nature of my app i decided to implement OAuth2 with PKCE manually. And after this i received more or less the same problem -> it was stated on the first run of the app that states are not the same. The nature of this problem was security storage from which as I understand angular-auth-oidc-client also benefits.

So it appears that in the beginning my app runs on http://localhost:8100/ but after authorization i am redirect to http://127.0.0.1:8100. Security storage was setted twice for localhost and 127.0.0.1. As easy to understand when we are redirected we are no longer able to read a state from localhost storage. If we click log in again we already are in http://127.0.0.1:8100 so state will be written and read form the same storage so everything will work.
