### ISSUE TITLE
Error: content_script.js:99 LEVEL: ERROR | MODULE: LEAKED_CREDENTIALS | SESSION: 403ff64a | MESSAGE: "Cannot read properties of undefined (reading 'Password')" | PARAMS: {}

### ISSUE THREAD

**Issue by Xab01** [damienbod/angular-auth-oidc-client#1352]
Hello, 

We have the following message into the Chrome console log.
Version 97.0.4692.71 (Build officiel) (64 bits)

_content_script.js:99 LEVEL: ERROR | MODULE: LEAKED_CREDENTIALS | SESSION: 403ff64a | MESSAGE: "Cannot read properties of undefined (reading 'Password')" | PARAMS: {}_

This error is present is several applications in Angular that We develop. 

The message doesn't appear on firefox. 

Do you have any ideas why or what we can do to remove this error message ?

Thanks in advance

Xavier

**Comment by FabianGosebrink** [comment]
Do you have any hints that it has to do with the library? Did you remove it and see the error disappear?
