### ISSUE TITLE
[Question]: How to inject access token in requests using provided http interceptor (version-13) ?

### ISSUE THREAD

**Issue by r-oueslati** [damienbod/angular-auth-oidc-client#1354]
**What Version of the libraray are you using?**
13.1.0 with Angular 13.1.1

**Question**
I've been trying to use this library for a few days to have my angular application use a REST API using an access token.
I'm almost there. I can see it gets the authorization code and exchanges it with the access token. And I see the access token in the session storage.
However the api requests do not include the access token in the authorization header.
After the access token was stored it seems checkAuth is called and the debug log shows:
```
checkAuth completed - firing events now. isAuthenticated: false
```
and then:
```
Wanted to add token to https://<api_url> but found no token: 'null'
```

Please what could I be doing wrong ?

auth-config.module.ts:
```
mport { NgModule } from '@angular/core';
import { AuthModule, LogLevel } from 'angular-auth-oidc-client';

@NgModule({
    imports: [AuthModule.forRoot({
        config: {
            authority: 'https://<some_url>',
            authWellknownEndpointUrl: 'https://<authserver>/.well-known/openid-configuration',
            autoUserInfo: false,
            redirectUrl: window.location.origin,
            postLogoutRedirectUri: window.location.origin,
            clientId: '<client_id>',
            scope: '<single_scope>',
            responseType: 'code',
            silentRenew: false,
            renewTimeBeforeTokenExpiresInSeconds: 10,
            logLevel: LogLevel.Debug,
            secureRoutes: ['https://<api_url>']
        }
      })],
    exports: [AuthModule],
})
export class AuthConfigModule {}
```
app.module.ts:
```
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AuthInterceptor, AuthModule } from 'angular-auth-oidc-client';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AuthConfigModule } from './auth/auth-config.module';
import { ItemsComponent } from './items/items.component';
import { HomeComponent } from './home/home.component';

@NgModule({
  declarations: [
    AppComponent,
    ItemsComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    AuthModule,
    AuthConfigModule
  ],
  providers: [
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by r-oueslati** [comment]
I did read the documentation [here](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/using-access-tokens) or [here](https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/site/angular-auth-oidc-client/docs/documentation/using-access-tokens.md)

But it seems getAccessToken() is no longer an observable in version 13.1.0.
And also `AuthModule.forRoot()` can no longer be included in the module imports.

I've been trying to figure it out but still unsuccessful.

Any help would be greatly appreciated.

Thank you

**Comment by r-oueslati** [comment]
I give up

**Comment by scurk1415** [comment]
I am not sure if it is the same problem as what i had (which sound similar based on your description), but In my case id_token was missing from the /token response. The way to fix that is to add **openid** in your scopes (had to debug the source code to find that).

**Comment by FabianGosebrink** [comment]
For debugging, you can always write your own interceptor and try getting the AccessToken.
