### ISSUE TITLE
[Bug]: Error while calling logoffAndRevokeTokens

### ISSUE THREAD

**Issue by bmarvinb** [damienbod/angular-auth-oidc-client#1357]
**What Version of the library are you using?**
12.0.3

**Describe the bug**
When I call 
```typescript
this.oidcSecurityService.logoffAndRevokeTokens().subscribe();
```
I got an error
![MicrosoftTeams-image](https://user-images.githubusercontent.com/23120972/149495976-b83c4483-a4ff-4a56-9f8d-2d6974edb870.png)

**To Reproduce**

1. run this.oidcSecurityService.logoffAndRevokeTokens().subscribe();
2. See error "cannot read properties of null (reading "toLowerCase")

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS/Windows
- Browser Edge (Version 97.0.1072.55)
- Browser Chrome (97.0.4692.71)

**Comment by badgerduke** [comment]
Hello, I am having the same problem.  Is there a workaround?

**Comment by agardiol** [comment]
Hello. I got also the same problem. In my case it came from the absence of the revoke_token endpoint in the well known endpoints list on the server. The library does not detect this and try to use it while it is null.
To solve this you have two options:
1. If you have control on the server, you can add the revoke_token endpoint in the well known endpoints list or
2. As a workaround, you can manually add the endpoint in the session data used by the library. Here is how I do that:
```
this._oidcSecurityService.checkAuth().subscribe(({ isAuthenticated, userData, accessToken, idToken, configId }) => {
            if (isAuthenticated) {

        // Check if revocation endpoint is set in the configuration well known enpoints
        let sessionData = sessionStorage.getItem(configId);
        if (sessionData) {
          let sessionDataJSON: any = JSON.parse(sessionData);
          const revokationEndpoint = environment.backend_url + '/o/revoke_token/';
          if (!sessionDataJSON['authWellKnownEndPoints']['revocationEndpoint']) {
            // and add it if not
            sessionDataJSON['authWellKnownEndPoints']['revocationEndpoint'] = revokationEndpoint;
            sessionData = JSON.stringify(sessionDataJSON);
            sessionStorage.setItem(configId, sessionData);
          }
        }
    }
}
``` 
Hope it will help.
Antoine

**Comment by badgerduke** [comment]
Thank you @agardiol !  This is very helpful.  Turns out Amazon Cognito does not advertise the revocation endpoint when calling for the well-known endpoints.  One question though, to actually log out I need to call the Cognito "/logout" endpoint in addition to the revocation endpoint and logoffLocal.  Looking at this library's source code I don't see the use of that endpoint.  So I ended up redirecting to the logout endpoint (window.lcoation.href = <cognito logout endpoint>).  This works fine for now.  But revoking the tokens by itself isn't enough for me.  Anyway, thank you!

**Comment by agardiol** [comment]
Do you use the [postLogoutRedirectUri ](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#postlogoutredirecturi) in the configuration. Maybe it can help.

**Comment by jgarciaokode** [comment]
Hi, in case someone is stuck here

I managed to get it working with cognito without setting manually the endpoint values in the local storage with this configuration


```ts
import { isPlatformBrowser } from '@angular/common';
import { Injectable, Inject, PLATFORM_ID, Optional } from '@angular/core';
import {
  OpenIdConfiguration,
  StsConfigStaticLoader
} from 'angular-auth-oidc-client';

@Injectable({ providedIn: 'root' })
export class OidcConfigService {
  constructor(
    @Inject(PLATFORM_ID)
    private platformId: Record<string, unknown>,
    @Optional() @Inject('X_FORWARDED_HOST') private host: string
  ) {}

  getConfig(): OpenIdConfiguration {
    const postLogoutRedirectUri = isPlatformBrowser(this.platformId)
      ? window.location.origin + '/home'
      : `${this.host}/home`;
    const clientId = 'XXXXXXXXXXX';
    const urlEncodedLogoutUri = encodeURIComponent(postLogoutRedirectUri);
    const endSessionEndpoint = `https://mar2-domain-cogn.auth.eu-west-1.amazoncognito.com/logout?client_id=${clientId}&logout_uri=${urlEncodedLogoutUri}`;
    const userPoolId = 'XXXXXXX';
    return {
      authority:
        'https://mar2-domain-cogn.auth.eu-west-1.amazoncognito.com/oauth2/authorize',
      redirectUrl: isPlatformBrowser(this.platformId)
        ? window.location.origin
        : this.host,
      clientId,
      unauthorizedRoute: 'unauthorized',
      postLogoutRedirectUri,
      scope: 'openid profile email mar2-resource-server/mar2.read', // 'openid profile offline_access ' + your scopes
      responseType: 'code',
      silentRenew: true,
      useRefreshToken: true,
      maxIdTokenIatOffsetAllowedInSeconds: 600,
      secureRoutes: ['http://example.org/api'],
      authWellknownEndpointUrl:
        `https://cognito-idp.eu-west-1.amazonaws.com/${userPoolId}/.well-known/openid-configuration`,
      issValidationOff: false,
      authWellknownEndpoints: {
        endSessionEndpoint,
        authorizationEndpoint: 'https://mar2-domain-cogn.auth.eu-west-1.amazoncognito.com/oauth2/authorize',
        issuer: `https://cognito-idp.eu-west-1.amazonaws.com/${userPoolId}`,
        jwksUri: `https://cognito-idp.eu-west-1.amazonaws.com/${userPoolId}/.well-known/jwks.json`,
        tokenEndpoint: 'https://mar2-domain-cogn.auth.eu-west-1.amazoncognito.com/oauth2/token',
        userInfoEndpoint: 'https://mar2-domain-cogn.auth.eu-west-1.amazoncognito.com/oauth2/userInfo'
      },
      autoUserInfo: false,
      customParamsAuthRequest: {
        prompt: 'select_account', // login, consent
      },
    };
  }
}

export const authFactory = (configService: OidcConfigService) => {
  const config = configService.getConfig();
  return new StsConfigStaticLoader(config);
};

```
