### ISSUE TITLE
[Feature Request]: Customizable redirectUrl for Popup Login

### ISSUE THREAD

**Issue by mduriancik** [damienbod/angular-auth-oidc-client#1361]
Hello everybody,

**Description**: It would be nice to have a possibility to redirect the authentication flow to a specific page for logins with popup.

**Problem**: an Angular SPA can be quite large and its loading and initializing is not always optimized (or "optimizable").
When using login in a popup, the whole application is loaded in the popup but all this application does is send a message to the opener window, then the popup is closed.

**Solution**: It would be nice to be able to use just a simple page with a 'sendMessage(currentUrl,currentUrl)' to relay the OP response to the application (in fact that's all a popup does).

I you are interested I can make a pull request either:

1. to pass a URL in parameters to authorizeWithPopUp (something like this: `OidcSecurityService.authorizeWithPopUp({redirectUrl: '/assets/simplified-popup-login.html', ...})`) or
2. to add a configuration property 'popupLoginRedirectUrl' (with default == redirectUrl),

this will make possible to specify a diffrent redirectUrl (a simple page) for popup logins.

(solution 1. could be extended to OidcSecurityService.authorize() which would simplify the code and could be useful for customization of returns form Oidc Provider in general)

**Comment by FabianGosebrink** [comment]
Should be possible in the latest version.
