### ISSUE TITLE
[Question]: OWASP ZAP complains about missing Content-Security-Policy attributes 

### ISSUE THREAD

**Issue by patolax** [damienbod/angular-auth-oidc-client#1362]
When we run OWASP ZAP scanner following medium severity warnings popup for login and code endpoint requests.
In the first case Content-Security-Policy headers are missing but in the second case some can be found in the header.

Our implementation: Identity server 4 .net core, angular 11 with "angular-auth-oidc-client": "12.0.2"

**Warning 1 : Missing Anti-clickjacking Header**
The response does not include either Content-Security-Policy with 'frame-ancestors' directive 
https://tst-001.net/client/?code=msJL_VHdtfPHgYDWW0B-0gHgoBDUov4Do_p8x7CIJFM&20permissions%20personal%20user%20asset%20

**Warning 2: CSP: Wildcard Directive**
The following directives either allow wildcard sources (or ancestors), are not defined, or are
overly broadly defined:
frame-ancestors, form-action
The directive(s): frame-ancestors, form-action are among the directives that do not fallback
to default-src, missing/excluding them is the same as allowing anything.

https://tst-001.net/auth/Account/Login?ReturnUrl=%2Fauth%
2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dangular_client%
in this case following headers are found in the response but we get above warning
![image](https://user-images.githubusercontent.com/29444156/150472474-fa406735-2e8f-44b6-93ad-10b97ee45620.png)

**Comment by damienbod** [comment]
Hi @patolax yes you need to add these but these headers are not part of the lib. You must add the protections to the meta data of the host html file. You have one, but it is missing everything. This also depends on your hosting env but you should always add this.

Grettings Damien

**Comment by patolax** [comment]
I am assuming you are talking about Identity server hosting is where I have to add these meta tags?
but the documentation is saying this.
https://identityserver4.readthedocs.io/en/latest/reference/options.html?highlight=csp#csp-content-security-policy
Do we have to do more?

**Comment by damienbod** [comment]
if you use an ASP.NET Core application, you can use middleware to implement this. The meta tags are just for static websites.
