### ISSUE TITLE
[Bug]: Dynamic custom parameters not added to silent-refresh calls 11.6.11

### ISSUE THREAD

**Issue by EEdgeLearner** [damienbod/angular-auth-oidc-client#1365]
**What Version of the library are you using?**
Angular 10  with angular_auth_oidc_client 11.6.11

**Describe the bug**
SilentRenew is set true
The silentRenew.html is getting called but the custom parameters set are not coming with authorize? call

We are not in a position to upgrade from 11 to 12 until you confirm this as a bug. Please confirm

**Comment by FabianGosebrink** [comment]
Hey @ColinLaws , thanks for the mention and the response. Do you have a use case where you would like to use the Service before configuring it? Thanks!

**Comment by ColinLaws** [comment]
@FabianGosebrink I wasn’t intending on using the service before the configuration was loaded, it just happens that after upgrading from v11 to v12, I could not solve an issue in which the OidcSecurityService was accessed by one of my guards. I believe that the old method of configuring Oidc protected against this, as it was using the ‘APP_INITIALIZER’ injection token, which always ensured the config was loaded. I couldn’t solve what I believe was a race condition between the service being configured, and one of my guards  accessing the Oidc service to check the auth state.

**Comment by FabianGosebrink** [comment]
Yes, that is an Angular "problem", depending on how you use guards and the service. When the app does not start, the config can not be passed and without the passed config, the guard can not check if authenticated or not and the app can not start. Chicken-Egg thing. Some of our customers have these issues. This is why we created two guards for this in the latest version. Also check out this blog here: [Loading Configuration Before Your Angular App Starts](https://offering.solutions/blog/articles/2021/11/11/loading-configuration-before-your-angular-app-starts/)

**Comment by ColinLaws** [comment]
Thank you for that information Fabian, and confirming what I believed was the issue I was experiencing. I was using the AutoLoginGuard by the way to cover auth for the entire app, just so you didn’t think I was trying to implement my own auth guards. AutoLoginGuard always worked great in v11, and I never ran into any issues I had to handle concerning app initialization. Your response definitely answered my questions by the way, I just wanted to clarify for the record, and anyone else running into this issue.
