### ISSUE TITLE
Static configuration not loaded at provider classes level

### ISSUE THREAD

**Issue by Dynamic91** [damienbod/angular-auth-oidc-client#1369]
Hello,

We have an app and on root app module, on import we load the AuthModule with static configuration. On the providers list we have a provider that uses a class at which the constructor injects the OidcSecurityService and call the checkAuth method. The problem is that the configuration specified in AuthModule import is set internally in angular-auth-oidc-client after angular runs all the constructors of the classes specified in provider list, so at the time we want to call the checkAuth method, the configuration is not available. 

Is there a workaround to have the configuration available at the constructors of the classes used in provider list? What other solutions do we have?

Thank you!

**Comment by FabianGosebrink** [comment]
Are you calling `checkAuth()` in the constructor?

**Comment by Dynamic91** [comment]
Yes

**Comment by FabianGosebrink** [comment]
This is too early because it is executed by instantiation from DI.

**Comment by Dynamic91** [comment]
Do you mean that it is early to run in any constructor (like the root component) or the constructor of an provided useClass?
