### ISSUE TITLE
[Bug]: startCheckSession can cancel the endsession redirect to logout call before logoffAndRevokeTokens finishes

### ISSUE THREAD

**Issue by michaelmarcuccio** [damienbod/angular-auth-oidc-client#1371]
**What Version of the library are you using?**
v13.1.0

**Describe the bug**
With startCheckSession enabled and calling logoffAndRevokeTokens, the startCheckSession can trigger a /connect/authorize call while the server is still trying to log the user out and ends up cancelling the /account/logout call initiated by endsession 302 redirect on the identityserver.

I noticed that logoff local stops the checksessionservice:
`logoffLocal() {
    this.resetAuthDataService.resetAuthorizationData();
    this.checkSessionService.stop();
  }`

If logoffAndRevokeTokens were to also stop the checksessionservice (which I don't see why it does not in the first place), this issue would not occur. 

**To Reproduce**

1. Enable  startCheckSession: true in config
2. Put breakpoint or Thread.Sleep for a few seconds on /account/logout endpoint of identityserver (this simulates a slow response by the server which causes this whole issue in the first place)
3. Call logoffAndRevokeTokens() from client.
4. The user is not logged off and is redirected to client app.

**Screenshots**
![image](https://user-images.githubusercontent.com/20432260/152260105-ad66ec93-b0b7-4362-b586-d64b39bb3234.png)

**Solutions**
The following solves the issue as it stops the checksessionservice:
` this.oidcSecurityService.logoffAndRevokeTokens().subscribe(() => this.oidcSecurityService.logoffLocal())`

If this is the intended way to do this, then close this bug ticket as solved. It was very confusing that this was necessary as logoffAndRevokeTokens does both revoke and logout.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 97.0.4692.99

**Comment by FabianGosebrink** [comment]
Is this issue still relevant? Did you upgrade to the latest version?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Comment by michaelmarcuccio** [comment]
@FabianGosebrink  yep this still occurs. very easy to reproduce.

**Comment by fightknights** [comment]
@FabianGosebrink This is still a thing.
angular-auth-oidc-client@15.0.2
angular/core@15.0.4

**Comment by mahidhar25** [comment]
@FabianGosebrink any update on this still we are facing issues
angular-auth-oidc-client: "^15.0.3"
angular/core: "^15.1.5"

**Comment by FabianGosebrink** [comment]
I have not yet looked into this.

**Comment by mahidhar25** [comment]
@FabianGosebrink May I know when can we expect this fix? Or else please provide any workaround for this issue

**Comment by michaelmarcuccio** [comment]
@mahidhar25 I provided a workaround in the initial bug report.

**Comment by mahidhar25** [comment]
@michaelmarcuccio thanks for the workaround it is working as expected locally but it is not working in the production environment
