### ISSUE TITLE
[Question]: Can I use this library on oauth-service without well-known endpoint ?

### ISSUE THREAD

**Issue by ebeling** [damienbod/angular-auth-oidc-client#1373]
**What Version of the library are you using?**
13.1.0

**Question**
I try using this lib with Polar Accesslink (https://www.polar.com/accesslink-api/#authentication). If I start my angular app with 
` this.oidcSecurityService.checkAuth().subscribe( ...)` 
an error occured:  "Getting auth well-known endpoints failed on start". I think, that there are not such endpoint. I have tried to find it via direct call in browser.
Is it possible using this lib for server without well-known endpoint and is there an example I can view?

**Comment by KitoCoding** [comment]
Can you provide your auth config? It would help debug.
