### ISSUE TITLE
[Question]: Version 14

### ISSUE THREAD

**Issue by scurk1415** [damienbod/angular-auth-oidc-client#1374]
How do i get version 14? The documentation and readme both show that the current version is 14, but neither _npm_ nor _ng add_ install version 14. As far as i can see the latest version is 13.1.0.

Is that a mistake or is the documentation ahead of its time? 😄

**Comment by damienbod** [comment]
Hi @scurk1415 YEs we have not released this yet. Will sync with @FabianGosebrink when we do this :)

Greeitngs Damien

**Comment by FabianGosebrink** [comment]
The documentation is ahead of its time and "prepared". Stay tuned, we have a few things to do and will release V 14 when we are ready.
