### ISSUE TITLE
[Question]: Is it possible to avoid forced redirect from checkAuth?

### ISSUE THREAD

**Issue by NachoBoss** [damienbod/angular-auth-oidc-client#1375]
I was wondering if it was possible to avoid the redirect made from checkAuth. In the examples posted with the package, you have checkAuth in AppComponent. I think I remember a post saying that a check auth needs to occur in order to populate values. When i remove the checkAuth, the redirect issues no longer occur, but my authentication is always returning false. 

I have appComponent ngOnInit with checkAuth. 
I have a /login route. which has a login button that pushes me to the IDP login page.

The redirect I have set up is set for /_signedin.  

This _signedin component is responsible for validating the user has access to the app in question. So it needs to be able to validate authentication, but also fetch user data and compare to the apps db. 

My issue currently is. With CheckAuth in the appComponent, the signedIn component doesn't finish doing what it needs to do before it forces a redirect to the main domain : http://localhost:4200/

I could be going at this wrong, just trying to follow the samples in the project.

**Comment by NachoBoss** [comment]
It looks like its not possible. But I was wondering if there was a way around it. looking at the source code. Its verifying if isAuthenticated is true then redirecting based on the storage key "redirect". However, my redirect set up is pointing to: localhost:4200/_signedin.  But it redirects to localhost:4200.   I have verified this is the case via checking my route redirects and tracing the navigation.

**Comment by diblaze** [comment]
@damienbod I see that you closed this, but it has not been adressed. Will this be added as an option in V14? If so, when is the release?

**Comment by damienbod** [comment]
@diblaze don't know when the release is, we still have some implementation left. The checkAuth does not force a redirect unless you want this. The redirect on the server has to match the redirect on the client. 

Greetings Damien

**Comment by diblaze** [comment]
Are you sure it does not force redirect?
The redirectURL is set to my callback component, but as soon as chechAuth gets a new value (subscribe) then it will redirect to the main domain. This is not wanted.
This issue (created by @NachoBoss) is describing the issue: https://github.com/damienbod/angular-auth-oidc-client/issues/1388

In v14 documentation I see the following for the ```authorize``` method: 
```ts
export interface AuthOptions {
  customParams?: { [key: string]: string | number | boolean };
  urlHandler?(url: string): any;
  redirectUrl?: string;
}
```
I guess we can in V14 tell it to redirect to a different url?

**Comment by FabianGosebrink** [comment]
Yes since V14 you can have a redirectUrl in the AuthOptions, overwriting the "global" config in this case.
