### ISSUE TITLE
[Question]: Why does forceRefreshSession() not reload my identity token, but returns the persisted identity token?

### ISSUE THREAD

**Issue by morrowyn** [damienbod/angular-auth-oidc-client#1378]
**What Version of the library are you using?**

Version: `13.1.0`

My config setting apart from the redirect uris and client ids

```
 responseType: 'code',
              silentRenew: true,
              useRefreshToken: true,
              autoUserInfo: false,
              renewTimeBeforeTokenExpiresInSeconds: 30,
              logLevel: LogLevel.Debug,
```

**Question**
Im trying to use the forceRefreshSession() in order to receive a new identity token. When I use the forceRefreshSession() I get the following log:
```
Checking: silentRenewRunning: false - has idToken: true - has userData: true
Has idToken expired: false --> expires in 3:19 , 5:36:01 PM > 5:32:42 PM
Has accessToken expired: false --> expires in 3:20 , 5:36:02 PM > 5:32:42 PM
persisted idToken and accessToken are valid
```

Afterwards I receive the persisted token instead of the new identity token from the idp. I'm under the impression that a `force` would override the persisted token and goes to the idp server to get a new one. Any idea what I'm missing here?

Regards,

**Comment by morrowyn** [comment]
It seems that if I use 
```
this.oidcSecurityService.authorize(null, {customParams : {prompt: 'none' }});
```
I receive a new token and everything works

**Comment by JohnGalt1717** [comment]
Is there a way to get forceRefreshSession to do this? The reason I ask, is that authorize doesn't return anything, but forceRefreshSession you can await and then act accordingly.

Alternatively, is there an awaitable way to force reload of the id token?

**Comment by rdu** [comment]
@morrowyn forceRefreshSession returns an obervable. An observable must be subscribed to be fired.
