### ISSUE TITLE
Audience list does not work

### ISSUE THREAD

**Issue by feargear** [damienbod/angular-auth-oidc-client#138]
We were using angular-auth-oidc-client v1.3.14 and decided to update to the latest client. Our identity server (wso2is) returns a list of clientid:s in the id_token's **aud** property. However, the new version of the angular oidc client seems to compare the list directly with a string. I noticed that the ts code is like this

`if ((dataIdToken.aud as string) !== (aud as string)) {
    this.oidcSecurityCommon.logDebug(
        'Validate_id_token_aud failed, dataIdToken.aud: ' +
            dataIdToken.aud +
            ' client_id:' +
            aud
        );
        return false;
}`

But this gets transpiled to:

`if (((dataIdToken.aud)) !== ((aud))) {
    this.oidcSecurityCommon.logDebug('Validate_id_token_aud failed, dataIdToken.aud: ' +
            dataIdToken.aud +
            ' client_id:' +
            aud
        );
        return false;
}`

In the old version this worked because they were compared with the value equal operator, but now it broke our app.

**Comment by damienbod** [comment]
OK, I will support a array again. We updated to strict Typescript, incorrectly. I will add support for arrays again. Will fix this in the next couple of days. Thanks for reporting

Greetings Damien

**Comment by damienbod** [comment]
Now supports an array of strings of any object.

Will release this weekend, just need to fix a test first

**Comment by damienbod** [comment]
fixed in 3.0.9
