### ISSUE TITLE
How can I make sure that the code inside isAuthenticated$.subscribe((config) => { if (config.isAuthenticated) { }}) is run only once

### ISSUE THREAD

**Issue by axell9641** [damienbod/angular-auth-oidc-client#1381]
**What Version of the library are you using?**
13.1.0
**Question**
After I got redirected from Keycloak I execute some inside the app.component.ts that must run only once. 

This is the code I use: 

```
 ngOnInit(): void {  
  this.subs.sink = this.oidcSecurityService.isAuthenticated$.subscribe((config) => {
      if (config.isAuthenticated) {
         // Code here must run only once.
      }
    });
  }
```

The problem is that the code inside that if is called not once, but three times.
Is there any way I can be notified only once the authentication process is done and the user is authenticated? 

Thanks.

**Comment by FabianGosebrink** [comment]
I dont know why it is executed three times but you can always use `take(1)` as a pipeable operator.

**Comment by axell9641** [comment]
> I dont know why it is executed three times but you can always use `take(1)` as a pipeable operator.

I think it would be more like `skip(1), take(1) ` because the first value returned will be false.

In any case, do you know if there's way I can get notified only once the value of isAuthenticated has changed  ?

**Comment by FabianGosebrink** [comment]
This would not be good because you want to be notified, when something changes. However, you can always check with a flag if your code has already run.
