### ISSUE TITLE
 i want to upgrad to version 14 to get the isLoading$ observable but im getting error in npm

### ISSUE THREAD

**Issue by alexkoretzki** [damienbod/angular-auth-oidc-client#1382]
currently we have version 13

when i try to install version 14 im getting this error
npm ERR! notarget No matching version found for angular-auth-oidc-client@14.0.0.
thanks

**Comment by damienbod** [comment]
@alexkoretzki We have not released V14 yet, still have some small stuff to add

Greetings Damien
