### ISSUE TITLE
Support for silent renew without requiring access token

### ISSUE THREAD

**Issue by acwatson** [damienbod/angular-auth-oidc-client#139]
The angular-auth-oidc-client is awesome! Here's one suggestion:

Currently, the OidcSecurityService.runTokenValidation method checks to see if there is a value for `_this._userData.value` before it will perform a silent renew via `_this.refreshSession();`

For my use case, I actually don't want an access token or userData at all. All I need is the id token and for it to be renewed when it expires. I noticed that if I did not enable getting an access token and user data, the silent renew functionality would not work.

I tried changing the "if" block in `OidcSecurityService.runTokenValidation` so that it checked `_this._isAuthorizedValue` instead of `_this._userData.value`. This fixed it for me so that I can have silent renew working without having to get an access token and user data.

It seems like this change can only help and I can't think of anything it would hurt. What do you think? Should the angular-auth-oidc-client module be changed to check for `_this._isAuthorizedValue` instead of `_this._userData.value`? Thanks.

**Comment by Pasivk86** [comment]
Hi, I am also joing for the request. I am using b2c and always my userData is empty. Filling userData is not working for b2c. I discover the same problem with token renew like acwatson write. Can apply that change in next release?

**Comment by damienbod** [comment]
implemented in 3.0.9

**Comment by Pasivk86** [comment]
Yes its working now. Empty UserData was the problem before, when now userData is supported for b2c token renew is working. Thank you for very fast response
