### ISSUE TITLE
[Question]: AutoLoginAllRoutesGuard with popup login?

### ISSUE THREAD

**Issue by josi02** [damienbod/angular-auth-oidc-client#1393]
**How can I use AutoLoginAllRoutesGuard with popup login?**

I didn't find any option to set this up.

Popup login examples contains using `authorizeWithPopUp` but in case of AutoLoginAllRoutesGuard it is not called directly.

**Lib version: 12.0.3**

**Comment by makandre** [comment]
I'm interested to know if this is possible as well.

**Comment by maxsalo** [comment]
Me too!
