### ISSUE TITLE
[Feature Request]: Make id_token_hint optional on session end logout

### ISSUE THREAD

**Issue by scurk1415** [damienbod/angular-auth-oidc-client#1396]
**Is your feature request related to a problem? Please describe.**
When session ends the user is redirected to the _end_session_endpoint_ with the added parameter _id_token_hint_ (plus some custome parameters and postLogoutRedirectUri).

The end URL that is created looks like this
/protocol/openid-connect/logout?**id_token_hint=undefined**&post_logout_redirect_uri=LOCATION

The problem here is that our backend authentication server (keycloak 15.1.1) make a validation for id_token_hint if it is null (I guess keycloak transforms undefined into "undefined" and performs validation on it).

If the logout URL is like (without id_token_hint parameter)
/protocol/openid-connect/logout?post_logout_redirect_uri=LOCATION

Then it works correctly.

**Describe the solution you'd like**
Don't add the parameter if it does not have a value.

In **UrlService.createEndSessionUrl**
```typescript
if (!!idTokenHint) {
    params = params.set('id_token_hint', idTokenHint);
}
```

**Describe alternatives you've considered**
In case some providers require the id_token_hint parameter (even if its empty), then you can maybe add a config parameter to OpenIdConfiguration (something like skipEmptyIdTokenHintOnLogout)
```typescript
const skipToken = this.getSkipEmptyIdToken(configuration);
if (!!idTokenHint || !skipToken) {
    params = params.set('id_token_hint', idTokenHint);
}
```

**Additional context**
angular-auth-oidc-client: 13.1.0
keycloak: 15.1.1

The changed code above was taken from the 14.0.0 version of your library (it might be a little different on 13.1.0).

I can make a pull request, if the suggested solution is ok for you

**Comment by scurk1415** [comment]
Any thoughts about this?

**Comment by damienbod** [comment]
This sounds like a good idea, need to validate if the specs allow this

Greetings Damien

**Comment by scurk1415** [comment]
Any update for this?

**Comment by chris-befoul** [comment]
Checking in to see what the status is on this update?

**Comment by damienbod** [comment]
Thanks for the issue. Checked with the specs, looks fine. 

Can you make a PR? We will add this to the next version.

Greetings Damien

**Comment by emanuelefricano93** [comment]
Hello guys, just run on the same issue described here.
Here the [PR](https://github.com/damienbod/angular-auth-oidc-client/pull/1512) as suggested by @scurk1415 and @damienbod.

Have a nice day,
Emanuele

**Comment by aiscrim** [comment]
I am having the same issue too with KeyCloak. The PR doesn't fix the issue, it only modifies the error that we get: without that change, the id_token_hint was passed as "undefined", which was rejected as invalid; but after the change it just doesn't pass it, which results in a different failure: the error "Missing parameters: id_token_hint" is now returned.  
KeyCloak accepts as a valid alternative the client_id if the id_token_hint is not passed. Therefore a possible solution would be to pass the client_id to the endsession endpoint. It could be always passed, or only when the id_token_hint is not available. That would make KeyCloak happy, and its users too.
