### ISSUE TITLE
[Question]: Can the authorizeWithPopUp initiated automatically e.g. in ngOnInit

### ISSUE THREAD

**Issue by josi02** [damienbod/angular-auth-oidc-client#1397]
**Can the authorizeWithPopUp initiated automatically e.g. in ngOnInit**

I tried to call it in app.component.ts (I used the sample `sample-code-flow-popup`) but I got an infinite loop of popups even the login was successful.
Also I tried to take the first (rxjs) but with same effect.

Does somebody has any idea how can I use popup login automatically during start the app?

**Comment by damienbod** [comment]
@FabianGosebrink Any ideas?
