### ISSUE TITLE
UserData support for azure b2c

### ISSUE THREAD

**Issue by paszkowskik** [damienbod/angular-auth-oidc-client#140]
Hi, we decided to choice your library because it has best feature of all oidc b2c libraries but one feature it is still missing for azure b2c.
Generaly I got a problem with token renew and after analyse the code I understood that problem is cause userData has empty string. UserData is based on userInfo endpoint that azure dont provide yet. Currently for my own purpose to get all user claims I am using .oidcSecurityService.getPayloadFromIdToken(). The problem is userData inside the library is empty and token renew is not working.
Can you support the path when well_known_configuration don't contain userInfo endpoint then userData should be taken from oidcSecurityService.getPayloadFromIdToken().

It would be nice if we would got that feature in future release.

**Comment by damienbod** [comment]
@paszkowskik thanks

If you set the auto_userinfo to false, the user data is not used. This should work, otherwise this is a bug. 

Hope this helps greetings Damien

**Comment by paszkowskik** [comment]
Thank you for very fast replay. Unfortunetly we have auto_userinfo = false and this case that i wrote before is happens no matter of that flag.

**Comment by damienbod** [comment]
@paszkowskik I will support this then as soon as possible. Want to do a fix this weekend, will add this fix, if I find the bug

**Comment by damienbod** [comment]
openIDImplicitFlowConfiguration.auto_userinfo = false;

When this is set, the user data is now set from the id_token.

Will merge and release, once I get a test fixed.

**Comment by paszkowskik** [comment]
Thank you very much. We are waiting for release.

**Comment by damienbod** [comment]
fixed in 3.0.9

**Comment by damienbod** [comment]
found another bug for this, will fix and release it in 3.0.10

**Comment by paszkowskik** [comment]
We will check it tommorow when we will come back to work. Good job, we are very thankful.

**Comment by paszkowskik** [comment]
We can proudly say that problem is resolved. First case userData is working correctly with b2c when flag auto_userinfo = false. Second thing is renew token is working now and that was very important case for us. Only one thing I notice that is a mistake in documentation because to renew token before it expire you must put positive value, not negative like documentation suggest.
Thank you very much.

silent_renew_offset_in_seconds

Makes it possible to add an offset to the silent renew check in seconds. By entering a **negivative value**, you can renew the tokens, before the tokens expire.
