### ISSUE TITLE
[Bug]: Doesn't close login window in browser after redirecting to cordova app

### ISSUE THREAD

**Issue by dewebeloper** [damienbod/angular-auth-oidc-client#1405]
I'm following a blog post about securing a Cordova App from https://offering.solutions/blog/articles/2020/09/17/securing-a-cordova-app-implemented-with-angular-using-oidc-and-oauth2.
In short, after implementing code from post, all works fine and I'm able to redirect to STS, to login and back to Cordova. But after redirection to Cordova app, STS login window stays open in a browser.
After some debugging, it looks like `this.modal` has a reference on the wrong window!?
![DxJT1cQPwt7Nrasn](https://user-images.githubusercontent.com/3725912/158008127-91331ddd-55aa-4344-bcdc-8aefe1803f11.png)

I'm using `"angular-auth-oidc-client": "^13.1.0",`

Reproducible example on https://github.com/dewebeloper/CordovaStsLogin.git.

**Comment by FabianGosebrink** [comment]
Is this also reproducible, maybe in an electron environment?

**Comment by dewebeloper** [comment]
I don't know. I'm not familiar with electron environment.

**Comment by FabianGosebrink** [comment]
See a working example here https://github.com/FabianGosebrink/cordova-angular-oauth2-oidc
