### ISSUE TITLE
[Question]: is there event that i can register to be notified when the token is expired?

### ISSUE THREAD

**Issue by alex-koretzki** [damienbod/angular-auth-oidc-client#1406]
v 13.0.0

i need some solution to get notified when the token is expired.
is there some event for it?
i cant find ant in the docs.
thanks

**Comment by soners** [comment]
Hello @alex-koretzki,

You can register for events by using Public Events Service and then you can listen to following events(v11, there are much more events for upper versions).

![image](https://user-images.githubusercontent.com/36479139/158078459-9a43d0b6-7e03-4a2e-83f9-f14ce8deb72f.png)

**Comment by FabianGosebrink** [comment]
You can find all supported events here: https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/public-events/event-types.ts
