### ISSUE TITLE
[Bug]: Query params are stripped by canLoad guards when user isn't authenticated

### ISSUE THREAD

**Issue by timdeschryver** [damienbod/angular-auth-oidc-client#1409]
**What Version of the library are you using?**

v11, but v12 and v13 have the same behavior.

**Describe the bug**

While using the `canLoad` guards the query parameter info is lost when there's no auth state in the storage.
This is because the persisted url only uses the route's segments.
When the authentication state is already persisted, this doesn't happen because the URL doesn't need to be stored.

For example, when a user navigates to `/search?query=hello`, the url `/search` is persisted to storage without the query parameter info `?query=hello`.

**To Reproduce**

1. Guard a route with the `AutoLoginAllRoutesGuard` or `AutoLoginPartialRoutesGuard` guard
2. Open a new browser (or tab), then navigate to that route and append a query parameter
3. The browser redirects and comes back to the page without the query parameter

**Expected behavior**

I expect that the query parameter doesn't get lost in the process.

**Screenshots**

/

**Desktop (please complete the following information):**

- OS: [e.g. iOS] all
- Browser [e.g. chrome, safari] all
- Version [e.g. 22] /

**Smartphone (please complete the following information):**

/

**Additional context**

This bug was partially resolved with #1051, but the wrong redirect URL is stored.
I think a solution would be to use [`router.getCurrentNavigation().toString()`](https://angular.io/api/router/Router#getCurrentNavigation) to get the complete URL (with query parameters), instead of using the segments from the `canLoad` method. This could also be used for the `canActivate` guards to keep both methods consistent.

First, I thought that using `location.path()` could also work, but this returns the current URL, not the URL that's being navigated to.

I found the `getCurrentNavigation` by looking into some Angular issues with a similar problem https://github.com/angular/angular/issues/17359 and https://github.com/angular/angular/issues/30633.

**Comment by timdeschryver** [comment]
Oh, and if want I can also submit a PR for this issue.

**Comment by FabianGosebrink** [comment]
Thanks for the issue. You can submit a PR if you want, we would be happy to review. Thanks! This could make it to V14 then. Thanks!

**Comment by vinishgeorge** [comment]
Is there a workaround ? to fix this issue any quick fix ?  i have a scenario that is blocking our users the first-time they use the url to set their passwords  because of the above issue .

**Comment by timdeschryver** [comment]
@vinishgeorge maybe not what you want to hear, but you could write your own guard for now.
Or, what we did was to change the route to include the query param as a route param for now.

**Comment by FabianGosebrink** [comment]
I just tried to reproduce the issue with our samples and started the `npm run start-sample-code-flow-auto-login` example and could not reproduce the issue
![queryparams](https://user-images.githubusercontent.com/11268349/160069285-16d324b2-9319-4a12-bad9-feb91247f2af.gif)
.

Is there anything I forgot?

**Comment by timdeschryver** [comment]
@FabianGosebrink can you try with a customers route? 
The `canActivate` guards do work because they use `state.url`, which includes query params.
It are the `canLoad` guards that have this problem, because they're using the route segments.

**Comment by timdeschryver** [comment]
@FabianGosebrink I could do this myself...
![false](https://user-images.githubusercontent.com/28659384/160122268-bbb8580c-0854-4a68-925f-bc4ae1b2d65b.gif)

**Comment by timdeschryver** [comment]
Using `canActivate` instead of `canLoad` could be a fix for @vinishgeorge

**Comment by FabianGosebrink** [comment]
Haha, was already looking into it. Okay, then I will try to implement the fix you suggested, but concentrate on the `canLoad`. Thanks!

**Comment by timdeschryver** [comment]
@FabianGosebrink I was also looking into it today 😅
I came up with #1414 let me know what you think, or feel free to close it.

**Comment by FabianGosebrink** [comment]
That looks absolutely brilliant. Thanks. LGTM!
