### ISSUE TITLE
[Question]: Cypress Test with a mocked Backend

### ISSUE THREAD

**Issue by git9999999** [damienbod/angular-auth-oidc-client#1412]
**What Version of the library are you using?**
13.1.0

**Question**
How can I create a Cypress Test with angular-auth-oidc-client in place. I have seen: https://github.com/damienbod/angular-auth-oidc-client/issues/1255 that there is no way to convince angular-auth-oidc-client that i am logged in. 
As i run against a mock backend. I am looking for a fake auth server or other solutions. Do you have any experience with that?

As Cypress Tests get more and more popular, a section in the Documentation with recommendation would be nice.

**Comment by damienbod** [comment]
@git9999999 Cypress  does not seem to support redirect and so to use this you need to create a backdoor or security hole to test which must not get deployed to and prod systems. 

Greetings Damien

**Comment by git9999999** [comment]
Thanks for your answer. :-)
