### ISSUE TITLE
After add second client with similar config to first, silent renew doesn't work

### ISSUE THREAD

**Issue by gundogduhasan** [damienbod/angular-auth-oidc-client#1413]
Hello,
So far i am using angular-auth-oidc-client just for one angular client. This way silent renew was working fine. But, i added a new angular client with very similar config to first and then silent renew doesn't work.In every 5 min return an error in console login_required and page return blank. When i refresh the page, page work fine and another 5 min later same error occurring all over again. By the way this happens in IIS, in my local everything working fine

Here is my auth config;
Only difference with first client just url and clientId.
config: {
        authority: environment.api.auth,
        redirectUrl: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        clientId: '<CLIENTNAME>',
        scope: 'openid profile role <CLIENTNAME>',
        responseType: 'id_token token',
        secureRoutes: [
          'http://localhost:4200',
          'http://url_in_iis'],
        silentRenew: false,
        silentRenewUrl: `${window.location.origin}/silent-renew.html`,
        //useRefreshToken: true, 
        logLevel: LogLevel.Debug,
        maxIdTokenIatOffsetAllowedInSeconds: 500
      },

And here is my debug logs;
```
[13:51:50 Information] IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator
Showing login: User is not authenticated

[13:51:50 Information] IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator
Changing response to LoginRequired: prompt=none was requested

[13:51:50 Information] IdentityServer4.Endpoints.AuthorizeEndpoint
{"ClientId": "<CLIENTNAME>Web", "ClientName": "<CLIENTNAME> Web", "RedirectUri": "<CLIENTURL>/silent-renew.html", "AllowedRedirectUris": ["<CLIENTURL>", "<CLIENTURL>/silent-renew.html"], "SubjectId": "anonymous", "ResponseType": "id_token token", "ResponseMode": "fragment", "GrantType": "implicit", "RequestedScopes": "openid profile role <CLIENTNAME>Api", "State": "aae306967bc6c28d27e135a71663a512c81PoV3gM", "UiLocales": null, "Nonce": "6122bf6a61488ea84d57352c586e862739qcH1CBF", "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "none", "MaxAge": null, "LoginHint": null, "SessionId": "", "Raw": {"client_id": "<CLIENTNAME>Web", "redirect_uri": "<CLIENTURL>/silent-renew.html", "response_type": "id_token token", "scope": "openid profile role <CLIENTNAME>Api", "nonce": "6122bf6a61488ea84d57352c586e862739qcH1CBF", "state": "aae306967bc6c28d27e135a71663a512c81PoV3gM", "prompt": "none"}, "$type": "AuthorizeRequestValidationLog"}

[13:51:50 Information] IdentityServer4.Events.DefaultEventService
{"ClientId": "<CLIENTNAME>Web", "ClientName": "<CLIENTNAME> Web", "RedirectUri": "<CLIENTURL>/silent-renew.html", "Endpoint": "Authorize", "SubjectId": null, "Scopes": "openid profile role <CLIENTNAME>Api", "GrantType": "implicit", "Error": "login_required", "ErrorDescription": null, "Category": "Token", "Name": "Token Issued Failure", "EventType": "Failure", "Id": 2001, "Message": null, "ActivityId": "8000018a-0002-f700-b63f-84710c7967bb", "TimeStamp": "2022-03-24T10:51:50.0000000Z", "ProcessId": 12628, "LocalIpAddress": "<ip_adres>", "RemoteIpAddress": "<ip_adres>", "$type": "TokenIssuedFailureEvent"}

```

**Comment by gundogduhasan** [comment]
Maybe this can give an idea about error. I simulated hosting environment in my pc. Two client working fine. But in the server second client doesn't work. I have same iis configuration. I will investigate two iis configurations again. If i found something i will let you know.

**Comment by gundogduhasan** [comment]
I can't find any difference between configs

**Comment by gundogduhasan** [comment]
I discovered something in IDS logs. When my first client start silent renew process sbujectid set with user id. But when my second client start silent renew process subjectid is null. Is error related with this?

**Comment by FabianGosebrink** [comment]
Is this issue still relevant? Did you upgrade to the latest version?

**Comment by gundogduhasan** [comment]
Actually I don't have a solid answer. I think issue is related IDS. I am currently upgrading IDS with BFF. And with BFF I think I don't need this lib, like says in this [issue](https://github.com/damienbod/angular-auth-oidc-client/issues/1568)

**Comment by gundogduhasan** [comment]
Actually I don't have a solid answer. I think issue is related IDS. I am currently upgrading IDS with BFF. And with BFF I think I don't need this lib, like says in this https://github.com/damienbod/angular-auth-oidc-client/issues/1568

Thank you soo much your concerns. And I am so sorry to keep this issue open.
