### ISSUE TITLE
[Refactoring]: Create an abstract logger service

### ISSUE THREAD

**Issue by FabianGosebrink** [damienbod/angular-auth-oidc-client#1416]
As discussed [here](https://github.com/damienbod/angular-auth-oidc-client/issues/1340#issuecomment-1082091028) overwriting the logger is a pretty common use case, and therefore it would be nice to provide the possibility for the users to overwrite the loggerservice with their custom implementation.

**Comment by FabianGosebrink** [comment]
I am  just thinking about a way how it can be set easily from the outside. Via the already existing config?

**Comment by timdeschryver** [comment]
I think that this won't be easy because it's probably going to be a service.
Maybe an injection token that could be provided could help here? Together with an `Logger` interface to implement the users' service. 
Something similar to `ErrorHandler`.

**Comment by FabianGosebrink** [comment]
I will give that a look and a try. Thanks!

**Comment by FabianGosebrink** [comment]
What would you like more?

```
@NgModule({
  imports: [
    AuthModule.forRoot({
      config: {
        ...,
        providers: [
               { provide: StorageService, useClass: MyStorageService }, 
               { provide: LoggerService, useClass: MyLoggerService }
         ]
      },
    }),
  ],
  exports: [AuthModule],
})
export class AuthConfigModule {}
```

or

```
@NgModule({
  imports: [
    AuthModule.forRoot({
      config: {
        ...
      },
    }),
     providers: [
               { provide: StorageService, useClass: MyStorageService }, 
               { provide: LoggerService, useClass: MyLoggerService }
         ]
  ],
  exports: [AuthModule],
})
export class AuthConfigModule {}
```

**Comment by timdeschryver** [comment]
I vote for the second, but I don't have a strong opinion about it.
Reasoning: it's more the "Angular way"? e.g. interceptors, errorhandler, ...

**Comment by damienbod** [comment]
Implemented in v14
