### ISSUE TITLE
[Question]: Is there any value using this lib with a BFF

### ISSUE THREAD

**Issue by rsouthgate** [damienbod/angular-auth-oidc-client#1417]
I've been through the samples and I don't see one specifically for use with a Backend-for-frontend so that might answer the question. But I wanted to double check...

The BFF has a /auth/getUser endpoint a login and logout endpoint and then everything else is proxy apis. It seems like there is still value in using the library to get the user identity from the getUser endpoint and at least initiate the auth code flow (using the popup). Would it be able to handle that flow?

**Comment by damienbod** [comment]
Hi @rsouthgate Yes BFF requires a backend. The idea with this is that all security is implemented on the server and the Angular code is just a "view" from the hosted backend. With this all sensitive data can be removed from the browser
