### ISSUE TITLE
[Question]: User data is empty

### ISSUE THREAD

**Issue by stjepan1211** [damienbod/angular-auth-oidc-client#1419]
**What Version of the library are you using?**
11.2.4

**Question**

![image](https://user-images.githubusercontent.com/18415784/162012665-eb4220cf-9a69-4f48-a4cd-184e68555951.png)

User data is always null in user data subscription. User data is correctly loaded in local storage. 

Authorization code flow and refresh token works correctly. Configuration:
![image](https://user-images.githubusercontent.com/18415784/162013550-81c32d7e-d69d-477d-8712-a929ce67b983.png)

How can I get userData from userData$ subscription?

**Comment by Ewerton** [comment]
Hi @damienbod, sorry for the late response. I will provide you more background on this issue.

### The Server
I'am using the Duende Identity Server version 6.0.4 as my STS. The client App is registered in my Id Server as follows:
```
new Client
{
   ClientId = "MyClient",
   ClientName = "Some Description",
   RequireClientSecret = false,
   AllowedGrantTypes = GrantTypes.Code,

   Enable support for refresh tokens 
   AllowOfflineAccess = true,

    // where to redirect to after login
    RedirectUris = new List<string>
    {
        "https://localhost:44400/login-callback",
    },

    PostLogoutRedirectUris = new List<string>
    {
        "https://localhost:44400/logout-callback",
    },

    AllowedCorsOrigins = new List<string>
    {
        "https://localhost:44400",
    },

    AllowedScopes = new List<string>
    {
    IdentityServerConstants.StandardScopes.OpenId,
    IdentityServerConstants.StandardScopes.Profile,
    IdentityServerConstants.StandardScopes.Email,
    IdentityServerConstants.StandardScopes.OfflineAccess,
    "api"
  }
},
``` 

Most of my `HostingExtensions.cs` class in my STS is pretty standard, except for some restrictions about CSP (Content Security Policy), so I put the entire class in [this gist](https://gist.github.com/Ewerton/61310e4c4db02bd794d69cc86ca7de1f) to you take a look. The important part starts around the 106 line. Also, note that I DO NOT ENABLED CORS, it is only enabled for specific clients in `AllowedCorsOrigins`.
I also have an API that I'm securing but I don't think this is relevant for this issue (please, let me know if you want more info about my API).

### The Client
My client is an Angular 13 App hosted in an .Net Core Project and I implemented the solution [based in this example](https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-refresh-tokens) the only difference is that I wrapped all the functionalities I needed in a custom module called `AuthService`. So, my Angular components injects an `AuthService` and the `AuthService` injects the `OidcSecurityService`
Here is how my **angular-auth-oidc-client** config looks like:
```
import { NgModule } from '@angular/core';
import { AuthModule, LogLevel } from 'angular-auth-oidc-client';
import { isDevMode } from '@angular/core';

@NgModule({
    imports: [AuthModule.forRoot({
        config: {
            authority: 'https://localhost:5001', // Url do Servidor de Identidade
            redirectUrl: 'https://localhost:44400/login-callback',
            postLogoutRedirectUri: "https://localhost:44400/logout-callback",
            //postLoginRoute: 'https://localhost:44400/login-callback',
            //triggerAuthorizationResultEvent: false, // https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#triggerauthorizationresultevent
            clientId: 'MyClient',
            scope: 'openid profile email offline_access api',
            responseType: 'code',
            silentRenew: true,
            useRefreshToken: true,
            logLevel: GetLogLevel(), // LogLevel.Debug, 
            tokenRefreshInSeconds: 60,
            refreshTokenRetryInSeconds: 10,
            autoCleanStateAfterAuthentication: false, // Deixe false, usamos o state para guardar a URL que o usuário estava antes de fazer login
            //renewTimeBeforeTokenExpiresInSeconds: 30,

            //forbiddenRoute: '/forbidden', // Como trataremos rotas proibidas?
            //unauthorizedRoute: '/unauthorized',  // Como trataremos rotas proibidas?
        }
    })],
    exports: [AuthModule],
    declarations: [
    ],
})
export class AuthConfigModule { }

function GetLogLevel() {
    if (isDevMode()) {
        return LogLevel.Debug;
    }
    else {
        return LogLevel.Error;
    }
}

```

### What I developed?
I developed a component just to test the login, logout and access token management for my Angular App. the code of this component just forwards the calls to my `AuthService`. As code speaks, [here is a gist with the entire](https://gist.github.com/Ewerton/c997eb4855183696ae825696332a67d2) `AuthService` and following here are some explanations that could be useful.

**Login**: The login() function saves the current URL (line 108). This URL will be read by my login-callback component to redirect the user to the URL he was before the login process.

**estaAutenticado()**: just maps the return of the `oidcSecurityService.isAuthenticated$` to an `Observable<boolean>`


### The Problem:
I tried to get the `UserDataResult` exactly like the line 18 in [the sample ](https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/sample-code-flow-refresh-tokens/src/app/home/home.component.ts), I mean, I just called the `this.userData$ = this.oidcSecurityService.userData$;` at the `ngInit()` in my custom `AuthService` module.  You can check it at [the line 22](https://gist.github.com/Ewerton/c997eb4855183696ae825696332a67d2). but the `this.userData$` was null every time.
I thought that my Angular http interceptor was blocking some request so I commented it out but the `this.userData$` stills returning null.
I also can't see any request in the network tab or any log messages in the console tab every time the `this.userData$ = this.oidcSecurityService.userData$;` was executed.


### A workaround?
I realized that after I call the `refreshSession()` function at least once, the `this.userData$` starts to work and be populated with the correct usar data. So, as you can check at the line 31 of the `AuthService`, if the UserData is null I call the `refreshSession()` and it starts to work. Although, I am afraid of this "technique" can cause some undesirable effect.
Please ignore the `getUser()` function at line 45. It was an attempt to call the `/connect/userinfo` endpoint directly, a solution that worked but I am not happy with it.

**Comment by Ewerton** [comment]
> Hi @Ewerton Is the userInfo request sent? and what do you get back in the response? You can check this in the F12 network tab. Not all IDPs support the user info endpoint
> 
> Greetings Damien

Hi Damien. 

I'm keeping investigating this issue in my side and I realized that, if the `UserData` isn't received the `silentRenew` process won't work either. I believe it is obvious to you but I'm just mentioning this because I believe **it elevates this problem to a "more severe" status**. 

Answering your question: Yes, **the userInfo request is being sent and it fails!** here are the details of the failed request:
```
Request URL: https://localhost:5001/connect/userinfo
Referrer Policy: strict-origin-when-cross-origin
:authority: localhost:5001
:method: GET
:path: /connect/userinfo
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtp ... VRMgc1l4-u-b7pUWoncPw
origin: https://localhost:44400
referer: https://localhost:44400/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Microsoft Edge";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39
```

After my page loads I can manually call the `userInfo` endpoint and it works! I mean, what is failing is just the request made by the library.

For comparison, here are the request details I get in the network tab when I call the userInfo endpoint manually:
```
Request URL: https://localhost:5001/connect/userinfo
Request Method: GET
Status Code: 200 
Remote Address: [::1]:5001
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: https://localhost:44400
cache-control: no-store, no-cache, max-age=0
content-type: application/json; charset=UTF-8
date: Fri, 20 May 2022 19:44:49 GMT
pragma: no-cache
server: Kestrel
:authority: localhost:5001
:method: GET
:path: /connect/userinfo
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY0MTV ... XubWLQdY4WrK1ed0GsgIcC_6Q
origin: https://localhost:44400
referer: https://localhost:44400/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Microsoft Edge";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39
```

Do you have any ideas on how can I solve it?

**Comment by damienbod** [comment]
I'll see if I can find something, our samples work using Identity server 4 as well

**Comment by Ewerton** [comment]
> I'll see if I can find something, our samples work using Identity server 4 as well

I tried to [run the this sample](https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-refresh-tokens) pointing to [your](https://offeringsolutions-sts.azurewebsites.net/) IDS and to my IDS and can't make it work in none of them but, please, consider I'm not a Angular developer so I may have made a mistake when testing.

**Comment by Ewerton** [comment]
Hi @damienbod 

I just upgraded my angular-auth-oidc-client lib to 14.0.1 and tested it again. Seems the UserInfo problem was solved 👍🏻
Thank you!
