### ISSUE TITLE
[Bug]: Invalid redirect_uri when authorization_code grant_type

### ISSUE THREAD

**Issue by gyko-bg** [damienbod/angular-auth-oidc-client#1423]
**What Version of the library are you using?**
^12.0.3

**Describe the bug**
Duende IdentityServer-based service logs the following:
```
{
  "Timestamp": "xxx",
  "Level": "Error",
  "MessageTemplate": "Invalid redirect_uri{@values}, details: {@details}",
  "Properties": {
    "values": {
      "redirectUri": "https://brand-master-tool-test.apps.igaming-test.euc1.xxx.tech/",
      "expectedRedirectUri": "https://brand-master-tool-test.apps.igaming-test.euc1.xxx.tech/silent-renew.html"
    },
    "details": {
      "_typeTag": "TokenRequestValidationLog",
      "ClientId": "Tools.BMT.Frontend",
      "ClientName": "Brand Master Tool SPA",
      "GrantType": "authorization_code",
      "Scopes": null,
      "AuthorizationCode": "****",
      "RefreshToken": "********",
      "UserName": null,
      "AuthenticationContextReferenceClasses": null,
      "Tenant": null,
      "IdP": null,
      "Raw": {
        "grant_type": "authorization_code",
        "client_id": "Tools.BMT.Frontend",
        "code_verifier": "xxx",
        "code": "xxx",
        "redirect_uri": "https://brand-master-tool-test.apps.igaming-test.euc1.xxx.tech/"
      }
    },
    "SourceContext": "Duende.IdentityServer.Validation.TokenRequestValidator",
    "RequestId": "xxxx",
    "RequestPath": "/connect/token",
    "ConnectionId": "xxxx",
    "Application": "IdentityServer",
    "RequestMethod": "POST"
  }
}
```
Angular SPA OpenIdConfiguration:
```
        const config: OpenIdConfiguration = {
          authority: environment.stsServer,
          redirectUrl: `${window.location.origin}${environment.rootPath}`,
          postLogoutRedirectUri: `${window.location.origin}${environment.rootPath}`,
          silentRenewUrl: `${window.location.origin}${environment.rootPath}silent-renew.html`,
          clientId: 'Tools.BMT.Frontend',
          scope: 'openid profile email tool-BMT',
          responseType: 'code',
          silentRenew: true,
          logLevel: LogLevel.Warn,
          autoUserInfo: true,
          forbiddenRoute: '/unauthorized',
          unauthorizedRoute: '/unauthorized',
          secureRoutes: [`${environment.apiBaseUrl}/api/`]
        };
```
Client configuration:
```
            return new ClientConfiguration
            {
                ClientName = "Brand Master Tool SPA",
                ClientId = "Tools.BMT.Frontend",
                RequireClientSecret = false,
                AccessTokenType = AccessTokenType.Reference,
                AllowedGrantTypes = new[] { OidcConstants.GrantTypes.AuthorizationCode },
                RequirePkce = true,
                AllowedCorsOrigins = new[]
                {
                    "http://localhost:4200",
                    "https://brand-master-tool-test.apps.igaming-test.euc1.xxx.tech"
                },
                RedirectUris = new[]
                {
                    "http://localhost:4200/",
                    "http://localhost:4200/silent-renew.html",
                    "https://brand-master-tool-test.apps.igaming-test.euc1.xxx.tech/",
                    "https://brand-master-tool-test.apps.igaming-test.euc1.xxx.tech/silent-renew.html"
                },
                PostLogoutRedirectUris = new[]
                {
                    "http://localhost:4200/",
                    "https://brand-master-tool-test.apps.igaming-test.euc1.xxx.tech/"
                },
                AllowedScopes = new[]
                {
                    IdentityServerConstants.StandardScopes.Email,
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    "tool-BMT"
                }
            };
```
**To Reproduce**
We are not sure what are the steps that reproduce the issue, but we find such log entries many times a day.

**Expected behavior**
Either any redirect URI enlisted in `RedirectUris` of the client configuration is accepted and token request validation succeeds **_OR_** `angular-auth-oidc-client` makes sure that a token request corresponding to the authorize endpoint request contains the same redirect URI so token request validation succeeds.

**Desktop (please complete the following information):**

- OS: Windows 10
- user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

**Comment by gyko-bg** [comment]
We have observed that 

1. Protection keys were out of sync between our running IdentiyServer instances due to a misconfiguration in our `Microsoft.AspNetCore.DataProtection.Repositories.IXmlRepository`
2. Deserialization of persisted grant items were broken when switching between our old `IdentityServer4` and `Duende.IdentityServer` based versions due to the incompatibility of the schema of the `PersistedGrant.Data` field.

These have been fixed. Since the above log does not indicate failed deserialization of the persisted grant, we assume that the reported issue is not related to these.

**Comment by everflux** [comment]
I have observed the same problem when integrating with keycloak.
When exchanging the code for the token the redirect uri sent is just the root URL without path. The mismatch leads to a failure/rejection by keycloak. This makes this library only useable without a subpath as redirect URI.

**Comment by gyko-bg** [comment]
A very similar issue was reported at https://github.com/damienbod/angular-auth-oidc-client/issues/801.
As written there it indeed may be caused by some kind of 'concurrency' in the SPA or how our Angular routes are set up/guarded.

We cannot reproduce the issue deterministically.

The routes of our Angular application is specified as
```
export const APP_ROUTES: Routes = [
  { 
    path: '', 
    redirectTo: '/dashboard', 
    pathMatch: 'full' 
  },
  {
    path: 'dashboard',
    loadChildren: () => import('./dashboard/dashboard.module').then((m) => m.DashboardModule),
    canLoad: [AutoLoginAllRoutesGuard]
  },
  { path: 'unauthorized', component: UnauthorizedComponent },
  { path: 'unauthenticated', component: UnauthenticatedComponent },
```
Our application does not initiate `this.oidcSecurityService.authorize()`, but it relies only on `AutoLoginAllRoutesGuard`.

We have checked the samples available in this repository. It seems that none of them has the very same design/configuration as our app: they either use `AutoLoginAllRoutesGuard` together with `useRefreshToken` set to `true`, or they set `silentRenewUrl` and initiate authentication from a component. Our understanding is that using refresh tokens in the browser should be avoided.

**Comment by gyko-bg** [comment]
It seems that the issue was caused by the `silent-renew.html` **not** being listed among the `assets` in `angular.json`.

Sorry for the confusion!
