### ISSUE TITLE
[Bug]: CheckSession errors upgrading from v13.1 -> v14.0

### ISSUE THREAD

**Issue by michaelmarcuccio** [damienbod/angular-auth-oidc-client#1428]
@angular-auth-oidc-client@14.0.0
Angular v13.3.3

After upgrading from v13.1 to v14.0, while using config with:
```
{ 
  silentRenew: true,
  useRefreshToken: false,
  startCheckSession: true,
  ngswBypass: true,
  ...
}
```
I get the following error that keeps on going with increasing outstanding messages:
```
CheckSession - OidcSecurityCheckSession not receiving check session response messages.
                            Outstanding messages: '4'. Server unreachable?
```

For some reason the checksession stuff no longer works.

- OS: Windows 10
- Browser: Chrome
- Version: 100.0.4896.88

**Comment by andrew-landsverk-win** [comment]
I am seeing this exact same issue, in one app I attempted an upgrade, and another fresh app starting with 14.0. My STS is Keycloak if that helps at all.

**Comment by damienbod** [comment]
The checksession has the problem that the browser begin to block this. So in the medium term, this will stop working anyway. Short term, I will try to fix his in V14

Greetings Damien

**Comment by michaelmarcuccio** [comment]
Why does the browser block the v14 one but not the v13 one?

**Comment by damienbod** [comment]
@michaelmarcuccio V14 probably has a bug which needs to be fixed. The browser is a second problem which is coming probably.

**Comment by Guerric-P** [comment]
test
