### ISSUE TITLE
getUserinfo() function is not sending name claim

### ISSUE THREAD

**Issue by rcanpahali** [damienbod/angular-auth-oidc-client#143]
Hi,
I'm trying to get user info from Identity server (identity server 4), **this.oidcSecurityService.getUserData()** function is working well, Im succesfuly retrieving user claims. On the other hand when I use **this.oidcSecurityService.getUserinfo()** function, Identity server handles request and when I check identity context, user comes as authenticated however identity name is null which causes internal server error. I believe getUserinfo method sends multiple requests to IdentityServer and only one of these request has **User.Identity.Name = ""** (empty string)

I'm also having another issue with: **openIdImplicitFlowConfiguration.auto_userinfo = true;** option, I presume this option uses **this.oidcSecurityService.getUserinfo()** function to retrieve user claims which causes same error

Please help me to solve these problems, thanks.

**Comment by damienbod** [comment]
@rcanpahali This depends on how you setup the profile data. You can add this explixitly using the IProfileService interface when using IdentityServer4. You can check which claims are sent by opening the id_token, or the access_token is you check use this in an API.

Greetings Damien

**Comment by simonare** [comment]
I am writing on behalf of @rcanpahali 

The claims that is handled by the CustomClaimsProvider inherited by IProfile Service is attached below.
apparently "name" claim is missing.
![image](https://user-images.githubusercontent.com/8443438/34478830-c4230d9a-efab-11e7-8b75-35013d36ca5f.png)

The weird thing is when I call GetUserInfo() method, angular sends 3 requests to Identity Server. and these request are handled by the IProfileService implementation. First and third request includes name claim, however second request doesnt which causes context.Subject.Identity.Name to be null.

Here is my Custom Claims Provider Implementation

`public class CustomClaimsProvider : IProfileService
    {
        private readonly IOrganizationService _organizationServiceClient;
        protected readonly ILogger<CustomClaimsProvider> Logger;

        public CustomClaimsProvider(IOrganizationService organizationServiceClient, ILogger<CustomClaimsProvider> logger)
        {
            _organizationServiceClient = organizationServiceClient;
            Logger = logger;
        }

        public virtual async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            context.LogProfileRequest(Logger);
            var subject = context.Subject;
            if (subject == null) throw new ArgumentNullException(nameof(context.Subject));
            if (subject.Identity.Name.IsNullOrEmpty()) throw new ArgumentNullException(nameof(context.Subject.Identity.Name));

            var claims = await GetClaimsFromUser(subject);

            context.AddRequestedClaims(claims);
            context.LogIssuedClaims(Logger);
        }


        public virtual async Task IsActiveAsync(IsActiveContext context)
        { 
            context.IsActive = false;
            Logger.LogDebug("IsActiveContext:Identity.Name={0}", context.Subject.Identity.Name);

            var subject = context.Subject;
            if (subject == null) throw new ArgumentNullException(nameof(context.Subject));
            if (subject.Identity.Name.IsNullOrEmpty()) throw new ArgumentNullException(nameof(context.Subject.Identity.Name));


            var domainUser = subject.Identity.Name;
            var user = domainUser.Split('\\', StringSplitOptions.RemoveEmptyEntries)[domainUser.Split('\\', StringSplitOptions.RemoveEmptyEntries).Length - 1];

            if (!string.IsNullOrWhiteSpace(user))
            {
                var staffDto = await _organizationServiceClient.GetStaffByUsernameAsync(user);
                context.IsActive = staffDto != null;
            }

            //return Task.CompletedTask;
        }

        private async Task<IEnumerable<Claim>> GetClaimsFromUser(ClaimsPrincipal claimsPrincipal)
        {
            IIdentity identity = claimsPrincipal.Identity;

            var claims = new List<Claim>
            {
                new Claim(JwtClaimTypes.Subject, identity.Name), //identity.GetSubjectId()),
                //new Claim(JwtClaimTypes.PreferredUserName, identity.Name),
                new Claim(JwtClaimTypes.Name, claimsPrincipal.Identity.Name)
            };


            var staffDto = await _organizationServiceClient.GetStaffByUsernameAsync(identity.Name.Split(new[] { "\\" }, StringSplitOptions.RemoveEmptyEntries)[1]);

            if (staffDto != null)
            {
                claims.AddRange(new []
                {
                    new Claim("branch-code", staffDto.Branch?.BranchCode),
                    new Claim("branch-name", staffDto.Branch?.Name),
                    new Claim("staffNo", staffDto.StaffNo),
                    new Claim("isCEO", staffDto.IsCEO ? "true" : "false"),
                    new Claim("department", staffDto.Department?.Name),
                    new Claim(JwtClaimTypes.Email, staffDto.Email),
                    new Claim(JwtClaimTypes.BirthDate, staffDto.DateOfBirth.ToString("d"))
                });

                if (staffDto.StaffTitle != null) claims.Add(new Claim("title", staffDto.StaffTitle.Name));
                if (staffDto.Positions != null && staffDto.Positions.Length > 0)
                    claims.AddRange(staffDto.Positions.Where(x => x.Enabled).Select(x => new Claim("position", x.Name)));
                if (staffDto.Manager != null) claims.Add(new Claim("manager-sma", staffDto.Manager?.UserName));
                if (staffDto.Director != null) claims.Add(new Claim("director-sma", staffDto.Director?.UserName));
            }

            if (claimsPrincipal is WindowsPrincipal wp)
            {
                // add the groups as claims -- be careful if the number of groups is too large
                if (AccountOptions.IncludeWindowsGroups)
                {
                    var wi = wp.Identity as WindowsIdentity;
                    var groups = wi.Groups.Translate(typeof(NTAccount));
                    var roles = groups.Select(x => new Claim(JwtClaimTypes.Role, x.Value));
                    claims.AddRange(roles);
                }
            }

           //userclaims buraya eklenecek

            return claims;
        }
    }`

**Comment by damienbod** [comment]
@simonare @rcanpahali 
Have you added this to the IdentityServer4 Config?

                AllowedGrantTypes = GrantTypes.Implicit,
                AllowAccessTokensViaBrowser = true,
                AllowOfflineAccess = true,
                AlwaysIncludeUserClaimsInIdToken = true,

Also is tis problem with the access_token or the id_token? I assume you have an API and use the id_token token flow. Correct?

**Comment by simonare** [comment]
Here is our IdentityServer Client Configuration

```
AccessTokenType = GrantTypes.Implicit
AllowAccessTokensViaBrowser = true
AllowOfflineAccess = true
AllowPlainTextPkce = false
AllowRememberConsent = true
AlwaysIncludeUserClaimsInIdToken = true
AlwaysSendClientclaims = true
BackChannelLogoutUri = true
EnableLocalLogin = false
FrontChannelLogoutSessionRequired = true
IncludeJwtId = false
RefreshTokenExpiration = true
RefreshTokenUsage = true
RequireClientSecret = true
RequireConsent = true
RequirePcke = false
UpdateAccessTokenClaimsOnRefresh = true
```

I Have Api but right now I just disabled Api Authentication because of this problem. 

I am simply trying to call the method below after successfully get authenticated

```
this.oidcSecurityService.getUserinfo().subscribe((userInfo: any) => {
            console.log(userInfo);
            console.log(userInfo['email']);
        });```

which in turns sends more then one request to IdentityServer CustomProfileService, and one of those request has "context.Subject.Identity.Name" is null.

it is kind of awkward.

What can I send you more?

thank you very much.

**Comment by simonare** [comment]
Dear @damienbod 

according to my resarch, there is high probability that  the problem is a missconfiguration issue on the id_token side (which I believe you are also suspicious about it). I will post update. 

thank you

**Comment by Jonesie** [comment]
When I do this:

    this.userData = this.userInfoSubscription = this.oidcSecurityService.getUserinfo().subscribe(
      (userData: any) => {
        this.userData = userData;
      });

all I get for userData is 'true'.  Is that right?  How am I supposed to get the user info?  I can see the response from my identity server has the claims.

**Comment by damienbod** [comment]
@Jonesie You should use the getUserData() . The getUserinfo() init and requests the user data from the server. I will rename the method. This is confusing. Sorry.

Greetings Damien

**Comment by Jonesie** [comment]
Thanks, I tried this... same result :/

**Comment by shivajikokate-shiro** [comment]
I am getting issue.

` var user = await _userManager.GetUserAsync(context.Subject);`

in this context.Subject "sub" value something "sub: 'user logged in'".

Please help me as I wasted my 3 days.
