### ISSUE TITLE
Persisted Access Token Expired

### ISSUE THREAD

**Issue by christian-servin** [damienbod/angular-auth-oidc-client#1433]
I am working on an issue with our Angular SPA authentication. The issue is the silent renew periodic check finishes, but the silent renew does not start. The access token eventually expires shown in the screenshot as a negative time. At this point, the application needs a new access token and the app is redirected to the sts then back to the auth-callback. The desire functionality is to fetch a new access token only after an x amount of hours.

Not sure what is causing this. Any direction on how to solve this is greatly appreciated.

Successful silent renew debug log:
![image](https://user-images.githubusercontent.com/66705550/165862300-6816b5da-6e1e-49c2-b833-f045166f37df.png)

Debug log when issue happens:
![image](https://user-images.githubusercontent.com/66705550/165862423-c9b53245-c72b-4f75-925f-b0c5982b25f7.png)

STS: IdentityServer4

Client Configuration
```
{
    ClientId = "dm-webapp",
    ClientName = "DataMaster Web",
    AccessTokenLifetime = 120,//For quick debugging, 3600 is in production
    RequireClientSecret = false,
    AllowedGrantTypes = GrantTypes.Code,
    RequirePkce = true,
    AllowAccessTokensViaBrowser = true,
    RedirectUris = new List<string>
    {
        "http://localhost:4200/auth-callback",
    },
    PostLogoutRedirectUris = new List<string>
    {
        "http://localhost:4200"
    },
    AllowedCorsOrigins = new List<string>
    {
        "http://localhost:4200",
    },
    AllowedScopes = new List<string>
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        "api",
        "offline_access" // for refresh token 
    },

    RequireConsent = false,
    AllowOfflineAccess = true
}
```

`angular-auth-oidc-client": "13.1.0"`

```
config: {
        authority: environment.authUrl,
        redirectUrl: `postLogoutRedirectUri`,
        postLogoutRedirectUri: `postLogoutRedirectUri`,
        clientId: "clientId",
        scope: "openid profile dm.api offline_access", 
        responseType: "code",
        silentRenew: true,
        useRefreshToken: true,
        logLevel: LogLevel.Debug,
        enableIdTokenExpiredValidationInRenew : false,
}
```

**Comment by FabianGosebrink** [comment]
Is this issue still relevant? Did you upgrade to the latest version?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
