### ISSUE TITLE
[Bug]: AutoLoginAllRoutesGuard infinite loop when error + state query param present

### ISSUE THREAD

**Issue by mrjeroendg** [damienbod/angular-auth-oidc-client#1434]
**What Version of the library are you using?**
13.1.0

**Describe the bug**
When using the AutoLoginAllRoutesGuard on a protected route all works well when a user authenticates successfully. But, when the user is redirected to the application with `url + ?error=access_denied&state=correct_state` the application freezes. Looking into the code and reproducing what's there it looks like an infinite loop is happening.

Tried creating my own guard that uses `checkAuth()` and chains it to `isAuthenticated` and this results in the same kind of behavior. All works well when doing the happy flow, an infinite loop starts when an error and state query parameter are present:
```
public canActivate(): Observable<boolean | UrlTree> {
    return this.oidcSecurityService.checkAuth().pipe(
      switchMap(() => {
        return this.oidcSecurityService.isAuthenticated$
      }),
      take(1),
      map(({ isAuthenticated }) => {
        return isAuthenticated ? true : this.router.parseUrl('/auth/login');
      })
    );
  }
```

**Expected behavior**
No infinite loop should be happening when AutoLoginAllRoutesGuard is used. And if an error is present we should be able to handle it accordingly.

Same goes for the guard above, it should no go into an infinite loop. If it isn't anymore we could potentially catch the error from the `errorMessage` property that is inside the `isAuthenticated` stream.

Thanks in advance!

**Comment by FabianGosebrink** [comment]
Is this Bug still relevant?

**Comment by mrjeroendg** [comment]
Not sure. We switched to another OIDC library after encountering this issue... So for me this issue can be closed as apparently no other people encountered the same problem.

**Comment by RutsuKun** [comment]
Issue still exists
![image](https://github.com/damienbod/angular-auth-oidc-client/assets/14915249/da038438-2e73-4857-a29e-291b75adb7ce)
