### ISSUE TITLE
Refresh token is not populating session storage

### ISSUE THREAD

**Issue by spikehockey75** [damienbod/angular-auth-oidc-client#1435]
Hello, 

Our app is using silent renew / refresh tokens. At first sign on everything works correctly. It gets all the tokens from the sts server and populates the session storage with all this information. Then on refresh the call happens and gets the response but session storage is not updated. This is causing issues because we cant grab the tokens from session storage to pass to our apis. Is there something that has changed?

Angular version : 11.2.14
Angular-auth-oidc-client: 11.6.11

auth-config-module.ts

`import { NgModule } from '@angular/core';
import { AuthModule, LogLevel } from 'angular-auth-oidc-client';

@NgModule({
  imports: [
    AuthModule.forRoot({
      config: {
        stsServer: environment.stsServer,
        redirectUrl: '${window.location.origin}/resolve',
        clientId: 'app_ui',
        postLogoutRedirectUri:'${window.location.origin}/unauthorized',
        scope: 'openid StandardWorkforceAndCDGroups',
        responseType: 'code',
        autoUserInfo: true,
        silentRenew: true,
        useRefreshToken: true,
        logLevel: LogLevel.Debug,
        issValidationOff: true,
      },
    }),
  ],
  exports: [AuthModule],
})
export class AuthConfigModule {}`

**Comment by FabianGosebrink** [comment]
Is this issue still relevant?
