### ISSUE TITLE
[Question]: Client Secret in Angular App in NON PUBLIC domain 

### ISSUE THREAD

**Issue by vardan500** [damienbod/angular-auth-oidc-client#1438]
**What Version of the library are you using?**
12.0.3

**Question**
I am on non public domain and our Ping Federate setup requires base 64 encoded ClientId & Client Secret to be passed as a part of authorization header when exchanging code with a token.  For this situation, any idea how can this be implemented while still using the library?

**Comment by damienbod** [comment]
You don't use secrets in an public application.

**Comment by FabianGosebrink** [comment]
Could you please give the question an appropriate title? Thanks.

**Comment by vardan500** [comment]
> You don't use secrets in an public application.

Hi @damienbod  - I fully understand that. But my employer is in PRIVATE domain and does not support PKCE unfortunately. Is there any library you are aware of that does client credentials.

**Comment by vardan500** [comment]
> Could you, @[vardan500](https://github.com/vardan500), please give the question an appropriate title? Thanks.

Hi @FabianGosebrink - updated the question title.
