### ISSUE TITLE
[Question]:  Issues using Client in another library

### ISSUE THREAD

**Issue by ttoups** [damienbod/angular-auth-oidc-client#1442]
**What Version of the library are you using?**
14

**Question**
We have multiple Angular apps (all version 13) that have things in common, so we created an angular npm Library that allows us to put those sharable pieces into one location, rather than duplicating the same code..

We are upgrading our library from using `oidc-client` to this `angular-auth-oidc-client` package.   Previously, our library contained a custom AuthService that encapsulates the OidcClient and exposed functions following a façade pattern.

Now we are attempting to do the same thing by encapsulating your client in our own.  But when we go to import our library into our apps, we can a ton of errors when we build that are like the following:
```
Package path ./lib/config/auth-well-known/auth-well-known.service is not exported from package ~\application\angular\node_modules\angular-auth-oidc-client (see exports field in ~\application\angular\node_modules\angular-auth-oidc-client\package.json
```

Any clue as to what we're doing wrong, or was your client not built with the expectation that it would be used in another angular library? 

TIA!!

Tom

**Comment by JT2011** [comment]
Hi Fabian, I work with Tom on the same project. We have the AuthModule configured inside our own custom AuthConfigModule,
like so:

```
export const httpLoaderFactory = (httpClient: HttpClient) => {
  const config$ = httpClient.get<AppConfig>('./assets/config.json').pipe(
    map((appConfig: AppConfig) => {
      return {
        authority: appConfig.oidcClient.authority,
        clientId: appConfig.oidcClient.clientId,
        clientSecret: appConfig.oidcClient.clientSecret,
        redirectUri: appConfig.oidcClient.redirectUri,
        postLogoutRedirectUri: appConfig.oidcClient.postLogoutRedirectUri,
        responseType: appConfig.oidcClient.responseType,
        scope: appConfig.oidcClient.scope,
        filterProtocolClaims: appConfig.oidcClient.filterProtocolClaims,
        loadUserInfo: appConfig.oidcClient.loadUserInfo,
        automaticSilentRenew: appConfig.oidcClient.automaticSilentRenew,
        includeIdTokenInSilentRenew: appConfig.oidcClient.includeIdTokenInSilentRenew,
        silentRedirectUri: appConfig.oidcClient.silentRedirectUri
      };
    })
  );

  return new StsConfigHttpLoader(config$);
};

@NgModule({
  imports: [
    AuthModule.forRoot({
      loader: {
        provide: StsConfigLoader,
        useFactory: httpLoaderFactory,
        deps: [HttpClient],
      },
    }),
  ],
  exports: [AuthModule],
})
export class AuthConfigModule { }
```

and then imported into the library's module:

```
  imports: [
     ...
    AuthConfigModule
  ]
})
export class InfrastructureModule {
```

Finally, this InfrastructureModule is loaded into the consuming application's AppModule in imports. The goal was that we would not have to duplicate most of this code because many of our angular client applications behave similarly when it comes to authentication using IdentityServer.

**Comment by FabianGosebrink** [comment]
Thanks for using the lib :) Where do you access the `/auth-well-known.service`, because it is mentioned in the error you provided. Thanks!
