### ISSUE TITLE
[Feature Request]: start periodic checks without calling checkAuth

### ISSUE THREAD

**Issue by charsleysa** [damienbod/angular-auth-oidc-client#1448]
**Is your feature request related to a problem? Please describe.**
Would like the periodic checks to start without requiring a call to `checkAuth()` which has side effects (e.g. if your url contains `state` in your query params then good luck working around it).

**Describe the solution you'd like**
Maybe a config option or an API to start the periodic checks (e.g. access token renewal using rotating refresh token) without needing to call `checkAuth()` as other APIs like `isAuthenticated()` provide the desired functionality for checking authentication.

**Describe alternatives you've considered**
None available. `checkAuth()` must be called.

**Additional context**
It might be easier to expose all the services as public API with the understanding that these services could change drastically between major versions.

**Comment by FabianGosebrink** [comment]
Well, the `checkAuth()` method is what is being used to read the parameters from the url and set everything up. I do not see an option to not read those parameters when returning to your app and start the checks then. Do you have a pseudocode sample where we can see your idea?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
