### ISSUE TITLE
[Question]: No authnResult / authzData was written to the SessionStorage

### ISSUE THREAD

**Issue by markus-ki** [damienbod/angular-auth-oidc-client#1450]
**What Version of the library are you using?**
13.1.0

**Question**
We have a public client (Ionic v6 with Angular v13) with a PKCE Flow. 

We have, especially in **corporate** networks, the problem that no token result is written. The request arrives but is not written to the SessionStorage.

The authNonce and codeVerifier are written and after the redirect to the Authentication Server and successful login the Auth Result is not written to the SessionStorage and the user cannot login.
![image](https://user-images.githubusercontent.com/59443427/171010290-47c22446-6219-49ac-b8b1-87a08eddcea1.png)

I can't repdroduce the behavior, because this phenomenon, as far as I have noticed, only occurs in corporate networks. For most users the lib with the works fine. 

Does anyone have any idea what could be causing this?

**Comment by donnyst** [comment]
Any updates on this? 

I'm having the same issue.
Our selenium tests are failing, not locally, but only on Jenkins. After adding a ton of logging we noticed getAccessToken() is returning null in the http interceptor, even though before this the AuthResult is logged and this does in fact contain the access_token.

**Comment by markus-ki** [comment]
Unfortunately not, I could not reproduce the error.
