### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by patolax** [damienbod/angular-auth-oidc-client#1453]
Just downloaded Openiddict sample below and added a couple of custom clams to the token
https://github.com/damienbod/AspNetCoreOpeniddict

However, the `getUserData()`  api is not listing any of these claims visible on the identity token. See below.
![image](https://user-images.githubusercontent.com/29444156/172308446-79f332b5-2ada-4895-8b1e-98bed59b9b52.png)

Is this the desired behaviour, if not how do we get custom claims from `getUserData()` api?

**Comment by damienbod** [comment]
This can be configured on the OpenIddict server client configuration

Greetings Damien
