### ISSUE TITLE
remember me

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#1456]
**What Version of the library are you using?**
I am using version 11.6.10

**Question**
My identity server 4 implements remember me when logging in. I need to close the webpage within a certain period of time and reopen it without entering the user name and password to log in, the user is already logged in. The problem now is that when I close the webpage and reopen it, I need to log in under the click to log in automatically. How can I reopen the webpage and no longer log in through the click to log in?

Hope you can give some inspiration, thank you

**Comment by fengzhihenxs** [comment]
I want to change the storage mechanism to localStorage, but I don't choose to remember that I close the browser and open it again, the user is still logged in. What I want is to choose remember me after a certain period of time without needing to enter the user name and password, close the browser and reopen the browser again after the user is logged in.

**Comment by 8thblock** [comment]
It seems there is none. Try injecting a storage provider at the root may be? I am in the same boat and looking for alternatives.
