### ISSUE TITLE
How can I disable .well-known/openid-configuration?

### ISSUE THREAD

**Issue by silverwind85** [damienbod/angular-auth-oidc-client#1457]
**What Version of the library are you using?**
... latest

**Question**
I want use this libary to auth https://allegro.pl/ but i have error 
![image](https://user-images.githubusercontent.com/6718212/173571490-a9ab3d12-5950-4d60-9401-af63185621d3.png)
It is posible disable .well-known/openid-configuration in this library

**Comment by FabianGosebrink** [comment]
So you want to disable to load the well known endpoint?
