### ISSUE TITLE
[Feature Request]: Support for Angular 14

### ISSUE THREAD

**Issue by lerich** [damienbod/angular-auth-oidc-client#1459]
Could you please add support for Angular 14?

It's the error when trying to update angular:
Found: @angular/common@14.0.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"14.0.2" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from angular-auth-oidc-client@14.0.2

**Comment by FabianGosebrink** [comment]
We will update the lib as one of our next actions. Thanks!

**Comment by JoachimVeulemans** [comment]
When can we expect a new release?
