### ISSUE TITLE
[Bug]: getUserData is not working

### ISSUE THREAD

**Issue by Githamza** [damienbod/angular-auth-oidc-client#1460]
**What Version of the library are you using?**
14.0.2

**Describe the bug**
I would like to get user data after login

```
            this.eventService.registerForEvents()
            .pipe(
                filter(notification=>notification.type===EventTypes.UserDataChanged)
                ).subscribe(data=> {
                    console.log("new event",data)
                    const dataUser= this.oidcSecurityService.getUserData()
                    .pipe(
                        map(data=> {
                        console.log("user infos",data)
                    }
                    ),
                    catchError(err=> {
                        console.log(err)
                        return EMPTY
                    })
                    )
                    console.log(dataUser)
        })
``` 
Map is not getting result.

I tried also to subscribe directly
```
        const dataUser = this.oidcSecurityService.getUserData().subscribe(
            (data) => {
                console.log('user infos', data);
            },
            (error) => {
                console.log(error);
            }
        );
```

But suscription is not fired

**To Reproduce**
NC

**Expected behavior**
get user informations

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows
- Browser chrome, firefox

**Comment by FabianGosebrink** [comment]
You get the user data back from the login immediately, see https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api#checkauthurl-string-configid-string

**Comment by Githamza** [comment]
So is it not possible to get user data other then after login immediately ?

**Comment by FabianGosebrink** [comment]
Sure, it is possible with the [getUserData()](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api#getuserdataconfigid-string) method you use. In your first example, you do not subscribe to the method itself, in the second example you do, but do you call if AFTER the login has been set, and you called `checkAuth()`?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
