### ISSUE TITLE
[Question]: How can i set auth config after APP_INITIALIZER

### ISSUE THREAD

**Issue by shwetaWS** [damienbod/angular-auth-oidc-client#1463]
**What Version of the library are you using?**
13.1.0

**Question**
How can i set auth config after APP_INITIALIZER.
 want to set  
```
AuthModule.forRoot({
      config: {
        authority: '<your authority address here>',
        redirectUrl: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        clientId: '<your clientId>',
        scope: 'openid profile email offline_access',
        responseType: 'code',
        silentRenew: true,
        useRefreshToken: true,
        logLevel: LogLevel.Debug,
      },
    }),
```
after appp initialization

**Comment by agardiol** [comment]
You can use an async loader:

In app.module.ts
```

const authFactory = (currentWebAppService: CurrentWebAppService) => {
  const config = [SomeWhereInYourCode].configureAuth();
  return new StsConfigStaticLoader(config);
};

@NgModule({
 ...
  imports: [
    AuthModule.forRoot({
      loader: {
        provide: StsConfigLoader,
        useFactory: authFactory,
        deps: [CurrentWebAppService],
      },
    }),
...
}) export class AppModule { }
```

And some where in your code
```
  configureAuth(): OpenIdConfiguration {
    const config: OpenIdConfiguration = {
...
    };
    return config;
  }
```

**Comment by shwetaWS** [comment]
ok thanks what can i use for AuthClientConfig replacement in oidc

**Comment by agardiol** [comment]
Not sure to understand your question. I updated my above comment with your configuration example.

**Comment by shwetaWS** [comment]
@agardiol  in my case i want to replace my configuration at the time of app_initialization  and set the openIdconfiguration after environmenmt file updates. but not able to inject OpenIdConfiguration in the service to set 
 constructor(
   private appConfig: OpenIdConfiguration
  ) {
 
  }


  public init() {
      var url = window.location.href;
    return from(
        fetch('assets/app-config.json').then(function(response) {
          return response.json();
        })
      ).pipe(
        map((config) => {
        window.config = config;
        this.appConfig = config.
        return 
      })).toPromise(); 
  }


but here i m getting error as This constructor was not compatible with Dependency Injection.

**Comment by mac-bhaird** [comment]
We're doing something like this:

helper function (AppConfig matches the shape of our config file):

`
export function fetchConfigAndBootstrapModule(module: any): void {
  fetch('./assets/config.json').then(async res => {
    const configData = await res.json() as AppConfig;
    const config = { ...new AppConfig(), ...configData };
    platformBrowserDynamic([
      { provide: AppConfig, useValue: config }
    ]).bootstrapModule(module)
      .catch(err => console.error(err));
  });
}

`

main.ts (replaces original bootstrap code):

`fetchConfigAndBootstrapModule(AppModule);`

ConfigService.ts constructor:

`
  constructor(private config: AppConfig) { }
`
Essentially ensuring the information from config.json is always available, even for lazy loaded modules.

**Comment by FabianGosebrink** [comment]
Using the main.ts file is the recommended way to do it. Thanks!
