### ISSUE TITLE
[Feature Request]: Define an interface for userData in UserDataResult

### ISSUE THREAD

**Issue by yurakhomitsky** [damienbod/angular-auth-oidc-client#1466]
**Is your feature request related to a problem? Please describe.**

`userData` is typed as any, so it's impossible to know what the shape of the object is.

![image](https://user-images.githubusercontent.com/54478076/175305684-9e6ddc6e-f782-45d2-83bd-3790591785c2.png)

**Describe the solution you'd like**
Define a type definition for `userData`

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by FabianGosebrink** [comment]
AFAIK the userdata depends on the provider you use. It is impossible for us to provide an interface for this.

**Comment by yurakhomitsky** [comment]
@FabianGosebrink Do you know where I can see the user data interface from the Microsoft provider?
