### ISSUE TITLE
[Question]: Can isAuthenticated be true even though there is no id_token?

### ISSUE THREAD

**Issue by dbrils** [damienbod/angular-auth-oidc-client#1469]
**What Version of the library are you using?**
`14.0.0`

**Question**
`checkAuth()` and `isAuthenticated$` both return `false` when no `id_token` is present (after the code exchange has been done for an access token). An example response of the `POST /access_token` could be:

```json
{ 
access_token: "eyJ0...Z"
expires_in: 3599
nonce: "abc"
scope: "scope"
token_type: "Bearer" 
}
```

Is this intentional behaviour? And would it be possible to only check the `access_token`? From what I can tell this is intended behaviour that cannot be changed, by looking at the `isAuthenticated` method of the `AuthStateService`.

![image](https://user-images.githubusercontent.com/28647803/176460272-2dbf8cd1-9dfe-44bc-84df-208893f6a226.png)

**Comment by damienbod** [comment]
from version 14.2.0, it is now possible to only check the access token for expired
