### ISSUE TITLE
Support for multiple STS?

### ISSUE THREAD

**Issue by thecepe** [damienbod/angular-auth-oidc-client#147]
I'm want to select between different STS servers to authenticate against in my application before login. 

So I tried to provide an OpenIDImplicitFlowConfiguration for each STS and to call oidcSecurityService.setupModule(..) with the configuration of the selected STS. 

But this didn't work and the first STS is always used. It seems that the the well known endpoints are not updated after they are initialized once. The log says: 'AuthWellKnownEndpoints already defined' (see setupModule() in auth.well-known-endpoints.ts)

Is there any way to change the STS after one is initialized?

**Comment by damienbod** [comment]
At present not. At present this lib can only be used once per Angular app. The AuthWellKnownEndpoints  are only loaded once as a proformance help.

**Comment by damienbod** [comment]
You could load the AuthWellKnownEndpoints manually and then you can select the correct STS

https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#override_well_known_configuration_url

**Comment by thecepe** [comment]
Hi Damien ,
thanks for the hint in the right direction. I'll try that as soon as possible.
