### ISSUE TITLE
[Feature Request]: Relax Angular version compatibility

### ISSUE THREAD

**Issue by marklagendijk** [damienbod/angular-auth-oidc-client#1470]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when a library is forcing me to use a specific Angular version.
Currently this library forces you to use a specific major Angular version:
- If that version isn't the latest version you have to wait until the library is updated and released.
- If that version is the latest version, but you aren't using that yet, you have to figure out which version of the library you need, and can't use the documentation of the library, because it won't match.

**Describe the solution you'd like**
I would like if the library would only specify a _minimum_ version of Angular, where that minimum is actually based on what the library requires. If it turns out that there is an issue with the library in combination with a new version of Angular that comes out, you can always specify a maximum at that point (via a bugfix release).
It would be best if the minimum required version would at least be 1 or 2 major versions behind the latest Angular version.
This should be feasible because Angular doesn't have that many breaking changes with new major releases. So even if there is one that would affect the library, usually it can be worked around.

**Describe alternatives you've considered**
The alternative is to not do this, and keep things as it is. But this can be very annoying for users of the library.

**Comment by damienbod** [comment]
@marklagendijk Would love this as well, but we have no control over the Angular releases and have this problem with every major Angular release.

**Comment by FabianGosebrink** [comment]
Thanks for the issue and comment. What would you like to see? Something like here https://github.com/damienbod/angular-auth-oidc-client/pull/1472/files ?

**Comment by damienbod** [comment]
Will be released with version 14.1.0

**Comment by marklagendijk** [comment]
> Thanks for the issue and comment. What would you like to see? Something like here https://github.com/damienbod/angular-auth-oidc-client/pull/1472/files ?

That is indeed what I would like.
Now of course there is a risk that a new major version of Angular would be incompatible with the library, but for users of the library that isn't a huge deal. In such a case it could work as follows:

* A new major version of Angular would come out, which would be incompatible with the library.
* Some early adopters upgrade, notice the issue and report it.
* You could directly release a bugfix where you limit the max version of Angular, so other people who would try to update would see the issue from the NPM error.
* You fix the incompatibility, if the fix is backwards compatible you leave the min version as is, otherwise you increase it to the new major Angular version.

**Comment by FabianGosebrink** [comment]
Yepp, thanks! Will be in the next release. Thanks!
