### ISSUE TITLE
[Bug] `getUserData` - You provided an invalid object where a stream was expected.

### ISSUE THREAD

**Issue by benthieu** [damienbod/angular-auth-oidc-client#1478]
https://github.com/damienbod/angular-auth-oidc-client/blob/00dd0556f4de35d2a6aeb920624636dd0583e48e/projects/angular-auth-oidc-client/src/lib/oidc.security.service.ts#L121
`getUserData` should return an Observable. This `switchMap` should therefore be replaced with `map` because`getUserDataFromStore` won't return an Observable.

Currently this function won't work and will return `You provided an invalid object where a stream was expected.`.

**Comment by FabianGosebrink** [comment]
You are totally correct. Bugfix is on the way.

**Comment by benthieu** [comment]
Thank you for the fix.
May I ask if there is any benefit of using `getUserData` over `getPayloadFromIdToken` (other than that the `sub` is validated)?

**Comment by FabianGosebrink** [comment]
No, it should be the same expect sub validation iirc. `getUserData` is more user friendly. We are trying to make it as easy as possible.

**Comment by damienbod** [comment]
fixed in release 14.1.1

**Comment by benthieu** [comment]
Thanks a lot!

**Comment by FabianGosebrink** [comment]
Well thank YOU for pointing this out!
