### ISSUE TITLE
Is there a way to subscribe to the check session changed?

### ISSUE THREAD

**Issue by ricksecretin** [damienbod/angular-auth-oidc-client#148]
First of all thanks for the fantastic library!

In the documentation I found that oidcSecurityService.checkSessionChanged changes to true when the session changes.

Is there any way to to perform some actions when this happens?
In other words is there any way to subscribe to this boolean?

I tried with oidcSecurityCheckSession.onCheckSessionChanged.subscribe() but it does nothing when the boolean changes;

Thanks in advance!

**Comment by damienbod** [comment]
At present not, I could add an event for this is it helps. We were thinking of adding events for most things in the near future.

Greetings Damien

**Comment by ricksecretin** [comment]
That would be great.

Thanks!

Rick

**Comment by damienbod** [comment]
Release 3.0.12

**Comment by damienbod** [comment]
https://www.npmjs.com/package/angular-auth-oidc-client

**Comment by JohnGalt1717** [comment]
What's the event and how do you use it?
