### ISSUE TITLE
[Feature Request]: Add Custom parameters to authorization request for refreshing token using Iframe

### ISSUE THREAD

**Issue by bssahney93** [damienbod/angular-auth-oidc-client#1481]
**Is your feature request related to a problem? Please describe.**
I am not able to add custom parameters to the auth request only in the case when I am trying to refresh the tokens using Iframes

**Describe the solution you'd like**
Introduce one key/property in Open Id Configuration which will take the custom parameters for the auth request in case of refreshing tokens using Iframes 

**Describe alternatives you've considered**
I am yet to find a solution for this alternative.

**Additional context**

**Comment by FabianGosebrink** [comment]
I am not sure how far iframes are still supported by modern browsers... 🤔🤔🤔 @damienbod opinions?

**Comment by damienbod** [comment]
Yes you need to move away from iframes.
