### ISSUE TITLE
[Question]: How can I stop sendAuthorizeRequestUsingSilentRenew from multiple tabs?

### ISSUE THREAD

**Issue by abdunnahid** [damienbod/angular-auth-oidc-client#1486]
**What Version of the library are you using?**
13.1.0

**Question**
How can I stop sendAuthorizeRequestUsingSilentRenew from multiple tabs?

If I have multiple tabs open, they all calls **sendAuthorizeRequestUsingSilentRenew**. One of them passes and successfully gets the response from the  server. However the other tabs throws an error and stops the silent renew. After that the token is not renewed in any of the tabs.

Debug Logs: 
```
signIn - ValidateStateFromHashCallback failed state: {{State}} local_state:{{State}}
signIn - Error: Error: null
signIn - removed event listener from IFrame
```

**Comment by greengumby** [comment]
Did you get an answer to this?
