### ISSUE TITLE
Version 14 does not work with rxjs version 6, but in lib package.json it specifies peerDependencies: "rxjs": "^6.5.3 || ^7.4.0"

### ISSUE THREAD

**Issue by niqolay** [damienbod/angular-auth-oidc-client#1489]
Steps to reproduce:
1. Create angular project with dependency to rxjs version 6 (for example, "rxjs": "^6.6.7")
2. Add dependency to angular-auth-oidc-client@14.1.0
3. Try to build project

Result:
1. Compilation errors like `./node_modules/angular-auth-oidc-client/fesm2020/angular-auth-oidc-client.mjs:7066:75-86 - Error: export 'switchMap' (imported as 'switchMap$1') was not found in 'rxjs'`

Expected result:
Compilation is successful

Notes:
1. The reason is that in rxjs 7 they moved operator imports from 'rxjs/operators' to 'rxjs' (https://rxjs.dev/guide/importing) and they are imported this way in this lib in version 14.
2. Version 13 works with rxjs 6 correctly (all operator imports were from 'rxjs/operators')

Possible solutions:
1. Remove support of rxjs v6 (remove from peerDependencies in projects/angular-auth-oidc-client/package.json)
2. Fix imports and continue to support rxjs6, add "rxjs": "^6.5.3 || ^7.4.0" to root package.json. Maybe add check in pipeline, that lib works with rxjs v6? I think I can try to help with PR with these fixes, if you decide to choose this way

**Comment by FabianGosebrink** [comment]
Could be solved with https://github.com/damienbod/angular-auth-oidc-client/pull/1491

**Comment by niqolay** [comment]
I checked with fixes in https://github.com/damienbod/angular-auth-oidc-client/pull/1491, it is working correctly now, thanks
