### ISSUE TITLE
[Feature Request]: Go to signup instead of signin

### ISSUE THREAD

**Issue by patoigz** [damienbod/angular-auth-oidc-client#1490]
Hey!
Im using the library with Keycloak as my OIDC Identity Provider... And every time that i use the authorize or authorizeWithPopUp it goes to the login page. And its fine, its developed to do that but i'd like to redirect user to the signup page.

I was wondering... If you can add another function method, to allow users to go to the signup page directly, instead of login/signin.

Thanks!!!

**Comment by timdeschryver** [comment]
@FabianGosebrink I think we closed the wrong issue with #1491 
The issue that needed to be closed is #1489

**Comment by FabianGosebrink** [comment]
Aren't both fixed with this PR?

**Comment by timdeschryver** [comment]
I think this is issue isn't related to the RxJS import changes ( I could be wrong though )
