### ISSUE TITLE
[Bug]: Inifinte loop after authentication

### ISSUE THREAD

**Issue by georgina1278** [damienbod/angular-auth-oidc-client#1509]
**Describe the bug**

I'm using this library in my Angular project with authentication throught IdentityServer. I configured my project following the docs.

When the user goes to the home page in my app, it checks if this user is authenticated or not with a guard provided on the app-routing on my home-page.component route with `canActivated`. The code of my guard looks like this:

```
return this.oidcSecurityService.isAuthenticated$.pipe(
	map(({ isAuthenticated }) => {

		// allow navigation if authenticated
		if (isAuthenticated) {
			return true;
		}

		// redirect if not authenticated
		this.oidcSecurityService.authorize();
		return false;
	})
);
```

If not authenticated, redirects the user to the external login page, after logging in IdentityServer redirects the users to my app HomePage.

After successfull authentication it cause an infinite loop because isAuthenticated always return false. 
 
I have the `.checkAuth()` on the ngOnInit() in my app.component.ts.

`this.oidcSecurityService.checkAuth().subscribe(({ isAuthenticated, userData, accessToken, idToken }) => {});`

**Angular Configuration**

Angular-auth-oidc-client 14.1.3
Angular 14.1.2
Typescript: 4.6.2

Desktop (please complete the following information):

OS: Windows
Browser: Chrome
Version: 104

**Comment by FabianGosebrink** [comment]
Are you aware of the guards we are providing with this library? https://nice-hill-002425310.azurestaticapps.net/docs/documentation/auto-login

**Comment by georgina1278** [comment]
Thank you @FabianGosebrink, with the guard provided with the library the authentication works as expected!
