### ISSUE TITLE
[Question]: How to catch error in checkAuth method

### ISSUE THREAD

**Issue by L1nkss** [damienbod/angular-auth-oidc-client#1513]
**What Version of the library are you using?**
14.0.2

**Question**
Greetings @FabianGosebrink @damienbod
In our application we use `AutoLoginAllRoutesGuard` and we can't change it to `AutoLoginPartialRoutesGuard`.
Sometimes our clients face `could not find matching config for state` error.
How can I catch and handle that error inside app.module or app.component? If I understood correctly, we can't use `AutoLoginAllRoutesGuard` and `checkAuth` method at the same time.

For example, maybe if we add new event in `PublicEventsService` and will fire it when error shows up in `checkAuth` it will allow us to subscribe and catch errors inside app.component.

**Comment by FabianGosebrink** [comment]
Are the clients logging in from a bookmark? When the app redirects to the IDP, then it saves a state and tries to match it when you're coming back. So this might cause the issue.

**Comment by Janl1** [comment]
Hey, I have the exact same problem.. Every now and than our Sentry logging reveals user being stuck with the error `could not find matching config for state`.

Is there a way to catch the error?

**Comment by FabianGosebrink** [comment]
I think the check is not correct... Let me check this and get back to you. Maybe we are checking a little too aggressive here. Will keep you posted and push a fix eventually. Need to clarify.

**Comment by Janl1** [comment]
Unfortunately I dont know how the url looks like when the issue occurs. Everytime I tried to reproduce the error I had no luck. The customer sadly had..

However, I switched to a public route including the PartialRouteGuard and since then my sentry instance doesnt report the issue anymore.

**Comment by FabianGosebrink** [comment]
Nice. That is good. We published a fix which is maybe targeting the issue as well. However, having one public route is the preferred solution.
