### ISSUE TITLE
would it be possible to add the AuthStateService to the package.json export

### ISSUE THREAD

**Issue by SemionMcAlice** [damienbod/angular-auth-oidc-client#1520]
**What Version of the library are you using?**
14.1.4

**Question**
I would like to use the AuthStateService in some custom code. if i do that i get an error stating that it is not part of the package.json export field.
 Error: Module not found: Error: Package path ./lib/auth-state/auth-state.service is not exported from package ...\ClientApp\n
ode_modules\angular-auth-oidc-client (see exports field in ...\ClientApp\node_modules\angular-auth-oidc-client\package.json)

**Comment by FabianGosebrink** [comment]
Which method do you need?

**Comment by SemionMcAlice** [comment]
Hey,
i use the this.authConfService.getAllConfigurations() and the this.authStateService.getAccessToken(firstConfig) methods of the AuthStateService.
similar to the auth.interceptor does.

**Comment by FabianGosebrink** [comment]
You can use the [getconfigurations](https://angular-auth-oidc-client.com/docs/documentation/public-api#getconfigurations) method to get all configurations, and you get the access token back in the LoginResponse as well as with the [getAccessToken ](https://angular-auth-oidc-client.com/docs/documentation/public-api#getaccesstokenconfigid-string) method. Everything you need should be exposed already.

**Comment by SemionMcAlice** [comment]
Hey,
The ConfigurationService is exposed (exportet), but the AuthStateService somehow isn't.
i created a test project, attached. here you can see the error when running ng build. example code is in the app.component.

i made a test with your code where i added the AuthStateService explicitly in the index.ts file under the lib directory, then it gets exported correctly.
![image](https://user-images.githubusercontent.com/8114937/188107735-d7287a1c-9dfb-4e5b-b3b0-911d75460054.png)

[AngularAuthOidcClientTest.zip](https://github.com/damienbod/angular-auth-oidc-client/files/9476694/AngularAuthOidcClientTest.zip)

**Comment by FabianGosebrink** [comment]
Thanks. But you do not need this. You can use the methods mentioned above, because the functionality is already exposed over the public API :)
