### ISSUE TITLE
[Question]: Infinite loop after login when maxIdTokenIatOffsetAllowedInSeconds is configured

### ISSUE THREAD

**Issue by walter-psjr** [damienbod/angular-auth-oidc-client#1522]
**What Version of the library are you using?**
14.1.4

**Question**
Hi, I updated an angular 13 project with angular-auth-oidc-client 13 to angular 14 with angular-auth-oidc-client 14.1.4. In the old version I was making use of the maxIdTokenIatOffsetAllowedInSeconds option because many of our users had the clock with the wrong time and everything was working perfectly. But after updating, using the same settings, now the application is in an infinite loop after login, appearing and disappearing the url parameter ?code=... and the following message appears on the console:

**authCallback id token expired
authorizedCallback, token(s) validation failed, resetting. Hash:**

If I remove the maxIdTokenIatOffsetAllowedInSeconds configuration it works again. Could anyone let me know if there was any change in behavior regarding this configuration or if it could be a possible problem?

**Comment by L1nkss** [comment]
Possibly because of my [PR](https://github.com/damienbod/angular-auth-oidc-client/pull/1451/files), but I'm not sure
I had the same problem as you 
Did you try to add `disableIdTokenValidation: true` to your configuration?

**Comment by walter-psjr** [comment]
Hi @L1nkss , 

Yes, with disableIdTokenValidation: true it works, but without it and with maxIdTokenIatOffsetAllowedInSeconds the application enters a loop after the post login redirect. So would it be a bug caused by this pull request?

**Comment by walter-psjr** [comment]
Hi, any clues about this problem? I'm stuck not being able to release an application update because of this. Could anyone tell me what would be the risk of disabling this idtoken validation? Could this expose any risk?

**Comment by walter-psjr** [comment]
The problem has been fixed in version 14.1.5.

Thanks
