### ISSUE TITLE
[Bug]: Silent renew called 2 times?

### ISSUE THREAD

**Issue by michal-husak** [damienbod/angular-auth-oidc-client#1523]
**What Version of the library are you using?**
"@angular/core": "14.0.7",
"angular-auth-oidc-client": "14.1.3",

**Describe the bug**
The library checks every 4 seconds if the access token expired.  When it does it triggers the silent renew:
![image](https://user-images.githubusercontent.com/5699580/188228756-6ea12a57-8790-4ae9-b380-0f9fed533ab4.png)

which causes two calls being fired against our IDP:
https://our-idp.com/nidp/oauth/nam/token
https://our-idp.com/nidp/oauth/nam/keys

This cycle sometimes works without any problem and sometimes the token call fails with error 400:
![image](https://user-images.githubusercontent.com/5699580/188229247-e3ee1485-5264-4547-814e-c52058b98430.png)

And this is what happens in the console when the debug mode is on:
![image](https://user-images.githubusercontent.com/5699580/188229567-4bfe4bbb-67f7-44b6-9e32-21d7930ccc30.png)

Seems like the library started the silent renew 2 times.

Could it be that the refresh token is being used 2 times and therefore the silent renew fails with the error: "Refresh token has been revoked"?

**Expected behavior**
I would expect this not to be happening :)

**Desktop (please complete the following information):**

- OS: iOS and Windows
- Browser chrome
- Version latest

**Comment by michal-husak** [comment]
Seems like during the first renew the request to our IDP /token endpoint took a bit longer and the library set the `silentRenewRunning` flag to `false` already, so the next check started again.
I think, that's why the call resulted with the error.

I played around with the config and added:
```js
renewTimeBeforeTokenExpiresInSeconds: 10,
tokenRefreshInSeconds: 10,
```

and the error seems to be gone. But still I think, this is something which should not happen.

**Comment by damienbod** [comment]
The renew can only be run once at a time for the same client. This is required due to the validation and the state, nonce checks.
