### ISSUE TITLE
keep new tab logged in

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#1527]
**What Version of the library are you using?**
Angular: 9.0.2
angular-auth-oidc-client: 11.6.10
**Question**
Hello, when a user logs into my website and opens the same website in a new tab, how can I keep the new tab logged in as well?

I am considering changing the storage mechanism to localStorage. I don't know if there are other problems. Do you have a good way?

Thank you and look forward to replying.

**Comment by fengzhihenxs** [comment]
@damienbod  Hello, after logging in, copy the link to open the second tab, how to achieve automatic login?

**Comment by Angelinsky7** [comment]
i think you need to change from `sessionStorage` to `localStorage` or something similar....

How : https://nice-hill-002425310.azurestaticapps.net/docs/documentation/custom-storage
Why:  https://codesource.io/localstorage-vs-sessionstorage-explained/
