### ISSUE TITLE
[Bug]: error in AuthModule configuration

### ISSUE THREAD

**Issue by Simkiw** [damienbod/angular-auth-oidc-client#1528]
**What Version of the library are you using?**
11.6.11

**Describe the bug**
Argument of type '{ config: { authority: string; redirectUrl: string; postLogoutRedirectUri: string; clientId: string; scope: string; responseType: string; silentRenew: boolean; useRefreshToken: boolean; logLevel: LogLevel; }; }' is not assignable to parameter of type 'Token'.
  Object literal may only specify known properties, and 'config' does not exist in type 'Token'.

**To Reproduce**

1. Installed the package via npm at package.json level
2. Added the AuthModule configuration in app.Module.ts as described in the docs
3. See error

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Ng cli v 8.3.29
- Node v 14.16.0

**Comment by FabianGosebrink** [comment]
You are using an old version of the lib. Please update to a later version. Thanks!

**Comment by Simkiw** [comment]
Hello,

I installed the version 14.0.0 and yet, I still have the same error.  
My app.module looks like this:

```
import { AuthModule, LogLevel } from 'angular-auth-oidc-client';
//Other imports

imports: [
    BrowserModule.withServerTransition({ appId: 'ng-cli-universal' }),
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    AuthModule.forRoot({
      config: {
        authority: '<your authority address here>',
        redirectUrl: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        clientId: '<your clientId>',
        scope: 'openid profile email offline_access',
        responseType: 'code',
        silentRenew: true,
        useRefreshToken: true,
        logLevel: LogLevel.Debug,
      },
    }),
    RouterModule.forRoot([
// routes and whatsoever
```

I believe there is no difference between using ng add and npm install but writing these lines by myself.  
Is there any specific cleaning I have to do? ForRoot method still expects a token instead of a config, it's as it's still sing the old library.

**Comment by timdeschryver** [comment]
@Simkiw I copy-pasted the config into a stackblitz and it appears to compile.
Could you reproduce it here as well?

https://stackblitz.com/edit/angular-ivy-f6pyvo?file=src%2Fapp%2Fapp.module.ts

**Comment by Simkiw** [comment]
@timdeschryver hmmmm, I just clicked on the link, i'm not very familiar with the stackblitz but ... yeah, it appears to be working there, I mean i do have the **Hello Angular 14!** and i don't seem have a compiling error.  
I'm gonna try to clean my cache, maybe the problem come from there.

**Comment by Simkiw** [comment]
I'm not sure how, but .. facing difficulties to clear my cache combined with my lack of expertise in angular, I uninstalled the package via **npm uninstall** and .. looks like it removed the error. Now the method takes the right argument which is the config and not a token.  
I think it has to do with the previous and old lib which has not been replaced with a recent one, and somehow angular was still using the old one.

**Comment by timdeschryver** [comment]
Great! Thanks for the update.
Feel free to close the issue if it's resolved :)
