### ISSUE TITLE
[Question]: Logoff and revoke tokens not working for me v14.1.4

### ISSUE THREAD

**Issue by Doc1027** [damienbod/angular-auth-oidc-client#1530]
**What Version of the library are you using?**

- Angular Auth Oidc Client v14.1.4
- Angular 14
- OPENIDDict on server

**Question.**
When logoffAndRevokeTokens method is called, the user is logged off locally but never logged off on the server. I'm seeing a couple of things happen:

1. It appears that the StsConfigLoader runs again as soon as the logoffAndRevokeTokens method is invoked. I know this because I see the call to fetch the json doc we use for config values and I also see a debug log entry stating: "Did not find any configured route for route" with the route to the config json doc.
2. I see debug log entries stating: "revocation endpoint not supported", "only local login cleaned up, no end_session_endpoint"

The interesting thing about the no end session endpoint log is that endpoint is in the config at /.well-known/...

This is how I setup the config:
```typescript
export const httpClientLoaderFactory = (httpClient: HttpClient) => {
  const authConfig$ = httpClient.get<CommonTypes.IIdentityTenantConfig>(configUrl).pipe(
    tap(d => {
      console.log('STSAUTHCONFIG TCONFIG', d);
    }),
    map((config) => {
      return {
        authority: authorityRoot,
        clientId: config.TENANT_ID,
        redirectUrl: `${hostLocation.origin}/callback`,
        responseType: 'code',
        scope: 'openid offline_access',
        postLogoutRedirectUri: `${hostLocation.origin}/logout`,
        silentRenew: true,
        useRefreshToken: true,
        secureRoutes: ENV.secureUris.map(uri => uri),
        ignoreNonceAfterRefresh: true,
        logLevel: LogLevel.Debug,
      };
    })
  );
  return new StsConfigHttpLoader(authConfig$);
}
```
and the auth module:

```typescript
@NgModule({
  imports: [
    AuthModule.forRoot({
      loader: {
        provide: StsConfigLoader,
        useFactory: httpClientLoaderFactory,
        deps: [HttpClient],
      }
    }),
  ],
  exports: [AuthModule],
  providers: [
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
  ],
})
```

Here is a sample of our openid-comfig @ /.well-known
```json
{
  "issuer": "https://localhost:5001/",
  "authorization_endpoint": ".../authorize",
  "token_endpoint": ".../token",
  "end_session_endpoint": ".../logout",
  "userinfo_endpoint": ".../current",
  "jwks_uri": ".../.well-known/jwks",
  "grant_types_supported": [
    "authorization_code",
    "client_credentials",
    "refresh_token"
  ],
  "response_types_supported": [
    "code"
  ],
  "response_modes_supported": [
    "form_post",
    "fragment",
    "query"
  ],
  "scopes_supported": [
    "openid",
    "offline_access"
  ],
  "claims_supported": [
    "aud",
    "exp",
    "iat",
    "iss",
    "sub"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "code_challenge_methods_supported": [
    "S256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "revocation_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "claims_parameter_supported": false,
  "request_parameter_supported": false,
  "request_uri_parameter_supported": false
}
```

Can anyone shed some light on what I may be doing wrong? This behavior was not present in v13.x. I updated to the latest to see if I could get refresh tokens working which does work now.

Thanks

**Comment by denhaandrei** [comment]
Hi All, @damienbod. @Doc1027 

I think it`s a bug, logoffAndRevokeTokens - does not logoff the current user
  does not work for v14.1.5:
        this.oidcSecurityService.logoffAndRevokeTokens();
now I'm used to fixing it:
        this.oidcSecurityService.logoffAndRevokeTokens();
        this.oidcSecurityService.logoff();

Maybe it help you:
**Data from the server logs(without call logoff()):**
[DEBUG] 0-angularclient_dev - Checking: silentRenewRunning: false, isCodeFlowInProgress: false - has idToken: true - has userData: true
[DEBUG] 0-angularclient_dev - Has idToken expired: false --> expires in 43199:23 , 15:22:46 > 15:23:23
[DEBUG] 0-angularclient_dev - Has accessToken expired: false --> expires in 43199:23 , 15:22:46 > 15:23:23
[DEBUG] 0-angularclient_dev - silent renew, periodic check finished!
[DEBUG] 0-angularclient_dev - Checking: silentRenewRunning: false, isCodeFlowInProgress: false - has idToken: true - has userData: true
[DEBUG] 0-angularclient_dev - Has idToken expired: false --> expires in 43199:21 , 15:22:46 > 15:23:25
[DEBUG] 0-angularclient_dev - Has accessToken expired: false --> expires in 43199:21 , 15:22:46 > 15:23:25
[DEBUG] 0-angularclient_dev - silent renew, periodic check finished!
[DEBUG] 0-angularclient_dev - Checking: silentRenewRunning: false, isCodeFlowInProgress: false - has idToken: true - has userData: true
[DEBUG] 0-angularclient_dev - Has idToken expired: false --> expires in 43199:17 , 15:22:46 > 15:23:29
[DEBUG] 0-angularclient_dev - Has accessToken expired: false --> expires in 43199:17 , 15:22:46 > 15:23:29
[DEBUG] 0-angularclient_dev - silent renew, periodic check finished!
**...**

**After Call LogOff:**
[DEBUG] 0-angularclient_dev - logoff, remove auth 
[DEBUG] 0-angularclient_dev - Checking: silentRenewRunning: false, isCodeFlowInProgress: false - has idToken: false - has userData: false
[DEBUG] 0-angularclient_dev - silent renew, periodic check finished!
OpenIddict.Server.OpenIddictServerDispatcher: Information: The request address matched a server endpoint: Logout.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The logout request was successfully extracted: {
  "id_token_hint": "[redacted]",
  "post_logout_redirect_uri": "https://localhost:44360"
}.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The logout request was successfully validated.
*.Controllers.AuthorizationController: Information: User *@gmail.com logged out.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The logout response was successfully returned to 'https://localhost:44360': Microsoft.AspNetCore.Http.DefaultHttpResponse.
[DEBUG] 0-angularclient_dev - Working with config '0-angularclient_dev' using https://localhost:44360
[DEBUG] 0-angularclient_dev - currentUrl to check auth with:  https://localhost:44360/
[DEBUG] 0-angularclient_dev - checkAuth completed - firing events now. isAuthenticated: false

**Comment by damienbod** [comment]
Will validate this, thanks for reporting

Greetings Damien

**Comment by damienbod** [comment]
@Doc1027 just tested this and it works. You are missing the support for this. If you check you well known endpoint, it is not support in your server setup. Add this to support it and also include the support in the client:

```
.SetRevocationEndpointUris("/connect/revocation")
```

```
 Permissions =
                        {
                            // permissions ...
                            Permissions.Endpoints.Revocation

                        },
```

**Comment by damienbod** [comment]
Please reopen is something is missing, Greetings Damien

**Comment by denhaandrei** [comment]
@damienbod 
Hi, sorry for the delay,
I have everything and it worked on Angular 12. 
After updating to Angular 14, it stopped working.
Can you attach your working example, maybe I miss something?

Thanks,
Andrey
