### ISSUE TITLE
[Question]: Using authorization_code flow with authentication required on token endpoint

### ISSUE THREAD

**Issue by kaiaverkvist** [damienbod/angular-auth-oidc-client#1531]
**What Version of the library are you using?**
> "angular-auth-oidc-client": "^13.0.0",

**Question**
How do I use this library with an oauth provider that requires authentication on the token endpoint?
Well-known tags this as the following:
```
"token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic"
],
```

Currently I see Http 401 on the /token endpoint after successfully logging in because of this. I want to avoid storing client_secret in the frontend.

I see some projects exist to act as a proxy between the SPA and the OIDC provider. How do I set this up with this library?

**Comment by henninga** [comment]
Did you find a solution to this? I'm having this same issue.
Apparently the oidc provider has to support pkce, ref https://github.com/damienbod/angular-auth-oidc-client/issues/399#issuecomment-471870487
