### ISSUE TITLE
[Bug]: Calling logoffAndRevokeTokens() does not revoke access token

### ISSUE THREAD

**Issue by benp25** [damienbod/angular-auth-oidc-client#1534]
Firstly, thank you for an awesome and simple to use library. I use this library at $job and we have bumped into a couple of minor issues, so as some small way of giving back I hope you will accept a PR to resolve this issue for others who may also be experiencing the same thing.

I have made PR #1532 to patch main and #1533 to patch V13.

**What Version of the library are you using?**
13.1.0, but I also see the bug in latest 14.1.4

**Describe the bug**
When I call `logoffAndRevokeTokens`, my refresh token is revoked but the access token is not. Inspecting network traffic, looking at server side logs, and interrogating the OpenIddict database, I can see the refresh token is revoked successfully but the request to the revocation endpoint for the access token sends a literal `[object Object]` and not the actual access token to revoke (see screenshot 1).

I have worked out this is coming from the following line of code (line 76 in logoff-revocation.service.ts):
`switchMap((result) => this.revokeAccessToken(config, result))`
This call to `revokeAccessToken` is sending along `result` (which is just an empty object), where it seems all other calls do not send the second argument (which is supposed to be an access token). The `revokeAccessToken` method sees that the `accessToken` argument has a value and thus does not call `this.storagePersistenceService.getRefreshToken(configuration)` to get the current access token and instead just uses `{}`, which `urlService.createRevocationEndpointBodyAccessToken` then serializes as `[object Object]`.

I do not believe the OIDC server should send a response body, only a HTTP 200 status, so passing the response from the refresh token revoke request seems incorrect behaviour. My solution is to simply not pass along a second argument to `revokeAccessToken` so the current access token is retrieved from storage. In my testing, this resolved the issue and my actual access token was sent to the revocation endpoint and I have verified it was successfully revoked in the OpenIddict database.

**To Reproduce**
Simply call `logoffAndRevokeTokens` in code.

**Expected behavior**
The actual access token should be sent to the revocation endpoint.

**Screenshots**
Screenshot 1 - network request to the revocation endpoint
![image](https://user-images.githubusercontent.com/3432323/189981102-ae503f9d-25a1-4f37-b509-110bd06468f8.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 105

**Comment by damienbod** [comment]
thanks
