### ISSUE TITLE
Validate_id_token_nonce failed authorizedCallback incorrect nonce

### ISSUE THREAD

**Issue by profet23** [damienbod/angular-auth-oidc-client#154]
I'm constantly getting this error and I'm just not really sure where to begin as far as correcting it.

Validate_id_token_nonce failed, dataIdToken.nonce: N0.80161413015388371515691465967 local_nonce:N0.30791266821172591515691468480

authorizedCallback incorrect nonce
authorizedCallback, token(s) validation failed, resetting

So basically my code loops. trying to authenticate, redirecting, getting a token, having a nonce failure, trying to authenticate....

Any insights here would be appreciated.

**Comment by damienbod** [comment]
Hi @profet23 

Are you calling the authorize function more than once without waiting for the callback?

Greetings Damien

**Comment by profet23** [comment]
It seems like I was. 

Some background:
I'm trying to get "auto" login to work. As in if the user hits a page and aren't logged in, the login process will be kicked off. 
Right now I'm doing this with an auth guard on any route requiring authentication. If the user is not authenticated they'll get rerouted to a `SignIn` component that just calls the following function on init:

```
    login() {
        if (this.isAuthorized === undefined) {
            this.oidcSecurityService.onAuthorizationResult.subscribe((isAuthorized) => {
                if (isAuthorized !== AuthorizationResult.authorized) {
                    this.oidcSecurityService.authorize();
                }
            });

            //this delay is required. I'm not entirely sure why 
            setTimeout(() => {
                if (this.isAuthorized !== true) {
                    this.oidcSecurityService.authorize();
                }
            }, 500)
        }
        else if(this.isAuthorized !== true) {
            this.oidcSecurityService.authorize();
        }
    }
```

Any info on why that delay is necessary would be extremely enlightening. It seems like `OidcSecurityService.onModuleSetup` is firing before everything is all setup. Either that or there is some other event subscription that I'm not seeing.

**Comment by damienbod** [comment]
@profet23 I'll have  a look at this. I want to improve the setup/init of the module.

**Comment by damienbod** [comment]
@profet23 The timer is required because the app is not waiting for the init requests to finish. Looking into  way the do this in the APP_INITIALIZER, and then the wait can be removed.

**Comment by damienbod** [comment]
@profet23 This seems like a bigger problem. The providers and the guards don't wait for the APP_INITIALIZER to complete, only the components in Angular. This seems like a design bug in Angular for me, as you then need to add hacks to the services, guards when using preloaded server data from a HTTP request.

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/156

**Comment by damienbod** [comment]
fixed this in release 4.0.0

**Comment by profet23** [comment]
Working as intended now. Thanks,

**Comment by satkanth** [comment]
@profet23 Do you have some sample code for how you got this working?  I am having the same issue with the continuous loop when I am trying to use the auto login feature in conjunction with the auth guards.  I have the authorize call in the autologin page and in the authguard.  Any insight would be appreciated.

**Comment by damienbod** [comment]
@satkanth Here's 2 examples

https://github.com/damienbod/dotnet-template-angular

Do these help?

**Comment by satkanth** [comment]
@damienbod  Thanks, I appreciate the reply.  That seems to have done the trick although for some reason after authorization, my Unauthorized page flickers for a bit before it sends me to my page.  I think the problem might have been that I had the authorize call within the authguard also if the page was not authenticated.  

 public canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean> | boolean {
      
      return this.oidcSecurityService.getIsAuthorized().pipe(
            map((isAuthorized: boolean) => {
                if (isAuthorized) {
                    return true;
                }

                // Stores the attempted URL for redirecting.
                this.authService.setRedirectUrl(state.url);

                this.oidcSecurityService.authorize();
                return false;
            })
      );
  }
I am assuming that this is NOT necessary

**Comment by aksjer** [comment]
I have same issue ... but just with Firefox ...
