### ISSUE TITLE
[Bug]: UnauthorizedComponent is shown for a moment before loading the application after login

### ISSUE THREAD

**Issue by patolax** [damienbod/angular-auth-oidc-client#1548]
We are using ` angular-auth-oidc-client": "14.1.5"` and  `AutoLoginAllRoutesGuard` in the router. 

When we log in and get redirected from identiyserver v4, the following things occur related to checkAuth.

We have our own service wrapping OidcSecurityService. 

There we subscribe to this.oidcSecurityService.checkAuth().
In this case, we get this error and a small glimpse of UnauthorizedComponent .
![image](https://user-images.githubusercontent.com/29444156/192418858-cdf5d32d-9bcf-43d4-89c3-4c47411cdb73.png)

if we remove checkAuth we get this error and the application would not load until the next refresh.
![image](https://user-images.githubusercontent.com/29444156/192418364-da90f185-64da-410b-a45d-66e3a33df7ce.png)

any idea what is happening?

**Comment by FabianGosebrink** [comment]
Can you please provide a title for this bug?

**Comment by patolax** [comment]
sorry, done!

**Comment by FabianGosebrink** [comment]
No worries, just help us to keep track of all the inputs. Thanks!

So normally if you start the login process from the app, a state is persisted, and when the IDP sends you back to the app we need to figure out which config is being used, so the state is being read and matched to a config.

In your case, a config can not be found, maybe the state is missing? Did you start the login process, maybe with a bookmark pointing to the IDP?

Thanks

**Comment by patolax** [comment]
historyCleanupOff: false, fixed the issue.
