### ISSUE TITLE
[Question]: customParams is null, when initially set in authorize. Angular 14

### ISSUE THREAD

**Issue by DenislavSyarov** [damienbod/angular-auth-oidc-client#1553]
I am using Angular 14 and the 14.1.5 version of the library

**Question**
How can I retrieve customParamsAuthRequest ?
I am initially setting a customParams object:

```
const customParams: AuthOptions = {
      customParams: {
        path: returnPath,
      },
    };
    this.oidcSecurityService.authorize("authConfig", customParams);  
```
 Then when I would like to retrieve it after the stsCallback the object is null, but I can see it in the session storage.
    
 Code to retrieve 
    
```
    this.oidcSecurityService.stsCallback$
          .pipe(
            mergeMap((x) => {
              return this.oidcSecurityService.getConfiguration();
            })
          )
          .subscribe((conf) => {
            let returnPath = decodeURIComponent(conf.customParamsAuthRequest.returnPath.toString());
          });
```

I can see the object `storageCustomParamsAuthRequest` being set in the session storage in the browser, but the returnPath in the code is always null. This was working fine with version 13 of Angular and the library.

**Comment by FabianGosebrink** [comment]
Hey, what exactly are you trying to retrieve after the login? Thanks!
