### ISSUE TITLE
[Question]: silent renew false and id_token expired

### ISSUE THREAD

**Issue by premsaikp** [damienbod/angular-auth-oidc-client#1555]
**What Version of the library are you using?**
Currently I am using 12.1 version.

**Question**
first of all I am new to this library and I am trying for below solution, 
I am trying to achieve token expiry pop message once my Id token expired, for this I make it silentRenew as false and in this case I am using public service events and these events not firing once my Id token expired( upto 30 min) and also isAuthendicated function returning always true.
Could you please suggest me how can I get a message once my Id Token expired with silentRenewa false.
Sorry If I asked anything wrong  & Thanks in advance.

**Comment by damienbod** [comment]
You probably should just use the default refresh and update to the latest version.

Greetings Damien
