### ISSUE TITLE
Migration 11 -> 12 load configuration from app environment

### ISSUE THREAD

**Issue by GeofoxCoding** [damienbod/angular-auth-oidc-client#1556]
Version 12.0.3

Hello,

I'm currently migration from version 11 to 12 and I'm facing a problem with the module initialization. I get my config object through my own ConfigService from my environment.ts configs.

So far I was able to configure OidcConfigService easily with a factory.

```
export function configureAuth(oidcConfigService: OidcConfigService, configService: ConfigService) {
  return () =>
    oidcConfigService.withConfig(configService.getConfiguration().auth);
}
```
```
  providers: [
    OidcConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: configureAuth,
      deps: [OidcConfigService, ConfigService],
      multi: true,
    },
```

How can this be done with the current setup?

Thank you for your help.

**Comment by timdeschryver** [comment]
Hey @GeofoxCoding does this help?
https://angular-auth-oidc-client.com/docs/migrations/v11-to-v12#loading-config-from-endpoint-http

**Comment by GeofoxCoding** [comment]
Hello @timdeschryver,yes, that helped. Thank you! 

I overlooked that point because I don't want to fetch with HTTP. But the point of the StsConfigHttpLoader is that it takes a Promise that can be created in any way.
