### ISSUE TITLE
[Question]: Requesting Individual Claims

### ISSUE THREAD

**Issue by dgphilly** [damienbod/angular-auth-oidc-client#1557]
**What Version of the library are you using?**
12.0.3

**Question**
Is there functionality to request individual claims in the config and set them as "essential"? My hope is for them to be returned as part of the userinfo api call. 

Specs based on openID:
https://openid.net/specs/openid-connect-core-1_0.html#IndividualClaimsRequests

**Comment by milo526** [comment]
I was just looking into this to enforce an `acr` claim.

You should be able to mark claims as essential by including them in the `customParamsAuthRequest` property.

Please be aware that this seemingly requires your IDP to support the claims parameter, this should be advertised in the `/.well-known/openid-configuration` document by the `claims_parameter_supported` key being set to `true`

```
customParamsAuthRequest: {
  claims: JSON.stringify({
    id_token: {
      acr: {
        value: 'mfa',
        essential: true,
      },
    },
  }),
},
```
