### ISSUE TITLE
[Question]: Unable to use this library with capacitor?

### ISSUE THREAD

**Issue by imdmehdi** [damienbod/angular-auth-oidc-client#1559]
**What Version of the library are you using?** 14.0.1
...

**Question**
How can I use this library with capacitor js to create hybrid android app.

My application is working properly with Angular 14 and is able to authenticate users. But when I generate capacitor files using npx cap sync it's not working. When I run the capacitor one:  It's opening the app and redirecting to login page of Identity server4 but after user input and login I am getting error log on identity server saying client id is null. But If client id has been null then I should not have able to open the login page itself, so I think library is not able to bring the code and call for getting token.

Please help @damienbod .  Am I missing anything? Or this library is not compatible with Capacitor.

**Comment by JyotiP10** [comment]
Hi @damienbod I am also facing similar issue Please help!!

**Comment by damienbod** [comment]
I assume capacitor  is a wrapper to create a native application on a mobile device. This framework needs to implement the bridge. The native app opens a browser with a special URL and does the authentication in the browser. Once finished, the tokens can be returned back to the native application. A logout needs to clear the browser as well. The native wrapper would need to implement this correctly. You also need a directly client configuration for native apps.

Greetings Damien

**Comment by imdmehdi** [comment]
@damienbod  ,
So, I understand that we need to make extra changes in place of using this library directly?

**Comment by damienbod** [comment]
no idea how capacitor does this or what it does, I would need to read the docs. I see in the does you can use this with Ionic, the lib works with ionic for native apps. I don't know these frameworks

Greetings Damien

**Comment by imdmehdi** [comment]
@damienbod  
Ok thanks Alot for responding, will look ahead.

**Comment by imdmehdi** [comment]
> no idea how capacitor does this or what it does, I would need to read the docs. I see in the docs that you can use this with Ionic, the lib works with ionic for native apps. I don't know these frameworks
> 
> Greetings Damien

Can you provide the link of that doc where you saw it can be used with ionic. It would be of great help.

**Comment by damienbod** [comment]
https://capacitorjs.com/docs/getting-started/with-ionic

**Comment by imdmehdi** [comment]
Thanks, 
But we did not got any reference where if we can use this angular-auth-oidc-client library with ionic or capacitor. 
Might be identity server is written in MVC so capacitor or ionic not works due to this as expected.

**Comment by FabianGosebrink** [comment]
You can use this lib with capacitor. You have to react to the redirection from the STS with this event here https://capacitorjs.com/docs/guides/deep-links#angular and a guide for react is here, but with their API. You can call the checkAuth() when it is redirected, it does everything for you. https://auth0.com/docs/quickstart/native/ionic-react/01-login

**Comment by imdmehdi** [comment]
> You can use this lib with capacitor. You have to react to the redirection from the STS with this event here https://capacitorjs.com/docs/guides/deep-links#angular and a guide for react is here, but with their API. You can call the checkAuth() when it is redirected, it does everything for you. https://auth0.com/docs/quickstart/native/ionic-react/01-login . `checkAuth()` supports passing a url. https://www.angular-auth-oidc-client.com/docs/documentation/public-api#checkauthurl-string-configid-string

Thanks Alot,  will check this solution.

**Comment by FabianGosebrink** [comment]
Just programmed it locally and it works. The hard thing is the custom url scheme. For android this is:

AndroidManifest.xml

```
            <intent-filter>
              <data android:scheme="@string/custom_url_scheme"/>
              <action android:name="android.intent.action.VIEW"/>
              <category android:name="android.intent.category.DEFAULT"/>
              <category android:name="android.intent.category.BROWSABLE"/>
            </intent-filter>
```

strings.xml

```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">ratemydoggo</string>
    <string name="title_activity_main">ratemydoggo</string>
    <string name="package_name">com.example.app</string>
    <string name="custom_url_scheme">com.example.app</string>
</resources>

```
