### ISSUE TITLE
[Question]: Id_token decoding

### ISSUE THREAD

**Issue by adampolyanskiy** [damienbod/angular-auth-oidc-client#1561]
**What Version of the library are you using?**
13.1.0

**Question**
Our Identity Provider Server is supposed to encrypt id_tokens using a key before there are sent to a client. One of our clients is an Angular app. When the client receives id_token I see that It's not in an encrypted form because I can easily decode using the base64 decoder, while It is should be encrypted at the time when it is transmitted and then decoded on the client. So my question is: does the library decodes the id_token before it can be seen in the preview section of the request (on the screenshot)? Maybe I understand something the wrong way? Could somebody clarify this? Thanks a lot.
![Screenshot_1](https://user-images.githubusercontent.com/85818526/197111197-05a1d141-dae1-4bdb-82ce-e3e38830bcb9.png)

**Comment by damienbod** [comment]
The id_token is normally not encrypted, most IDPs just use base64 encoding. If the id_token is encrypted, then you would need a key to decrypt. It does not make sense for the ID token in a SPA. The access token can be encrypted and would improve the security.

**Comment by adampolyanskiy** [comment]
> The id_token is normally not encrypted, most IDPs just use base64 encoding. If the id_token is encrypted, then you would need a key to decrypt. It does not make sense for the ID token in a SPA. The access token can be encrypted and would improve the security.

Thank for the reply, damienbod. I wanted to clarify the part with the encryption on IDP. The thing is that our IDP is configured to encrypt id_token, but the angular app recieves it as it is, only base64 encoded. Can it be wrong configuration on UI side? Just in case, we use [[[Openiddict library]()](https://github.com/openiddict/openiddict-core)](https://github.com/openiddict/openiddict-core) as a library to implement openid connect.
