### ISSUE TITLE
[Question]: How can I subscribe to silent renew errors => add new event

### ISSUE THREAD

**Issue by PankajPatro** [damienbod/angular-auth-oidc-client#1565]
Using "angular-auth-oidc-client": "14.1.4"

We are using the angular-auth-oidc client library with PKCE mode. We also have enabled silentRenew option so that the application can fetch a new access token if the accesstoken expires. However sometime due to some error on the server (in our case we have a sub application which sometimes also refreshes the token) the silentRenew fails. We are glad that it does the right thing and fails, however when that happens, we would like to show the user of such a failure and ask him to take some appropriate action. The problem is when silentRenew fails it logs the error into the console window and throws the error, but there is no way to either catch that error or there is no event letting us know when such an error happens.

Would be glad if we are directed to some example codes of how others have handled these scenario

**Comment by FabianGosebrink** [comment]
We have an event called "SilentRenewStarted". We can introduce one if there was an error IMHO.

**Comment by PankajPatro** [comment]
Thank you, please let us know when the new event is added.

**Comment by damienbod** [comment]
Will be released in 15.0.1 , thanks for reporting.

Greetings Damien

**Comment by FabianGosebrink** [comment]
Event is added now, you can use it over the public event service.
