### ISSUE TITLE
[Question]: Prevent interceptor from always using token from first configured provider.

### ISSUE THREAD

**Issue by origooo** [damienbod/angular-auth-oidc-client#1566]
**What Version of the library are you using?**
13.1.0

I have a setup with two providers, Google and Azure (configured in that order). They both use the same `secureRoutes` and it works just fine when I sign in with Google. Though, when I sign in with Azure, the interceptor still tries to use a token from Google simply because that is the first config. The interceptor calls `closestMatchingRouteService.getConfigIdForClosestMatchingRoute(req.url)` to get the config id and since both configs use the same `secureRoutes` Google, in this case, will be matched but I expect it to use the Azure token since that is what I have authed through.

Is there a way around this?

**Comment by FabianGosebrink** [comment]
Currently, when an HTTP-Request hits the interceptor, we can not figure out which config tot take, so until now takes the first config always. What would be possible is: configure a URL and passing the `configId` to match. Then we would know it out of the configuration. Would that be something? I don't know if that works, it just came into my head.

**Comment by FabianGosebrink** [comment]
Just taking a look at this and I think this is not possible. You are having the issue that you got multiple configs, but only one of them is authenticated, and you want to receive the token from the config which is authenticated? Or are you authenticated with multiple configs at the same time?

**Comment by FabianGosebrink** [comment]
Is this issue still relevant?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Comment by origooo** [comment]
Hi Fabian,

I completely missed your replies. Sorry for that!

My case is as you asked in your second reply. I solved it by setting an 'active-provider' cookie while being successfully authenticated and then I refer to that cookie in an interceptor.

I'll attach my interceptor implementation for others to take inspiration from. It's still a work in progress but I haven't had any issues with it since I implemented it. Though, I haven't thought too hard about error handling yet. Any improvements are welcomed!

Maybe the library could be configured to require all or just one provider to be considered authenticated and make use of such a cookie (or whatever storage is used).

```import { Injectable } from "@angular/core";
import { LoggerService, OidcSecurityService } from "angular-auth-oidc-client";
import {
  HttpHandler,
  HttpEvent,
  HttpInterceptor,
  HttpRequest,
} from "@angular/common/http";
import { Observable } from "rxjs";
import { CookieService } from "ngx-cookie-service";

@Injectable()
export class AngularOIDCClientInterceptor implements HttpInterceptor {
  constructor(
    private cookieService: CookieService,
    private oidcSecurityService: OidcSecurityService,
  ) {}

  intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {

    // This could probably make use of the configs secureRoutes instead
    if (req.url.includes(`/api/`)) {
      const matchingConfigId = this.cookieService.get(`active-provider`);

      if (!matchingConfigId) {
        return next.handle(req);
      }

      const token = this.oidcSecurityService.getAccessToken(matchingConfigId);

      if (!token) {
        return next.handle(req);
      }

      req = req.clone({
        headers: req.headers.set(`Authorization`, `Bearer ` + token),
      });
    }

    return next.handle(req);
  }
};```
