### ISSUE TITLE
[Question]: Can this lib be used with Duende Identity Server?

### ISSUE THREAD

**Issue by gundogduhasan** [damienbod/angular-auth-oidc-client#1568]
**What Version of the library are you using?**
Latest.
**Question**
Hi,
I am currently using this lib in my project with identity server 4. But some reasons we decide to upgrade our identity server 4 to duende. Can i still use this lib? Have you any example related with bff? And last question do i have to use bff all clients and identity server in same domain? Or could be a different domains? Like identity.com, client1.com, client2.com etc.

Maybe last question doesn't related with this lib but if you can help me with these questions it would be great. Sorry for too many questions.

Best regards.

**Comment by damienbod** [comment]
Hi @gundogduhasan Yes this lib can be used with the latest identityServer. If you decide to switch to BFF, then you don't need this lib but some server rendered application which hosts the Angular application and the auth is implemented in the server application. Public clients with PKCE is still supported though.

Greetings Damien

**Comment by gundogduhasan** [comment]
Hi @damienbod thank you so much for your detailed answer. I just asking for double check. If I use bff I don't need to use this library right?

**Comment by damienbod** [comment]
correct

**Comment by gundogduhasan** [comment]
Thank you so much again 

Greetings.
