### ISSUE TITLE
[Question]: dynamic redirectUrl

### ISSUE THREAD

**Issue by julien-von-oetinger** [damienbod/angular-auth-oidc-client#1570]
**What Version of the library are you using?**
14.1.5

**Question**

In the configuration, we can only set a single redirection URL. At the moment I have this: `redirectUrl: 'http://localhost:4200'`.

But that means that whatever URL the user is trying to reach in my application, he will be redirected to the root of the application instead of the URL he entered. For example, if the user tries to access `http://localhost:4200/a/b/c` he will be forwarded to the IS4 login and then he will be sent back to `http://localhost:4200`. I have tried to use the `redirectUrl` in the `AuthOptions` when calling the `authorize` function but I get errors when coming back to my application (token endpoint return `invalid_grant`).

So, I am just wondering what is the correct way to deal with this?

**Comment by FabianGosebrink** [comment]
Is the url you want to redirect to configured at the IDP correctly?
