### ISSUE TITLE
[Question]: Is there any documentation for the "autoCleanStateAfterAuthentication?"

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1572]
**What Version of the library are you using?**
14.1.5

**Question**
How can I get more information on how the **autoCleanStateAfterAuthentication** works?

**Comment by FabianGosebrink** [comment]
We have problems with our docs currently, but they are saying 

```
Denotes if the state should be reset after authentication. When set to false, the state is not automatically reset. This can be used for custom state logic handling.
```

**Comment by fritzwf** [comment]
The key information I need for this variable is "reset after authentication," that is what does the reset actually do when it resets?

Thanks

**Comment by FabianGosebrink** [comment]
It overwrites the variable `authStateControl` with an empty string.

```
 if (autoCleanStateAfterAuthentication) {
      this.storagePersistenceService.write('authStateControl', '', configuration);
    }
```
