### ISSUE TITLE
Documentation Page is offline

### ISSUE THREAD

**Issue by RakouskyS** [damienbod/angular-auth-oidc-client#1574]
https://angular-auth-oidc-client.com/ gives a 404 error.

**Comment by FabianGosebrink** [comment]
Yes, we know and are working on that issue,

**Comment by FabianGosebrink** [comment]
You can find the docs in the repo as long as the site is not running https://github.com/damienbod/angular-auth-oidc-client/tree/main/docs/site/angular-auth-oidc-client/docs

**Comment by FabianGosebrink** [comment]
Should be online again
