### ISSUE TITLE
[Question]: How can I log in using the IP Address instead of the URL?

### ISSUE THREAD

**Issue by ramiz4** [damienbod/angular-auth-oidc-client#1576]
**What Version of the library are you using?**
14.1.5

IDP = keycloak 

**Describe the bug**
When running the sample-implicit-flow-silent-renew app via "npm start -- --host=0.0.0.0 --disable-host-check" and open the app on Browser via local IP address, then login does not work.

Repo to reproduce: https://github.com/ramiz4/sample-implicit-flow-silent-renew

![image](https://user-images.githubusercontent.com/1623235/201117499-ff725838-b387-4895-984c-83b1682906b0.png)

**Expected behavior**
Login should also work when opening the app via ip address

- OS: Windows 10
- Browser chrome
- Version 107.0.5304.89

**Comment by otrebor-bni** [comment]
I can confirm this behavior with the latest version 14.1.5.
On localhost everything works fine, as far as I host the app on a server (in my case IIS on windows server) it doesn't work anymore. This seems to be a bug.. 
@FabianGosebrink can you investigate this behavior?

**Comment by FabianGosebrink** [comment]
Does the IDP know the IP as referrer?

**Comment by otrebor-bni** [comment]
I use keycloak as IDP.
![image](https://user-images.githubusercontent.com/54057524/201138454-eb9061e4-ef06-4705-bc3b-fc236c757ebe.png)
 The IDP should know the IP as referrer.. Maybe you have some experience with keycloak ? And I'm missing a setting or something else..

**Comment by FabianGosebrink** [comment]
Can we confirm that this is not a bug, but a misconfiguration on the IDP Side? You have to enter the IP address if you want to allow it to be a referrer.

**Comment by ramiz4** [comment]
I have set up a new Keycloak instance using the official instructions (https://www.keycloak.org/getting-started/getting-started-docker).

In the Client details under Access settings I set the value "*" for Valid redirect URIs and Web origins. I also entered the IP address for both of them, but the result was the same.

After Keycloak was set up I tested the sample app and could see the same behavior.
When I call the app via the IP address and then click login , the following error message appears in the console:

...
home.component.ts:26 isAuthenticated: false
app.component.ts:13 [ERROR] 0-myclient - TypeError: Cannot read properties of undefined (reading 'importKey')
app.component.ts:13 app authenticated {isAuthenticated: false, errorMessage: "TypeError: Cannot read properties of undefined (reading 'importKey')", userData: null, idToken: null, accessToken: null, ...}
...
![image](https://user-images.githubusercontent.com/1623235/201280901-c0fb8b45-b817-4d57-9b5c-7fbb854cac20.png)

**Comment by ramiz4** [comment]
I created a Docker image (lokira/sample-implicit-flow-silent-renew-keycloak) with the pre-configured Keycloak instance. To start it you have to execute the following command: 
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin lokira/sample-implicit-flow-silent-renew-keycloak start-dev

After that, the app (https://github.com/ramiz4/sample-implicit-flow-silent-renew) can be started without any customization with "npm start".

User data for login in the app are: test/test

**Comment by FabianGosebrink** [comment]
We are using the `.importKey` here: https://github.com/damienbod/angular-auth-oidc-client/blob/88a16cdcc57f613c398a523267a1edd6817a79c2/projects/angular-auth-oidc-client/src/lib/validation/jwk-window-crypto.service.ts#L9

Does that help you?

**Comment by ramiz4** [comment]
@FabianGosebrink If i run the app over HTTPS (ng serve --host=0.0.0.0 --disable-host-check --ssl true) then it works via IP Address
![image](https://user-images.githubusercontent.com/1623235/201293139-57654a95-b61d-42d2-9956-f7ca9ab36399.png)

**Comment by ramiz4** [comment]
With version 12 of angular-auth-oidc-client it works without ssl

**Comment by ramiz4** [comment]
The following comment describes the same error: https://github.com/CyberSource/cybersource-flex-samples-java/issues/30#issuecomment-612154765

**Comment by damienbod** [comment]
Hi all, you need to use HTTPS and the signature validation requires this. Setup the Keycloak to run on HTTPS, then it will work, when the IDP URL matches the app. You should always develop using HTTPS anyway. 

Greetings Damien
