### ISSUE TITLE
Silent renew  problem when browser is closed or suspended

### ISSUE THREAD

**Issue by KollarM** [damienbod/angular-auth-oidc-client#158]
This is partially a problem and partially a question. 
Here is the situation:
I'm using Angular 5 SPA application with angular-auth-oidc-client version 4.0.0.
STS is IdentityServer4 hosted and maintained internally.
I'm using Implicit flow.
I have implement OidcSecurityStorage which is storing state using browser local storage (users want to sign in and stay signed in even when they close browser and open it again after some time)
IdToken expiration is set to X seconds.

Silent renew is working fine, except a scenario when browser is closed too long time, longer than the X seconds. Or the browser in mobile phone is hibernated for longer than X seconds.
Now the IDToken is expired. 
**Here I'm expecting that it will be refreshed automatically, but this is not happening**.
When I explicitly call oidcSecurityService.refreshSession(), then I'm getting two warnings:
"authorizedCallback, token(s) validation failed, resetting"
and
"#error=login_required&state=15163985770650.12328725264949791"

Are my expectations wrong?

**Comment by damienbod** [comment]
I think yes. If the token is expired, it should not be automatically refreshed. If the session is active, it will not expire.  In a lot of use cases this would be unsecure if the browser always had an active session even after the user left.

Greetings Damien

**Comment by KollarM** [comment]
Thanks Damien for your fast reply.
Actually I was looking for a setup where my AccessToken is valid for 1 hour and is refreshed every hour. But user also want to be able to close browser for longer time (few days even) open it again and refresh AccessToken. And repeat this 30 days, after 30 days something like RefreshToken will expire and AccessToken is not able to be refreshed anymore and user will be redirected to IdentityServer where he needs to put his credentials again.
Not sure if something like this possible with angular-auth-oidc-client.

**Comment by damienbod** [comment]
Then I would use a token which does not expire, or after 30 days. If you use IdentityServer4, you could use a reference token to the access_token with the OIDC Implicit Flow, and so it is possible to logout. If the user does not logout, the tokens can be reused and remain valid. 

Greetings Damien

**Comment by KollarM** [comment]
Thanks I will consider this option.
