### ISSUE TITLE
[Question]: Get customParams storageCustomParamsAuthRequest from storage data

### ISSUE THREAD

**Issue by sanjib-kumar-mandal** [damienbod/angular-auth-oidc-client#1581]
`customParams` send in the request get stored in the storage by name `storageCustomParamsAuthRequest` 
Is there any method to get this `customParams` or else suggest a way to retrieve this value

**Comment by FabianGosebrink** [comment]
You can read it from the storage not over the lib but by using the storage from the browser if you want, that should work :)
