### ISSUE TITLE
[Question]: Should CheckAuth be called again if the user logged-out and then logs back in?

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1584]
**What Version of the library are you using?**
14.1.5

**Question**
If I call the checkAuth(), and then authorize() and successfully login, then logout and I want to log back in again, do I need to call the checkAuth() again before calling authorize()?

Regards,
Fritz

**Comment by FabianGosebrink** [comment]
No, you do not need to call it. CheckAuth() method checks for values in the URL and, if there, processes them, and if not it checks, if everything is still valid, starts all the timers and returns the result. So calling it should not be a problem. But after a logout, you do not have to.
