### ISSUE TITLE
[Question]: How does checkAuthIncludingServer() work?

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1585]
**What Version of the library are you using?**
4.1.5

**Question**

I want to use the

 checkAuthIncludingServer()

and I'm somewhat confused.  Is this function to be used inside the iframe, or do I use the function outside of the iframe?  I see a window event in the silent-renew.html that I assume is to communicate with the iframe?

Regards,
Fritz

**Comment by FabianGosebrink** [comment]
You can use this function to check the auth not only in your app but also on the server. That what it is for, has nothing to do with an iframe :)

**Comment by fritzwf** [comment]
Here is what I am assuming:

1.  I configure the silent-renew.html in the iframe code
2. Outside of the iframe, I can call this.oidcSecurityService.checkAuthIncludingServer() and that will go to the server and load the state into the this.oidcSecurityService on the outside of the iframe.

So, we have two instances of the this.oidcSecurityService, one in the iframe, and one in the application outside the iframe?
 
Is this correct?

**Comment by damienbod** [comment]
This checkAuthIncludingServer() is used to call the check session spec using an iframe. I think we will make this obsolete in time and don't think we should use this in the future. iframes are getting blocked by modern browsers and these flows are problematic.

I would recommend doing a new auth request with prompt=none to check the session on the server, but this would cause a redirect. Maybe it is not possible to solve this in a clean way.

Greetings Damien

**Comment by fritzwf** [comment]
If anyone is using an iframe to process the login, I would suggest that you use the JavaScript post message() to communicate between the parent and child iframe.  It's something like a proxy.  This method let's you send messages from the parent to the iframe to call things like authorize, logout etc, and the iframe can send the authorized event to the parent when login is done. The messages are small so the overhead is negligible.
