### ISSUE TITLE
[Question]: How to load configuration dynamically during runtime in v14

### ISSUE THREAD

**Issue by AD1306** [damienbod/angular-auth-oidc-client#1586]
I'm migrating to v14 of this library where `OidcConfigService` isn't part of the library anymore. I have a use case where I'm fetching configs based on user selection i.e. my application supports user to log into multiple configs and I was able to load the config like below previously.
```
      this.oidcConfigService
            .withConfigs([oidcConfig])
            .toPromise()
            .then(() => {
               // do things here with that config i.e. checkAuth, authorize, etc.
            })
```

**Question**
How do I do the same with the v14 library. I tried to do something like this : 
```
      new StsConfigStaticLoader(oidcConfig).loadConfigs().subscribe(x => {
        // do things here
       });
```
This doesn't seem to execute. I'm not a observable expert so, if I've misunderstood the usage please let me know.  The root of the problem being how do I load configs dynamically at runtime. 

Thanks,
Aditya Dave

**Comment by FabianGosebrink** [comment]
You can not set the config at runtime anymore. However, you can load the configs at the start via HTTP and then start the app and use the configId the user has choosen (We are supporting multiple libs). Or, you can save the config, the user has chosen, save it in localstorage and do a reload of the app, then read it again and pass it into the lib.

**Comment by AD1306** [comment]
Was there a reason that was removed ? Just for the completeness of this thread.

**Comment by FabianGosebrink** [comment]
I have explained this in an issue before, let me just link that here: https://github.com/damienbod/angular-auth-oidc-client/issues/923#issuecomment-859346440 . I am not lazy to answer, it is just I would write the same again. Don't want to be unpolite :)

**Comment by AD1306** [comment]
No worries. Thank you for the help ! Appreciate it.
