### ISSUE TITLE
[Feature Request]: Provide Standalone APIs (A15)

### ISSUE THREAD

**Issue by FabianGosebrink** [damienbod/angular-auth-oidc-client#1599]

**Comment by timdeschryver** [comment]
👋 Can I help with anything here?
I'm thinking of a functional interceptor, but perhaps there are more opportunities here.

**Comment by FabianGosebrink** [comment]
Of course, you can help here, this is always appreciated. I have to dive into this a bit, but I am open for every proposal. Would also love to have a sample app to show the users how to use this lib with standalone APIs.

**Comment by timdeschryver** [comment]
@FabianGosebrink do you (or someone else) are working on an standalone example?
If that's not the case, I should have some time later to look into this if that's OK.

**Comment by FabianGosebrink** [comment]
Hey Tim, no I do not, and I don't think anybody else does. Yes, that would be nice. I think to get standalone working, we have to provide the providers array of the lib https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/auth.module.ts#L84-L145 as a method which gets exported and then used by standalone components. Not sure tho.

**Comment by FabianGosebrink** [comment]
Yes, we are planning to move and provide full standalone support. I am short on time, think it will be July, then I have time to do it. But it will come.

**Comment by FabianGosebrink** [comment]
We merged several PRs for standalone APIs, @timdeschryver did a great job there and with the next release this is gonna be released as well. Thanks!
