### ISSUE TITLE
Version for validation

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#16]
@robisim74 @FabianGosebrink 

This npm is ready now for certification. Should we bump the version to 1.0.0 to do the certifcation?

cheers Damien

**Comment by robisim74** [comment]
Awesome! I don't see in the docs that the version is relevant, or am I wrong? So we could use a minor version now (0.1.0), and release the major version (1.0.0) with the certification.

**Comment by FabianGosebrink** [comment]
Cool! Would also go with a version below 1.0.0 and do the 1.0 with the cert. Congrats!

**Comment by damienbod** [comment]
No mention of the version in the docs anywhere, but the implementation for the tests is usually given and shown on the cert page. My thinking is just that this is the first major release which will plan to do the certification. The proccess validates an exact version. I want to do semantic versioning, with major, minor and patch.

http://openid.net/certification/

**Comment by damienbod** [comment]
http://semver.org/

**Comment by robisim74** [comment]
If so, use the first major release for certification! Semantic versioning consider API and changes, not certifications.

**Comment by damienbod** [comment]
I only want to consider API changes for the versioning. If an API change result in a a major change or a breaking change, the I plan to re-certify. Opinions?

**Comment by robisim74** [comment]
Do you want re-certify on every API change? What other libraries as IdentityServer do?

**Comment by damienbod** [comment]
We will just validate version 1.0.0. No plans for anything further at the moment. Don't want to re-certify on every API change. A lot of effort... All other libs only have 1 single certification.
