### ISSUE TITLE
authorizedCallback incorrect state

### ISSUE THREAD

**Issue by Lempkin** [damienbod/angular-auth-oidc-client#160]
Hi,

In my app I use the HashLocationStrategy so I've tried the solution here : https://github.com/damienbod/angular-auth-oidc-client/issues/125 but it doesn't work for me. 
Here what I see in console : 

> {id_token: "eyJraWQiOiJDWHVwIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ…xYmN0EniT-ROhd_wwUqrvWa-1vjfQF3n6unx3GkHXE64wezBw", state: "15166429317850.016974215901399692"}
> authorizedCallback created, begin token validation
> ValidateStateFromHashCallback failed, state: 15166429317850.016974215901399692 local_state:
> authorizedCallback incorrect state
> authorizedCallback, token(s) validation failed, resetting
> 

Seems that I do get the token but state is not ok, what am I supposed to do?

I tried with this https://github.com/damienbod/angular-auth-oidc-sample-google-openid  and configure with my OpenId server (I use connect2id) but I still get the error.

**Edit** : I've noticed that : 
When i'm not logged on sso, I call 
`this.oidcSecurityService.authorize()`
 then i'm redirected on the sso, I enter login/password, then I have a second screen to authorize client : https://prnt.sc/i4gxz6
Then i'm back to my app and I got the error message in console

> authorizedCallback incorrect state

If I call 
`this.oidcSecurityService.authorize()`
a second time, i'm redirected on the sso once again, directly on the authorize client screen (as I'm already logged on the sso), and when I'm redirected back on my app, this time I don't get any error and I got the token, this.oidcSecurityService.getIsAuthorized() is true.
Any tips?

Many Thx

**Comment by Lempkin** [comment]
I tried with this https://github.com/damienbod/angular-auth-oidc-sample-google-openid  and configure with my OpenId server (I use connect2id) but I still get the error

**Comment by damienbod** [comment]
Hi @Lempkin It something to do with how you handle the authorization callback. When the authorize method is called, it saves a state. Then when the callback is returned, the state is checked. If the authorize is called twice beofre the callback, you get these errors

Make sure the authorize is called only once.

I never used HashLocationStrategy, will creatre a test, demo for this. 

Greetings Damien

**Comment by Lempkin** [comment]
Hi, thx for your answer.
I think you missunderstand what I said, I have the error when I call authorize only once.

**Comment by damienbod** [comment]
@Lempkin Sorry, I'll look into this

**Comment by Lempkin** [comment]
Hi, more informations about my problem : 
In my app.component I have : 

```
constructor() {
if (this.oidcSecurityService.moduleSetup) {
      this.doCallbackLogicIfRequired();
    } else {
      this.oidcSecurityService.onModuleSetup.subscribe(() => {
        this.doCallbackLogicIfRequired();
      });
    }

    this.router.events.filter((event: any) => event instanceof NavigationStart)
      .subscribe((data: NavigationStart) => {
        if (data.url == "/access_token") {
          console.info("hash!");
          this.hash = window.location.hash;
          this.router.navigate([]);
        }
      });
}


private doCallbackLogicIfRequired(): void {
    const hash = this.getTokenHash();
    if (hash) {
      this.oidcSecurityService.authorizedCallback(hash);
    }
  }

  private doCallbackLogicIfRequired() {
    console.info("doCallbackLogicIfRequired");
    if (window.location.hash) {
      this.oidcSecurityService.authorizedCallback();
    }
  }
```

What I see is that doCallbackLogicIfRequired() is always called before the router.event is thrown, so the  `this.hash = window.location.hash;` is always done too late

**Comment by Lempkin** [comment]
I've tried to debug a little, and in your code here : 

```
var OidcSecurityService = /** @class */ (function () {
    /**
     * @param {?} platformId
     * @param {?} oidcDataService
     * @param {?} stateValidationService
     * @param {?} authConfiguration
     * @param {?} router
     * @param {?} oidcSecurityCheckSession
     * @param {?} oidcSecuritySilentRenew
     * @param {?} oidcSecurityUserService
     * @param {?} oidcSecurityCommon
     * @param {?} oidcSecurityValidation
     * @param {?} tokenHelperService
     * @param {?} loggerService
     */
    function OidcSecurityService(platformId, oidcDataService, stateValidationService, authConfiguration, router, oidcSecurityCheckSession, oidcSecuritySilentRenew, oidcSecurityUserService, oidcSecurityCommon, oidcSecurityValidation, tokenHelperService, loggerService) {
        this.platformId = platformId;
        this.oidcDataService = oidcDataService;
        this.stateValidationService = stateValidationService;
        this.authConfiguration = authConfiguration;
        this.router = router;
        this.oidcSecurityCheckSession = oidcSecurityCheckSession;
        this.oidcSecuritySilentRenew = oidcSecuritySilentRenew;
        this.oidcSecurityUserService = oidcSecurityUserService;
        console.info("-----", oidcSecurityCommon);
        this.oidcSecurityCommon = oidcSecurityCommon;
```


First time that I'm redirected from sso to my app oidcSecurityCommon.authStateControl il empty, that's what leads to error that I see in console.
Then I run authorize() a second time and this time oidcSecurityCommon.authStateControl contains value, which is === result.state and that's why I don't get error anymore.

But I have no idea why it's empty the first time, can it be because of some configuration?
Here the json that I use : 

```
{
    "stsServer": "http://127.0.0.1:8080/c2id/",
    "redirect_url": "https://127.0.0.1:8443/hsmt-front/",
    "client_id": "tlhyy2m635qwu",
    "client_secret": "VOXiYgR6lMIobQ8A9AqTLw_ZkiREVCrcvywjWzvocs8",
    "response_type": "id_token token",
    "scope": "openid profile email",
    "post_logout_redirect_uri": "https://localhost:8443/hsmt-front/",
    "start_checksession": false,
    "silent_renew": true,
    "registration_access_token": "qkkyrW4zkPZ5KrCRhN_hRZSqVnO4Dp9CPwwmmxU0K18.Kg",
    "forbidden_route": "https://127.0.0.1:8443/hsmt-front/",
    "unauthorized_route": "/home",
    "log_console_warning_active": true,
    "log_console_debug_active": true,
    "max_id_token_iat_offset_allowed_in_seconds": "30"
}
```

**Comment by Lempkin** [comment]
@damienbod I try to find in your code where is the sessionStorage.authStateControl set. I've tried to print it in the console to check why it's null the first time I come back from sso, and not the second time, but it seems that second time it's already set when your code is run.

**Comment by Lempkin** [comment]
@damienbod  ok I may have an idea about what's going on. I see that you set the state and nonce in the authorize() method, which works, but as soon as I reach the connect2id login form, the sessionStorage is empty. OIDC url used for login is : 
http://127.0.0.1:8080/c2id-login/login?client_id=tlhyy2m635qwu&redirect_uri=https:%2F%2F127.0.0.1:8443%2Fhsmt-front%2F&response_type=id_token%20token&scope=openid%20email&nonce=N0.130903925399014521517313427428&state=15173131751260.6921374475821616&authSessionId=iiV4VjFVyGDaWXBGfEOqr0cOqU-XKpmg_mW3kf0LNto.

That's why when I'm redirected in my app state validation is KO.
Any idea about why the sessionStorage is empty?

**Comment by Lempkin** [comment]
Ok I finally found out what's going on. Problem was that I use to load my website with localhost:8080 and connect2id accepts only 127.0.0.1 for redirect_uris declaration. And as you use sessionStorage, on the first sso redirection my sessionStorage was obviously emtpty.
Sorry for the inconvenience then, and good job for library :)

**Comment by damienbod** [comment]
@Lempkin thanks

**Comment by Joseph7695** [comment]
How did you solved the issue ?
