### ISSUE TITLE
How to force checkAuth getting new tokens

### ISSUE THREAD

**Issue by schoes** [damienbod/angular-auth-oidc-client#1605]
hello there i would like to use the checkAuth for a special config. But i don't know how to use the lib becaus there need to bee an url as first parameter and i don't know what to fill in there. i did not fin any examples on how to use it. can you help me out ?

**Comment by FabianGosebrink** [comment]
You can check the docs, you can pass the configId as a parameter: https://angular-auth-oidc-client.com/docs/documentation/public-api#checkauthurl-string-configid-string

**Comment by schoes** [comment]
Yes i know that but when i don't set an url nothing happens

**Comment by FabianGosebrink** [comment]
So you're passing "null" as an url and nothing happens? What version are you using?

**Comment by schoes** [comment]
14.1.5
The code is inside a guard and looks like.
 `this.oidService.checkAuth(null, OAuthConfig.SwissId).pipe(
            tap((oidResponse) => console.log('OID Response:', oidResponse)),
            switchMap((oidResponse) =>
                oidResponse.isAuthenticated
                    ? this.swissIdService.verifySwissIdToken(oidResponse.userData?.cnumber, oidResponse.idToken)
                    : throwError(() => new Error('swiss.id.connection.failed'))
            ),
            map(() => this.router.createUrlTree([RoutePath.Account])),
            catchError((error: unknown) => {
                console.log(error);
                return of(this.createErrorUrlTree());
            })`

**Comment by FabianGosebrink** [comment]
Are you subscribing? This can not be seen from the code sample.

**Comment by FabianGosebrink** [comment]
And with `nothing happens` you mean that you do not even run into to" tap((oidResponse) => console.log('OID Response:', oidResponse)),", right?

**Comment by schoes** [comment]
yes exactly

**Comment by FabianGosebrink** [comment]
How does your config look like? How does the guard look like? Do you have a sample where we can reproduce the issue?

**Comment by schoes** [comment]
i changerd now the config tha i got only one auth config but now when call the checkAuth method twice the tokens won't get refreshed. what do i need to do so that the tokens get refrreshed because i know that there was an update ind the id_token and i need to get this update
First check Auth that works: 
`canActivate(next: ActivatedRouteSnapshot): Observable<UrlTree> {
        const { language } = next.queryParams;
        return this.oidcSecurityService.checkAuth().pipe(
            switchMap((oidResponse) =>
                oidResponse.isAuthenticated
                    ? this.accountService.getLoggedInAccount().pipe(
                          tap((user) => DynatraceUtils.setUserId(user.loginId)),
                          tap((user) => this.setUserLanguage(user, language)),
                          map(() => this.router.createUrlTree([RoutePath.Account]))
                      )
                    : of(this.createErrorUrlTree())
            ),
            catchError(() => of(this.createErrorUrlTree()))
        );
    }`

second checkAuth that is not triggereing the token refresh
`canActivate(): Observable<UrlTree> {
        this.oidService.getAuthenticationResult().subscribe((result) => console.log(result));
        this.store.dispatch(verifySwissIdToken());
        return this.oidService.checkAuth(`${location.origin}/b2c-useraccount/${RoutePath.SwissIdCode}`).pipe(
            switchMap((authenticationResponse) => {
                if (authenticationResponse.isAuthenticated) {
                    return this.handleSwissIdConnection(authenticationResponse);
                } else {
                    this.store.dispatch(connectSwissIdFailed());
                    of(this.createErrorUrlTree());
                }
            }),
            catchError(() => of(this.createErrorUrlTree()))
        );
    }`

**Comment by schoes** [comment]
i think it is a timing issue when the checkAuth refreshes the tokens.

**Comment by schoes** [comment]
By the way here is my config of the module
`{
                    configId: OAuthConfig.B2C,
                    authority: IDP_ENDPOINT_HOST[appConfig.environment],
                    authWellknownEndpointUrl: IDP_ENDPOINT_HOST[appConfig.environment],
                    redirectUrl: `${location.origin}/b2c-useraccount/${RoutePath.AcceptCode}`,
                    clientId: CLIENT_ID[appConfig.environment],
                    scope: SCOPE,
                    responseType:'code',
                    silentRenew: true,
                    useRefreshToken: true,
                    autoUserInfo: false,
                    logLevel: environment.production ? LogLevel.None : LogLevel.Debug,
                    customParamsAuthRequest: {
                        claims: JSON.stringify({
                            id_token: {
                                acr: null,
                                cnumber: null,
                                ['swissid.sub']: null,
                                ['swissid.acr']: null
                            }
                        })
                    }
                } as OpenIdConfiguration`

**Comment by FabianGosebrink** [comment]
Have you trief using the `isAuthenticated$` result as described here https://angular-auth-oidc-client.com/docs/documentation/guards ?

**Comment by schoes** [comment]
I use the autologin mechanism with the AutoLoginPartialRoutesGuard  And do a checkauth in de guard mentioned On 25 Nov 2022, at 18:02, Fabian Gosebrink ***@***.***> wrote:﻿
Have you tried using the isAuthenticated$ result as described here https://angular-auth-oidc-client.com/docs/documentation/guards ?

**Comment by FabianGosebrink** [comment]
Okay, but you have to call `checkAuth()` initially as well, when coming back from the IDP. The URL needs to be processed.

**Comment by schoes** [comment]
Ok I have two different guars that will be activated when getting back from the IDP and these guards do call the checkAuth in the first guard the checkAuth works and when I navigate to the second guard there the checkAuth does not trigger the refresh of all tokens. Do I need to paste any code snippet to be clearer?On 27 Nov 2022, at 12:26, Fabian Gosebrink ***@***.***> wrote:﻿
Okay, but you have to call checkAuth() initially as well, when coming back from the IDP. The URL needs to be processed.

**Comment by FabianGosebrink** [comment]
You do not need to refresh the tokens by calling `checkAuth()`. The tokens are not refreshed by calling `checkAuth()`. Can you provide a sample repo? You can use one of the configs we have in our samples. Thanks!

**Comment by schoes** [comment]
Will create a repo as soon as possible.

**Comment by FabianGosebrink** [comment]
Nice, thanks. Then we can have a look, thanks!

**Comment by schoes** [comment]
so i tried to create a sample repo to show you what we would like to do the auth.  [https://github.com/schoes/angular-oidc-check-auth](check-auth-sample). hope you can understand what I would like to do. otherwise just ask. thanks for your help

**Comment by FabianGosebrink** [comment]
Hey thanks! That helps. Out of your comment

> // here should the id token be adapted with the changes we made while we were at the IDP and it does not happen here

I assume you are logging in, changing something in the IDP and then want to have this changes being reflected in the ID Token, is that correct?

**Comment by schoes** [comment]
Yes that's correct

**Comment by FabianGosebrink** [comment]
So the ID Token is bound to the login. To the session as long as it runs. So if you need a _new_ ID token, you have to log in again. You can not force the changes being reflected, neither with a token refresh (automatically done with the lib) nor with another call to `checkAuth()`. `checkAuth()` does _not_ refresh the token. It "only" sets up the timers to do so based on your config. So you have to log out and login again to see the changes you made on your IDP to see them in the ID token.
