### ISSUE TITLE
[Question]: Support for DPoP

### ISSUE THREAD

**Issue by rgraham7503** [damienbod/angular-auth-oidc-client#1606]
Hi just curious if you will support DPoP? This is picking up some steam in open banking and will be a standard in the near future.
Here is a well written article on it if you are not familiar. (I didnt write this btw and I am not promoting anyone)
[medium DPoP article](https://darutk.medium.com/illustrated-dpop-oauth-access-token-security-enhancement-801680d761ff)

**Comment by damienbod** [comment]
Hi @rgraham7503 It is not possible to support this as an Angular application runs in the browser and cannot keep a secret
