### ISSUE TITLE
[Question]: Should closing a login popup manually return an unauthenticated result?

### ISSUE THREAD

**Issue by mladewski** [damienbod/angular-auth-oidc-client#1617]
**What Version of the library are you using?**
15.02

**Question**
Should closing a login popup manually return an unauthenticated result?
Currently when I manually close the popup, I am not getting an unauthenticated observable result, thus there is an orphaned open subscription.  I could probably unsubscribe manually when attempting to re-authenticate.  Just curious the expected behavior.
Thanks,

**Comment by FabianGosebrink** [comment]
When you close the login popup, a message should be sent with "user closed" and you get back an unauthenticated result. https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/login/popup/popup-login.service.ts#L54

**Comment by mladewski** [comment]
got it thanks!
