### ISSUE TITLE
Implementation of registration

### ISSUE THREAD

**Issue by Aeseir** [damienbod/angular-auth-oidc-client#162]
Hi

I'm looking to improve of my registration component and was wondering if the package has anything built into it to help with this.

Rationale is that login component will capture the URL and pass it to the identity server for call back and further actions.
There is no similar item for register component but identity server accepts same parameters.

Is there a way to extend the login component but have it direct to registration page of identity server so that post registration it executes on the callback and other processes?

**Comment by damienbod** [comment]
@Aeseir Hi @Aeseir This logic belongs to the OIDC server. For example IdenityServer4 supports this in its examples.

Greetings Damien

**Comment by Aeseir** [comment]
Hi @damienbod 

Are you saying that when user triggers oidc.authorize() function, it takes it to ID4 login and then ID4 server collates the parameters?

_i.e._ 
**localhost:5000/account/login is triggered by authorize()** 
then id4 converts it to
**localhost:5000/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Da-client%26redirect_uri%3Dhttp%253A%252F%252F192.168.0.8%253A5003%252Fcallback%26response_type%3Did_token%2520token%26scope%3Dopenid%2520api1%2520profile%26nonce%3DN0.037105830639998061517896719755%26state%3D15178967193440.21482273263435747**

**Comment by damienbod** [comment]
No, the angular Application creates the URL and this is then handled by the IdentityServer4 which then displays the view as required. You can change, edit and do anything with the view.

Greetings Damien

**Comment by Aeseir** [comment]
Thanks Damien, that is what i thought.

I've read through the angular-auth-oidc-client docs but i cannot see any ability to configure registration or function that takes user to registration page (equivalent to authorize()).
Have a missed something somewhere?

**Comment by damienbod** [comment]
@Aeseir No, registration is not part of this. I usually use the ASP.NET Core Identity examples and adopt these for the registration part of a application. dotnet 2.1 is bring out a whole new UI Identity add on.

Greetings Damien
