### ISSUE TITLE
[Question]: Token not fetched after login stage

### ISSUE THREAD

**Issue by AD1306** [damienbod/angular-auth-oidc-client#1623]
**What Version of the library are you using?**
`^14.1.5` 

**Question**
After I login into IDP, the app doesn't get the token i.e. there is no user data after I've logged into IDP. Is there something wrong I am doing here with the usage ?  This is a fresh application. 

`app.component.ts`

```
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { lastValueFrom } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'auth-test';
  constructor(private router: Router, private oidcSecurityService: OidcSecurityService) {}
  async ngOnInit() {
    const loginResponse = await lastValueFrom(this.oidcSecurityService.checkAuth('main'));
    console.log(loginResponse); ---------> this doesn't return token after i've logged in. 
  }

  async authorize() {
    this.oidcSecurityService.authorize('main');
  }
}
```

`app.component.html`

```
<router-outlet></router-outlet>
<p>before-login page!</p>
<button (click)="authorize()">Login</button>
```

`app.module.ts` (I'm just to copy the imports for this section, the config is actually taken from sample codebase, I have my own to test against with the same behaviour)

```
imports: [
    BrowserModule,
    AppRoutingModule,
    AuthModule.forRoot({
      config: {
        configId: 'main',
        authority: 'https://login.microsoftonline.com/7ff95b15-dc21-4ba6-bc92-824856578fc1/v2.0',
        authWellknownEndpointUrl: 'https://login.microsoftonline.com/common/v2.0',
        redirectUrl: window.location.origin,
        clientId: 'e38ea64a-2962-4cde-bfe7-dd2822fdab32',
        scope: 'openid profile offline_access email api://e38ea64a-2962-4cde-bfe7-dd2822fdab32/access_as_user',
        responseType: 'code',
        silentRenew: true,
        maxIdTokenIatOffsetAllowedInSeconds: 600,
        issValidationOff: true,
        autoUserInfo: false,
        // silentRenewUrl: window.location.origin + '/silent-renew.html',
        useRefreshToken: true,
        logLevel: LogLevel.Debug,
        customParamsAuthRequest: {
          prompt: 'select_account', // login, consent
        },
      }
    }),
]
```

**Additional Information**
- I'm running on Port 4200, which is a authorized redirect path too. 
- I do not see anything related to failures of any kind when I set the `logLevel` to `LogLevel.Debug`. Refer to the screenshot. 
![screenshot-oidc](https://user-images.githubusercontent.com/20426450/205649686-88255741-9946-44fd-b233-c7c7fafa3d6a.png)

Let me know if there's any additional information I can provide.

**Comment by FabianGosebrink** [comment]
IIRC you can not await observables. You have to convert them to a promise. But not sure, maybe I am wrong. Can you give that a shot?

**Comment by AD1306** [comment]
Nope that didn't work out. FWIW I'm using the [lastValueFrom](https://rxjs.dev/api/index/function/lastValueFrom) as `toPromise()` is deprecated with the newer RxJS version based on this [documentation](https://rxjs.dev/deprecations/to-promise).

**Comment by AD1306** [comment]
no luck with `firstValueFrom()`. Thats the problem it logs I'm not authenticated but if you see the screenshot closely you'll see there is a redirect to `http://localhost:4200/?code=EDDC....` which we normally get after the user has logged in. 
![image](https://user-images.githubusercontent.com/20426450/205665106-31478f7d-00f9-4ebb-80bc-245657538b3e.png)

**Comment by FabianGosebrink** [comment]
Yes, then the code gets exchanged, and this is not going well for some reason.

**Comment by AD1306** [comment]
let me setup a github repo for you and update you so, you can better view at it.

**Comment by FabianGosebrink** [comment]
You can use one of our configs, if you want.

**Comment by AD1306** [comment]
Here is the github repository : https://github.com/AD1306/angular-auth-oidc-debug. `README.md` should have all the information you'll need hopefully. Let me know if you need anything else from me. I am using one of your configs and was able to reproduce the issue so, hopefully it'll be easier to debug.

**Comment by AD1306** [comment]
@FabianGosebrink , are you able to reproduce the issue now on your end ?

**Comment by FabianGosebrink** [comment]
![image](https://user-images.githubusercontent.com/11268349/205837550-8ac0daec-8911-427d-8a7f-7d1bea25506f.png)

Hey, just give me some time ;) This was just one hour...

**Comment by FabianGosebrink** [comment]
Easy, all good. I will test it and come back when I have found out something. Thanks to you for providing a sample repo so quick :)

**Comment by FabianGosebrink** [comment]
What credentials should I use for login? You got any test account?

**Comment by AD1306** [comment]
@FabianGosebrink any update on this request ? Were you able to reproduce this on your end ?

**Comment by FabianGosebrink** [comment]
I could reproduce the issue but do not see any error. I would tend to say this is a server configuration thing. Can you see if @damienbod has some article for you here? https://damienbod.com/category/azure/azure-b2c/ @damienbod  can you help?

**Comment by damienbod** [comment]
Hi @AD1306 

If you are using B2C can you compare to this? 

https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/sample-code-flow-azure-b2c/src/app/auth-config.module.ts#L6-L25

Are you using B2C? 

If not compare to the Azure AD example.

Azure AD and Azure AD B2C are 2 different IDPs and have different requirements.

To get an access token, your configuration looks correct.

Greetings Damien

**Comment by AD1306** [comment]
@damienbod  I am using azure B2C in my local config. The sample repository I provided is also picked from one of your sample configs. I am using https://github.com/AD1306/angular-auth-oidc-debug/blob/main/src/app/app.module.ts#L18

**Comment by AD1306** [comment]
@FabianGosebrink  this happens in v15 too FWIW. I just tried it. Let me know if you'd like to see the same code.

**Comment by aylmercarson** [comment]
i'm having a similar issue with v15. i log in, no errors, then i'm left with:

codeVerifier: "68d3a7a25d4719f03b6834427c06fac9c96b0317a51fac6770283d955f1cRoUl0du"
...
storageCodeFlowInProgress: "{\"state\":\"in progress\"}"

**Comment by grozandrei** [comment]
I am encountering the same situation, token is not fetched after login (sometimes only after I call 3rd or 4th time `oidcSecurityService.authorize()` function).

**Comment by AD1306** [comment]
alright finally I was able to resolve this issue. Seems like I need to call `checkAuth` with `url` params i.e. the current call is 
```
 const loginResponse = await lastValueFrom(this.oidcSecurityService.checkAuth('main'));
``` 

should be changed to 
```
const loginResponse = await lastValueFrom(this.oidcSecurityService.checkAuth(window.location.href, 'main'));
OR 
const loginResponse = await lastValueFrom(this.oidcSecurityService.checkAuth(null, 'main'));
```
Because the earlier call was not passing in a `configId` instead it was passing the `url` param. Closing this as this is now resolved.
