### ISSUE TITLE
[Question]: How can I inject Basic Auth into the token request header?

### ISSUE THREAD

**Issue by ArmyaAli** [damienbod/angular-auth-oidc-client#1624]
Hi Folks,

I am using this library for work and I am wondering if it is possible to inject a Header for the /token call in the code flow. Our auth provider needs this header and I have been going through the documentation and could not find it! Apologies if it is there but please point in the right direction! 

EDIT: I also noticed that there is a request interceptor feature that is not in the documentation. potentially for me?

Thanks,

Ali

**Comment by FabianGosebrink** [comment]
So there are interceptors, but this is not a feature of this lib, but a feature of angular. [HttpInteceptors on angular.io](https://angular.io/api/common/http/HttpInterceptor). You can use this to add a header if you want.

**Comment by ArmyaAli** [comment]
Thanks Fabian, I'm working on finding a solution for this.. maybe adding custom headers should be a configuration option for the public interface of this library !! Thank you for your response
