### ISSUE TITLE
Cannot read property 'stsServer' of undefined

### ISSUE THREAD

**Issue by neildonkin** [damienbod/angular-auth-oidc-client#163]
I'm using this technique to retrieve sts server config, as shown in your sample code:
```
export function loadConfig(oidcConfigService: OidcConfigService) {
  console.log('APP_INITIALIZER STARTING');
  return () => oidcConfigService.load_using_stsServer('http://localhost:550');
}
```
The exception is thrown on this line:
```
this.oidcConfigService.onConfigurationLoaded.subscribe(() => {

        const openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
        openIDImplicitFlowConfiguration.stsServer = this.oidcConfigService.clientConfiguration.stsServer;
```
I can see the config data is returned from the sts, but for some reason the `clientConfiguration ` property is `undefined`.

I'm using an IdentityServer4 sts.  Could this be because my sts url is not using ssl?

**Comment by damienbod** [comment]
The clientConfiguration configuration is undefined because you don't load any settings for your application, just the well known endpoints. Your STS URL is http://localhost:550, so you can set the openIDImplicitFlowConfiguration.stsServer value to this value because it is fixed. 

Greetings Damien

**Comment by neildonkin** [comment]
Thanks for your response @damienbod.

I am confused.  Your sample code using [load_using_stsServer](https://www.npmjs.com/package/angular-auth-oidc-client) makes it appear that you only have to specify the sts url as an argument and the `clientConfiguration` is fully-populated in the `onConfigurationLoaded.subscribe` function.

I will just continue to use the code without the `APP_INITIALIZER` because this is working fine, but it would have been nice to retrieve the sts config from the sts server itself.

Thanks for a great library 👍
