### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by kiranpurelli** [damienbod/angular-auth-oidc-client#1631]
Hi,

**Background**: Refreshing the token in the background after the current token expiration without any interruption

Facing issue when generating refresh token. We are using Azure Ad authentication which is returning the token and the refresh token as well. To retrieve the refresh token, we are calling the getRefreshToken() in angular-auth-oidc-client.js but it is returning undefined from that library. We also tried to use the silent renew option as well but not able to see the token is refreshing after the token expiration.

**Technical Stack** 
Angular 11.2.14
Angular-auth-oidc-client - 10.0.15
Node: 14.16.1

Please advise how to go forward for the above scenario.

Thanks
Kiran

**Comment by FabianGosebrink** [comment]
Can you update to the latest version?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Comment by kiranpurelli** [comment]
We have updated the angular version to 14, yet we were not able to achieve this functionality, could you please help us in providing some documents or insights for the below issue. We want to achieve the following functionality. for now, the access token is valid for an hour and if the user is still active for an hour and wants to continue after that .. we need to authorize the session without any user interaction. (Currently the token is valid for 1 hour and if the user is still making some changes after the token expiration, we are getting 401 Unauthorized.)
