### ISSUE TITLE
[Bug]: LogLevel.Debug not working

### ISSUE THREAD

**Issue by thatsmeta** [damienbod/angular-auth-oidc-client#1645]
### Version

15.0.2

### Please provide the exception or error you saw

```true
I'm trying to debug the token refresh process but I cannot see any debug messages.
```

### Steps to reproduce the behavior

```true
Set `logLevel: LogLevel.Debug` in AuthModule config.
```

### A clear and concise description of what you expected to happen.

```true
I exected debug messages to be visivle in the browser console.
```

**Comment by FabianGosebrink** [comment]
Have you started a sample and taken a look if you can reproduce it with one of the samples? Do you have a filter in your console?

**Comment by thatsmeta** [comment]
Ha, I feel a bit stupid now, had a filter in my console.
