### ISSUE TITLE
[Question]: How can I trigger the token expiration early for my web app so that I can test the redirect URLs for auto-logout when token expires? 

### ISSUE THREAD

**Issue by Omega-Zero** [damienbod/angular-auth-oidc-client#1646]
How can I trigger the token expiration early for my web app so that I can test the redirect URLs for auto-logout when token expires? 
 I've fiddled with a couple variables in my config(such as silentRenewTimeoutInSeconds) , but none seem to trigger the correct redirect URL. Am not sure if I am using incorrect approach/config or if perhaps my redirect URL is wrong and am not sure how to test besides waiting a full hour + for the stock expire_in condition to be met.

Thank you in advance-

![Capture](https://user-images.githubusercontent.com/36581543/210849302-53acf8cd-9d81-4155-9946-da116dcafd58.PNG)

**Comment by timdeschryver** [comment]
I don't know if this helps, but...
Can you change the token on the server side, this would be the easiest way and gives you the most confidence.
Another option that you could try is to advance the time on your machine (advance it by one hour).

**Comment by Omega-Zero** [comment]
Unfortunately I do not have access to server side token variables.
The time advance on my local machine is a great attempt at a workaround- thanks for recommending it. However, when attempting to trigger the redirect URL while toggling a couple config variables, it did continued to hit the stock unauthorized screen or did not recognize the time change.

**Comment by benthieu** [comment]
In the `Application`-> `Session Storage` you should have your current auth-state. You could modify the property `refresh_token` to something outdated (or just a wrong token) and set the `access_token_expires_at` property to something in the past. Then reload the page
