### ISSUE TITLE
Unhandled error when Auth server isn't running/responding

### ISSUE THREAD

**Issue by Ibro** [damienbod/angular-auth-oidc-client#165]
It would be nice to allow the angular application to be able to deal with this. One could simply show an error inside of an application or do something totally custom.

> Failed to load resource: net::ERR_CONNECTION_REFUSED
> ERROR TypeError: Failed to fetch

**Comment by damienbod** [comment]
@Ibro I'll add a error meassge to the logs, thanks for reporting

**Comment by damienbod** [comment]
fix: https://github.com/damienbod/angular-auth-oidc-client/pull/171

**Comment by Ibro** [comment]
Awesome, thanks @damienbod  !
