### ISSUE TITLE
[Question]: How can I configure the library with keycloak?

### ISSUE THREAD

**Issue by giafar** [damienbod/angular-auth-oidc-client#1650]
**What Version of the library are you using?**
15.0.2

**Question**
I have to integrate Keycloak, version 20.x, but I have to configure a client secret but seamts it is not supported by the library: could you please share docs to integrate the library with Keycloack ?

Thanks in advance.

**Comment by fritzwf** [comment]
Can I use this configLoaderFactory for multiple configs?
