### ISSUE TITLE
[Question]: login in a nav component. how can the rest of the app see the results without reloading the whole thing?

### ISSUE THREAD

**Issue by aylmercarson** [damienbod/angular-auth-oidc-client#1651]
**What Version of the library are you using?**
"angular-auth-oidc-client": "15.0.2",

**Question**
i have a login button in a nav component, which sits in the app component:

```
< app-nav>< /app-nav >
< router-outlet>< /router-outlet >
< app-footer>< /app-footer >
```

the code to login by popup is in the nav.ts file:
```
  loginWithPopup(configId: string) {
    this.oidcSecurityService
      .authorizeWithPopUp(undefined, undefined, configId)
      .subscribe(({ isAuthenticated, userData, accessToken, errorMessage }) => {
        console.log(isAuthenticated);
        console.log(userData);
        console.log(accessToken);
        console.log(errorMessage);
        this.isAuthenticated = isAuthenticated;
      });
  }
```
no other component seems able to get the result of the login. for example, in the home component, i have:
```
  ngOnInit() {
    this.oidcSecurityService.isAuthenticated().subscribe(( isAuthenticated ) => {
      this.isAuthenticated = isAuthenticated;
    });
```
this is always false unless i reload the app. i can see that the login definitely succeeds. i get a token etc back from azure b2c. even a guard i have can't get the result:
```
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
    return this.oidcSecurityService.isAuthenticated$.pipe(
      map(({ isAuthenticated }) => {
        // allow navigation if authenticated
        if (isAuthenticated) {
          return true;
        }
        // redirect if not authenticated
        return this.router.parseUrl('/home');
      })
    );
  }
}
```
i really don't want to have to force an app reload after logging in. what am i missing? anyone any thoughts?

FWIW: when i logout using a button in the navbar, that event percolates throughout the app ok, using:
```
  logout() {
    this.oidcSecurityService.logoff().subscribe((result) => console.log(result));
  }
```

**Comment by FabianGosebrink** [comment]
I would call a service from the nav component and spread the event when the login succeeds. Try `this.oidcSecurityService.isAuthenticated$` outside a guard. Guard is only triggered on route change to the route.

**Comment by aylmercarson** [comment]
thanks, i'll have a look at that. 
re the guard, it's triggered when i call a protected test page via a router call. still gives unauthenticated:

 { path: 'protected', component: ProtectedComponent, canActivate: [TestGuard], }

**Comment by aylmercarson** [comment]
that does it, thanks very much. and subscribing to the service in the guard contructor gets the correct value.
