### ISSUE TITLE
[Question]: How can I use the library in a new pop-up window ? 

### ISSUE THREAD

**Issue by JoSeTe4ever** [damienbod/angular-auth-oidc-client#1654]
**What Version of the library are you using?**
.."15.0.2",.

**Question**
How can I use the library in a pop-up ? 

After updating from version 14 to version 15, the method  this.oidcSecurityService.checkAuth() is always returning a null object due to this change of better pop-up handling: 

https://github.com/damienbod/angular-auth-oidc-client/commit/165941ca4d8ee4d334beccd6e4a7fafc5069a87c

Due to some bussiness requirements, I would need to use this functionality in a pop-up (or new tab...) is there anything I can do?

Thank you in advance !

**Comment by FabianGosebrink** [comment]
Hey, do you mean login with a popup? Greetings.

**Comment by JoSeTe4ever** [comment]
Hello @FabianGosebrink  

thank you very much for your response. In my use case, I need to run my angular application in a new window that appears as a pop-up, and need to use the library checkAuth() method in this new pop-up window. 

I think the problem is this change from version 15

`  if (this.popupService.currentWindowIsPopUp()) {
      alert('I AM IN POPUP');
      this.popupService.sendMessageToMainWindow(currentUrl);

      return of(null);
      // return of({ isAuthenticated: false, errorMessage: null, userData: null, idToken: null, accessToken: null, configId });
    }`
    
    For some reason, I guess because I am runing in a pop-up,  returning null as the LoginResponse does not me allow to either checkAuth or Authorize using the library ...
    
    Is there something I can do? 
    
    
    Thank you in advance.

**Comment by NeutralAngel** [comment]
I am having the same issue.

We are calling ```this.oidcSecurityService.checkAuth()``` from within ```app.component.ts```. 

If the application is opened via entering the url in the browser it works fine. The ```AutoLoginPartialRoutesGuard``` on the route sends them to our Authentication provider and then when they are redirected back to our app the observable emits a ```LoginResponse``` and the user is properly redirected to the appropriate location.

However, if the application is opened via ```window.open('example.com')``` then after they visit the Authentication provider and return to our app, ```this.oidcSecurityService.checkAuth()``` returns ```null``` and no redirect occurs.

This seems to be because ```document.defaultView.opener``` returns a value and no longer checks for ```popupauth``` in session storage and causes ```isCurrentlyInPopup()``` to return true.

**Comment by FabianGosebrink** [comment]
I am thinking of a way to distinguish between "popup for an app" and "popup for authentication".

**Comment by NeutralAngel** [comment]
Was that not the reason for ```popupauth``` in session storage previously?

BTW, thank you for responding and for maintaining this excellent library. :)

**Comment by hallidev** [comment]
@FabianGosebrink I'm having the same problem, and although an old issue, it's the same symptom seen here:

https://github.com/damienbod/angular-auth-oidc-client/issues/983

I'm doing the same thing as the others in this thread:

window.open('https://something.com', '_blank');

Where "something.com" is my own site. When ```checkAuth()``` gets called, ```loginResponse``` is null.

As @NeutralAngel said - wasn't that handled previously with ```popupauth``` in session storage?

**Comment by FabianGosebrink** [comment]
Yes, I think we have to do this. But I am short on time currently :(

**Comment by hallidev** [comment]
@FabianGosebrink I understand. Would you be willing to accept a PR? I looked and it wasn't clear if you were accepting new contributors.

**Comment by FabianGosebrink** [comment]
Oh we absolutely do accept PRs! I am happy to review :)

**Comment by hallidev** [comment]
@FabianGosebrin - I worked with my colleague @bclementfidx and he put together a PR. Please let me know if you have any feedback. Thanks!

**Comment by hallidev** [comment]
Hi @FabianGosebrink. Any chance you could take a peek at @bclementfidx's PR? It would be great to get this merged in as it's a blocker for us. Really appreciate it!

**Comment by FabianGosebrink** [comment]
Hey, which PR you're referring to? Unsure.

**Comment by hallidev** [comment]
Oh man I'm sorry, I didn't even notice! Apologies

**Comment by FabianGosebrink** [comment]
All good :) Thanks for writing here and asking!
