### ISSUE TITLE
[Question]: Request for shorter lived token?

### ISSUE THREAD

**Issue by makandre** [damienbod/angular-auth-oidc-client#1656]
**What Version of the library are you using?**

`12.0.3`

**Question**

I'm using the authorization code flow.  Is there a way to request for a token with a shorter expiry time than what my auth server (Dex) normally gives out?

Thanks.

**Comment by damienbod** [comment]
The server needs to set this and the client cannot dynamically request this as part of the spec. You could add custom logic for this if you control both parts, greetings Damien
