### ISSUE TITLE
[Question]: where to put CheckAuth() and what parameters to use?

### ISSUE THREAD

**Issue by aylmercarson** [damienbod/angular-auth-oidc-client#1657]
What Version of the library are you using?
"angular-auth-oidc-client": "15.0.2",

Question
following on from a previous question...i have signin & signup buttons in a nav component, which sits in the app component:

< app-nav>< /app-nav >
< router-outlet>< /router-outlet >
< app-footer>< /app-footer >

the functions to login + signin by popup are in the nav.ts file. eg:

  loginWithPopupClient(configId: string) {
    this.oidcSecurityService
      .authorizeWithPopUp(undefined, undefined, configId)
      .subscribe(({ isAuthenticated, userData, accessToken, errorMessage }) => {
        console.log(isAuthenticated);
        console.log(userData);
        console.log(accessToken);
        console.log(errorMessage);
        this.isAuthenticated = isAuthenticated;
      });
  }

where should i be placing the checkAuth() code?
and, if i have more than 1 config (i have 4 ... i have 2 user types and a config each for signup and signin. each one calls a different user flow in azure ad b2c), what should go in the checkAuth() parameter(s)?

**Comment by aylmercarson** [comment]
i think i have it...

checkAuthMultiple() in ngOnInit() on the return page, no parameters. 

i wonder if it might be better to track the configId used in the initial signup/signin and get that passed to simply checkAuth() in the return page?

**Comment by FabianGosebrink** [comment]
If you have the currently active configId I think it is safer to pass it to the lib. Closing this as the main issue is solved.
