### ISSUE TITLE
[Bug]: OidcSecurityCheckSession not receiving check session response messages.

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#1658]
### Version

14.1.5

### Please provide the exception or error you saw

```true
I am facing this famous error:
> CheckSession - OidcSecurityCheckSession not receiving check session response messages.

but it seems to happen only when running angular locally with hmr.
```

### Steps to reproduce the behavior

```true
Just create a new project add the library and `ng server --hmr`
```

### A clear and concise description of what you expected to happen.

```true
Error should ne be displayed
```

### Additional context

When I put breakpoints in the `checkSessionService` I can see that keycloak behaves correctly and that checks are sent and received. But for some weird reason there are two different instances of `checkSessionService` which causes `this.outstandingMessages` not getting cleared. Any idea what might be causing that ( I suspect --hmr (Hot Module Reload) but what more specifically and maybe how to fix it ?)

**Comment by henning-anderssen** [comment]
I'm having this problem as well, and it went away when I disabled HMR. Not a good solution, but I can't have my app freeze on me while I'm working, due to the number of errors I get. Quickly the app, dev tools and chrome gets very unresponsive.

**Comment by damienbod** [comment]
I don't see how we can support hmr, see no solution for this. 
Greetings Damien

**Comment by yelhouti** [comment]
@damienbod can you provide a little bit more detail on why this is happening, maybe someone else can think of a solution ?

**Comment by damienbod** [comment]
@yelhouti 

HMR is when a module changes, angular only updates this part. This never really worked. As we have something which affects the complete application, we can not support it.

**Comment by yelhouti** [comment]
@damienbod sorry if my comment wasn't clear. I understand what hot module reload means. what i don't understand is why it breaks things. (I guess it is because of some state getting lost on page refresh), why can't we retrieve it on start would be my question ?

**Comment by FabianGosebrink** [comment]
The only "explanation" which I can think of is that when hmr kicks in, a part of your app with maybe a new instance of service x is provided. This is crucial when you have something like auth with affects the whole application and not just a part.

**Comment by yelhouti** [comment]
if there any reason why we keep checking for failure even after a 100 failed attempts ?
```
                this.zone.runOutsideAngular(() => {
                    this.scheduledHeartBeatRunning = setTimeout(() => this.zone.run(pollServerSessionRecur), this.heartBeatInterval);
                });
```
maybe we can just stop if > 20 outstanding messages, and restart when threshold gets back below that

**Comment by yelhouti** [comment]
@FabianGosebrink @damienbod here is a fix
