### ISSUE TITLE
SSO - Silent signin

### ISSUE THREAD

**Issue by lundn** [damienbod/angular-auth-oidc-client#166]
Hi,

We're currently in the works to replace oidc-client-js library with this library for handling authentication in our SPA.

One of the options in oidc-client-js is to silently signin the user if he/she is already logged on to IdentityServer. e.g from another portal site - is there a way to implement this with your library? Hope I managed formulate my question..ok'ish.. :)

**Comment by BiLKiNiS** [comment]
For me if the user is already logged in the Identity Provider, I redirect him to a component where I have this in the constructor 
`import { Component, OnInit } from '@angular/core';
//import { isNumeric } from 'rxjs/util/isNumeric';
//import { Observable } from "rxjs/Observable";


import { OidcSecurityService } from '../../oidc/services/oidc.security.service';

@Component({
    selector: 'autologin',
    template: ''
})
export class AutoLoginComponent {

    constructor(
        public oidcSecurityService: OidcSecurityService
    ) {
        if (this.oidcSecurityService.moduleSetup) {
            this.oidcSecurityService.authorize();
        } else {
            this.oidcSecurityService.onModuleSetup.subscribe(() => {
                this.oidcSecurityService.authorize(); 
            });
        }
    }
}
`

**Comment by lundn** [comment]
Thanks for the input @BiLKiNiS, much appriciated. However, I do not think this is exactly what we want to achieve.

**User scenario**
Unauthenticated user opens portal with SPA (portal A). He / she opens a new tab and access another portal (portal B) using the same Identity Provider as portal A. The user logs in portal B, is authenticated in IDServer and authorized to use portal B. 

Upon returning to tab with portal A, we want to silently authorize the user in portal A if he performs an action. Using the [oidc-client-js](https://github.com/IdentityModel/oidc-client-js) we have access to `silentSignin` method, which enables authorization through iFrame.

> signinSilent: Returns promise to trigger a silent request (via an iframe) to the authorization endpoint. The result of the promise is the authenticated `User`.

The whole process is unoticable to the user.

Is it possible to achieve this with this library?

**Comment by BiLKiNiS** [comment]
I don't think it is implemented, the only thing using iframe are the silent renew of the token and de session check.
Using this as a template you could implement this, but I have a question.
For the user to be silently log in the portal A, you need to save the credential he has typed in the portal B?

For me this is not very secure to do du to the fact that the credential sould only be use (type by the user) in the identity provider login page.
They should not be type in a page of the portal A or B.

If after being logged in the id provider to the portal B you want to access portal A, maybe you should request an access token to the id provider with the necessary claim and audience to access portal A, the does not requier to manipulate the user credentials, only the id_token or token previously generated for the user for the other portal

**Comment by damienbod** [comment]
@BiLKiNiS @lundn 

This would work if you use autologin in the client app, but you should use different tokens for each application. At present the tokens are saved to the same location so you would need to create a custom storage for 1 app, and then it would work.

1) User logins in coming from portal 1
2) User opens Portal 2
3) redirected to STS
4) Already logged in, redirected back

You also need to turn of the consent page, otherwise the second login will stop at the consent page.

Greetings Damien

**Comment by damienbod** [comment]
Please reopen if this is not solved for you

Greetings Damien
