### ISSUE TITLE
[Bug]: Silent refresh fails using localStorage when multiple tabs trying to refresh at the same time

### ISSUE THREAD

**Issue by medeirosrich** [damienbod/angular-auth-oidc-client#1662]
### Version

5.0.3

### Please provide the exception or error you saw

```true
silent renew failed! Error: Error: authorizedCallback, token(s) validation failed, resetting.
```

### Steps to reproduce the behavior

```true
1) Set up OIDC Code Flow PKCE using refresh tokens (used 'ng add angular-auth-oidc-client')

2) Set up custom storage using localStorage (used example from https://angular-auth-oidc-client.com/docs/documentation/custom-storage)

4) To speed up testing, setup your authority to have short lived access and refresh tokens. (i.e. 1 or 2 minutes) 

3) Login using one browser [chrome] tab (i.e. this.oidcSecurityService.authorize()). Open console and verify refresh is working

4) Open a few more tabs. Open console and verify they are authorized and refreshing

5) Wait until error occurs. It shouldn't take long - usually 2-10 minutes with 1 minute tokens. Open more tabs if needed.
```

### A clear and concise description of what you expected to happen.

```true
access token should refresh successfully and all tabs remain authorized
```

### Additional context

It seems that multiple tabs simultaneously attempting to refresh the token using a shared localStorage is causing a race condition, resulting in validation failure.

**Comment by TarasKovalenko** [comment]
@medeirosrich I tried to reproduce the issue, but from my side, everything works well. Can you please prove the AuthModule configuration?

**Comment by medeirosrich** [comment]
> @medeirosrich I tried to reproduce the issue, but from my side, everything works well. Can you please prove the AuthModule configuration?
```
config: {
            authority: '[my authority]',
            redirectUrl: window.location.origin,
            postLogoutRedirectUri: window.location.origin,
            clientId: 'Portal',
            scope: 'openid email profile offline_access roles internal_api external_api', // 'openid profile offline_access ' + your scopes
            responseType: 'code',
            silentRenew: true,
            useRefreshToken: true,
            renewTimeBeforeTokenExpiresInSeconds: 30,
            ignoreNonceAfterRefresh: true,
            logLevel: LogLevel.Debug
        }
```

**Comment by TarasKovalenko** [comment]
@medeirosrich I have the same configuration and everything works well with multiple tabs.

**Comment by medeirosrich** [comment]
I don't know if this helps, but here is a side by side of the logs from the two tabs that are colliding

![image](https://user-images.githubusercontent.com/368982/215765137-ee6179a2-f64f-450c-9306-a1b41741c4fa.png)

**Comment by TarasKovalenko** [comment]
@medeirosrich your AuthConfigModule was added to the imports of the main AppModule? and can you please show the code of your LocalStorageManagerService? because localstorage by default shared all data between all tabs and windows from the same origin.

**Comment by medeirosrich** [comment]
@TarasKovalenko Yes
Here is the AppModule
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AuthConfigModule } from './auth/auth-config.module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    AuthConfigModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

And the LocalStorageManagerService
```
import { Injectable } from "@angular/core";
import { AbstractSecurityStorage } from "angular-auth-oidc-client";

@Injectable()
export class LocalStorageManagerService implements AbstractSecurityStorage {
  read(key: string) {
    return localStorage.getItem(key);
  }

  write(key: string, value: any): void {
    localStorage.setItem(key, value);
  }

  remove(key: string): void {
    localStorage.removeItem(key);
  }

  clear(): void {
    localStorage.clear();
  }
}
```

**Comment by VaclavChalupa** [comment]
Hi. @TarasKovalenko is local storage with multiple browser tabs/windows supported?
It requires some internal synchronization to prevent concurrent refresh token issues.

**Comment by TarasKovalenko** [comment]
Hi @VaclavChalupa ,
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
`localStorage data is specific to the protocol of the document. In particular, for a site loaded over HTTP (e.g., http://example.com), localStorage returns a different object than localStorage for the corresponding site loaded over HTTPS (e.g., https://example.com).`

is local storage with multiple browser tabs/windows supported - about tabs for sure, but about windows it's hard to say. data will be saved even if you close and open the browser again. so I guess the answer is yes (but not related to the incognito window)

**Comment by Adrii77** [comment]
Hello,

We’re facing the same issue… We try so many things to solve it, but we’re stuck.

Versions :
Angular : 15.2.5
angular-auth-oidc-client : 15.0.3

Contexte : 
We are on Azure.

We’re using localStorage with a custom class [the same as the documentation](https://angular-auth-oidc-client.com/docs/documentation/custom-storage), but with providedIn ‘root’  in order to use the same instance in other places inside our app).

We’re using silentRenew (without Iframe).

When we’re using the application in a single tab, no problem : silent renew works perfectly.
But in multi tabs, when each of them ask to refresh the token (at the same time), it doesn’t work (see below) : 
![unknown](https://user-images.githubusercontent.com/40627664/231757272-63b5c366-9886-4479-81db-1fd881f0c101.png)

Has-new is an HTTP polling request. Left screen is a tab, the right another.   Error always appeared after the « keys » http call. The call response is always return from disk cache (I don’t know if its a problem as it works in single tab with this behavior).
![unknown](https://user-images.githubusercontent.com/40627664/231757319-1462dab7-87aa-407b-bdb9-16fc81228cc2.png)


The encountered error :
![MicrosoftTeams-image](https://user-images.githubusercontent.com/40627664/231757351-24901d88-f81d-434e-884a-29b6111e1fb0.png)

@medeirosrich Did you find a solution ?

Thanks in advance

**Comment by medeirosrich** [comment]
@Adrii77 We did not. We switched to using sessionStorage for now.

**Comment by medeirosrich** [comment]
@damienbod I see you closed this bug, does that mean the concurrency issue when using localStorage is fixed?

**Comment by Adrii77** [comment]
@medeirosrich  I guess not. Damien answered on this topic : https://github.com/damienbod/angular-auth-oidc-client/issues/1716#issuecomment-1510416354

**Comment by joewIST** [comment]
I am also facing similar issues. Session storage is not ideal as we want the authentication state to be preserved when the user opens the app in a new tab. Any joy?

**Comment by Adrii77** [comment]
We found a temporary solution (with localStorage) which we're still experimenting right now : 

We set the `renewTimeBeforeTokenExpiresInSeconds` with a random value between 100 and 500. This allows us to reduce the probability of tabs refreshing the token at the same time.

`renewTimeBeforeTokenExpiresInSeconds: Math.floor(Math.random() * 400) + 100
`

**Comment by Coldfen** [comment]
Hello, I have the same problem when I use localStorage. A temporary solution does not suit me well, because my token functions for 300 seconds. Do you have any advice or solutions for me?

Version: 16.0.0

**Comment by joewIST** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/1753 do you get any errors like this @Coldfen  ?

**Comment by Coldfen** [comment]
@joewIST I didn't see that error. 

My error: 
![image](https://github.com/damienbod/angular-auth-oidc-client/assets/94360746/f0930576-9924-4113-900f-e550d7af9687) 

We use localStorage, and when we use multi tabs, we get this error.

**Comment by joewIST** [comment]
This is still an issue for us, has anyone been able to find a workaround for using localStorage + silentRenew? It definitely seems to be linked to multiple tabs refreshing at the same time... I'm not sure it should be closed.
