### ISSUE TITLE
[Question]: How can I check authentication when using StsConfigLoader to initialize?

### ISSUE THREAD

**Issue by skeletor069** [damienbod/angular-auth-oidc-client#1668]
**What Version of the library are you using?**
15.0.2

**Question**
How can I check authentication when using StsConfigLoader to initialize?

I am initializing AuthModule in the root AppModule imports section. In the app.component.ts file, I am checking the auth in ngOnInit like this

![image](https://user-images.githubusercontent.com/15325370/216302840-7ba40182-16dc-48f4-a2b3-efcfc2b7c43a.png)

When I initialize using `AuthModule.forRoot(authModuleConfig)`, everything works fine, in app component I am getting `isAuthenticated` true. But when I use the loader, I always get `isAuthenticated` false.  I compared the loaded configuration for both the cases using `PublicEventsService`, and they are identical. 

What might be the cause of the issue? Am I missing something here? the `errorMessage` is undefined in app component, so I do not have any error either.

**Comment by Lexa-tech** [comment]
Hello @skeletor069 , set the logLevel to debug and verify this log : [DEBUG] 0-[YourclientId] - currentUrl to check auth with:  [url to check].
Check if the url contains queryParam code=XXXXX (when returning from authentication server).
I had a problem like this (but I don't know if it's the same than yours).
In my case, the callback url when returning from authentication was www.url.com/index.html?code=xxxxx, the `checkAuth` method was called in `app.compponent.ts`  but I have a route configuration that redirects to #home, without preserving params, and when the library code that checks the code is executed, the query param code is already lost.
I think the redirectTo is executed before the library code is called.
I fixed it by passing a url param to the `checkAuth`function: `checkAuth(window.location.href)`, with this patch, I preserve the code query param.

**Comment by skeletor069** [comment]
Hello @Lexa-tech , thank you very much for you reply. You are right, it was redirecting to a different route, and the query param is lost. using `checkAuth(window.location.href)` solved my issue.

**Comment by FabianGosebrink** [comment]
This is why you should use a callback component or something which processes the url and _then_ redirects ;)

**Comment by skeletor069** [comment]
@FabianGosebrink thank you for the suggestion. I am also planning to have a separate route for the authentication callback only.

**Comment by skeletor069** [comment]
Hello @FabianGosebrink, can you please re-open the issue? unfortunately there was a big delay between my re-opening of the issue and submitting my question :)

**Comment by FabianGosebrink** [comment]
I am confused :-) Is the initial issue solved?

**Comment by skeletor069** [comment]
Oh, sorry. Yes, the initial issue is solved :). you can leave this issue as closed, no problem. I will create another issue with details. Thank you very much :)

**Comment by FabianGosebrink** [comment]
Thank you very much for your understanding and for opening a new issue. It is easier for other users of this lib to find your new question then if we do not hide it in this conversation.
