### ISSUE TITLE
[Question]: Is it possible to use the getState() to find out if the authorize() function was called?

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1671]
**What Version of the library are you using?**
14.1.5

**Question**
What does the getState() return? 

Is it possible to use the getState() to find out if the authorize() function was called, not the status of the login.

Regards,
-Fritz

**Comment by FabianGosebrink** [comment]
You have to track if the authorize method was called by yourself. What use case do you have?
