### ISSUE TITLE
[Question]: Move Http Interceptor into its own page

### ISSUE THREAD

**Issue by timdeschryver** [damienbod/angular-auth-oidc-client#1674]
**What Version of the library are you using?**
N/A

**Question**
In most applications we need to add an authorization header to the requests that the application makes. This is done with HTTP Interceptors, and this library already provides the `AuthInterceptor` interceptor.
But, this is a bit hidden in the current documentation. The `AuthInterceptor` interceptor is currently added to the "Using Access Tokens" page.
Because it's such a frequent thing to look up, I think it would be better to move the current content in a dedicated "Interceptor" page.

I opened this question because I saw new developers writing their own interceptor because they didn't find/search the docs.

**Comment by FabianGosebrink** [comment]
Hey, if you want to review, feel free :)
