### ISSUE TITLE
[Bug]: AutoLoginAllRoutesGuard does not work with "safe" links

### ISSUE THREAD

**Issue by benthieu** [damienbod/angular-auth-oidc-client#1676]
### Version

15.0.3

### Please provide the exception or error you saw

```true
ERROR Error: Uncaught (in promise): TypeError: Cannot destructure property 'isAuthenticated' of 'object null' as it is null.
TypeError: Cannot destructure property 'isAuthenticated' of 'object null' as it is null.
    at main.2a0dc4ad57622d2a.js:formatted:0:43521:50
```

### Steps to reproduce the behavior

Create a link (i.e. from an email) with `rel="noopener noreferrer"` to a route with the `AutoLoginAllRoutesGuard`. Our email provider for example automatically adds these attributes to any link.

The library automatically assumes that we are in a popup (because of the context) and returns null (line 111 in `check-auth.service.ts`).

### A clear and concise description of what you expected to happen.

```true
Either to redirect to the login or the be logged in.
I think the mechanism to detect a popup is flawed for these kind of links.
```

**Comment by FabianGosebrink** [comment]
Nice. But be aware that the AutoLoginAllRoutesGuard is not recommended anymore.
