### ISSUE TITLE
[Question]: About using checkAuthMultiple()

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1678]
**What Version of the library are you using?**
14.1.5

**Question**
Trying to understand here:

So when the "this.oidcSecurityService.checkAuthMultiple()" is called, it will load all of the configs, which means that you can then call the authorize(clientId). And when login is successful it will do:

```
    this.oidcSecurityService.checkAuthMultiple().subscribe((checkAuth) => {

      checkAuth.forEach((item: any) => {
         if (item.isAuthenticated) {
            if (item.configId === myClientId) {
              // Send event that clientId is logged-in.
           }        
         }
      });  
    });
```

**Comment by FabianGosebrink** [comment]
Yes, you get back an `LoginResponse[]` where you can do

```
  this.oidcSecurityService.checkAuthMultiple().subscribe((loginResponses: LoginResponse[]) => {
      loginResponses.find(response => response.clientId === myClientId);
      return clientId.isAuthenticated;
    });
```

Just typed that in the browser, this is maybe not the 100% correct syntax.

**Comment by fritzwf** [comment]
Also, when I get the clientId from CheckAuth subscription, it is the version that has the 0- in front of the clientId that is in config AuthModule.

**Comment by fritzwf** [comment]
Is the numbering of the clientId something that only the OIDC Client does?  If so, why do you that?  The clientId's should already be unique right?  Also, does it guarantee to always put 0- starting at the first config in the array?

**Comment by aylmercarson** [comment]
the clientid is something you should be getting from your id provider. it is fixed by them and you enter it in your config settings. any (decent) id provider will require a client id, which, among other things, will whitelist clients making calls. if yours starts with "0-" then i'm guessing that's what your id provider has given you to use?

**Comment by fritzwf** [comment]
> the clientid is something you should be getting from your id provider. it is fixed by them and you enter it in your config settings. any (decent) id provider will require a client id, which, among other things, will whitelist clients making calls. if yours starts with "0-" then i'm guessing that's what your id provider has given you to use?

No, my clientId's don't have 0- or 1-, etc.  It appears that the OIDC client adds those.  Maybe its done so that if a particular clientId is a duplicate of another config, but I would think that would be very low odds it would happen.

**Comment by FabianGosebrink** [comment]
The clientId is a unique identifier you can provide the config to have. If you do not specify one, the lib does. And this does start with an index. https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/config/config.service.ts#L94-L100

**Comment by fritzwf** [comment]
Thanks.  Do you know if there is an existing code example for of setting up the identifiers?

**Comment by FabianGosebrink** [comment]
You can choose whatever string you like. It just has to be unique.

**Comment by FabianGosebrink** [comment]
WAIT! I did a mistake. ClientID !== configId! Checking where this comes from: `if (item.configId === myClientId) {` from your first code sample. 

The configId is something the lib internally needs to identify a config.
The clientId is something you get from your IDP. 

That is two different things!

**Comment by fritzwf** [comment]
That's okay.

So if I have this:  

```
AuthModule.forRoot({
  config: [
	{
	  authority:
		"https://mylogin.com/services/oidc/authorize",
	  redirectUrl:
		"https://myredirect.com/mypage",
	  clientId: "4335-343654-5454",
	  scope: "openid profile",
	  responseType: "code",
	  logLevel: LogLevel.Debug,
	  useRefreshToken: false,
	  silentRenew: false,
	  triggerAuthorizationResultEvent: true,
	},
	{
	  authority:
		"https://myotherlogin.com/services/oidc/authorize",
	  redirectUrl:
		"https://myotherredirect.com/mypage",
	  clientId: "6578-379877-9004",
	  scope: "openid profile",
	  responseType: "code",
	  logLevel: LogLevel.Debug,
	  useRefreshToken: false,
	  silentRenew: false,
	  triggerAuthorizationResultEvent: true,
	}
  ]
})
```
I can change it to:

```
myLogin = {
  authority:
	"https://mylogin.com/services/oidc/authorize",
  redirectUrl:
	"https://myredirect.com/mypage",
  clientId: "4335-343654-5454",
  scope: "openid profile",
  responseType: "code",
  logLevel: LogLevel.Debug,
  useRefreshToken: false,
  silentRenew: false,
  triggerAuthorizationResultEvent: true,
}

myotherlogin = {
  authority:
	"https://myotherlogin.com/services/oidc/authorize",
  redirectUrl:
	"https://myotherredirect.com/mypage",
  clientId: "6578-379877-9004",
  scope: "openid profile",
  responseType: "code",
  logLevel: LogLevel.Debug,
  useRefreshToken: false,
  silentRenew: false,
  triggerAuthorizationResultEvent: true,
}
	
AuthModule.forRoot({
  config: [ myLogin, myotherlogin ]
})
```

Thanks.

**Comment by FabianGosebrink** [comment]
I am not sure if I understand this correct.

The clientId tells the IDP which client to identify. The configId is for the lib to identify its configuration. So your IDP should know your clients `6578-379877-9004` and `4335-343654-5454` in this case. These are NOT the configIds the library is working with to identify the configs.

> And those names used in the array, will be the unique configId's.
I do not understand, because the arrays have no "name" and the configId is a property the lib sets on the config. If you mean the name of the variables here  `[ myLogin, myotherlogin ]`: No, the names of the variables are not used as a configId. The lib does not know them.

> And we will see them when we are logging the checkAuthMultiple() function?
You will get back a LoginResponse[] as described here: https://angular-auth-oidc-client.com/docs/documentation/public-api#checkauthmultipleurl-string

On there is the configId (not the clientId).

Hope this helps :)

**Comment by fritzwf** [comment]
Maybe I didn't expresss what I was trying to do, since I don't know how to do this.  The docs say if I don't create a name (for my clientIds'), the client will give them a name, I assume that is those names like 0-6578-379877-9004, etc.   So, I want to create my names so I can refer to that particular clientId by a name so that I can do things like, logout without using the 0-6578-379877-9004.  That would be better than relying on the order of  config's in module.

Regards,
-Fritz

**Comment by FabianGosebrink** [comment]
Do you have the part where the docs say this? Can you link it?

**Comment by FabianGosebrink** [comment]
Is it clear now?

**Comment by fritzwf** [comment]
Oh I was mistaken, mixed up with clientId and configId.  Chalk it up lack of sleep.

Another question, why don't you just use the configId as the clientId?

Thanks for answering my questions so promptly.

Regards,
-Fritz

**Comment by FabianGosebrink** [comment]
The clientId is crucial to the IDP. We can not tell the users what the clientId is as they have to configure this at their IDP :-) Separating this is a way for us to see which config is which and having the users their clientId at their IDPs independent.

**Comment by fritzwf** [comment]
I have been using checkAuthMultiple().   I have 3 clients and only 1 will be logged-in at any one time.  When I login, and the loginResponses come in, I get 6 of each clients.  I am console logging the ones that are true and see 6 logged-in.  It seems like it sends the subscription twice.  I would think that only 3 would show with 1 true.  Is this the way it should work?

Regards,
-Fritz

**Comment by fritzwf** [comment]
BTW, I found the comment with about the giving it a name or it will make a name:

import { LogLevel } from '../logging/log-level';
import { AuthWellKnownEndpoints } from './auth-well-known/auth-well-known-endpoints';

export interface OpenIdConfiguration {
  /**
   * To identify a configuration the `configId` parameter was introduced.
   * If you do not explicitly set this value, the library will generate
   * and assign the value for you. If set, the configured value is used.
   * The value is optional.
   */
  configId?: string;

Location is here:

https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/angular-auth-oidc-client/src/lib/config)/openid-configuration.ts

Regards,
-Fritz
