### ISSUE TITLE
[Question]: Remember me functionality

### ISSUE THREAD

**Issue by davidsarkany** [damienbod/angular-auth-oidc-client#1682]
**What Version of the library are you using?**
15.0.3

**Question**
How can I do the "Remember me" functionality?
I work in an industry environment, and we need this functionality.
1. User login to the website.
2. Use close the browser and wait 72 hour
3. Use open the website without login.

Is it possible with the refresh token?

I tried to use local storage as StorageService, but the access token expired (5 min later, with a closed browser), and the user needs login.

**Comment by damienbod** [comment]
Hi @davidsarkany 

Yes a refresh token can be used for this and the STS needs to be setup to allow this and support this. You don't need to use localstorage. The refresh token lifespan is important as well

Greetings Damien
