### ISSUE TITLE
Issue when try to logout [TypeError: Cannot read property 'toLowerCase' of undefined]

### ISSUE THREAD

**Issue by simulaterz** [damienbod/angular-auth-oidc-client#169]
I clone your repo "angular-auth-oidc-sample-google-openid" and Change setting to use AD B2C

When I run it work fine but when I try to logout I got error like

![image](https://user-images.githubusercontent.com/24958945/35690742-3e23c34a-07a9-11e8-960d-c835c79c4c43.png)

I don't know why it happen, 
When I logout and new tab and open website again it not auto redirect me to login page but still on this page seem it already login.

Can you help me to fix this issue,
Cheers

**Comment by damienbod** [comment]
Here' an example with B2C

https://github.com/HWouters/ad-b2c-oidc-angular

The google example does not use the logout, because the google oidc server does not support the logout.

Greetings Damien

**Comment by damienbod** [comment]
Hi @simulaterz 
Please reopen if this is not solved for you

Greetings Damien
