### ISSUE TITLE
[Question]: how to catch the login callback from the auth server to the main angular app and show the loader during the getting token process?

### ISSUE THREAD

**Issue by TarasKovalenko** [damienbod/angular-auth-oidc-client#1690]
**What Version of the library are you using?**
15.0.3

**Question**
How to catch the login callback from the auth server to the main angular app and show the loader during the getting token process?
After pressing the login button the user will be navigated to the auth server with the login/password form. After successful login, the user will be automatically navigated to the main angular app and will wait some time (it depends on the network connection speed). So to avoid end-user confusion I want to show some loading information, but unfortunately can't find the needed function from the angular-auth-oidc-client. 
Does anyone know if we can do it from the box without custom workarounds?

**Comment by FabianGosebrink** [comment]
Hey, set the redirecturl after login to a /callback component in your app, do the checkAuth() in that component and show the loading screen in the template of the component. If authenticated (in the subscribe of the checkAuth() method, you redirect to your main route.

**Comment by TarasKovalenko** [comment]
Hey, thank you! Have no idea why I am not thinking about the callback component :)
