### ISSUE TITLE
[Bug]: AutoLoginPartialRoutesGuard does not start SilentRenew

### ISSUE THREAD

**Issue by benthieu** [damienbod/angular-auth-oidc-client#1691]
### Version

15.0.3

### Please provide the exception or error you saw

We migrated from `AutoLoginAllRoutesGuard` to `AutoLoginPartialRoutesGuard`. The `AutoLoginPartialRoutesGuard` does however not start the SilentRenew Process.

In the deprecrated `AutoLoginAllRoutesGuard` the function `checkAuth` was called which started `startCheckSessionAndValidation`.

**Comment by benthieu** [comment]
Is there a way to start the SilentRenew manually?

**Comment by FabianGosebrink** [comment]
You have to call the checkAuth() method in your app.component. The samples should help you there. The AutoLoginAllRoutesGuard did that, yes.

**Comment by benthieu** [comment]
Ok thanks :) Sorry for opening a bug

**Comment by FabianGosebrink** [comment]
All good, easy :) Feel free to ask at any time.
