### ISSUE TITLE
[Question]: Logout after time goes by

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1694]
**What Version of the library are you using?**
14.1.5

**Question**
If a login is idle for a while (not sure how long), and then logout using the:

```
this.oidcSecurityService.logoffAndRevokeTokens(MY_ID).subscribe(() => {
      this.oidcSecurityService.logoffLocalMultiple();
});
```

Does it still remove the tokens, userData, or will the idle cause it to not remove the tokens and userData?

**Comment by FabianGosebrink** [comment]
It will normally log out, the lib does not care about the idle time. If you log out, it will remove everything and log out.
