### ISSUE TITLE
[Question]: CORS Error on console after OpenId login redirect

### ISSUE THREAD

**Issue by Temi-Tory** [damienbod/angular-auth-oidc-client#1697]
**Version**  15.0.3 

Hi, I  have been trying to follow the samples in docs. And I cannot manage to get the service to work. I am able to get to the login screen. But upon redirecting back to app, I get these two errors repeated over and over again related to CORS. I  would usually fix the CORS issue by allowing Cors on ASPnet API.  But I am not integrating this app with an API, so I am not sure how to fix this problem. 
 I think it is similar to #1683 , but not quite. 
These are the errors I am getting on the console: #

```
POST https://fs.myauthority.co.uk/adfs/oauth2/token/ net::ERR_FAILED 400 (Bad Request)

Access to XMLHttpRequest at 'https://fs.myauthority.co.uk/adfs/oauth2/token/' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by FabianGosebrink** [comment]
Have you enabled CORS for the url you are trying to call?

**Comment by Temi-Tory** [comment]
> Have you enabled CORS for the url you are trying to call?

Do you mean this URL:  https://fs.myauthority.co.uk/adfs/oauth2/token/? 

I am relatively new to Angular and coming from C# and ASP.net, I have never had to enable CORS in my adfs server.

**Comment by FabianGosebrink** [comment]
CORS is a server side thing, not an angular one. So when you are reaching out to a resource, and it is not allowed by the server, you have to allow it via CORS. If you did ASP.NET Core before the resource was maybe running on the same server, then you do not need this.

**Comment by Temi-Tory** [comment]
thank you for the insight. I will explore the adfs server further. Thank you
