### ISSUE TITLE
[Question]: How can I check if user is logged in on the server (not locally)? 

### ISSUE THREAD

**Issue by 4AK1LLA** [damienbod/angular-auth-oidc-client#1699]
**What Version of the library are you using?**
Latest

**Question**
How can I check if user is logged in on the server (not locally)? Everytime I open my site in new tab I have to call authorize method to get userdata and tokens, but identity provider lets me slip through without login&password so it has session, as I understand. Please help

My settings:
![image](https://user-images.githubusercontent.com/90700933/220908143-04d80af9-0412-42e9-a799-3b652fa99fec.png)

**Comment by fritzwf** [comment]
What was the answer to this?  I am also having that same new tab issue.

**Comment by 4AK1LLA** [comment]
> What was the answer to this? I am also having that same new tab issue.

I had cookie received from server, so I just checked if client has this cookie, if no, then send authorize()
(it's my solution)

**Comment by fritzwf** [comment]
My implementation was to use the subscription and if there is no login, it will return false.

    this.oidcSecurityService.isAuthenticated$.subscribe(loginStatus => {
        if (loginStatus === false) {
            this.oidcSecurityService.authorize(CLIENT_ID);
        }
    });

**Comment by 4AK1LLA** [comment]
> isAuthenticated

As far as I remember isAuthenticated is client side, but I can be wrong

**Comment by fritzwf** [comment]
When I call the authorize it works but is shows, "Error: codeFlowCodeRequest incorrect state"
