### ISSUE TITLE
[Question]: How can I solve checkAuthIncludingServer() sends authorize request with redirect uri https://please_set ?

### ISSUE THREAD

**Issue by 4AK1LLA** [damienbod/angular-auth-oidc-client#1700]
**What Version of the library are you using?**
Latest

**Question**
How can I solve checkAuthIncludingServer() sends authorize request with redirect uri https://please_set ? I have set it in configuration like window.location.origin, and when authorize method is called it works properly.

My settings:
![image](https://user-images.githubusercontent.com/90700933/220907565-032ecf45-a871-4ec2-8ca6-bd25cc2d0e17.png)
Error:
![image](https://user-images.githubusercontent.com/90700933/220907867-9124ee19-9fcd-43d8-93b1-4f0453d1416a.png)

**Comment by FabianGosebrink** [comment]
Can you please set a title when posting an issue?

**Comment by 4AK1LLA** [comment]
> Can you please set a title when posting an issue?

Sorry, I didnt notice title input

**Comment by FabianGosebrink** [comment]
No worries, all good. Can you set the loglegel to "Debug" and watch out for the `Working with config ...` entry? Is there a redirectUri entered?

**Comment by 4AK1LLA** [comment]
> No worries, all good. Can you set the loglevel to "Debug" and watch out for the `Working with config ...` entry? Is there a redirectUri entered?

I have one config 'identity_server':
![image](https://user-images.githubusercontent.com/90700933/220921064-acd36e0d-1239-45f8-9a42-cdca18e5c839.png)

Debug (Dont pay attention on GET errors):
![image](https://user-images.githubusercontent.com/90700933/220920659-45cf5f97-73b6-4c81-801f-f1c65d3474d1.png)

**Comment by 4AK1LLA** [comment]
`sendAuthorizeRequestUsingSilentRenew for URL` has `redirect_uri=https%3A%2F%2Fplease_set`

**Comment by FabianGosebrink** [comment]
Yeah but you have other errors as well.... Can you provide a sample repo or stackblitz to reproduce the issue?

**Comment by 4AK1LLA** [comment]
> Yeah but you have other errors as well.... Can you provide a sample repo or stackblitz to reproduce the issue?

Shure, here is sample repo https://github.com/4AK1LLA/sample

**Comment by FabianGosebrink** [comment]
The link is not working. Can you reproduce this with one of our samples?

**Comment by FabianGosebrink** [comment]
I just ran the sample with `this.oidcSecurityService.checkAuthIncludingServer()` without any problems.

**Comment by 4AK1LLA** [comment]
Solved already, I wasnt logged in and had login_required error
