### ISSUE TITLE
[Bug]: Possible Documentation Issue

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1701]
### Version

14.1.5

### Please provide a link to a minimal reproduction of the bug

Possible documentation issue

### Please provide the exception or error you saw

https://angular-auth-oidc-client.com/docs/documentation/public-api#checkauthmultipleurl-string

The checkAuthMultiple(url?: string) shown in the docs, it returns an Observable<LoginResponse[]>.

However below the above, it shows:

Is this code below still valid?
```
this.oidcSecurityService.checkAuthMultiple().subscribe(({ isAuthenticated, userData, accessToken, idToken, configId }) => {
  // ...use data
});
```
Regards,
-Fritz
```

**Comment by FabianGosebrink** [comment]
Thanks for the hint. That really is a bug in the docs. You are getting back an array and can not destructure the properties immediatelly. Thanks!
