### ISSUE TITLE
[Bug]: isAuthenticated$ and isAuthenticated() return different values when logged in and reloading the page

### ISSUE THREAD

**Issue by heapifyman** [damienbod/angular-auth-oidc-client#1708]
### Version

15.0.3

### Please provide a link to a minimal reproduction of the bug

https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-auto-login-all-routes

### Please provide the exception or error you saw

```true
`authenticated:  false home.component.ts:19:14`
```

### Steps to reproduce the behavior

```true
1. Run sample app [Code flow PKCE auto-login for all routes](https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-auto-login-all-routes)
2. Login and get redirect to HomeComponent - it will display "Is Authenticated: true" and your user data.
3. Press F5 to reload the page - it will display:

> Is Authenticated: false

> {
>   "userData": null,
>   "allUserData": []
> }

And the navigation bar at the top will return to the "not logged in state", only displaying "Route to 'protected' Route & Auto Login".

However, clicking the "Route to 'protected' Route & Auto Login" link in the navigation bar still works. You can access the "/protected" route and the page displays

> protected works!

All the other routes that require authentication like "/customers" or "/forbidden" also still work.
```

### A clear and concise description of what you expected to happen.

```true
After pressing F5 the HomeComponent should still display the logged in user's data and the navigation bar should remain in the "user is logged in" state, showing all the links.
```

### Additional context

It appears that the `isAuthenticated$` and `userData$` observables do not emit the correct value when the page is reloaded.

`isAuthenticated$` will emit `false` even though the user is still logged in and the other observable `isAuthenticated()` still returns `true`. Can be tested by changing the code of `NavigationComponent.ngOnInit` to this:

```
  ngOnInit() {
    this.oidcSecurityService.isAuthenticated$
      .pipe(
        tap(({ isAuthenticated }) => console.log('[NavigationComponent] isAuthenticated$: ', isAuthenticated)),
        concatMap((_) => this.oidcSecurityService.isAuthenticated())
      )
      .subscribe((isAuthenticated) => {
        console.log('[NavigationComponent] authenticated: ', isAuthenticated);
        this.isAuthenticated = isAuthenticated;
      });
  }
```

It will print to the browser console:

> [NavigationComponent] isAuthenticated$:  false
> [NavigationComponent] authenticated:  true

See also https://github.com/damienbod/angular-auth-oidc-client/issues/1549#issuecomment-1450968732 

The [documentation](https://angular-auth-oidc-client.com/docs/documentation/auto-login#auto-login-when-all-routes-are-guarded) advises:

> Also think of calling checkAuth() in the AppComponent

So maybe this code from `CallbackComponent` should be added to the sample's `AppComponent`?

```
  ngOnInit(): void {
    this.oidcSecurityService.checkAuth().subscribe(({ isAuthenticated, userData, accessToken, idToken, configId }) => {
      console.log('callback authenticated', isAuthenticated);
    });
  }
```

On the other hand that causes angular-auth-oidc-client to make two requests to the token endpoint, where the second one will fail.:

```
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 400,
  "statusText": "Bad Request",
  "url": "https://offeringsolutions-sts.azurewebsites.net/connect/token",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://offeringsolutions-sts.azurewebsites.net/connect/token: 400 Bad Request",
  "error": {
    "error": "invalid_grant"
  }
}
```

And that might lead to further unexpected behavior?

**Comment by FabianGosebrink** [comment]
That is definitely not good. I have to look into this. I think this comes from removing the `...AllRoutesGuard`, not sure.

**Comment by FabianGosebrink** [comment]
True, this should be done by the lib logic, not the guard. Will have to look into this but short on time currently.

**Comment by alexeek** [comment]
> That is definitely not good. I have to look into this. I think this comes from removing the `...AllRoutesGuard`, not sure.

Sorry for bothering you in this issue but I saw you mentioned `...AllRoutesGuard`,  I used it before, and now I am using `AutoLoginPartialRoutesGuard` and I have an issue which is described #1465 . Could you help or explain why a refresh token doesn't work, or maybe there is a solution.. One more sorry I am just tired of fixing this in my project

**Comment by FabianGosebrink** [comment]
As long as there is a bug in there you can implement your own guard, it is not that much logic. We have to take a look at this and fix it. When I have time, then I can look into it.

**Comment by alexeek** [comment]
> As long as there is a bug in there you can implement your own guard, it is not that much logic. We have to take a look at this and fix it. When I have time, then I can look into it.

Yes, I did my own guard. But at first, I wanted to extend `AutoLoginPartialRoutesGuard` but there are restrictions with a private method I got a small problem with saving the redirection URL (solved). The main reason is that I prefer using the library methods and services as the best way. However most of them the library does not export and that was a bit of a problem.

**Comment by alexeek** [comment]
> As long as there is a bug in there you can implement your own guard, it is not that much logic. We have to take a look at this and fix it. When I have time, then I can look into it.

Is it possible to make `AutoLoginService` as public. Library doesn't export it but I need it for some reason for saving  redirection route  (saveRedirectRoute)

**Comment by Tyler-V** [comment]
Seeing similar results in our app, where it works for a few minutes navigating and refreshing the app

Then after 'x' minutes refreshing the angular app loses all userData state and our conditional async "show this to user in role" stuff starts to disappear :)

Any suggestions on how to ensure the userData maintains state, if its not already accomplished by local storage?

**Comment by Tyler-V** [comment]
> > Edit: Trying the observables getUserData() and isAuthenticated() to see if that resolves anything
> 
> @Tyler-V based on my tests it seems that `isAuthenticated()` and `getUserData()` return the correct values, also after reloading the page.
> 
> The following seems to work fine in my case:
> 
> ```
> this.oidcSecurityService.isAuthenticated$.pipe(
>     concatMap((_) => this.oidcSecurityService.isAuthenticated())
> )
>       
> this.oidcSecurityService.userData$.pipe(
>     concatMap((_) => this.oidcSecurityService.getUserData()
> )
> ```

Thanks @heapifyman so far in our testing - this is what we are noticing as well

Using the observable() instead of the observable$ in both cases is working great for us - it makes it a little confusing why two observables are exposed and only 1 of them works, perhaps some cleanup is in order

**Comment by bluebaroncanada** [comment]
I'm having this same issue.  Any progress on fixing it?  I created a new project and tried to implement the code as closely as I can tell.

I also noticed, and maybe this is a clue, that the silent renew is not working at all.  I turn on debug-level logging, but I get no messages in the console.

It's like it's failing to start crucial services.

Two projects.  Same thing.
