### ISSUE TITLE
[Question]: What does the subscription return when using logoffAndRevokeTokens()

### ISSUE THREAD

**Issue by fritzwf** [damienbod/angular-auth-oidc-client#1714]
**What Version of the library are you using?**
14.1.5

**Question**
Can you tell me what the subscription sends when using the: 
    this.oidcSecurityService.logoffAndRevokeTokens().subscribe(/* what */);

Regards,
-Fritz

**Comment by FabianGosebrink** [comment]
Have you tried out console.logging the result out?

**Comment by fritzwf** [comment]
I didn't check yet because we are doing integration and I don't have the time to spare.  Maybe I test it in a few weeks.

Anyways, I think your OIDC Client is a very good module.

**Comment by FabianGosebrink** [comment]
Okay, thanks. The response is depending on your IDP. So you have to debug or log it out and then you will see it :) Thanks!
