### ISSUE TITLE
[Bug]: Logging doesn't work 

### ISSUE THREAD

**Issue by scurk1415** [damienbod/angular-auth-oidc-client#1715]
### Version

15.0.3

### Please provide a link to a minimal reproduction of the bug

You can try on your own code samples

### Please provide the exception or error you saw

```true
There was no error
```

### Steps to reproduce the behavior

```true
Well it happens every time so no steps needed, just run one of your sample app with logLevel set on Debug (i tried it on sample-code-flow-auto-login-all-routes)
```

### A clear and concise description of what you expected to happen.

```true
I expected the debug logs to show in my developer tools console (I remember this was working before, I think in v14).
```

### Additional context

I tried it on a few different apps and none of them had any logging output. I also tried to implement a custom logger (based on the example in the docs), with no success. So my guess is that the logger methods are not being called

**Comment by FabianGosebrink** [comment]
I just tried it out, and it logs console debug. You have to set this in your browser. You have to set this. I think this change was a fix a user wanted. 
![image](https://user-images.githubusercontent.com/11268349/226739361-aec7a6b4-a208-45b8-97b3-fde22d188b8f.png)
