### ISSUE TITLE
[Question]: Redirect url after authentication using Identity Server

### ISSUE THREAD

**Issue by stefan0s** [damienbod/angular-auth-oidc-client#1726]
**What Version of the library are you using?**
v13

**Question**
I am having an angular spa application and need to redirect user to the Target url after successful authentication.

User opens a browser with a target url (the Target url may vary). Since user is not authenticated is redirected to identity server using as redirect_url the window.location.

I need to pass as a parameter the Target url to the identity server and get is back again after authentication handshake. I have tried to set as state parameter, but it seems that is not working. I will also try to use acr_values and set it as claim through profile service. 

Any suggestions? It seems common case for me, but I cannot find any easy way to implement that.

**Comment by jayachristina** [comment]
is it a similar usecase?

https://github.com/damienbod/angular-auth-oidc-client/issues/1722

**Comment by damienbod** [comment]
hi @stefan0s You would need to change the IDP implementation to implement it in this way. Normally I would store this in a session storage and after a successful authentication, open that page. 

Greetings Damien

**Comment by stefan0s** [comment]
Hello damien,

session storage would easily solve that case. 
I am also thinking from the security perspective is a good solution, since the target_url initialisation is on the client. That means that even if we where travelling back and forth the target_url to the idp would not provide any extra security.

Thank you
