### ISSUE TITLE
multiple redirect_uri's

### ISSUE THREAD

**Issue by premiumwd** [damienbod/angular-auth-oidc-client#173]
Anyway to have multiple redirect uris on angular side? 

I have multiple environments and websites (dev, stag, prod).

**Comment by damienbod** [comment]
@premiumwd yes. You can use a configuration json which is different for each environment, and load it in the APP_INIT. The STS server needs to support the correct environment redirects for each deployment. I do this is the app.settings in the dotnet application and set it in the build deployment of the CI.

**Comment by premiumwd** [comment]
Well I did this, since you didn't put any code:

```
let redirect = '';

if (environment.production) {
	redirect = 'http://appmngerprod.azurewebsites.net/#/auth';
} else {
	redirect = 'http://localhost:4200/#/auth';
}

const settings = {
	client_id: 'testClient',
	scope: 'openid profile email PhxAppMgrScope',
	response_type: 'id_token token',
	redirect_uri: redirect,
	post_logout_redirect_uri: 'http://localhost:4200/index.html',
	authority: 'https://phenomenexauthserver.azurewebsites.net',
	filterProtocolClaims: true,
	loadUserInfo: true
};
```

**Comment by damienbod** [comment]
@premiumwd looks good, don't forget about the post_logout_redirect_uri. What STS server, hosting do you use? Sorry about no code, but short of time at the moment

Greetings Damien

**Comment by premiumwd** [comment]
got it.
