### ISSUE TITLE
Is Id token validated as OpenId connect recommends?

### ISSUE THREAD

**Issue by Lempkin** [damienbod/angular-auth-oidc-client#174]
Hi,

Can you confirm that your lib validate id token as said in : 
http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest
part -> 3.1.3.7.  ID Token Validation

Thx

**Comment by damienbod** [comment]
Hi @Lempkin 
yes

http://openid.net/certification/#RPs

Greetings Damien
