### ISSUE TITLE
[Question]: AutoLoginPartialRoutesGuard with additional custom params

### ISSUE THREAD

**Issue by schoes** [damienbod/angular-auth-oidc-client#1761]
**What Version of the library are you using?**
15.0.2

**Question**
How can I use the AutoLoginPartialRoutesGuard and add some customParams ?

**Comment by tboeker** [comment]
I have the same Issue. I want to use the AutoLoginPartialRoutesGuard with capacitor InApp-Browser. That is only possible with a custom urlHandler. So I need to provide customParams. 
Maybe we can Inject a service like "AutoLoginCustomParamsProvider" into the Guard. This provider then creates the customParams,

**Comment by FabianGosebrink** [comment]
Help me understand this: Why do you need a guard to add custom params? You can add custom params in the auth request. The guard is on the way into the app. Is the problem, that custom params are not kept in the route when the request into your app is run through this guard?

**Comment by tboeker** [comment]
The Guard calls ` this.loginService.login(config);` without the authOptions parameter.
Without this parameter, the login is always done with redirect to identity provider.
But i need to open the InApp Browser here.

The AutoLoginPartialRoutesGuard  is a nice feature because of the redirect after login :-)

**Comment by schoes** [comment]
i have one route which uses the AutoLoginPartialRoutesGuard , but i need to add just one param at this exact entry point for the login. when you have a different approach how to handle this. let me know. THX

**Comment by schoes** [comment]
created a PR to support that behaviour
