### ISSUE TITLE
[Question]: Get access token in a synchronous way

### ISSUE THREAD

**Issue by lufo88ita** [damienbod/angular-auth-oidc-client#1765]
**What Version of the library are you using?**
14.1.5

**Question**
In the old versions getAccessToken() return a string, but now return an observable. 
How can I get the access token in a synchronous way?
I need the access token to customize the interceptor.

**Comment by vds-simon-lapointe** [comment]
Use switchMap.

`return this.oidcSecurityService.getAccessToken().pipe(
  switchMap((accessToken) => {
    //Do something custom with the accessToken
    return next.handle(request);
  })
)`
