### ISSUE TITLE
not responding due to a long-running script - IE issue

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [damienbod/angular-auth-oidc-client#177]
I am getting  a strange issue on Internet explorer. After IdentityTokenLifetime expiration, IE is not responding due to “due to a long-running script”. This issue happens only on IE, Chrome works fine. IE is not able renew token silently or some other issue after token renewal don’t know what’s is causing this. 
I am using Identity Server4 for Authentication. I can see Chrome is able to renew token silently and app works fine. Please help

**Comment by damienbod** [comment]
@rajeshmuraleedharan thanks for reporting. Could you give some more info, I would like to reproduce, versions, info how this happens, do you see anything in F12 of the browser?, Is it only IE, or Edge as well
Does it always happen, or just sometimes?

Thanks Damien

**Comment by rajeshmuraleedharan** [comment]
My current version is "angular-auth-oidc-client": "^3.0.9"
This issue is only for IE, couldn't test for Edge yet
IE will get frozen once this happens.
This happens every time when IdentityTokenLifetime  expires and app tries to renew.

**Comment by rajeshmuraleedharan** [comment]
@damienbod 
I tested this on Edge and worked fine. I can see network activity to renew tokens silently. So this issue happens only on IE browser.

**Comment by damienbod** [comment]
Could this be the issue?
https://github.com/damienbod/angular-auth-oidc-client/issues/179

**Comment by rajeshmuraleedharan** [comment]
isomorphic-fetch package fixed the issue. Thank you.
