### ISSUE TITLE
Logout without redirect to IDM server

### ISSUE THREAD

**Issue by TakhirMamirov** [damienbod/angular-auth-oidc-client#178]
If I call .logoff() method, then I'm redirected to identity server, which shows logoff page, and then back to client (if post_logout_redirect_uri is set). Instead, I want a silent logout where I clean the client session and moved directly to start page, not being redirected to idm. How can I do that?

**Comment by damienbod** [comment]
Hi @TakhirMamirov 
You can deactivate the UI stuff on the server and redirect directly back. Client will not notice anything. 

Greetings Damien

**Comment by damienbod** [comment]
Yes, this can all be set per configuration

**Comment by s-triar** [comment]
> If I call .logoff() method, then I'm redirected to identity server, which shows logoff page, and then back to client (if post_logout_redirect_uri is set). Instead, I want a silent logout where I clean the client session and moved directly to start page, not being redirected to idm. How can I do that?

How did you that? my project does not redirect back even though I set post_logout_redirect_uri on angular and backend (client table)
