### ISSUE TITLE
Optional jwks_uri

### ISSUE THREAD

**Issue by feargear** [damienbod/angular-auth-oidc-client#181]
Hello, I noticed that the jwks_uri has to be defined for the client to work. As far as I know, the discovery is an optional feature and our team would love to configure this manually. Luckily our identity server supports this feature, but it's really not something we want to use unless we have to.

http://openid.net/specs/openid-connect-core-1_0.html#DiscoReg

Is it possible to make the jwks_uri optional for a future release?

Thanks

**Comment by damienbod** [comment]
@feargear The lib only supports the whole discovery as optional. Then in the well known end points, you can define the jwk document, where the jwk json can be found.

**Comment by feargear** [comment]
@damienbod Ok, thanks
