### ISSUE TITLE
[Bug]: many types are wrong

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#1818]
### Version

latest

### Please provide a link to a minimal reproduction of the bug

https://github.com/damienbod/angular-auth-oidc-client/blob/8f4553aadd3e54f182a8388a26fbc293913b4745/projects/angular-auth-oidc-client/src/lib/auth-state/auth-state.service.ts#L81-L84

### Please provide the exception or error you saw

```true
getAccessToken returns null
```

### Steps to reproduce the behavior

```true
call getAccessToken before authenticating
```

### A clear and concise description of what you expected to happen.

```true
As can be seen here, some functions can return null but do not.
I think the typescript config should be much more strict to detect all these issues and fix them.

https://github.com/damienbod/angular-auth-oidc-client/blob/8f4553aadd3e54f182a8388a26fbc293913b4745/projects/angular-auth-oidc-client/src/lib/auth-state/auth-state.service.ts#L81-L84
```

### Additional context

It is a great waste of time to have to check the source code when I call a function because I do not trust this library to return  what it says it does.
Also, I do this because I has two many issues with cannot access x of null. Most people will trust the code and will have it blew in there face in production because a session has expires or something like this.

**Comment by FabianGosebrink** [comment]
Sorry if we have not fulfilled this completely, but saying something is a "waste of time" is not very polite in my opinion. 

However. I wanted to plan to enable the strict mode anyway to avoid this kind of issues, and hopefully the lib then fulfills your expectations.

Thanks for using.

**Comment by yelhouti** [comment]
@damienbod sorry if my comment came out as rude, that was not the purpose at all (English is my third language). I really appreciate all the work you did and keep doing on the project.
What I meant is that I spent a lot of time (an maybe others two) trying to figure out why my code broke in production and avoiding that happening again.
Your library is great and I am using it in many projects :) .
Thanks a lot :bow:

**Comment by FabianGosebrink** [comment]
Hey, no worries, all good. Thanks for the appreciation, we really enjoy reading this and are glad that you are using the lib in other projects. 

You are totally correct: We should add the strict mode, I wanted to do that for a long time, so thank you for the heads-up! We will get better there and make the library more reliable. 

Thanks ❤️
