### ISSUE TITLE
[Bug]: Silent renew periodic check doesn't run on page reload

### ISSUE THREAD

**Issue by smithbrianscott** [damienbod/angular-auth-oidc-client#1831]
### Version

16.0.0

### Please provide a link to a minimal reproduction of the bug

Unable to provide a link as it would contain the details of our IDP and require login

### Please provide the exception or error you saw

```true
I have set up silent renew and it works without problem, until the page is refreshed then I notice the event that states, 'silent renew, periodic check finished!' no longer is logging. 

I noticed this when working on the app locally and updating the code causing the site to refresh multiple times on code save.

If this is a configuration issue on myside, my apologies, please let me know what should be changed.
```

### Steps to reproduce the behavior

```true
1. Set up the project to use silent renew (see additional context for module configuration).
2. Set up a route that uses the AutoLoginPartialRoutesGuard
3. Load the app and hit the route that is protected and it will log you in via your IDP. Afterwhich, you will notice the logs in the console that silent renew is checking periodically.
4. Reload the page and notice that silent renew is no longer checking periodically.
```

### A clear and concise description of what you expected to happen.

```true
I would expect that even if the user using the app decides to reload the app, that silent renew will continue to check periodically and not force the user to login after each time the token expires.
```

### Additional context

Auth Module Configuration:

```
AuthModule.forRoot({
      config: {
        authority: environment.auth.authority,
        redirectUrl: window.location.origin + `/pages/callback`,
        postLogoutRedirectUri: window.location.origin + `/pages/logged-off`,
        clientId: environment.auth.clientID,
        secureRoutes: [
          'http://localhost/project',
          environment.auth.secureRoute,
        ],
        scope: `openid profile email ${environment.auth.scopes}`, // 'openid profile ' + your scopes
        responseType: 'code',
        silentRenew: true,
        useRefreshToken: true,
        renewTimeBeforeTokenExpiresInSeconds: 600,
        unauthorizedRoute: '/pages/unauthorized',
        logLevel: LogLevel.Debug,
      },
    }),
```

Routes
```
export const DEMO_ROUTES: Routes = [
  {
    path: '',
    component: ParentDemoComponent,
    children: [
      {
        path: 'demo',
        canActivate: [AutoLoginPartialRoutesGuard],
        data: { title: 'Demo' },
        component: DemoComponent,
      },
      {
        path: '',
        redirectTo: 'demo',
        pathMatch: 'full',
      },
    ],
  },
];
```

On initial login, I see this happening about every 3 or 4 seconds
![image](https://github.com/damienbod/angular-auth-oidc-client/assets/19986009/8234d301-52ec-4d9f-924d-11b39b62e7f0)

After I reload the page, it will no longer check every 3 or 4 seconds, however on a navigation event within the app, there is a check for access token validity but no more periodic check for silent renew. Even if the user is using the app continuously, once the token expires, it is not being exchanged and will cause the user to login again.
![image](https://github.com/damienbod/angular-auth-oidc-client/assets/19986009/ce6ff186-c5fc-431d-b06d-de39dd14b408)

**Comment by davidsarkany** [comment]
I have same issue #1828

**Comment by smithbrianscott** [comment]
> I have same issue #1828

I am running version 16.0.0 so upgrading in your case doesn't seem to resolve it.

**Comment by ThorstenKunz** [comment]
There seems to be more broken than the silent refresh. I also don't get any events from `OidcSecurityService.userData$` when a refresh occures. Which means no userData related content is showing up anywhere on the page at all after a refresh. Once it is broken even a full reload is not helping. I have to create a whole new browser session in order to fix the issue.

**Comment by ThorstenKunz** [comment]
You can actually reproduce the issue with your own example: run `start-sample-code-flow-auto-login-all-routes`. Once you have logged in and the page shows your userData objects just press ctrl+F5. This will refresh the page and fully clear the userData object and not even a shift+F5 reload will bring it back.

**Comment by smithbrianscott** [comment]
Is there an update on this bug? ETA or planned start? This is the only bug preventing us from moving forward with using this library. I appreciate it!

**Comment by FabianGosebrink** [comment]
Is this bug reproducible with the samples the library provides?

**Comment by ThorstenKunz** [comment]
> Is this bug reproducible with the samples the library provides?

Yes, please see my comment from 3 weeks ago: https://github.com/damienbod/angular-auth-oidc-client/issues/1831#issuecomment-1701384055

**Comment by FabianGosebrink** [comment]
We have to remove this `-login-all-routes` sample. This is not a realistic point. Will have a look as soon as I got time.

**Comment by ThorstenKunz** [comment]
> We have to remove this `-login-all-routes` sample. This is not a realistic point. Will have a look as soon as I got time.

What other sample would you recomment to use if you want to force a login for all routes in your app?

**Comment by FabianGosebrink** [comment]
You can not have _all_ routes protected in your app. This is not possible with an SPA. You need one public place to have a redirect to set up the auth. https://angular-auth-oidc-client.com/docs/documentation/auto-login#auto-login-when-all-routes-are-guarded 

However, you are correct that the sample is not correct. I am looking into it and will fix the sample to avoid the issues.

**Comment by ThorstenKunz** [comment]
> You can not have _all_ routes protected in your app. This is not possible with an SPA. You need one public place to have a redirect to set up the auth. https://angular-auth-oidc-client.com/docs/documentation/auto-login#auto-login-when-all-routes-are-guarded
> 
> However, you are correct that the sample is not correct. I am looking into it and will fix the sample to avoid the issues.

Yeah, I know we need the callback route to be public. But everything else should be guarded and I really appreciate your help with this.

**Comment by smithbrianscott** [comment]
Mine is working now. I found that by creating a route called 'callback' and only using it during initial login that on page load, the 'checkAuth' is not being fired and in turn not setting up the refresh token periodic check. I added 'checkAuth' to the app.component.ts and it is now working as expected.

**Comment by RakouskyS** [comment]
@smithbrianscott 

> Mine is working now. I found that by creating a route called 'callback' and only using it during initial login that on page reload, the 'checkAuth' is not being fired and in turn not setting up the refresh token periodic check. I added 'checkAuth' to the app.component.ts and it is now working as expected.

Hi! Do you still have the callback route, which calls the checkAuth, in addition to the checkAuth in your app.component.ts?

I think had the same setup as you did before. 

1. Open the page
2. get redirected to /login-page
3. login-page.component.ts calls checkAuth() (in my own authService)
4. get redirected to identity server
5. login
6. get redirected to /callback
7. callback.component.ts calls checkAuth() (in my own authService)
8. authService redirects to main page

I would now add another checkAuth (not in my authService) in the app.component.ts.
Did you get rid of the loginpage/callback page or did you add another checkAuth in your app.component.ts as I am planning to do?

Thanks for you help.

**Comment by FabianGosebrink** [comment]
We updated the sample. You do not need the `checkAuth()` in the callback-route directly, because the app.component normally hosts the router outlet and therefore the callback.component. However, it is in your project: Just make sure an unauthenticated state can call the checkauth, when it returns from the IDP ;)

**Comment by smithbrianscott** [comment]
@RakouskyS 
> @smithbrianscott
> 
> > Mine is working now. I found that by creating a route called 'callback' and only using it during initial login that on page reload, the 'checkAuth' is not being fired and in turn not setting up the refresh token periodic check. I added 'checkAuth' to the app.component.ts and it is now working as expected.
> 
> Hi! Do you still have the callback route, which calls the checkAuth, in addition to the checkAuth in your app.component.ts?
> 
> I think had the same setup as you did before.
> 
> 1. Open the page
> 2. get redirected to /login-page
> 3. login-page.component.ts calls checkAuth() (in my own authService)
> 4. get redirected to identity server
> 5. login
> 6. get redirected to /callback
> 7. callback.component.ts calls checkAuth() (in my own authService)
> 8. authService redirects to main page
> 
> I would now add another checkAuth (not in my authService) in the app.component.ts. Did you get rid of the loginpage/callback page or did you add another checkAuth in your app.component.ts as I am planning to do?
> 
> Thanks for you help.

I do not have a login-page component as I just use the AutoLoginPartialRoutesGuard on routes that needs to be secured by authentication. I 'moved' checkAuth to app.component.ts but I still have a callback.componet.ts file that is now empty (meaning it doesn't checkAuth anymore) and does nothing but be an open route that is not secured by a guard so that the authentication provider can have a redirect that isn't hitting a secured routed. The checkAuth in app.component is all that is needed and can be removed from callback component.
