### ISSUE TITLE
[Question]: How can i use the OidcSecurityService to implement canActivateFn?

### ISSUE THREAD

**Issue by davidmathew** [damienbod/angular-auth-oidc-client#1870]
import { inject } from '@angular/core';
How to implement a simple CanActivateFn  using isAutheticated$?

import { ActivatedRouteSnapshot, CanActivateFn, RouterStateSnapshot, UrlTree } from '@angular/router';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { Observable } from 'rxjs';

export const authGuardGuard: CanActivateFn = (
  route: ActivatedRouteSnapshot, 
  state: RouterStateSnapshot):
  | Observable<boolean | UrlTree>
  | Promise<boolean | UrlTree>
  | boolean
  | UrlTree => {
  //logic
    return true
    
};

**Comment by cedbesafilm** [comment]
https://angular-auth-oidc-client.com/docs/documentation/guards

**Comment by davidmathew** [comment]
i have written the authguard as follows:

```
import { inject } from '@angular/core';
import { ActivatedRouteSnapshot, CanActivateFn, Router, RouterStateSnapshot, UrlTree } from '@angular/router';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { Observable, map, take } from 'rxjs';


export const authGuardGuard: CanActivateFn = (
  route: ActivatedRouteSnapshot, 
  state: RouterStateSnapshot):
  | Observable<boolean | UrlTree>
  | Promise<boolean | UrlTree>
  | boolean
  | UrlTree => {

    const oidcSecurityService = inject(OidcSecurityService);
    const router = inject(Router);
    return oidcSecurityService.isAuthenticated$.pipe(
      take(1),
      map(({isAuthenticated}) => {
        console.log(isAuthenticated);
        if (!isAuthenticated) {
          router.navigate(['unauthorised']);
          return false;
        }
        return true;
      })
    )
    
};
```

Even though from the login click the isAuthenticated is true, once it reached the authguard it is getting it as false.

**Comment by davidmathew** [comment]
This is resolved. I just had to add the following in app.module in config.
```
postLoginRoute:"/home",
```
