### ISSUE TITLE
[Feature Request]: Upgrade to Angular 17

### ISSUE THREAD

**Issue by alexgelb1** [damienbod/angular-auth-oidc-client#1873]
**Describe the solution you'd like**
At the moment the last supported version of Angular is Angular 16 as written in the documentation.
Is there planned to do an Upgrade to Angular 17 soon?

**Comment by davidsarkany** [comment]
Duplicated #1861

**Comment by FabianGosebrink** [comment]
Yes, as soon as we got time we want to upgrade. Thanks!

**Comment by ABDUGO** [comment]
Just add key `main` into `build` object in project file `angular.json` and it will works inshaAllah,

![image](https://github.com/damienbod/angular-auth-oidc-client/assets/11174691/a4d3b246-9f06-4a45-b01b-dc7d6288fb3a)
