### ISSUE TITLE
[Question]: why are unit tests failing in with "NullInjectorError: No provider for HttpClient!" ?

### ISSUE THREAD

**Issue by diegobayshanntech** [damienbod/angular-auth-oidc-client#1875]
**What Version of the library are you using?**
Main branch at commit d71e3bf093fd27547ef4db7e726e3794f36648d5 (Nov 30 2023)

** Environment
Angular CLI: 16.0.2
Node: 20.8.0 (Unsupported)
Package Manager: npm 10.1.0
OS: darwin arm64

Angular: 16.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.2
@angular-devkit/build-angular   16.0.2
@angular-devkit/core            16.0.2
@angular-devkit/schematics      16.0.2
@schematics/angular             16.0.2
ng-packagr                      16.0.1
rxjs                            7.8.1
typescript                      5.0.4

**Question**
Hi, this could be user error, hence phrasing it as a question. I am trying to run the unit tests for the sample project "sample-code-flow-refresh-tokens" but am getting `NullInjectorError: No  provider for HttpClient!`. What am I missing ?

Steps to reproduce"
1. `git clone git@github.com:damienbod/angular-auth-oidc-client.git`
2. `cd angular-auth-oidc-client/`
3. `npm install`
4. `ng build angular-auth-oidc-client`
5. `ng build sample-code-flow-refresh-tokens`
6. `ng test sample-code-flow-refresh-tokens`
7. --> Fails with:   
```
NullInjectorError: R3InjectorError(DynamicTestModule)[OidcSecurityService -> CheckAuthService -> SilentRenewService -> FlowsService -> CodeFlowCallbackHandlerService -> DataService -> HttpBaseService -> HttpClient -> HttpClient]: 
          NullInjectorError: No provider for HttpClient!
```

**Comment by diegobayshanntech** [comment]
OK, did some more research, I think the test needs some updating:

```
import {TestBed, waitForAsync} from '@angular/core/testing';
import { AppComponent } from './app.component';
import {HttpClientTestingModule} from '@angular/common/http/testing';
import {AuthConfigModule} from "./auth-config.module";

describe('AppComponent', () => {
  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      declarations: [AppComponent],
      imports: [HttpClientTestingModule, AuthConfigModule],
    }).compileComponents();
  }));
```

It looks like none of the tests in this project have been maintained ?

**Comment by FabianGosebrink** [comment]
Hey, yes, the tests of the app are not maintained. We want to switch to jest anyway. The tests of the lib are maintained. We are taking PRs btw :)
