### ISSUE TITLE
Support for authorization code flow

### ISSUE THREAD

**Issue by b-wins** [damienbod/angular-auth-oidc-client#189]
Hi -

Because of my application structure, I'm looking to use authorization code flow and pass the code to a backend server which will take over from there.

Does this library have any way to support that? Or ideas of a different one you played with?

Thanks,

B Wins

**Comment by damienbod** [comment]
Hi @b-wins 
No This library is for SPA angular applications. Angular applications should use the OIDC Implicit Flow. Server tech. libs which support OIDC, can support the authorization code flow. Which tech do you use? 

Greetings Damien

**Comment by b-wins** [comment]
I have an Angular SPA however my use case is not the typical. My SPA talks to a secured RESTful API which is secured with a pretty complex system. It generates its own token when it receives either a username/password or an auth code that it exchanges for a valid token.

**Comment by damienbod** [comment]
You could take the src code, and create you custom case yourself.

Greetings Damien

**Comment by damienbod** [comment]
@b-wins I'm going to close this as the lib will not support this flow. SPAs should always use the OpenID Implicit Flow, and I do not want to confuse people with custom flows.

Greetings Damien

**Comment by SaltyDH** [comment]
With Angular support in Native app frameworks such as Ionic and NativeScript, it would be great if this could be reconsidered. There's a lot of discussions recently about moving away from Implicit flow even for SPAs.

**Comment by damienbod** [comment]
@SaltyDH Yes, native apps should always use the authorization Code Flow with PKCE... I was thinking about this, but AppAuth does this good (Android, IOS). At present no solution exists for doing Angular apps and native apps securely from one code base. 

The best solution for doing security in an SPA is an implemention using the OIDC Implicit Flow specification, other solutions/suggestions, examples are not the recommended way. There are lots of angular security examples doing this insecurely with bad recommendations.

**Comment by SaltyDH** [comment]
Thanks @damienbod. I seem to have stumbled across the bad examples over the past few days! We're doing a lot of code sharing between mobile and browser based Angular apps and I have been looking for that unified solution which allows me to use one flow for browser and mobile alike - reduction in testing and code maintenance being the main driver.

**Comment by ttothebrown** [comment]
@damienbod You should look here:

Directly from Oauth's site: https://oauth.net/2/grant-types/implicit/

So the information you are basing this on is outdated.

**Comment by damienbod** [comment]
@ttothebrown really interesting, thanks for the links. I ask around for some opinions

**Comment by ttothebrown** [comment]
@damienbod thank you for the resource. So it looks like they are considering it, but there's more implications that need to be thought out.

**Comment by damienbod** [comment]
Hi @andifalk yes, I'm following this discussion. The specs is a first draft with lots of open issues and the recommendations are just an opinion. When the draft becomes support from the IETF and the problems with this flow are solved, then great. 

I will re open this, and do start with supporting this flow. There is a lot of noise about this at the moment, buzt this opinion is still not standard or best practice. A lot of stuff in this draft also exists when using OIDC Implicit Flow with CSP and so on. The doc compares with OAuth2 Implicit Flow. 

I continue to flow the discussions and recommendations about this.

Thanks for your comment.

Greetings Damien

**Comment by andifalk** [comment]
Hi @damienbod yes, storing of the tokens in the unsecure client is another problem that is currently discussed a lot. One solution discussed often here is here to store token inside a cookie (with httponly and secure flags set) plus adding CSRF protection.

**Comment by damienbod** [comment]
@andifalk Using cookies like this is not a better solution for SPAs, works good for server rendered Web application though.

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/pull/363

**Comment by damienbod** [comment]
@andifalk @b-wins @SaltyDH @ttothebrown 

If the reviews are ok, I add this to the next version. See PR
