### ISSUE TITLE
[Question]: Use with Angular 17

### ISSUE THREAD

**Issue by agilulf-dev** [damienbod/angular-auth-oidc-client#1890]
**What Version of the library are you using?**
15.0.4
...

**Question**
Is possible to use version **16.0.1** in an Angular 17 project?
The project seems to be updated to the latest release of Angular 17, but still not released.

Thank you!

**Comment by schoes** [comment]
@agilulf-dev Yes it works. We have already upgraded to Angular 17 and are using the lib in version 16.0.1 without any issues

**Comment by agilulf-dev** [comment]
Thank you so much!!!
