### ISSUE TITLE
ValidateStateFromHashCallback failed, state: undefined 

### ISSUE THREAD

**Issue by mikeandersun** [damienbod/angular-auth-oidc-client#194]
I'm confusing what happen in  `this.stateValidationService.validateState(result, jwtKeys)`  method of the lib. The `resukt `and `jwtKes `are present but  I get this warring and can't  validate the tokens:

```
ValidateStateFromHashCallback failed, state: undefined local_state:15206489476250.9600014463464683
authorizedCallback incorrect state
```
As you can see the state return from server callback via url fragment. I think the code don't retrieve state from the fragment . 
Why state: **undefined**  ?!
I use **4.0.3** with  **angular 6.0.0-beta.7**
Sorry for this splash issue. :)

`http://localhost:65000/home#id_token%3DeyJhbGciOiJSUzI1NiIsImtpZCI6IjkxMTQ1YzU4OWUwZDRjMzBjMzk5YzdmMjE1NzVhY2NkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MjA2NDkzNDIsImV4cCI6MTUyMDY0OTY0MiwiaXNzIjoiaHR0cDovL2lkLnZuZXh0LmxvY2FsIiwiYXVkIjoicmVzZWFyY2hpbmciLCJub25jZSI6Ik4wLjg3ODI0OTk3ODgxODc5MzkxNTIwNjQ5MzQyNjQ0IiwiaWF0IjoxNTIwNjQ5MzQyLCJhdF9oYXNoIjoiV1llSDNVUm1WVnRXaWw3LVcxa3J3QSIsInN1YiI6IjEzY2I0NmQ3LWM1ZmEtNDVkZi1iMTFmLThjM2Y4N2EyZGZmMiIsImF1dGhfdGltZSI6MTUyMDY0NzcwMywiaWRwIjoibG9jYWwifQ.Om1D16M3nQGmEArHUYRbAz8KgoaujbAIEhtWaYt8gSsANNqSFtcp8gJjP_cfcjUNsCrtWQAzXI4gIZIck0hDteBoN576AgIW0OZcCHO-5PZMf9fU5Kgtq3WBvlwRo6Tq7hEQfcXmWgxNO1XxVy_eHcMEyDLGIpbkg2WLpZX9IEiRV01gq5dHv8MO6IpFR-coWBI8tohtmJfGYXhvn0KWHJ53926L4DLxzzUfU0aR2hNXlD7Ex6083z1W26TENO8uZ4LUB_iF_HXOveNm8Ya5l7Cf_lTA9CVAMq2WkRcWulaa8QkUmHbcD3P59CHYljn0d7O28GPuLV-l1FJDEsf5bg%26access_token%3DeyJhbGciOiJSUzI1NiIsImtpZCI6IjkxMTQ1YzU4OWUwZDRjMzBjMzk5YzdmMjE1NzVhY2NkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MjA2NDkzNDIsImV4cCI6MTUyMDY1Mjk0MiwiaXNzIjoiaHR0cDovL2lkLnZuZXh0LmxvY2FsIiwiYXVkIjoiaHR0cDovL2lkLnZuZXh0LmxvY2FsL3Jlc291cmNlcyIsImNsaWVudF9pZCI6InJlc2VhcmNoaW5nIiwic3ViIjoiMTNjYjQ2ZDctYzVmYS00NWRmLWIxMWYtOGMzZjg3YTJkZmYyIiwiYXV0aF90aW1lIjoxNTIwNjQ3NzAzLCJpZHAiOiJsb2NhbCIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJlbWFpbCJdfQ.pW2Ve2a2T8azFEAnghC1iQlbcq20sA6dEEZLEVyTXfGnoo2EQW2YWGaI6DDC-XXv28WCh3UYnjYyPd-ahW6ja4uZlmENeeRjhzxx8PZwaWFO_u49dOo2DI7W_nh92d8d4imnQpEOsA6ZzMKpSlXbrZ31394LTWg7QGRW0xPNqH79ERnTFyapGI4YMYPk5zZHjW4UkkPd9WA9dNoHnAm1PBBpCo6GDay5IzoVh6pDXQb6LMYVeY1IDDgfQnp8EN8D85KuxGsaM5d7xjjSw3pCNnZAWTTOI_tiDMWGBvsSANII65bXJfalcG4Eq46uBXKPIaFDbc-6IFqCW3d7Gdc63A%26token_type%3DBearer%26expires_in%3D3600%26scope%3Dopenid%20profile%20email%26state%3D15206489476250.9600014463464683`

**Comment by mikeandersun** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/195

**Comment by mikeandersun** [comment]
It seem that is related to angular ,please see  [this question](https://stackoverflow.com/questions/49220150/error-no-state-in-response-after-callback-in-oidc-client-js) on SO.

**Comment by vsimeonoff** [comment]
It is caused by URI encoding of state in the window.location.hash. 
For me this fix the issue:

` if (window.location.hash) {`
` window.location.hash = decodeURIComponent(window.location.hash);`
` // authorizedCallback returns wrong result when hash is URI encoded`
 `     this.oidcSecurityService.authorizedCallback();`
`    } else {`
`      this.oidcSecurityService.authorize();`
`    }`
