### ISSUE TITLE
Azure B2C auto log in - authorizedCallback incorrect state, token(s) validation failed, resetting

### ISSUE THREAD

**Issue by alvipeo** [damienbod/angular-auth-oidc-client#195]
I've tried many things in order to make this sample to work but no way https://github.com/alvipeo/oidc-azure-b2c-not-working.

I got the right token from Azure B2C but for some reason I get in the console the following:
 - authorizedCallback created, begin token validation
 - jwks_uri: https://login.microsoftonline.com/bptst.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_susi
 - ValidateStateFromHashCallback failed, state: undefined local_state:15207528662090.5646689947174761
 - authorizedCallback incorrect state
 - authorizedCallback, token(s) validation failed, resetting

and it always redirects me to *unauthorized* page.

I looked at the token with https://jwt.ms/ and it seems correct to me. So why would I get validation failed?

Please help. Clone the repo and use *server.cmd* or just *ng serve --port 4200 --aot --watch*.

**Comment by mikeandersun** [comment]
What is you angular version?

**Comment by alvipeo** [comment]
5.2.8

**Comment by alvipeo** [comment]
I tried 5.2.7 - same error (updated the repo)

**Comment by damienbod** [comment]
Looks like this is a breaking change in the angular 5.2.8 version, and it wasn't even mentioned in the release notes...

Here's a fix for now:

if (window.location.hash) {
window.location.hash = decodeURIComponent(window.location.hash);
// authorizedCallback returns wrong result when hash is URI encoded
this.oidcSecurityService.authorizedCallback();
} else {
this.oidcSecurityService.authorize();
}

**Comment by damienbod** [comment]
fixed in Angular version 5.2.9
