### ISSUE TITLE
[Bug]: Fix Quality build standalone.js

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#1951]
### Version

17.1.0

### Please provide the exception or error you saw

```true
https://github.com/damienbod/angular-auth-oidc-client/actions/runs/9320374483
```

**Comment by timdeschryver** [comment]
Let me know if you need help with this.
I should be able to clear some time next week for this.

In the worst case we can downgrade the angular schematics, or copy paste the older implementation in order to release a new version.
