### ISSUE TITLE
[Bug]: Expected double-quoted property name in JSON at position 709

### ISSUE THREAD

**Issue by Braincompiler** [damienbod/angular-auth-oidc-client#1967]
### Version

18.0.0

### Please provide the exception or error you saw

When running `npx ng add angular-auth-oidc-client` and after entering an URL (or anything else) to the prompt "Please enter your authority URL or Azure tenant id or Http config URL" the schematic crashes with the error `Expected double-quoted property name in JSON at position 709`. It doesn't matter what is entered at this point, it crashes immediately. (See screenshot below)

### Steps to reproduce the behavior

```true
1. > npx ng add angular-auth-oidc-client
2. Select the flow
3. Enter the Authority URL
4. ⚡️
```

### Additional context

![image](https://github.com/damienbod/angular-auth-oidc-client/assets/142524/9d06d6a8-3646-4b63-a368-e0f576ccf39c)

**Comment by timdeschryver** [comment]
Can you try this is a new application @Braincompiler ?
I tried to reproduce this but without success.
I'm thinking that the `package.json` isn't correctly formatted, you can also check that.

![image](https://github.com/damienbod/angular-auth-oidc-client/assets/28659384/f42ac142-dcd2-4bda-9e41-94ffc68fafed)

**Comment by Braincompiler** [comment]
Your are right, but in my case it was the angular.json where I comment out the line with the "zone.js" polyfill which I don't use in that project. So the angular cli is fine with that (maybe because they support json5) but in the schematic it will fail. 

![image](https://github.com/damienbod/angular-auth-oidc-client/assets/142524/b32e0dd7-5581-4a26-892d-a51f08954797)

In my current project I was then creating the config by myself, which is working as expected, since I used your lib in many projects before :)

So bug is closed, thanks for pointing out 👍
