### ISSUE TITLE
[Question]: Async provider loader with provideAuth

### ISSUE THREAD

**Issue by Liotarne** [damienbod/angular-auth-oidc-client#1971]
**What Version of the library are you using?**
Working with Angular 18+ and "angular-auth-oidc-client": "18.0.0",
...

**Question**
How can I implement the loader factory "provideAuth" with Angular 18 please ?

Here is my `app.config.ts` 

```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideAuth({
      loader: {
        provide: StsConfigLoader,
        useFactory: () => new StsConfigHttpLoader(from(getAuthConfig()))
      }
    })
  ],
};
```

And the config loader:

```typescript
const makeStsConfig = (realm): OpenIdConfiguration => {
  const config: OpenIdConfiguration = {
    // Interpreted config
  };

  return config;
};

export const getAuthConfig = async (): Promise<OpenIdConfiguration> => {
  const realm = await getRealm();
  return makeStsConfig(realm);
};
```

I followed the exemple here: https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html 

For an implementation with a static config. It works well with it but not when it comes with a loader.

I need to load the config dynamically and asynchronously.

Thanks for your help !

**Comment by pandanirio** [comment]
I am experiencing the same problem. Due to business requirements, I need to load the OIDC configuration from an API.

It worked with the HTTP loader in the old module implementation, but since upgrading to Angular 18, I cannot find a solution to use an async loader with `provideAuth` standalone implementation.

**Comment by Liotarne** [comment]
It works well !

Thanks for your help @timdeschryver !

I close this issue

PS: My problem was the call of useFactory as an arrow function.

**Comment by rashmidubeyv** [comment]
I am getting the error: could not find matching config for state ${stateParamFromUrl} when I dynamically load the config (using StsConfigHttpLoader) Please see the below reported issue, kindly let me know what could be happening wrong here-

https://stackoverflow.com/questions/78980789/error-could-not-find-matching-config-for-state-when-using-stsconfighttploader?noredirect=1#comment139257694_78980789
