### ISSUE TITLE
Silent Renew failing?

### ISSUE THREAD

**Issue by Jonesie** [damienbod/angular-auth-oidc-client#198]
I seem to be getting regular (?) auth failures after about maybe 10 minutes.

My config has silent_renew set to true.  I can see logged activity in the console but Im really new to this so dont really know where to start.  Not really an issue except for me I guess :/  I was hoping it 'would just work'.

**Comment by Jonesie** [comment]
My config is loaded from this:

    "stsServer": "blah",
    "redirect_url": "blah blah",
    "client_id": "thingyclient.js",
    "response_type": "id_token token",
    "scope": "openid profile api.v1",
    "post_logout_redirect_uri": "http://blah",
    "start_checksession": true,
    "silent_renew": true,
    "startup_route": "/design",
    "forbidden_route": "/forbidden",
    "unauthorized_route": "/unauthorized",
    "log_console_warning_active": true,
    "log_console_debug_active": false,
    "max_id_token_iat_offset_allowed_in_seconds": 10

**Comment by damienbod** [comment]
@Jonesie This should just work :) Could you check the network traffic, and post it, and maybe also the STS client configuration.

Greetings Damien

**Comment by Jonesie** [comment]
This is failing on my dev machine locally.  Probably also on my test server.
I just increased max_id_token_iat_offset_allowed_in_seconds to 60 but that shouldnt effect locally.

**Comment by Jonesie** [comment]
Im thinking this might just a dev issue with angular restarting when I save changes.  I'll close this for now and research further if it happens live.
Cheers
