### ISSUE TITLE
Documentation website down

### ISSUE THREAD

**Issue by timdeschryver** [damienbod/angular-auth-oidc-client#1982]
I just wanted to create this issue in case you aren't aware of it, but it appears that the website is down.
If you're currently looking for the docs see https://nice-hill-002425310.azurestaticapps.net until the main website is back up.

https://angular-auth-oidc-client.com
![image](https://github.com/user-attachments/assets/8ba373d4-7622-4c79-b845-e4f0ff44441c)

**Comment by FabianGosebrink** [comment]
Just had a look at this and can not find any strange things. This is weird....
