### ISSUE TITLE
[Bug]: Sample & Documentation site is down (404)

### ISSUE THREAD

**Issue by MonDeveloper** [damienbod/angular-auth-oidc-client#1986]
### Version

*

### Please provide a link to a minimal reproduction of the bug

https://angular-auth-oidc-client.com/

### Please provide the exception or error you saw

```true
the site hosting samples and documentation (https://angular-auth-oidc-client.com/) is down
```

### Steps to reproduce the behavior

```true
https://angular-auth-oidc-client.com/
```

### A clear and concise description of what you expected to happen.

```true
always return 404
```

**Comment by timdeschryver** [comment]
This is a duplicate of #1982

**Comment by FabianGosebrink** [comment]
Should work again :)
