### ISSUE TITLE
Get lib certified

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#2]

**Comment by damienbod** [comment]
http://openid.net/certification/

http://openid.net/certification/rp_testing/

https://github.com/openid-certification/oidctest

**Comment by damienbod** [comment]
http://openid.net/wordpress-content/uploads/2016/12/OpenID-Connect-Conformance-Profiles.pdf

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/16

**Comment by damienbod** [comment]
https://github.com/openid-certification/oidctest/issues/27

**Comment by damienbod** [comment]
@FabianGosebrink @robisim74 

The RP Implicit certification tests have been sent. Version 1.0.2

Will do the RP Config next.

**Comment by damienbod** [comment]
http://openid.net/certification/#RPs Implicit RP is norw Certified 

Now the Config RP

**Comment by robisim74** [comment]
Great!

**Comment by damienbod** [comment]
Do config tests

**Comment by damienbod** [comment]
Tests:

rp-discovery-openid-configuration
rp-discovery-issuer-not-matching-config
rp-discovery-jwks_uri-keys
rp-key-rotation-op-sign-key

**Comment by damienbod** [comment]
RP Config certification started

**Comment by damienbod** [comment]
RP Config is now certified.

https://openid.net/certification/#RPs
