### ISSUE TITLE
Sending credentials to fetch token

### ISSUE THREAD

**Issue by vicver82** [damienbod/angular-auth-oidc-client#20]
Hi,
This might be a question that has a trivial answer, but I'm new to Angular and OIDC.

In order to get a token, where do I specify the Authorization (in header of POST request), and grant_type, username and password (in POST request's body) in the code?

Thanks a lot for your support and for your work!

**Comment by damienbod** [comment]
Hi @vicver82 , yes
First you login on the server, the SPA should not deal with user, passwords. A login button redirects you the the server where you login and then you're redirected back the the angular application where you have a token and an id_token.


https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/dataeventrecords/DataEventRecordsService.ts#L27

Greetings Damien

**Comment by vicver82** [comment]
Thank you for your reply @damienbod !
It turns out we are using Hybrid flow with OIDC, which is why I couldn't make this library work.

**Comment by damienbod** [comment]
Ah ok, you should not use the hybrid flow with a pure Angular SPA.

**Comment by vicver82** [comment]
Thanks for your support @damienbod !
