### ISSUE TITLE
[Question]: Can I use this lib without "OIDC"?

### ISSUE THREAD

**Issue by Chris81T** [damienbod/angular-auth-oidc-client#2001]
**What Version of the library are you using?**
I'm using version ^18.0.1 with Angular ^18.2.0.

**Question**
I want to use with my angular app two different external provided api's (over which I have no influence). Both of them are using OAuth 2 for auth. In order not to implement the entire OAuth workflow myself, I looked for existing Angular libraries and came across these.

After I integrated the lib and adjusted the configuration, I fail when using the first external API because the GET request ".../.well-known/openid-configuration" returns a 404 not found.

I then contacted API support to see if there was an alternative URL for the "well-known" request, but all I received was the answer:

> "At this time our API only supports Oauth2.0 for authentication, if possible we recommend moving forward with Oauth2 and the PKCE flow for authorization."

Is there a way to use this lib so that it only handles the "plain" OAuth PKCE flow without OpenID Connect?

If it's possible, what exactly would I need to do to achieve this?

Thank you for the support!

**Comment by damienbod** [comment]
Problem if you disable some of the validation checks, you will a a version which works with the legacy IDP. You should look at updating the IDP.
