### ISSUE TITLE
jsrsasign & bundle size

### ISSUE THREAD

**Issue by mseknibilel** [damienbod/angular-auth-oidc-client#201]
Hi,

the jsrsasign is adding about 200 kb to the final bundle (after minification and tree shaking). is there something to do about it please ?

The jsrsasign is huge swiss knife (non-shakable), why don't you just select what you need.
![capture](https://user-images.githubusercontent.com/1716566/37699915-e624c606-2ce9-11e8-846e-30a9640adb67.PNG)

**Comment by mseknibilel** [comment]
![image](https://user-images.githubusercontent.com/1716566/37699941-0031dc6e-2cea-11e8-9639-3b4af4f42fb1.png)

**Comment by damienbod** [comment]
@mseknibilel this makes sense, but I would need time to find out what bits are required. If you want, you can create a PR

Greetings Damien

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/26

**Comment by damienbod** [comment]
Will continue this on issue #26
