### ISSUE TITLE
[Question]: Can two different client-id and identity providers be used in the same page?

### ISSUE THREAD

**Issue by Serge-Libotte** [damienbod/angular-auth-oidc-client#2012]
Hello, given the documentation it seems the authn service is always a singleton with a unique configuration.
What if two APIs are protected by two different IdP?
I posted the same question about another framework: https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1437
Looking at the code, the use of storage is very similar and will give the same issue.
Is there a solution foreseen for this? (or am I worrying for nothing)

**Comment by FabianGosebrink** [comment]
Yes, we do support multiple configurations in this lib.
