### ISSUE TITLE
upgrade RxJx 

### ISSUE THREAD

**Issue by mikeandersun** [damienbod/angular-auth-oidc-client#202]
The rc release of angular upgrade `RxJx` to `6.0.0-beta.0 ` that incompatible with code base of this lib . 
My app is an in progress with angular 6.x . 
Can you release a beta version at least for developer like me?

**Comment by kochax** [comment]
"angular-auth-oidc-client": "4.1.0"
"rxjs": "5.5.7"

During _"https://d****/.well-known/openid-configuration/jwks"_ I`m getting this error:

"You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable"

**Comment by damienbod** [comment]
@mikeandersun @kochax thanks

**Comment by fouadmess** [comment]
+1

**Comment by oivindth** [comment]
+1

**Comment by damienbod** [comment]
yep, time for this, will do it within the next week

**Comment by damienbod** [comment]
I have tested this with (Angular 5.2.10)
"angular-auth-oidc-client": "4.1.0"
"rxjs": "5.5.10"

This is working.

I will begin work on a version for Angular 6 now.

**Comment by oivindth** [comment]
Any ETA on Angular 6 version? Thanks!

**Comment by damienbod** [comment]
https://github.com/damienbod/AspNetCoreAngularSignalRSecurity/tree/master/DirectMessagesAngular

This with with Angular 6 and rxjs 6

Greeitngs Damien

**Comment by damienbod** [comment]
Requires rxjs-compat to run with 6.1.0

"rxjs": "^6.1.0",
"rxjs-compat": "^6.1.0",

**Comment by damienbod** [comment]
npm released version 6.0.0
