### ISSUE TITLE
Update docs to use `standalone`

### ISSUE THREAD

**Issue by timdeschryver** [damienbod/angular-auth-oidc-client#2021]
With standalone become more mainstream and the default, I think we should update the docs pages to reflect this change.

I can help with the migration, but I wanted to verify if this is OK.

**Comment by FabianGosebrink** [comment]
Sure, this is fine. Thanks. Should we erase the module related things completely from the docs?

**Comment by timdeschryver** [comment]
That's a call you can make, for the NgRx docs we added a note about NgModules with a reference to the archived docs (e.g. https://v17.ngrx.io/docs).
For now we can also add a standalone and NgModules snippet (for the API docs that don't have them), but put the standalone version first.
