### ISSUE TITLE
For testing purposes, how to avoid getting redirected to the sso page?

### ISSUE THREAD

**Issue by goncard** [damienbod/angular-auth-oidc-client#2026]
18.0.1

**Question**
For testing purposes, how can I setup previously the authentication? I'm using Playwright to test and I want to navigate to my home page but don't want to be redirected to the login page. The idea is to be already authenticated before the test. Anybody has any clue?

**Comment by timdeschryver** [comment]
You can login before your test suite is run and store the authentication state so it can be reused while running your tests.
Shameless plug: https://timdeschryver.dev/blog/revamped-authentication-with-playwright

**Comment by goncard** [comment]
@timdeschryver Thanks, looks great. I'm not being able to make it work on my project. :( 
Playwright ends up only detecting my login test, the other tests are not detected.

**Comment by FabianGosebrink** [comment]
You can do that with `fixtures` in playwright.

```
import { expect, test } from '@playwright/test';

export const testWithLogin = test.extend({
    loggedInPage: async ({ page }, use) => {
        // Your login logic

        // execute the tests
        await use(page);
    },
});
```

test.ts
```
import { testWithLogin } from './login-e2e.fixture';
import { mergeTests } from '@playwright/test';

export const test = mergeTests(testWithLogin, /* more fixtures eventually */);
export const expect = test.expect;
```

and then import that file and use it

```
import { expect, test } from './fixtures/test';

test('....', async ({ loggedInPage }) => {
    await loggedInPage.goto('/');
     // ...
});
```

and if you want to store something in the storage you can do that by using a setup project

playwright.config.ts
```
projects: [
        {
            name: 'setup',
            testMatch: 'e2e-tests/fixtures/my-do-something-with-storage.fixture.ts',
        },
        {
            name: 'chromium',
           ...
        },
```
a settings file

```json
{
    "cookies": [ ... ],
    "origins": [],
    ....
}
```

```
import { test as setup } from '@playwright/test';

const settingsFile = 'e2e-tests/.browser/settings.json';

setup('store something', async ({ page, context }) => {
    await context. ...

    await page.context().storageState({ path: settingsFile });
});
```

with this you can execute something before each test and store something in the storage. If you combine those things you'll get the solution :)

**Comment by goncard** [comment]
Thanks @FabianGosebrink , in the meanwhile I was able to make it work with @timdeschryver tutorial. It does work perfectly locally but I'm getting these errors when it tries to run the authentication test on jenkins :/

<img width="551" alt="Screenshot 2024-10-18 at 10 29 16" src="https://github.com/user-attachments/assets/2cbeab32-2dbd-4cf7-a3d0-5bf1a289b5f4">

Thank you both, already helped me a lot.
