### ISSUE TITLE
Silent Renew IFrame adding to parents history

### ISSUE THREAD

**Issue by mcshiz** [damienbod/angular-auth-oidc-client#203]
When you set the src attribute of an iframe it adds to the parent windows browser history. This is breaking the use of the browsers back / forward buttons.

If the following line gets replaced
`this.sessionIframe.src = url;`
with this line
`this.sessionIframe.contentWindow.location.replace(url);`
it should fix that behavior.

I have not tested this yet, but I believe this should work.

**Comment by damienbod** [comment]
@mcshiz Thanks for this. I need to look into this.

**Comment by damienbod** [comment]
@mcshiz fixed in version 6.0.1

**Comment by mcshiz** [comment]
Awesome, thank you!
