### ISSUE TITLE
[Bug]: I seem to be getting logged out straight after I log in 

### ISSUE THREAD

**Issue by drMRI** [damienbod/angular-auth-oidc-client#2034]
### Version

18.0.2

### Steps to reproduce the behavior

```true
As soon as I log in I get logged out. Works fine on 18.0.1.
```

### A clear and concise description of what you expected to happen.

```true
I would expected to be logged in
```

### Additional context

I m also using angular 18.

**Comment by rammba** [comment]
Hello @drMRI, can you provide more details please?

**Comment by drMRI** [comment]
I am not sure what details I need to provide

**Comment by drMRI** [comment]
I should mention also maybe that we are using Okta as well

**Comment by rammba** [comment]
Can you maybe check if your situation is similar to #2040?

**Comment by drMRI** [comment]
it looks quite similar, I m having a bit of trouble setting checkRedirectUrlWhenCheckingIfIsCallback  flag to false

**Comment by drMRI** [comment]
yep it's the same situation, setting the flag to false fixed my issue

**Comment by rammba** [comment]
If that's the case, I suppose you can close this. I explained everything problematic in the mentioned issue.
