### ISSUE TITLE
Getting HttpErrorResponse after upgrading to 4.1.0 in my app with Azure B2C

### ISSUE THREAD

**Issue by alvipeo** [damienbod/angular-auth-oidc-client#204]
I haven't changed any code in my app, just upgraded to 4.1.0 (from 4.0.3) and now I get this:

```
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null
    },
    "status": 200,
    "statusText": "OK",
    "url": "http://localhost:4200/api/oidc",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure during parsing for http://localhost:4200/api/oidc",
    "error": {
        "error": {},
        "text": "{"
    }
}

```
I wonder what has changed...

**Comment by mcshiz** [comment]
you should use the new silent_renew_url configuration.
It's at the very bottom of the docs here https://github.com/damienbod/angular-auth-oidc-client.
Previously the silent renew Iframe was loading your entire application inside an iframe. Using this will prevent unnecessary side affects and reduce data-transfer

**Comment by damienbod** [comment]
@alvipeo should be no breaking changes. I checked this with other applications. Could you be getting a server error?

**Comment by alvipeo** [comment]
ok, sorry about this. this was .NET Core 2.0 related.

**Comment by alvipeo** [comment]
@mcshiz can you please elaborate on this? I read that piece of docs, not sure I fully understand. I use this https://github.com/HWouters/ad-b2c-oidc-angular as a start.

**Comment by damienbod** [comment]
@alvipeo I updated this to 4.1.0 and it works, without any changes. Could it be something else?

https://github.com/damienbod/ad-b2c-oidc-angular/tree/update_oidc_4_1_0

Greetings Damien

**Comment by alvipeo** [comment]
no, no, it works too. I just wanted to ask about this silent_renew_url and what to do with it?

**Comment by damienbod** [comment]
cool, nice that it works.

Does this help?

https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#silent_renew_url

If not maybe you can do a PR, and add the missing bits.

**Comment by alvipeo** [comment]
well, made this:

import { OnInit, Component } from "@angular/core";

```
@Component({
   template: ""
})
export class SilentRenewComponent implements OnInit {
   ngOnInit(): void {
      window.onload = function() {
         /* The parent window hosts the Angular application */
         const parent = window.parent;
         /* Send the id_token information to the oidc message handler */
         const event = new CustomEvent("oidc-silent-renew-message", {
            detail: window.location.hash.substr(1)
         });
         parent.dispatchEvent(event);
      };
   }
}

```
added to app module routing. But how do I test this?

**Comment by alvipeo** [comment]
And I see this error in FF :(

>> Load denied by X-Frame-Options: https://login.microsoftonline.com/bptst.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_susi&client_id=blahblah&redirect_uri=%2Fsilentrenew&response_type=id_token%20token&scope=https%3A%2F%2Fbptst.onmicrosoft.com%2Fbpl%2Fblahblah%20openid%20offline_access&nonce=N0.75006134054833461521742858814&state=15217392411680.7363158920338136&prompt=none does not permit framing.

**Comment by mcshiz** [comment]
@alvipeo you need to create a separate HTML file that's served from your assets directory. Not a component.
This is the contents of that file
``` 
<!doctype` html>
<html>

<head>
  <base href="./">
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>silent_renew</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
  <script>
    window.onload = function () {
      /* The parent window hosts the Angular application */
      var parent = window.parent;
      /* Send the id_token information to the oidc message handler */
      var event = new CustomEvent('oidc-silent-renew-message', { detail: window.location.hash.substr(1) });
      parent.dispatchEvent(event);
    };
  </script>
</body>

</html>
```

**Comment by alvipeo** [comment]
why not component? sorry, I just need to understand

**Comment by mcshiz** [comment]
If you are trying to load one component into an I frame you have to load
your entire application. If it is a separate file it only loads what’s in
that file.

**Comment by alvipeo** [comment]
got it, thank you!
