### ISSUE TITLE
Identity provider and login hint support

### ISSUE THREAD

**Issue by rexdefuror** [damienbod/angular-auth-oidc-client#205]
Hi,

Do you support passing identity provider and login hint in this library? I haven't been able to find a way to pass them through. In the Identity Server middleware they had an event `RedirectToIdentityProvider` where you could add them and it would include them in your query string, however that's for server side applications and can't be used for client side apps like this one. 

If you do not support this what are the chances of it being added in near future?

**Comment by damienbod** [comment]
The lib supports custom paramaters in the authorize request. 
login_hint= 

https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#setcustomrequestparametersparams--key-string-string--number--boolean-

example:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.component.ts#L79

set the login_hint like this.

hope this helps

Greetings Damien

**Comment by damienbod** [comment]
@rexdefuror I'm closing this, please repoen, if you still have an issue
