### ISSUE TITLE
[Question]: Is it possible to retrieve the username and e-mail

### ISSUE THREAD

**Issue by PWagner1** [damienbod/angular-auth-oidc-client#2052]
Hi,

Is it possible to retrieve the username and e-mail via claims. If so, how do I go about it?

**Comment by FabianGosebrink** [comment]
Depending on your IDP, you have to request them, your IDP has to provide them, then they should be on your response in the lib.

**Comment by PWagner1** [comment]
Hi @FabianGosebrink 

> Depending on your IDP, you have to request them, your IDP has to provide them, then they should be on your response in the lib.

Thanks for your response, we're using ADO. I was wondering if there is a example demonstrating how to read back this data and display it?

**Comment by FabianGosebrink** [comment]
An example right for your project is hard to do ;) You can find all the sample projects here https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects . I have no experience in ADO unfortunately :(

**Comment by PWagner1** [comment]
Hi @FabianGosebrink 

Just a update, we've found a solution. So I'll close this thread.
