### ISSUE TITLE
Configure OpenIDImplicitFlowConfiguration to call another Login URL

### ISSUE THREAD

**Issue by RGVGreatCoder** [damienbod/angular-auth-oidc-client#208]
The OpenIDImplicitFlowConfiguration.**stsServer** in my Angular app (Angular with ASP.Net Core 2.0 / Identity template generated from Visual Studio) correctly calls the default Login screen (controller/action) on my ASP.Net Core 2.0 IDM Server. But I don't want to call the default login screen anymore. So I built another Login action method in the same controller (I called it LoginFromAngular) which has a different look & feel.

How can I configure the OpenIDImplicitFlowConfiguration object in Angular to call the LoginFromAngular screen (controller/action)?

**Comment by damienbod** [comment]
@RGVGreatCoder You do this on the STS server. You need to set the actions in the accountController

Greetings Damien
