### ISSUE TITLE
Error on authorizedCallback function.

### ISSUE THREAD

**Issue by OleksandrParfeniukOsf** [damienbod/angular-auth-oidc-client#209]
Currently, I have the errors:
_Failed to load http://myidentity.com/.well-known/openid-configuration/jwks: Response for preflight is invalid (redirect)_
_Http failure response for (unknown url): 0 Unknown Error_
_Failed to retreive siging key with error: "Http failure response for (unknown url): 0 Unknown Error"_

It's my response from server:
http://localhost:9000/callback#id_token%3DeyJhbGciOiJSUzI1NiIsImtpZCI6ImZhYjUyODkyNjI4ZjgxMzI5MWU4OGYwYzY3MjEyZWIyIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MjI5NDAzMjcsImV4cCI6MTUyMjk0MDYyNywiaXNzIjoiaHR0cDovL2lkZW50aXR5LmRldi5sb2NhbC5kaXN0cmlidXRvcmRkLmNvbSIsImF1ZCI6IndlYmFwcC5jbGllbnQiLCJub25jZSI6Ik4wLjQ4MDM5NjYwMTgwNTIwMDgzMTUyMjk0MDMyNTM0OSIsImlhdCI6MTUyMjk0MDMyNywiYXRfaGFzaCI6IlkwaG1iVjJSUWtsbGZBbUN1X0ZMdkEiLCJzaWQiOiJkMjc5OGQ0MjE1NTVhMjAzMTM5NzM5N2QzN2M2NjA2NSIsInN1YiI6Ijc0Nzc2MDExLWJlNjItNDMwYi1hOTNjLTM4YjhmMTNjMTIzZCIsImF1dGhfdGltZSI6MTUyMjkzOTUxMywiaWRwIjoibG9jYWwiLCJhbXIiOlsicHdkIl19.K08lMlC0VC1RH3T9LN6L4Rn4XVp_6EGoYzwwv66Jee_QVxmyFCEJIguhpVTQScGmIECG65vhdAsdIu0ACP9VS8fR-ewjXxlBCTHKu2xhtcyvGNels03VxDgKiiMCAAPQGFMrsfmjClMOpBRa2F7lgNu-kcgzD1ovfc55q5tQNe_COOtAuveGcAlE6KZdV1m32AdfaiF_lO8eFZ7tHfwvUUN4Sy9p8dgAFWnQXFh9syI4h_N3-nLX_jgfET9CLcWO2bDoj0-v7TCKmd9O2_LjRE_3rSXLKtA1en1oSdIYF1K0Ov9iFBvOKe24KD83g0kwZaFG6YsEw8HNlr_zQX35EQ%26access_token%3DeyJhbGciOiJSUzI1NiIsImtpZCI6ImZhYjUyODkyNjI4ZjgxMzI5MWU4OGYwYzY3MjEyZWIyIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MjI5NDAzMjcsImV4cCI6MTUyMjk0MzkyNywiaXNzIjoiaHR0cDovL2lkZW50aXR5LmRldi5sb2NhbC5kaXN0cmlidXRvcmRkLmNvbSIsImF1ZCI6Imh0dHA6Ly9pZGVudGl0eS5kZXYubG9jYWwuZGlzdHJpYnV0b3JkZC5jb20vcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoid2ViYXBwLmNsaWVudCIsInN1YiI6Ijc0Nzc2MDExLWJlNjItNDMwYi1hOTNjLTM4YjhmMTNjMTIzZCIsImF1dGhfdGltZSI6MTUyMjkzOTUxMywiaWRwIjoibG9jYWwiLCJzY29wZSI6WyJvcGVuaWQiXSwiYW1yIjpbInB3ZCJdfQ.kSBHbSeCgrXPVox2G242ROtypCFL5YjRXOwtnMayJwaVmxp23A3W14m-tmplRyEqEHdzuQMHt7ojCV7gpkm8UOC8PB_tgNUV8Tqg6EDLyREQfBj5_FAWiky_-ZrQxOt1MeBi3-didj5nGAtCL-Z0yH6UHvuR1xhR_hS9pryunpX4UvLFSknuL1Doal1NWZ7048FBfXyzpe6Qx0oW6ayn7QL8kDwkW4UotKqVPOMf8daWAKy5zXnqYIGIoCXplDKwWWmwl30QkiLb4ZEehu9a00RBpepKyWbyXytFxM0ybc_TkRy56Kc30XJIji0ZudT08FajMZF5XiKQX7elFpvJwQ%26token_type%3DBearer%26expires_in%3D3600%26scope%3Dopenid%26state%3D15229136806160.1978153346259024%26session_state%3D869akhF4WbZedr0jkWVTj9XfYdwIwpL9Oxws4BOb-88.e31efb7416200b703487fa7a43c095f0

I think it's because on hash, symbols like a '=' and '&' replaced by '%3D' and '%26', but I don't know why.

If need some additional information, just write.

P.S. It's just my error, sorry if I should not add this question here, but maybe you help me.

**Comment by sunilrav** [comment]
I'm getting this too.
Do you see this error in the browser too?


`ERROR TypeError: this.oidcDataService.get(...).pipe is not a function
    at t.getSigningKeys (angular-auth-oidc-client.es5.js:2337)
    at t.authorizedCallback (angular-auth-oidc-client.es5.js:2001)
    at t.onOidcModuleSetup (app.component.ts:48)
`

**Comment by damienbod** [comment]
@OleksandrParfeniukOsf Is CORS supported for the jwk route?

greetings Damien

**Comment by sunilrav** [comment]
@damienbod do we have to do anything specifically allow that? I already have this.



          services.AddCors(options =>
            {

                options.AddPolicy("AllowAllOrigins",

                    builder =>
                    {
                        builder
                            .AllowAnyOrigin()
                            .AllowAnyHeader()
                            .AllowAnyMethod();
                    });
            });

**Comment by sunilrav** [comment]
Here is browser screenshot.
![image](https://user-images.githubusercontent.com/1291174/38709546-d914b160-3e78-11e8-883e-eeb91ec702a3.png)

**Comment by sunilrav** [comment]
Please let me know if this need a different thread.

**Comment by sunilrav** [comment]
I can now confirm it is not a CORS issure. Seems like some kind of a  rxjs issue.
