### ISSUE TITLE
Unable to route to Resource basing on example 

### ISSUE THREAD

**Issue by inpicksys** [damienbod/angular-auth-oidc-client#211]
Stuck with authguard & routing.

**Comment by inpisksys** [comment]
I'm using https://github.com/robisim74/angular-openid-connect-php as example but using Identity server. I have added everything as in example. How guard routes to modules
And second question. 
How to implement default route to login to stsserver on attempt access app without unathorized component?

**Comment by damienbod** [comment]
See the other examples, this works. 

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/authorization.can.guard.ts


Greetings Damien
