### ISSUE TITLE
[Question] - Re: Authorizing in a popup or iframe, how to "pass state" back to parent window?

### ISSUE THREAD

**Issue by ttugates** [damienbod/angular-auth-oidc-client#212]
Ultimate goal is to not require client app reload when log in is necessary.

I have from [**Authorizing in a popup or iframe**](https://github.com/damienbod/angular-auth-oidc-client#authorizing-in-a-popup-or-iframe)
```
login() {
    this.oidcSecurityService.authorize((authUrl) => {
        // handle the authorrization URL
        window.open(authUrl, '_blank', 'toolbar=0,location=0,menubar=0');
    });
}
```

I am reaching but tried the following...
On the STS I created a SilentRenew View with the following script block.

```
@section script
    {
<script>
    window.onload = function () {
        /* The parent window hosts the Angular application */
        var parent = window.parent;
        /* Send the id_token information to the oidc message handler */
        var event = new CustomEvent('oidc-silent-renew-message', { detail: window.location.hash.substr(1) });
        parent.dispatchEvent(event);
    };
</script>
}
```

And my OpenIDImplicitFlowConfiguration  is like this:
  ```
openIDImplicitFlowConfiguration.stsServer = 'http://localhost:5000';
  openIDImplicitFlowConfiguration.redirect_url = 'http://localhost:4200';
  openIDImplicitFlowConfiguration.client_id = 'angularOidcClient';
  openIDImplicitFlowConfiguration.response_type = 'id_token token';
  openIDImplicitFlowConfiguration.scope = 'webapi openid';
  openIDImplicitFlowConfiguration.post_logout_redirect_uri = 'http://localhost:4200';
  openIDImplicitFlowConfiguration.start_checksession = false;
  openIDImplicitFlowConfiguration.silent_renew = true;
  openIDImplicitFlowConfiguration.silent_renew_url = 'http://localhost:5000/Account/SilentRenew';
  openIDImplicitFlowConfiguration.post_login_route = '/home';
  // HTTP 403
  openIDImplicitFlowConfiguration.forbidden_route = '/Forbidden';
  // HTTP 401
  openIDImplicitFlowConfiguration.unauthorized_route = '/home';
  openIDImplicitFlowConfiguration.log_console_warning_active = true;
  openIDImplicitFlowConfiguration.log_console_debug_active = true;
  openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 10;
```

When the window opens, and after successful log in, its redirected to the "post_login_route" of /home.  
I need to close that window and pass the  window.location.hash(I presume?) back to the parent form and then automatically close the window.  I assumed I do that with new CustomEvent.

Do I create a custom View for openIDImplicitFlowConfiguration.redirect_url  or ??  

Thanks for any help

**Comment by Jonesie** [comment]
Just curious - does it have to be a window?  Could it be a modal dialog?  Not sure that will help ...

**Comment by ttugates** [comment]
Ultimately I need it to be a modal(material overlay) that all of our apps will consume.  Was trying to build up to the knowledge without being too specific.

Currently when our site is on a phone and not visible, after an amount of time a user is no longer logged in.  Need their state preserved and a modal overlay to indicate they need to log back in.  Also, if they log out in another of our apps in another tab.

**Comment by profet23** [comment]
I am also curious about how this is supposed to work.

**Comment by profet23** [comment]
@damienbod are there any examples of how to use the new authorize method with callback?

It certainly works in that I can have a popup that shows the auth window, but then it's not clear what to do after successful sign in in the popup window. 

Do we need to push an event back to the parent? How do we have the parent pick up that the login was successful?

**Comment by profet23** [comment]
@damienbod so are you saying:

1) call the authorize method with callback to open a pop up window to show auth url.
2) sign in via pop up
3) when sign in is completed via popup call authorize without callback in main window

?

I have gotten it to work by manually calling refreshsession in the main window after sign in, but it's not clear if this is the correct workflow.

**Comment by damienbod** [comment]
@profet23 yes this should work. The workflow is correct, what you usually want is to update the tokens, without refresh the client application.

**Comment by JohnGalt1717** [comment]
So the question is, how do you KNOW that the login is complete to refresh?  I can get it to do the login process in the iframe of a dialog popup that I do, however I don't have any way to know that it completed and close it.


If you subscribe to the getIsAuthorized it calls in the separate iframe, not in the root window.

So I have no idea how to close the login window and cause the refresh of the parent's token.

**Comment by sukhbirsaini** [comment]
Any updates on this?

**Comment by profet23** [comment]
Is this necessary anymore?   In the latest versions of the lib, if you enable silent_renew you'll no longer need to redirect/refresh the page to authenticate (provided the user is already authenticated with the authority).

What are you looking to accomplish?

**Comment by profet23** [comment]
@damienbod to me, everything that is trying to be accomplished here is now doable via `getIsAuthorized()`, silent renew, and check session.

Am I wrong?  @sukhbirsaini if you have something specific that isn't doable. Let us know.

**Comment by ttugates** [comment]
@profet23, my question was unrelated to silent renew.  It was how

>  to not require client app reload when log in

The full extent of what we were trying to accomplish was..  
Say user is logged into many client apps of ours, many tabs in browser.   They log out of one client.  We detect this and provide the oportunity to relog in, in all other apps, by providing credentials.  In this specific case, we don't want to nav to our Auth site as we would like to preseve the particular apps state.  As far as OIDC / idsrvr4 is concerned, this is a new login.

Another developer solved the issue by using a `window.post` to the parent window as I recall.

**Comment by JohnGalt1717** [comment]
Basically the reason I'm looking for this is that angular apps take a while to load which is made worse while doing login because the login will normally be to something that isn't using Angular.

So I'm looking to eliminate the angular reload delay and have it all in an iframe that returns to a page that isn't angular and then the angular page picks up the navigation and loads in the login. (Basically a static page will receive the redirect and then then the angular will process it eliminating seconds from reload)

**Comment by profet23** [comment]
@JohnGalt1717 see [my comment above](https://github.com/damienbod/angular-auth-oidc-client/issues/212#issuecomment-431879847)

**Comment by JohnGalt1717** [comment]
@profet23 how does one past it back to the parent window? I don't see anything in the documentation (at least the last time I looked)

**Comment by profet23** [comment]
@JohnGalt1717 

The answer is... any way you want. 

[You can look at how silent renew handles it](https://github.com/damienbod/angular-auth-oidc-client#silent-renew)

They key is that you need to take the hash that you get from the popup (after the authority redirects back to the popup) and pass it back to the main window and call: `authorizedCallback(theHash)`

You can do this similar to this:

```
<script>
    window.onload = function () {
    /* The parent window hosts the Angular application */
    var parent = window.parent;
    /* Send the id_token information to the oidc message handler */
    var event = new CustomEvent('oidc-popup-auth-message', {detail: window.location.hash.substr(1) });
    parent.dispatchEvent(event);
};
</script>
```

You'll need to make sure you register for the `oidc-popup-auth-message` event in your angular app.

**Comment by ttugates** [comment]
@profet23 

Following your example and presuming the following is desired.

> Present pop-up to user to relog in?

After popup success.  How is that passed back to parent window?  This presumes the popup is using an iFrame in and of itself.

**Comment by profet23** [comment]
@ttugates 

[see above](https://github.com/damienbod/angular-auth-oidc-client/issues/212#issuecomment-431881982)

**Comment by profet23** [comment]
sorry.. just edited my comment.. meant to put `window.opener` rather than `window.parent`

**Comment by ttugates** [comment]
@profet23, thanks.  I recall that as being roughly what we did.  Will be a while before I get back to that code and verify.

**Comment by profet23** [comment]
@damienbod does this need better documentation?

**Comment by damienbod** [comment]
@profet23 I don't think so, because this is not really a standard flow and the silent renew code is documented as well as this issue. But if you have an idea that would help, it's always good.

Greetings Damien

**Comment by profet23** [comment]
I think this can be closed then. As I believe everything has been addressed.

**Comment by sukhbirsaini** [comment]
Hi,
Let me get you through the workflow I'm facing issue

MVC DotNet Core App Identity server code:

Add below code in the login page:
`window.onload = function () {
    debugger;
    /* The parent window hosts the Angular application */
    var parent = window.opener;
    /* Send the id_token information to the oidc message handler */
    var event = new CustomEvent('oidc-popup-auth-message', { detail: window.location.hash.substr(1) });
    parent.dispatchEvent(event);
};
`


In Angular 6 app:

On login button:
`  this.oidcSecurityService.authorize((authUrl) => {
      debugger;
        this.attrHref = authUrl + '&from=iFrame';
        this.isCollapsed = false;
    });
`

Html of nav bar with login button contains dropdown with iframe as
`<iframe #iframe width="420" height="345" [src]="attrHref | safe" frameborder="1">
                          </iframe>`

Here is the error  

Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at window.onload (JavaScript.js:7)



![image](https://user-images.githubusercontent.com/21036336/47316237-4a836980-d664-11e8-99e7-9af5ee26ea17.png)

**Comment by profet23** [comment]
With your login button... Are you actually opening a pop-up? I don't see a window.open call.

**Comment by profet23** [comment]
Oh I see.. you are using an iframe... Not a pop-up.  Then you want window.parent. not window.opener.

**Comment by profet23** [comment]
Are your redirect iframe url and angular app on different domains(origins)? They should be on the same domain.

**Comment by profet23** [comment]
To be clear. The window that contains the window .onload function should be hosted on the same domain as your angular app.

**Comment by sukhbirsaini** [comment]
Ok.. I have fixed cross domain issue:
Now when listening to the same event as mentioned
`
window.addEventListener('oidc-popup-auth-message', this.handleMessage, false);
 handleMessage(event): void {
    this.oidcSecurityService.authorizedCallback();
  }
`

i'm facing TypeError: Cannot read property 'authorizedCallback' of undefined

**Comment by sukhbirsaini** [comment]
When handling listener callback in handle message, then the scope of this changed to window, and not pointing to the angular controller.

**Comment by profet23** [comment]
`this.oidcSecurityService` is not defined for whatever reason. You'll need to figure out why. 

My guess is that you aren't binding corrently, and thus losing scope of `this`.

also, when you do figure out why, you'll need to pass the hash from the event to the `authorizeCallback()` call.

so like:

```
this.oidcSecurityService.authorizedCallback(e.detail);
```

**Comment by sukhbirsaini** [comment]
Ok I have figured that out, using arrow function that binds automatically the 'this' to the function.
Thanks it is now working. I was able to complete the iframe authentication.

**Comment by profet23** [comment]
Awesome! Glad you're all sorted.   I think maybe we're good to close this now... maybe? lol

**Comment by fritzwf** [comment]
This is a fairly old, but I have a particular solution that might fit your use case.

What you can do is, use the JavaScript postMessage() capability, which can effectively become a proxy to the OIDC module in the iframe.  In your app, you get the iframe child using its id, and in the iframe, it would get the parent using window.parent
This enables communication between the parent and the iframe, were both parent and iframe can send messages to each other.  Example, after the successful login, the parent would wait for the message that the user is logged in.
