### ISSUE TITLE
Request still going to userinfo endpoint

### ISSUE THREAD

**Issue by sunilrav** [damienbod/angular-auth-oidc-client#213]
I assigned auto_userinfo = false

`        openIDImplicitFlowConfiguration.auto_userinfo = false; `

but I am still seeing a request to 

`       \connect\userinfo`

end point in the browser debug tools.

Is this normal?

**Comment by damienbod** [comment]
@sunilrav No, I'll look at thi, thanks for reporting

**Comment by damienbod** [comment]
@sunilrav I checked this, and the user info request is only executed if this is true. When false, the user info is got from the token.

Greetings Damien
