### ISSUE TITLE
getIsAuthorized returns true only after calling authorizedCallback

### ISSUE THREAD

**Issue by gayathri-rajamanickam4** [damienbod/angular-auth-oidc-client#215]
Hi,

We are using this library to authenticate Angular 5.0 application with Azure AD using v2 endpoints.

We have a requirement wherein we don't want to validate the token in the client side as it will be validated in the API. This is  the recommendation from Azure as well.

As per my understanding,authorizedCallback method is validating the tokens. The problem is that until i call authorizedCallback  method, getIsAuthorized  is not returning true, even though, the user has successfully authenticated with ID provider and browser url is returned with tokens.

I have also gone through source code where setAuthorizationData (this sets IsAuthorized to be true ) is getting invoked only in authorizedCallback  method. 

Is there a possibility of providing the authentication status independent of validating the tokens?

Regards,
Gayathri

**Comment by damienbod** [comment]
"We have a requirement wherein we don't want to validate the token in the client side as it will be validated in the API. This is the recommendation from Azure as well."

If your using client side applications for secure applications, you must validate the tokens! This cannot be a recommendation from Azure.

Greetings Damien

**Comment by feco93** [comment]
I think the token must be validated both client and server side.

Greetings,
Feco
