### ISSUE TITLE
AuthConfiguration resource property never used

### ISSUE THREAD

**Issue by Booster2ooo** [damienbod/angular-auth-oidc-client#217]
Hello,

I read in the [documentation](https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#resource) I could set a resource property in the AuthConfiguration to specify a resource identifier.

But after some tests, I noticed the param is never set in the authorize url (resulting in an invalid access_token for my resource). After having a look at [createAuthorizeUrl from oidc.security.service](https://github.com/damienbod/angular-auth-oidc-client/blob/24a54ddf531adc948f27bd2385d1bb57944214ea/src/services/oidc.security.service.ts#L563), I didn't see any use of `this.authConfiguration.resource`.

After adding
```typescript
         params = params.append('scope', this.authConfiguration.scope);
+        if (this.authConfiguration.resource) {
+                  params = params.append('resource', this.authConfiguration.resource);
+        }
```

The request works well and the access_token provided works with my resource.

Could this be added/fixed ?

P.S.: In the meanwhile, I use [setCustomRequestParameters](https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#setcustomrequestparametersparams--key-string-string--number--boolean-)

**Comment by damienbod** [comment]
@Booster2ooo Thanks for reporting, will remove this, clean it up

**Comment by damienbod** [comment]
@Booster2ooo Would you like to do a PR to fix this? Otherwise I will fix this. Let me know. Thanks for reporting.

Greetings Damien

**Comment by Booster2ooo** [comment]
@damienbod you can fix it, thanks for asking :)

**Comment by damienbod** [comment]
removed in version 6.0.1
