### ISSUE TITLE
private createAuthorizeUrl

### ISSUE THREAD

**Issue by feco93** [damienbod/angular-auth-oidc-client#218]
I need to use createAuthorizeUrl method of OidcSecurityService class in another class. I would be happy, if it would be a public method.

**Comment by damienbod** [comment]
@feco93 I don't see why this would be required. This is private because it has internal validation checks, and the app need not know of this. I don't think this is a good idea to make this function public

**Comment by profet23** [comment]
I guess the question is... why?

**Comment by feco93** [comment]
For example:
There are more applications that connect to a central API, which has an API endpoint creating user. This endpoint send an e-mail to the new user with a link pointing to the login URL. In this URL you must provide a returnUrl, because after successfull authentication the API redirects the user to the given returnUrl. The returnUrl depends on that which application created the user. Therefore it's required to send an authorizeurl to the API.

**Comment by profet23** [comment]
Why would you have a link pointing the a login url?  Why not just have the email link point to a protected resource. The protected resource would then use the implicit flow as it was designed to redirect back to itself using OAuth. 

I believe you're trying to solve an error with workflow with a feature that doesn't make sense in a proper workflow.
