### ISSUE TITLE
Provide reason for failed authorization to onAuthorizationResult

### ISSUE THREAD

**Issue by hannesrohde** [damienbod/angular-auth-oidc-client#220]
Authorization with a token can fail for a variety of reasons (see oidc-security-state-validation.service.ts).

In our project we have the requirement to show verbose feedback to the user if e.g. he is unauthorized because his local system clock is off (log message "id_token was issued too far away from the current time").

For this it would be great if onAuthorizationResult would receive not only the status "unauthorized", but also an enum value with the reason for the failed authorization.

**Comment by damienbod** [comment]
@hannesrohde This would be possible for the client validation failures, but the server errors are just 401 in most cases.

Greetings Damien

**Comment by damienbod** [comment]
Will be released in version 7.0.0
