### ISSUE TITLE
Calling the oidcSecurityService.getToken() in order to validate API calls

### ISSUE THREAD

**Issue by gitsat17** [damienbod/angular-auth-oidc-client#221]
Is there an example on how to use oidcSecurityService.getToken() in order to set the header with the authorized token to subsequent API calls ?  Currently I have some code in the app.module.ts to build up the http header but this is getting hit before the token is retrieved.  And also a hard refresh is returning a null value.

**Comment by damienbod** [comment]
The getToken should only be called after the module is setup and the application, user is authenticated. You could use these events and then call, but you should not have logic in the app module if possible.

**Comment by damienbod** [comment]
See the examples for this. The gettoken should only be called when the module is ready, and you should usually not do this in the app module, but in the services when the requests are called.
