### ISSUE TITLE
Using with Angular 6, include the rxjs-compat npm package

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#223]
"rxjs": "^6.1.0",
"rxjs-compat": "^6.1.0",

**Comment by starquake** [comment]
Hi! Love your plugin!

Will this requirement eventually be dropped?

**Comment by damienbod** [comment]
@starquake yes, I think I'll do a new version Angular 6 onwards. rxjs 6.1.0, I see most switching to Angular 6 soon, so no reason to continue to support A4, A5. The npm 4.1.0 works good for these versions. good?

**Comment by damienbod** [comment]
npm version 6.0.0 released for Angular 6, rxjs 6.1.0

npm version 4.1.0 for Angular 5, Angular 4.3
