### ISSUE TITLE
Question: is authorizationData stored to session storage before app initialization is complete?

### ISSUE THREAD

**Issue by wolfhoundjesse** [damienbod/angular-auth-oidc-client#226]
Given this basic structure: 

    <toolbar></toolbar>
    <sidenav>
        <router-outlet></router-outlet>
    </sidenav>

There are things in my sidenav that require an API call with authorization headers. It appears as though those calls are being made before the authorizationData is stored. Does that mean writing to storage is happening after `load()` returns its Promise, allowing the app to initialize? 

I.e., my interceptor is sending along the first few requests without authorization data because it hasn't been written to storage just yet.

**Comment by wolfhoundjesse** [comment]
Nevermind, I figured out how to hook into the AuthorizationResult and populated my store from there instead.

**Comment by terencevs** [comment]
@wolfhoundjesse do you mind sharing how you did it as I am having the same stuggle. PLEASE.
