### ISSUE TITLE
IE Silent Refresh Problem

### ISSUE THREAD

**Issue by ibrahimsen** [damienbod/angular-auth-oidc-client#228]
Hello,

I'm getting below error while refreshing token in IE. How can I fix this issue?

![image](https://user-images.githubusercontent.com/2427905/40267708-390c603c-5b6a-11e8-9240-42c15da19030.png)

Silent-Renew.html

`<script>
    window.onload = function () {
        /* The parent window hosts the Angular application */
        var parent = window.parent;
        /* Send the id_token information to the oidc message handler */
        var event = new CustomEvent('oidc-silent-renew-message', { detail: window.location.hash.substr(1) });
        parent.dispatchEvent(event);
    };
</script>`

**Comment by damienbod** [comment]
Have you included the isomorphic-fetch package? This is required for the fetch

Greetings Damien

**Comment by ibrahimsen** [comment]
Yes I've invluded, This error was about CustomEvent function in silent.renew.html file. CustomEvent funtion not supported by IE.

**Comment by damienbod** [comment]
@ibrahimsen Do you have an example which works in IE, PR? I must update the docs then. Thanks for reporting

Greetings Damien

**Comment by damienbod** [comment]
Added to the API docs

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#silent_renew_url

The customEvent would need to be replaced with an IE friendly javascript function.
