### ISSUE TITLE
Silent renew fails. authorizedCallback incorrect nonce.

### ISSUE THREAD

**Issue by lyncstream** [damienbod/angular-auth-oidc-client#229]
I have an Angular SPA app that is set to silent renew against Identity Server 4.

I am able to login in just fine but after a minute or so when it tries to renew I get logged out.

Here is a sample of how my code is set up. (Just examples of the pertinent code.)

[http://plnkr.co/edit/TfbvRfj0t1WcCuN7C0lB?p=catalogue](http://plnkr.co/edit/TfbvRfj0t1WcCuN7C0lB?p=catalogue)

The **full dump** from the chrome console is also included in the plnkr link above. 

`vendor.bundle.js:108007 storing to storage, getting the roles
vendor.bundle.js:108007 Validate_id_token_nonce failed, dataIdToken.nonce: N0.35682087465253121526740438308 local_nonce:
vendor.bundle.js:107998 authorizedCallback incorrect nonce
`

Also here are the version I am using:

```
    "@angular/common": "^5.2.11",
    "@angular/compiler": "^5.2.11",
    "@angular/core": "^5.2.11",
    "@angular/http": "^5.2.11",
    "angular-auth-oidc-client": "4.1.0",
```

**Comment by lyncstream** [comment]
Do you need more information?

**Comment by damienbod** [comment]
@lyncstream The nonce is incorrect :) So my guess is that you send the request twice to the STS, the first request returns, and the nonces don't match. You can check your network calls in the F12

hope this helps

Greetings Damien
