### ISSUE TITLE
Silent token renew fails on state validation

### ISSUE THREAD

**Issue by ssilviu87** [damienbod/angular-auth-oidc-client#23]
I'm having an issue for the silent token renew flow.
After a few (three or four) successful token renewals, it seems that the library is starting two consecutive silent renew sessions, which causes the local state to be overridden and the response from the first renewal attempt fails at the state validation.
I'm also including a [console log snippet](https://drive.google.com/open?id=0B9XtpWOgIc-VTFVXMDN0ck1pNXM) showing the last successful silent renewal attempt and the following one that failed at the state validation.
Please note that the token provider from my scenario is implemented with Identity Server 4 and I replicated the client configuration from the samples provided at [damienbod/AspNet5IdentityServerAngularImplicitFlow](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/npm-lib-test/src/IdentityServerWithIdentitySQLite/Config.cs) for the `angularclient` client.

**Comment by damienbod** [comment]
Thanks for reporting this. I'll investigate, could be to do with how I init the silent renew, I don't check if 1 is already running.

**Comment by AaronHood** [comment]
We had to stop using this package because of this issue.  Any update for this bug?  Thanks

**Comment by damienbod** [comment]
@AaronHood sorry, I hd no time, busy at my day job. As soon a I get time, I'll address this. At present I have ver little time for OSS

**Comment by damienbod** [comment]
fix: version 1.1.3

**Comment by damienbod** [comment]
@ssilviu87  @AaronHood  fixed
