### ISSUE TITLE
Refused to display ...' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by Jonesie** [damienbod/angular-auth-oidc-client#231]
I'm seeing this error in the browser console after ... a couple of minutes?

Refused to display 'http://identity.web:5002/home/error?errorId=[big long string here]' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Ive been having a lot of token expiry issues on my dev machine so today I checked everything is setup correctly.  I replaced my intercepter with the suggested one, but still seeing the above error.  Im using v 4.1 on Angular 5.2.10

Is this a problem?  Im not sure it causing any issues for the user (ie, me :)

**Comment by Jonesie** [comment]
That makes sense, but I have no idea how to make that change.  Im like a 12 year old who has just found the keys to Dad's Harley :)  I'll spend the day googling. 

Cheers

**Comment by Jonesie** [comment]
I see now.  I was using localhost for the angular SPA and a hosts file entry for the STS.  I changed this to localhost also and the problem seems to have gone away.

However, in production, my STS is identity.domain.blah and the SPA is app.domain.blah.  Are these considered the same origin?

**Comment by damienbod** [comment]
no, you could remove the iframe protection and use CRP frame ancestors instead to only allow your domains. Then you still protected against click jacking.
