### ISSUE TITLE
Update to 6.0.0 and storage setting issue

### ISSUE THREAD

**Issue by mseknibilel** [damienbod/angular-auth-oidc-client#232]
Hi,

After updating angular-auth-oidc-client from 4.0.1 to 6.0.0, i am experiencing an issue.

![image](https://user-images.githubusercontent.com/1716566/40495828-8b9ad31c-5f78-11e8-95cc-5af07e05072d.png)

My config is Angular 6.0.3/angular-auth-oidc-client 6.0.0 and i am not setting my storage settings inside OpenIDImplicitFlowConfiguration to anything.

I didn't have this issue before on 4.0.1 and angular 5.2.2

Can you please help ?

**Comment by mseknibilel** [comment]
You can reproduce it here: https://angular-xgtov3.stackblitz.io
Just open the devtools and check out the console: 
![image](https://user-images.githubusercontent.com/1716566/40497566-d6bdb81a-5f7c-11e8-801a-3e6f616b8093.png)

**Comment by damienbod** [comment]
Is this still an issue, please re-open if it is.
