### ISSUE TITLE
Sign out event

### ISSUE THREAD

**Issue by gagle** [damienbod/angular-auth-oidc-client#233]
Hi all,

Does this client library supports sign-out events? I just want to get notified when the user logs out from another tab.

Thanks

**Comment by damienbod** [comment]
No, I did not think this is required, because when a signout is started, it is started from the client application, so you already have an event. If the user logs out of the STS server, the check session is implemented for this.

Greetings Damien

**Comment by gagle** [comment]
But if I have 2 tabs open logged in with the same user and I log out from one of them, the other one will get notified?


-------- Original message --------From: damienbod <notifications@github.com> Date: 6/1/18  07:46  (GMT+01:00) To: damienbod/angular-auth-oidc-client <angular-auth-oidc-client@noreply.github.com> Cc: Gabriel Llamas <gabriel.llamas.llopis@gmail.com>, Author <author@noreply.github.com> Subject: Re: [damienbod/angular-auth-oidc-client] Sign out event (#233) 
No, I did not think this is required, because when a signout is started, it is started from the client application, so you already have an event. If the user logs out of the STS server, the check session is implemented for this.
Greetings Damien

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/damienbod/angular-auth-oidc-client/issues/233#issuecomment-393766828","url":"https://github.com/damienbod/angular-auth-oidc-client/issues/233#issuecomment-393766828","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/damienbod/angular-auth-oidc-client","title":"damienbod/angular-auth-oidc-client","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/damienbod/angular-auth-oidc-client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@damienbod in #233: No, I did not think this is required, because when a signout is started, it is started from the client application, so you already have an event. If the user logs out of the STS server, the check session is implemented for this.\r\n\r\nGreetings Damien"}],"action":{"name":"View Issue","url":"https://github.com/damienbod/angular-auth-oidc-client/issues/233#issuecomment-393766828"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [damienbod/angular-auth-oidc-client] Sign out event (#233)",
"sections": [
{
"text": "",
"activityTitle": "**damienbod**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@damienbod",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"damienbod/angular-auth-oidc-client\",\n\"issueId\": 233,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"damienbod/angular-auth-oidc-client\",\n\"issueId\": 233\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/damienbod/angular-auth-oidc-client/issues/233#issuecomment-393766828"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339688205\n}"
}
],
"themeColor": "26292E"
}

**Comment by damienbod** [comment]
@gagle please re-open if you think this issue is not ok.

Greetings Damien
