### ISSUE TITLE
What is the myiFrameForCheckSession iframe used for?

### ISSUE THREAD

**Issue by RGVGreatCoder** [damienbod/angular-auth-oidc-client#234]
Hello,
I notice my browser's developer console continuously displays iframe "myiFrameForCheckSession". What is this frame used for and can I make use of it in any way to further benefit my Angular application?

**Comment by damienbod** [comment]
@RGVGreatCoder This is user in the session management standard which checks the session of the server. If you log out of the STS, the event is sent to the client application via an iframe

Greetings Damien
