### ISSUE TITLE
silent-renew problems when using webpack hot module replacement

### ISSUE THREAD

**Issue by profet23** [damienbod/angular-auth-oidc-client#235]
I'm having an issue when webpack runs its hot module replacement.

What's happening is that when the replacement happens, the oidc library has a second instance loaded. When that happens there are now two listeners for the `CustomEvent` `oidc-silent-renew-message`. This causes a race when the silent renew happens and then a failure to renew. 

I believe the library should be adding an instance id to the state and only processing the `CustomEvent` if the instance id matches. If the instance id does not match, it should unsubscribe.

**Comment by profet23** [comment]
PR submitted here: #236

**Comment by damienbod** [comment]
@profet23 thanks

**Comment by damienbod** [comment]
release 6.0.1
