### ISSUE TITLE
IdentityServer4 Implicit Flow Silent Renew problem when browser is suspended

### ISSUE THREAD

**Issue by lyncstreamdevlf** [damienbod/angular-auth-oidc-client#239]
I am working on an angular 5 SPA that is utilizing ASP.NET Core 2.0 & Identity Server 4 Implicit Flow in conjunction with the angular-auth-oidc-client library 4.1.0 to handle user authentication.   We are utilizing silent renew on the client so that when the IdentityTokenLifetime expires, or is about to expire, the client can call the sts server and refresh the AccessTokenLifetime.

Please see configurations below:

**Identity Server Configuration.....**
```
public static class Clients
{
	public static IEnumerable<Client> Get()
	{
		var clients = new List<Client>
		{
			new Client
			{
				ClientId = "Foo.App",
				ClientName = "Foo.App",
				AllowedGrantTypes = GrantTypes.Implicit,
				RedirectUris = new Collection<string>()
				{
					Common.Settings.FooAppUrl + "/",
					Common.Settings.FooAppUrl + "/assets/renew.html"
				},
				PostLogoutRedirectUris = { Common.Settings.IdentityServerUrl + "/account/logout" },
				AllowedCorsOrigins = { Common.Settings.FooAppUrl },
				AllowAccessTokensViaBrowser = true,
				RequireConsent = false,
				IdentityTokenLifetime = 86400, // one day. See notes below for more details on this setting.
				AccessTokenLifetime = 1296000, // 15 days.  See notes below for more details on this setting.
				ClientSecrets =
				{
					new Secret("Foo.App.Seceret_123==".ToSha256())
				},
				AllowedScopes =
				{
					IdentityServerConstants.StandardScopes.OpenId,
					"Foo.Api"
				}
			}
		};

		return clients;
	}
}
```
Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
	services.AddMvc();
	services.AddIdentityServer(options =>
		{
			options.Discovery.CustomEntries.Add("stsServer", Common.Settings.IdentityServerUrl);
		})
		.AddInMemoryApiResources(ApiResources.Get())
		.AddInMemoryClients(Clients.Get())
		.AddCertificateFromStore(HostingEnvironment,
			Configuration["Foo.SigningCertificateThumbprint"],
			Configuration["Foo.SigningCertificateFriendlyName"])
		.AddInMemoryIdentityResources(IdentityResourceManager.Get());

	DependancyResolver.Resolve(services);
}
```
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}

	app.UseIdentityServer();
	app.UseStaticFiles();
	app.UseMvcWithDefaultRoute();
}
````
Extension.cs
```
public static class Extensions
    {
        public static IIdentityServerBuilder AddCertificateFromStore(this IIdentityServerBuilder builder, IHostingEnvironment env, string certificateThumbprint, string certificateFriendlyName)
        {
            if (env.IsDevelopment())
            {
                builder.AddDeveloperSigningCredential();
            }
            else
            {
                X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
                store.Open(OpenFlags.ReadOnly);

                foreach (var certificate in store.Certificates)
                {
                    if (certificate.FriendlyName != certificateFriendlyName) continue;

                    if (certificate.Thumbprint?.ToLower() == certificateThumbprint.ToLower())
                    {
                        builder.AddSigningCredential(certificate);
                    }

                    builder.AddValidationKey(certificate);
                }

                store.Close();
            }

            return builder;
        }
    }
```
AccountController.cs
```
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Login([FromForm]LoginInputModel model, string button)
{
	...

	// only set explicit expiration here if user chooses "remember me". 
	// otherwise we rely upon expiration configured in cookie middleware.
	AuthenticationProperties props = null;
	if (AccountOptions.AllowRememberLogin && model.RememberLogin)
	{
		props = new AuthenticationProperties
		{
			IsPersistent = true,
			ExpiresUtc = DateTimeOffset.UtcNow.Add(TimeSpan.FromDays(30))
		};
	}

	....
}
```

**WebApi Server Configuration.....**
Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
	services.AddCors();
	services.AddMemoryCache();
	services.AddMvcCore()
		.AddAuthorization()
		.AddJsonFormatters();

	services.AddAuthentication("Bearer")
		.AddIdentityServerAuthentication(options =>
		{
			options.Authority = Core.Common.Settings.IdentityServer;
			options.RequireHttpsMetadata = false;
			options.ApiName = "Foo.Api";
			options.RoleClaimType = ClaimTypes.Role;
			options.NameClaimType = ClaimTypes.Name;
		});

	services.AddScoped<FooSiteContextFilter>();
	ConfigureAuthorization(services);
	DependancyResolver.Resolve(services);
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}

	app.UseCors(builder =>
			builder.AllowAnyHeader().AllowAnyMethod().WithOrigins(
				Core.Common.Settings.IdentityServer,
				Core.Common.Settings.IdentityServer + "/"));

	app.UseAuthentication();
	app.UseMvc();
}
```

99% of all user authentication behavior is working great.  However, we have been seeing some unexpected behavior in our production environment whenever a user's computer is asleep for 2 days or more.  I have performed several tests by following these steps:
1) Authenticate User w/Remember Me checked
2) Verify the existence of the idsrv cookie (fyi: expires 1969-12-31) and the idsrv.session cookie (fyi: expires 1 month from current date) in the browser.
3) Put the computer to sleep for > 2 days (So that the IdentityToken expires and so that the client is unable to call the sts server and renew the AccessToken)
4) Wake up computer.  The idsrv cookie is gone and the idsrv.session cookie is gone.
5) Refresh browser
6) User is required to authenticate again.  (**I would have expected the sts server to re-authenticate the user and I would expect the 2 cookies to remain in the browser that was never closed.**)

It is worth noting the following:
1)  I have tried smaller IdentityTokenLifetime & AccessTokenLifetime values, but saw the same behavior in a matter of hours instead of days.  Therefore, to prevent the user from having to login again after putting there computer to sleep for several hours, temporarily the values for token expiration are set the way they are in the above code samples.
2)  It appears that somehow the idsrv cookie and the idsrv.session cookie are being removed.  After waking the computer up from several days of sleep, the chrome developer tools no long shows the cookies.

Thank you in advance, please let me know if there is any other configuration setting that might help to better understand the setup.

**Comment by xaviergxf** [comment]
Hi @lyncstreamdevlf i'm having the same problem too. Do you managed to fix it?

**Comment by lyncstreamdevlf** [comment]
@xaviergxf .  No, unfortunately there was no solution using implicit flow that we were able to find.  Our plan is to use cookie auth for web browsers and the Identity Server "Authorization Code" flow for mobile authentication.

We are planning to use basic out of the box cookie auth with our Angular SPA and AppAuth for Android with our Identity Server Authorization Code Flow setup.

I hope that helps.

**Comment by damienbod** [comment]
closing this, please re-open is required
