### ISSUE TITLE
Add support for login in a popup

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#24]
request

**Comment by profet23** [comment]
Has anyone begun work on this?

**Comment by damienbod** [comment]
No @profet23 What is it you want exactly? Would you like that the login process is inside a popup?

1) User clicks login
2) popup opens
3) after successful login tokens returned, and app has tokens

Greetings Damien

**Comment by profet23** [comment]
My specific workflow desire might be bit weird.

I would like for child iFrames to be able to initiate login automatically via a popup. 

The popup would either show the login form, and allow login or just get the login token from the auth server (when the user is already authenticated with the auth server). 

My use case is that I have an app that requires child iframes on different domains (also running angular-auth-oidc-client). I figure with the popup workflow, I don't have to worry about child iframes trying to redirect to a login page, which would not be desired functionality.

Thanks @damienbod

**Comment by satkanth** [comment]
I also have a similar need and my use case is where I am trying to use the angular-auth-oidc package for authenticating an office add in, following the pattern described in 
https://github.com/OfficeDev/Office-Add-in-UX-Design-Patterns/blob/master/patterns/auth-single.md
For this I need to be able to open a popup and have the authentication flow go through and then go back to the flow of the add in.  Is this something that can be done with this library ?  Any thoughts/help will be appreciated.

Thanks.

**Comment by damienbod** [comment]
This should be supported now
