### ISSUE TITLE
`getIsAuthorized` function never returns true in IE and Edge

### ISSUE THREAD

**Issue by majco333** [damienbod/angular-auth-oidc-client#240]
Hi,

We have problem with `getIsAuthorized` function in IE and Edge. This function never returns `true` when we use it in auth guard. 
In Chrome everything works fine. (That means, after login on Identity Server, `getIsAuthorized` is `false` and Chrome redirect to unauthorized page, but in less than one sec `getIsAuthorized` returns `true` and Chrome redirect to app).
In IE we never get `true` value after redirect from Identity Server. We tried debug it in IE, but console is closing and cleaning because of redirecting.

We allowed everything what we need in `polyfills.ts` including `'isomorphic-fetch'`.

Can you help us?

Thanks

Our code:

auth.guard.ts
```
canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean> | boolean {

      return this.oidcSecurityService.getIsAuthorized().pipe(
        map((isAuthorized: boolean) => {
          if (isAuthorized) { return true; }
          this.router.navigate(['/unauthorized']);
  
          return false;
        })
      );
  }
```

app-routing.module.ts
```
Routes = [
  {
    path: '', component: ShellComponent,
    canActivate: [AuthGuard],
    canActivateChild: [AuthGuard],
    children: [
      { path: 'programs', loadChildren: './programs/programs.module#ProgramsModule', canLoad: [AuthGuard] },
      { path: '', component: DashboardComponent, pathMatch: 'full' }
    ]
  },
  { path: 'unauthorized', component: UnauthorizedComponent },
  { path: 'callback', redirectTo: ''},
  { path: 'id_token',  redirectTo: '' },
  { path: '**', component: UnauthorizedComponent }
];
```

**Comment by damienbod** [comment]
@majco333 In the browser, can you click the preserve logs in the F12 console/network tabs. Then you should see the reason why this is failing.

Hope this helps

Greetings Damien

**Comment by majco333** [comment]
Thanks for feedback.  We know how to open IE console but IE close our console when redirecting from Identity server to our angular app. (We read about this, and IE is starting new threads. )
Side effect is also cleaning and closing debug console. 

(It looks like session storage is cleaned too, because we tried set storage to `localStorage` and after that it looks like it works correct.
