### ISSUE TITLE
IE11 - issue with signing keys

### ISSUE THREAD

**Issue by bowerej** [damienbod/angular-auth-oidc-client#245]
Hi,

After following your previous solution for [IE11 compatibility](https://github.com/damienbod/angular-auth-oidc-client/issues/179), I am getting an error when trying to get the signing keys in IE11. 

"SCRIPT7002: XMLHttpRequest: Network Error 0x4c7, The operation was canceled by the user.

auth-callback
Failed to retreive siging key with error: {"description":"'Response' is undefined","number":-2146823279,"stack":"ReferenceError: 'Response' is undefined\n   at OidcSecurityService.prototype.handleErrorGetSigningKeys (https://localhost:4200/vendor.js:82431:9)\n   at CatchSubscriber.prototype.error (https://localhost:4200/vendor.js:92092:17)\n   at Subscriber.prototype._error (https://localhost:4200/vendor.js:87074:9)\n   at Subscriber.prototype.error (https://localhost:4200/vendor.js:87048:13)\n   at Subscriber.prototype._error (https://localhost:4200/vendor.js:87074:9)\n   at Subscriber.prototype.error (https://localhost:4200/vendor.js:87048:13)\n   at OuterSubscriber.prototype.notifyError (https://localhost:4200/vendor.js:86448:9)\n   at InnerSubscriber.prototype._error (https://localhost:4200/vendor.js:85907:9)\n   at Subscriber.prototype.error (https://localhost:4200/vendor.js:87048:13)\n   at OuterSubscriber.prototype.notifyError (https://localhost:4200/vendor.js:86448:9)"}"

I believe the issue has to do with the http get happening in the get function of OidcDataService that is being called in getSigningKeys() from OidcSercurityService. When I implemented my own service to load my stsServer, I had to include the option "withCredentials: true" in my http get (ex. this.http.get(configUrl, {withCredentials:true});) to solve a network error I was getting in IE11 when trying to reach my openid-configuration:

"SCRIPT7002: XMLHttpRequest: Network Error 0x4c7, The operation was canceled by the user.

autologin"

However, since I am unable to add the "withCredentials: true" to the http get in OidcDataService,  I am unsure of the best way to work around this problem I am having and I was wondering if you had any ideas.

Thanks!

**Comment by torrescgeorge** [comment]
Hi @bowerej,

Did you solve this issue? I have the same problem.

**Comment by damienbod** [comment]
closing this, please re-open is required
