### ISSUE TITLE
The AuthModule runs before APP_INITIALIZER Provider

### ISSUE THREAD

**Issue by bhaidar** [damienbod/angular-auth-oidc-client#247]
Hi,
I am integrating the client in my Angular app that makes use of APP_INITIALIZER. The code for the client is configured in the constructor of the AuthModule, hence it is running before the APP_INITIALIZER.

What are possible solutions to make sure APP_INITIALIZER runs before the AuthModule runs?

Thanks

**Comment by damienbod** [comment]
@FabianGosebrink Any ideas how to do this?

**Comment by damienbod** [comment]
@bhaidar This is why the setup module was added

**Comment by bhaidar** [comment]
@damienbod Hey Damien, thanks for checking out this post.
Can you please illustrate more? 

By the way, I am still new to the OIDC client project, can you point me to some resources to better under how it works?

Thanks a lot
Bilal

**Comment by damienbod** [comment]
Hi @bhaidar 

The APP_INITIALIZER does not complete before the AuthModule starts. I use an event handler to do the setup logic inside the AuthModule 

https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#output-onmodulesetup-eventemitter--new-eventemittertrue

**Comment by bhaidar** [comment]
Hi @damienbod 
OK perfect. Now I see it. So the important thing here is that you are loading STS configuration at the APP_INITIALIZATION and once data is ready, you handle it inside the AuthModule.

I saw in the documentation a place where you load the configuration right inside the AppModule constructor that's why I raised the issue here!
