### ISSUE TITLE
Expiry offset/skew misinterpretation

### ISSUE THREAD

**Issue by Mich-b** [damienbod/angular-auth-oidc-client#248]
Hi,

The logic to check whether or not the IDToken is expired can be found in oidc.security.validation.ts line 81:
`        // Token not expired?`
`        return (`
`            tokenExpirationDate.valueOf() >`
`            new Date().valueOf() + offsetSeconds * 1000`
 `       );`

I'd argue you should **subtract** the offsetSeconds instead of adding them to the current date, since you wish to soft fail on slight clock skews. The current logic makes it stricter, which I don't think was the goal when introducing clock skew.

**Comment by damienbod** [comment]
@Mich-b Thanks for the feedback. I'll look into this. I need to add some tests here.

Greetings Damien

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
