### ISSUE TITLE
Code cleanup authorization callback

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#25]
Clean up this code.

**Comment by FabianGosebrink** [comment]
Already working on a branch here https://github.com/FabianGosebrink/angular-auth-oidc-client/tree/FabianGosebrink/beautify-nested-if

**Comment by fdcastel** [comment]
Sorry... Can't resist...

![image](https://user-images.githubusercontent.com/629408/31855954-b4ec7c30-b694-11e7-9b79-9b82efb728a1.png)

😂 😂 😂

**Comment by FabianGosebrink** [comment]
Fixe by commit #702f1bb
