### ISSUE TITLE
QUESTION: Is there some way to check if user is authorized on Identity Server?

### ISSUE THREAD

**Issue by dm-CaT** [damienbod/angular-auth-oidc-client#250]
Is there way to check authorization on Identity Server (IS) from angular client app? I want to auto login users only in case if they are authorized on IS. Otherwize I want to show them some welcome text and button which will forward them to IS.

P.S. I try to search against issues here but found only either you're forward always either you're show 'welcome' always.

**Comment by damienbod** [comment]
Hi @dm-CaT 

I will check this, never tried this. I use the check session once the user is logged in. You could re-implement the samre logic as the check session iframe calls.

Greetings Damien

**Comment by juanp3053** [comment]
@dm-CaT Any updates? Where you able to implement this on your Angular Client App?

**Comment by dm-CaT** [comment]
@profet23, I think this is enough. An issue can be closed.

**Comment by profet23** [comment]
@damienbod  can be closed.
