### ISSUE TITLE
openIDImplicitFlowConfiguration.storage = localStorage fails

### ISSUE THREAD

**Issue by JohnGalt1717** [damienbod/angular-auth-oidc-client#251]
When I set storage to localStorage in the onConfigurationLoaded I get the following upon login:

authorizedCallback incorrect state
authorizedCallback, token(s) validation failed, resetting

If I use a custom storage like the readme and just use: return localStorage.getItem(key);
and localStorage.setItem(key, value); for read and write I get an invalid operation error on replace with null.

How does one get all of the auth information to persist between sessions and automatically refresh the token when the user comes back to the page so that they don't have to login every time?

**Comment by damienbod** [comment]
Hi @JohnGalt1717 

What browser do you test with?

I'll investigate this.

**Comment by JohnGalt1717** [comment]
@damienbod  Thanks!

Chrome, latest public release with developer tools open.

Also errors in Edge.

**Comment by JohnGalt1717** [comment]
Hi there, any luck with this?

**Comment by JohnGalt1717** [comment]
This appears to be working in the latest version.
