### ISSUE TITLE
Question: Manually push in token information or alternative solution

### ISSUE THREAD

**Issue by JohnGalt1717** [damienbod/angular-auth-oidc-client#256]
Hi there, I have what I would consider a pretty standard requirement for a sign in form:

1. Sign up with login and password provided OR use 3rd party sign in (all provided by OpenIdConnect.Server)
2. If sign in with 3rd party, then pre-fill in all of the fields for any data we got back and store the provider info.
3. Prompt the user to fill in the rest of the form in either case.
4. User fills in the form.
5. User account is created, either with just l/p or with 3rd party provider info.
6. Once created, user is automatically logged in and continues on to home page.

There are 2 parts I can't figure out:

1. How to prompt for external login and have it pop a popup window that then goes through the 3rd party selection and login process using identity in asp.net core, and then comes back but doesn't prompt to authenticate the account, just returns the data somehow that came back from the 3rd party.

2. Now that I have the l/p or the 3rd party info, how do I silently log them in without looping through the the standard sign in process?

**Comment by damienbod** [comment]
Hi @JohnGalt1717 

You should use an STS server for this and not a client application. This is pretty easy to implement, for example when you use IdentityServer4 with Identity. Then you can use an OIDC Implicit flow to log in to the server. The server handles the logic you described.

No password, username should be handled by the client application.

**Comment by JohnGalt1717** [comment]
Ok, but are you saying that all of the signup process should be handled on the server and not the client application?


I.e., should the angular app just redirect into the implicit flow, and that should offer to allow them to sign up from there?

That's really not a good flow for something like an ecommerce site where you want to have a separate call to action that let's them purchase on one screen.

**Comment by profet23** [comment]
Is this covered here?  #212

Can we close this?

**Comment by JohnGalt1717** [comment]
I don't think so.  I still don't see a process where I can have a user that doesn't exist, get the 3rd party info back from openIdConnect server and then create the account and not require a second login after the account is created.

i.e. even if it doesn't use openid connect server and the user just enters their email and password it would still require a login to the server. I can't see how I could return anything from the server and inject the access token etc. so that the user became logged in without a double login process.

**Comment by profet23** [comment]
I think your flow might be a little wonky.

The oidc client shouldn't care about user registration. It simply knows if the user is authenticated or not, and has info about how to talk to the authentication authority.

So if a user comes to your angular site and wants to register/login you should forward them to the authority either via a popup, iframe, or some other method. Once they are registered and logged in to the authority, you can call `OidcSecurityService.refreshSession()` and it should utilize silent_renew to silently authenticate the user in the background. For this to work, you'll need silent_renew properly configured.

**Comment by JohnGalt1717** [comment]
That's fine in theory but I don't want to put all of my registration code in the server side. I want to put it in the angular app, send the info to the api via http client and then continue after the api client returns a token set.

**Comment by profet23** [comment]
But that is out of scope of this library and not part of the oidc spec.  You could create some end point on the authority to receive user registration information and register the user dynamically before authenticating them. But that's server side, and has nothing to do with oidc.

**Comment by JohnGalt1717** [comment]
So how would I go about telling the oidc client that it's now logged in and provide the information to it?

**Comment by profet23** [comment]
What information?

You shouldn't provide any information about the user. You need to rely on the authority to give you information about that user.

Now if you want to somehow create a registration process that takes some info in your angular client and sends it to the authority for registration, thats cool, but has nothing to do with oidc or this library. 

The flow would be something like:

1. User loads angular app
2. Angular app checks if user is logged into authority (false)
3. Angular app asks if user wants to log in or register (register)
4. Angular app collects some info about the user and then sends that info to some custom endpoint on the authority that registers a new user with provided information.
5. Angular app forwards user to authority to log in. 
6. User logs into authority
7. Authority returns user to angular app and user is logged in.

but all of that seems odd... the usual flow is:

1. User loads angular app
2. Angular app checks if user is logged into authority (false)
3. Angular app redirects user to authority (either page redirect or popup or iframe)
4. Authority asks user to log in or register
5. Authority returns user to angular app and user is logged in.

**Comment by profet23** [comment]
@JohnGalt1717  can this be closed?

**Comment by JohnGalt1717** [comment]
The issue is that it's completely not intuitive to the user that they have to provide information including password and then are prompted to login with the information they just provided.

I want the user to be able to provide credit card information, email address and password, and upon success of the credit card, just be logged in and ready to go.

We don't consider it a security risk to not use a separate email verification because they're forking out money for the transaction which is the case with most ecommerce sites if you look at their flow.

So I'm still looking for a way that I can somehow do this without the user having to login twice effectively.

**Comment by JohnGalt1717** [comment]
(Double comments because editing the comment fails horribly every time I try)

The IdentityServer example for this project doesn't deal with this process and it and other samples or documention really needs to.

A very standard flow is:

1. Ask for email address, password and credit card info.
2. Process credit card and create the new user.
3. Return the user token so that the user is logged in.
4. Start silent renew.
5. Redirect the user to their user home page or order confirmation page allowing them to use the product immediately.

In every single case that I can find, the user ends up having to enter their information twice with this and other libraries causing fud for no reason.

And worse, try having the user register with a 3rd party and then take credit card information which is also pretty standard.

**Comment by profet23** [comment]
@JohnGalt1717  While I understand what you want... Since that flow isn't part of OIDC I don't think it belongs in this library.

If you don't control the authority, there is simply no way to do this. It's not how OIDC works.

But if you **DO** control the authority:

1. User loads angular app
2. Angular app checks if user is logged into authority (false)
3. Angular app asks if user wants to log in or register (register)
4. Angular app collects some info about the user and then sends that info to some custom endpoint on the authority that registers a new user with provided information.
5. Angular app receives confirmation from authority that user registration was successful.
6. Angular app opens an iframe to some custom page on the authority that can receive a username/password from parent frame angular app.
7. iframe logs in silently thus creating the cookie needed for that domain.
8. Angular app kicks off silent renew and user is logged in.

**Comment by profet23** [comment]
But as I was saying... the above workflow is non standard and not part of the spec. Thus I don't think it should be part of the library.

**Comment by profet23** [comment]
@JohnGalt1717 I'm going to close this issue, but if you want to keep discussing the above workflow, I'd be happy to help.

**Comment by JohnGalt1717** [comment]
Thanks. Experimenting now to see if I can make your suggestion work. I've had a horrible time getting iframe login to work properly so this will be interesting.

**Comment by JohnGalt1717** [comment]
@profet23 how do I do a silent login request?

I.e. I have logged the user on server side when they sign up, so they have a cookie and it's recognized (hopefully)

So I'm trying to call a function of some sort that will go to the server and get back all of the authentication information so that I can use oidcSecurityService.authorizedCallBack() to authenticate the user on the client side.

I can't find anything that does this. I would have thought a call to the well known authorization endpoint would have worked with prompt=none but that still redirects to our login page.

**Comment by profet23** [comment]
@JohnGalt1717 provided you have configured silent renew properly with the library, a subscription to `getIsAuthorized()` will do a silent renew before returning true or false.

**Comment by profet23** [comment]
@JohnGalt1717 you should only have to call `authorizedCallBack()` when returning from the authority.

**Comment by JohnGalt1717** [comment]
Right, but this is my problem all along.

I can't get singinManager to set the response cookie properly as a response to ajax. It appears that only a redirect will set it and I cant find how to get the cookie so that I can manually set it.

Which is the root of this entire GitHub issue.

All I want to do is call an ajax call with user info and credit card data, have it check if the user exists, process the card, then login the user as part of an Ajax call on Asp.net core and then have this library transparently login.

Everything I try is a complete hack job for something that should be basic 101 stuff and it doesn't work. (and the asp.net core sample that goes with this project should include an example of this)

I've verified that the ajax call using angular httpClient does return the cookie.  I can't verify that it's actually being set for the api endpoint because I can't find anything in devTools to verify that it's there.

.getIsAuthorized() returns false however and I do have silentRenew = true.

Any help greatly appreciated. I would suspect that just about anyone else using this library would need to do the same thing because putting registration pages on your oidc sts definitely is not desirable.

**Comment by profet23** [comment]
Registration on STS is the norm. It is the authority. It's weird to register on anything but the authority. But let's move beyond that. 

> All I want to do is call an ajax call with user info and credit card data, have it check if the user exists, process the card, **then login the user as part of an Ajax call on Asp.net core** and then have this library transparently login.

Don't do it as an ajax call. Do it as a hidden iframe. Pass whatever info you need to the iframe. Have the iframe log the user in, register them, make them coffee, whatever you wish. As long as you do it as a hidden iframe, the cookie will be set. (Nothing mentioned in this paragraph has anything to do with OIDC or this library). 

Once that cookie is set, you'll be able to silently log the user in using this library.

**Comment by profet23** [comment]
So again the workflow should be something like:


1. User loads angular app
2. Angular app checks if user is logged into authority (false) (`getIsAuthorized()`)
3. Angular app asks if user wants to log in or register (register)
4. Angular app collects some info about the user and then sends that info to some custom endpoint on the authority that registers a new user with provided information (ajax request to authority).
5. Angular app receives confirmation from authority that user registration was successful (ajax response from authority)
6. Angular app opens a hidden iframe to some custom page on the authority that can receive a username/password from parent frame angular app.
7. Angular app passes a message to the iframe via javascript with the username and password that was previously used to register the user. The username and password is then used to log the user in. 
8. Since the user has now logged into the authority, the authority will give them a cookie for the authority domain.
8. Angular app kicks off silent renew (via this library) and user is logged in.

**Comment by JohnGalt1717** [comment]
I finally figured out the tricks to all of this: (hope this helps someone banging their head against a wall)

1. You can't use iframe with openidconnect anymore unless you're only doing it with your own because essentially every other SSO provider out there blocks it. If you want to do it yourself, your registration httpClient call has to pass withCredentials: true in the options and your login server must allow CORS withCredentials AND it must have x-Frame-Allow set properly.

2. Otherwise you need to redirect through, which is horrible for SPAs but is what it is. You should set your redirect to a static HTML page exactly like the silent-renew and should use sesssionStorage to store the page you ultimately want to redirect to and do the same to set a variable of the hash/querystring that is returned from the StP.  Then in your angular app, look for the hash in the variable and use that to login and then once logged in, redirect to the path in the sessionStorage as well.

Subscribing to onModuleSetup is where you'd look for the authinfo that came back from the StP something like this:


`			const authInfo = sessionStorage.getItem('AuthInfo');
			if (authInfo) {
				sessionStorage.removeItem('AuthInfo');
				oidcSecurityService.authorizedCallback(authInfo);
				return;
			}
`

and getIsAuthorized is where you can do the redirect if it passes true simply using the router.

3. When doing a registration where you want the person to sign up with their 3rd party credentials (facebook, google whatever) you want to create a separate page in asp.net core that doesn't log the local user and only uses the 3rd party info and then parses out whatever additional information other than the provider and providerKey and returns that in the URL to a static page in the same manner as above.


Personally I think that this client should handle all of this automatically. I.e. on authentication I should be able to pass a dynamic URL to it of where the redirect goes to, and by default it should redirect back to the current page unless overridden and we should just have to put in a pre-defined static page like the silent-renew page. Same with doing registration.

And all of this should be better documented since it's a pretty standard process given that 0% of all of the sites I tested using OpenidConect use the StP to do registrations so this should be the default flow and fully documented since it's highly likely this is the only way people are ever going to use it.

**Comment by profet23** [comment]
If you want to write something that conforms to OIDC specification...   pull requests welcome.

Glad you're sorted.
