### ISSUE TITLE
How do I detect when session expired?

### ISSUE THREAD

**Issue by Jonesie** [damienbod/angular-auth-oidc-client#261]
Im sorry, this is not really an issue - I am the issue :) - but I cant figure out how to detected when the session/login expires.

I tried this in the app component, but it never seemed to get fired:

```
ngOnInit() {
    this.isAuthorizedSubscription = this.oidcSecurityService.getIsAuthorized().subscribe(
      (isAuthorized: boolean) => {
        if (this.isAuthorized && !isAuthorized) {
          // session expired - lockout the user
          this.dialog.open(SessionExpiredDialogComponent, {
            disableClose: false,
            role: 'alertdialog'
          });
        }
        console.log(`isAuth = ${isAuthorized}`);
        this.isAuthorized = isAuthorized;
      });
  }
```

**Comment by FabianGosebrink** [comment]
I like the idea of having an event for this... @damienbod shall we target this?

**Comment by damienbod** [comment]
@FabianGosebrink new branch with this allow, easy to test

**Comment by damienbod** [comment]
this.oidcSecurityService.getIsAuthorized() should now work in version 6.0.12
