### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by kratosmat** [damienbod/angular-auth-oidc-client#265]
Hi all,
there is a contribution guide?
I would like to contribute on this project, but I cannot find the contribution steps.

Thanks a lot,
Matteo.

**Comment by damienbod** [comment]
Hi @kratosmat 

thanks, contributions are very welcome. PRs are best, and try to keep them small. The project does not have enough tests, so for each/ some changes, I need to do a lot of manual testing.

The project needs a lot more docs to help people use it, examples with different OIDC providers and more tests.

Greetings Damien
