### ISSUE TITLE
when using localStorage new session doesn't automatically Update from refresh token

### ISSUE THREAD

**Issue by JohnGalt1717** [damienbod/angular-auth-oidc-client#266]
Basically if you use any storage that persists between sessions, the library isn't detecting the expired auth token and using the refresh token to update the auth token automatically so it then logs the user out.

Is there a way to hook in and manually do this? Or is it possible to make it do this?

Thanks!

**Comment by profet23** [comment]
@JohnGalt1717 this should be happening now. And with the recent changes to `getIsAuthorized()` and silent_renew, things should feel a lot more consistent. 

Can we close this?
