### ISSUE TITLE
Exposing EndSessionUrl and make ResetAuthorizationData method public.

### ISSUE THREAD

**Issue by DooMachine** [damienbod/angular-auth-oidc-client#268]
Hello, 
I'm trying to implement this library to Ionic4 client using [InAppBrowser](https://ionicframework.com/docs/native/in-app-browser/) to handle login and logout. So, Is there any way I get the endSessionUrl ? Can we expose it somehow? 

About ResetAuthorizationData method: Since we logout with hidden InAppBrowser, logoff() method is trying to redirect to logout_url which is not valid for ionic, I need to clear auth data from application after being sure that user logged out with InAppBrowser.

You can check relevant implementation [here](https://github.com/DooMachine/Ionic_IdentityServer4/blob/master/ionic_4_cli/src/pages/login/login.ts)
Thanks.

**Comment by damienbod** [comment]
will be part of the next release, just need to merge 1 more PR
