### ISSUE TITLE
Switching between websites in same tab uses wrong token

### ISSUE THREAD

**Issue by rtaylor72** [damienbod/angular-auth-oidc-client#272]
I have found an issue where when you have multiple sites using your library and staying in the same tab, the later sites are still using the token from the first accessed websites.  If a new tab is opened, they work fine individually.  I would like to suggest a change to the BrowserStorage to resolve this by appending something unique to the key name, like in my case I used the client_id.  I have created a new custom storage class as a work around that others can use if needed until (or if) a fix is completed.

```
import { Injectable } from '@angular/core';

import { OidcSecurityStorage, AuthConfiguration } from 'angular-auth-oidc-client';

@Injectable()
export class CustomBrowserStorage implements OidcSecurityStorage {
    private authConfiguration: AuthConfiguration;
    private hasStorage: boolean;

    constructor(authConfiguration: AuthConfiguration) {
        this.authConfiguration = authConfiguration;
        this.hasStorage = true;
    }

    public read(key: string): any {
        if (this.hasStorage) {
            return JSON.parse(this.authConfiguration.storage.getItem(key + '_' + this.authConfiguration.client_id));
        } else {
            return;
        }
    }

    public write(key: string, value: any): void {
        if (this.hasStorage) {
            value = value === undefined ? null : value;
            this.authConfiguration.storage.setItem(key + '_' + this.authConfiguration.client_id, JSON.stringify(value));
        }
    }
}
```

Then implement with the "AuthModule.forRoot({ storage: CustomBrowserStorage })," in app.module.ts.

**Comment by damienbod** [comment]
added in version 6.0.6
