### ISSUE TITLE
IE11 "Object doesn't support this action" when using new CustomEvent

### ISSUE THREAD

**Issue by Booster2ooo** [damienbod/angular-auth-oidc-client#276]
Hello,

When using the application in IE11, OidcSecurityService.setupModule fails with the error "Object doesn't support this action". This error is caused by the following snippet:

```javascript
window.dispatchEvent(
    new CustomEvent('oidc-silent-renew-init', {
        detail: instanceId,
    })
);
```
[oidc.security.service.ts#L167](https://github.com/damienbod/angular-auth-oidc-client/blob/63bc25ee248c32fc40648a0b04940e1a2b9ddea6/src/services/oidc.security.service.ts#L167)

For IE versions >= 9, custom events must be created using document.createEvent() then initialized using the initCustomEvent method of the previously created event, something approaching:
```javascript
const customEvent = document.createEvent("CustomEvent");
customEvent.initCustomEvent('oidc-silent-renew-init', false, false,{
    detail: instanceId,
});
```

An alternative would be to use a polyfill.
```javascript
(function () {
  function CustomEvent ( event, params ) {
    params = params || { bubbles: false, cancelable: false, detail: undefined };
    var evt = document.createEvent( 'CustomEvent' );
    evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
    return evt;
   }

  CustomEvent.prototype = window.Event.prototype;

  window.CustomEvent = CustomEvent;
})();
```
Those are anwers were found on [StackOverflow](https://stackoverflow.com/questions/19345392/why-arent-my-parameters-getting-passed-through-to-a-dispatched-event/19345563#19345563).

Best regards

**Comment by damienbod** [comment]
closing this, please re-open is required

**Comment by jfhector** [comment]
Thanks @Booster2ooo for this clear explanation. I've been struggling with a similar issue in my repo. I've come across your post and the fix worked.
