### ISSUE TITLE
IE 11 - fetch undefined

### ISSUE THREAD

**Issue by klanglie** [damienbod/angular-auth-oidc-client#278]
I had to include the source code in my project and modified OidcConfigService to fix this problem. I also had to import { Buffer } from 'buffer'; into TokenHelperService as well as add  (window as any).global = window; to polyfills.ts . Now I am getting a separate, likely un-related to this library, error. Same as [this person.](https://github.com/angular/angular/issues/22982). How fun it is to work with IE. My project is based off of [this one](https://github.com/start-angular/SB-Admin-BS4-Angular-6)

```
import { HttpClient } from '@angular/common/http';
import { EventEmitter, Injectable, Output } from '@angular/core';

@Injectable()
export class OidcConfigService {

    constructor(private http: HttpClient) { }

    @Output()
    onConfigurationLoaded = new EventEmitter<boolean>();
    clientConfiguration: any;
    wellKnownEndpoints: any;

    load(configUrl: string) {
        try {

            this.http.get(configUrl).subscribe((clientConfig: any) => {
                this.clientConfiguration = clientConfig;
                this.http.get(`${clientConfig.stsServer}/.well-known/openid-configuration`).subscribe((data) => {
                    this.wellKnownEndpoints = data;
                    this.onConfigurationLoaded.emit(true);
                });
            });

        } catch (err) {
            console.error(
                `OidcConfigService 'load' threw an error on calling ${configUrl}`,
                err
            );
            this.onConfigurationLoaded.emit(false);
        }
    }
}
```

**Comment by JohnGalt1717** [comment]
You'll need a fetch polyfill likely.

**Comment by klanglie** [comment]
I tried something similar to that without success. fetch is a non-standard api which is why it isn't included in core-js. [Some people recommend staying away from it altogether.](https://medium.com/@shahata/why-i-wont-be-using-fetch-api-in-my-apps-6900e6c6fe78). Besides, why avoid using Http in the library. What does fetch provide that the standard HttpClient does not provide?

**Comment by JohnGalt1717** [comment]
If you npm install isomorphic-fetch it should work. We have no problem at all with fetch which we use immediately before bootstrap to pull configuration information in.

**Comment by damienbod** [comment]
In version 6.0.9, we have removed the fetch dependency.

**Comment by FabianGosebrink** [comment]
Should be fixed with https://github.com/damienbod/angular-auth-oidc-client/commit/a24bc53a5993d82e3adc4d8937d45448d92424ba
