### ISSUE TITLE
Get storage from dependency injection (for server-side rendering)

### ISSUE THREAD

**Issue by astegmaier** [damienbod/angular-auth-oidc-client#28]
First of all, I wanted to say thanks for sharing this package. I'm finding it lean, well-conceived, and very useful!

I was trying to use it in the context of a project where I'd like to leverage server-side rendering (SSR) based of [this](https://github.com/aspnet/JavaScriptServices) template from @SteveSandersonMS, and I was running into trouble.

One of the constraints of SSR is that there is no access to SessionStorage or LocalStorage. It looks like this package [currently depends](https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.common.ts#L18) on these being available in order to successfully retrieve auth tokens from a previous signin.

I'd like to be able to provide server-side mock of the Storage interface that populates its values from cookies. That way, when a page was being rendered in node on the server and it needed to make a call to a protected API, it could pull auth keys from this storage, and everything would work well.

Would you be open to a PR aimed at enabling this scenario? An idea for an approach would be to allow an implementation of Storage to be injected using angular's DI. The constructor of `oidc.security.common` might look something like this:

```
constructor(private authConfiguration: AuthConfiguration, private injectedStorage: Storage) {
    if (typeof Storage !== 'undefined') { 
        if (injectedStorage) { this.storage = injectedStorage }
        else { this.storage = sessionStorage; }
    } 
}
```

Thoughts? I'm happy to work on a PR if you like this direction.

**Comment by damienbod** [comment]
Sounds great, thanks, PR would be awesome. All storage access is in this class:

https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.common.ts

so you would only need to change this and add a property auth.configuration if required. Let me know if you need help, thanks

**Comment by astegmaier** [comment]
I create [PR#29](https://github.com/damienbod/angular-auth-oidc-client/pull/29) to cover the DI case.

You mentioned possibly also changing auth.configuration to allow users to do the same thing. This isn't strictly necessary for my case, but I'm happy to create a separate PR to add this feature, too. I wanted to check with you about the right approach, though. I was thinking maybe adding a `setStorage()` method to `oidc.security.common.ts` (so that the Storage property can remain private, and be set after the fact), and then calling this method in the constructor of `oidc.security.service` based off of a new parameter in `auth.configuration`. Thoughts?

**Comment by damienbod** [comment]
@astegmaier super. 

@robisim74 What do you think about the setStorage(), at present only the OidcSecurityService and the AuthConfiguration classes are required, by the user of the lib. 

For me the pull request is good. 

@astegmaier How do you set the injectedStorage: Storage in the common?

thanks

**Comment by damienbod** [comment]
@FabianGosebrink  @robisim74  @astegmaier 
I purpose we merge the pull request as it is, and do another one for the setStorage() enhancement

**Comment by robisim74** [comment]
@damienbod Yes, since a dev has more ways to do it, we should add a property to the configuration. Please, can you provide a repro how a dev will be able to use a cookie after this change?

**Comment by damienbod** [comment]
merged
