### ISSUE TITLE
unauthorized after reloading page

### ISSUE THREAD

**Issue by python-programmer** [damienbod/angular-auth-oidc-client#280]
token lost after page reload.
how to resolve this?

**Comment by klanglie** [comment]
yeah, i run into this problem frequently too when developing my angular applications. I am testing out a work around to store the bearer token in a separate storage mechanism, say a cookie. Only in development. So I have a separate configuration to store that. Then I have a class that gets the token from the special storage place during development, but using the Oidc library when in prod. I think it is helping me out some.

**Comment by python-programmer** [comment]
@klanglie thanks,

`but using the Oidc library when in prod`:  when reload a page in production, is the token valid?

**Comment by damienbod** [comment]
Yes, the token is valid until it expires.

**Comment by damienbod** [comment]
Version 6.0.12 should fix this.
