### ISSUE TITLE
QUESTION: Set Custom Parameters (Outside ReturnUrl 'parameter')

### ISSUE THREAD

**Issue by juanp3053** [damienbod/angular-auth-oidc-client#283]
Is there a way to set a custom parameter outside ReturnUrl param when the AuthorizeUrl is being generated?

I have noticed that when using **OidcSecurityService.setCustomRequestParameters(params: { [key: string]: string | number | boolean })**, and then authorizing with **OidcSecurityService.authorize().** The format generated for the url is the following: 
"http://localhost:XXXX/?returnUrl=/(AuthenticationInformation)%26customparam%3XX/"

I noticed that the special characters are escaped since they are 'inside' the 'ReturnUrl' parameter. But I need them outside for ex. 
http://localhost:XXXX/?returnUrl=/(AuthenticationInformation)/&customparam=XX/. 
Is there any way to accomplish this? 

Thanks in advance for the help

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
