### ISSUE TITLE
There is no intuitive way to specify the prompt parameter

### ISSUE THREAD

**Issue by CobusKruger** [damienbod/angular-auth-oidc-client#287]
The `createAuthorizeUrl` function has a parameter for `prompt` ([as defined in the spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)), but the `authorize` function calls it without this parameter. There is also no obvious way to specify the parameter in config, which worsens the problem.

The workaround I'm using is to pass in a `urlHandler` function, which adds the parameter and then assigns it to `window.location.href` manually. I don't think this is ideal, especially since the parameter is already available in `createAuthorizeUrl` - it is simply not used.

**Comment by damienbod** [comment]
@CobusKruger Could you not use the setCustomRequestParameters function? Maybe this needs better docs.

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.component.ts#L81

Greetings Damien

**Comment by CobusKruger** [comment]
Thanks for the reply. I don't think I would have figured that out. I wound up adding it to the URL and setting the `window.location.href` manually. That works very well, but I'll try setCustomRequestParameters.

My point was really that it is already supported in `createAuthorizeUrl` but then simply left out from `authorize`. That seems like low-hanging fruit.

Anyway, I want to commend you on the solution overall; I'm using it for Azure AD and it really does work very well. And the series of posts are very well written and easy to follow. Very nice indeed.

**Comment by damienbod** [comment]
@CobusKruger Yes, It should be possible to add this per configuration. I'll add a new configuration proper for this, good?

Greetings Damien

**Comment by damienbod** [comment]
@CobusKruger need to think about this, maybe we could have a better way of doing this. At the moment all the optional parameters are like this.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
