### ISSUE TITLE
getting issue while redirecting to oidc portal page 

### ISSUE THREAD

**Issue by fahimulhaque** [damienbod/angular-auth-oidc-client#293]
login:1 Failed to load https://xxxxxxxxxxxxxx/.well-known/openid-configuration: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.210.81.36:4200' is therefore not allowed access.

After adding CORS extension in chrome it workerd .

How dependency on CORS extension can be removed??

**Comment by fahimulhaque** [comment]
Added Interceptor
`@Injectable()
export class CorsInterceptor implements HttpInterceptor {

  intercept(req: HttpRequest < any > , next: HttpHandler) {

    // tslint:disable-next-line:max-line-length
    const corsReq = req.clone({
      setHeaders: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Allow-Methods': '*'
      }
    });
    return next.handle(corsReq);
  }


}` 

but on request Access-Control-Allow-Origin is not being passed and all headers are getting added in CORS headers.

`Provisional headers are shown
Access-Control-Request-Headers: access-control-allow-headers,access-control-allow-methods,access-control-allow-origin
Access-Control-Request-Method: GET
Origin: http://10.210.81.36:4200
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36`

And below error is coming 
Failed to load https://xxxxxxxxxx/.well-known/openid-configuration: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.210.81.36:4200' is therefore not allowed access

**Comment by damienbod** [comment]
Hi @fahimulhaque you need to allow CORS on the STS application, where the ../.well-known/openid-configuration is. 

Greetings Damien

**Comment by fahimulhaque** [comment]
On STS Application i was not handling CORS , Added that and it works fine.

Thanks @damienbod @FabianGosebrink
