### ISSUE TITLE
at_hash hextob64u or hextob64?

### ISSUE THREAD

**Issue by ryanrolland** [damienbod/angular-auth-oidc-client#296]
I am currently working with CAS5 as an OIDC identity provider. It is generating the at_hash using 'standard' Base64 encoding:
https://cryptii.com/pipes/base64-to-hex

I see that the angular-auth-oidc-client is using 'base64 URL' encoding [angular-auth-oidc-client.es5.js]:
![image](https://user-images.githubusercontent.com/4400607/45988346-3707c300-c012-11e8-9a05-cb6b622340db.png)

Who is right here? Is there a way to configure this somewhere?

**Comment by FabianGosebrink** [comment]
@damienbod do we have to change this?

**Comment by damienbod** [comment]
closing this, please re-open is required
