### ISSUE TITLE
userinfo.openid throws 401 Error

### ISSUE THREAD

**Issue by arunprasathv** [damienbod/angular-auth-oidc-client#300]
@damienbod 
We have Enterprise OAuth provider that we use to authenticate internal applications. I get access token and when userinfo.openid api is being called it doesn't take token even though i see it in the method and throws 401 unauthorized error.

What am I missing here? Appreciate your help. 
I see Authorization Header is null or empty in fiddler 
![image](https://user-images.githubusercontent.com/7142390/46437783-2b12b400-c72a-11e8-887b-19abdda91f5b.png)

**Comment by damienbod** [comment]
maybe you don't need to decode the token, if this doesn't work, try checking on the API why the token is rejected

**Comment by arunprasathv** [comment]
I removed decode here, still same issue. In fiddler, i don't see token being sent, it shows just bearer

![image](https://user-images.githubusercontent.com/7142390/46440235-c73fb980-c730-11e8-9866-11281badc358.png)

     */
    OidcDataService.prototype.getIdentityUserData = function (url, token) {
        var /** @type {?} */ headers = new HttpHeaders();
        headers = headers.set('Accept', 'application/json');
        headers = headers.set('Authorization', 'Bearer ' + token);
        return this.httpClient.get(url, {
            headers: headers,
        });
    };
    /**

**Comment by damienbod** [comment]
Hi @arunprasathv 

If the token is not being sent, then it has no value in the parameters. You need to find out why, maybe add some logging, or a exception to check if the token has a value.

I will close this, because it's not directly related to the lib. Hope this is ok.

Greetings Damien
