### ISSUE TITLE
Paste url in new tab unathorized

### ISSUE THREAD

**Issue by oivindth** [damienbod/angular-auth-oidc-client#301]
When opening a new tab and pasting a url the user is not authorized and has to login. How can we avoid this?

**Comment by oivindth** [comment]
Solved by setting openIDImplicitFlowConfiguration.storage = localStorage; Is this the recommended way?

**Comment by damienbod** [comment]
@oivindth What would you like to avoid? If already logged in, and you would like to auto login and redirect back to the page required, then you could use the event for this. Implement a SSO, ie Auto login

**Comment by profet23** [comment]
This could be another example of the refresh_session silently authenticating a new page and not requiring redirects. Sorry. Beating a dead horse.

**Comment by damienbod** [comment]
Version 6.0.12 should fix this.
