### ISSUE TITLE
idcConfigService 'load_using_stsServer' threw an error

### ISSUE THREAD

**Issue by sunilrav** [damienbod/angular-auth-oidc-client#309]
Just upgraded to Angular 6 and angular-auth-oidc-client package to 6.0.12.
Currently getting this error in the Edge browser.

> idcConfigService 'load_using_stsServer' threw an error on calling https://identity.website.com [object Object]
> 
> eval code (977) (1776,13)
> 
> [object Object]: {error: Object, headers: Object, message: "Http failure response for (unknown url): 0 Unknown Error", name: "HttpErrorResponse", ok: false...}
> 
> ERROR TypeError: Unable to get property 'issuer' of undefined or null reference

> [object Error]: {description: "Unable to get property 'issuer' of undefined or null reference", message: "Unable to get property 'issuer' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'issuer' of undefined or null reference at AuthWellKnownEndpoints.prototype.setWellKnownEndpoints (eval code:60:9) at Anonymous function (eval code:179:13) at Anonymous function (http://localhost:62499/dist/vendor.js?v=ugdSNLK1ri_QY0G5Gz0LVDooj-Q6j8ktsHNrbg7HP5c:3892:36) at "

Seems to be working fine in Chrome.

Appreciate any ideas of how I can tackle this.

**Comment by damienbod** [comment]
Is it possible that the HTTP request failed? What is the response in the network tab of the F12?

Greetings Damien

**Comment by sunilrav** [comment]
@damienbod Your are right. Seems like my localhost site on Edge was blocking calls to my id server. I got around it by opening Fiddler. It seems to some how by pass the restriction.

Anyways, I am still cant get it to work on Edge. Currently, token validation fails

> BEGIN authorizedCallback, no auth data
> 
>  getIsAuthorized: false
> 
>  [object Object]
> 
>  authorizedCallback created, begin token validation
> 
>  jwks_uri: https://id.website.com/.well-known/openid-configuration/jwks
> 
>  ValidateStateFromHashCallback failed, state: 15391137914290.22088643089069393 local_state:
> 
>  authorizedCallback incorrect state
> 
>  authorizedCallback, token(s) validation failed, resetting
> 
>  #id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjZFODdCNzM4RkIzNjZCR..[truncated by me]

The site works fine on chrome.
Seems like some kind of a timing issue, any ideas?

**Comment by damienbod** [comment]
incorrect state usually happens when you try to authorize twice at the same time. Check that only 1 authorize request is sent at a time.

**Comment by sunilrav** [comment]
After a lot of debugging I am fairly certain I am only calling this.oidcSecurityService.authorize(); once
Here is the code which I took exactly from you samples. Keep in mind, this works fine in chrome and IE, just doesn't not work in Edge.

In App.Component.ts

```
   constructor(public oidcSecurityService: OidcSecurityService)   {
        if (this.oidcSecurityService.moduleSetup) {
            console.log("this.oidcSecurityService.moduleSetup");
            this.onOidcModuleSetup();
        } else {
            this.oidcSecurityService.onModuleSetup.subscribe(() => {
                console.log("this.oidcSecurityService.moduleSetup sub");
                this.onOidcModuleSetup();
            });
        }

        this.oidcSecurityService.onAuthorizationResult.subscribe(
            (authorizationResult: AuthorizationResult) => {
                console.log("this.oidcSecurityService.onAuthorizationResult.subscribe");
                this.onAuthorizationResultComplete(authorizationResult);
            });  
     }

     private onOidcModuleSetup() {
        if (window.location.hash) {
            console.log("window.location.hash");
            this.oidcSecurityService.authorizedCallback();
        }
        else {
            console.log("else window.location.hash");
            if ('/autologin' !== window.location.pathname) {
                this.write('redirect', window.location.pathname);
            }
           
        }
    }

    private onAuthorizationResultComplete(authorizationResult: AuthorizationResult) {
        console.log("onAuthorizationResultComplete");
        const path = this.read('redirect');
        if (authorizationResult === AuthorizationResult.authorized) {
            this.router.navigate([path]);
        }
        else {
            console.log("/unauthorized");
            this.router.navigate(['/unauthorized']);
        }
    }

    private read(key: string): any {
      const data = localStorage.getItem(key);
      if (data != null) {
        return JSON.parse(data);
      }
      return;
    }

    private write(key: string, value: any): void {
      localStorage.setItem(key, JSON.stringify(value));
    }


    login() {
      this.oidcSecurityService.authorize();
    }

```
Is there anything else I could try?

**Comment by profet23** [comment]
@sunilrav If you enable warning and debug messages... what does the console say is happening?

**Comment by profet23** [comment]
Also... this:

```typescript
        if (this.oidcSecurityService.moduleSetup) {
            console.log("this.oidcSecurityService.moduleSetup");
            this.onOidcModuleSetup();
        } else {
            this.oidcSecurityService.onModuleSetup.subscribe(() => {
                console.log("this.oidcSecurityService.moduleSetup sub");
                this.onOidcModuleSetup();
            });
        }
```

can be replaced by:

```typescript
this.oidcSecurityService.getIsModuleSetup().pipe(
    filter((isModuleSetup: boolean) => isModuleSetup),
    take(1)
).subscribe((isModuleSetup: boolean) => {
    this.onOidcModuleSetup();
});
```

Which is more reliable.

I also recommend switching from `onAuthorizationResult` to `getIsAuthorized()`

**Comment by profet23** [comment]
Sorry... reading more of your message. Seems like you're calling

`AuthWellKnownEndpoints.setWellKnownEndpoints()` with a null value.  How are you populating that?

**Comment by sunilrav** [comment]
> Sorry... reading more of your message. Seems like you're calling
> 
> `AuthWellKnownEndpoints.setWellKnownEndpoints()` with a null value. How are you populating that?

Ignore this part because at that point Edge had some CORS issues. But that part works now.

**Comment by sunilrav** [comment]
> @sunilrav If you enable warning and debug messages... what does the console say is happening?

This is what is in the console on call back.

> 
> TML1300: Navigation occurred.
> mysite.site.com (1,1)
> 
>  CSS3121: The media query -ms-viewport has been deprecated.
> 
>  onUserDataChanged: last = undefined, new = 
> main-client.js (349,40152)
> 
>  STS server: https://id.website.com
> main-client.js (349,40152)
> 
>  IsAuthorizedRace: Silent Renew Not Active. Emitting.
> main-client.js (349,40152)
> 
>  IsAuthorizedRace: Completed
> main-client.js (349,40152)
> 
>  getIsAuthorized: false
> main-client.js (349,40152)
> 
>  BEGIN authorizedCallback, no auth data
> main-client.js (349,40152)
> 
>  getIsAuthorized: false
> main-client.js (349,40152)
> 
> 
> 
> [object Object]: {access_token: "eyJhbGciOiJSUzI1N..}
> 
>  authorizedCallback created, begin token validation
> main-client.js (349,40152)
> 
>  jwks_uri: https://id.website.com/.well-known/openid-configuration/jwks
> main-client.js (349,40152)
> 
>  ValidateStateFromHashCallback failed, state: 15391981355410.41162640842178133 local_state:
> main-client.js (349,40152)
> 
>  authorizedCallback incorrect state
> main-client.js (349,40053)
> 
>  authorizedCallback, token(s) validation failed, resetting
> main-client.js (349,40053)
> 
>  #id_token=eyJhbGciOiJSUzI1NiIsImt
> main-client.js (349,40053)
> 
>  getIsAuthorized: false
> main-client.js (349,40152)
> 
>  /unauthorized

**Comment by profet23** [comment]
This is your problem:

> ValidateStateFromHashCallback failed, state: 15391981355410.41162640842178133 local_state:
> main-client.js (349,40152)

Seems like reading or writing the local_state to/from storage is the problem. 

You may want to put some debugging breakpoints in your storage read/write methods that you showed above.
 
The state is successfully being retrieved from the callback hash.. but the local state seems to be blank.

**Comment by sunilrav** [comment]
@profet23 Did storage testing as you suggested. My read/write seem to work fine because I am using `localStorage`. I tried switching to `sessionStorage` and that didn't work. I just checked in `auth.configuration.ts` that by default the plugin uses `sessionStorage`. 

Is there a way to switch that?

**Comment by profet23** [comment]
Sure thing.

See here:. https://github.com/damienbod/angular-auth-oidc-client/blob/master/README.md#custom-storage

**Comment by profet23** [comment]
Did this work for you @sunilrav ?

**Comment by sunilrav** [comment]
Hmmm, unable to my CustomStorage to kick in

```
import { Injectable } from '@angular/core';
import { AuthConfiguration, OidcSecurityStorage } from 'angular-auth-oidc-client';

@Injectable()
export class CustomStorage implements OidcSecurityStorage {
    private hasStorage: boolean;

    constructor(private authConfiguration: AuthConfiguration) {
        debugger;
        this.hasStorage = typeof Storage !== 'undefined';
    }

    public read(key: string): any {
        debugger;
        if (this.hasStorage) {
            debugger;
            return JSON.parse(localStorage.getItem(key + '_' + this.authConfiguration.client_id));
        }

        return;
    }

    public write(key: string, value: any): void {
        if (this.hasStorage) {
            debugger;
            value = value === undefined ? null : value;
            localStorage.setItem(key + '_' + this.authConfiguration.client_id, JSON.stringify(value));
        }
    }
}

```
In app.module.ts

`AuthModule.forRoot({ storage: CustomStorage }),`

Continuing to wrestle with it....

**Comment by profet23** [comment]
@sunilrav try getting rid of the constructor.

**Comment by sunilrav** [comment]
After further testing it doesn't seem like a local/session storage issue anymore. The first time I try logging in I get unauthorized but when I retry in the same browser instance it succeeds.
I recorded a clip below to explain what I mean.
https://youtu.be/MUHjmSYci5M

**Comment by damienbod** [comment]
closing this, please re-open is required

**Comment by teebszet** [comment]
Is it possible to add retries to the load_using_custom_stsServer option in case of flaky network connection? 

```
angular-auth-oidc-client.js:1719 OidcConfigService 'load_using_custom_stsServer' threw an error on calling https://xxxxx/.well-known/openid-configuration 
HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: "Unknown Error", url: "https://xxxxx/.well-known/openid-configuration", ok: false, …}

core.js:9110 ERROR TypeError: Cannot read property 'issuer' of undefined
    at AuthWellKnownEndpoints.setWellKnownEndpoints (angular-auth-oidc-client.js:35)
    at TapSubscriber._tapNext (auth.service.ts:56)
    at TapSubscriber._next (tap.js:40)
    at TapSubscriber.next (Subscriber.js:49)
    at ThrowIfEmptySubscriber._next (throwIfEmpty.js:24)
    at ThrowIfEmptySubscriber.next (Subscriber.js:49)
    at TakeSubscriber._next (take.js:35)
    at TakeSubscriber.next (Subscriber.js:49)
    at Subject.next (Subject.js:39)
    at CatchSubscriber.selector (angular-auth-oidc-client.js:1720)
```

**Comment by damienbod** [comment]
@teebszet this would be possible, you could also implement your own cusrom loader. Not sure, if custom retries should be part of this lib.
