### ISSUE TITLE
Getting error "authorizedCallback incorrect at_hash"

### ISSUE THREAD

**Issue by salmanjaved2** [damienbod/angular-auth-oidc-client#313]
Hi  see my issue below:

This is my first time submitting an issue on Github, I hope you will be patient.  Not sure exactly what details to provide.  I'm finding issues with the access_token validation. 

validate_id_token_iat_max_offset: 1572 < 20000
angular-auth-oidc-client.es5.js:664 Token not expired?: 1539245811000 > 1539202612575  (true)
angular-auth-oidc-client.es5.js:664 From the server:undefined
angular-auth-oidc-client.es5.js:664 client validation not decoded:-yY5bM2hu5ZwQhcx-MWjdQ
angular-auth-oidc-client.es5.js:664 -gen access---yY5bM2hu5ZwQhcx-MWjdQ
authorizedCallback incorrect at_hash

**Comment by profet23** [comment]
@salmanjaved2 you should edit your comment and remove the token. It contains sensitive information.

**Comment by salmanjaved2** [comment]
Thanks, I just did it.  Appreciate the heads up.

Salman Javed

________________________________
