### ISSUE TITLE
QUESTION: Getting OidcSecurityCheckSession not receiving check session response messages. Server unreachable?

### ISSUE THREAD

**Issue by gerardl123** [damienbod/angular-auth-oidc-client#316]
I'm trying to use start_checksession so that I can redirect the user to the home page when they logoff from a different browser tab or window, but I keep getting this error even when the user is not logged in: 
OidcSecurityCheckSession not receiving check session response messages. Server unreachable?

I'm not too sure if I'm using the start_checksession correctly but should it still be checking the session even if you're not logged in?

I'm using version 7.0.0

**Comment by profet23** [comment]
The check session iframe is not loading properly. Do you have your identity server setup to allow your application to load it in an iframe?

**Comment by gerardl123** [comment]
I think it's set up to allow the check session iframe and i can see the check session javascript code on the iframe when I inspect it. I'm not too sure whether this is an indication of the check session iframe loading properly though.

 The check session seems to work fine when I'm actually logged in and then as soon as I logoff from another tab or window it detects this and emits the onCheckSessionChanged event as expected. But its only when I'm not actually logged in that I keep getting the error. 

Could it be because when I'm not logged in I would have a blank session_state which means the check session service would not send a message to the iframe to check the session and therefore no check session response going back hence the error?

**Comment by profet23** [comment]
Ah ok. This is probably a bug then. You should pause listening for the onchecksessionchanged event until the user is logged in again. But yes. The library should be quieter.

**Comment by avinash-more** [comment]
@damienbod  this issue released? can you please give version?

**Comment by damienbod** [comment]
hi @avinash-more use the latest version. This works when iframes are supported, which are slowly getting blocked by browsers...

**Comment by avinash-more** [comment]
it is **11.1.3**

![image](https://user-images.githubusercontent.com/45229708/97592834-18612b00-1a27-11eb-98a4-ae0acd7cecda.png)
