### ISSUE TITLE
Redirect URL not working for Domain name with load balance 

### ISSUE THREAD

**Issue by AjitkSa** [damienbod/angular-auth-oidc-client#318]
Hi, 

My code is working on localhost but when i deploy on server not working. I am trying to understand why it showing "unauthorized_client: 'redirect_uri' is unsafe."  only with domain name.

**Comment by inpicksys** [comment]
Incorrect redirect uri. Each symbol matters - verify slash for example

**Comment by profet23** [comment]
@AjitkSa did you get this working? Can we close this?
