### ISSUE TITLE
isAuthorized is always false after updating to latest version of library & angular 7

### ISSUE THREAD

**Issue by inpicksys** [damienbod/angular-auth-oidc-client#322]

**Comment by profet23** [comment]
Need more information. Are you using the getIsAuthorized() observable?

What is your configuration?

**Comment by inpicksys** [comment]
app.module:

providers: [
        ConfigurationService,
        StorageService,
        OidcConfigService,
        OidcSecurityService,
        {
            provide: APP_INITIALIZER,
            useFactory: init,
            deps: [ConfigurationService],
            multi: true
        },
        {
            provide: HTTP_INTERCEPTORS,
            useClass: AuthInterceptor,
            multi: true
        },
        AuthorizationGuard,
        AuthorizationCanGuard,
        AuthService

    ],
export function init(configService: ConfigurationService): Function {
    return () => configService.loadConfig();
}


export class AppModule {
    constructor(
        private oidcSecurityService: OidcSecurityService,
        private configService: ConfigurationService,
    ) {
        this.configService.onConfigurationLoaded
            .pipe(
                catchError(error => {


                    return of(false);

                })
            )
            .subscribe(() => {
                this.configService.setupSSO(this.oidcSecurityService);
            })
    }
}

AuthInterceptor
import { Injectable, Injector } from '@angular/core';
import { HttpInterceptor, HttpRequest, HttpHandler, HttpEvent, HttpResponse } from '@angular/common/http';

import { Observable } from 'rxjs';
import { OidcSecurityService } from 'angular-auth-oidc-client';

@Injectable()
export class AuthInterceptor implements HttpInterceptor {

    private oidcSecurityService: OidcSecurityService;

    constructor(private injector: Injector) {
    }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

        let requestToForward = req;

        if (this.oidcSecurityService === undefined) {
            this.oidcSecurityService = this.injector.get(OidcSecurityService);
        }

        if (this.oidcSecurityService !== undefined) {
            const token = this.oidcSecurityService.getToken();
            if (token !== '') {
                const tokenValue = 'Bearer ' + token;
                requestToForward = req.clone({ setHeaders: { Authorization: tokenValue } });
            }
        } else {
            console.log('OidcSecurityService undefined: NO auth header!');
        }

        return next.handle(requestToForward);
    }
}

AuthGuard

import { Injectable, Injector } from '@angular/core';
import { Router, CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, CanLoad } from '@angular/router';
import { Observable, throwError, never, of } from 'rxjs';
import { map, take, catchError, tap, switchMapTo } from 'rxjs/operators';

import { OidcSecurityService } from 'angular-auth-oidc-client';
import { AuthService } from '../services/auth.service';

@Injectable()
export class AuthorizationGuard implements CanActivate, CanLoad {

    constructor(
        private router: Router,
        private oidcSecurityService: OidcSecurityService,
        private authService: AuthService,
        private injector: Injector
    ) { }

    canLoad(): Observable<boolean> | Promise<boolean> | boolean {
        console.log('AuthorizationGuard, canLoad:' + this.oidcSecurityService.moduleSetup);
        return this.authRoute('canLoad', location.pathname);

    }
    public canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean | Promise<boolean> {
        console.log(route + '' + state);
        console.log('AuthorizationGuard, canActivate');
        if (this.oidcSecurityService === undefined) {
            this.oidcSecurityService = this.injector.get(OidcSecurityService);
        }
        return this.authRoute('canActivate', state.url);
    }

    private authRoute(source: string, url: string = null): Observable<boolean> | Promise<boolean> | boolean {

        return this.oidcSecurityService.getIsAuthorized().pipe(
            tap((isAuthorized: boolean) => {
                console.log('AuthorizationGuard, canActivate isAuthorized: ' + isAuthorized);
                debugger;
                if (!window.location.hash) {

                    if (url && url.length > 0) {
                        this.authService.setRedirectUrl(url);
                    } else {
                        this.authService.removeRedirectUrl();
                    }
                    console.log('AuthorizationGuard auto login');
                    this.router.navigate(['/autologin']);
                }

                if (!isAuthorized) {
                    return false;
                    //this.router.navigate(['/unauthorized']);
                }

            })
        );

    }
}

AutoLogin


import { Component, OnInit, OnDestroy } from '@angular/core';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { catchError } from 'rxjs/operators';

import { Router, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { throwError, of } from 'rxjs';

@Component({
    selector: 'app-auto-component',
    templateUrl: './auto-login.component.html'
})

export class AutoLoginComponent implements OnInit, OnDestroy {
    lang: any;
    constructor(public oidcSecurityService: OidcSecurityService
       
    ) {
        
        this.oidcSecurityService.onModuleSetup.
            subscribe(() => { this.onModuleSetup(); });
    }

    ngOnInit() {
        if (this.oidcSecurityService.moduleSetup) {
            this.onModuleSetup();
        }
    }

    ngOnDestroy(): void {
        this.oidcSecurityService.onModuleSetup.unsubscribe();
    }

    private onModuleSetup() {
        this.oidcSecurityService.authorize();
    }
}


AppComponent
import { Component, Inject, OnDestroy, OnInit, ViewChild, ViewContainerRef } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { Platform } from '@angular/cdk/platform';
import { Subject, Subscription, of } from 'rxjs';
import { takeUntil, catchError } from 'rxjs/operators';

import { OidcSecurityService } from 'angular-auth-oidc-client';
import { ConfigurationService } from 'app/shared/services/configuration.service';
import { StorageService } from 'app/shared/services/storage.service';

import {
    MatSnackBar
} from '@angular/material';
import { Router, NavigationStart } from '@angular/router';
import { AuthService } from './shared/services/auth.service';

@Component({
    selector: 'app',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
    isAuthorizedSubscription: Subscription | undefined;
    isAuthorized = false;

    onChecksessionChanged: Subscription | undefined;
    checksession = false;


    // Private
    private _unsubscribeAll: Subject<any>;
    /**
     * Constructor
     *
     */
    constructor(
        @Inject(DOCUMENT) private document: any,
        private _platform: Platform,

        public snackBar: MatSnackBar,
        private configurationService: ConfigurationService,
        public oidcSecurityService: OidcSecurityService,
        private router: Router,
        private authService: AuthService,
    ) {

        // Set the private defaults
        this._unsubscribeAll = new Subject();


        // Auth Init
        if (this.oidcSecurityService.moduleSetup) {
            this.doCallbackLogicIfRequired();
        } else {
            this.oidcSecurityService.onModuleSetup.subscribe(() => {
                this.doCallbackLogicIfRequired();
            });
        }
    }

    ngOnInit(): void {
       this.isAuthorizedSubscription = this.oidcSecurityService.getIsAuthorized().subscribe(
            (isAuthorized: boolean) => {
                this.isAuthorized = isAuthorized;
                if (this.isAuthorized === true) {
                    this.authService.saveUserInfo();
                }
            });
    }

    ngOnDestroy(): void {
        // Unsubscribe from all subscriptions
        this._unsubscribeAll.next();
        this._unsubscribeAll.complete();

        if (this.isAuthorizedSubscription) {
            this.isAuthorizedSubscription.unsubscribe();
        }
        this.oidcSecurityService.onModuleSetup.unsubscribe();
        this.oidcSecurityService.onCheckSessionChanged.unsubscribe();
        this.oidcSecurityService.onAuthorizationResult.unsubscribe();
    }
    login() {
        console.log('start login');
       this.oidcSecurityService.authorize();
    }

    logout() {
        console.log('start logoff');
        this.oidcSecurityService.logoff();
    }

    private doCallbackLogicIfRequired() {
        if (window.location.hash) {
            this.oidcSecurityService.authorizedCallback();
        }
    }

    // private onAuthorizationResultComplete(authorizationResult: AuthorizationResult) {
    //     console.log('AppComponent:onAuthorizationResultComplete ' + authorizationResult);
    //     const path = this.authService.getRedirectUrl();
    //     switch (authorizationResult) {
    //         case AuthorizationResult.authorized:
    //             if (path) {
    //                 this.router.navigate([path]);
    //             } else {
    //                 this.router.navigate(['/project-dashboard']);
    //             }
    //             break;
    //         case AuthorizationResult.unauthorized:
    //             this.authService.setRedirectUrl(window.location.pathname);
    //             //     this.write('redirect', window.location.pathname);
    //             this.router.navigate([['autologin']]);
    //             // if (window.parent) {
    //             //     window.parent.location.href = '/unauthorized';
    //             // } else {
    //             //     window.location.href = '/unauthorized';
    //             // }
    //             // this.router.navigate(['/unauthorized']);
    //             break;
    //         case AuthorizationResult.forbidden:
    //             this.router.navigate(['/forbidden']);
    //             break;
    //     }

    //     // if (authorizationResult === AuthorizationResult.authorized) {
    //     //     debugger;
    //     //     this.router.navigate([path]);
    //     // } else if (authorizationResult == AuthorizationResult.unauthorized) {
    //     //     debugger;
    //     //     this.write('redirect', window.location.pathname);
    //     //     this.router.navigate([['autologin']]);
    //     // }
    //     // else if (authorizationResult == AuthorizationResult.forbidden) {
    //     //     debugger;
    //     //     this.router.navigate(['/forbidden']);
    //     // }
    // }
}

Config Service

import { Injectable, Output, EventEmitter, Injector } from '@angular/core';
import { Http, Response, RequestOptionsArgs, RequestMethod, Headers } from '@angular/http';
import { IConfiguration } from '../models/configuration.model';
import { StorageService } from 'app/shared/services/storage.service';
import 'rxjs/Rx';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import { Observer } from 'rxjs/Observer';
import 'rxjs/add/operator/map';
import { Subject } from 'rxjs/Subject';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { OpenIDImplicitFlowConfiguration } from 'angular-auth-oidc-client';
import { AuthWellKnownEndpoints } from 'angular-auth-oidc-client';
import { of } from 'rxjs';
import { reject } from 'q';
import { Router } from '@angular/router';

@Injectable({
    providedIn: 'root'
})
export class ConfigurationService {
    @Output() onConfigurationLoaded: EventEmitter<boolean> = new EventEmitter<boolean>();
    serverSettings: any;
    wellKnownEndpoint: any;

    private router: Router;


    constructor(private http: Http,
        private storageService: StorageService,
        private injector: Injector) {

    }

    async loadConfig() {
        this.router = this.injector.get(Router);
        const baseUri = document.baseURI.endsWith('/') ? document.baseURI : `${document.baseURI}/`;
        let configUrl = `${baseUri}Home/Configuration`;
        try {

            await this.loadAPIConfig(configUrl);
            await this.loadSSOConfig(this.serverSettings.identityUrl);
            this.onConfigurationLoaded.emit(true);

        } catch (err) {
            console.error(`ConfigService threw an error on calling ${configUrl}`, err);
            this.onConfigurationLoaded.emit(false);
            this.onConfigurationLoaded.next(null);
            this.router.navigate(['maintenance'], { replaceUrl: true });
            reject(false);
            return of(false);
        }
    }

    private async loadAPIConfig(configUrl: string) {
        const response = await fetch(configUrl);
        if (!response.ok) {
            //or route or what else
            this.router.navigate(['maintenance'], { replaceUrl: true });
            throw new Error(response.statusText);
        }

        console.log('server settings loaded');
        this.serverSettings = await response.json();
        console.log(this.serverSettings);
        this.storageService.store('identityUrl', this.serverSettings.identityUrl);
        this.storageService.store('spaUrl', this.serverSettings.spaUrl);
        this.storageService.store('spaClientId', this.serverSettings.spaClientId);
        this.storageService.store('staffUrl', this.serverSettings.staffUrl);
        this.storageService.store('servicesUrl', this.serverSettings.servicesUrl);
        this.storageService.store('supportUrl', this.serverSettings.supportUrl);

        let userManagementUrl = `${this.serverSettings.identityUrl}/api/UserManagement`;
        this.serverSettings.userManagement = userManagementUrl;
        this.storageService.store('userManagement', userManagementUrl);

        let organizationUrl = `${this.serverSettings.identityUrl}/api/Organization`;
        this.serverSettings.organizationUrl = organizationUrl;
        this.storageService.store('organizationUrl', organizationUrl);



        this.storageService.store('marketingUrl', this.serverSettings.marketingUrl);
        this.storageService.store('purchaseUrl', this.serverSettings.purchaseUrl);
        this.storageService.store('signalrHubUrl', this.serverSettings.signalrHubUrl);
        this.storageService.store('activateCampaignDetailFunction', this.serverSettings.activateCampaignDetailFunction);
    }

    private async loadSSOConfig(stsServer: string) {
        try {
            const response = await fetch(`${stsServer}/.well-known/openid-configuration`);
            this.wellKnownEndpoint = await response.json();
            debugger;
        } catch (ex) {
            this.router.navigate(['maintenance'], { replaceUrl: true });
            this.onConfigurationLoaded.emit(false);
            this.onConfigurationLoaded.next(null);
            reject(false);
            return of(false);
        }
    }

    public setupSSO(oidcSecurityService: OidcSecurityService) {
        debugger;
        const openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
        //console.log(configService.serverSettings);
        openIDImplicitFlowConfiguration.stsServer = this.serverSettings.identitySettings.stsServer;
        openIDImplicitFlowConfiguration.redirect_url = this.serverSettings.identitySettings.redirect_url;
        // The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer
        // identified by the iss (issuer) Claim as an audience.
        // The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience,
        // or if it contains additional audiences not trusted by the Client.
        openIDImplicitFlowConfiguration.client_id = this.serverSettings.identitySettings.client_id;
        openIDImplicitFlowConfiguration.response_type = this.serverSettings.identitySettings.response_type;
        openIDImplicitFlowConfiguration.scope = this.serverSettings.identitySettings.scope;

        openIDImplicitFlowConfiguration.post_logout_redirect_uri = `${this.serverSettings.spaUrl}/maintenance`;
        openIDImplicitFlowConfiguration.start_checksession = false;//this.serverSettings.identitySettings.start_checksession;

        openIDImplicitFlowConfiguration.silent_renew = false;
        openIDImplicitFlowConfiguration.silent_renew_url = `${this.serverSettings.spaUrl}/silent-renew.html`;

        openIDImplicitFlowConfiguration.post_login_route = this.serverSettings.identitySettings.startup_route;
        // HTTP 403
        openIDImplicitFlowConfiguration.forbidden_route = this.serverSettings.identitySettings.forbidden_route;
        // HTTP 401
        openIDImplicitFlowConfiguration.unauthorized_route = this.serverSettings.identitySettings.unauthorized_route;
        openIDImplicitFlowConfiguration.log_console_warning_active = true;
        openIDImplicitFlowConfiguration.log_console_debug_active = true;
        // id_token C8: The iat Claim can be used to reject tokens that were issued too far away from the current time,
        // limiting the amount of time that nonces need to be stored to prevent attacks.The acceptable range is Client specific.
        openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 600;

        openIDImplicitFlowConfiguration.trigger_authorization_result_event = true;
        openIDImplicitFlowConfiguration.auto_userinfo = false;
        openIDImplicitFlowConfiguration.auto_clean_state_after_authentication = false;
        //TODO: Figure out where it configured!!!!!
        //configuration.FileServer = this.oidcConfigService.clientConfiguration.apiFileServer;
        //configuration.Server = this.oidcConfigService.clientConfiguration.apiServer;

        const authWellKnownEndpoints = new AuthWellKnownEndpoints();
        authWellKnownEndpoints.issuer = `${this.serverSettings.identityUrl}`;
        authWellKnownEndpoints.jwks_uri = `${this.serverSettings.identityUrl}/.well-known/openid-configuration/jwks`;
        authWellKnownEndpoints.authorization_endpoint = `${this.serverSettings.identityUrl}/connect/authorize`;
        authWellKnownEndpoints.token_endpoint = `${this.serverSettings.identityUrl}/connect/token`;
        authWellKnownEndpoints.userinfo_endpoint = `${this.serverSettings.identityUrl}/connect/userinfo`;
        authWellKnownEndpoints.end_session_endpoint = `${this.serverSettings.identityUrl}/connect/endsession`;
        authWellKnownEndpoints.check_session_iframe = `${this.serverSettings.identityUrl}/connect/checksession`;
        authWellKnownEndpoints.revocation_endpoint = `${this.serverSettings.identityUrl}/connect/revocation`;
        authWellKnownEndpoints.introspection_endpoint = `${this.serverSettings.identityUrl}/connect/introspect`;
        //authWellKnownEndpoints.setWellKnownEndpoints(this.oidcConfigService.wellKnownEndpoints);
        oidcSecurityService.setupModule(openIDImplicitFlowConfiguration, this.wellKnownEndpoint);

    }
    clear() {
        this.storageService.clear();
    }
}

**Comment by inpicksys** [comment]
So at least -> autologin - redirects to identity server, user successfully  logged in, and auth guard logs not authorized result, and no route startup page

**Comment by inpicksys** [comment]
Will be appreciated for any suggestions.

**Comment by profet23** [comment]
@inpicksys that's a lot of unformatted code. Do you have a github repo setup that I can just clone?

Is this happening with 7.0.2? (Released yesterday)

Can you post the actual console logs (redact any sensitive user info like token contents)? 

I'm more curious with how the library came to the false is authorized on callback.

**Comment by profet23** [comment]
Wait. Are you saying that your authguard is being triggered on the callback page?

It should not. Your callback page should simply process the hash if it exists and then redirect.

It should not be protected with an authguard.

**Comment by inpicksys** [comment]
I have private github repo

**Comment by inpicksys** [comment]
Your callback page should simply process the hash if it exists and then redirect:
authcallback.component? 
ngInit()  with redirection to real init page?

**Comment by profet23** [comment]
I do NOT want access to sensitive info. (Also, you shouldn't store secrets in github repos).

Is your callback route protected via an authguard?

**Comment by mARiote** [comment]
I'm having issues too. After sts redirect I got this message on the console "IsAuthorizedRace: Timeout reached. Emitting." and session storage keys are generated but with empty values.
If I delete session data and hit F5 the data is created ok and the isAuthorized is true.

**Comment by profet23** [comment]
If you're racing, that means you have silent renew enabled.

But if it's timing out, that means that silent renew is not running properly.

Logs would be useful.

**Comment by inpicksys** [comment]
server settings loaded
main.js:25079 Object
vendor.js:151289 onUserDataChanged: last = undefined, new = 
vendor.js:151289 STS server: http://localhost:5105
vendor.js:151289 IsAuthorizedRace: Silent Renew Not Active. Emitting.
vendor.js:151289 IsAuthorizedRace: Completed
vendor.js:151289 getIsAuthorized: false

**Comment by inpicksys** [comment]
Removing authguard from callback page/or home 
this logs
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
vendor.js:151289 ValidateStateFromHashCallback failed, state: 15401300733180.283879777527434 local_state:
vendor.js:151280 authorizedCallback incorrect state
push../node_modules/angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.LoggerService.logWarning @ vendor.js:151280
vendor.js:151280 authorizedCallback, token(s) validation failed, resetting
push../node_modules/angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.LoggerService.logWarning @ vendor.js:151280
vendor.js:151280 #id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjZCN0FDQzUyMDMwNUJGREI0RjcyNTJEQUVCMjE3N0NDMDkxRkFBRTEiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJhM3JNVWdNRnY5dFBjbExhNnlGM3pBa2ZxdUUifQ.eyJuYmYiOjE1NDAxMzAwNzQsImV4cCI6MTU0MDEzMDEzNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTA1IiwiYXVkIjoiTHVjeVdlYkFwcCIsIm5vbmNlIjoiTjAuNTc4MDQxMjAzOTM0MDQ3MjE1NDAxMzAwNzMzMTkiLCJpYXQiOjE1NDAxMzAwNzQsImF0X2hhc2giOiJ5MVItNVpsS0pLVU9IYi1uWFlLdV9RIiwic2lkIjoiOTI5ZTIyOTcxMWI5ZTlmNTZiZDVhMzQxNzdmNDg0MTgiLCJzdWIiOiJjZTY3YzZiZC05ZmE5LTQyN2UtOWVjYS01YjVkOTZhMGM0ODMiLCJhdXRoX3RpbWUiOjE1NDAxMTg5MjUsImlkcCI6ImxvY2FsIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiSW5QaWNrU3lzIiwibmFtZSI6IkluUGlja1N5cyIsImVtYWlsIjoiaW5waWNrc3lzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZ2l2ZW5fbmFtZSI6IkluUGlja1N5cyIsInJvbGUiOlsidXNlciIsIm9yZ2FuaXphdGlvbnMiLCJvcmdhbml6YXRpb25zLmFkbWluIiwib3JnYW5pemF0aW9ucy51c2VyIiwiT3JnYW5pemF0aW9ucyJdLCJmaXJzdE5hbWUiOiJNaXNoYSIsImxhc3ROYW1lIjoiU3RydXRpbnNreSIsInVzZXJuYW1lIjoiTWlzaGEgU3RydXRpbnNreSIsInBob25lX251bWJlciI6IiszODA2Njg0ODQwNjQiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOmZhbHNlLCJhbXIiOlsicHdkIl19.hFIKq-dfyxFSjrGdlI8h1hn_7tJ1hqR9v3zYvN1vISMQ-EyUX-6Po-f8-hDv0BfIDuYosDDlWj0VboARYCiaZjaDzuZRycQfnnNp4Ff4fdLUTLyWs3dpwFJ5nkSAJNOuya6c4oI5SvPhdfrfNWzL94hYAZXpVvnke2s94nfkXMsyg3roluyM4QlccOQ_IGyKQFR0tFYUIuCEIqWELnWAAavDd_9on4tWqB20_HS2mYp2T96n4J0dMYVU1gN7OGGGtZOPvi5Rr3F6LL9GvH6KGDrCqfYr8DuXhNYhaB6Jn1oNqgthjZu2bVxVx_trmVL_5vlczpmN27tISysrVx5atA&access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjZCN0FDQzUyMDMwNUJGREI0RjcyNTJEQUVCMjE3N0NDMDkxRkFBRTEiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJhM3JNVWdNRnY5dFBjbExhNnlGM3pBa2ZxdUUifQ.eyJuYmYiOjE1NDAxMzAwNzQsImV4cCI6MTU0MDEzMDQwNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTA1IiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTEwNS9yZXNvdXJjZXMiLCJvcmdhbml6YXRpb25zIl0sImNsaWVudF9pZCI6Ikx1Y3lXZWJBcHAiLCJzdWIiOiJjZTY3YzZiZC05ZmE5LTQyN2UtOWVjYS01YjVkOTZhMGM0ODMiLCJhdXRoX3RpbWUiOjE1NDAxMTg5MjUsImlkcCI6ImxvY2FsIiwiZ2l2ZW5fbmFtZSI6IkluUGlja1N5cyIsInJvbGUiOlsidXNlciIsIm9yZ2FuaXphdGlvbnMiLCJvcmdhbml6YXRpb25zLmFkbWluIiwib3JnYW5pemF0aW9ucy51c2VyIiwiT3JnYW5pemF0aW9ucyJdLCJlbWFpbCI6WyJpbnBpY2tzeXNAZ21haWwuY29tIiwiaW5waWNrc3lzQGdtYWlsLmNvbSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJJblBpY2tTeXMiLCJmaXJzdE5hbWUiOiJNaXNoYSIsImxhc3ROYW1lIjoiU3RydXRpbnNreSIsInVzZXJuYW1lIjoiTWlzaGEgU3RydXRpbnNreSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfbnVtYmVyIjoiKzM4MDY2ODQ4NDA2NCIsInBob25lX251bWJlcl92ZXJpZmllZCI6ZmFsc2UsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJlbWFpbCIsIm9yZ2FuaXphdGlvbnMiXSwiYW1yIjpbInB3ZCJdfQ.QslI_9FguC3yjtutsVB1Fn6XZN7JHT2QAcnAct66GccEboupg-dbUpwQitQRqkmE5gyjQiPAeO1CpZwR_T47EU4ViSVzo6giC_BZeD_zxkKTz-0lQ5LYxk1L35xVLQptGb-onxwP4SJhqEstijQIAp2Kplx1aLe1GE5z5SFh0tpgerC_97-94A-lN76cm3eHd8dHJIlhIRZ454iz-goN7Z-EsZul_0uqSYJ8OJTa0Nt4UcJ9B-G5fvn4umhBZ0yq1IQhyIj2VqOXr7SND3_fNJQwPpNShrt92bvPVeLR-22dE1zc33fjGH8TIE9kjirM1P71l9wonFOqiI4mh3M6CQ&token_type=Bearer&expires_in=330&scope=openid%20profile%20email%20organizations&state=15401300733180.283879777527434&session_state=Jbl6SXhWMOCo7qtdOy5rreQ1KL6fOs0UTWdMNtOit0g.6e0284592ed98b0780b97371f94848f6
push../node_modules/angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.LoggerService.logWarning @ vendor.js:151280
vendor.js:151289 getIsAuthorized: false

**Comment by profet23** [comment]
No reason to protect the redirect_uri with an authguard. All it should be doing is calling `oidcSecurityService.authorizedCallback();` and then redirecting.

My guess is that angular is preventing the module from loading and thus your app is never actually processing the callback hash and sending it to the library for processing.

**Comment by profet23** [comment]
@inpicksys please edit your comment and remove the token. It contains sensitive information.

**Comment by inpicksys** [comment]
which module? Could you explain? How it can be fixed? 
What is proper way to get it worked?

**Comment by inpicksys** [comment]
Thank you

**Comment by profet23** [comment]
@inpicksys it seems like maybe you are calling authorize() multiple times?  The internal state seems to be wrong. Is it being called multiple times?

**Comment by inpicksys** [comment]
called once in auth guard

 return this.oidcSecurityService.getIsAuthorized().pipe(
            tap((isAuthorized: boolean) => {
                console.log('AuthorizationGuard, canActivate isAuthorized: ' + isAuthorized);
                debugger;
                if (!window.location.hash) {

                    if (url && url.length > 0) {
                        this.authService.setRedirectUrl(url);
                    } else {
                        this.authService.removeRedirectUrl();
                    }
                    console.log('AuthorizationGuard auto login');
                    this.router.navigate(['/autologin']);
                }

                if (!isAuthorized) {
                    return false;
                   
                }

            })
        );

and 
Autologin

import { Component, OnInit, OnDestroy } from '@angular/core';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { catchError } from 'rxjs/operators';

import { Router, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { throwError, of } from 'rxjs';

@Component({
    selector: 'app-auto-component',
    templateUrl: './auto-login.component.html'
})

export class AutoLoginComponent implements OnInit, OnDestroy {

    constructor(public oidcSecurityService: OidcSecurityService,
    ) {
       this.oidcSecurityService.onModuleSetup.
            subscribe(() => { this.onModuleSetup(); });
    }

    ngOnInit() {
        if (this.oidcSecurityService.moduleSetup) {
            this.onModuleSetup();
        }
    }

    ngOnDestroy(): void {
        this.oidcSecurityService.onModuleSetup.unsubscribe();
    }

    private onModuleSetup() {
        this.oidcSecurityService.authorize();
    }
}

only one redirection from authguard

**Comment by inpicksys** [comment]
sockjs.js:2998 WebSocket connection to 'ws://localhost:5104/sockjs-node/266/ajphiue3/websocket'
failed: WebSocket is closed before the connection is established.

**Comment by profet23** [comment]
And if you put a console.log in the `onModuleSetup()` function does it appear multiple times?

**Comment by inpicksys** [comment]
@profet23 Anyway I appreciate you for Sunday's conversation & help.

**Comment by profet23** [comment]
I use local storage.

**Comment by profet23** [comment]
@inpicksys feel free to close the issue I'd it's resolved.

@mARiote please open a new issue if you need further help.

**Comment by inpicksys** [comment]
Closed according discussion
