### ISSUE TITLE
Login issue in production

### ISSUE THREAD

**Issue by mARiote** [damienbod/angular-auth-oidc-client#323]
I'm having an issue with auth in production mode. In development machine it works without issues.

When I try to login in the app I got this log in console
`onUserDataChanged: last = undefined, new = `
`STS server: xxxxxxxx`
`Silent Renew is active, check if token in storage is active`
`IsAuthorizedRace: Timeout reached. Emitting.`
`IsAuthorizedRace: Completed`
`getIsAuthorized: false`

If i check in session storage i can see all values empty except authNonce_site and authStateControl_site

I need to delete both values and refresh tab and get the user logged in. Then, silent renew and session check start to work without issues

`Silent Renew is active, check if token in storage is active`
`Silent Renew or login not running, try to refresh the session`
`BEGIN refresh session Authorize`
`RefreshSession created. adding myautostate: 15401720175730.2350240670221373`
`startRenew for URL: xxxxxxx`
`silentRenewEventHandler`
`BEGIN authorizedCallback, no auth data`
`{token_type: "Bearer", access_token: ...`
`authorizedCallback created, begin token validation`
`jwks_uri: ...`
`validate_id_token_iat_max_offset: 2423 < 10000`
`Token not expired?: 1540173217000 > 1540172019425  (true)`
`From the server: ....`
`client validation not decoded: ....`
`AuthorizedCallback token(s) validated, continue`
`...`
`storing to storage, getting the roles`
`IsAuthorizedRace: Existing token is still authorized.`
`IsAuthorizedRace: Completed`
`getIsAuthorized: true`
`authorizedCallback id_token token flow`
`onUserDataChanged: last = , new = [object Object]`
`...`
`runTokenValidation silent-renew running`
`<iframe id=​"myiFrameForCheckSession" style=​"display:​ none;​" src(unknown)>​…​</iframe>​`
`OidcSecurityCheckSession pollServerSession session_state is blank`
`onCheckSessionChanged`
`<iframe id=​"myiFrameForCheckSession" style=​"display:​ none;​" src(unknown)>​…​</iframe>`​
`OidcSecurityCheckSession pollServerSession session_state is blank`
`onCheckSessionChanged`
`silentRenewHeartBeatCheck`
`	silentRenewRunning: false`
`	idToken: true`
`	_userData.value: true`
`Token not expired?: 1540173217000 > 1540172029851  (true)`
`<iframe id=​"myiFrameForCheckSession" style=​"display:​ none;​" src(unknown)>​…​</iframe>​`
`OidcSecurityCheckSession pollServerSession session_state is blank`
`onCheckSessionChanged`
`silentRenewHeartBeatCheck`
`	silentRenewRunning: false`
`	idToken: true`
`	_userData.value: true`
`Token not expired?: 1540173217000 > 1540172032861  (true)`

**Comment by mARiote** [comment]
It's was a redirect issue.  The STS redirect is to "/" route and the app redirects to "/home". For any reason in production code the the login process didn't work. I changed the login redirect to "/home" and worked fine.

**Comment by profet23** [comment]
The fact that this is working locally and not in production has me thinking that maybe it's a cors issue?

```
IsAuthorizedRace: Timeout reached. Emitting
```

That line tells me that silent renew is configured, but not working properly. 

Is your authority setup properly in production? Cors rules and silent renew redirect url?

What do you see in the network tab with the silent renew?

**Comment by profet23** [comment]
oh... i think github is having issues. didn't see that you solved the issue.

Glad you're all sorted.
