### ISSUE TITLE
GetPayLoadFomIdToken special characters

### ISSUE THREAD

**Issue by maarten-vdb** [damienbod/angular-auth-oidc-client#324]
I've been having issues with getting the payload from the token, which in some cases can contain special characters like é or ã for names. The problem is that the conversion that's being done reads characters form a different characterset, as far as I can see.

The problem seems to be in src/services/oidc-token-helper.service.ts , line 74
 `return typeof window !== 'undefined' ? window.atob(output) : new Buffer(output, 'base64').toString('binary');`

When I take one of your unittests (tests/oidc-token-helper.service.spec.ts, line 108): 

`it('returns payload if token is correct, encode is false', () => {
	const token =
'SGVsbG8gV29ybGQgMTIzIQ==.eyAidGV4dCIgOiAiSGVsbG8gV29ybGQgMTIzISJ9.SGVsbG8gV29ybGQgMTIzIQ==';
	const expected = JSON.parse(`{ "text" : "Hello World 123!"}`);
	const result = tokenHelperService.getPayloadFromToken(token, false);
	expect(expected).toEqual(result);
});`

and I replace the token with the following, (created @ jwt.io): 
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEw7PDqyJ9.wMn-1oLWnxKJolMGb7YKnlwjqusWf4xnnjABgFaDkI4`

as well as the expected result with 
`{
  "name": "John Dóë"
}`

the test will fail, as the payload result is not the same.

Is it something wrong on my end or an actual bug?

**Comment by profet23** [comment]
@maarten-vdb should be all set with version 7.0.3

**Comment by maarten-vdb** [comment]
That was very fast, thanks a lot!
