### ISSUE TITLE
[Question]: About validate_id_token_aud with array

### ISSUE THREAD

**Issue by JiaLiPassion** [damienbod/angular-auth-oidc-client#326]
I have a question, I use `angular-auth-oidc-client` with `ory/hydra`.
And in `client side`, I send a request to `hydra` with a  `client_id=demo`, and `hydra` issued a jwt token with `idToken.aud=["demo"]`, so it will break the `validate_id_token_aud` logic. Is this the correct behavior or a bug? Thanks!

**Comment by profet23** [comment]
Why do you think it will break the `validate_id_token_aud` logic?

The token must contain the client_id in its audience... which you state that it does.

**Comment by JiaLiPassion** [comment]
@profet23, the logic of `validate_id_token_aud` is 

```
  if (dataIdToken.aud instanceof Array) {
            const result = this.arrayHelperService.areEqual(dataIdToken.aud, aud);

            if (!result) {
                this.loggerService.logDebug('Validate_id_token_aud  array failed, dataIdToken.aud: ' + dataIdToken.aud + ' client_id:' + aud);
                return false;
            }

            return true;
        } else if (dataIdToken.aud !== aud) {
            this.loggerService.logDebug('Validate_id_token_aud failed, dataIdToken.aud: ' + dataIdToken.aud + ' client_id:' + aud);

            return false;
        }
```

if the `idtoken.aud` is array, it will require the `client_id` from `client side` also an array.
It doesn't check `contains`, it check the `equals`.

**Comment by profet23** [comment]
@JiaLiPassion nope.   `this.arrayHelperService.areEqual(dataIdToken.aud, aud)`  takes care of it.

There is actually already a unit test for this here:
```
it('string and array (same) return true', () => {
        const array1 = ['somestring1'];
        const string2 = 'somestring1';
        const result = equalityHelperService.areEqual(array1, string2);
        expect(result).toBe(true);
    });
```

**Comment by JiaLiPassion** [comment]
@profet23, thanks, my bad, I am using the old version... I will try to upgrade.
