### ISSUE TITLE
Should silent_renew be disabled by default?

### ISSUE THREAD

**Issue by profet23** [damienbod/angular-auth-oidc-client#329]
This would be a breaking change.

Silent renew is currently enabled by default. 

With the default options, if a user calls `getIsAuthorized()` the observable will wait 5 seconds before emitting. This is because silent_renew is enabled but not configured. So the observable will try to execute a silent_renew that will never work and eventually timeout at 5 seconds.

Maybe silent_renew should be disabled by default and we should force users to configure it properly and turn it on explicitly. 

To me, it doesn't make sense to have it enabled, but not configured correctly by default.

**Comment by Yanal-Yves** [comment]
I agree, having it enabled by default but not configured is confusing.
I believe this feature should be disabled by default.

**Comment by damienbod** [comment]
@profet23 Yes, I think this is  a good idea. I always have it explicitly configured anyway.
