### ISSUE TITLE
Setup and custom request parameters concurrency (renew url)

### ISSUE THREAD

**Issue by Booster2ooo** [damienbod/angular-auth-oidc-client#333]
Hello,

I stubble upon a problem in the setup flow when providing custom parameters and using a silent renew (using 7.0.3).

As I wanted to set a global custom parameter named "resource", I added a call to setCustomRequestParameters after setupModule:

```javascript
export class MyAppOrModule {

  constructor(
    private oidcSecurity: OidcSecurityService,
    private oidcConfig: OidcConfigService,
  ) {
    this.oidcConfig.onConfigurationLoaded.subscribe((loaded: boolean) => {
      if (loaded) {
        console.log('OIDC Module: Setting up');

        let openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
        let parameters: any = { resource: "ABCD" };
        openIDImplicitFlowConfiguration.silent_renew = true;
        openIDImplicitFlowConfiguration.stsServer = this.oidcConfig.clientConfiguration.stsServer;
        // ...
        openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 1200;
        const authWellKnownEndpoints = new AuthWellKnownEndpoints();
        authWellKnownEndpoints.setWellKnownEndpoints(this.oidcConfig.wellKnownEndpoints);
        this.oidcSecurity.setupModule(openIDImplicitFlowConfiguration, authWellKnownEndpoints);

        // Adding custom param
        const parameters: any = { resource: "ABCD" };
        this.oidcSecurity.setCustomRequestParameters(parameters);
        
        console.log('OICD Module: Setup called');
      }
    });
  }

}
```

When the user logs in, a call to createAuthorizeUrl is done which retrieves the custom parameters from storage and adds them to the authorize url query string. The user successfully authenticates. Until there, everything works as expected.

Now, the user closes the SPA tab (but the browser still have other tabs opened so it stays open). The user then reopens a new tab to the SPA.

The SPA loads, the oidc security service setupModule method is called. If a silent renew has been set to true, it will create a new authorize url with a promp param set to none. When the createAuthorizeUrl retrieves the oidcSecurityCommon.customRequestParams, they are empty because they haven't been set yet. Therefore, the token resulting from the silent renew is not valid on resource specified in the module configuration.

If I try to call setupModule after setting the custom parameters, the storage key for the custom parameters is not yet initialized. The key name will be the default "storage_custom_request_params_angularclient" instead of a key ending with the clientid specified in the configuration. When the setupModule is called, the storage key is initialized (with the clientid), invalidating the custom parameters previously set (using the default key).

Could you please consider investigating this issue ?

**Comment by profet23** [comment]
@Booster2ooo @damienbod 

The pull request referenced above has a proposed fix for this.  With the change, you would modify your code above to look like:

```Typescript
export class MyAppOrModule {

  constructor(
    private oidcSecurity: OidcSecurityService,
    private oidcConfig: OidcConfigService,
  ) {
    this.oidcConfig.onConfigurationLoaded.subscribe((loaded: boolean) => {
      if (loaded) {
        console.log('OIDC Module: Setting up');

        let openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
        let parameters: any = { resource: "ABCD" };
        openIDImplicitFlowConfiguration.silent_renew = true;
        openIDImplicitFlowConfiguration.stsServer = this.oidcConfig.clientConfiguration.stsServer;
        // ...
        openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 1200;
        const authWellKnownEndpoints = new AuthWellKnownEndpoints();
        authWellKnownEndpoints.setWellKnownEndpoints(this.oidcConfig.wellKnownEndpoints);


        this.oidcSecurity.onConfigurationChange.pipe(take(1)).subscribe(() => {
            // Adding custom param
            const parameters: any = { resource: "ABCD" };
            this.oidcSecurity.setCustomRequestParameters(parameters);
        });

        this.oidcSecurity.setupModule(openIDImplicitFlowConfiguration, authWellKnownEndpoints);
        
        console.log('OICD Module: Setup called');
      }
    });
  }

}
```

**Comment by profet23** [comment]
And for others, the workaround with the current version (8.0.0 and below) is to implement your own version of `OidcSecurityStorage` that doesn't rely on the client id or have the client id passed in some other way before `setupModule` is called.

**Comment by damienbod** [comment]
will be released in 8.0.1 soon

**Comment by profet23** [comment]
@Booster2ooo  the change should be available now. Was curious if it met your needs.

**Comment by Booster2ooo** [comment]
@damienbod @profet23 thanks, I'll try to update to 8.0.1 as soon as possible (this week I hope). I'll let you know.
