### ISSUE TITLE
logOff doesn't clear storage

### ISSUE THREAD

**Issue by JohnGalt1717** [damienbod/angular-auth-oidc-client#339]
currently the logoff() method isn't clearing storage so the tokens etc. are all still there.

Is there a method that will clear this?  Shouldn't the logOff() method clear these for you?

**Comment by profet23** [comment]
@JohnGalt1717 the `logOff()` method should be clearing storage. 

Are you by chance reacting to a change in the `getIsAuthorized()` observable and redirecting? Before the `logOff()` method returns?

**Comment by JohnGalt1717** [comment]
I do have a getIsAuthorized() subscription.

How do I know that it's executing the logoff and not do anything there?

**Comment by profet23** [comment]
@JohnGalt1717  You may want to unsubscribe from the `getIsAuthorized()` observable right before calling `logOff()`.

We could probably change the sequence of events in the `logOff()` routine to clear the local storage before emitting. But this workaround should work for you. 

Please try the workaround and let me know if your local storage clears (it should). If it does, then we know its just a change in sequence that is required and not something else.

**Comment by damienbod** [comment]
will be released in version 8.0.2

**Comment by JohnGalt1717** [comment]
@damienbod Thanks! I can confirm that the work around does work temporarily.
