### ISSUE TITLE
Upgrading from 4.0 to 8.0 version fails with 'is not a function'

### ISSUE THREAD

**Issue by tpatikirikorala** [damienbod/angular-auth-oidc-client#342]
I just tried upgrading from 4.0 to 8.0 version. Updated the code based following the new documentation. However, I ended up with this error. Any ideas?

onUserDataChanged: last = undefined, new = 
angular-auth-oidc-client.js:610 STS server: http://localhost:7101
core.js:1448 ERROR TypeError: Object(...) is not a function
    at SwitchMapSubscriber.eval [as project] (angular-auth-oidc-client.js:2394)
    at SwitchMapSubscriber._next (switchMap.js:91)
    at SwitchMapSubscriber.Subscriber.next (Subscriber.js:92)
    at FilterSubscriber._next (filter.js:90)
    at FilterSubscriber.Subscriber.next (Subscriber.js:92)
    at BehaviorSubject.Subject.next (Subject.js:55)
    at BehaviorSubject.next (BehaviorSubject.js:44)
    at SafeSubscriber.eval [as _next] (angular-auth-oidc-client.js:2388)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:239)
    at SafeSubscriber.next (Subscriber.js:186)

**package.json**
```
   "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@angularclass/hmr": "^2.1.2",
    "@angularclass/hmr-loader": "^3.0.2",
    "angular-auth-oidc-client": "^8.0.1",
     "rxjs": "^5.5.2",
```

    "tslint": "~5.11.0",
    "typescript": "2.6.2",

**Comment by profet23** [comment]
Could you turn on error and warning messages and give the console output?

**Comment by tpatikirikorala** [comment]
its already on     
implicitFlowCfg.log_console_warning_active = true;
implicitFlowCfg.log_console_debug_active = true;

**Comment by profet23** [comment]
I'm not really sure what's happening as your code has been transpiled to js and the line numbers no longer mean anything. 

My guess is that you are using an old version of rxjs.

**Comment by tpatikirikorala** [comment]
I have added     "rxjs": "^5.5.2" to my original post.

**Comment by profet23** [comment]
Yeah... you'll want to upgrade to 6.3.3 and will probably also need the rxjs-compat library

**Comment by profet23** [comment]
This library has a dependency on "rxjs": ">= 6.0.0",

**Comment by tpatikirikorala** [comment]
thanks, Ill try to update and let you know.
