### ISSUE TITLE
Azure multi-tenant auth fails at issuer check

### ISSUE THREAD

**Issue by admanb** [damienbod/angular-auth-oidc-client#347]
I'm not sure if this is supposed to support AAD multi-tenant out of the box but just changing the configuration from https://login.microsoftonline.com/{tenantid}/v2.0/ to https://login.microsoftonline.com/common/v2.0/ successfully goes through the login process and gets the access token, but then fails on this validate check:

this.oidcSecurityValidation.validate_id_token_iss

is there a configuration setting I'm missing or is this scenario not supported without customization?

**Comment by damienbod** [comment]
As far as I know, multi tenant Azure AD sets the iss incorrectly here. We could deactivate this check per configuration, but this is turning off a security validation check, which is not good. 

Only solution would be to use a different OIDC server which sets this correctly as per spec, or we could turn the iss check off per configuration.

default 

iss_validation = true;

Then it would work.

**Comment by damienbod** [comment]
fix: https://github.com/damienbod/angular-auth-oidc-client/pull/349

**Comment by damienbod** [comment]
added in version 8.0.3
