### ISSUE TITLE
getUserData Observable emits nothing in version 6.0.12

### ISSUE THREAD

**Issue by DanielC2008** [damienbod/angular-auth-oidc-client#353]
In any version past 6.0.12 the getUserData() observable completes but logging its data results in nothing. 
Obviously this is problematic for not getting the user object however, since your code checks to make sure there is a user during the silentRenewHeartBeatCheck before proceeding with the silent renew, silent renews are no longer happening. Any ideas about why this may be happening? 6.0.11 and previous code works perfectly fine. Here is my configuration object. 

`
    const openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
    openIDImplicitFlowConfiguration.stsServer = `${env.ping.endpoint}`;
    openIDImplicitFlowConfiguration.redirect_url = `${env.rootUrl}`;
    openIDImplicitFlowConfiguration.client_id = `${env.ping.clientId}`;
    openIDImplicitFlowConfiguration.response_type = 'id_token token';
    openIDImplicitFlowConfiguration.scope = 'openid profile';
    openIDImplicitFlowConfiguration.post_logout_redirect_uri = `${env.rootUrl}`;
    openIDImplicitFlowConfiguration.start_checksession = false;
    openIDImplicitFlowConfiguration.silent_renew = true;
    openIDImplicitFlowConfiguration.silent_renew_url = `${env.rootUrl}/assets/refresh_redirect.html`;
    openIDImplicitFlowConfiguration.post_login_route = '/';

    // HTTP 403
    openIDImplicitFlowConfiguration.forbidden_route = '/Forbidden';
    // HTTP 401
    openIDImplicitFlowConfiguration.unauthorized_route = '/Unauthorized';
    openIDImplicitFlowConfiguration.auto_userinfo = false;
    openIDImplicitFlowConfiguration.log_console_warning_active = true;
    openIDImplicitFlowConfiguration.log_console_debug_active = false;
    // id_token C8: The iat Claim can be used to reject tokens that were issued too far away from the current time,
    // limiting the amount of time that nonces need to be stored to prevent attacks.The acceptable range is Client specific.
    openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 320;
`

**Comment by profet23** [comment]
Could you try changing:

`openIDImplicitFlowConfiguration.auto_userinfo = false;`

to:

`openIDImplicitFlowConfiguration.auto_userinfo = true;`

**Comment by DanielC2008** [comment]
ah great thank you. I believe I checked this boolean before I knew the user observable was emitting nothing and ruled it out as a possibility. Appreciate your quick response.

**Comment by DanielC2008** [comment]
@profet23 
This actually led me to another issue, which may or may not be something you can help me with. 

When I turn the `openIDImplicitFlowConfiguration.auto_userinfo = true` it makes a call to the authWellKnownEndpoints.userinfo_endpoint on our ping service. This endpoint is not actually used by ping and gets blocked due to a CORS error that our ping team cannot seem to alleviate (cannot tell you why).

When I tried removing the userinfo_endpoint from the configuration there was an error from your service that said...
`init check session: authWellKnownEndpoints.userinfo_endpoint is undefined; set auto_userinfo = false in config`

Regardless, the user info is indeed set in the getUserData observable so is it necessary for this userinfo_endpoint to be called?

**Comment by profet23** [comment]
@DanielC2008 

According to ping:  https://www.pingidentity.com/content/developer/en/resources/openid-connect-developers-guide.html

Step 3 is "Retrieve profile information from the UserInfo endpoint"  So it most definitely is used by ping. Sounds to me like you need get with your ping team and resolve your CORS issue. It shouldn't be very difficult.

https://documentation.pingidentity.com/pingfederate/pf90/index.shtml#adminGuide/pf_c_corsSupportForOAuthEndpoints.html

**Comment by DanielC2008** [comment]
@profet23 thats what I thought you may say! thanks again for your help!
