### ISSUE TITLE
Support for asynchonous storage interface

### ISSUE THREAD

**Issue by codemasterover9000** [damienbod/angular-auth-oidc-client#354]
Hi,

I am using ngrx store in my project and would like to store the auth information in the ngrx store. I'm not sure how I would implement this using OidcSecurityStorage. 

Any ideas on how to implement this?

Thanks

**Comment by profet23** [comment]
I'm not familiar with ngrx store... but just implement the OidcSecurityStorage abstract class with whatever backing mechanism you need. 

There are only 2 methods. `read` and `write`  

What are you having issues with?

**Comment by profet23** [comment]
Looking at https://github.com/ngrx/store  I think this is way way way way way overkill for this application. 

Do you have a reason for its usecase?

**Comment by profet23** [comment]
Refactoring the underlying storage API to be async would be a major refactor and it would probably lead to breaking changes in the current API as we would need to change over the value returns to be either async returns or observable returns. 

It's certainly possible, I'm just afraid that we would break a lot of people's code. 

It would basically involve creating a new abstraction layer like OidcSecurityStorageAsync or some such... and having that have async methods. The default implementation would probably just call the standard OidcSecurityStrage class (or a user provided implementation of it) synchronously. 

But again, changing the return values or method signatures would break a lot of code.

**Comment by robisim74** [comment]
@codemasterover9000 

The storage of this library (used to store the user info in the local storage) and ngrx store are two different things. The way in which the state of ngrx is implemented does not depend on this library: personally I have also implemented it with firebase authentication, custom authentication and so on.

So, once authentication and user data are obtained, you need to dispatch your action to update your state, something like this:

```
        this.oidcSecurityService.getUserData().subscribe(
            (userData: any) => {
                this.store.dispatch({
                    type: AuthActionTypes.SigninSuccess,
                    payload: userData
                });
            });
```
I think you should follow the exmples in the official repo: https://ngrx.io/

**Comment by codemasterover9000** [comment]
Thanks for the reply. I implemented it that way indeed.
