### ISSUE TITLE
Token refresh error, is silent_renew.html configuration ?

### ISSUE THREAD

**Issue by nizarkhsib** [damienbod/angular-auth-oidc-client#356]
Hello,
I have an issue with refreshing tokens.
After logging in succesfully, the tokens works fine till the end of IdTokenExpiration duration (which I configured in identity.xml to be 60seconds).
When the duration of 60 seconds passes, I get an error in my console saying that the token has expired.
This forces me to reload the url then I get redirected to the login page, else I stay navigating between my dashboard pages without having beeing able to get anything because my token has expired.

My configuration is as follows : 
```
  start_checksession: true,
  silent_renew: true,
  silent_renew_url: '/silent-renew.html',
```
What I would like to know is, where should I place the silent-renew.html file ?

I would appreciate your help

**Comment by profet23** [comment]
I've always specified the full url (including protocol and hostname) for the silent_renew_url.  Your silent-renew.html file should be  reachable at that location.

**Comment by nizarkhsib** [comment]
Thank for your response.
I placed the silent_renew in the same directory where I have my config.ts file.
Should it work if I place the file locally in the angular app ?

**Comment by profet23** [comment]
if your browser can reach it.

**Comment by jdelafon** [comment]
If you place it in `/src/assets` it should work fine.
