### ISSUE TITLE
Clear tokens without triggering a redirection/logout

### ISSUE THREAD

**Issue by tpatikirikorala** [damienbod/angular-auth-oidc-client#358]
Where can I find tokens (identity and access) and how can I clear them without triggering a redirection.
I want to clear tokens and redirect the user to the identity server change password page. Upon password change redirection to the angular client should in turn redirect the user to the Login page.
Can I achieve this without logout? 
Question is related to the following item [#289](https://github.com/damienbod/angular-auth-oidc-client/issues/289).

**Comment by RyanYizhaoHuang** [comment]
I want to do a silent login out(without redirect).
I have tried this approach. Clear the session only clear the data. The status for login is still true. If the use come back the same page. Login page will show up and the data (token) will be saved again.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
