### ISSUE TITLE
Question: Implicit flow without popup

### ISSUE THREAD

**Issue by vella-nicholas** [damienbod/angular-auth-oidc-client#359]
Is it possible to use Implicit flow and redirect the user to the login screen instead of a popup? I do not need to use iFrames, correct?

**Comment by profet23** [comment]
Yep, that's the default functionality.

**Comment by nvella88** [comment]
Thank you, is there a way to avoid redirection too? Can I put Identity Server behind a reverse proxy? I do not want the user to "feel/see" the URL of the website he/she is visiting to change.

**Comment by profet23** [comment]
That would be a security issue.

**Comment by nvella88** [comment]
Why is that so, please?
