### ISSUE TITLE
Session management implementation

### ISSUE THREAD

**Issue by gitsudouser** [damienbod/angular-auth-oidc-client#360]
Hello. I am implementing session management as described in article:
https://damienbod.com/2017/06/11/openid-connect-session-management-an-angular-application-using-identityserver4/

My goal is to show a warning, if user is working in multiple tabs, so if he logs out on one tab, he gets warning dialogs in all other tabs. Article clearly shows how to implement this behaviour and its working.

But i need to implement additional behaviour:
if user logs in in any other tab, i shoud hide warning dialogs and let user to continue work.  Problem is, that 
	this.oidcSecurityService.onCheckSessionChanged.subscribe((stateChanged) => {
		console.log('is auth state changed:' + stateChanged);
	});
fires only when state is "logged out". Is there any public event i can subscribe to, to know that user is logged in, or how can i implement such behaviour? 

Thank you.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
