### ISSUE TITLE
Silent Renew bug with the 4.1.0 version, do I have to install a new version ?

### ISSUE THREAD

**Issue by nizarkhsib** [damienbod/angular-auth-oidc-client#361]
Hello !

I am actually using the version 4.1.0 of oidc with Angular 5 version.

I have a problem with refreshing my token and I always get this error when the start renew is launched.

**Invalid request. redirect_uri not found in request as parameter. It is mandatory because of there is regex pattern for callback url in service provider configuration.** 

In the releases I saw that the silent_renew bug was fixed since the version 6.0.1.

So I am asking if I should use a higher version ? 

Thanks

**Comment by mustafakachwala** [comment]
Hi @nizarkhsib, i am facing a similar issue on version 9.0.1. Could you let me know how can this be fixed?
