### ISSUE TITLE
Load denied by X-Frame-Options: https:/localhost:9444/authenticationendpoint/oauth2_error.do?oauthErrorCode=invalid_callback&oauthErrorMsg=Registered+callback+does+not+match+with+the+provided+url. does not permit framing.

### ISSUE THREAD

**Issue by nizarkhsib** [damienbod/angular-auth-oidc-client#362]
Hello,
I actually can't refresh my tokens and I get the following error.

I tried to activate X-Frame-Options to accept iframes by adding the following config in my jaggery.conf file as stated in the wso2 documentation : 

I tried to configure my jaggery.conf file as stated in the documentation to allow framing as follows :

```
"filters":[
      {
        "name":"HttpHeaderSecurityFilter",
        "class":"org.apache.catalina.filters.HttpHeaderSecurityFilter",
        "params" : [
            {"name" : "hstsEnabled", "value" : "false"},
                        { "name": "antiClickJackingOption", "value": "SAMEORIGIN" }
             ]
      },
      {
        "name": "ContentTypeBasedCachePreventionFilter",
        "class": "org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter",
        "params":[
          {"name": "patterns", "value": "text/html\" ,application/json\" ,plain/text"},
          {"name": "filterAction", "value": "enforce"},
          {"name": "httpHeaders", "value": "Cache-Control: no-store, no-cache, must-revalidate, private"}
        ]
      }
    ],
```
But after my token expires and the silent renew starts, I get the following message.

`Load denied by X-Frame-Options: https:/localhost:9444/authenticationendpoint/oauth2_error.do?oauthErrorCode=invalid_callback&oauthErrorMsg=Registered+callback+does+not+match+with+the+provided+url. does not permit framing.`

Help, please !

**Comment by damienbod** [comment]
The URL https:/localhost:9444  is blocked by your server. You need to activate this. Check the config again, and also the headers in the HTTP responses. The iframe could be blocked by the HTTP Header. Turn this off, if it is and add the CSP which only allows the explicit URLs from your software. But make sure the iframe will only work for your URLs, not any URL.
