### ISSUE TITLE
How can I prevent destructive auto-authorization on application startup?

### ISSUE THREAD

**Issue by glazkovalex** [damienbod/angular-auth-oidc-client#364]
My app uses ["angular-auth-oidc-client"](https://github.com/damienbod/angular-auth-oidc-client) in mode ["silent_run": true](https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#silent_renew).
My app starts with different routes and always with query parameters. Most of the resources in my application do not require authorization on the server. If I needed authorization, I ran it through [this.oidcSecurityService.authorize()](https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#authorize), but pre-save the current route and query parameters to restore it in the [onAuthorizationResult event](https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#onauthorizationresult-observable). On [version 6.0.2](https://github.com/damienbod/angular-auth-oidc-client/blob/master/CHANGELOG.md#2018-10-07-version-6012), this worked, but from [version 6.0.12](https://github.com/damienbod/angular-auth-oidc-client/blob/master/CHANGELOG.md#2018-10-07-version-6012) ("check for valid tokens on start up") and now on version 9.0.0, when the application starts, the authorization process that is not needed in most cases is automatically started, followed by a redirect to ["post_login_route"](https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#post_login_route), respectively, with the loss of the route and the request parameters with which the application was launched.

How can I prevent destructive auto-authorization on application startup?

**Comment by naaambo** [comment]
Just to note: I am also experiencing this issue. Looks like the silent renew iframe is getting loaded immediately and therefore its onload function gets called causing authorisation logic to be executed.

**Comment by glazkovalex** [comment]
Version 9.0.1 added "history_cleanup_off" parameter which solves this problem, if you set it to "true".
