### ISSUE TITLE
authorizedCallback doesn't exists anymore

### ISSUE THREAD

**Issue by Booster2ooo** [damienbod/angular-auth-oidc-client#365]
Hello,

I updated to v9.0.0 and noticied authorizedCallback doesn't exist anymore even if the documentation for implicit flow still mentions it (https://github.com/damienbod/angular-auth-oidc-client/#implicit-flow).

Is there an alternative ? I only saw authorizedCallbackProcedure in the source code but it's private and have a different function signature.

Best regards

**Comment by damienbod** [comment]
Hi @Booster2ooo This has been renamed to authorizedImplicitFlowCallback()

This breaking change was made because the OIDC Code Flow with PKCE is also supported now. Each have a different callback

**Comment by damienbod** [comment]
@Booster2ooo Thanks for the feedback, corrected the readme

**Comment by Joseph7695** [comment]
authorizedImplicitFlowCallback() does not exist too now ?
