### ISSUE TITLE
silent renew removes query params

### ISSUE THREAD

**Issue by csourcenl** [damienbod/angular-auth-oidc-client#366]
When a silent renew takes place the following code removes all query params:
window.history.replaceState({}, window.document.title, window.location.origin + window.location.pathname);

This code is situated inside the authorizedCallbackProcedure function.

The reason for this line is to remove the tokens from the url. But for silent renew this is not relevant. Might it be possible to make it conditional when it is not a renew process (isRenewProcess).

**Comment by damienbod** [comment]
@csourcenl yes, I could make this optional.  I could add a configuration to turn it on or off. 

default = on.

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/pull/369

review?
