### ISSUE TITLE
getUserData is not very secure

### ISSUE THREAD

**Issue by teebszet** [damienbod/angular-auth-oidc-client#368]
I noticed that the getUserData() method directly retrieves the field from the userData object stored in session storage by default, where it can be easily manipulated.

```
{
  "sub":"00u70b6",
  "iss":"https://okta.com/oauth2/aus66",
  "aud":"0oa65bd356",
  "iat":1547883,
  "exp":1547191483,
  "jti":"ID.EXFrCE4ZCutF0o8ln5L09aVHzzAytZYNlvo0zg4rnB8",
  "customClaim": "false",
  ...
}
```

For example, in the above example, a user could edit their session storage to set "customClaim" to true, and subsequent calls to getUserData() would show "customClaim": true.

Is there any config to not persist userData in the session storage, without having to write a custom storage class?

Note, that it seems even storing the encoded JWT in session storage is not recommended by some, https://auth0.com/docs/security/store-tokens

**Comment by damienbod** [comment]
When using APIs from different domains with SPAs, you require tokens in the client application. You need to keep these somewhere for later use. Storing them in the session storage is the best of the possible solutions. Storing in memory will not work, if you refresh your app. You could also implement your own custom storage and keep the tokens where ever you what.

If you what stop managing token in the browser, the switch to a server rendered application which uses cookies with same site protection. All API calls are then done on the server.

Greetings Damien

https://damienbod.com/2019/01/20/is-a-spa-less-secure-than-a-server-rendered-web-application/

https://leastprivilege.com/2019/01/18/an-alternative-way-to-secure-spas-with-asp-net-core-openid-connect-oauth-2-0-and-proxykit/

https://brockallen.com/2019/01/03/the-state-of-the-implicit-flow-in-oauth2/

https://www.scottbrady91.com/OAuth/Cheat-Sheet-OAuth-for-Browser-Based-Applications
