### ISSUE TITLE
How we can implement Resource Owner Password Flow using angular-auth-oidc-client?

### ISSUE THREAD

**Issue by Asifislam110** [damienbod/angular-auth-oidc-client#370]
Hi,

I want to implement Resource Owner Password Flow in angular application.
I read this article, 
https://github.com/manfredsteyer/angular-oauth2-oidc/blob/master/docs-src/password-flow.md

but i don't know how i can implement using angular-auth-oidc-client.

**Comment by Asifislam110** [comment]
Hi,

I want to implement R

**Comment by damienbod** [comment]
@Asifislam110 This is not recommended, and so not supported in this lib

Greetings Damien
