### ISSUE TITLE
Why do you enforce the presence of a session state in authorizedCallbackWithCode ?

### ISSUE THREAD

**Issue by jonathanantoine** [damienbod/angular-auth-oidc-client#371]
Hello,

I am wondering why you enforce the presence of a session_state in the authorizedCallbackWithCode function ?

Thank you.

**Comment by jonathanantoine** [comment]
yes in this one you pointed but there is a check in authorizedCallbackWithCode.

**Comment by damienbod** [comment]
Ah ok, this is just a helper method, but yes, if it does not exist, I should add a check for this. I'll clean this up

Greetings Damien

**Comment by jonathanantoine** [comment]
Thank you :) I asked this because I lost an hour today understanding why it was not working in my sample :)

**Comment by damienbod** [comment]
released
