### ISSUE TITLE
Why is there an implicit dependency on the RouterModule?

### ISSUE THREAD

**Issue by woppa684** [damienbod/angular-auth-oidc-client#373]
I'm creating a large framework application that dynamicaly loads other apps that can each have their own Router (forRoot!), therefore the framework itself cannot use the Router (which is what we want anyway). the framework is, however, responsible for doing the authentication and authorization for all the sub-applications (they can use a framework API that we provide to retrieve privileges and user details). 

When I now follow the "Using in Angular app" part of the README, I get the error below. It seems weird to me that HttpClientModule is listed as a required import but RouterModule isn't (and it apparently is required!)

```ts
main.ts:12 Error: StaticInjectorError(AppModule)[OidcSecurityService -> Router]: 
  StaticInjectorError(Platform: core)[OidcSecurityService -> Router]: 
    NullInjectorError: No provider for Router!
```

**Comment by damienbod** [comment]
The service uses the angular router to redirect after a successful login, if configured this way.

I will add this to the docs, thanks for pointing this out.

Greetings Damien

**Comment by damienbod** [comment]
This is added to the docs now @FabianGosebrink  correct?
