### ISSUE TITLE
authorize() process clears token which cause errors in other tabs

### ISSUE THREAD

**Issue by gitsudouser** [damienbod/angular-auth-oidc-client#375]
Hello. 
In situation, when user works in two tabs and oidcSecurityService configured to work with localStore error exists:
User logined in one tab and he working there, if user start working in second tab and authorize process started (for example, login page in IdentiyServer was opened and user started process of authorization), then token will be cleared for both tabs, and will be empty for some time. If user will work in first tab in that time (for example HttpClient request), no token will be avaliable.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
