### ISSUE TITLE
Issue verifying hash [RSA256] Code Flow optional

### ISSUE THREAD

**Issue by Davidmesm** [damienbod/angular-auth-oidc-client#376]
In **oidc-security-state-validation.service.ts**, in the function **validateState** in line 108 the attribute toReturn.decoded_id_token.at_hash is incorrect.  This will always return undifiened causing the verification to fail.  For more information please let me know.

**Comment by damienbod** [comment]
I need some more info, but this happens if the tokens are incorrect, or you are using old tokens

**Comment by damienbod** [comment]
@Davidmesm What token service are you using, maybe the token service is created this at_hash value incorrectly. If you sent a token I could validate this. Or see the OpenID connect specification for this, to see if the at_hash is being created correctly.

**Comment by damienbod** [comment]
@Davidmesm You are correct, this is optional, but I think it's a bad idea not to do this. The access token should be validated in this way.  I think pingFederate should update this.

BUT, in the specs it is optional for the code flow, so I will also make it optional for the code flow. I will make a fix for this and create a new npm as soon as possible

Thanks for reporting.

Greetings Damien

**Comment by damienbod** [comment]
will be released in version 9.0.2, hopefully Friday

**Comment by damienbod** [comment]
released, thanks for reporting
