### ISSUE TITLE
load_using_stsServer throws error

### ISSUE THREAD

**Issue by dapalmi** [damienbod/angular-auth-oidc-client#377]
angular version 7.2.0
angular-auth-oidc-client version 9.0.1

I get following error when calling the load_usings_stsServer when initializing the app:

> message: "Http failure response for http://localhost:5105/.well-known/openid-configuration: 0 Unknown Error"
name: "HttpErrorResponse"
ok: false
status: 0
statusText: "Unknown Error"
url: "http://localhost:5105/.well-known/openid-configuration"

Even though when looking at the http request in chrome it says http code 200 and also the log on my authorization server says everything is alright.

Here is how I implimented it in the app module:

`export function loadConfig(oidcConfigService: OidcConfigService) {
  console.log('APP_INITIALIZER STARTING');
  return () => oidcConfigService.load_using_stsServer(`${environment.stsServerUrl}`);
}
...
...
providers: [
    OidcSecurityService,
    OidcConfigService,
    {
        provide: APP_INITIALIZER,
        useFactory: loadConfig,
        deps: [OidcConfigService],
        multi: true,
    },
...
...
`

**Comment by damienbod** [comment]
@dapalmi This usually means that the URL cannot be requested. Check this it works in the browser and if it does, then check that CORS is allowed for the angular application. Also, you should be using HTTPS

Greetings Damien

**Comment by dapalmi** [comment]
Thanks for your prompt response. It was a CORS issue.
