### ISSUE TITLE
Refresh token iframe causes errors when application is running in iframe. 

### ISSUE THREAD

**Issue by bielu000** [damienbod/angular-auth-oidc-client#379]
I have 2 applications.

App_1 - application is an angular app, it uses angular-auth-oidc-client. 
App_2 - second application, not in angular.

App_2 has iframe where App_1 is loaded.
It works, but if I enable refreshing tokens in App_1, it causes error:

> Blocked a frame with origin "domain_app_2" from accessing a cross-origin frame.

and it brokes my app.

I think that the problem is in: existing-iframe.service.ts
When any other componen would to get iframe, in the first step, existing-iframe.service is trying to get iframe from parent, which cause "cross-origin frame" error. 

Is it desirable behaviour?

**Comment by damienbod** [comment]
yep, this has nothing to do with the lib. This is the CORS protection from you host. you need to configure this, if required. Also add a CSP, and the iframe headers to the host servers.
