### ISSUE TITLE
Silent-renew logs are confusing

### ISSUE THREAD

**Issue by jdelafon** [damienbod/angular-auth-oidc-client#380]
Logs say something very contradictory: `"silent-renew-running"`, then a heartbeat that checks if it needs to renew, but is aware that `silentRenewRunning: false`.

![silent-renew-1](https://user-images.githubusercontent.com/12040845/52048968-e61e5300-254c-11e9-8c43-93596275233f.png)

How should I interpret that ? 

When I reload the page, the same heartbeat runs, but with `silentRenewRunning: true`.

Thanks

**Comment by damienbod** [comment]
The logs show the check which starts a silent renew. If the token is expired, the silent renew will start.
