### ISSUE TITLE
Warning: error: "interaction_required"

### ISSUE THREAD

**Issue by jdelafon** [damienbod/angular-auth-oidc-client#381]
Hello again, 
what should one do in this case? All seems to work fine except for this warning that has an error inside.

![silent-renew-interaction-required](https://user-images.githubusercontent.com/12040845/52049770-e4ee2580-254e-11e9-8522-fa87fde7cd10.png)

Thanks

**Comment by damienbod** [comment]
This happens when you have tokens from a previous login, but are no longer logged in, or the STS was cleaned up. It is required that the user, app logs in again.

Greetings Damien

**Comment by WoMayr** [comment]
Is it possible to react to an error?
If i understood the code correctly only an error with value `login_required` gets special treatment and a non generic authorizationResult gets emitted.

**Comment by mcarefully** [comment]
I have the same question as the above, what's the recommended way to observe or handle for this error condition so that the app can properly bounce or otherwise prompt/inform the user when it detects this state?
