### ISSUE TITLE
OpenIDImplicitFlowConfiguration naming

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#382]
Hey guys,

Great work for this lib, and maybe this is my OCD talking, but I'm I the only one who thinks that this class OpenIDImplicitFlowConfiguration should have a different name, ex: OpenIDFlowConfiguration to avoid confusing any new users?
I understand te backward compatibility issues and may be this class should be marked as deperctaed and extend the new one with exactly the same fields...

Thanks in advance

**Comment by damienbod** [comment]
Yes this would make sense, pity I missed this, this would be a breaking change.

I will do this with the next breaking change issue.
