### ISSUE TITLE
Silent renew triggered infinitely

### ISSUE THREAD

**Issue by ygeelen-tb** [damienbod/angular-auth-oidc-client#383]
Hello,

After upgrading from version 6.0.1 to version 9.0.1, everytime I follow a link or refresh the page the silent renewal process is triggered, I am routed to the post_login_route, I am routed back to the page I requested and then everything repeats. This goes on indefinitely...

This behavior seems to come from a call to getIsAuthorized? But when authorized = true, I don't expect the silent renewal to run.

As soon as I disable silent renewal, I no longer have this issue.
Were' on Angular 6 and rxjs 6.3.3

`import { Component, OnInit, OnDestroy } from '@angular/core';
import { OidcSecurityService, AuthorizationResult, AuthorizationState } from 'angular-auth-oidc-client';
import { Router } from '@angular/router';
import { PersonService } from './person/person.service';
import { ToastrService } from 'ngx-toastr';
import { AuthenticationService } from './core/services/authentication.service';
import { filter, take } from 'rxjs/operators';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
    title = 'TrustO - Trusted Mail+';
    oidcModuleSetupSubscription: Subscription;
    authorizationResultSubscription: Subscription;
    isAuthorizedSubscription: Subscription;

    constructor(
        public oidcSecurityService: OidcSecurityService,
        private router: Router,
        private personService: PersonService,
        private toastrService: ToastrService,
        private authenticationService: AuthenticationService
    ){
        this.oidcModuleSetupSubscription = this.oidcSecurityService.getIsModuleSetup().pipe(
            filter((isModuleSetup: boolean) => isModuleSetup),
            take(1)
        ).subscribe((isModuleSetup: boolean) => {
            this.onOidcModuleSetup();
        });
        
        this.authorizationResultSubscription = this.oidcSecurityService.onAuthorizationResult.subscribe(
            (authorizationResult: AuthorizationResult) => {
                this.onAuthorizationResultComplete(authorizationResult);
        });
    }

    ngOnInit() {
        
    }

    ngOnDestroy(): void {
        this.oidcModuleSetupSubscription.unsubscribe();
        this.authorizationResultSubscription.unsubscribe();
        this.isAuthorizedSubscription.unsubscribe();
    }

    private onOidcModuleSetup() {
        if (window.location.hash) {
            window.location.hash = decodeURIComponent(window.location.hash);
            this.oidcSecurityService.authorizedImplicitFlowCallback();
        } else {
            if (window.location.pathname !== '/autologin' && window.location.pathname !== '/postlogin') {
                this.authenticationService.setRedirectUrl(window.location.pathname);
            }
            this.isAuthorizedSubscription = this.oidcSecurityService.getIsAuthorized().subscribe((isAuthorized: boolean) => {
                if (!isAuthorized && window.location.pathname === '/postlogin') {
                    this.router.navigate(['/autologin']);
                }
            });
        }
    }

    private onAuthorizationResultComplete(authorizationResult: AuthorizationResult) {
        if (authorizationResult.authorizationState === AuthorizationState.authorized) {
            let subject: string = this.oidcSecurityService.getPayloadFromIdToken(false).sub;

            this.personService.login(subject).subscribe(response => {
                this.router.navigate(["/postlogin/" + response.model]);
              }, error => {
                this.toastrService.error(error.message);
              });
        } else {
            this.router.navigate(['/unauthorized']);
        }
    }
}
`

AppModule:

`export function loadConfig(oidcConfigService: OidcConfigService, appConfig: AppConfig, logger: NGXLogger) {
  return () => new Promise<void>(
    function (resolve, reject) {
      appConfig.loadUrlConfig();
      var appLoad = appConfig.loadAppConfig();
      appLoad.then((configSettings) => {
        logger.updateConfig(
          {
            level: +configSettings.clientLogLevel,
            serverLogLevel: +configSettings.serverLogLevel,
            serverLoggingUrl: `${configSettings.webApiUrl}/log`
          });
        
        oidcConfigService.load(`${configSettings.identityServerUrl}/api/ClientAppSettings`);
        resolve();
      })
    });
}`

`import { CanActivate, Router, ActivatedRouteSnapshot, RouterStateSnapshot } from "@angular/router";
import { OidcSecurityService } from "angular-auth-oidc-client";
import { Injectable } from "@angular/core";
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AuthenticationService } from "../services/authentication.service";

@Injectable()
export class AuthorizationGuard implements CanActivate {

  constructor(private router: Router, private oidcSecurityService: OidcSecurityService, private authenticationService: AuthenticationService) { }

  canActivate(next: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean {
    if (next.params['guid']) {
      sessionStorage.setItem('guid', next.params['guid']);
    }
    
    return this.oidcSecurityService.getIsAuthorized().pipe(
      map((isAuthorized: boolean) => {
        if (isAuthorized) {
          return true;
        }
        this.authenticationService.setRedirectUrl(state.url);
        if (!window.location.hash) {
          this.router.navigate(['/autologin']);
        }
        return false;
      })
    );
  }
}`

`import { Component, OnInit, OnDestroy } from '@angular/core';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { Subscription } from 'rxjs';

@Component({
    selector: 'app-auto-component',
    templateUrl: './auto-login.component.html'
})

export class AutoLoginComponent implements OnInit, OnDestroy {
    lang: any;
    oidcModuleSetupSubscription: Subscription;

    constructor(public oidcSecurityService: OidcSecurityService
    ) {
        this.oidcModuleSetupSubscription = this.oidcSecurityService.onModuleSetup.subscribe(() => { this.onModuleSetup(); });
    }

    ngOnInit() {
        // See also https://github.com/damienbod/angular-auth-oidc-sample-google-openid/tree/master/src/AngularClient
        if (this.oidcSecurityService.moduleSetup) {
            this.onModuleSetup();
        }
    }

    ngOnDestroy(): void {
        this.oidcModuleSetupSubscription.unsubscribe();
    }

    private onModuleSetup() {
        this.oidcSecurityService.authorize();
    }
}`

Best regards,
Yannick.

**Comment by ygeelen-tb** [comment]
For clarification: the redirect loop happens on page load/redirect and not on angular route navigate.

**Comment by damienbod** [comment]
closing this, please re-open is required

**Comment by ygeelen-tb** [comment]
@damienbod I eventually disabled the Silent Renew feature... so not really solved.

**Comment by bmadhan90** [comment]
> @damienbod I eventually disabled the Silent Renew feature... so not really solved.

@ygeelen-tb solved this issue?? i am also getting the same issue.

**Comment by damienbod** [comment]
@ygeelen-tb @bmadhan90 I have some working examples with this type of setup, or at least I think it's the same. I will try to reproduce this, to see what's going on, and what is the difference to the examples. I was focusing on the version 10 which has breaking changes with the configuration. I wanted to get this configuration change completed first. I will now try to improve this part on the lib.

Greetings Damien

**Comment by ygeelen-tb** [comment]
> > @damienbod I eventually disabled the Silent Renew feature... so not really solved.
> 
> @ygeelen-tb solved this issue?? i am also getting the same issue.

Nope, I still have the feature set to disabled. Let's see what the results of Damien's test will be.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue

**Comment by ygeelen-tb** [comment]
@damienbod will silent renew work when we upgrade to angular-auth-oidc-client v10.0.10 ?

**Comment by damienbod** [comment]
It should, I use this all the time.

Greetings Damien
