### ISSUE TITLE
Authorization flow required at_hash

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#384]
Hi,

It seems like your lib fails to validated my token simce I don't include the at_hash field which is optional, it should fallback to signature verification. Would you mind me fixing it?

**Comment by damienbod** [comment]
@yelhouti  Thius is fixed in version 9.0.2

https://github.com/damienbod/angular-auth-oidc-client/issues/376

Greetings Damien

**Comment by yelhouti** [comment]
@damienbod Thanks :), do you check the access token in that case using signature?

**Comment by yelhouti** [comment]
Hahah To bad I tested yesterday XD

**Comment by damienbod** [comment]
@yelhouti no, because the access token does not need to be a jwt token.

**Comment by yelhouti** [comment]
well any way, checking of the front-end only improved the UX, and I don't care about the UX of people hacking around, so checking the id_token in the front is also not that necessary.
