### ISSUE TITLE
"getIsAuthorized" function never returns true in MS Edge

### ISSUE THREAD

**Issue by ygeelen-tb** [damienbod/angular-auth-oidc-client#385]
This issue was supposedly fixed since version 7.0.2+ (see #240 !).
But in the latest version 9.0.1 this seems to be occurring again?
This is causing an infinite redirect loop between our postlogin component and our autologin component... which is very hard to debug because the console/network log output can't be viewed.
For code samples of our project, please see my previous issue #383 

The strange thing is that it's no issue on localhost, but only on servers (Angular production build).

@damienbod do you have any insights on a workaround or fix? Perhaps downgrade to an older version?

**Comment by damienbod** [comment]
Is this still an issue?, closing this, please re-open is required

**Comment by ygeelen-tb** [comment]
@damienbod I think I fixed it by mixing code snippets from 2 github sample repositories: https://github.com/damienbod/angular-auth-oidc-client and https://github.com/damienbod/AspNetCoreAngularSignalRSecurity
But it's been too long to remember..

**Comment by damienbod** [comment]
@ygeelen-tb form me too, sorry I could not handle this issue properly, have a bit of a time problem lately for OSS

Greetings Damien

**Comment by ygeelen-tb** [comment]
Ok no worries, great library by the way
