### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by evoronovich** [damienbod/angular-auth-oidc-client#386]
Hi! I have the such question: 
I have auth-guard, which is checking isAuthorized();
If no authorized, I save redirect_url in local storage, it's redirecting user to login page, user login, in the IDS we have redirect url to the '/callback'.
In the AppRouting I have such entry: {path: '', redirectTo: 'dashboard', pathMatch: 'full'},
The question how app-routing and oidc client should be configured to redirect user to the page, that he has requested before?
Ex. User enters http://localhost/jobs, unauthorized, login, redirecting to the dashboard (but I need redirect to jobs).
There are some info in documentation about it, but it's not clear for me. Could you help?

**Comment by damienbod** [comment]
@evoronovich I have docs for this in the API documentation

**Comment by codemasterover9000** [comment]
Where is his documented exactly? The authorize() function seems to use the static url from this.authConfiguration.redirect_url. The only thing I could think of is to pass an urlHandler to authorize() and rewrite the url but that seems hacky.

**Comment by damienbod** [comment]
I will add a code exmample for this. This describes the event which can be used. 

https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#onauthorizationresult-observable

You should not use the guard on the default route. You need to save your path somewhere in localstorage or sessionstorage before the authorize request, and use this after in the event.

**Comment by codemasterover9000** [comment]
Thanks!

**Comment by HedayatTajik** [comment]
Hello, @damienbod,
I cannot find any example for this. the url that you sent does not exist now.
can you send it again. :)
Thank you.

**Comment by damienbod** [comment]
The docs were moved, didn't update this issue:

https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api

**Comment by HedayatTajik** [comment]
Thank you

________________________________
Von: damienbod ***@***.***>
Gesendet: Donnerstag, 15. Juli 2021 10:54
An: damienbod/angular-auth-oidc-client ***@***.***>
Cc: Hedayat Tajik ***@***.***>; Comment ***@***.***>
Betreff: Re: [damienbod/angular-auth-oidc-client] Redirect after login (#386)


The docs were moved, didn't update this issue:

https://nice-hill-002425310.azurestaticapps.net/docs/documentation/public-api

**Comment by marculescu** [comment]
I'm having a similar problem. I'm using angular-auth-oidc-client 15.0.3.

```
export class AuthGuard implements CanActivate {
  constructor(private oidcSecurityService: OidcSecurityService) { }

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    return this.oidcSecurityService.checkAuth()
      .pipe(map((response) => {
        if (response?.isAuthenticated) return true;
        
        const url = state.url;
        this.oidcSecurityService.authorize(null, {redirectUrl: url});
        return false;
      }));
  }
}
```
The authorization server is responding with 404 to the authorize request. The URL requested looks like this:
`https://authority/oauth/authorize?client_id=xxx&redirect_uri=%2Fmypage&response_type=code&scope=openid%20profile%20email&...

`If I hardcode the full url in the authorize call:
`this.oidcSecurityService.authorize(null, {redirectUrl: 'https://mydomain/root_app_path/mypage'});`

I get the following error from the authority:
_"The specified 'redirect_uri' parameter doesn't match the client redirection endpoint the authorization code was initially sent to."_

If I change the redirectUrl in the OpenIdConfiguration to hardcode my very page, then everything works:

```
export const OidcConfig: OpenIdConfiguration = {
    // ...
    redirectUrl: 'https://mydomain/root_app_path/mypage',
    // ...
};

```
Do you have any pointers please?

Thanks.

**Comment by FabianGosebrink** [comment]
Passing the redirect URI in the config is the recommended way because the IDP has to know all redirectUrls in prior, and he matches them. You have to implement the "when the IDP redirects to my app then I want to redirect to the route the user was before" by yourself or you can also try the "AutoLoginPartialRoutesGuard" from the lib.

**Comment by marculescu** [comment]
Thanks for the quick reply. I incorrectly assumed that providing the redirectUrl in authorize() will actually do what AutoLoginPartialRoutesGuard does for me.
For anyone else landing here, it's worth reading @FabianGosebrink's explanation [here](https://github.com/damienbod/angular-auth-oidc-client/issues/1549#issuecomment-1265020158).

**Comment by FabianGosebrink** [comment]
Thanks for linking the response. I should add this response to the docs :D Would have searched it as well. Thanks!
