### ISSUE TITLE
401: You have no rights to access this. Please Login

### ISSUE THREAD

**Issue by antonigiovanniello** [damienbod/angular-auth-oidc-client#387]
Hello,
trying to authenticate from Angular webApp
with WSO2 IS 5.6.0 setting OAuth / OpenID Connect Configuration
I get a lack of authentication with HttpError: 401: You have no rights to access this. Please Login

From the known console
at_hash from the server: undefined
at_hash client validation not decoded: _KdHCi3YUDg-3cenasfzKw
-gen access --_ KdHCi3YUDg-3cenasfzKw
authorizedCallback incorrect at_has
authorizedCallback, token (s) validation failed, resetting
userData getting data
getIsAuthorized: false

Has anyone had the same problem or solved it?

**Comment by damienbod** [comment]
authorizedCallback incorrect at_hash This happens when the at_hash is incorrect. In the Implicit Flow, this is required, In the code flow, this is optional. depending on your flow,m check that the at_hash is returned correctly.

Greetings Damien

**Comment by antonigiovanniello** [comment]
I have found that from WSO2 it is not correctly evaluated at_hash.

Thanks Antonio

**Comment by damienbod** [comment]
@antonigiovanniello Could you give me more information here please. 

What flow do you use?

What is the auth request (full url)?

What is the at_hash in the id_token repsonse?

What is not correctly evaluated?

Greetings Damien

**Comment by antonigiovanniello** [comment]
The bug depends on WSO2 Identity Server 5.6.0, does not correctly evaluate the at_hash field,
solved with version 5.7.0.

angular-auth-oidc-client.js:647 STS server: https://localhost:9443/oauth2/oidcdiscovery
angular-auth-oidc-client.js:647 IsAuthorizedRace: Silent Renew Not Active. Emitting.
angular-auth-oidc-client.js:647 IsAuthorizedRace: Completed
angular-auth-oidc-client.js:647 getIsAuthorized: false
angular-auth-oidc-client.js:647 BEGIN authorizedCallback, no auth data
home.component.ts:38 userData getting data
angular-auth-oidc-client.js:647 getIsAuthorized: false
angular-auth-oidc-client.js:647 {access_token: "e046acdc-6e48-311a-b6e5-9a22277cf50d", id_token: "eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0…YrwkFRijHuiyPU_bJM5GXLSmSEjIUJG9pLrQXClik8gOYWi9A", state: "15506789473230.5280966452301199", token_type: "Bearer", expires_in: "3600", …}
angular-auth-oidc-client.js:647 authorizedCallback created, begin token validation
angular-auth-oidc-client.js:647 jwks_uri: https://localhost:9443/oauth2/jwks
client:77 [WDS] Hot Module Replacement enabled.
angular-auth-oidc-client.js:647 validate_id_token_iat_max_offset: 2948 < 20000
angular-auth-oidc-client.js:647 Token not expired?: 1550682642000 > 1550679044953  (true)
angular-auth-oidc-client.js:647 at_hash from the server:undefined

**Comment by manojsati** [comment]
can any one provide sample configuration for a perticular version number of the component which works perfectly with angular6 calling webapi core 2.1, identity server4?

**Comment by damienbod** [comment]
@manojsati see the eample at the end of the readme
