### ISSUE TITLE
Redirect after login to OPENID USER CLAIMS

### ISSUE THREAD

**Issue by antonigiovanniello** [damienbod/angular-auth-oidc-client#388]
Hello,
I have performed the configuration on the identity.xml file as indicated below
https://docs.wso2.com/display/IS560/OpenID+Connect+Hybrid+Flow

for the purpose of authenticating from the Angular webApp
enhancing in app.module.ts
openIDImplicitFlowConfiguration.response_type = 'code id_token token';

But, what I get
it is a continuous redirect to the login page.

Is there anyone who has had the same anomaly?
Has anyone solved it?

**Comment by damienbod** [comment]
@antonigiovanniello Only the Code flow or the Implicit Flow are supported in this lib. You should use the Code Flow with PKCE  ie response_type = 'code'

Greetings Damien
