### ISSUE TITLE
getUserData() not sending user information and returns only {sub: "User Logged in"}

### ISSUE THREAD

**Issue by shivajikokate-shiro** [damienbod/angular-auth-oidc-client#391]
Hi All,

I am expecting the user information and user claims in this (**connect/userinfo**) call. But I only get the **{sub: "User Logged in"}** in oidcSecurityService.getUserData().

As after login success I want user information and user claims to handle the permissions. I don't know this information is sufficient or not to assume or understand my issue but adding my server side and client side setting.

**Server side client setting:**
`new Client
                {
                    ClientId = "angular",
                    ClientName = "Angular client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    // where to redirect to after login
                    RedirectUris = { "http://localhost:4200" },
                    // where to redirect after logout
                    PostLogoutRedirectUris = { "http://localhost:4200" },
                    AllowedScopes = new List<string>
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    },
                    AllowedCorsOrigins = new List<string> { "http://localhost:4200" },
                    AllowAccessTokensViaBrowser = true
                }`

**Client side setting:**
`const openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
        openIDImplicitFlowConfiguration.stsServer = 'http://localhost:5000';
        openIDImplicitFlowConfiguration.redirect_url = 'http://localhost:4200';
        openIDImplicitFlowConfiguration.client_id = 'angular';
        openIDImplicitFlowConfiguration.response_type = 'id_token token'; 
        openIDImplicitFlowConfiguration.scope = 'api1 openid';
        openIDImplicitFlowConfiguration.post_logout_redirect_uri = 'http://localhost:4200';
        openIDImplicitFlowConfiguration.start_checksession = false;
        openIDImplicitFlowConfiguration.silent_renew = false;
        openIDImplicitFlowConfiguration.silent_renew_url ='http://localhost:5000/silent-renew.html';
        openIDImplicitFlowConfiguration.post_login_route = '/';
        // HTTP 403
        openIDImplicitFlowConfiguration.forbidden_route = '/Forbidden';
        // HTTP 401
        openIDImplicitFlowConfiguration.unauthorized_route = '/Unauthorized';
        openIDImplicitFlowConfiguration.log_console_warning_active = false;
        openIDImplicitFlowConfiguration.log_console_debug_active = true;
        openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 10;
        openIDImplicitFlowConfiguration.auto_clean_state_after_authentication = true;
 
        const authWellKnownEndpoints = new AuthWellKnownEndpoints();
        authWellKnownEndpoints.issuer = 'http://localhost:5000';
        authWellKnownEndpoints.jwks_uri ='http://localhost:5000/.well-known/openid-configuration/jwks';
        authWellKnownEndpoints.authorization_endpoint = 'http://localhost:5000/connect/authorize';
        authWellKnownEndpoints.token_endpoint = 'http://localhost:5000/connect/token';
        authWellKnownEndpoints.userinfo_endpoint = 'http://localhost:5000/connect/userinfo';
        authWellKnownEndpoints.end_session_endpoint = 'http://localhost:5000/connect/endsession';
        authWellKnownEndpoints.check_session_iframe ='http://localhost:5000/connect/checksession';
        authWellKnownEndpoints.revocation_endpoint = 'http://localhost:5000/connect/revocation';
        authWellKnownEndpoints.introspection_endpoint ='http://localhost:5000/connect/introspect';
 
        openIDImplicitFlowConfiguration.trigger_authorization_result_event = true;
        this.oidcSecurityService.setupModule(
            openIDImplicitFlowConfiguration,
            authWellKnownEndpoints
        );`

**Also snippet where I am expecting user information.**
`this.oidcSecurityService.getUserData().subscribe(
      (userInfo: any) => {
        console.log("UserInfo", userInfo);
      }
    )`

**below is the screen of server side GetProfileDataAsync method debug:**
![sub absent](https://user-images.githubusercontent.com/36633181/52622743-90449600-2ed0-11e9-8ee0-f2e8e7b4fb5e.png)

wasted 2/3 days to identify.

Thank you in advance.

**Comment by manojsati** [comment]
Hi,
did you find any solution. At least it doesnot show there is any response.
Thanks

**Comment by damienbod** [comment]
closing this, please open if you still have an issue

**Comment by alecrt** [comment]
Same problem here @damienbod.

The observable immediatly after login emits twice:

1. user object 
2. string serialization of a function (need to check the exact function on debug..)

Ther order is random.

It happens only after authorize flow initialization.
