### ISSUE TITLE
Exported members have mimified names

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#396]
I'm trying to use the TokenHelperService to decode the access token (keycloak only show roles in access tokens) but it's exported as `export { TokenHelperService as ɵe } from './src/services/oidc-token-helper.service';`
Would you mind adding it to the public_api or exported in a usable way?

Thanks

**Comment by damienbod** [comment]
Hi @yelhouti 

TokenHelperService is a internal service. I could add this to the public api, if it is required. Why do you require this?

Her are are the public APIs:

https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.service.ts#L205

https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.service.ts#L214

Greetings Damien

**Comment by yelhouti** [comment]
I tried to explain it in the request, I need to something like:
```
getPayloadFromIdToken(encode = false): any {
        const token = this.getIdToken();
        return this.tokenHelperService.getPayloadFromToken(token, encode);
    }
```
More precisely, I need `getUserData` equivalent using accessToken

**Comment by damienbod** [comment]
Release version 9.0.3

**Comment by yelhouti** [comment]
@damienbod you sir, are awesome :) thank you very much for the great lib
