### ISSUE TITLE
onCheckSessionChange with keycloak

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#397]
When using keycloak onCheckSessionChange is never triggered.
In my case stsServer is `http://keycloak/auth/realms/myrealm` while e.origin is `http://keycloak`

may be the code should be changed to this:
`this.authConfiguration.stsServer.indexOf(e.origin) === 0` instead of checking if they are equal

**Comment by yelhouti** [comment]
After fixing that I found some other issue with how checkSession is implements, please check my code and comments here: https://github.com/yelhouti/angular-auth-oidc-client/commit/d03e641badf90e8625a057497b17680687b95203
Sorry I can't do more in the next few days.

**Comment by damienbod** [comment]
closing this, please re-open is required
