### ISSUE TITLE
What is STS 

### ISSUE THREAD

**Issue by vit100** [damienbod/angular-auth-oidc-client#398]
In documentation `sts` probably means security token server? 
Is it auth or token endpoint?
Should be 2 separate configuration settings for each endpoints for code flow, as authorization and token exchange are different endpoints.

**Comment by damienbod** [comment]
HI @vit100 

Yes security token server, no Only 1 endpoint is required, the well known endpoint API defines all the required endpoints for the OIDC server as per spec.

Greetings Damien

**Comment by vit100** [comment]
aha, so it is url of .well-known?

**Comment by damienbod** [comment]
Can I close this?

Greetings Damien

**Comment by vit100** [comment]
Probably yes, but docs should be fixed as well.

**Comment by damienbod** [comment]
Hi @vit100 
Would you let to do  a PR? 

I would be very grateful.

Greetings Damien

**Comment by vit100** [comment]
OK.  Will work on weekends

**Comment by findinfinite** [comment]
I notice this code:
return () => oidcConfigService.load_using_custom_stsServer('**https://login.microsoftonline.com/fabrikamb2c.onmicro**soft.com/v2.0/.well-known/openid-configuration?p=b2c_1_susi');

Is there any documentation on how to get my STS Server URL? I'm using Azure and have my app service configured with Goole Authentication provider so far, will expand that to Facebook, Twitter, etc. later. I'm missing something some where.

**Comment by damienbod** [comment]
closing this, please re-open is required
