### ISSUE TITLE
client secret is missing

### ISSUE THREAD

**Issue by vit100** [damienbod/angular-auth-oidc-client#399]
Trying to test lib with google. Idea is that SPA application should use code flow, but looks like google is not happy about this.

Below is config loaded when app starts. See that only clientId is configured, which is probably OK for unsecured client.
```
oidcConfigService.onConfigurationLoaded.subscribe((isLoaded) => {
      if (!isLoaded) { return; }

      const authWellKnownEndpoints = new AuthWellKnownEndpoints();
      authWellKnownEndpoints.setWellKnownEndpoints(that.oidcConfigService.wellKnownEndpoints);

      const openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
      openIDImplicitFlowConfiguration.stsServer = 'https://accounts.google.com';
      openIDImplicitFlowConfiguration.redirect_url = 'http://localhost:4200/login'; 
      openIDImplicitFlowConfiguration.client_id = 'MYCLIENTID.apps.googleusercontent.com';  
      openIDImplicitFlowConfiguration.response_type = 'code'; 
      openIDImplicitFlowConfiguration.post_logout_redirect_uri = 'http://localhost:4200/logout'; 
      openIDImplicitFlowConfiguration.start_checksession = false;
      openIDImplicitFlowConfiguration.silent_renew = true; 
      openIDImplicitFlowConfiguration.silent_renew_url = 'http://localhost:4200/silent-renew'; 
      openIDImplicitFlowConfiguration.post_login_route = '/data'; 
      // HTTP 403
      openIDImplicitFlowConfiguration.forbidden_route = '/Forbidden'; 
      // HTTP 401
      openIDImplicitFlowConfiguration.unauthorized_route = '/Unauthorized'; 
      openIDImplicitFlowConfiguration.log_console_warning_active = true; 
      openIDImplicitFlowConfiguration.log_console_debug_active = true; 
      openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 10;
      that.oidcSecurityService.setupModule(openIDImplicitFlowConfiguration, authWellKnownEndpoints);
```

Browser gets redirected to authorization endpoint, user got authorized, browser gets code and then browser sends POST to get tokens with following body:
```
grant_type: authorization_code
client_id: MYCLIENTID.apps.googleusercontent.com
code_verifier: C0.9539607791251963155234427018915523442701890.9264509834410828
code: 4/CwGLrrFFX8ILjGmJ6WU6xyrD8XYm7jyNmUIZLMyvNfqCMlW120fb8NWIz48MwtMr0OGad6_94dvhlBL17ruYSqQ
redirect_uri: http://localhost:4200/login
```
Full POST request:

`curl "https://oauth2.googleapis.com/token" -H "Accept: application/json, text/plain, */*" -H "Referer: http://localhost:4200/login?state=15523442246540.9649396982372547^&code=4^%^2FCwGLrrFFX8ILjGmJ6WU6xyrD8XYm7jyNmUIZLMyvNfqCMlW120fb8NWIz48MwtMr0OGad6_94dvhlBL17ruYSqQ^&scope=email^%^20profile^%^20openid^%^20https:^%^2F^%^2Fwww.googleapis.com^%^2Fauth^%^2Fuserinfo.email^%^20https:^%^2F^%^2Fwww.googleapis.com^%^2Fauth^%^2Fuserinfo.profile^&authuser=0^&session_state=fbe68abb6d80fb0bf97c667b37b7ded210627f38..56c8^&prompt=consent" -H "Origin: http://localhost:4200" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" -H "DNT: 1" -H "Content-Type: application/x-www-form-urlencoded" --data "grant_type=authorization_code^&client_id=MYCLIENTID.apps.googleusercontent.com^&code_verifier=C0.9539607791251963155234427018915523442701890.9264509834410828^&code=4/CwGLrrFFX8ILjGmJ6WU6xyrD8XYm7jyNmUIZLMyvNfqCMlW120fb8NWIz48MwtMr0OGad6_94dvhlBL17ruYSqQ^&redirect_uri=http://localhost:4200/login" --compressed `

POST requests has correct code, but no client secret and server responded with:
{
  "error": "invalid_request",
  "error_description": "client_secret is missing."
}

Is it server problem?
I tried similar with local Keycloak instance - got error: 

> 01:34:37,263 WARN  [org.keycloak.events] (default task-4) type=CODE_TO_TOKEN_ERROR, realmId=master, clientId=angular, userId=null, ipAddress=172.17.0.1, error=invalid_client_credentials, grant_type=authorization_code

**Comment by damienbod** [comment]
Hi @vit100 Yes the client secret is missing because a code flow with secret is not supported for this application type. This is because an Angular application cannot keep a secret as it runs in the browser. This is where PKCE comes into to play to solve this problem. The token servers need to support PKCE for SPA or native devices. Configure the PKCE and it will work. (No secret required)

**Comment by vit100** [comment]
Thank you Damien, 
It confirms my suspicion if server supports PKCE clientSecret is not required. Problem is that there are services which support PKCE and do require client secret.
I am not sure if it is deviation from standard and custom server implementation but result is POST request rejected due to missed client secret.

**Comment by damienbod** [comment]
closing this, please re-open is required

**Comment by dwohlfahrt** [comment]
I have been dealing with this exact issue.  Does anybody know if the Google token endpoint (https://oauth2.googleapis.com/token) officially does not support PKCE without a client secret?  @vit100 did you ever find a solution to this???  Thanks!

**Comment by vit100** [comment]
nope. I gave up.

**Comment by jo-george** [comment]
In case you absolutely need to use a client secret in your particular flow, you can use the custom parameters to add the client_secret parameter to the requests: https://angular-auth-oidc-client.com/docs/documentation/custom-parameters
Or this can also be done via the configuration for every request: https://angular-auth-oidc-client.com/docs/documentation/configuration#customparamsauthrequest
