### ISSUE TITLE
OidcSecurityService’s setupModule check for authNonce fails on browser page refresh when Silent Renew enabled and user authorized

### ISSUE THREAD

**Issue by negrea** [damienbod/angular-auth-oidc-client#400]
When Silent Renew is enabled and user is authorized calls to OidcSecurityService’s setupModule will always trigger a request to the authorization endpoint because the check for the authNonce fails. Because of this refreshSession() will proceed to reauthorize the user even though his id_token hasn’t expired yet. As a result, whenever a user refreshes the web application from the browser button a new set of tokens are created. This in turn leads to a new access token being created in the PersistedGrantStore database, which is problematic.

From my understanding this seems to be because the authNonce is not persisted in the application’s session storage when the user is authorized. 

Here are some snippets of the oidc Angular logs:

At initial app launch
![oidc-issue-ss1-initial-log](https://user-images.githubusercontent.com/9590802/54214884-ebbd7000-44de-11e9-85ec-d5c99c4fec9f.jpg)

After an initial browser refresh (if I manually trigger one before attempting to login)
![oidc-issue-ss2-after-page-refresh](https://user-images.githubusercontent.com/9590802/54214907-f7109b80-44de-11e9-8e17-a777280ce5bb.PNG)

After logging in
![oidc-issue-ss3-after-login](https://user-images.githubusercontent.com/9590802/54214931-fd9f1300-44de-11e9-812e-605f885bb22e.jpg)

![oidc-issue-ss3-after-login2](https://user-images.githubusercontent.com/9590802/54214939-01329a00-44df-11e9-98e0-ef89842c50cd.PNG)
Login seems to work fine as well as the Silent Renew in this case.

On page refresh
![oidc-issue-ss4-after-refresh1](https://user-images.githubusercontent.com/9590802/54214955-098ad500-44df-11e9-8d8f-bafde226a004.jpg)
![oidc-issue-ss4-after-refresh2](https://user-images.githubusercontent.com/9590802/54214962-0bed2f00-44df-11e9-9c4f-a89a3212aea7.jpg)

Code snippet of our workflow for initialising the module and authentication logic:

We’ve refactored the angular-auth-oidc-client into a separate module to be then imported into our applications.
```
@Injectable()
export class RdOidcLoginService {
  …
  initAuthModule() {
    this._store.dispatch(new InitOidcModuleSetup());

  login() {
    this._oidcSecurityService.authorize();
  }

  logoff() {
    this._oidcSecurityService.logoff();
  }
}
```

```
@Effect() initModuleSetup$ = this.actions$.pipe(
        ofType(rdUserInfoActionTypes.INIT_MODULE_SETUP),
        switchMap(() => this._oidcSecurityService.getIsModuleSetup()),
        filter(isModuleSetup => isModuleSetup),
        take(1), // it is important that we only take 1 value once it is set to true as this observable will be emitted for all late subscribers
        map((isModuleSetup: boolean) => {
            return new OnInitOidcModuleSetup(isModuleSetup);
        }))
        .catch((error) => Observable.of(new OnUserInfoError(error)));
```
```
@Effect() onInitModuleSetup$ = this.actions$.pipe(
        ofType(rdUserInfoActionTypes.ON_INIT_MODULE_SETUP),
        map((action: OnInitOidcModuleSetup) => {
            if (window.location.hash) {
                this._oidcSecurityService.authorizedCallback();
            }
        }),
        switchMap(() => this._rdOidcAuthService.getDataForOidcModuleInit()),
        map((val) => {
            return new OnInitAuthModule(val.isAuthorized, val.userData);
        }))
        .catch((error) => Observable.of(new OnUserInfoError(error))
        );
```
```
getDataForOidcModuleInit() {
    return this._oidcSecurityService.getIsAuthorized().switchMap((isAuthorized) => {
      if (isAuthorized)
        return this._oidcSecurityService.getUserData().map((userData: RdUserData) => ({
          isAuthorized: isAuthorized,
          userData: userData
        }));
        else
          return Observable.of({
            isAuthorized: false,
            userData: null
          });
    });
  }

```
Then in our application’s app.components.ts we are calling:
`this._oidcLoginService.initAuthModule();`
in `ngOnInit()`.

These are the settings loaded into oidcSecurityService’s setupModule:

```
"StsServer": "https://localhost:44321",
"RedirectUrl": "https://localhost:4200",
"ClientId": "…",
"ResponseType": "id_token token",
"Scope": "…",
"PostLogoutRedirectUri": "https://localhost:4200",
"StartChecksession": false,
"SilentRenew": true,
"SilentRenewUrl": "https://localhost:4200/Home/SilentRenew",
"PostLoginRoute": "/",
"ForbiddenRoute": "/forbidden",
"UnauthorizedRoute": "/unauthorized",
"AutoUserinfo": false,
"LogConsoleWarningActive": true,
"LogConsoleDebugActive": true,
"MaxIdTokenIatOffsetAllowedInSeconds": 10,
"AutoCleanStateAfterAuthentication": false,
"TriggerAuthorizationResultEvent": false,
"SilentRenewOffsetInSeconds": 10
```
And these are the config settings on the IDP:

```
new Client {
…
AccessTokenType = AccessTokenType.Reference,
RequireConsent = false,
AccessTokenLifetime = 360, // 6 min, defaults to 3600 seconds / 1 hour
IdentityTokenLifetime = 60, // 1 min, defaults to 300 seconds / 5 minutes
AllowedGrantTypes = GrantTypes.Implicit,
AllowAccessTokensViaBrowser = true,
RedirectUris = new List<string>
{
"https://localhost:4200",
"https://localhost:4200/Home/SilentRenew"
},
PostLogoutRedirectUris = new List<string>
{
"https://localhost:4200",
"https://localhost:4200/unauthorized"
},
AllowedCorsOrigins = new List<string>
{
"https://localhost:4200",
"https://localhost:44322"
},
…
}
```
How do we prevent a page refresh from the browser from triggering an authorization request when the user is already logged in and authorized?

Also, considering that the Silent Renew only checks for the expiration time of the id_token and if it is expired then makes a request for a new set of tokens, could you please explain the reasoning behind setting an AccessTokenLifetime longer than the IdentityTokenLifetime when every time the Silent Renew will trigger this will result in the creation of a new access token? (have seen this in several of your examples).

Thanks for taking the time to read this and will be waiting for your reply on the issue.

**Comment by korolevsa** [comment]
Good day! I tried this case.

auth.actions.ts
```
import { Action } from '@ngrx/store';

export const INITIALIZING = '[AUTH] INITIALIZING'
export const INITIALIZING_DONE = '[AUTH] INITIALIZING_DONE'
export const INITIALIZING_ERROR = '[AUTH] INITIALIZING_ERROR'
export const AUTHORIZATION_DONE = '[AUTH].[USER] AUTHORIZATION_DONE';
export const AUTHORIZATION_ERROR = '[AUTH] AUTHORIZATION_ERROR';

export const AUTO_LOGIN = "[AUTH] AUTO_LOGIN"
export const LOG_OUT = "[AUTH].[USER] LOG_OUT"

export class Initializing implements Action {
  readonly type = INITIALIZING;
}

export class InitializingDone implements Action {
  readonly type = INITIALIZING_DONE;
  constructor(public isModuleSetup: boolean) { }
}

export class InitializingError implements Action {
  readonly type = INITIALIZING_ERROR;
  constructor(public error: string) { }
}

export class AuthorizationDone implements Action {
  readonly type = AUTHORIZATION_DONE;
  constructor(public isAuthorized: boolean, public userData: any) { }
}

export class AuthorizationError implements Action {
  readonly type = AUTHORIZATION_ERROR;
  constructor(public error: string) { }
}

export class AutoLogin implements Action {
  readonly type = AUTO_LOGIN;
  constructor() { }
}

export class LogOut implements Action {
  readonly type = LOG_OUT;
  constructor() { }
}

export type AuthActions = Initializing
  | InitializingDone
  | InitializingError
  | AuthorizationDone
  | AuthorizationError
  | AutoLogin
  | LogOut;
```

auth.effects.ts
```
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { Actions, Effect, ofType } from '@ngrx/effects';

import { of } from 'rxjs';
import { catchError, map, switchMap, filter, take, tap } from 'rxjs/operators';

import * as authActions from '../actions/auth.actions';
import { AuthService } from '../../services';



@Injectable()
export class AuthEffects {
  constructor(private action$: Actions, private authService: AuthService, private router: Router) { }

  private onAutoLogin = () => {
    this.authService.logIn();
  }

  private onLogOut = () => {
    this.authService.logOut();
  }

  @Effect()
  initModuleSetup$ = this.action$.pipe(
    ofType(authActions.INITIALIZING),
    switchMap(() => this.authService.Initializing())
    , filter(isModuleSetup => isModuleSetup)
    , take(1)
    , map((isModuleSetup: boolean) => {
      //console.log('isModuleSetup', isModuleSetup);
      return new authActions.InitializingDone(isModuleSetup);
    }),
    catchError((error) => of(new authActions.InitializingError(error)))
  );

  @Effect() onInitModuleSetup$ = this.action$.pipe(
    ofType(authActions.INITIALIZING_DONE),
    map((action: authActions.InitializingDone) => {
      this.authService.doCallbackLogicIfRequired()
    }),
    switchMap(() => this.authService.getDataForOidcModuleInit()),
    take(1)
    , map((val) => {
      if (!val.isAuthorized) {
        //console.log('AuthorizationError');
        return new authActions.AutoLogin();
      }
      //console.log('AuthorizationDone', val);
      return new authActions.AuthorizationDone(val.isAuthorized, val.userData);
    }),
    catchError((error) => of(new authActions.AuthorizationError(error)))
  );

  @Effect()
  AutoLogin$ = this.action$.pipe(
    ofType(authActions.AUTO_LOGIN),
    take(1)
    , tap(this.onAutoLogin)
  );

  @Effect()
  logOutEffect$ = this.action$.pipe(
    ofType(authActions.LOG_OUT),
    take(1)
    , tap(this.onLogOut)
  );
}
```
auth.guard.ts
```
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, CanLoad, Route } from '@angular/router';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { getUserIsAuthorized } from '../store/reducers';

@Injectable()
export class AuthGuardService implements CanActivate, CanLoad {
  constructor(public store: Store<any>) { }

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
    return this.checkUser();
  }

  canLoad(state: Route): Observable<boolean> {
    return this.checkUser();
  }

  private checkUser(): Observable<boolean> {
    return this.store.select(getUserIsAuthorized);
  }
}
```
auth.service.ts

```
import { Injectable } from '@angular/core';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { Observable, of } from 'rxjs';
import { map, switchMap, take } from 'rxjs/operators';

@Injectable()
export class AuthService {

  constructor(public oidcSecurityService: OidcSecurityService) {
  }

  Initializing = (): Observable<boolean> =>
    this.oidcSecurityService.getIsModuleSetup();

  logIn = () => this.oidcSecurityService.authorize();

  logOut = () => this.oidcSecurityService.logoff();

  doCallbackLogicIfRequired = () =>
    window.location.hash
      ? this.oidcSecurityService.authorizedCallbackWithCode(window.location.toString())
      : [];

  getDataForOidcModuleInit = () =>
    this.oidcSecurityService.getIsAuthorized().pipe(
      take(1)
      ,switchMap((isAuthorized) =>
        isAuthorized
          ? this.oidcSecurityService.getUserData().pipe(
            map((userData: any) => ({
              isAuthorized: isAuthorized,
              userData: userData
            })))
          : of({
            isAuthorized: false,
            userData: null
          })
      ));
}
```
app.component.ts
```
export class AppComponent  implements OnInit {

  public isAuthorized$: Observable<boolean>;

  constructor(private store: Store<any>) { }

  ngOnInit(): void {
    this.store.dispatch(new Initializing());
    this.isAuthorized$ = this.store.select(getUserIsAuthorized);
  }
}
```

It works for me.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue

**Comment by inpicksys** [comment]
@negrea Hi. Great example. Could you post here reducers as well? For complete perfect implementation auth with ngrx. Will be appreciated for that. Thanks.

**Comment by inpicksys** [comment]
> Good day! I tried this case.
> 
> auth.actions.ts
> 
> ```
> import { Action } from '@ngrx/store';
> 
> export const INITIALIZING = '[AUTH] INITIALIZING'
> export const INITIALIZING_DONE = '[AUTH] INITIALIZING_DONE'
> export const INITIALIZING_ERROR = '[AUTH] INITIALIZING_ERROR'
> export const AUTHORIZATION_DONE = '[AUTH].[USER] AUTHORIZATION_DONE';
> export const AUTHORIZATION_ERROR = '[AUTH] AUTHORIZATION_ERROR';
> 
> export const AUTO_LOGIN = "[AUTH] AUTO_LOGIN"
> export const LOG_OUT = "[AUTH].[USER] LOG_OUT"
> 
> export class Initializing implements Action {
>   readonly type = INITIALIZING;
> }
> 
> export class InitializingDone implements Action {
>   readonly type = INITIALIZING_DONE;
>   constructor(public isModuleSetup: boolean) { }
> }
> 
> export class InitializingError implements Action {
>   readonly type = INITIALIZING_ERROR;
>   constructor(public error: string) { }
> }
> 
> export class AuthorizationDone implements Action {
>   readonly type = AUTHORIZATION_DONE;
>   constructor(public isAuthorized: boolean, public userData: any) { }
> }
> 
> export class AuthorizationError implements Action {
>   readonly type = AUTHORIZATION_ERROR;
>   constructor(public error: string) { }
> }
> 
> export class AutoLogin implements Action {
>   readonly type = AUTO_LOGIN;
>   constructor() { }
> }
> 
> export class LogOut implements Action {
>   readonly type = LOG_OUT;
>   constructor() { }
> }
> 
> export type AuthActions = Initializing
>   | InitializingDone
>   | InitializingError
>   | AuthorizationDone
>   | AuthorizationError
>   | AutoLogin
>   | LogOut;
> ```
> 
> auth.effects.ts
> 
> ```
> import { Injectable } from '@angular/core';
> import { Router } from '@angular/router';
> import { Actions, Effect, ofType } from '@ngrx/effects';
> 
> import { of } from 'rxjs';
> import { catchError, map, switchMap, filter, take, tap } from 'rxjs/operators';
> 
> import * as authActions from '../actions/auth.actions';
> import { AuthService } from '../../services';
> 
> 
> 
> @Injectable()
> export class AuthEffects {
>   constructor(private action$: Actions, private authService: AuthService, private router: Router) { }
> 
>   private onAutoLogin = () => {
>     this.authService.logIn();
>   }
> 
>   private onLogOut = () => {
>     this.authService.logOut();
>   }
> 
>   @Effect()
>   initModuleSetup$ = this.action$.pipe(
>     ofType(authActions.INITIALIZING),
>     switchMap(() => this.authService.Initializing())
>     , filter(isModuleSetup => isModuleSetup)
>     , take(1)
>     , map((isModuleSetup: boolean) => {
>       //console.log('isModuleSetup', isModuleSetup);
>       return new authActions.InitializingDone(isModuleSetup);
>     }),
>     catchError((error) => of(new authActions.InitializingError(error)))
>   );
> 
>   @Effect() onInitModuleSetup$ = this.action$.pipe(
>     ofType(authActions.INITIALIZING_DONE),
>     map((action: authActions.InitializingDone) => {
>       this.authService.doCallbackLogicIfRequired()
>     }),
>     switchMap(() => this.authService.getDataForOidcModuleInit()),
>     take(1)
>     , map((val) => {
>       if (!val.isAuthorized) {
>         //console.log('AuthorizationError');
>         return new authActions.AutoLogin();
>       }
>       //console.log('AuthorizationDone', val);
>       return new authActions.AuthorizationDone(val.isAuthorized, val.userData);
>     }),
>     catchError((error) => of(new authActions.AuthorizationError(error)))
>   );
> 
>   @Effect()
>   AutoLogin$ = this.action$.pipe(
>     ofType(authActions.AUTO_LOGIN),
>     take(1)
>     , tap(this.onAutoLogin)
>   );
> 
>   @Effect()
>   logOutEffect$ = this.action$.pipe(
>     ofType(authActions.LOG_OUT),
>     take(1)
>     , tap(this.onLogOut)
>   );
> }
> ```
> 
> auth.guard.ts
> 
> ```
> import { Injectable } from '@angular/core';
> import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, CanLoad, Route } from '@angular/router';
> import { Observable } from 'rxjs';
> import { Store } from '@ngrx/store';
> import { getUserIsAuthorized } from '../store/reducers';
> 
> @Injectable()
> export class AuthGuardService implements CanActivate, CanLoad {
>   constructor(public store: Store<any>) { }
> 
>   canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
>     return this.checkUser();
>   }
> 
>   canLoad(state: Route): Observable<boolean> {
>     return this.checkUser();
>   }
> 
>   private checkUser(): Observable<boolean> {
>     return this.store.select(getUserIsAuthorized);
>   }
> }
> ```
> 
> auth.service.ts
> 
> ```
> import { Injectable } from '@angular/core';
> import { OidcSecurityService } from 'angular-auth-oidc-client';
> import { Observable, of } from 'rxjs';
> import { map, switchMap, take } from 'rxjs/operators';
> 
> @Injectable()
> export class AuthService {
> 
>   constructor(public oidcSecurityService: OidcSecurityService) {
>   }
> 
>   Initializing = (): Observable<boolean> =>
>     this.oidcSecurityService.getIsModuleSetup();
> 
>   logIn = () => this.oidcSecurityService.authorize();
> 
>   logOut = () => this.oidcSecurityService.logoff();
> 
>   doCallbackLogicIfRequired = () =>
>     window.location.hash
>       ? this.oidcSecurityService.authorizedCallbackWithCode(window.location.toString())
>       : [];
> 
>   getDataForOidcModuleInit = () =>
>     this.oidcSecurityService.getIsAuthorized().pipe(
>       take(1)
>       ,switchMap((isAuthorized) =>
>         isAuthorized
>           ? this.oidcSecurityService.getUserData().pipe(
>             map((userData: any) => ({
>               isAuthorized: isAuthorized,
>               userData: userData
>             })))
>           : of({
>             isAuthorized: false,
>             userData: null
>           })
>       ));
> }
> ```
> 
> app.component.ts
> 
> ```
> export class AppComponent  implements OnInit {
> 
>   public isAuthorized$: Observable<boolean>;
> 
>   constructor(private store: Store<any>) { }
> 
>   ngOnInit(): void {
>     this.store.dispatch(new Initializing());
>     this.isAuthorized$ = this.store.select(getUserIsAuthorized);
>   }
> }
> ```
> 
> It works for me.

It doesn't work. There is not reducer in this example.
And I don't find any working example with autologin & and implemented it with ngrx
