### ISSUE TITLE
Using refresh token

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#401]
Hi @damienbod 

I have a use case where I want to use the refresh token to silent renew my token.

Would you agree to me adding an opt-in option (useRefreshToken) in the oidc.security.service and when true in the `refreshSession` send a post request with refreshToken instead of creating the URL and using in the iframe.

I would also need to make the `authorizedCallbackProcedure` public to be able to update the (access/id/refresh tokens manually)

**Why?**
Some of my users are able to impersonate others, my IdP doesn't allow me to specify who can impersonate /token exchange) who, therefore, I check on my server if X can impersonate Y, an admin is used to impersonate and retrieve a refresh token for Y, and send it to the frontend, the frontend should use that refresh token each time to renew the access token.

**Expected and know limitations:**
The impersonation would work per browser tab, which I prefer.
The original session might expire if not used in another tab, or if the user doesn't switch back, which might lead to logout.

Thanks in advance

**Edit**: after some testing, it seems like the validation should handled ait differently than in `authorizedCallbackProcedure` (nonce and state are not present in the refresh response and should not be checked), maybe we should have a function that all the other checks (signature, aud...) separately and call it from the two places (onRefresh and authorizedCallbackProcedure)..., what do you think?

**Comment by lthorne1** [comment]
I have a basic implementation that defaults to using a refresh code if it exists (should only be populated with the 'code' response type). - https://github.com/damienbod/angular-auth-oidc-client/pull/474
I would love any input on ways to make it customizable or any other improvements!

**Comment by DemonICOLI** [comment]
@lthorne1 I've checked your work and seems fine, however, I'm having an issue at refresh time, since local nonce doesn't match the one in the new token.

Probably my fault but i'll check it again

**Comment by damienbod** [comment]
closing this, please open if you still have an issue

**Comment by a-a-k** [comment]
@yelhouti hi, could you describe your approach for impersonation implementation?
