### ISSUE TITLE
illegal state manipulation

### ISSUE THREAD

**Issue by yelhouti** [damienbod/angular-auth-oidc-client#402]
Hi @damienbod I was going thru the code and found this:
```
let obj: any = new Object;
obj = response;
obj.state = state;
obj.session_state = session_state;

this.authorizedCodeFlowCallbackProcedure(obj);
```
There is no point on setting the state manually to check it latter  against the same value or am I wrong?
Also, if I understand it well, state is only useful for GET request (should be sent in the request) that result in redirects to make sure that the response is received from the IdP. May be I cleanup this part.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
