### ISSUE TITLE
Application lifecycle.

### ISSUE THREAD

**Issue by andriy-tsvikla** [damienbod/angular-auth-oidc-client#404]
Is there any diagram or description of application lifecicle?
It seems that after login against Identity Server it takes some time for app to process response data.
And if i wont set delay after login on redirection to route with guardian which checks this.oidcSecurityService.getIsAuthorized(), i will always return false. Should i wait for some event?
Same thing on doCallbackLogicIfRequired with PCKE flow, page reload with this.oidcSecurityService.authorizedCallbackWithCode(window.location.toString()) trigger next reload and then for each reload it does call to connect/token endpoint.
It is hard to understand what is going on and whats wrong. Thanks.

**Comment by FabianGosebrink** [comment]
will be fixed in rls 11
