### ISSUE TITLE
authorizedCallback incorrect iss does not match authWellKnownEndpoints issuer

### ISSUE THREAD

**Issue by gazalle** [damienbod/angular-auth-oidc-client#407]
Validate_id_token_iss failed, dataIdToken.iss: http://localhost:5000 authWellKnownEndpoints issuer:http://localhost:5000/

**Comment by manojsati** [comment]
which version of angular-auth-oidc-client are you using?

**Comment by damienbod** [comment]
@gazalle This usually happens when you use a incorrect server configuration. What Secure token service are you using? It is possible to turn off this validation in the lib, but this is not recommended unless required, for example when the Azure AD multi tenant OIDC server

**Comment by gazalle** [comment]
> which version of angular-auth-oidc-client are you using?

it is 9.0.3 version

**Comment by gazalle** [comment]
> @gazalle This usually happens when you use a incorrect server configuration. What Secure token service are you using? It is possible to turn off this validation in the lib, but this is not recommended unless required, for example when the Azure AD multi tenant OIDC server

@damienbod  Thanks for the response. 

I am using IdentityServer4 as STS. I somehow solved the problem by just removing this  / from  authWellKnownEndpoints.issuer and it is working fine.  Can it be that much sensitive to just one extra / ? Or I need to consider some more things while configuring the server (or client setting)?

**Comment by damienbod** [comment]
This should work with ID4. Are you behind a proxy?

**Comment by gazalle** [comment]
My ID4 is running on IIS Express

` "iisSettings": {
    "windowsAuthentication": false, 
    "anonymousAuthentication": true, 
    "iisExpress": {
      "applicationUrl": "http://localhost:5000",
      "sslPort": 0
    }`

My Angular application is redirected to ID4 for authentication and ID4 redirects to Azure AD for user authentication and then back to the Angular client. When client wants to validate token I was getting this error that iss does not match the wellknown endpoint. So there are no other extra proxies.

**Comment by damienbod** [comment]
You should not have this then, they must be a client config, server config mismatch then
