### ISSUE TITLE
angular-auth-oidc-client version 6.0.1 is not working at present.

### ISSUE THREAD

**Issue by manojsati** [damienbod/angular-auth-oidc-client#408]
In our project we were using version 6.0.1 of angular-auth-oidc-client component for long time. But suddenly it stopped working. As a temporarary work out now I am modifying (basically blocking some piece of code) of angular-auth-oidc-client.es5.js file to avoid authentication. This is not a solution. Blocked code is:
 OidcSecurityValidation.prototype.validate_id_token_nonce = function (dataIdToken, local_nonce) {
        /* if (dataIdToken.nonce !== local_nonce) {
            this.loggerService.logDebug('Validate_id_token_nonce failed, dataIdToken.nonce: ' +
                dataIdToken.nonce +
                ' local_nonce:' +
                local_nonce);
            return false;
        } */
        return true;
    };

Now Big question is why same version of one component will stop working suddenly. That means code management is not at all proper for this component. 

Also immediately I need a full proof angular-auth-oidc-client component which will work perfectly with Angular 6 application which access WebApi and identityserver4 (both are http i.e. not ssl certified.) . Can you give any link where I can see proper sample application.

Waiting for your earliest reply.

**Comment by damienbod** [comment]
Hi @manojsati 

Here's an example:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow

**Comment by manojsati** [comment]
Hi damien,
I also saw that example but do you recommend Implicit flow?

is there any security concern with this approach?
Also my confusion is do we need to use angular routerguard with this component?

Thanks for your reply. Please reply to my query.

Best Regards,
Manoj
________________________________

**Comment by manojsati** [comment]
Hi damien,
can I use this sample code?

https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects/sample-code-flow/src

regards
________________________________

**Comment by damienbod** [comment]
@manojsati clone the repo, install the nodejs tools, and the .NET Core tools, and run

**Comment by manojsati** [comment]
@damien, I have a serious doubt. you have recommended to use from sample https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow but this sample is purely a implicitflow. And it is very clearly told that we should not use implicit flow. I also feel we should use a component of particular version. That is why I have big doubt. Please tell me which version of your componet works perfectly with angular 6.0.1 version? Also please give me full proof Angular project code that works with your component's particular version. Please help as it is very urgent.

**Comment by manojsati** [comment]
@damienbod are you not sure about the latest version of this component? My doubt is if you are sure about stability of version 9.0.3 then why will you recommend implicit flow? How can we depend on angular-auth-oidc-client for a very professional level of project?

**Comment by damienbod** [comment]
@manojsati I don't recommend the implicit flow any more. An example of the code flow is also in this repo. 

Here's another example

https://github.com/damienbod/AspNetCoreAngularSignalRSecurity

And another example in in this repo.

9.0.4 is stable and I don't see what your problem is. The repo also has an Angular-CLI example using the code flow.

**Comment by warrior711** [comment]
@damienbod Hi Damien,

I have recently implemented Implicit flow after lot of efforts but now i see this comment.
I have grant types to code in both Id server and angular application , but now after successful login it is redirecting me with parameters such as code,scope,state etc. but i don't want it to be in url . and also when i am calling getToken() , it is returning me blank.
Please help me and let me know if any further information required from my end.
Thanks

**Comment by warrior711** [comment]
Sorry i hadn't removed client secret from the client in IDS 4 so i was getting error. Now it works perfectly .
Thanks.

**Comment by manojsati** [comment]
Hi @warrior711 , can you help me with your project configuration settings?

**Comment by warrior711** [comment]
[clientInAngular.txt](https://github.com/damienbod/angular-auth-oidc-client/files/3032560/clientInAngular.txt)
[clientInIdentityServer.txt](https://github.com/damienbod/angular-auth-oidc-client/files/3032561/clientInIdentityServer.txt)

I have attached my configuration of client (angular and IS4 ). you can contact me on skyfighter.001@gmail.com

**Comment by damienbod** [comment]
Thanks @warrior711 

you should use HTTPS as well.

Greetings Damien

**Comment by warrior711** [comment]
Thanks , i will make them https. Damien , i need one more help form you ,i am sorry i am posting it over here. 
https://stackoverflow.com/questions/55469622/how-to-send-email-id-when-calling-identity-server-4-to-login/55469757#55469757

i want to send some extra information(like username , IP etc ) of user to identity server when redirecting to login , but couldn't find any way in this angular library.
Please help.

**Comment by warrior711** [comment]
Thanks Damien
