### ISSUE TITLE
Unable to stop request to authorization endpoint initiated by startRenew() on program load

### ISSUE THREAD

**Issue by scharnyw** [damienbod/angular-auth-oidc-client#409]
When silent renew is enabled and authNonce is empty, there is always a request to the authorization endpoint initiated by OidcSecuritySilentRenew.startRenew() (see below). This happens regardless of whether the user is authorized and is the result of the callback to the isModuleSetup observable in OidcSecurityService constructor. As a result it is impossible to stop this request (unlike other silent renew requests which can be disabled by stopCheckingSilentRenew()), as long as silent renew is enabled when initially setting up the module.

![second login fail - Copy](https://user-images.githubusercontent.com/35246522/55139923-db112900-5171-11e9-8c8d-aef573b1135c.PNG)

This probably shouldn't be an issue, but I'm facing a problem where my program is set to automatically login upon first load (i.e. call OidcSecurityService.authorize() without user intervention). So 2 closely-spaced requests to the authorization endpoint are made, carrying the same state and nonce, and returning with different client nonce, which for some reason is causing authorization to fail under certain circumstances. Specifically, observing the logs it seems that authorization tends to fail when the second request (initiated by authorize()) responds before the first (initiated by startRenew()). It may be that the client detects that these 2 requests share a state, so for some reason it's treating one of them as a forgery call and denying authorization?

I can't tell if this is a problem with my code, with my authorization server (which is beyond my control), or with silent renew in the package. The workaround for now is to manually delay the call to OidcSecurityService.authorize() by 2 seconds, which is not exactly ideal.

While I check my code and with our authorization server team to see if this is their problem, can I ask what is the purpose of the first startRenew() call at program start up? The comment says

`// login not running, or a second silent renew, user must login first before this will work.`

but this is not really true as login may be actually in progress, as in this case.

Really appreciate if you can shed some light on this issue!

**Comment by bvatai** [comment]
Hi All,
I'm facing the same issue, I'd like to authenticate the user during application boot-up, without interactions. It seems like a race issue, silent-renew process is initated, authorize call is initiated, and the second call to STS ends up on trying to validate different nonces, causing a validation error. Delaying the authorize() call for a couple of seconds does help, but obviously, it's not a solution.  First thought was to initiate the silent renew process later, after the authentication process is done with positive result. Is it possible somehow?

**Comment by bvatai** [comment]
Hmm, a few more thoughts on this, and questions 
Is there anything that might block contribution of new features like 
* making new configuration properties, like automatic_silent_renew (whilst marking the existing 'silent_renew: boolean' as obsolete 
  * the new automatic_silent_renew = true case works just like silent_renew = true
  * the new automatic_silent_renew = false case works almost like silent_renew = false, however a few refactors allowed developers to explicitly initialize and start the silent renew process. As I can see this could be done with some refactors in OidcSecurityService.

My motivation is to avoid having the iframe loaded straight away, especially when the user is not authenticated yet.

In my case, I could work it around only by using a hacky setTimeout(() => this.login(), 0);

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
