### ISSUE TITLE
Request to provide sample with 9.0.3 version.

### ISSUE THREAD

**Issue by manojsati** [damienbod/angular-auth-oidc-client#411]
Can you please provide a full proof sample application with Angular 6 which works perfectly with version 9.0.3 of this component?

**Comment by damienbod** [comment]
Hi @manojsati 
There is a sample in the repo and also samples if you look at the readme links (at the bottom)

Greetings Damien

**Comment by manojsati** [comment]
Hi damien,

in my project: weapi is in localhost:4202


identity :  localhost:53648


Angular 6.0.1 application:  localhost:4200


So, you can understand what can be configuration of the project?

which sample will be suitable with this project configuration?
regards,
________________________________

**Comment by damienbod** [comment]
This is not no problem just set the configurations to match your URLs. Also you should use HTTPS

**Comment by manojsati** [comment]
Hi Damien,
Thank you so much for your help. Few days back I also realised that we need https instead of http, but couldn't convince higher management on this. Again I am telling our identity and wbapi both are http and configuration is:


in my project: weapi is in localhost:4202


identity :  localhost:53648


Angular 6.0.1 application:  localhost:4200


Kindly clarify again that do we need to modify both webapi and identity application to https ?


If we keep these two on http, we cannot implement your component?


based on your reply I will talk to higher authority. So, kindly reply to this.

regards,

________________________________

**Comment by manojsati** [comment]
Hi Damien,
 need another clarification from you. at present our webapi core has version 2.1 . Can we continue with 2.1 or we must use core 2.2 like example given by you?
regards,
________________________________

**Comment by damienbod** [comment]
@manojsati You can continue to use 2.1.

Greetings Damien

**Comment by manojsati** [comment]
Kindly reply to this email.
reagrds,
________________________________
