### ISSUE TITLE
Null response while call back with code

### ISSUE THREAD

**Issue by vik073** [damienbod/angular-auth-oidc-client#414]
Hi @damienbod  i am getting null response with 200 status , when i am calling the function with code to get id token access token and refresh token. if i make the same post request using the postman the response is required JSON.
can you please let me know if i need pass any custom parameter.

**Comment by damienbod** [comment]
hi @vik073 Are you using the correct silent renew html configuration? I need some more information. Compare you code to the docs in the readme.

Greetings Damien

**Comment by vik073** [comment]
![issue library](https://user-images.githubusercontent.com/34395826/55459565-85270000-560d-11e9-9893-1ee341ebd920.JPG)
![issue oidc](https://user-images.githubusercontent.com/34395826/55459571-88ba8700-560d-11e9-8d85-64ddc4579a0f.JPG)

kindly see the screenshot , This is simple callback with code , do i need to add any silent renew html for this as well ?

**Comment by DoloMike** [comment]
Where's the body of your request? Are the client_id, scope, and auth code included as params?

**Comment by damienbod** [comment]
fixed in the actual version
