### ISSUE TITLE
Silent Renew - consent error

### ISSUE THREAD

**Issue by maghibus** [damienbod/angular-auth-oidc-client#415]
What was the cause of error?

![silent](https://user-images.githubusercontent.com/21333465/55485225-5408f880-562a-11e9-8733-e0ba5a45d491.JPG)

**Comment by damienbod** [comment]
Consent is required for the user on the STS. The silent sends a promt=none, and consent should not be required here. Check the client configuration on the server. The consent should not be required for all requests, just logins (if required)

**Comment by maghibus** [comment]
ok , thanks.
