### ISSUE TITLE
Changing access scope dynamically

### ISSUE THREAD

**Issue by ijimmun** [damienbod/angular-auth-oidc-client#417]
Hi all, 
I'm testing the library with OpendId Connect server. The angular app has three buttons for askung authorization for different scopes (openid - profile - and openid + profile). So I need a way to change the scope on each authorize request. Right now I'm doing it by accessing directly to the OpenIDImplicitFlowConfiguration variable that I use to configure the module and changing the scope directly before the request. The problem by doing so is that the silent renew doesn't work just because the renew request is made with the default value for the scope. That is due to the fact that the callback re-render the app so the OpenIDImplicitFlowConfiguration is initialized again. 
So my main question is...
Is there a way of changing the scope before calling authorized method?

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
