### ISSUE TITLE
API acess with Code flow

### ISSUE THREAD

**Issue by ijimmun** [damienbod/angular-auth-oidc-client#418]
Hi,
I'm using the library with OpenId Connect and it is configured using code flow. I have a button in the application that request an authorization with the scope set to 'sampleApi'. The returned set from OpenId Connect is a json with access_token but no id_token as expected. But because I have no id_token I can call the Api even having the access_token.
How can I request authorization only to an api without openid nad be able to call the api?

**Comment by damienbod** [comment]
Hi @ijimmun 

Yes the access token is for the APIs, but you should receive an id_token. Sounds like your using the OAuth flow, not the OIDC Code flow. You should check this on your STS

Greetings Damien

**Comment by ijimmun** [comment]
I reviewed my STS configuration and it is set to code flow like this  
`AllowedGrantTypes = GrantTypes.Code,`
My sts configuration with the library is set like this
```
  config.response_type = 'code';
  config.scope = 'sampleApi';
```
And I'm still getting only the access token to the API but not the id_token so I'm getting an error from the library.
token 'undefined' is not valid --> token falsy
id token has no header data
any clue or example that I can use?

**Comment by damienbod** [comment]
You need to request the openid scope

https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/sample-code-flow/src/app/app.module.ts#L49

Greetings Damien

**Comment by ijimmun** [comment]
Thanks @damienbod that is what I am guessing.

**Comment by spp125** [comment]
> You need to request the openid scope
> 
> https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/sample-code-flow/src/app/app.module.ts#L49
> 
> Greetings Damien

Hi @damienbod I am getting the token ' '  is not valid --> token falsy error as well. The link you mentioned above is not working. Can you please give the reference link again if possible

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/sample-code-flow-refresh-tokens/src/app/auth-config.module.ts#L12
