### ISSUE TITLE
iat_offset and Clock Issues

### ISSUE THREAD

**Issue by evhfla** [damienbod/angular-auth-oidc-client#419]
I am using your library on an application with thousands of users, one of the issues that are causing me a lot of pain, is the fact that many users have clock issues where their times being off by a few minutes.   When that happens they can't login successfully.   I have gone as far as to set max_id_token_iat_offset_allowed_in_seconds to 180 seconds, which has helped to alleviate the issue, but day by day as more users are coming aboard, the issue is still persisting.  The only remedy is to have the users adjust their clock on their computer, and it is often a source of great frustration as they don't understand why they should have to do that, to access an application.  Do you have any recommendation as to how I can totally eliminate this issue?  Is there a way to only rely on the time on the STS Server?  This is an angular 7 application using implicit flow, with IdentityServer 4 as a secure Token Server.  I am using version 9.0.3 of the library.  

Also, I plan on transitioning the application to code flow with PKCE soon.  Would that help to mitigate the issue?

**Comment by damienbod** [comment]
@evhfla No this would not help the clock issue. The clocks offset are validated, because if I was to rob an old access token, I could maybe reset the time of my PC, and re-use the old access token. The check prevents this.

If you increase the time more, maybe this could help?

Otherwise I could also add a configuration to turn this off, if this would help you.

Let me know

Greetings Damien

**Comment by evhfla** [comment]
@damienbod Please add a configuration to turn it off...Perhaps, setting it that value to Zero...would meant that it is an indefinite value.  I have thought about making the number bigger, which I actually have done already.  Initially, it was 10 seconds, then 120 seconds, and now 180 seconds.  At every step, it helped to reduce the number of occurrences, but it doesn't eliminate it.  I have pondered setting it to 300 seconds, but this is a site that will eventually have 30,000 users and there is no telling how far off some of the user's clock will be.  The thing is this site is replacing an ASP.net MVC site with Form Auth, and needless to say, that was never a problem before.

Having the business handle support call on an issue that we do not have with our old/current site, and telling them to have users fix their time is not a good thing.  We currently have 7,000 users on the new site and as we migrate all users to the new site, the problem will just become more acute.

Thanks in advance 

P.S.  Lastly, how is someone changing their time on the PC affect API calls anyway?  Isn't the token validation for an API call happening at the server level?  In other words, the angular application is calling a WebAPI using the JWT token generated by IdentityServer4 initiated by your library.  If the time of the access token was wrong when compared to the server time, wouldn't the server reject the API call?  Also, my token is only good for 10 minutes.

**Comment by damienbod** [comment]
added a config in version 9.0.5, you can now disable this:

config.disable_iat_offset_validation = true;


The PC clocks are compared to the server clocks to prevent replay attacks using old tokens.

**Comment by evhfla** [comment]
God bless you.  Thanks!
