### ISSUE TITLE
getIsAuthorized alwasy false 

### ISSUE THREAD

**Issue by pnguyen535** [damienbod/angular-auth-oidc-client#420]
Hi,

I think I have everything setup correctly with the version "9.0.4". The Identity server login successfully, but the getIsAuthorized() always return false

this.oidcSecurityService.getIsAuthorized().subscribe(
            (isAuthorized: boolean) => {
                console.log("ngOnInit > isAuthorized:" + isAuthorized);
            });

Please help, thank you

**Comment by damienbod** [comment]
Hi @pnguyen535 

Could you compare your code to the example?

https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects/sample-code-flow/src/app

Greetings Damien

**Comment by pnguyen535** [comment]
Hi Damien,

Actually, I copied the code from there.

The only thing I changed is this code: oidcConfigService.load_using_stsServer()

Thank you

**Comment by damienbod** [comment]
Here's another working example

https://github.com/damienbod/AspNetCoreAngularSignalRSecurity/tree/master/SecurityAspNetCoreSignalR/angularApp/app

I'll check the sample and the docs, in case something is wrong.

**Comment by damienbod** [comment]
@pnguyen535 I checked the example, and this works without the problem you mentioned. Can you try building the sample and compare you solution to test?

Greetings Damien

**Comment by pnguyen535** [comment]
Hi Damien,
I just found out that my Identity Server (SSO) doesn't allow implicit (response_type: 'code'). I have to use response_type: 'code id_token'. Do you know if your library support this?
Thanks

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Software Engineer

CodeAddictive LLC

pnguyen535@yahoo.com
(206) 715-6790 





http://www.linkedin.com/in/phonguyen

KNOWLEDGE IS POWER --> CODE 4 FUN.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 

    On Tuesday, April 9, 2019, 5:15:32 AM PDT, damienbod <notifications@github.com> wrote:  
 
 
@pnguyen535 I checked the example, and this works without the problem you mentioned. Can you try building the sample and compare you solution to test?

Greetings Damien

**Comment by damienbod** [comment]
no the hybrid flow is not good for SPA clients. The lib only supports code or token id_token flows. Other flows should not be used for SPA clients.

Greetings Damien

**Comment by pnguyen535** [comment]
Yes, I hear you. I think that is one of your recommendation as well.
Anyway, I am using the 'code' authorization flow, and I ran into the issues:
1. authorizedCallback incorrect state2. authorizedCallback, token(s) validation failed, resetting
Do you ware of this?
Thanks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Software Engineer

CodeAddictive LLC

pnguyen535@yahoo.com
(206) 715-6790 





http://www.linkedin.com/in/phonguyen

KNOWLEDGE IS POWER --> CODE 4 FUN.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 

    On Tuesday, April 9, 2019, 11:14:21 AM PDT, damienbod <notifications@github.com> wrote:  
 
 
no the hybrid flow is not good for SPA clients. The lib only supports code or token id_token flows. Other flows should not be used for SPA clients.

Greetings Damien

**Comment by pnguyen535** [comment]
Hi Damien,

My original issue has to do with useHash: true, which prevent the oidc validate the code. However, I ran into an other issue. When it try to get the Access_token, it returns the 401 code

myidentityserver.com/oauth/token - this return 401 code. Below is the form data for the Post:

grant_type: authorization_code
client_id: ce4d4f27-7e84-4926-9c82-abf516919d77
code_verifier: C0.6232840363963785155495315842915549531584290.29015790925366636
code: EjXDu5b4ed
redirect_uri: https://localhost:44369

Thank you
