### ISSUE TITLE
 try use setCustomRequestParameters({ 'ui_locales': culture}); 

### ISSUE THREAD

**Issue by andreyshiryaev** [damienbod/angular-auth-oidc-client#424]
Hi when i try use setCustomRequestParameters({ 'ui_locales': culture}); i don't see  in fiddler my ui_locales param (any custom params ) 
`var culture = this.langHelper.getLangProperty();
this.oidcSecurityService.setCustomRequestParameters({ 'ui_locales': culture});
this.oidcSecurityService.authorize();`

![image](https://user-images.githubusercontent.com/14107563/55969010-c2326880-5c85-11e9-97e2-29303f8ef4fc.png)

**Comment by damienbod** [comment]
Just wondering, would this help you?

https://github.com/damienbod/angular-auth-oidc-client/issues/426

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.component.ts#L82

**Comment by andreyshiryaev** [comment]
I do as in the documentation 
![image](https://user-images.githubusercontent.com/14107563/56122322-d7a3dd00-5f7a-11e9-9804-f272973127b1.png)

this is get /connect/authorize   http://prntscr.com/nc43j4

**Comment by damienbod** [comment]
@andreyshiryaev I checked this, and it is getting sent in my examples. Do you still have this problem, or could you post your authorize request?

**Comment by andreyshiryaev** [comment]
hi, i am sorry  for long answer this task is low priority ....
yes i have problem yet , 
i use 
 "angular-auth-oidc-client": "9.0.4",
and after   this.oidcSecurityService.authorize();  i can show in output window msvs (or fiddler) request 
without parameter ui_locales
http://prntscr.com/od02l4

**Comment by nybroe** [comment]
@andreyshiryaev 
You need to create a named object instead of an anonymous one - as the [documentation](https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#setcustomrequestparametersparams--key-string-string--number--boolean-) states:
`const params: any = { ui_locales: "en" };`
`this.oidcSecurity.setCustomRequestParameters(params);`

Hope this helps.

**Comment by rekosko** [comment]
@nybroe are you sure? I'm trying different variants and I'm still unable to use this `setCustomRequestParameters` correctly.

**Comment by nybroe** [comment]
@rekosko , these are the syntax' that works in our implementation:

`const parameters: any = { prompt: "login" };
this.oidcSecurityService.setCustomRequestParameters(parameters);
this.oidcSecurityService.authorize();`

And:
`this.oidcSecurityService.setCustomRequestParameters({ prompt: "login" });
this.oidcSecurityService.authorize();`

We are using the latest version `10.0.10`.
You should be able to replace the `prompt` parameter with whatever you want to add to the request.

I hope this helps.
