### ISSUE TITLE
audience parameter in ImplicitFlowConfiguration

### ISSUE THREAD

**Issue by vit100** [damienbod/angular-auth-oidc-client#426]
sts server: auth0.com
By default this server will return non JWT access token if audience is not set in request:
>If the Access Token you got from Auth0 is not a JWT but an opaque string (like kPoPMRYrCEoYO6s5), this means that the access token was not issued for your custom API as the audience. When requesting a token for your API, make sure to use the audience parameter in the authorization or token request with the API identifier as the value of the parameter.
See: [https://auth0.com/docs/api-auth/tutorials/verify-access-token](https://auth0.com/docs/api-auth/tutorials/verify-access-token).

I configure service like this:
[https://stackblitz.com/edit/angular-auth-oidc-client?file=src%2Fapp%2Fauth%2Fauthentication.service.ts](https://stackblitz.com/edit/angular-auth-oidc-client?file=src%2Fapp%2Fauth%2Fauthentication.service.ts)

How to add audience parameter if access_point is retrieved from well-know Url?

**Comment by damienbod** [comment]
@vit100 The aud parameter is set, this is part of the specification and the server is responsible for setting this claim. If you're using JWT access token, you can check this, if it's set correct by the server. The client app does not open or do anything with the access token, just sends it to access the APIs.

Greetings Damien

**Comment by vit100** [comment]
Hi Damien,
Point is that for auth0.com they want audience parameter in request in order to get JWT access token, not opaque token.
Otherwise they return opaque string, which is useless for backend server call, as backend expect JWT bearer to validate, etc..

**Comment by damienbod** [comment]
OK,  you can add custom parameters to the request with this in it

Greetings Damien

**Comment by vit100** [comment]
acknowledged. It works.
May be it make sense to set this param before invoking _oidcSecurityService.setupModule(), not before login()?

So closing issue.

Rhetorical question - when i have time to create PR for README document update....

**Comment by woeterman94** [comment]
> OK, you can add custom parameters to the request with this in it
> 
> Here's an example
> 
> https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.component.ts#L82
> 
> Greetings Damien

I know this is old, but do you have that code somewhere? I'm facing the same issue

**Comment by vit100** [comment]
Hi, yeh, I may have it somewhere, but now I  nodeJS dev and almost don't touch .Net...If I run on this code again, i will let u know


Best regards, Vitaliy----------------------------------------



 

    On Friday, October 8, 2021, 05:16:48 p.m. EDT, Wouter ***@***.***> wrote:  
 
 



OK, you can add custom parameters to the request with this in it

Here's an example

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.component.ts#L82

Greetings Damien


I know this is old, but do you have that code somewhere? I'm facing the same issue

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
