### ISSUE TITLE
browser refresh - token lost, redirect_url missed

### ISSUE THREAD

**Issue by vit100** [damienbod/angular-auth-oidc-client#431]
Hi Damien,
I am developing solution with this package and have problem which I can not find root cause - either I do something wrong or there is bug, so I need your help.

Here is sample code: [https://stackblitz.com/edit/angular-auth-oidc-client?file=src%2Fassets%2Fauth.clientConfiguration.json](https://stackblitz.com/edit/angular-auth-oidc-client?file=src%2Fassets%2Fauth.clientConfiguration.json).
I can send you credentials in PM (if you can find time to look at this issue).
Login works, I get IdToken and AccessToken, User_info called. All looks ok,
But if browser refreshed call to login service invoked again, but this time with wrong return_url.

This is first call during initial authorization

`https://steamulsauna.auth0.com/authorize?client_id=a5JU28RExwjd37fJHe0P7rSLQuKah3rG&redirect_uri=https%3A%2F%2Fangular-auth-oidc-client.stackblitz.io&response_type=id_token%20token&scope=read%3Aschedule%20write%3Aschedule%20openid%20profile&nonce=N0.93768032296828331555450721814&state=15554506632500.572734790850419&audience=schedule-repl`

And this is call to the same endpoint just after browser refresh:

`https://steamulsauna.auth0.com/authorize?client_id=a5JU28RExwjd37fJHe0P7rSLQuKah3rG&redirect_uri=https%3A%2F%2Flocalhost%3A44311%2Fsilent-renew.html&response_type=id_token%20token&scope=read%3Aschedule%20write%3Aschedule%20openid%20profile&nonce=N0.37291451156680181555450663250&state=15554506632500.572734790850419&prompt=none&audience=schedule-repl`

Here all params are valid, except redirect_url, which is default value...
Need help.

**Comment by damienbod** [comment]
Hi @vit100 

You need to set the silent_renew_url parameter in your configuration. 

Greetings Damien

**Comment by vit100** [comment]
well, anyway after refresh tokens got cleaned and as result not authorized

**Comment by damienbod** [comment]
closing this, please re-open is required
