### ISSUE TITLE
Silent-Renew failure due to no user data (active IDP session, no application session)

### ISSUE THREAD

**Issue by Cracien** [damienbod/angular-auth-oidc-client#433]
Library Version: 9.0.3
Angular Version: 6.1.0
Description: Silent-Renew will fail if the initial authorization call (no application session state, or no userData variable) is successfully made through silent-renew instead of the authorize method.

Requirements for exhibited behavior
- There is an active session on the IDP (logged in at least once before the issue)
- The application does not call authorize automatically on start-up
- The userData_[ID] session storage variable is empty or does not exist (either due to a manual session reset or for some other reason)

Assumption
- Application does not auto-authorize on start-up
- Library is configured to silent-renew
- Library has auto_userinfo set to false

Easiest way to reproduce
1. Start application and login through any means (create idp session)
2. Clear application session storage (at a minimum the userData should be cleared, however everything can be cleared)
3. Reload the application

Expected Behavior
- Silent-renew should monitor the status of the token (i.e. expires) and renew when applicable
- User data is populated

Actual Behavior
- userData is not populated (due to the authorization being through silent-renew)
- Silent-renew does not trigger (due to the userData being null)

Cause
- silentRenewHeartBeatCheck ensures that there is a user data value prior to running the validation process
- authorizedCallbackProcedure will only set the user data if it is NOT called in response to a renew process

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
