### ISSUE TITLE
Having trouble finding the right example

### ISSUE THREAD

**Issue by bluebaroncanada** [damienbod/angular-auth-oidc-client#437]
Trying to find the example that shows how I can use an `id_token` only for accessing an API.  I went through the https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/AngularClientIdTokenOnly

I checked out the whole project and got it running.   But it doesn't say how to use it to access an API.  I actually got stuck on your main `README.md` because you're calling `getToken()` and I'm getting `""`.  So I'm just wondering how to tie the rest of the pieces together.  I have the headers ready to be modified while making a call to the API, but I don't know how to get and send the `id_token`, nor what I would do with the token in my .Net Core Api.

**Comment by damienbod** [comment]
Hi @bluebaroncanada The id token only is for UIs without APIs. You should use the id_token token  flow or the code flow if you need to access an API. The code flow is now recommended and you should use this, if your STS supports this.

Greetings Damien

**Comment by bluebaroncanada** [comment]
Fair enough.  Thank you for that.  I could be wrong, but it seem like you're using `'id_token token'` flow to access your API in the example.  The `'code'` flow doesn't seem to access the API.

**Comment by bluebaroncanada** [comment]
Ok. I figured it out.  Thanks!
