### ISSUE TITLE
Silent renew timing to renew token different from access token lifetime

### ISSUE THREAD

**Issue by ravi22saini** [damienbod/angular-auth-oidc-client#438]
Hi @damienbod

I am facing one issue recently when i moved from JWT token type to reference token in implicit flow for SPA.

I have set accesstokenlifetime about 120 and this is working fine(my token get expire after the time completes) but the silent renew is now working fine to these changes. 

Now what happen is my access token get expired long before silent renew refresh the token and because of this in my API calls i am geting 401(screenshot below).
![image](https://user-images.githubusercontent.com/31721143/56721122-dab08180-6761-11e9-9d55-773c94c8e89a.png)

Could you please help.
Thanks

**Comment by damienbod** [comment]
You need to make sure that the access token has a lifespan a little bit longer than the id_token. I only check the id_token lifespan.

**Comment by ravi22saini** [comment]
Thanks @damienbod it worked. Is this documented somewhere (which i missed you read).
And shouldn't we check access token lifespan separate then id_token because i want my user to use application but to avoid the risk of attacks on my api, i would want the access token to get quickly refresh.
This way we can give users a more better and secure experience.

**Comment by damienbod** [comment]
closing this, please open if you still have an issue
