### ISSUE TITLE
Identity server complaining sate value is too short

### ISSUE THREAD

**Issue by seleshmaster** [damienbod/angular-auth-oidc-client#439]
I am getting error from the Identity Server complaining the state value is too short when trying to authorize. It is expecting 32 characters long but it is getting 31.

http://localhost:8080/home?error=invalid_request&error_description=State+is+too+short+(minimum+is+32+characters)&state=15564487983260.5560921194917418.

can the state generation be customized or is there a way this can be changed? sorry I am fairly  new to Angular 

-thanks

**Comment by damienbod** [comment]
@seleshmaster This sounds like a problem, I had this with the code. Which version of IdentityServer4 is used? I will increase the length of the state value. Will create a new version to fix this.

**Comment by seleshmaster** [comment]
Thank you for your quick response.

The STS server I am using is actually different. I am using company owned STS server which supports OpenID version 1.0 of the specification.

Thanks

**Comment by damienbod** [comment]
updated in version 9.0.7

What version of ID4 are you using?

Greetings Damien

**Comment by seleshmaster** [comment]
That was super fast!

Thank you
