### ISSUE TITLE
Unable to respond to error when getting signing key or getting user info

### ISSUE THREAD

**Issue by scharnyw** [damienbod/angular-auth-oidc-client#442]
I have an application that uses OIDC implicit flow to perform user authentication. Due to network fluctuations, requests to the JWKs endpoint (authWellKnownEndpoints.jwks_uri) and user info endpoint (authWellKnownEndpoints.userinfo_endpoint) could sometimes fail. The current implementation of authorizedImplicitFlowCallbackProcedure() does not propagate these errors, nor does it emit anything that could notify the user (except logging) of the failure. I have also noticed that both OidcDataService.get() and OidcDataService.getIdentityUserData() does not make use of retry, which increases the likelihood that a failed JWKs or user info request would cause the user app to become stuck at post-login, as the observable in authorizedImplicitFlowCallbackProcedure() would throw error without informing the user.

Is this a problem that the development team recognizes? While I check with my OIDC service provider on the reliability of their endpoints, is there any way you could recommend as a fix to this issue?

Thanks a lot in advance!

**Comment by castrinho** [comment]
I have exactly the same need. In my case if any of these requests throw an error the application will become in an inconsistent state and will cause a loop since the application already contains a valid id_token. I would need to call the logout or clear the current state so that the user is allowed to start the login process again.

**Comment by damienbod** [comment]
@castrinho @scharnyw 
We issue a NewAuthorizationResult event now in version 11. This could be used to login again. Would this work for you?

Greetings Damien

**Comment by damienbod** [comment]
closing this for now, please reopen if you think this is still an issue.

Thanks Damien
