### ISSUE TITLE
authNonce not cleared in storage after unsuccessful login and logout

### ISSUE THREAD

**Issue by john-hi** [damienbod/angular-auth-oidc-client#443]
it prevents start silent renew process at next time. I've spent a lot of time trying understand why [Confirm registration with authorizedCallback #292](https://github.com/damienbod/angular-auth-oidc-client/issues/292) stopped work while using localStorage.

https://github.com/damienbod/angular-auth-oidc-client/blob/c1ab79303c29de6c77b983725726f9cd8e637e3d/projects/angular-auth-oidc-client/src/lib/services/oidc.security.service.ts#L107-L111

**Comment by damienbod** [comment]
@john-hi This will be fixed in the next release, within the next few days

Thanks for reporting

Greetings Damien

**Comment by damienbod** [comment]
fixed in 9.0.8

**Comment by damienbod** [comment]
Released in 9.0.8
