### ISSUE TITLE
Promise undefined IE11

### ISSUE THREAD

**Issue by dhameergovind** [damienbod/angular-auth-oidc-client#445]
I am getting "'Promise' is undefined" error on IE 11. Other browsers are fine. It happens on the signin-redirect page after the user manager is returned. Any libraries or pollyfills I can try?

**Comment by damienbod** [comment]
what mode are you using, maybe you could set the meta tag in you index file?

<meta http-equiv="X-UA-Compatible" content="IE=edge" />

maybe these polyfills will help:

import 'ie-shim'; // Internet Explorer 9 support.

import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/weak-map';
import 'core-js/es6/weak-set';
import 'core-js/es6/typed';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

**Comment by funnyuser2** [comment]
> I am getting "'Promise' is undefined" error on IE 11. Other browsers are fine. It happens on the signin-redirect page after the user manager is returned. Any libraries or pollyfills I can try?

so the auto-login in IE works for you?
