### ISSUE TITLE
Expose silent renew running observable

### ISSUE THREAD

**Issue by WoMayr** [damienbod/angular-auth-oidc-client#447]
When first starting the app the auth guard triggers the authorize, even though the silent renew is running.

I expect the auth guard to wait for the renew process to finish (or fail) before deciding to allow activation of the route or trigger the login.

Would it be possible to expose a `Observable<boolean>` over which one can check if the silent renew is running and when it is finished.

As a workaround I implemented a simple OidcSecurityStorage service that emits a value whenever a value gets written to key `storage_silent_renew_running`

**Comment by damienbod** [comment]
@WoMayr we will provide examples  and a fix for this with the version 11 release. Thanks for reporting

Greetings Damien
