### ISSUE TITLE
Silent Renew - Renews Token only once

### ISSUE THREAD

**Issue by juanp3053** [damienbod/angular-auth-oidc-client#448]
Hello,

When I enable silent renew, I can see it checking if the token is expired.
![Screenshot (20)](https://user-images.githubusercontent.com/22222178/58907172-2f390c00-86d3-11e9-87d4-bc72c62db444.png)
It successfully detects when the token expires and I can see it starting the 'silentRenewRunning' session (from the console), it successfully refreshes the token (1st token requested) from the oidc server (I can confirm this from the logs in the oidc server) but once it's renewed, it stops checking if the new token (2nd token requested) is going to expire, the 'silentRenewHeartBeatCheck' indicates that the 'silentRenewRunning' is true even though the token has already been renewed, 
![Screenshot (22)](https://user-images.githubusercontent.com/22222178/58907249-5f80aa80-86d3-11e9-9f3c-095a4eb4ef00.png)
which means it doesn't bother renewing the token (2nd token requested) once again when its expires. Which is the main issue I'm having, is that a normal behavior or something it might only be happening in my case?
 (I am using the 9.0.8 version)

Thanks a lot in advance for the help,

**Comment by damienbod** [comment]
Hi @juanp3053 This happens when the silent renew fails. check what the F12 developer tools, network traffic or console logs report. Either it's blocked iframe or something like this, the STS configuration does not match the client configuration, or  maybe CORS

Greetings Damien

**Comment by juanp3053** [comment]
@damienbod Thanks for the fast response! is it possible that the silent renew fails (without throwing an exception) but what is very weird is that I still get the renewed token in the client so I can still access my APIs? Because that is what happens the first time it tries to auto-renew, no error in the console/network to show that failed, but it just gets stuck in the 'silentRenewRunning' phase. 
![Screenshot (24)_LI](https://user-images.githubusercontent.com/22222178/58914977-82b45580-86e5-11e9-9135-14e686b803a6.jpg)
Also I checked the logs in my token provider and it successfully returns a new token... 

Thanks for you help

**Comment by juanp3053** [comment]
Has anyone else encountered this issue before?

**Comment by juanp3053** [comment]
@damienbod is there a way I can force I silent-renew grammatically?

**Comment by OCATCloudApps** [comment]
Hi Damien,

I also have this issue with the latest version:-

1) Silent renew runs once and the tokens are renewed
2) No errors on the STS console
3) Subsequent checks skip the check for expiry

**Before silent renew compares the timestamp:-**

```
Checking: silentRenewRunning: false id_token: true userData: true
Has id_token expired: false, 1603536078000 > 1603535806261
Has access_token expired: false, 1603535811129 > 1603535806262
silent renew finished!
```

**Timestamps show token expired - Renew works fine and there are no errors on the STS console (IDS4)**

```
Checking: silentRenewRunning: false id_token: true userData: true
Has id_token expired: false, 1603536078000 > 1603535812263
Has access_token expired: true, 1603535811129 > 1603535812263
starting silent renew...
BEGIN refresh session Authorize Iframe renew
RefreshSession created. adding myautostate:  Array [ "f9b21f51375da50cfbdffbfc8a808c6b10MFtZrqx" ]
....
STS server: http://an.ip.address
currentUrl to check auth with:
....
BEGIN authorizedCallback, no auth data
history clean up inactive
Object { id_token: 
....
removed event listener from IFrame
authorizedCallback created, begin token validation
Getting signinkeys from Array [ "http://an.ip.address/.well-known/openid-configuration/jwks" ]
silent renew finished!
```


**Then subsequent silent renews don't check the timestamps**

```
Checking: silentRenewRunning: false id_token: true userData: true
silent renew finished!
```

Why did it do 'removed event listener from IFrame'?

Thanks in advance,
Nigel.

**Comment by OCATCloudApps** [comment]
Hi,

Some more info:-

Silent renew skips checking the timestamps when userData is null.

After subscribing to checkAuth using below code to get user data:-

```
this.oidcSecurityService.userData$.subscribe( 
          userData => {
            console.log('User data', userData);
          }
       );

```

User data is null after first successful silent renew.
User data is null sometimes on refreshing / reloading the app in browser

userData$ cannot always be relied on to emit the user data
This seams to be random

Thanks
Nigel.

**Comment by OCATCloudApps** [comment]
Even more info

The key value for myClientName_storageSilentRenewRunning is not being reset after the tokens are renewed. But manually setting this key value to something other than running makes the silentRenew check the timestamps again.

IE this code doesn't return null anymore and the timestamp evaluation runs:-

```
            const shouldBeExecuted = userDataFromStore && !isSilentRenewRunning && idToken;
            if (!shouldBeExecuted) {
                return of(null);
            }
```

After the refresh In the code (around 2900)

```
            .subscribe(() => {
            this.loggerService.logDebug('silent renew finished!');
            if (this.flowHelper.isCurrentFlowCodeFlowWithRefeshTokens()) {
                this.flowsDataService.resetSilentRenewRunning();
            }
```

resetSilentRenewRunning is not being called so the key value isn't updated from "running"

In the config the default value for useRefreshToken is false. Is this why

`this.flowHelper.isCurrentFlowCodeFlowWithRefeshTokens()`

returns false?

Tried adding the property useRefreshToken: true but this crashes things with the error:-

`ERROR TypeError: this.configurationProvider.openIDConfiguration is null`

**FYI** 

- There are no errors in the browser Console
- There are no errors in browser Network  
- There are no errors from the STS
- We are using version 11.2.1
- Angular 10.2
- rxjs 6.6.3
- Typescript 4.0.3
- Implicit flow (while we test)

Some help on this please would be great
Thanks in advance,
Nigel.
