### ISSUE TITLE
Login Page After Logout 

### ISSUE THREAD

**Issue by jbloem9** [damienbod/angular-auth-oidc-client#449]
Is it possible to some way have the system going to the login page after the user logs out.  Currently I am getting a logout success page and then must click to return to my application.  My application is guarded and it then automatically redirects to the IDS login page.  I would like to skip that middle step.

I am using IDS 3.

**Comment by damienbod** [comment]
In ID4, this is possible, these are just views , don't know about ID3
Greetings Damien

**Comment by jbloem9** [comment]
Thanks Damien, so just to confirm then, this is not something that can be done via this angular-auth-oidc-client package?

**Comment by damienbod** [comment]
yep
