### ISSUE TITLE
Move to HttpClientModule (Angular 4.3+)

### ISSUE THREAD

**Issue by NoMoreLoad** [damienbod/angular-auth-oidc-client#45]
With Angular 4.3 [release](http://angularjs.blogspot.ru/2017/07/angular-43-now-available.html), Angular team was [introduced](https://angular.io/guide/http) new module to work with http requests.
I think it's good to use it.
What do you think about it?

**Comment by damienbod** [comment]
seems really cool, but we would like to support all versions from 4.0 onwards. Maybe after 3 months we could switch and only support Angular 4.3 onwards, both for the moment would like to support all Angular 4 versions. 

Greetings Damien

**Comment by NoMoreLoad** [comment]
Ok, Iclose this issue)
