### ISSUE TITLE
any examples with latest version of the package

### ISSUE THREAD

**Issue by arunprasathv** [damienbod/angular-auth-oidc-client#452]
@damienbod 
In V9.0.8, this method no longer exists, I'm using Azure AD to do implicit flow in angular. 

this.oidcSecurityService.authorizedCallback();  - this method doesn't authorize the user so the SSO goes on in the loop never able come out of SSO. never goes to onAuthorizationResult. 

I tried both without passing hash and with hash.  
this.oidcSecurityService.authorizedImplicitFlowCallback(window.location.hash);

Unsubscribe is also not available. 
this.oidcSecurityService.onModuleSetup.unsubscribe();

Should i use authorizedImplicitFlowCallback without passing any params?  

Finally, I see this error during authorize callback,
 
Access to XMLHttpRequest at 'https://login.microsoftonline.com/{tenant-id}/discovery/v2.0/keys' from origin 'http://localhost:4300' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

Appreciate your help.

**Comment by damienbod** [comment]
@arunprasathv I 'll create an updated example for this

**Comment by arunprasathv** [comment]
@damienbod now the issue is CORS, working on it. have you seen a similar issue?

**Comment by damienbod** [comment]
https://github.com/damienbod/dotnet-template-angular/tree/master/dotnet-angular-azure-ad-oidc

The link is a working example. The CORS problem is solved using a backend proxy

Greetings Damien

**Comment by arunprasathv** [comment]
@damienbod  backend proxy -  is that on IIS server, can you pls point me to the code.

**Comment by damienbod** [comment]
https://github.com/damienbod/dotnet-template-angular/blob/master/dotnet-angular-azure-ad-oidc/Controllers/ConfigController.cs

I use this to get the well known end points and the jwt json files. Rest works directly from javascript.

**Comment by arunprasathv** [comment]
Got it. But I need to implement everything on the client side, I don't have a .Net backend.

**Comment by damienbod** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#get-access-tokens

AAD does not support CORS so you need a backend if you want to use OIDC. Either you use a backend of some type, put a STS in between and use AAD indirect, or you don't use a standard which I would not recommend. 

If you could use the AAD indirect, for example put IdentityServer4 in between, then you can use OIDC Code flow with PKCE, federate to AAD and also control the claims in the tokens with ease.

**Comment by arunprasathv** [comment]
I think I can get it working with the MSAL library.  I could get the ID Token.  Working on to get Access Token and call graph api through grap client library.  '@microsoft/microsoft-graph-client - library to talk to graph api. Implicit Flow should work 100 % in the browser is what my understanding.

**Comment by damienbod** [comment]
MSAL has some type of non standard workaround for the CORS thing, will look into the src to see how this avoids the CORS problem from the AAD server.
