### ISSUE TITLE
Getting an error message when adding the package

### ISSUE THREAD

**Issue by yoelhor** [damienbod/angular-auth-oidc-client#456]
Uncaught TypeError: Object(...) is not a function
    at angular-auth-oidc-client.js:198
    at Module../node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js (angular-auth-oidc-client.js:200)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap:78)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:78)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)

**package.json**
{
  "name": "my-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "angular-auth-oidc-client": "10.0.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.8.26",
    "jsrsasign": "8.0.12"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.5",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}

**Comment by FabianGosebrink** [comment]
Hey, 

so what did you do? Did you `npm install` and then the message appeared? Or at runtime?

**Comment by vnabet** [comment]
Same message, here, at runtime, with angular 7 too.
I downgrade the package to 9.0.8 and it work fine now.

**Comment by FabianGosebrink** [comment]
@yoelhor @vnabet do you have a repo to reproduce the issue?

**Comment by yoelhor** [comment]
I wanted to thank you for all of your assistance. I updated the angular using the `npm install -g @angular/cli` command, which solved the issue.
