### ISSUE TITLE
Error in Url parsing

### ISSUE THREAD

**Issue by PartyArk** [damienbod/angular-auth-oidc-client#458]
Hi, there's a small but pernicious bug in the way you are parsing callback urls when using code flow. It's triggered because the return url I get when signing in from Google (depending on the account) is in this format:

`https://www.example.com/signin?code=ABABABABA...&state=0000.1234.000#`

You'll immediately note the fragment identifier at the end, which should not be part of the parsed state parameter.

The 'state' here is correctly 0000.1234.000 - 
```
var url= new URL("https://www.example.com/signin?code=foo&state=0000.1234.000#");
url.searchParams.get('state'); //0000.1234.000
```

.... but your code will get it as 0000.1234.000# and cause authentication to fail for me. 

The bug is caused by the numerous use of -

```
      const urlParts = urlToCheck.split('?');
      const params = new HttpParams({
            fromString: urlParts[1],
        });
```
 
... which is not quite doing what it should. A quick fix would be:

```
      const params = new HttpParams({
            fromString: new URL(urlToCheck).search.substring(1)
      });
```
But note that IE11 requires a URL polyfill.

**WORKAROUND** in case anyone else comes across this - 

```
        const href = window.location.origin + window.location.pathname + window.location.search;
        this.oidcSecurityService.authorizedCallbackWithCode(href);
```

Thank you!

**Comment by damienbod** [comment]
released 10.0.6
