### ISSUE TITLE
Issue in executing the project

### ISSUE THREAD

**Issue by shwetashukla** [damienbod/angular-auth-oidc-client#459]
Hi

**My application is angular 7 , I used the latest version 10 I got the error**

angular-auth-oidc-client.js:198 Uncaught TypeError: Object(...) is not a function
    at angular-auth-oidc-client.js:198
    at Module../node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js (angular-auth-oidc-client.js:200)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap:78)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:78)
    at Object.0 (request-action-model.ts:5)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)
(anonymous) @ angular-auth-oidc-client.js:198
./node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js @ angular-auth-oidc-client.js:200
__webpack_require__ @ bootstrap:78
./src/app/app.module.ts @ app.component.ts:8
__webpack_require__ @ bootstrap:78
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:78
0 @ request-action-model.ts:5
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
client:148 [WDS] Warnings while compiling.
warnings @ client:148
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js 198:58-76
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js 319:63-81
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js 198:154-162
"export 'ɵɵinject' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js 319:169-177
"export 'ɵɵinject' was not found in '@angular/core'

**I downgraded to 9 it is giving error**
ERROR in src/app/app.module.ts(35,19): error TS2304: Cannot find name 'OpenIdConfiguration'.
src/app/app.module.ts(59,11): error TS2739: Type '{ issuer: string; authorization_endpoint: string; token_endpoint: string; userinfo_endpoint: string; end_session_endpoint: string; check_session_iframe: string; revocation_endpoint: string; introspection_endpoint: string; }' is missing the following properties from type 'AuthWellKnownEndpoints': jwks_uri, setWellKnownEndpoints

**Comment by damienbod** [comment]
Here's the 9.0.8 documentation

https://github.com/damienbod/angular-auth-oidc-client/tree/relase_9_0_8

This seems strange that Angular 7 has problems with this. I have moved all my projects to 8. I'll look into this

Greetings Damien

**Comment by damienbod** [comment]
@shwetashukla fixed in version 10.0.1
