### ISSUE TITLE
[SSR] Session storage is not defined

### ISSUE THREAD

**Issue by xalhera** [damienbod/angular-auth-oidc-client#461]
Hi @damienbod,

I noticed a bug from release v10.0.0, in the file auth.configuration.provider.ts line 33.

This was fixed previously here : #252 

Could you please replace
`storage: sessionStorage,`
with
`storage: typeof Storage !== 'undefined' ? sessionStorage : null,`

Thanks a lot

**Comment by damienbod** [comment]
released 10.0.2
