### ISSUE TITLE
onConfigurationLoaded does not fired

### ISSUE THREAD

**Issue by xalhera** [damienbod/angular-auth-oidc-client#462]
Hi @damienbod,

Before release v10.0.0, I could suscribe to onConfigurationLoaded to detect when my STS Server configuration was loaded and then users could try to log in.

But since I upgraded to the last release, this doesn't work anymore :'(

**Comment by damienbod** [comment]
Ups, sorry, when made a big change to the startup configuration, to make it more angular style. This got broken then. Will have a look at this as soon as possible. If you know how to fix, send a PR please

Greetings Damien

**Comment by damienbod** [comment]
released 10.0.2
