### ISSUE TITLE
code, id_token, token for background API access

### ISSUE THREAD

**Issue by jamesikanos** [damienbod/angular-auth-oidc-client#465]
Google Sign-In supports a flow whereby both a SPA and back-end API (separate server URLs) can get access to a token. This allows for an API to do "google things" on behalf of the user even after the SPA has been closed.

This Google article shows an example of how this could work: https://developers.google.com/identity/sign-in/web/server-side-flow.

However, when I try a response_type of "code id_token token", there are errors. My theory is that the "id_token token" should be used by the SPA and the "code" passed to the API to exchange for a long-lived token (with refresh_token support).

How can this be achieved?

I'd like both my API and SPA to talk to an external resource (ie: they both need an access token).

I'm not using an MVC app so Issue #131 is not appropriate.

Many thanks.

**Comment by damienbod** [comment]
code id_token token should be used with server rendered applications.
