### ISSUE TITLE
Silen Renew: Incorrect nonce

### ISSUE THREAD

**Issue by marcBalta** [damienbod/angular-auth-oidc-client#471]
Hello,

Im using relase_9_0_8 with the implicit flow. And because I dont want to have reloading the app when the redirect is started I use a special callback.html running within an hidden iframe which sets the received hash from the STS to local storage : 

localStorage.setItem("hash", window.location.hash);

In the angular app itself there is a periodically running routine which checks for the localstorage item and then calls authorizedImplicitFlowCallback(hash).

Thats all working fine. The problems began however when I switched on the silent renew feature. I know that the error message incorrect nonce is caused when the authorize function is called twice. The image below show this. At first authorize is called by my own callback handling and then it is called by the silent renew (with prompt = none). What is here the correct way to solve this? When I switch off calling authorize from my callback then there is just the prompt =none authorize call which is however insuficient for the initial authorization, right? 

![image](https://user-images.githubusercontent.com/36480965/61035352-4d2b1800-a3c7-11e9-9907-9ce377c64aef.png)

Thx in advance and Greetings,
Marc

**Comment by marcBalta** [comment]
I fixed it by a workaround. I renamed the event inside silent-renew.html and catching it on my own. Then I check if the user is already authorized and only if this is the case I forward the event with its original name to angular-auth-oidc-client. 

My advice is to implement this check into angular-auth-oidc-client.

**Comment by damienbod** [comment]
@marcBalta PR?
