### ISSUE TITLE
authorizedCallbackWithCode() failure question

### ISSUE THREAD

**Issue by djkiwe** [damienbod/angular-auth-oidc-client#473]
This is more a question about some strange behavior rather than an issue I think.
I'm implementing auto-login with the following code:
```
ngAfterViewInit() {
    if (this.oidcSecurityService.moduleSetup) {
      this.onOidcModuleSetup();
    } else {
      this.oidcSecurityService.onModuleSetup.subscribe(() => {
        this.onOidcModuleSetup();
      });
    }
  }

  private onOidcModuleSetup() {
    this.oidcSecurityService.getIsAuthorized().subscribe((signedIn: boolean) => {
      if (!signedIn) {
        this.router.navigate(['/auto-login']);
        // return this.oidcSecurityService.authorize();
      }
      // else redirect to main app
    });
  }
```
What happens is that if I call the `authorize()` method from inside the `getIsAuthorized()` subscription, the callback fails with a code challenge validation error from the sts server. But if I redirect to another component which then calls the authorization method, everything works as expected. 

Any idea why this happens? Does it have to do with asynchronous behavior?

**Comment by damienbod** [comment]
This has been refactored and changed in verison 11 which we plan to release in the next few days after testing

Greetings Damien
