### ISSUE TITLE
Refresh IdToken without IdServer Cookies

### ISSUE THREAD

**Issue by rengert** [damienbod/angular-auth-oidc-client#475]
My application is running in an environment where the cookies are not allow to be accessed. I am using grandtype code, with refresh tokens i guess. Is there a way using it without the normal silent refresh, because it is using the authorize endpoint telling me i need to login. But having the refresh token their should be no reason for it or are we wrong?

**Comment by damienbod** [comment]
@rengert yes, you can just turn off the silent renew
