### ISSUE TITLE
redirect_url mismatch

### ISSUE THREAD

**Issue by twmobius** [damienbod/angular-auth-oidc-client#476]
First off let me thank you for your time building and maintaining this module. 

I've been using implicit flow with `silent_renew: false` for some time now but recently I've tried to change the client to use `code PCKE flow` with `silent_renew: true` but it seems that something is wrong.

Here is what I'm doing. 

First off this is the configuration used:

```
export function loadConfig(oidcConfigService: OidcConfigService) {
  return () => oidcConfigService.load_using_stsServer(environment.server);
}

@NgModule({
  imports: [
    SharedModule,
    RouterModule.forChild([
      {
        path: 'login',
        component: LoginComponent
      },
      {
        path: 'login/unauthorized',
        component: UnauthorizedComponent
      },
      {
        path: 'login/forbidden',
        component: ForbiddenComponent
      },
      {
        path: '',
        component: LoginComponent
      }
    ]),
    AuthModule.forRoot(),
  ],
  declarations: [
    LoginComponent,
    UnauthorizedComponent,
    ForbiddenComponent
  ],
  providers: [
    OidcConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: loadConfig,
      deps: [OidcConfigService],
      multi: true,
    },
  ],
})
export class AuthenticationModule {
  constructor(
    private oidcSecurityService: OidcSecurityService,
    private oidcConfigService: OidcConfigService,
  ) {
    const location = window.location;

    this.oidcConfigService.onConfigurationLoaded.subscribe((configResult: ConfigResult) =>{
      const config: OpenIdConfiguration = {
        stsServer: environment.server,
        redirect_url: 'http://localhost:4200/login',

        client_id: environment.clientId,
        response_type: 'code',
        scope: 'openid email profile telephone address',

        post_logout_redirect_uri: `${location.protocol}//${location.hostname}/login`,
        forbidden_route: '/login/unauthorized',
        unauthorized_route: '/login/unauthorized',

        start_checksession: false,
        silent_renew: true,
        silent_renew_url: `${location.protocol}//${location.hostname}/assets/silent-renew.html`,

        log_console_warning_active: true,
        log_console_debug_active : true,
        max_id_token_iat_offset_allowed_in_seconds : 100
      };

      this.oidcSecurityService.setupModule(config, configResult.authWellknownEndpoints);
    });
  }
}

```

I've build a AuthGuard that checks if the user is authenticated and if not it redirects to route `/login`. 

The matching component `LoginComponent` is somewhat like this:

```
@Component({
  selector: 'app-login-component',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit {
  constructor(
    private securityService: OidcSecurityService,
    private store: Store<fromStore.State>,
    private router: Router,
    private logger: NGXLogger
  ) {
    if (this.securityService.moduleSetup) {
      this.doCallbackLogicIfRequired();
    } else {
      this.securityService.onModuleSetup.subscribe(() => {
        this.doCallbackLogicIfRequired();
      });
    }
  }

  ngOnInit(): void {
    this.securityService.getIsAuthorized().subscribe(auth => {
      this.logger.debug('Authentication result:', auth);
    });

    this.securityService.getUserData().subscribe(userData => {
      if ( userData && typeof userData.sub !== 'undefined' ) {
        // We complete the login at this point

        // Saves the user state 

        this.handleRedirectAfterLogin();
      }
    });
  }

  public login() {
    this.securityService.authorize();
  }

  private doCallbackLogicIfRequired() {
    this.securityService.authorizedCallbackWithCode(window.location.toString());
  }

  private handleRedirectAfterLogin() {
    // redirect after successful login
  }
```

I've added the `silent-renew.html` to the `/assets` directory of the app which contains:

```
<script>
  window.onload = function () {
    const parent = window.parent;
    const event = new CustomEvent('oidc-silent-renew-message', { detail: window.location });
    parent.dispatchEvent(event);
  };
</script>
```

What happens next is the following:

1. The app connects and retrieves the `.well-known/openid-configuration` file. 

2. Calls the `authorization_endpoint` from the .well-known with `redirect_uri: http://localhost:4200/assets/silent-renew.html`.

3. The oauth server redirects back to the silent-renew.html passing code and state: `http://localhost:4200/silent-renew.html?code=...&state=...`

4. The app performs a `POST` to the `token_endpoint` with the code received on step 3 but this time the redirect_url is `http://localhost:4200/login` and the `code_verifier` is empty which I think is also wrong

5. The server replies back with 400 `redirect_uri_mismatch` because the original code created had a different redirect_url than the one on the `token_endpoint` request according to http://tools.ietf.org/html/rfc6749#section-4.1.3

I'm feeling that I'm definately doing something wrong here but I cannot put my finger to it. For instance the `this.securityService.authorize()` is never actually called but yet the whole login process starts when the user is being redirected to the `/login` route

Any help would be much appreciated

**Comment by damienbod** [comment]
@twmobius I think the guard is causing the problem here. Make sure it does not execute on the silent renew redirect URI. The guard should only be used on the protected routes, and not the default routes.

Greetings Damien

**Comment by twmobius** [comment]
@damienbod Thanks for the reply. No, it's not the guard, since the silent-renew.html is not served via an angular route, but it's a static file on the /assets directory.

**Comment by castrinho** [comment]
@twmobius Hi, have you found a solution for this? I'm facing the same problem when using the silent renew. I also get the redirect_uri_mismatch. Have tried to find what I am doing wrong but without success.

**Comment by twmobius** [comment]
@castrinho No, not really. I've rolled back to the `id_token token` flow for now but I intend on looking further into this in the future

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
