### ISSUE TITLE
getIsAuthorized() executing before authorize() call is finalized in some cases

### ISSUE THREAD

**Issue by Talark** [damienbod/angular-auth-oidc-client#481]
In my authorization guard if getIsAuthorized returns true I allow route activation, if false I redirect to auto login component, this was working with the identity server hosted locally. Once Identity server was deployed, now after the login is succeeded I'm stuck in a loop, because getIsAuthorized() is always returning false. I'm using the code flow.

**Comment by damienbod** [comment]
You should only apply the guard to the routes you want to protect, not the whole application. remove it from the route which processes the authorization response.

Greetings Damien

**Comment by Talark** [comment]
I need the authenticated user data in the shared layout component that is the parent component for many other routes:
     {
        path: 'shared',
        component: SharedLayout,
        canActivate: [AuthorizationGuard],
        resolve: { userData: AuthUserResolverService },
        children: [{
            path: 'site',
            loadChildren: './site.module#SiteModule'
         }]
    }
My redirect url component also has a guard on it, the auto-login component is the only one that does not have guard on it in my application.
How can I make the getIsAuthorized in my auth guard to return true before redirecting to the auto-login component (this is where I'm stuck in the loop) in my case?

**Comment by dozer75** [comment]
The url that you have defined as `redirect_url` cannot be under any guards. Alternative that your AuthorizationGuard checks if it contains `code` as query string/hash parameter and if it does allows it to go through for completion of the authentication sequence.

**Comment by speedy32** [comment]
Just add another empty unguarded component lilke callback

**Comment by Veronika-R** [comment]
i guess it is because of this changes https://github.com/damienbod/angular-auth-oidc-client/commit/1e10d4a2bb29ac5a7767ba9c411f0af1657bfd0a#r38187640

**Comment by FabianGosebrink** [comment]
Fixed in version 11
