### ISSUE TITLE
Validate_id_token_nonce failed, dataIdToken.nonce: undefined local_nonce

### ISSUE THREAD

**Issue by JohnGalt1717** [damienbod/angular-auth-oidc-client#484]
Hi, I'm working on upgrading our stuff from 9.x to 10.x and also updating to PKCE.

We're getting the above error and I'm at a loss as to why on oidcSecurityService.authorizedCallbckWithCode(window.location);

This calls our connect/token endpoint which passes through fine and gets a response with scope, token_type, access_token, expires_in, refresh_token, id_token, .issued, .expires, as:client_id.

One would think based on the error that this is some validation nonce that isn't being stored somewhere?

**Comment by damienbod** [comment]
Hi @JohnGalt1717 

need some more info, have you compare the code to the examples? when the request is sent, a nonce is stored to the storage you use, and after a successful authorization, the nonce is returned in the callback and validated.

Greetings Damien

**Comment by JohnGalt1717** [comment]
Here's the request to the api server:

https://localhost:44301/connect/authorize?client_id=Portal&redirect_uri=https%3A%2F%2Flocalhost%3A5002%2Fsilent-renew.html&response_type=code&scope=openid%20profile%20email&nonce=N0.9771518013607751566490284088&state=15664902840880.91972818661509130.4779767967387516&code_challenge=C_djOI8d14nvKOzoBFdZraxtxuselI2IiYwfajsdKYw&code_challenge_method=S256

Here's the call back response:

https://localhost:5002/silent-renew.html?code=CfDJ8FHnGh0iaHRHhXGx7Bzb-C3K5iCaE9wrP0ky1mbNXhsZ0xCbJoU8WI6abYbgh63wbpurpsy6s4rQ9aXAh7kcOe9OOz654wrsChUdmv5iiQ3-KlGpfYc56bRCTOTlxcznUHpbnQ9o9SOgRizGecFFkfzn1FS_mkPW1y61CiVK3P54wlCY7vSPrOZwqJVKqSBec9tr1cu3s2TOJxp57LdgfWAKsIfA_3im1DOd2ovF9V9OOW600xkhjAfAcqk01gvTDktHCq6RfKZgfJtO8KDMQe1z1VNy3roH7CN2ydYrkAVfos-ErVMQjgdDnUv8UAX-HyWKXogVvoA7wB7MfElZ2FwNaBdGNBjAxyExyjdSghCskSAMvghR0WrcFrgujBgdG6usguccQ1MRsVgrJBXOnEqIOQ2YFNIxmnPsGjXZyAdriJPq7vIQktl9B-aLILre8ErhkOYaLUMTXgAz3F4rItwnh9fgbJu0wpAjxG9l5hu00MAF30__XCeBHY_TBEgz1guYlmeNq5dEgD8Xm558-I_QVfOFOqMvGmhHDorYIweFKRnvYc7PT0YO0anClayIiDQqf-GUV-N1ohczDtAgM_Ql_XIISMwrmKqj4ewE6ZLlSZIqplQkZ7hZSuNjKjNVZ1CgOU8DockxDHjmKztjulxTdz2FE72FqC8L-RRdZzr8aZbAWwakNTosdaKDaOqHqiD0lvSua4vxJsKRfh-SOtU-QMScRUZcqhU80XS636VIj5Bi-CWwU5jAeSkvW5NViW-6SAHOju_k2k_QotAg3ijZP5zC-9tIyJmRqdD_d_tC6ukon0pPZV9kSxNhj5Cj_tM-9KIhonoPFKLCKmWFT8I-1Ps1RMsbKHAhzG_NSQkcodE-zPfBfE9XSjYZturtN7t2mQSQKPzgEFMK9ACMq_6JOwq0iKZunaSZxfXLc6y-tDliB5A3QfZfBF-8kiY9i4cuwBjobOB4BeK_yfSY6_5AO88i8ykm8z2lOxABvyhW13GjvAa_B11pDluLWZxHUO_-eXjubHwwUeBZk4OBHBwK8iKI5HbvcR3lEaJX4zExSeZG2us5jSJc9cKLAEVMdAHX_PNJwfw8--YAaT0cQ1w99kIm6yakDCBVcZhdOrHGawVzZpsiFuokdWZ2S1QgMBxv7GoR75BDtDq0MHVvQUCSV_Pq_L_jZQWP8i2wl_CJVJcK7Nbf4XlMoPRgFLrUGCQiYR4XS8u8kZwrr1Bg1f_CV5hod3Cqf6jbxRMBOBqEmFgrMjrM-d8v_UBbF-A7OMaVQHi8coooYsOwdmHQdtUWk2-bd7u6ucM-R_EhmEbWKkd4U68LX0t-a0PpzOj_5rYNmYgWaNAfb4HjAcSVIJEzL519S6PyIdArVB2v3a1wXXinJ-nNwGDPGTE_dGqOOp9LUWEUe_UFnep7ddFmUvNU4jEjo1I3Gql4pCTRYr33EsknQ3NQ__DmaeOIuq8FdJdsfIQxtftPlGOUyRf906t1Sc980UxIDIPlTd2jm_op6uh0osGgQPThz4l2vyGJ6ZZJjxnh4tvxD2V7kauPRoljhdS0SprxK2dpv7mcq0bERm_I7RSrpF3FLYH3_fjfVHNTM0zKx_luXXIvLjTEKrQX6QgUu26ogh66uAR1sM_3QWf0-ThsHWaJItJ6FStAd3o978Sq052gXX9oTQnbBXxEUcmP-VW0O2c1x-hSJh9GMH9CzLyi1b91FHGt1c-KCvZW1HKSEnbIlESus1EE86jVKF6NBZONmykD5WcpLAq-lpf_Xe4CsZongVgXnzkxR124mgZ88-GFTRMOK5QSXwk9C9OTiY4scYbLJ1SV73nHHJ3E3-uKvT4cwjLqpJsitbI9XdKTPkxOZianBAMnLlzDGitZ9YHEuFi_zStj8AASD6Yqdd-PdxR5wA80up9rHh7R9MOmZtFJ0HbPU0X_3GWOuutuJCBT1iawvrX4dANwvnnrcV2p7-SQhooZG2hHxBxo6q9hj7K-2BqYa1aFTJFx9tb2ns6m3FtSpGbSvZoZeHjlypFJFUoPl0yBeFlGJzBIZG8omgQ1TOUnvfcVM4ZQmz8pW1XoRwFky71LleJyzhVxdx3bhVANEF5z8g6KBi6d1FCIHerTs4BMETSnj9Jvj9MzPgVqbEfLB2I6rAt2iayHqpCbgN-IfqqNM90NpalBJyyQf5MmgdbB7BfIVUfG1EKKTYPbTZb-FT630Us6-Dp6Nrm_UCyZlqyovRcUD-eQajePjUKlyzIkuteEgLpfmf7sxvm_78mNEMs15zAzLEd6iX__s91ctPIA9HPYTe2jFbXCoelFJqeB0qt-smajQ_XOL3PiSL-T9MO63c4D2mFMFZs1htqg1STlmgJugPey-nvg9cnMl8HWxf6Gyfz8DmNDq2pHzuvquv-eWgLqqGZCXkR3sDsKeq6fXbja9kbin3jOsP84jGJFVhSN3ynxQ3NWVElmFiUKnbNm8_3XeBdaJetU3PkuK8ZnD63Xw51egDQFTfBxErvMItV9j2eYyn0a5S_0E7tboCm15A64eFPhSkZa29D60WVIsZLo9FuRCYLjr9iOV7hyYzwtLMmKc65rxhIpd2oqwtizmaCu8aAlKCG5L7m3tb7Q1wBick3lbAhm6nBFci4AQKYgVoOMkYARzSVcFkbqgnwEWVxtu4JREqi9Z-SaM1LK_Q-XmapCtO9NJm9lbHz6sEkqKrU14dSLAAuULOInCct-mdWf&state=15664902840880.91972818661509130.4779767967387516


It doesn't try anything after that and just fails with the above error.

**Comment by JohnGalt1717** [comment]
I figured this out. It was OpenIDConnect.Server not returning the Nonce that was sent to it.

**Comment by tiagopsantos** [comment]
Or add the config: ignoreNonceAfterRefresh : true,
