### ISSUE TITLE
post_logout_redirect not happening

### ISSUE THREAD

**Issue by Jonesie** [damienbod/angular-auth-oidc-client#486]
Im really not sure if this is a client issue or Identity Server - maybe the later - but I dont want to get my head bitten off with them so thought I'd ask here first :)

ID server has both redirect and post logout redirect url set to http://localhost:4200 but when I logout from my ng app, it stops on the ID server login and does not bounce me back.  

Im using the latest client code - 10.0.3 and ng 8.1.  

``` js
logout() {
    this.isAuthorizedSubscription.unsubscribe();
    this.isLogingOut = true;
    this.oidcSecurityService.logoff();
  }
```

``` json
  "ClientAppSettings": {
    "stsServer": "http://localhost:5002",
    "redirect_url": "http://localhost:4200",
    "client_id": "client.js",
    "response_type": "id_token token",
    "scope": "openid profile api.v1 payment.api.v1",
    "post_logout_redirect_uri": "http://localhost:4200",
    "start_checksession": true,
    "silent_renew": true,
    "silent_renew_url": "http://localhost:4200/assets/silentrenew.html",
    "startup_route": "/",
    "forbidden_route": "/forbidden",
    "unauthorized_route": "/unauthorized",
    "log_console_warning_active": true,
    "log_console_debug_active": true,
    "max_id_token_iat_offset_allowed_in_seconds": 10,
    "apiServer": "http://localhost:5001/"
  },
```
Any clues or easy to understand samples?

Thanks

**Comment by damienbod** [comment]
@Jonesie Yes this is a IdentityServer4 thing, you need to do some checks in the account controller, views. The URL has to exactly match the sent post redirect URL. Also you can change the controller view logic in your identity server 4 to redirect directly back to the Angular App without clicking the link. Add a breakpoint to the controller methods, and you'll see what's happening.

Also maybe you should use HTTPS for development as well. Angulat-CLI supports this good, and then you can add the things to block http requests.

Greetings Damien
