### ISSUE TITLE
Is it possible to set response_mode parameter?

### ISSUE THREAD

**Issue by ngRevan** [damienbod/angular-auth-oidc-client#490]
Hello there

Is it possible to set the response_mode parameter as specified [here](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes)?
I would like to use OpenID Connect with ADFS 2016 as described in this [blog post](https://medium.com/the-new-control-plane/the-mystery-of-the-missing-adfs-jwt-claims-7658d9cdeaac).

Thanks in advance for your help.

**Comment by damienbod** [comment]
@ngRevan 

Yes this is possible, but I have never tested if it is possible to handle the response from this authorization request then.

Greetings Damien
