### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Maikell84** [damienbod/angular-auth-oidc-client#495]
The documentation for `authorizedcallback()` is wrong. [(link)]( https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#authorizedcallback) 

There is no such function in the whole project.

**Comment by damienbod** [comment]
thanks, I fix this

**Comment by damienbod** [comment]
fixed, thanks for reporting
