### ISSUE TITLE
Silent Renew Session Expired Error Not Thrown

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#497]
Hi,

I was testing the case in which for w.e reason the single sign on session get expired and silent_renew is still running. I expected that sometype of error would be passed to me saying that I need to log in. Though this does not seem to be the case, instead it just seems like nothing really happens until i try refreshing the page, I am kicked back to my login page (but this is because of my Angular Guard)

Test case:

Log in to app with token exp set to 2 mins.

In another tab open the authorization server and log out.

Let silent-renew gets triggered.

Actual Result: Nothing happens no errors come up.

Expected Result: Error thrown saying that the user needs to log in, so I could instruct the user to do so.

**Comment by damienbod** [comment]
You should see an error in the console logs

**Comment by JoellyR** [comment]
@damienbod  is there any function in the library that i can use to hook on to this error so I could do something with it?

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
