### ISSUE TITLE
Bad request when calling authorizedCallbackWithCode()

### ISSUE THREAD

**Issue by Maikell84** [damienbod/angular-auth-oidc-client#498]
I have a problem implementing the library and I'm not sure if it is a bug or if I'm doing it wrong.
I am using **Angular 8.2.4** on client side with version 10.0.6 of this library , and an **Identity Server 4** with code-flow as authorization server.

After successfully logging in at the server, I get correctly redirected to my configured angular-route. Here I have created a component, which handles the callback. This unfortunately is not working.

```
// Redirect Component
public ngOnInit(): void {
    this.authorizationService
        .getOidcClientReady()
        .pipe(
            take(1),
            switchMap(() => {
                return this.oidcSecurityService.getIsAuthorized();
            }),
            distinctUntilChanged(),
            filter(isAuthorized => !isAuthorized),
            takeUntil(this.isDestroyed$),
        )
        .subscribe(() => {
            // If we are not authorized, we must call authorizedCallbackWithCode()-function with code, state and session_state params from url.
            // If params are valid, onAuthorizationResult-Observable will fire, where we perform the loading of the user-object
            this.oidcSecurityService.authorizedCallbackWithCode(window.location.toString());
        });
}
```

`getOidcClientReady()` is an own function that emits, as soon as the library is setup and the configuration is loaded.

My app module looks like this:

```
export class AppModule {
    constructor(private oidcSecurityService: OidcSecurityService, private oidcConfigService: OidcConfigService, private router: Router) {
        this.oidcConfigService.onConfigurationLoaded.subscribe((configResult: ConfigResult) => {
            const config: OpenIdConfiguration = {
                stsServer: configResult.customConfig.stsServer,
                redirect_url: window.location.origin + '/admin/#/redirectLogin',
                client_id: 'myClientId',
                scope: 'openid profile email IdentityServerApi offline_access',
                response_type: 'code',
                silent_renew: true,
                storage: localStorage,
                silent_renew_url: window.location.origin + '/admin/assets/staticSites/silent-renew.html', // Static iframe, that handles silent refresh events
                log_console_warning_active: true, 
                log_console_debug_active: true,
                auto_userinfo: true,
                trigger_authorization_result_event: true, 
            };

            try {
                this.oidcSecurityService.setupModule(config, configResult.authWellknownEndpoints);
            } catch (error) {
                this.router.navigate(['/notAuthorized'], { queryParams: { error: error } });
            }
        });
    }
}
```

As soon as **authorizedCallbackWithCode()** is called, an error occurs. 
The "Bad Request" is happening, because the library sends an empty "**code_verifier**" to the server. See screenshot. Here is the console.log:

**Console Output**
```
STS server: /.well-known/openid-configuration
Silent Renew is active, check if token in storage is active
<iframe id=​"myiFrameForSilentRenew" style=​"display:​ none;​">​…​</iframe>​
IsAuthorizedRace: Timeout reached. Emitting.
angular-auth-oidc-client.js:334 IsAuthorizedRace: Completed
angular-auth-oidc-client.js:334 getIsAuthorized: false
POST http://localhost:5000/connect/token 400 (Bad Request)
angular-auth-oidc-client.js:317 Error: invalid_grant
    at HttpConfigInterceptor.handleHTTPError (authInterceptor.ts:128)
    at CatchSubscriber.selector (authInterceptor.ts:62)
    at CatchSubscriber.error (catchError.js:29)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at XMLHttpRequest.onLoad (http.js:2466)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39679)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
```

![bad request](https://user-images.githubusercontent.com/12297422/64670888-ee395c00-d466-11e9-9198-c8e25974badd.png)

**When I turn `silent_renew` to false, everything works properly. However in this case I am not able to refresh my tokens.** 

So my questions are:
- Is there something wrong with my code, or with the library code?
- Can I make a workaround? E.g. not use silent_renew but refresh the tokens manually?

**Comment by elwray** [comment]
Hi to everyone. Faced with the same issue. The error occurs for the following reason:
1. We have OpenIdConfiguration with the "https://site.local/callback" redirect_url and "https://site.local/silent-renew.html" silent_renew_url.
2. oidcConfigService.authorize() method generate link for us (with return_url="https://site.local/callback") and redirects browser.
3. After successful login we should return to "https://site.local/callback" url.
4. After that we should exchange our code on two tokens (identity token and access token).
5. And in the requestTokensWithCodeProcedure method I have found some strange code:

```
let data = `grant_type=authorization_code&client_id=${this.configurationProvider.openIDConfiguration.client_id}` +
           `&code_verifier=${this.oidcSecurityCommon.code_verifier}&code=${code}&redirect_uri=${this.configurationProvider.openIDConfiguration.redirect_url}`;
if (this.oidcSecurityCommon.silentRenewRunning === 'running') {
    data = `grant_type=authorization_code&client_id=${this.configurationProvider.openIDConfiguration.client_id}` +
           `&code_verifier=${this.oidcSecurityCommon.code_verifier}&code=${code}&redirect_uri=${this.configurationProvider.openIDConfiguration.silent_renew_url}`;
}
```
7. If we turned on silent_renew to true and now running silent renew process we changing redirect_url to "https://site.local/silent-renew.html". Redirect to other url (in our case we should redirect to "https://site.local/callback") causes Bad Request on IdentityServer.

**Comment by AnonymusRaccoon** [comment]
Any update on this? The bug occured for me today and not having silent refresh with code flow is a bit troublesome. I found out that it happens on Identity Server because they check that the redirect_uri given at the authentification endpoint matches the redirect_uri given at the token endpoint but angular-auth-oidc-client send the ```redirect_url``` var to the authentification endpoint and the ```silent_renew_url``` to the token endpoint.

**Comment by AnonymusRaccoon** [comment]
@damienbod Any news on this?

**Comment by serge-wq** [comment]
@AnonymusRaccoon I think it has to do with the IsAuthorized race that occurs in the library setup. This race sets authNonce to an empty character string if it does not get any authorization results. If the login page is inside the SPA then the authNonce is empty when the application is redirected to the callback page, which triggers the silent-renew to try to refresh the session and causing a kind of race condition in IdentityServer.

**Comment by junyuan** [comment]
I'm not sure if this is same issue I met in #483. But my second failed request's response is 400 and  `invalid_grant` as well
