### ISSUE TITLE
Not able to build angular app

### ISSUE THREAD

**Issue by samrules** [damienbod/angular-auth-oidc-client#500]
I have imported the package and I am trying to build my angular app. 

It has started giving me build errors stating incorrect syntax in auth-conifguration.provider.d.ts

Any help, is appreciated.

![image](https://user-images.githubusercontent.com/973258/64955784-0b17ca00-d881-11e9-83fa-49eae312e816.png)

See attached image.

**Comment by damienbod** [comment]
Hi @samrules don't understand this, are you  using the files directly?
