### ISSUE TITLE
Code Flow Authorize -> Token Problem missing client secret

### ISSUE THREAD

**Issue by Ylvur** [damienbod/angular-auth-oidc-client#502]
Hi!

I´m using authorization_code.
The authorize request goes well. The following call to issue a token from Identity Server 3 does not work. Resulting in a an error: Bad request. 

The problem is that connect/token request requires a client secret to work and it is not 
possible to add that in OpenIdConfiguration set up. 

I can issue a token from postman with the same data but adding client secret (code, codeverifier and all the other stuff).

Is there any way around this or is it possible to add client secret to OpenIdConfiguration interface.

Thanks.

**Comment by damienbod** [comment]
The angular app does not use a secret because it cannot be trusted. So you can use the implicit flow, or switch to ID4

hope this helps 

Greetings Damien
