### ISSUE TITLE
Add an option to revoke the Access Token On Signout

### ISSUE THREAD

**Issue by djosemartine** [damienbod/angular-auth-oidc-client#504]
It would be nice to have and option to automatically revoke the reference access token when an user signs out

**Comment by davebaol** [comment]
This might be a useful feature, however you can revoke access token from inside the callback passed to logoff.
It works like a charm for me, see https://github.com/davebaol/oidc-angular-wso2is/blob/94d000cbfcd3c9d79cabd0a566e43f8b91541553/src/app/core/auth/auth.service.ts#L179

**Comment by damienbod** [comment]
Revoking tokens has been added to Version 11. See the logout docs
