### ISSUE TITLE
[feat] replace jsrsasign-reduced with native crypto module

### ISSUE THREAD

**Issue by Toxicable** [damienbod/angular-auth-oidc-client#506]
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto
This can be pollyfilled for older browser
It will reduce bundle size and increase bundler compatibility.
Aswell as using a standard API rather than a NPM one.

**Comment by damienbod** [comment]
@Toxicable tried this and had many problems with getting it to work. Closing this for now.
