### ISSUE TITLE
Firefox & Well known endpoints must be loaded before user can login

### ISSUE THREAD

**Issue by jsklassen** [damienbod/angular-auth-oidc-client#51]
I might be missing something obvious here or I've discovered a bug.

I'm getting an error "Well known endpoints must be loaded before user can login!" when I call securityService.authorize() but only in Firefox. In Chrome and IE11 this works properly and redirects to the login page. 

I am using the implicit flow. I'm using angular-auth-oidc-client 1.3.0, Firefox 54.0.1, Angular 4.3.1. This same problem also happens in a different angular 4+ app using angular-auth-oidc-client 1.3.0.  It also happens to all 3 coworkers that I tested firefox with in both apps.

![image](https://user-images.githubusercontent.com/456593/28580159-5257b7d4-7124-11e7-95a6-01d98bb8cf99.png)

This is the setup code:
`initOpenIdServer(): OpenIDImplicitFlowConfiguration {

        if (this.openIdConfiguration != null)
            return this.openIdConfiguration;

        let implicitFlow = new OpenIDImplicitFlowConfiguration();

        implicitFlow.stsServer = this.cs.config.openIdBaseApiUrl;
        implicitFlow.redirect_url = this.cs.config.openIdRedirectUrl;
        implicitFlow.post_logout_redirect_uri = this.cs.config.openIdRedirectUrl;

        implicitFlow.client_id = 'my.id';
        implicitFlow.response_type = 'id_token token';
        implicitFlow.scope = 'openid profile email';

        implicitFlow.start_checksession = true;
        implicitFlow.silent_renew = true;
        implicitFlow.max_id_token_iat_offset_allowed_in_seconds = 10;

        implicitFlow.log_console_warning_active = true;
        implicitFlow.log_console_debug_active = false;

        implicitFlow.startup_route = '/';
        implicitFlow.forbidden_route = '/forbidden';
        implicitFlow.unauthorized_route = '/unauthorized';

        this.securityService.setupModule(implicitFlow);

        return implicitFlow;
    }
`

I have verified the values coming from config files are correct before this code runs.

Is there something I should be doing with implicitFlow.override_well_known_configuration or implicitFlow.override_well_known_configuration_url? Do I need to provide different storage for FireFox?

**Comment by damienbod** [comment]
This seems strange. I'll look into it. The implicitFlow.override_well_known_configuration and implicitFlow.override_well_known_configuration_url properties are only required, if the STS server does not support this for browser clients. These properties make it possible to load the configuration locally. 

What does the well known endpoints HTTP request return? Can you check this in the network F12?

**Comment by jsklassen** [comment]
In chrome it returns 

`{
  "issuer": "https://identityservertestprovider.cloudapp.net/",
  "jwks_uri": "https://myserver/.well-known/jwks",
  "authorization_endpoint": "https://myserver/connect/authorize",
  "token_endpoint": "https://myserver/connect/token",
  "userinfo_endpoint": "https://myserver/connect/userinfo"
}`

if I place that in `assets/data/wellknownconfiguration.json` and then add

`        implicitFlow.override_well_known_configuration = true;
        implicitFlow.override_well_known_configuration_url = 'http://localhost:4200/assets/data/wellknownconfiguration.json'; 
`

Firefox, Chrome, and IE all work.  This got me to the actual login page where Firefox again complained that the internal qa url had an invalid cert.

![image](https://user-images.githubusercontent.com/456593/28583516-136cf6fa-712f-11e7-89a5-62de1c361ec0.png)

I clicked Add Exception and it let me continue to the page. The login page and wellknown redirect to the same domain. So wellknown was silently failing with this cert error but couldn't display the page to do something about it. 

Now removing the `override_well_known_configuration and override_well_known_configuration_url` settings Firefox works consistently. Once trusted the wellknown json pulls down correctly.

Thank you for the prompt response. Apologies for the unrelated issue.
