### ISSUE TITLE
Silent-renew and access token 

### ISSUE THREAD

**Issue by maghibus** [damienbod/angular-auth-oidc-client#521]
Hi,

In most cases, the access token expires before the id-token, such as using Multiple Active User Session.
Why is it that only id-token lifetime is checked?
Any particular reason for this?

Thank you.

**Comment by chtinnes** [comment]
+1 
For me, i even can not change the id token expiry with my identity provider, so if i change the exp of my access tokens, the expiry times will be different. In the case the expiry for the access token is shorter, there will be no refresh in time.

**Comment by damienbod** [comment]
Now supported in version 11
