### ISSUE TITLE
Handling initial application query parameters

### ISSUE THREAD

**Issue by chuckcollins70** [damienbod/angular-auth-oidc-client#522]
I noticed and used setCustomRequestParameters function. It stores Params in a session object under storage_custom_request_params name. However, a getCustomRequestParameters function does not appear available. There doesn't appear to be any mechanism in the spec to handle (application query parameters) being preserved in the redirect callback. I have created my own mechanism to do this - getting the values from session storage. Curious if I am missing something in the spec and/or why there isn't a corresponding getCustomRequestParameters to encapsulate the session storage_custom_request_params?

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing. Please refer to the new docs

Greetings Damien
