### ISSUE TITLE
getIsAuthorized returns false always at first

### ISSUE THREAD

**Issue by JamilOmar** [damienbod/angular-auth-oidc-client#524]
I am trying to use  this.oidcSecurityService.authorize(). The this.oidcSecurityService.getIsAuthorized() is always returning false the first using implicit flow, This makes my code to be on a loop because the getIsAuthorized method only returns true on a second time. Do you have an example on how to automatically redirect the user to the identity if is not authenticated ?

**Comment by dozer75** [comment]
Do you have any code example or snippet of your subscribe statement? I had some issues with this since I am calling the authorize method within the subscribe and got multiple false due to an issue in the library, I solved this by adding a `setTimeout` around my authorize call.

**Comment by Patrickkk** [comment]
Im having the same issue, because our entire application is protected i check the result of getIsAuthorized() in the app component and login if it is not authorized (or an iframe). However the result is an infinite loop because getIsAuthorized first emits false.

**Comment by Patrickkk** [comment]
The issue is not there is silent renew is enabled. For me this solved the issue

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
