### ISSUE TITLE
ID Token missing at_hash claim is invalid

### ISSUE THREAD

**Issue by willsu** [damienbod/angular-auth-oidc-client#525]
Hi folks. Thanks for the great library you've created! 

I'm working on an integration with an OIDC provider that returns ID Tokens with no `at_hash` claim, which are granted via the Implicit Flow (`response_type="token id_token"`). The vended OIDC provider does not yet support PKCE.

The problem is that ID Token validation fails in the `validate_id_token_at_hash` function due to the `at_hash` param being `undefined`, thus [not matching the hash of the Access Token.](https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/oidc.security.validation.ts#L347-L371)

A [code comment suggests](https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/oidc.security.validation.ts#L345-L346) that the `at_hash` validation should only occur if the ID Token has an `at_hash` claim:
> // access_token C3: The value of at_hash in the ID Token MUST match the value produced in the previous step if at_hash is present in the ID Token.

Is the intent that token validation should fail if the ID Token doesn't contain an `at_hash` param? If validation failure is the intended behavior, which I assume that it is, would you consider adding a [configuration switch](https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/auth-configuration.provider.ts#L9-L36) to allow disabling the `at_hash` validation?

Unfortunately we're currently tied to a vendored OIDC provider implementation that will not return the `at_hash` claims in the ID Token, so we're looking for skip this validation for the time being.

Thanks a lot for you help!

**Comment by damienbod** [comment]
@willsu Yes, the at_hash is required.

https://openid.net/specs/openid-connect-implicit-1_0.html#IDToken

**Comment by willsu** [comment]
Thanks @damienbod. Totally understandable. I've filed an issue with the specific OIDC Provider and will run a forked version of this library for our purposes until it is fixed by the provider.

**Comment by rsdickerson** [comment]
@willsu Out of curiosity, could you disclose who the OIDC Provider is that is not including the at_hash in the id token per spec when using the Authorization Code flow?
