### ISSUE TITLE
Authorization completely breaks for Chrome when they enable "Sites must specify SameSite=None in order to enable third-party usage.", in a couple of months

### ISSUE THREAD

**Issue by hakonamatata** [damienbod/angular-auth-oidc-client#526]
Hi

Google Chrome and probably other browsers are intruducting breaking changes in how they handle third party cookies, this completly breaks the login with "angular-auth-oidc-client", when using redirect to third pary login sites. 

These breaking changes will be intruduced for Google Chrome just a couple of months, February 2020. Not sure about the other browsers, but this will instantly break every site using this login library (in it's current version). 

This can be reproduced now

**Reproduce steps**

1. Go to chrome://flags/#same-site-by-default-cookies, and set "SameSite by default cookies" to true
2. Set up athorization with third party site for login (we useIdentityServer4: http://docs.identityserver.io/en/latest/)

3. Login to your page (this still works), refresh, this will instantly log you out again, with error messages like this: 

![image](https://user-images.githubusercontent.com/4003969/68015349-46842180-fc92-11e9-92ae-333b3e3a291d.png)

This is how our authorization module look like:
```
export class AuthenticationModule {
  constructor(
    private oidcSecurityService: OidcSecurityService,
    private oidcConfigService: OidcConfigService,
    public appData: AppData
  ) {

    const url = `${window.location.protocol}//${window.location.host}/`;

    this.oidcConfigService.onConfigurationLoaded.subscribe((configResult: ConfigResult) => {

      const config: OpenIdConfiguration = {
        stsServer: `${this.appData.identityServerUrl}`,

        redirect_url: url,
        // The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer
        // identified by the iss (issuer) Claim as an audience.
        // The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience,
        // or if it contains additional audiences not trusted by the Client.
        client_id: 'CLIENT',
        response_type: 'id_token token',
        scope: 'openid profile roles ',

        post_logout_redirect_uri: url,
        start_checksession: false,
        silent_renew: true,
        silent_renew_url: `${url}silent_renew.html`,

        log_console_warning_active: true,
        log_console_debug_active: false,
        // id_token C8: The iat Claim can be used to reject tokens that were issued too far away from the current time,
        // limiting the amount of time that nonces need to be stored to prevent attacks.The acceptable range is Client specific.
        max_id_token_iat_offset_allowed_in_seconds: 60,
        trigger_authorization_result_event: true
      };

      this.oidcSecurityService.setupModule(config, configResult.authWellknownEndpoints);

    });
  }
}
```

We use this great project in several ciritical applications, so it's very important for us that a fix is introduced soon :/

**Comment by damienbod** [comment]
Hi @hakonamatata yes this is a pain...

Here's the fix as yet

https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

The angular part with not need to be changed as this uses tokens.

Greetings Damien
