### ISSUE TITLE
`auto_userinfo: false` stops silent renew from working

### ISSUE THREAD

**Issue by ahofman** [damienbod/angular-auth-oidc-client#531]
I am using code flow with PKCE. 

When configuring `auto_userinfo: false`, the silent renew never fires because on this line:

https://github.com/damienbod/angular-auth-oidc-client/blob/229cdbbcb2bbe8e4a2bd1364f0ffbdbd237dbab2/projects/angular-auth-oidc-client/src/lib/services/oidc.security.service.ts#L944

`this._userData.value` is always falsey because it is never set.

Can you help me understand why the userData is required for the silent renew to fire? Should it only check `this._userData.value` only if `auto_userinfo` is `true`?

**Comment by damienbod** [comment]
This has been refactored, fixed and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
