### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by massimoalbertin** [damienbod/angular-auth-oidc-client#532]
I'm using **Code + PKCE** and I'm trying to add **Refresh Token** support.
If I understood well the only supported mechanism is using silent_renew as follow:

```ts
const config: OpenIdConfiguration = {
    silent_renew: true,
    silent_renew_url: 'https://localhost:4200/silent-renew.html',
    use_refresh_token: true,
    trigger_authorization_result_event: true,
    history_cleanup_off: true
};
```

The main idea is to call refresh token api when token is expired without iframe mechanism. 
I've noticed following behaviors/questions:

1. **trigger_authorization_result_event** without this configuration every executed refresh request redirect to post_login_route creating some problem to page render

2. **history_cleanup_off** previous setting avoids route redirection but, when refresh request successfully occurs browser url will be updated (without changes in page render). This happens because in method authorizedCodeFlowCallbackProcedure (OidcSecurityService) line 450 is 
```ts
        const silentRenew = this.oidcSecurityCommon.silentRenewRunning;
        const isRenewProcess = silentRenew === 'running';
```
isRenewProcess is always false and line 495
```ts
        if (!this.configurationProvider.openIDConfiguration.history_cleanup_off && !isRenewProcess) {
            // reset the history to remove the tokens
            window.history.replaceState({}, window.document.title, window.location.origin + window.location.pathname);
        } else {
            this.loggerService.logDebug('history clean up inactive');
        }
```
the if (instead of else) part is always executed. Putting history_cleanup_off I restored the expected behavior.

3. Also with `use_refresh_token: true ` the iframe (empty) is created when the application starts (not authenticated) but after login when refresh token procedure is performed iframe mechanism is not used. After a login --> logout iframe is still present with src populated and can create some X-FRAME security issues (errors on console) if X-FRAME-OPTION deny on STS. But If I use Refresh Token mechanism I don't need the iframe, right?

Is it correct or I'm doing it in the wrong way?
Thank you
M.

**Comment by dozer75** [comment]
If you set `use_refresh_token` to true, but there is no `refresh_token` the library automatically tries to do a silent renew and thus requires the `iframe`. If you have set `log_console_debug_active` to `true`, you'll see a console entry like this `no refresh token found, using silent renew` that states this.

So as far as I can see it's by design.. Is it a good design? I don't have any direct opinion on that...

**Comment by damienbod** [comment]
support in version 11
