### ISSUE TITLE
Accessing token response AuthResult

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#536]
Looking through the documentation I can not seem to find a subscription or a custom callback to use to access the response object from the access_token call. In our solution there may be extra values that get added to the token response (i.e {access_token: ..., id_token: ...., customValue: ...}. Is there any way to access this using the current functions in the library? or would this need to be an enhancement?

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien

**Comment by JoellyR** [comment]
It seems that in version 11 there still doesnt seem to be a clean way to access this... (i can read it from session storage but i need to always change the key because its alway *client_id*.authnResult. Am i missing something? Or is there any road map to add this in the future?

**Comment by damienbod** [comment]
Hi @JoellyR when have custom params which you can send and these are persisted. custom values coming backing from your STS which definition is not supported at the moment. 

We have 4 or 5 different types of responses depending on the flow. So this might be difficult to support.

What do you use these for? and which response? Is this user profile data maybe? what STS do you use and which flow?

Greetings Damien

**Comment by JoellyR** [comment]
@damienbod  ah i well i guess when i see it in session storage you just seem to store w.e was sent as a response from the access_token call under *client_id*_authnResult. What i would imagine is having  access to something **like** the AuthResult
but instead it AuthResult an object that is just the parsed data from inside the session storage from whatever is under the key  *client_id*_authnResult.

**Comment by damienbod** [comment]
Hi @JoellyR We will make the AuthResult public through the APIs

Suggestion:

```
GetAuthResult(configId? : string)
```

Good?

**Comment by JoellyR** [comment]
that sounds good thanks for your help and your quick replies!
