### ISSUE TITLE
Authorization data get lost from session storage (Firefox) for 1st app after loading 2nd app of the same origin inside an iFrame

### ISSUE THREAD

**Issue by valleron** [damienbod/angular-auth-oidc-client#538]
Hi @damienbod ,

I have an application (App1) that loads another application (App2) inside an iframe. After initial login to App1 and loading App2 inside an iframe, all the authorization data of App1 which is stored in session storage get lost. Further requests for App1 runs in an 401. This behavior occurs only in FF browser and only if both applications are of the same origin.

#### The configuration (excerpt)
```typescript 
OpenIdConfiguration = {
   ...
   response_type: 'id_token token', // implicit flow
   trigger_authorization_result_event: true, // required for auto login component
   max_id_token_iat_offset_allowed_in_seconds: 60,
   silent_renew: true,
   silent_renew_url: window.location.origin + this.platformLocation.getBaseHrefFromDOM() + 'silent_renew.html',
   storage: sessionStorage,
   silent_renew_offset_in_seconds: 10,
   ...
}
```

#### The way we loading App2 inside an iFrame
```typescript
const container: HTMLElement = ...
const iFrame: HTMLIFrameElement = document.createElement('iframe');
iFrame.src = 'https://myhost/app2';
container.appendChild(iFrame);
```

#### Resulting session storage entries for use case described above

1. Successfully log into App1 (_https://myhost/app1_)
* created session storage entries for _https://myhost_:

key | value
-----|--------
_isAuthorized_App1|`true`
authNonce_App1|""
authStateControl_App1|""
authorizationDataIdToken_App1|`<token_data>`
authorizationData_App1|`<token_data>`
authorizationResult_App1|`<state_data>`
session_state_App1| `<session_data>`
storage_silent_renew_running_App1|""
userData_App1|`<user_data>`

2. Trigger some action to load App2 (_https://myhost/app2_) inside an iframe
* updated session storage entries for _https://myhost_:

key | value
-----|--------
_isAuthorized_App1|`false`
authNonce_App1|""
authStateControl_App1|""
authorizationDataIdToken_App1|""
authorizationData_App1|""
authorizationResult_App1|""
session_state_App1|""
storage_silent_renew_running_App1|""
userData_App1|""
_isAuthorized_App2|`true`
authNonce_App2|""
authStateControl_App2|""
authorizationDataIdToken_App2|`<token_data>`
authorizationData_App2|`<token_data>`
authorizationResult_App2|`<state_data>`
session_state_App2| `<session_data>`
storage_silent_renew_running_App2|""
userData_App2|`<user_data>`

3. Further actions/requests in App1 run into HTTP status code 401 

#### Questions
* Is the usage of mutliple instances of angular-auth-oidc-client library in one browser tab supported in general?
* Do you have any idea why the authorization data of App1 get lost from the session storage for the use case described above?

Any help is appreciated.

Best regards

Valentin

**Comment by damienbod** [comment]
At present multiple instances are not supported due to the way this session is stored. This could be added with little effort. This is also the reason the data gets lost. 

This service would have to be updated:

https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/oidc.security.common.ts

**Comment by valleron** [comment]
Hi @damienbod,

it's a pity that multiple instance are not supported yet. This enhancement would be greatly appreciated.

Thank you for the hint to the service which is responsible for reading/writing the session storage entries. I recognized that the service already uses the client id as key suffix for separating storage entries of several applications (e.g. App1, App2). So I would expected that no session storage entries of App1 (which are created by 1st instance of oidc library) are cleared or reset by 2nd instance of oidc library(App2) and vice versa. This behavior works in Chrome but not in Firefox. Do you have an explanation for that?

Best regards

Valentin

**Comment by damienbod** [comment]
fixed in version 11
