### ISSUE TITLE
Configurable Wellknown endpoints url

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#539]
Would it be possible to have a completely configurable well-know-endpoints url? In our current use case, the spec that we are following wants out resource server to be the one to ask for the well-known-endpoints url... this is because it is meant to be transparent what url we are using for our auth server...

 I was thinking to just make the sts server value to be the resource server and hoped that the well-know endpoints url would get attached to that then the urls in the well-known json would be used for the rest of the calls. 

BUT the spec we are using asks us to name the well-known url as /.well-known/**smart**-configuration instead of /.well-known/**openid**-configuration

**Comment by damienbod** [comment]
Yes, you could load this yourself, and set the well known endpoints manually, like using the example with no app initializer in the readme

Greetings Damien

**Comment by JoellyR** [comment]
@damienbod  Yes but this would be setting all the url's myself, what if i have a discovery url but it is just a slightly different url
