### ISSUE TITLE
Question: how to get an resource access token?

### ISSUE THREAD

**Issue by MovGP0** [damienbod/angular-auth-oidc-client#54]
**Context**
```gherkin
Given I've got an STS at https://sts.foo.com (based on IdentityServer4)
And an Angular Client at https://client.foo.com
And I want to access an API Resource at https://api.foo.com
When I start an implicit flow
Then I get an ID token 
And I get an Access Token with audience "https://client.foo.com"
```

**Question**
How can I request an Access Token with an audience of `https://api.foo.com`?

**Comment by damienbod** [comment]
@MovGP0 If you use the id_token token Implicit Flow, you will recive the access_token back.

The getToken method then returns the access token.

https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.service.ts#L111

Greetings Damien

**Comment by MovGP0** [comment]
the access token I get is for the STS. But I figured out a method that works for me: 

* the `Client` gets the `Access Token` and the `Refresh Token` from the STS using the `Implicit Flow`
* the `Client` send the `Access Token` to the `Resource`
* the `Resource` uses the `IdentityEndpoint` to validate the token and get the user information
* If the user has the proper role claims, the `Resource` invokes the `TokenEndpoint` of the STS to get an `Resource Access Token` for the `Resource` using `Code Flow`
* the `Resource Access Token` gets send to the client 
* the client caches the `Resource Access Token` 
* the client uses the `Resource Access Token` to access the protected resources (without additional round trips). 

I am just wondering if there is a simpler solution...

**Comment by damienbod** [comment]
Yes you could just use the id_token token flow. No need to get the access_token a second time.

Greetings Damien

**Comment by MovGP0** [comment]
well, how do I get the `id_token` then? the `.getToken()` method returns the STS access token, and the `.getUserData()` method doesn't return the ID token either, but only its decoded variant. Apparently, it doesn't get exposed by the `.authorizedCallback()` method like the access token.

**Comment by MovGP0** [comment]
btw: i am not fully sure what an ID Token flow is. There is
* Implicit Flow (for web clients) 
* Authorization Code Flow (3-ledged OAuth flow)
* Resource Owner Password Credentials Flow
* Client Credentials Flow / Code Flow (for clients with secrets)
* Hybrid Flow (basically what I do, but with an additional roundtrip for checking the user roles) 

sources: 
* [OpenID Connect Flows](https://www.scottbrady91.com/OpenID-Connect/OpenID-Connect-Flows)
* Biehl, Matthias. OAuth 2.0: Schnelleinstieg in Web-API Security (API University Series) (German Edition) (Kindle Location 209). Matthias Biehl. Kindle Edition.

**Comment by damienbod** [comment]
Hi @MovGP0 

OpenID Implicit Flow (id_token token) => web clients which access APIs

This PR makes it possible to get the id_token (Will be merged next week when I have a PC again)

https://github.com/damienbod/angular-auth-oidc-client/pull/49/files

Why do you need the id_token? 

Greetings Damien

**Comment by MovGP0** [comment]
what I **need** are 

1. user claims in the frontend to enable and disable visible functionality; `.userData()` is fine for that. 
2. resource access tokens for the resources (there are more than one) 

what I **have** is after the Implicit Flow is 

1. the user claims (id token)
2. the STS Access Token (can be used to get additional tokens from the token endpoint)

**Comment by damienbod** [comment]
@MovGP0 

The access_token can be used to access the user data endpoint which has the user claims. (or userData which is the same for the id_token token flow.

The access_token is also used for the APIs

Why do you need additional tokens?

Greetings Damien

**Comment by MovGP0** [comment]
when accessing the API, I don't want to invoke the User Data Endpoint every time for performance reasons. So my current method is that the Resource invokes the User Data Endpoint only once and gives the Client an Ressource Access Token when the Resource Owner has the appropriate claims. 

The Client can cache this Ressource Access Token and use it to access the Resource. 

* The advantage is that the Ressource can validate this token without additional round trips to the UDE. 
* The drawback is that I need to cache and refresh the Resource Access Tokens. 

*Note:* the Resource can issue the Ressource Access Token himself or via the Token Endpoint from the STS. Both methods should work.

**Comment by MovGP0** [comment]
the problem I have with the access_token is that it is issued with 
```json
{
   "aud": "sts.mydomain.com"
}
```
what I would need is: 
```json
{
   "aud": "sts.mydomain.com", 
   "aud": "resource1.mydomain.com", 
   "aud": "resource2.mydomain.com"
}
```

**Comment by damienbod** [comment]
You should not use the aud like this. You should use, scopes, or api resources claims for this.

 aud
REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case-sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case-sensitive string.

Here's an example:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/ResourceServer/Startup.cs#L108

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.module.ts#L66

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/IdentityServerWithIdentitySQLite/Config.cs#L27

**Comment by damienbod** [comment]
But it should be possible to add multiple aud values in IdentityServer4  to the access_token so only 1 token is required.

**Comment by MovGP0** [comment]
I guess it is. Just haven't figured it out yet. 

As I understand it, I need to do the following: 

1. create an API Resource for each Resource Server. 
2. bundle claims into Scopes that the user can allow or deny. 
3. add the Scopes to the appropriate API Resources
4. configure UserClaims, which the ApiResource can get from the user. 
5. when asking for the access token handle the name of the ApiResource as a claim 
6. IdentityServer's `IProfileService` enriches and filters the claims for the Access Token based on the user properties 
7. the access token should now contain all the requested ApiResource names in the audience field
