### ISSUE TITLE
Successful login callback

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#542]
I was looking through the docs for a method which I could add custom logic on a succcessful login. The closest thing I could find was the onAuthorizationResult, though this still gets triggered if I just refresh the page. Is there any listener that would ONLY be triggered on a successful login and will not be triggered again regardless of page reload, until the user has to enter credentials and login to the AM again ?

**Comment by marcopierobon** [comment]
I'm using a callback module once I'm authenticated 

    redirect_url: this.originUrl + 'callback',

Once the module is loaded I do execute custom logic in there.
