### ISSUE TITLE
AuthorizedCallback token(s) invalid

### ISSUE THREAD

**Issue by allschu** [damienbod/angular-auth-oidc-client#543]
Hello, 
I am stuck at this for couple of days now.
I am new to the code flow with PKCE. 
I am using the code flow example in the documentation. Everything works great until the callback gets hit. (When I use the implicit flow I don't have any problems)

The result that I keep getting is

`authorizedCallback Signature validation failed id_token
angular-auth-oidc-client.js:335 AuthorizedCallback token(s) invalid`

No matter what I try. I can't get around it.
My configuration is this

`{
  "stsServer": "http://localhost:5000",
  "redirect_url": "http://localhost:4200/authCallback",
  "client_id": "angular_spa",
  "response_type": "code",
  "scope": "webapi openid profile",
  "post_logout_redirect_uri": "http://localhost:4200",
  "post_login_route": "/",
  "forbidden_route": "/forbidden",
  "unauthorized_route": "/unauthorized",
  "log_console_debug_active": true,
  "max_id_token_iat_offset_allowed_in_seconds": 10
}`

In Identity server I have the following client configuration
`{
                    ClientId = "angular_spa",
                    ClientName = "JavaScript PKCE OIDC Client",
                    ClientUri = "http://identityserver.io",
                    
                    RequireClientSecret = false,
                    AllowedGrantTypes = GrantTypes.Code,
                    RequirePkce = true,

                    AccessTokenType = AccessTokenType.Jwt,
                    AccessTokenLifetime = 330, // 330 seconds, default 60 minutes
                    IdentityTokenLifetime = 30,

                    RedirectUris =
                    {
                       "http://localhost:4200/authCallback",
                       "http://localhost:4200"
                    },
                    PostLogoutRedirectUris =
                    {
                       "http://localhost:4200",
                       "http://localhost:4200/"
                    },
                    
                    AllowedCorsOrigins = { "http://localhost:4200" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "webapi"
                    }
                }`

What am I missing?

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
