### ISSUE TITLE
Unable to get emitted values from getIsAuthorized in auth guard

### ISSUE THREAD

**Issue by BrandonClapp** [damienbod/angular-auth-oidc-client#544]
Hi Damien,

Fantastic library, I just had a quirk that I'm trying to work through with the authorization guard. My auth guard is modeled from the one provided in the readme, but am having no luck getting angular to actually invoke the `getIsAuthorized` observable (as indicated with the `tap` that I've added).

I am using Angular 8.2. Below is my auth guard implementation...

```ts
@Injectable()
export class OidcAuthGuard implements CanActivate, CanLoad {
  constructor(
    private router: Router,
    private oidcSecurityService: OidcSecurityService
  ) {}

  canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> {
    return this.checkUser();
  }

  canLoad(state: Route): Observable<boolean> {
    return this.checkUser();
  }

  private checkUser(): Observable<boolean> {

    return this.oidcSecurityService.getIsAuthorized().pipe(
      tap(isAuthorized => console.log('This never seems to get invoked', isAuthorized)),
      map((isAuthorized: boolean) => {
        if (!isAuthorized) {
          // Would like to authorize() here instead of in my component
          // to handle redirects to the identity provider
          return false;
        }
        return true;
      })
    );
  }
}
```

I have swapped the `checkUser` implementation out with the following tests and angular seems to be able to process these observables fine.

```ts
private checkUser2(): Observable<boolean> {
  return of(true).pipe(tap(val => console.log('This observable works', val)));
}
```

and

```ts
private checkUser3(): Observable<boolean> {
  return new Observable<boolean>(observer => {
    observer.next(true);
    console.log('This works too');
    // Doesn't seem to be related to the observable completing
  });
}
```

If I add the subscription to `OidcSecurityService.getIsAuthorized` inside of my components, for example in `ngOnInit` (like the examples show) then the values seem to get emitted from the observable, however, angular doesn't seem to be subscribing to the observable (or nothing is being emitted) when it's returned from `canActivate`.

Can you spot anything that I'm doing wrong here?

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
