### ISSUE TITLE
Why can I still request an access token if refresh token expired?

### ISSUE THREAD

**Issue by lustuyck** [damienbod/angular-auth-oidc-client#546]
I have set up the authorization Code Flow with Proof Key for Code Exchange (PKCE), with silent renew. All is working properly. But I have something I cannot explain and a question.

### My first question 
...is about behavior I cannot explain related to refresh tokens. I have configured my Angular Client in Identity Server as follows:

**RefreshTokenUsage = TokenUsage.OneTimeOnly,
AccessTokenLifetime = 30,
AbsoluteRefreshTokenLifetime = 3600,
RefreshTokenExpiration = TokenExpiration.Sliding,
SlidingRefreshTokenLifetime = 60,**

Also, my Angular client uses the 'silent renew' mechanism (using angular-auth-oidc-client).

If the Angular client is started, after 20 seconds the 'silent renew' kicks in and asks for a new access token, which makes sense because this is about 75% of the access token lifetime of 30 seconds). It gets a new access token and all keeps working.

At a given moment in time, I stop the silent renew. This means that it does not refresh the access token anymore, and indeed, after a while my calls to the web api fail because the access token expired.

Now, minutes later I restart 'silent renew'.

The strange thing is that it succeeds in getting a new access token, but it was my understanding that this should not work anymore because the refresh token should have expired after 60 seconds?

I probably misunderstand how this sliding refresh token mechanism works.. can someone explain why I can still request a new access token with a refresh token that is expired?

### Second question
the user remains logged on. Even closing the browser remembers the session if 'remember where I left off' option is enabled in Chrome or Firefox, which is quite a problem if the site is used on a shared computer. My question about this: is there a way to make the access token invalid if the user is not active for let's say 15 minutes, or when the browser is closed with the option 'remember where I left off' is enabled?

Thanks!

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
