### ISSUE TITLE
nonce validation after using refresh token fails for keycloak

### ISSUE THREAD

**Issue by remkoboschker** [damienbod/angular-auth-oidc-client#552]
Keycloack returns the nonce that is contained in the refreshtoken it sent. The refreshtoken contains the same nonce as the one that was sent on the original code grant request. This nonce is not the same as refreshtokennonceplaceholder and so the validation of the returned tokens fails. 

I think there are two options to fix this:
1. remove the is undefined check in https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/oidc.security.validation.ts#L177 and just check if the refreshtoken place holder was stored.
2. not set the placeholder if the refresh token contains a nonce, but use the nonce from the refresh token.

I am aware that most oidc clients assume no nonce will be sent on a fresh request and I am also aware of the standards erratum tracked in this issue https://bitbucket.org/openid/connect/issues/1025/ambiguity-with-how-nonce-is-handled-on, but my company has invested in using keycloak and I would rather use this library than the keycloak.js client lib.

How can I proceed and would you accept a pull request with one of the work arounds mentioned above?

**Comment by damienbod** [comment]
A PR with the first option would be cool. Maybe use a ew config property to activate your KeyCloak fix. Then we can be sure that all the other flows are uneffected.

Does this sound good to you?

I will then merge and release if all is ok.

Gruss Damien

**Comment by remkoboschker** [comment]
Alright, I will write one next week. Thank you. Which of the two options seems best to you?

**Comment by damienbod** [comment]
I would prefer option 1, I think this would be better, and use a config property to turn on, off the new logic.  Default is like it is,. What do you think?

Greetings and thanks Damien

**Comment by remkoboschker** [comment]
I agree, will do

**Comment by everflux** [comment]
It seems this was amended in the OIDC spec and as I understand it, keycloak is behaving according to the current spec.
