### ISSUE TITLE
Using services from the library

### ISSUE THREAD

**Issue by shifka** [damienbod/angular-auth-oidc-client#555]
Hi, 
I'm looking to use the services like OidcSecurityCommon, OidcSecurityUserService in my implementation. I'm not using the source code directly. It seems the library doesn't seem to expose these services outside. I'm getting a compile error when I import these services from the library as below. 
![image](https://user-images.githubusercontent.com/59949907/72586974-a006fe80-3919-11ea-95bc-c03f1db8691f.png)

This is how I have imported the service:
```
import { OidcSecurityCommon } from 'angular-auth-oidc-client/lib/services/oidc.security.common';

@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate, CanActivateChild {
  constructor(
    public router: Router,
    private oidcSecurityCommon: OidcSecurityCommon,
```

**Comment by FabianGosebrink** [comment]
Hey shifka, the lib does not expose the services yet. What is your usecase only using parts of the library?

**Comment by shifka** [comment]
I'm using the library for the flow. But I need to use methods like get
