### ISSUE TITLE
return types authorizedCodeFlow side effects

### ISSUE THREAD

**Issue by remkoboschker** [damienbod/angular-auth-oidc-client#559]
https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/oidc.security.service.ts#L391 call returns void. But https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/oidc.security.service.ts#L391 expects an `observable<boolean>`

**Comment by damienbod** [comment]
em... The more strict type was added last week, must have missed this, don't see a warnings for this.
