### ISSUE TITLE
Large authorizationDataIdToken (because of roles etc.) & cookie storage

### ISSUE THREAD

**Issue by robertmuehsig** [damienbod/angular-auth-oidc-client#56]
Hi

We are pretty new in the Angular and OpenID Connect land, so maybe we are doing things just plain wrong :)

Our IdentityServer (v3 btw) returns a "large" list of claims ("groupSids" and associated roles) from the UserInfoEndpoint 

![image](https://user-images.githubusercontent.com/756703/29020169-67bb943c-7b61-11e7-9d69-675766a27f1e.png)

The jwt is about >5500 chars.

Now we wanted to implement a proper storage for the auth data, so that we can get the silent renew workflow working, but unfortunately the "authorizationDataIdToken" is too big for the cookie and the browser refuses to save it. 

The library tries to load some important oidc-keys (e.g. "exp") from the JWT token so it seems the complete authorizationDataIdToken is needed.

Have you a suggestion for us? Are we using the userinfo endpoint wrong? We also could "split" the jwt in several cookies (like in the old ASP.NET days) and combine them during runtime, but I'm not sure if this is the way we should go. 
Or just use the HTML5 localStorage? 

We faced a similar problem with our WPF Windows client, but we were using Reference-AccessTokens and using access-tokens & refresh-tokens, but it seems in the Angular world it is different. In the fat client app I only store the accesstoken, the expire-date and the refresh-token and thats it. With them I can get a fresh accesstoken and do a proper logout without the super large JWT token.

**Comment by damienbod** [comment]
Hi @robertmuehsig 

I try to split the claims as follows:

id_token : includes only the claims for identity logic in client application
access_token : claims required the API resources
User API in Identity : user profile

Using this lib, the id_token  and the access_token are saved to the local_storage per default.

I would use the local storage for the local persistence. If your using the 'id_token token' flow (which you should be), the user profile is requested with the first auth sign in. In the next version of this lib, you will have a helper function which will return the user data. (Will merge the pull request this week). 

Splitting the claims like this might reduce the size of your tokens. You could also use redux.

Greetings Damien

**Comment by robertmuehsig** [comment]
Splitting & using the localStorage did the trick for us - seems to work just fine now. Thanks!
