### ISSUE TITLE
requestTokensWithCode sends incorrect redirect_uri

### ISSUE THREAD

**Issue by CobusKruger** [damienbod/angular-auth-oidc-client#566]
**Edit**
Well, that was fun. I found the bug in my code as soon as daylight returned, so feel free to close this.

For reference to anyone who may run into this, I was sending as redirect_uri the value of `document.location.href`, which will always be the full URI, including the parameters passed to the site. I should have used `document.location.origin` instead.

**Original**
I followed these instructions for PKCE: https://damienbod.com/2019/01/09/securing-angular-applications-using-the-openid-connect-code-flow-with-pkce/

Accordingly, in my autorization callback I call `requestTokensWithCode` when the URL contains the `code` and `state`.

```javascript
if (code && state && session_state) {
   this.oidcSecurityService.requestTokensWithCode(code, state, session_state);
}
```
However, this gets rejected, because the `redirect_uri` sent to the token endpoint actually contains the code. Consequently, IdentityServer4 keels over with this message:

```
fail: IdentityServer4.Validation.TokenRequestValidator[0]
      Invalid redirect_uri{ redirectUri = https://localhost:4200/auth-callback?code=bqAyuKwOlLj-aR6qaSVqUa-BkmqwV1qk4Zq6-_xhYlE, expectedRedirectUri = https://localhost:4200/auth-callback },
```

Notice that the configured URI actually matches what was sent, without the code. The result is a 400 Bad Request response.

**Comment by jeroenheijmans** [comment]
Hey hey! Thx for letting us know how you solved things!

You can usually close your own issues, if you want to.
