### ISSUE TITLE
Module not resolved in latest build

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#570]
Getting the following error when updating to the newest version. 

ERROR in ./node_modules/angular-auth-oidc-client/fesm2015/angular-auth-oidc-client.js
Module not found: Error: Can't resolve 'common-tags' in '.../node_modules/angular-auth-oidc-client/fesm2015'

**Comment by damienbod** [comment]
Hi  @JoellyR  which version?

**Comment by damienbod** [comment]
fixed in 10.0.14 sorry about that
