### ISSUE TITLE
getIsAuthorized true and then false?

### ISSUE THREAD

**Issue by vsakhdeo** [damienbod/angular-auth-oidc-client#574]
![image](https://user-images.githubusercontent.com/49958040/73300590-7ded6600-41ce-11ea-8272-4a53bedac16e.png)

I am trying to use implicit flow with Identity Server 3 and I can see the id_token and access_token in the dev tools. but getIsAuthorized  is eventually false. 

Also this.oidcSecurityService.getToken() returns null. I am using v10.0.14. What am I missing here?

this is my app.component.ts for the login/logout:

import { Component, OnDestroy, OnInit } from '@angular/core';
import { ConfigResult, OidcConfigService, OidcSecurityService, AuthorizationResult, AuthorizationState } from 'angular-auth-oidc-client';
import { TestService } from './testservice.service';

@Component({
    selector: 'app-root',
    templateUrl: 'app.component.html',
})
export class AppComponent implements OnInit, OnDestroy {
    isAuthenticated: boolean;
    isConfigurationLoaded: boolean;
    userData: any;

    constructor(private oidcConfigService: OidcConfigService, public oidcSecurityService: OidcSecurityService, private _testService: TestService) {

        if (this.oidcSecurityService.moduleSetup) {
            this.doCallbackLogicIfRequired();
        } else {
            this.oidcSecurityService.onModuleSetup.subscribe(() => {
                this.doCallbackLogicIfRequired();
            });
        }
     
    }

    ngOnInit() {
        this.oidcConfigService.onConfigurationLoaded.subscribe((value: ConfigResult) => {
            this.isConfigurationLoaded = true;
        });

        this.oidcSecurityService.getIsAuthorized().subscribe(auth => {
            this.isAuthenticated = auth;
        });

        this.oidcSecurityService.getUserData().subscribe(userData => {
            this.userData = userData;
        });
    }

    ngOnDestroy(): void {}

    login() {
        this.oidcSecurityService.authorize();
    }

    logout() {
        this.oidcSecurityService.logoff();
    }

    private doCallbackLogicIfRequired() {
        // Will do a callback, if the url has a code and state parameter.
        //this.oidcSecurityService.authorizedCallbackWithCode(window.location.toString());
        if (window.location.hash) {
          this.oidcSecurityService.authorizedImplicitFlowCallback();
      }
    }
Thank you!
    
}

**Comment by vsakhdeo** [comment]
looks like it's failing on comparison as it's strict (but the values returned from userinfo endpoint and access token are string and int respectively), not sure how to correct that though?

**Comment by damienbod** [comment]
Hi @vsakhdeo I'll investige this, if it's a type problem, I will add a fix for this, thanks for reporting

**Comment by vsakhdeo** [comment]
Hi @damienbod, the data type for sub(for userinfo endpoint) was integer in our case. We changed it to string since the one from token will always be string and that seemed to fix our issue. I guess the strict comparison(in this package) makes more sense as to make sure they both match exactly. thoughts? And if you agree, I am good with closing this issue.

**Comment by damienbod** [comment]
fixed in version 11
