### ISSUE TITLE
Silent renew always fails with login_required

### ISSUE THREAD

**Issue by CobusKruger** [damienbod/angular-auth-oidc-client#575]
I have a small sample based on [the PKCE blog post](https://damienbod.com/2019/01/09/securing-angular-applications-using-the-openid-connect-code-flow-with-pkce/) and [the accompanying project.](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/AngularClientCode/angularApp)

I can upload place the code somewhere for review, but the only changes are:
1. I switched to using the NPM library.
2. I removed the translation bits to yield a simpler demo.
3. My secure files component only shows a piece of text, also to make it simpler.
4. I'm reading the config values from a JSON files, not an extra web service. Again, for the sake of simplicity.

I'm connecting to an IdentityServer4 authority, which uses Azure AD to authenticate.

When I sign in, everything looks good and I'm authenticated, I get a token, and `userinfo` is called and returns sensible results.

Then I see the silent renew entries. They all look something like this:

```
onCheckSessionChanged
app.component.ts:36 ...recieved a check session event
angular-auth-oidc-client.js:337 silentRenewHeartBeatCheck
	silentRenewRunning: false
	idToken: true
	_userData.value: true
angular-auth-oidc-client.js:337 Token not expired?: 1580881666000 > 1580881646545  (true)
angular-auth-oidc-client.js:337 <iframe id=​"myiFrameForCheckSession" style=​"display:​ none;​">​…​</iframe>​
angular-auth-oidc-client.js:337 
```

Until the token expires:

```
...recieved a check session event
angular-auth-oidc-client.js:337 silentRenewHeartBeatCheck
	silentRenewRunning: false
	idToken: true
	_userData.value: true
angular-auth-oidc-client.js:337 Token not expired?: 1580881666000 > 1580881667564  (false)
angular-auth-oidc-client.js:337 IsAuthorized: id_token isTokenExpired, start silent renew if active
angular-auth-oidc-client.js:337 BEGIN refresh session Authorize
angular-auth-oidc-client.js:337 RefreshSession created. adding myautostate: 15808816675640.<Redacted>
angular-auth-oidc-client.js:337 startRenew for URL:https://<redacted>.azurewebsites.net/connect/authorize?client_id=MyClientID&redirect_uri=https%3A%2F%2Flocalhost%3A4200%2Fassets%2Fsilent-renew.html&response_type=code&scope=openid%20profile%20api1&nonce=N<Redacted>&state=<Redacted>&code_challenge=<Redacted>&code_challenge_method=S256&prompt=none
angular-auth-oidc-client.js:337 silentRenewEventHandler
app.component.ts:75 Auth result received AuthorizationState:unauthorized validationResult:LoginRequired
app.component.ts:81 
```

I redacted state, nonce and code and anything else I thought migh be sensitive, but they all look like I'd expect.

Notice that the silent renew sends `prompt=none`, which is what I expect. IdentityServer responds with `login_required`.

Looking at the IdentityServer logs, I see this for the intial (interactive) login:

```json
IdentityServer4.Endpoints.AuthorizeCallbackEndpoint: ValidatedAuthorizeRequest
{
    "ClientId": "RegisteredClientID",
    "ClientName": "My App Name",
    "RedirectUri": "https://localhost:4200/auth-callback",
    "AllowedRedirectUris": [
        "https://localhost:4200/auth-callback",
        "https://localhost:4200",
        "https://localhost:4200/assets/silent-renew.html"
    ],
    "SubjectId": "253aa016-74ed-40dc-8b78-5aa5085a4df6",
    "ResponseType": "code",
    "ResponseMode": "query",
    "GrantType": "authorization_code",
    "RequestedScopes": "openid profile api1",
    "State": "<Redacted>",
    "Nonce": "N<Redacted>",
    "SessionId": "<Redacted>",
    "Raw": {
        "client_id": "RegisteredClientID",
        "redirect_uri": "https://localhost:4200/auth-callback",
        "response_type": "code",
        "scope": "openid profile api1",
        "nonce": "N<Redacted>",
        "state": "<Redacted>",
        "code_challenge": "<Redacted>",
        "code_challenge_method": "S256"
    }
}
```

The silent renew fails *every* time:

```json
IdentityServer4.Endpoints.AuthorizeEndpoint: 
{
    "ClientId": "MyRegisteredClientID",
    "ClientName": "My App Name",
    "RedirectUri": "https://localhost:4200/assets/silent-renew.html",
    "AllowedRedirectUris": [
        "https://localhost:4200/auth-callback",
        "https://localhost:4200",
        "https://localhost:4200/assets/silent-renew.html"
    ],
    "SubjectId": "anonymous",
    "ResponseType": "code",
    "ResponseMode": "query",
    "GrantType": "authorization_code",
    "RequestedScopes": "openid profile Citadel.Auth",
    "State": "<Redacted>",
    "Nonce": "N<Redacted>",
    "PromptMode": "none",
    "Raw": {
        "client_id": "MyRegisteredClientID",
        "redirect_uri": "https://localhost:4200/assets/silent-renew.html",
        "response_type": "code",
        "scope": "openid profile Citadel.Auth",
        "nonce": "N<Redacted>",
        "state": "<Redacted>",
        "code_challenge": "<Redacted>",
        "code_challenge_method": "S256",
        "prompt": "none"
    }
}
```

This causes a `Token Issued Failure` error with `login_required`.

Note that it sends along the code, but not the subject, and not the session ID. This seems intuitively correct to me, as the session is expired (that's why we're renewing) and the code was issued to refresh the session, so it should surely imply the subject. But clearly my intuition is way off.

Here is the error showing the token issue failure:

```json
IdentityServer4.Events.DefaultEventService: {
    "Name": "Token Issued Failure",
    "Category": "Token",
    "EventType": "Failure",
    "Id": 2001,
    "ClientId": "MyRegisteredClientID",
    "ClientName": "My App Name",
    "RedirectUri": "https://localhost:4200/assets/silent-renew.html",
    "Endpoint": "Authorize",
    "Scopes": "openid profile api1",
    "GrantType": "authorization_code",
    "Error": "login_required",
    "ActivityId": "80000980-0000-bc00-bf76-84710c7967bb",
    "TimeStamp": "2020-02-05T05:31:09Z",
    "ProcessId": 90786,
    "LocalIpAddress": "<Redacted>",
    "RemoteIpAddress": "<Redacted>"
}```

**Comment by damienbod** [comment]
Hi @CobusKruger 

This is usually a configuration problem , or  the iframe request is getting blocked by your CSP policy, CORS or an incorrect url.

turn on the debug logging on the ID4 and the PII to see why it gets rejected. Also control you CSP configuration, the IFRAME headers and the CORS. 

Hope this helps

Greetings Damien

**Comment by jjonas3** [comment]
I have a kind of similar problem.  I log in OK, but then in about 4  minutes or so it logs me out

**Comment by babackkh** [comment]
I get the same issue with silent renew,
I am using `detail: window.location.hash.substr(1),`
please respond...

**Comment by damienbod** [comment]
Hi @babackkh  login_required means that you have no session on the STS you use and the STS requires than you login again. So the silent renew fails correctly because you are not logged into the server and there is nothing to renew. If you are logged in, then it will work, or you get  a different message. 

Greetings Damien

**Comment by babackkh** [comment]
thanks Damien but I'm logged in and have a valid access and id token, this happens during silent renewal

**Comment by elmcherqui** [comment]
Same issue here for me and i think i missed some configuration on the client because it seems that Identity server is working as excpected.
![image](https://user-images.githubusercontent.com/12566542/117564989-56fb3080-b0af-11eb-9d20-a226d63367ea.png)

**Comment by damienbod** [comment]
@elmcherqui If you look at the logs, token issued failed on the STS, please check why to server STS does not issue the token and reject the silent renew. You can compare your setup to the examples, we use ID4 as well to test against. Also you run iframe silent renew which is now blocked in some browsers and maybe on the server.

Greetings Damien

**Comment by elmcherqui** [comment]
Hello if anyone has the same issue with asp.net core here is what i ve done.
I don't recommand what i did in production, i'am still in the process of understanding and tightening the security.
1- Allow the cookie to be available ( Cross Site Request Forgey )
![image](https://user-images.githubusercontent.com/12566542/117590218-a16fc200-b12e-11eb-81a5-dab581f564a2.png)

2- Allow the site to be available within iframe
![image](https://user-images.githubusercontent.com/12566542/117590277-fc091e00-b12e-11eb-9ce8-ed010b00a02d.png)

3- Make sur you are on the same browser and not in private mode . i made my angular app available through https so that it can run on another tab of the same chrome instance.

**Comment by gundogduhasan** [comment]
Hello,
I think i am getting the same error too. I have to angular client with similar config. First client works fine. But second client i added getting error on silent renwe. But after i hit ctrl+r everything works fine. Here is my logs;


[14:02:54 Debug] IdentityServer4.Endpoints.AuthorizeEndpoint
ValidatedAuthorizeRequest
{"ClientId": "<CLIENTNAME>Web", "ClientName": "<CLIENTNAME> Web", "RedirectUri": "http://<CLIENTNAMEURL>/silent-renew.html", "AllowedRedirectUris": ["http://<CLIENTNAMEURL>", "http://<CLIENTNAMEURL>/silent-renew.html"], "SubjectId": "anonymous", "ResponseType": "id_token token", "ResponseMode": "fragment", "GrantType": "implicit", "RequestedScopes": "openid profile role <CLIENTNAME>Api", "State": "4ce6f3477ef1758261b505fc1168974a26vWj6ZUx", "UiLocales": null, "Nonce": "362a528729a69d1a979d0dd070e5ef4066HQDhIUy", "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "none", "MaxAge": null, "LoginHint": null, "SessionId": "", "Raw": {"client_id": "<CLIENTNAME>Web", "redirect_uri": "http://<CLIENTNAMEURL>/silent-renew.html", "response_type": "id_token token", "scope": "openid profile role <CLIENTNAME>Api", "nonce": "362a528729a69d1a979d0dd070e5ef4066HQDhIUy", "state": "4ce6f3477ef1758261b505fc1168974a26vWj6ZUx", "prompt": "none"}, "$type": "AuthorizeRequestValidationLog"}

[14:02:54 Information] IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator
Showing login: User is not authenticated

[14:02:54 Information] IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator
Changing response to LoginRequired: prompt=none was requested

[14:02:54 Information] IdentityServer4.Endpoints.AuthorizeEndpoint
{"ClientId": "<CLIENTNAME>Web", "ClientName": "<CLIENTNAME> Web", "RedirectUri": "http://<CLIENTNAMEURL>/silent-renew.html", "AllowedRedirectUris": ["http://<CLIENTNAMEURL>", "http://<CLIENTNAMEURL>/silent-renew.html"], "SubjectId": "anonymous", "ResponseType": "id_token token", "ResponseMode": "fragment", "GrantType": "implicit", "RequestedScopes": "openid profile role <CLIENTNAME>Api", "State": "4ce6f3477ef1758261b505fc1168974a26vWj6ZUx", "UiLocales": null, "Nonce": "362a528729a69d1a979d0dd070e5ef4066HQDhIUy", "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "none", "MaxAge": null, "LoginHint": null, "SessionId": "", "Raw": {"client_id": "<CLIENTNAME>Web", "redirect_uri": "http://<CLIENTNAMEURL>/silent-renew.html", "response_type": "id_token token", "scope": "openid profile role <CLIENTNAME>Api", "nonce": "362a528729a69d1a979d0dd070e5ef4066HQDhIUy", "state": "4ce6f3477ef1758261b505fc1168974a26vWj6ZUx", "prompt": "none"}, "$type": "Authoriz

**Comment by gundogduhasan** [comment]
I have the similar issue after adding the second client. I explain in here https://github.com/damienbod/angular-auth-oidc-client/issues/1413
My subject id also null like @CobusKruger
