### ISSUE TITLE
Session checks do not work if sts is not at root of domain

### ISSUE THREAD

**Issue by k-schneider** [damienbod/angular-auth-oidc-client#577]
Hello,

Our STS (IDS4) is actually hosted similar to:  

`https://path-to.my-sts.com/auth`

This is causing issues with the check session functionality because there is some code in the message handler that is checking that the origin matches the configured stsServer exactly:

`e.origin === this.configurationProvider.openIDConfiguration.stsServer`

Unfortunately with the example stsServer string above e.origin will just be "https://path-to.my-sts.com" and the handler code will be skipped.

I'm wondering if the proper check here would be to check that e.origin starts with the stsServer value?

**Comment by damienbod** [comment]
@k-schneider thanks for reporting, yes this should be added

**Comment by damienbod** [comment]
fixed in version 10.0.15

thanks for reporting
