### ISSUE TITLE
Client secret feature 

### ISSUE THREAD

**Issue by timhtuite** [damienbod/angular-auth-oidc-client#578]
The configuration should allow for the use of a client secret as some openconnect providers still require the secret. For example [yahoo](https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html#getting-started-auth-code) requires the client secret in the get token request.

**Comment by damienbod** [comment]
@timhtuite  I if client secret is required, then it's the incorrect flow, and you should not be using it. 

a public client should never use a secret, and thus it is not supported here.

hope this helps.

Greetings Damien

**Comment by timhtuite** [comment]
You are correct, I will close this issue. Thank You!
