### ISSUE TITLE
IE10+ and Edge search params

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#58]
Reported by @breaman 
Using the URL class and the searchParams property doesn't seem to be very well supported in many browsers. (https://developer.mozilla.org/en/docs/Web/API/URL). I tried using the url-polyfill to get this working in IE10+ and Edge, but was unsuccessful. Do you know of a way to get this working in more than just Chrome, Firefox, and Opera?

https://github.com/damienbod/angular-auth-oidc-client/commit/8cec12f1bd8cd765f855b5aeca5f22192f9984de

**Comment by damienbod** [comment]
reverted in version 1.3.5

**Comment by breaman** [comment]
I know you reverted this code back already, but after getting some sleep, I did get version 1.3.4 working in Edge and IE11 by adding "url-polyfill" via npm and then importing it in my main.ts file with "import 'url-polyfill';" (in the same area where I added code to import reflect-metadata and zone.js). So if this change needs to be added, it does look like there is a polyfill out there that will allow for it to work. I haven't done extensive testing, but it at least routed correctly to my local IdentityServer instance and allowed me to log in using forms based auth.

**Comment by damienbod** [comment]
Thanks, I reverted due to this issue.
https://github.com/damienbod/angular-auth-oidc-client/issues/59

I needed to have something working in the npm releases. Plan to fix the issue now, might still use it, so your information is really useful. I need a way of sopporting a string like this

/oauth2/v2.0/authorize?p=b2c_1_siupin

Greetings Damien
