### ISSUE TITLE
code flow client with PKCE issue

### ISSUE THREAD

**Issue by dewebeloper** [damienbod/angular-auth-oidc-client#581]
I'm facing with very strange issue on line 
` this.oidcSecurityService.setupModule(openIdConfiguration, authWellKnownEndpoints );`

I'm following this tutorial and when I execute above code line, on SST console I get /connect/authorize request.
But url is like following
```
http://localhost:5001/connect/authorize?
client_id=Plativoo.Mobile
&redirect_uri=https://please_set
&response_type=code
&scope=openid profile email Plativoo.Mobile
&nonce=N0.92708824363343421581682156012
&state=15816818159180.68617943989260490.021681771849732856
&code_challenge=xkUuwHe0A7si1XsohSVChx13WqG_sHhisaRea8-VYtU
&code_challenge_method=S256
&prompt=none
```
**&redirect_uri=** is somehow set to **https://please_set** and that is not value that I put in OpenIdConfiguration.

After that result is unauthorized_client: Invalid redirect_uri.
Tested on angular-auth-oidc-client": "^10.0.2" and angular-auth-oidc-client": "^10.0.14" with Angular 8

What can be wrong here?

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
