### ISSUE TITLE
Initial silent refresh never starts when user not logged in

### ISSUE THREAD

**Issue by alecrt** [damienbod/angular-auth-oidc-client#583]
Hi,

the initial oidcSecuritySilentRenew.startRenew(url) inside refreshSession method never fires if the user is not authorized.

I'm getting also the following warning:
angular-auth-oidc-client.js:332 IsAuthorizedRace: Timeout reached. Emitting.

I don't understand why oidcSecuritySilentRenew.startRenew(url) is inside a pipe of getIsAuthorized?

**Comment by alecrt** [comment]
Changing the result of with the following code makes silent login working

`return this.getIsModuleSetup().pipe(switchMap(() => {
            return this.oidcSecuritySilentRenew.startRenew(url).pipe(map(() => true));
        }));`

**Comment by alecrt** [comment]
Side effect of #579

**Comment by alecrt** [comment]
@damienbod do you need any help to better understand the issue?

**Comment by damienbod** [comment]
see #588 Could you add your thoughts here, for what you require.

**Comment by alecrt** [comment]
Hi damienbod,

This is the use case: a SPA with both public (no login required) and private sections.
This SPA is part of a bigger ecosystem, made by multiple SPA and MVC applications, where an Identity Server 4 manages SSO for all.

In this context, one user can reach the target SPA being already logged-in in the Identity Server (cookie), and we don't want him to click on the login button. Instead, the library should try a silent login against the IDS and, if the cookie is found, authorized the user.

Let me know if you want additional informations.
Thank you very much for you amazing job,
Alessandro
