### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by sgentile** [damienbod/angular-auth-oidc-client#584]
Running this on a new Angular 9 project.

client:159 src/app/app.module.ts(30,5): Error during template compile of 'AppModule'
  Could not resolve angular-auth-oidc-client relative to [object Object]..
src/app/app.module.ts(43,5): Error during template compile of 'AppModule'
  Could not resolve angular-auth-oidc-client relative to [object Object]..
src/app/app.module.ts(47,14): Error during template compile of 'AppModule'
  Could not resolve angular-auth-oidc-client relative to [object Object]..
Can't resolve all parameters for AppModule in /app/src/app/app.module.ts: (?, ?).
src/app/app.module.ts(30,5): Error during template compile of 'AppModule'
  Could not resolve angular-auth-oidc-client relative to [object Object]..
src/app/app.module.ts(43,5): Error during template compile of 'AppModule'
  Could not resolve angular-auth-oidc-client relative to [object Object]..
src/app/app.module.ts(47,14): Error during template compile of 'AppModule'
  Could not resolve angular-auth-oidc-client relative to [object Object]..
Can't resolve all parameters for AppModule in /app/src/app/app.module.ts: (?, ?)

I followed the instructions in the readme

**Comment by FabianGosebrink** [comment]
Can you provide a sample repository where you can not compile?
