### ISSUE TITLE
Automated redirection if not authorized in Authguard

### ISSUE THREAD

**Issue by HassanChmsdn** [damienbod/angular-auth-oidc-client#585]
Hey, in my approach I am trying to redirect the user to the login page of keycloak directly by using the method `this.oidcSecurityService.authorize() `if the user is not authorized in the AuthorizationGuard class:

```
private checkUser(): Observable<boolean> {
    return this.oidcSecurityService.getIsAuthorized().pipe(
      map((isAuthorized: boolean) => {
        if (!isAuthorized) {
         this.oidcSecurityService.authorize();
          return false;
        }
        return true;
      })
    );
  }
```
which is returning high load seen in the console  and a too much recursion error.

Can anybody explain why I'm getting this huge load, and how I can simply force the user to redirect automatically to the login page if there were no authorization!

Thanks a lot. 
@MovGP0

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing. The the docs for Guards once we merge

Greetings Damien
