### ISSUE TITLE
Prevent IdToken expiry check when Silent Renew is off

### ISSUE THREAD

**Issue by jamesikanos** [damienbod/angular-auth-oidc-client#586]
I have a web app where I have not enabled Silent Renew (on purpose).

I am authenticating with IdentityServer4 and retrieve successfully an Access Token (exp 3600 seconds) and an Id Token (exp 300 seconds).

I notice that after 5 minutes, I am auto-logged off (on page refresh) because the Id Token has expired. However, I don't care about this.

Is there a way to suppress the "id token" expiry check and only care about the "access token" expiry?

From reading this SO answer (https://stackoverflow.com/a/45767095) it appears that the Id Token can be discarded and is only used for one-time checks. 

Many thanks.

**Comment by damienbod** [comment]
if the id_token is expired, then the app and user is not longer authenticated, and you should get a new id_token + access token. Maybe you could just increase the lifespan of the id_token. At present the id_token validation cannot be disabled.

**Comment by jamesikanos** [comment]
Understood, thanks for the response.

Would you entertain a PR to make this an option? I am happy to increase the lifespan of the id_token for now, but there may be other scenarios in the future where this is not possible.

**Comment by Zetanova** [comment]
I am facing the same problem with the implementation of an [user session manager](https://github.com/damienbod/angular-auth-oidc-client/issues/763)

After i switch the storage with a session of an other user and call `oidcSecurityService.checkAuth()` 
the result ist false with the debug output: `persisted id_token is expired`.

The session `expiresAt` of the auth session itself is far in the feature.
I think that the `id_token` should only be validated once and after 
it stays valid on the client. 
After all the client gets never a new `id_token` in a long running open session
then it refresh  the `access_token` with the it's `refresh_token`

**Comment by Zetanova** [comment]
I made a PR https://github.com/damienbod/angular-auth-oidc-client/pull/780

**Comment by damienbod** [comment]
Hi @Zetanova @jamesikanos 

Doing a lot of thinking about this. I see don't see a reason to allow an invalid id_token. If the validation for this is disabled, then the code will get complicated for some logout flows and by init and also allow a possible copy paste problem from old id_tokens which have expired.

I think that you can increase the lifespan of the id_token on the server, if you require this. If the token lifespan is short, this is usually for a reason. You can refresh you session if either the access token expires or the id_token expires. 

So if the lifespan of the id_token is not important for you, then just increase this in the STS and all is good. 

hope this is ok for you, and thanks for the PR.

Greetings Damien

**Comment by damienbod** [comment]
released in version 12
