### ISSUE TITLE
Problem with silent-renew after authorize() / logoff()

### ISSUE THREAD

**Issue by jScope** [damienbod/angular-auth-oidc-client#589]
Hello,

I'm currently struggling with the correct setup between Angular 8 and Keycloak 8 Authorization Code Flow with PKCE.

My core problem seems to be, that the silent-renew callback is redirecting me back to an https://localhost/... address but I configured it as http for development purpose:

{
  "stsServer": "https://ripstoken:443/auth/realms/Test",
  "redirect_url": "http://localhost:4200",
  "client_id": "angular-test",
  "response_type": "code",
  "scope": "dataEventRecords securedFiles openid profile",
  "post_logout_redirect_uri": "http://localhost:4200",
  "start_checksession": true,
  "silent_renew": true,
  "silent_renew_url": "http://localhost:4200/silent-renew.html",
  "post_login_route": "/",
  "forbidden_route": "/no-access",
  "unauthorized_route": "/",
  "log_console_warning_active": true,
  "log_console_debug_active": true,
  "max_id_token_iat_offset_allowed_in_seconds": 10
}

In the browser I get an auth request like that:
https://ripstoken/auth/realms/Test/protocol/openid-connect/auth?client_id=angular-test&redirect_uri=https%3A%2F%2Flocalhost%3A4200...

Forced to https, I had to create a self-signed cert on my application localhost to run my local app under https. Now I also hat to create a self-signed cert on my Keycloak which also is in test state for now and which now also has to serve https to my https localhost app.

However if I have all this set up as https and changed

  "redirect_url": "https://localhost:4200",
  "post_logout_redirect_uri": "https://localhost:4200",
  "silent_renew_url": "https://localhost:4200/silent-renew.html",

my this.oidcSecurityService.getIsAuthorized() always returns false but my Keycloak has a valid session for my user.

Please can someone give me some assistance to get this right?

Thank you a lot.

**Comment by jScope** [comment]
Okay I was surprisingly able to solve it partially for my Chrome by visiting:

chrome://flags/#allow-insecure-localhost

and enabling "Allow invalid certificates for resources loaded from localhost"

Now my this.oidcSecurityService.getIsAuthorized() returns true correctly. But once I hit this.oidcSecurityService.logoff();

I'm doing a Keycloak-Roundtrip to logout but this time with an empty redirect uri, my url configuration hasn't changed (see above)

https://ripstoken/auth/realms/Test/protocol/openid-connect/logout?id_token_hint=...&post_logout_redirect_uri=https%3A%2F%2Fplease_set

**Comment by jScope** [comment]
I've fixed another issue. Accidentially I was not passing all my parameters defined in

assets\auth.clientConfiguration.json 

to my OpenIdConfiguration in AppModule constructors  

this.oidcConfigService.onConfigurationLoaded.subscribe() { ... }

Now I have the correct desired configuration and logout redirects work as expected.

But now I'm still experiencing a strange behaviour with silent-renew / this.oidcSecurityService.getIsAuthorized() and login/logout flow.

Here some steps:

1. when I open my app initially I get console output like this:

![01_app_init_not_logged_in](https://user-images.githubusercontent.com/24228798/75980630-2506a100-5ee3-11ea-886e-2a416ec00921.PNG)

I'm not logged in at this moment.

2. After I logged in at Keycloak and have been redirected I get an output like this:

![02_app_after_keycloak_login](https://user-images.githubusercontent.com/24228798/75980710-50898b80-5ee3-11ea-9156-8aa92158769f.PNG)

and getIsAuthorized()  returns false.

3. Now if I just refresh my browser tab I get following console:

![03_app_after_browser_tab_refresh](https://user-images.githubusercontent.com/24228798/75980765-6ac36980-5ee3-11ea-9aa5-2f78b640de6e.PNG)

and getIsAuthorized() returns true.

A similar behaviour occures during logout process. I'm assuming something is wrong in how I included my silent-renew.html. It's just a normal HTML-Page served as an asset of my Angular-App.
angular.json -> architect -> build -> options -> assets -> "src/silent-renew.html"

Is there any further description o´n how to best setup the silent-renew.html?

**Comment by jScope** [comment]
The behaviour changed after I updated to current 10.0.15. Now I'm totally unable to login no matter if http or https. Now whatever I do after redirect I get this console output:

![04_after_update](https://user-images.githubusercontent.com/24228798/76005002-b6d5d480-5f0a-11ea-8588-2ff8f300e06a.PNG)

getIsAuthorized() is always false also after browser refresh.

Please I can anyone help me to get this right?

**Comment by jScope** [comment]
Please @damienbod  can you help a little bit? Why is my iframe src always empty? It's similar behaviour like in #222 . But I'm definetly passing the right silent-renew.url to

const config: OpenIdConfiguration = {
...
    silent_renew: configResult.customConfig.silent_renew,
    silent_renew_url: configResult.customConfig.silent_renew_url
...
}
{
...
  "silent_renew": true,
  "silent_renew_url": "https://localhost:4200/silent-renew.html",
...
}

**Comment by damienbod** [comment]
@jScope Which flow are you using? Does the silent renew html code match for your flow?

**Comment by jScope** [comment]
Hello @damienbod yes it should, I'm using code flow with PKCE as recommended. If it helps my Keycloak PKCE settings are simple 

![05_keycloak_pkce_settings](https://user-images.githubusercontent.com/24228798/76077378-e1726c80-5fa0-11ea-8bb0-e57e342e849f.PNG)

Sitent renew would be really nice to have. But wat would be the expected behaviour if we don't use silent_renew? 

And it was asked before but what is then "start_checksession" and "max_id_token_iat_offset_allowed_in_seconds" for? Is this a separate mechanism?

I removed these additional settings but silent_renew still doesn't work. It's strange to me that my configured silent_renew_url doesn't appear in the src Attribute of the iframe. I remember this worked partially in the past (see screens above under 10.0.14) but I can't figure out the conditions.

**Comment by jScope** [comment]
Hello @damienbod,

we had still no luck with this package. I turned off silent_renew and start_checksession and even removed my real routing (app-routing.module with normal route components and lazy loaded feature modules) to simplify everything.

I've now a simple sign on at my keycloak with a redirect back to my app. But I'm not logged in after redirect, getIsAuthorized() returns false.

authorize sends me to login page:
https://ripstoken/auth/realms/Test/protocol/openid-connect/auth?client_id=angular-test&redirect_uri=https%3A%2F%2Flocalhost%3A4200&response_type=code&scope=openid%20profile%20email&nonce=...&state=...&code_challenge=...&code_challenge_method=S256

Once I return to my app (Keycloak has active session now) I get the following in my app.component:

ngOnInit() {
    this.isAuthorizedSubscription =
      this.oidcSecurityService
        .getIsAuthorized()
        .subscribe((isAuthorized: boolean) => {
          this.isAuthorized = isAuthorized; (**FALSE**)
        });
  }

My session storage doesn't seem to have token:
![06_no_token_after_login](https://user-images.githubusercontent.com/24228798/76201293-52a95e00-61f3-11ea-9c33-f2db221ea883.PNG)

Here are my network requests and console output after successful login redirect back to my app:
![07_network_after_login](https://user-images.githubusercontent.com/24228798/76201733-feeb4480-61f3-11ea-985c-09cd0d57a436.PNG)
![08_console_after_login](https://user-images.githubusercontent.com/24228798/76201737-00b50800-61f4-11ea-940a-92d7d56b5f38.PNG)

Is there anything suspicious to you?

**Comment by jScope** [comment]
Hello @damienbod,

the problem is solved. I was missing some code which I found in the documentation today. I was missing the logic inside app.component constructor

`if (this.oidcSecurityService.moduleSetup) {
      this.doCallbackLogicIfRequired();
    } else {
      this.oidcSecurityService.onModuleSetup.subscribe(() => {
        this.doCallbackLogicIfRequired();
      });
    }`

and

`private doCallbackLogicIfRequired() {
    // Will do a callback, if the url has a code and state parameter.
    this.oidcSecurityService.authorizedCallbackWithCode(window.location.toString());
  }`

This was solving nearly all my problems. I have no idea why I missed that section.

Sorry for the inconvenience.
