### ISSUE TITLE
Question - v1.3.4, anyone seen this?

### ISSUE THREAD

**Issue by pieman302** [damienbod/angular-auth-oidc-client#59]
Have run 1.3.1 / 1.3.2 / 1.3.3 without issue. Went to latest version 1.3.4 and get the error shown in screen dump.

Looking at the code it appears the createAuthorizeUrl is making a call

var /** @type {?} */ customParams = 
  this.oidcSecurityCommon.retrieve(this.oidcSecurityCommon.storage_custom_request_params);
        Object.keys(customParams).forEach(function (key) {
            params.set(key, customParams[key]);
        });

The 'customParams' object is null hence causing the issue I am seeing locally.

I have tried creating a new app from scratch using the quick start tutorial and still see this problem.

Thoughts?
Thanks!

![untitled](https://user-images.githubusercontent.com/25282732/29168892-eed8ce76-7dc8-11e7-9df0-3bcb8ca1c5ee.png)

**Comment by vicver82** [comment]
I'm also getting an error with 1.3.4. I reverted back to 1.3.2 to keep working on my project. I'll post the error output here at the earliest opportunity.

**Comment by damienbod** [comment]
looks like 1.3.4 has a bug here. Use 1.3.3 and I'll fix today. Sorry

Greetings Damien

**Comment by damienbod** [comment]
@robisim74 The tests run local, but fail on the server, any ideas?

https://travis-ci.org/damienbod/angular-auth-oidc-client/builds/263122531

**Comment by robisim74** [comment]
Are you calling an external url inside the test?

**Comment by damienbod** [comment]
Yes, I can remove this, thanks

**Comment by robisim74** [comment]
Maybe there is a way, but it is not simple: https://assertible.com/blog/how-to-run-api-integration-tests-on-ci

Usually it is better to create a mock backend or a mock service.

**Comment by pieman302** [comment]
Thanks guys, appreciated :-)

**Comment by damienbod** [comment]
fixed in verion 1.3.5
