### ISSUE TITLE
silent renew iframe error

### ISSUE THREAD

**Issue by koo9** [damienbod/angular-auth-oidc-client#590]
hi 

Getting this error when it's doing silent renew:

Refused to display 'https://localhost:44385/home/error?errorId=CfDJ8AYyttD0Yl1Ov-y-FXDxH2P0-9pJ7-hxGDRwVsYkW9mKghhtH4dKfFden02ijH3Eu4B2_VDtolE1uqrXP21U0XIIGWfghozg13BdafBBkeP465RynRvD-rQ_onqkW0kdgZYNyo2QlDaTLHGr-_BSYACM1SJZpMGWdNBQ-MzZq_xUmB6SBOtJ_FlSsYqtL0iYfbcBNgl9kHbfqhEzWPK1zweXn3gslZ743qVf0kZtQP_qCh4uQC02CygBO_889O-CIgAG7oDGIJouwKEwWuKtX-RY2RjfNZvgsvOtZFly_atUsNiG6NwYBVdLn-HDUnRWiw' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

what could cause this?

Thx

**Comment by damienbod** [comment]
Hi @koo9 

The is the securtiy settings on the server blocking your request. You need the server to update its CSP to remove the none and add your client domain.

Greetings Damien

**Comment by koo9** [comment]
@damienbod here's the CSP for IDP. 
` // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
                var csp = "default-src 'self'; object-src 'none'; frame-ancestors 'none'; sandbox allow-forms allow-same-origin allow-scripts; base-uri 'self';";
                // also consider adding upgrade-insecure-requests once you have HTTPS in place for production
                //csp += "upgrade-insecure-requests;";
                // also an example if you need client images to be displayed from twitter
                // csp += "img-src 'self' https://pbs.twimg.com;";

                // once for standards compliant browsers
                if (!context.HttpContext.Response.Headers.ContainsKey("Content-Security-Policy"))
                {
                    context.HttpContext.Response.Headers.Add("Content-Security-Policy", csp);
                }
                // and once again for IE
                if (!context.HttpContext.Response.Headers.ContainsKey("X-Content-Security-Policy"))
                {
                    context.HttpContext.Response.Headers.Add("X-Content-Security-Policy", csp);
                }`
where to add the client domain?

**Comment by damienbod** [comment]
You could do it something like this (using NWebSec) 

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/StsServerIdentity/Startup.cs#L177

**Comment by koo9** [comment]
@damienbod thx will take a look.

**Comment by koo9** [comment]
it seems like it's the issue with the silent-renew.html. after correcting that. the silent renew works! no changes made on the IDS side.

**Comment by bsheriff** [comment]
@koo9 I am having the same issue how did you end up correcting this?  I see you mentioned "it's the issue with the silent-renew.html".  What exactly did you fix in that file?  Do you mind explaining a little further, I am kind of stuck on this problem.  

Thank You

**Comment by koo9** [comment]
@bsheriff it's the path to silent-renew.html. make sure the path is correct.

**Comment by bsheriff** [comment]
@koo9  thanks for the quick response, but I am still a bit confused, do you mind being a bit more specific on what you mean by "path", I updated the silent-renew.html file based on what the documentation had said.

**Comment by koo9** [comment]
the path is the correct url to silent-renew.html. i made a mistake by pointing to a wrong url.
