### ISSUE TITLE
isauthorized returns false when the user has an active session in identity server

### ISSUE THREAD

**Issue by marcopierobon** [damienbod/angular-auth-oidc-client#591]
Hey,

We've a legacy angularjs mcv apps that uses identity server with the client credentials flow.

We've set up a new angular8 spa that integrates with the same identity server through the code authorization flow. In this app, we're using the angular-auth-oidc-client library.

The user scenario would be to always start and login from the mvc app and then load the spa one.
We cannot seem to be able to get SSO working: on the first request to the SPA the isAuthorized value is always false, and hence no token is generated without going through the login page.

Our configuration is:

    const openIdConfiguration: OpenIdConfiguration = {
        stsServer: authorizatonURL,
        redirect_url: this.originUrl + 'callback',
        client_id: this.configService.getSecurityClientIdentifier,
        response_type: 'code',
        scope: this.configService.getSecurityScopes,
        post_logout_redirect_uri: this.originUrl,
        forbidden_route: '/forbidden',
        unauthorized_route: '/unauthorized',
        silent_renew: false,
        silent_renew_url: this.originUrl,
        history_cleanup_off: true,
        auto_userinfo: true,
        log_console_warning_active: true,
        log_console_debug_active: true,
        max_id_token_iat_offset_allowed_in_seconds: 10,

    };

Is this achievable with this library?

**Comment by damienbod** [comment]
The login is correct (you could automatically call the login), and the secure token server should complete the login without user interaction unless the consent is required, which can be turned off. The second auth call would then use the silent renew which would be automatic. 

Greetings Damien

**Comment by marcopierobon** [comment]
Hey, thanks for getting back so quickly. What do you mean with 

> The login is correct (you could automatically call the login)

We have several MVC apps that already use SSO, so I do not believe the consent is an issue.

Are you saying that the SSO into the SPA would be achieved through the silent_renew?

I tried turning it on with 

    silent_renew: true,
    silent_renew_url: this.originUrl + 'silent-renew.html',

And adding the silent-renew.html page from the example

    <!doctype html>
    <html>
    <head>
        <base href="./">
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>silent-renew</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    </head>
    <body>

        <script>
        window.onload = function () {
          /* The parent window hosts the Angular application */
          var parent = window.parent;
          /* Send the id_token information to the oidc message handler */
          var event = new CustomEvent('oidc-silent-renew-message', { detail: window.location });
          parent.dispatchEvent(event);
        };
        </script>
    </body>
    </html>

But in the console logs I get 

	STS server: https://MySTSServer/authentication
	VM269 app.bundle.js:132389 Silent Renew is active, check if token in storage is active
	VM269 app.bundle.js:132389 Silent Renew or login not running, try to refresh the session
	VM269 app.bundle.js:132389 BEGIN refresh session Authorize
	VM269 app.bundle.js:132389 RefreshSession created. adding myautostate: 15834930302090.97817730212502040.35327221663249775
	VM269 app.bundle.js:132389 <iframe id=​"myiFrameForSilentRenew" style=​"display:​ none;​">​…​</iframe>​
	VM269 app.bundle.js:77733 Angular is running in the development mode. Call enableProdMode() to enable the production mode.


And I'm still prompted for login. Is this wrong configuration on my end?

**Comment by marcopierobon** [comment]
My issue was related to the connection to the authorization endpoint differing in casing between the various applications (mysecurityserver/authentication vs mysecurityserver/Authentication). This was making the idsrv and idsrvsession keys being stored in different cookies.
