### ISSUE TITLE
refreshing browser after authenticated, silent renew won't run

### ISSUE THREAD

**Issue by koo9** [damienbod/angular-auth-oidc-client#593]
it looks like the lib is trying to do a silent renew but failed. here's the log messages:

STS server: https://localhost:44385
Silent Renew is active, check if token in storage is active
Silent Renew or login not running, try to refresh the session
BEGIN refresh session Authorize
RefreshSession created. adding myautostate: 15835175997450.65827223791874070.26752385569683357
`<iframe id="myiFrameForSilentRenew" style="display: none;"></iframe>`
no state in url
IsAuthorizedRace: Timeout reached. Emitting.
IsAuthorizedRace: Completed
getIsAuthorized: false

by default , the token is stored in memory, correct? so when refreshing the browser, it will be gone. 
question is how to make it such that the silent renew still work after refreshing the browser?

**Comment by koo9** [comment]
add a custom local storage won't help to survive the browser refresh.

**Comment by koo9** [comment]
also if the user don't logout and close the browser, next time open the site, it won't redirect to login, instead it's trying to do silent renew. it's correct that the session is still valid on the server but the client already lose the silent renew info.

**Comment by GabrielGil** [comment]
I think this may be a duplicated of #588. Version 10.0.15 was the problem for me and downgrading to 10.0.14 worked just fine.

**Comment by damienbod** [comment]
dupe, please add you thoughts in #588 I plan a refactor here
