### ISSUE TITLE
Authorizing in a popup or iframe, iframe won't close after authentication

### ISSUE THREAD

**Issue by koo9** [damienbod/angular-auth-oidc-client#594]
the iframe does not close, instead it loads the app again in the iframe. nothing happen to the parent window. is it supposed to behave like this?

**Comment by ferryferry** [comment]
When using a popup, the login page is shown in the popup, and then I see the whole app in the popup. (logged in). And the main window is still not logged in... Looks like the same issue as @koo9 instead in a popup?

**Comment by gustavomarty** [comment]
I have the same problem using login with a new window. Is there any thing that i can do?

**Comment by arv9135** [comment]
Same issue with me

**Comment by damienbod** [comment]
We will add a popup feature, or support for this. I haven't tried this yet and don't know how what state or what is required to support this. We have added electron support in 11.2.0, and this goes in this direction.

**Comment by FabianGosebrink** [comment]
Will be in the 11.5.0 Release. Enjoy!
