### ISSUE TITLE
Slow login problem

### ISSUE THREAD

**Issue by aiscrim** [damienbod/angular-auth-oidc-client#596]
If the IdentityServer is slow upon login (e.g. because it's starting up after a period of being idle), then the silent renew and the normal login flow seem to get mixed up. I receive an AuthorizationState.unauthorized result and if I look into the Identity Server logs, the error is:

Invalid redirect_uri{"redirectUri": "http://localhost:4200/silent-renew.html", "expectedRedirectUri": "http://localhost:4200/callback"}

Any idea of what might be happening here?

**Comment by jorisbrauns** [comment]
There is someone with the same error which you can find here:
https://github.com/damienbod/angular-auth-oidc-client/issues/519
