### ISSUE TITLE
id_token : alg : HS256 support

### ISSUE THREAD

**Issue by anshmathur** [damienbod/angular-auth-oidc-client#597]
Hi, 
I need to understand why other algorithms are not supported for id_token. 
https://tools.ietf.org/html/rfc7518#section-3.1
mentions various algorithms that are applicable. Is there a specific reason for using RS256 and can HS256 be added in a future enhancement?
Thanks

**Comment by damienbod** [comment]
@anshmathur They is no reason apart from I have never got around to it. This would be a good enhancement.

**Comment by damienbod** [comment]
will be part of release 11. Thanks for reporting. You will need to updtae the jsrsasign-reduced to 8.0.15 when this gets published
