### ISSUE TITLE
Ngrx way

### ISSUE THREAD

**Issue by inpicksys** [damienbod/angular-auth-oidc-client#602]
I'm trying to implement auth flow with ngrx.
Basing on https://github.com/damienbod/angular-auth-oidc-client/issues/400
as it mentioned it works.
For now I have endless loop without ability to login.
Will be appreciated for help as it blocking totally my work.

Can share repo if someone can take it review.

**Comment by FabianGosebrink** [comment]
Yeah, please share a repository to take a look. We can review this.
