### ISSUE TITLE
Authorization not working when app hosted by ASP.NET Core

### ISSUE THREAD

**Issue by aiscrim** [damienbod/angular-auth-oidc-client#603]
Hi, I have a strange issue, I hope you can help me identify what the problem is.
I have an Angular app that uses your library to authenticate and makes calls to an API written in ASP.NET Core 2.2. When the two applications are deployed separately everything works fine.
I have now a new need: the static files generated by ng build should be served by the API application itself.
In order to do that, I copied these files to the wwwroot folder of the API and configured it this way to redirect the not found results to the Angular main page, as it's suggested in various articles:

`
app.Use(async (context, next) => {

                await next();

                string pathValue = context.Request.Path.Value.ToLower().Trim('/');
                if (context.Request.Method.ToUpper() == "GET" && context.Response.StatusCode == (int)HttpStatusCode.NotFound && 
                    !Path.HasExtension(pathValue))
                {
                    context.Request.Path = "/index.html";
                    context.Response.StatusCode = (int)HttpStatusCode.Redirect;
                    await next();
                }
            });
`

With this configuration in place, what happens is that everything runs normal until the call to authorizedCallbackWithCode, which prints the 'running validation for' message in the console, but then doesn't proceed requesting the token.
The result is that my app doesn't authenticate and the url remains the one of the callback, with the code, scope, state and session_state querystring parameters correctly filled in.

Any help would be much appreciated!

**Comment by nickoarg** [comment]
Replace "!Path.HasEtension(pathValue))" with 
`(!Path.HasExtension(pathValue) || pathValue.StartsWith("callback"))`
and edit the config to have 
`redirect_url: this.originUrl + 'callback',`

**Comment by aiscrim** [comment]
Hi Nick, thanks but in the end the issue was completely unrelated to this library, so I'm gonna close this issue.
