### ISSUE TITLE
Missing required parameter: grant_type when requesting token from Azure AD B2C

### ISSUE THREAD

**Issue by tpatikirikorala** [damienbod/angular-auth-oidc-client#604]
I am using the latest version  "angular-auth-oidc-client": "10.0.15" and trying to connect to azure ad b2c. I was able to connect successfully with the implicit flow using version 8.0.3. However, in order to use _code flow_, I updated the lib and code to support the latest version. I can login successfully however afterward this is the result I end up getting. Angular app loops between /autologin and ?state requests infinitely. 

![image](https://user-images.githubusercontent.com/29444156/76913104-2768f200-690a-11ea-910b-6ac47032418d.png)

Although the logged error shows cors issues, when I browse to onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_signin the error is 
'"error":"invalid_request","error_description":"AADB2C90083: **The request is missing required parameter: grant_type**.\r\nCorrelation ID: '

**Comment by damienbod** [comment]
I haven't tested the latest version against Azure AD B2C. Need to check this

**Comment by mathieu2em** [comment]
well I have the same issue

**Comment by bsomeshwer** [comment]
Please send GET request instead of POST. Docs say POST but it is working with GET request.
