### ISSUE TITLE
Issue with silent renew when js execution has been suspended.

### ISSUE THREAD

**Issue by remkoboschker** [damienbod/angular-auth-oidc-client#605]
We are using refresh tokens and silent renew. When js execution has been suspended (for instance when you close the lid on your mac), polling stops, the refresh token has expired en when execution resumes we get an invalid grant error from our idp. Should this trigger an attempt to log in here? https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/services/oidc.security.service.ts#L397 Or at least update the authorazation status?

**Comment by damienbod** [comment]
@remkoboschker Not really sure here. I have the habit of always refreshing after closing my MAC book.

**Comment by remkoboschker** [comment]
Is the issue not that a failed request with an expired refresh token should change the authorisation status?

**Comment by damienbod** [comment]
@remkoboschker  This is fixed in verions 11, thanks for reporting

Greetings Damien
