### ISSUE TITLE
Master issue new version 11

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#609]
This is the master issue for planning the new release of version 11. Following features are planned:

- <s>Refactor lib config to make it easier to use</s>
- <s>Update project to Angular 9</s> https://github.com/damienbod/angular-auth-oidc-client/issues/610
- <s>add examples </s> https://github.com/damienbod/angular-auth-oidc-client/issues/625
- <s>support refresh tokens with example, and docs (coming safari change)</s>
- <s>refactor configuration property names</s>
- <s>eslint conform</s> https://github.com/damienbod/angular-auth-oidc-client/issues/627
- <s>Remove avoidable classes and add interfaces instead</s> https://github.com/damienbod/angular-auth-oidc-client/issues/626
- <s>Create Loglevel enum instead of boolean "isxyzactive" </s>https://github.com/damienbod/angular-auth-oidc-client/issues/628
- <s>Add prefix configuration for storage to allow multiple angular run in parallel</s> https://github.com/damienbod/angular-auth-oidc-client/issues/634
- <s>Add an event service with an enum to throw events out </s>https://github.com/damienbod/angular-auth-oidc-client/issues/635
- <s>Make folders for features not `services`, etc.</s> #636
- <s> SilentRenew breaks when using refresh_token and refresh_token is expired/invalid </s>https://github.com/damienbod/angular-auth-oidc-client/issues/667
- <s>Pack the tests beside the files which are being tested when feature folders are available</s> #637
- <s>support multiple instances in browser</s> 
- <s>Do not provide default config when config should have been set before</s> #644
- <s>Code Verifier not cryptographically random</s> https://github.com/damienbod/angular-auth-oidc-client/issues/642
- <s> After successful login, getIsAuthorized still returns false for a bit. </s>https://github.com/damienbod/angular-auth-oidc-client/issues/549
- <s>Expose silent renew running observable</s> https://github.com/damienbod/angular-auth-oidc-client/issues/447
- <s>Issue with silent renew when js execution has been suspended</s> https://github.com/damienbod/angular-auth-oidc-client/issues/605
- <s>Add support for OAuth 2.0 Token Revocation</s> https://github.com/damienbod/angular-auth-oidc-client/issues/673
- <s>Silent renew dies if startRenew fails</s> https://github.com/damienbod/angular-auth-oidc-client/issues/617
- <s>support for Angular 8 , Angular 9 </s>
- <s>redesign login init</s>
- <s>Remove avoidable `any`s </s> https://github.com/damienbod/angular-auth-oidc-client/issues/624
- <s>Use returned expired value of access token for expired validation</s>
- <s>Id_Token is rejected because of timing issue when server hour is different then client hour </s> 
https://github.com/damienbod/angular-auth-oidc-client/issues/175
- <s>fix validate, fix max time offset</s>
- <s>Support azp and multiple audiences</s> https://github.com/damienbod/angular-auth-oidc-client/issues/582
- <s>Add extra Refresh token validation</s> https://github.com/damienbod/angular-auth-oidc-client/issues/687
- <s>Notification that checking session is initialized</s> https://github.com/damienbod/angular-auth-oidc-client/issues/686
- <s>Refactor rxjs events, user profile events, silent renew, check session</s>
- <s>Add support for EC certificates</s> https://github.com/damienbod/angular-auth-oidc-client/issues/645
- <s>id_token : alg : HS256 support</s> https://github.com/damienbod/angular-auth-oidc-client/issues/597
- <s>redesign docs </s>

In general the idea with this release is to make it easier to use, and improve the rxjs implementation.

Please comment here for improvement suggestions

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/588

**Comment by inpicksys** [comment]
@damienbod  Please. say - when approximately release planned?

**Comment by damienbod** [comment]
@inpicksys I guess it will take about 2 weeks, so when I start plus 2 weeks, kind of busy at the moment, and don't have time to start this yet.

**Comment by damienbod** [comment]
work for this will be merged in this branch
https://github.com/damienbod/angular-auth-oidc-client/tree/dev_examples

**Comment by damienbod** [comment]
Following examples will be added to project:

- basic code flow
- code flow with silent renew
- code flow with refresh tokens
- code flow auto login
- code flow with guard, interceptor, api calls
- code flow with config from http request
- implicit flow with silent renew
- code flow with Azure AD
- code flow with google

**Comment by FabianGosebrink** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/624

**Comment by ntsehaye** [comment]
wondering when this release will be available? thanks

**Comment by damienbod** [comment]
Hi @ntsehaye very soon now, we have done most of the testing now, and all seems good We just have the docs left now and then we will publish

**Comment by inpicksys** [comment]
@damienbod happy labor day!

**Comment by ntsehaye** [comment]
> Hi @ntsehaye very soon now, we have done most of the testing now, and all seems good. We just have the docs left now and then we will publish

thank you for the update! appreciate it!
