### ISSUE TITLE
reopen site without logout error

### ISSUE THREAD

**Issue by koo9** [damienbod/angular-auth-oidc-client#611]
after login then close the browser, reopen the site, getting authentication error. please see screen capture.
![renew failed](https://user-images.githubusercontent.com/8421906/77194142-fd980280-6aa4-11ea-95b8-2146e7e8afb4.PNG)

seems like the state is not set in the renew url.

**Comment by damienbod** [comment]
This has been refactored and changed in version 11 which we plan to release in the next few days after testing

Greetings Damien
