### ISSUE TITLE
NullInjectorError: No provider for OidcSecurityService

### ISSUE THREAD

**Issue by patelhirn** [damienbod/angular-auth-oidc-client#613]
Hi,

I am using this library in two projects and both are throwing different error with the latest Angular .

**Project #1 **
I am getting **NullInjectorError: No provider for OidcSecurityService!** while running the application. 

> main.ts:12 NullInjectorError: R3InjectorError(AppModule)[CoreModule -> AuthenticationService -> OidcSecurityService -> OidcSecurityService -> OidcSecurityService]: 
>   NullInjectorError: No provider for OidcSecurityService!    
>     at Object.AuthenticationService_Factory [as factory] (http://localhost:4200/main.js:901:177)

If I include "OidcSecurityService" in providers then it starts throwing another error **(NullInjectorError: No provider for OidcDataService!)**:

> NullInjectorError: R3InjectorError(AppModule)[CoreModule -> AuthenticationService -> OidcSecurityService -> OidcDataService -> OidcDataService -> OidcDataService]: 
>   NullInjectorError: No provider for OidcDataService!
> 

I believe I shouldn't include OidcDataService in providers as this stops building the application.

**Project #2**
I do have another project using the same package and that's throwing some weird error ""

> Compiling angular-auth-oidc-client : es2015 as esm2015
> ERROR in Cannot read property 'push' of undefined

BTW  both the projects have below setup: 

> Angular: 9.0.3
> rxjs: 6.5.4
> angular-auth-oidc-client : 10.0.15
> Node:  v13.1.0

Can you help me to resolve this?

Thanks
Hiren

BTW Sample Code:

AuthenticationService.ts (I just copy the constructor)
```
import { Injectable, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders } from '@angular/common/http';
import { Router } from '@angular/router';

import { AuthorizationResult, OidcConfigService, OpenIdConfiguration, ConfigResult, AuthorizationState, 
  OidcSecurityService } from 'angular-auth-oidc-client';
import { Observable } from 'rxjs';
import { StorageService } from '../storage/storage.service';

export class AuthenticationService implements OnInit, OnDestroy {
  private isAuthorized = false;
  private readonly impersonationTokenKey: string = 'impersonationToken';
  private readonly redirectKey: string = 'redirect';

  constructor(private oidcSecurityService: OidcSecurityService, private oidcConfigService: OidcConfigService,
              private storageService: StorageService, private router: Router) {
    if (this.oidcSecurityService.moduleSetup) {
      this.onOidcModuleSetup();
    } else {
      this.oidcSecurityService.onModuleSetup.subscribe(() => {
        this.onOidcModuleSetup();
      });
    }

    this.oidcSecurityService.onAuthorizationResult.subscribe((authorizationResult: AuthorizationResult) => {
      this.onAuthorizationResultComplete(authorizationResult);
    });
```

CoreModule.ts
```
import { StorageService } from './services/storage/storage.service';
import { NgModule, Optional, SkipSelf, APP_INITIALIZER, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { AuthModule, OidcConfigService, OidcSecurityService } from 'angular-auth-oidc-client';
import { AuthenticationService } from './services/authentication/authenticationService';
import { AutoLoginComponent } from './components/autologin/autologin.component';
import { RouterModule, Routes } from '@angular/router';

// configure OIDC service via settings provided by server
// export function loadConfig(oidcConfigService: OidcConfigService): () => Promise<any> {
//   // return () => oidcConfigService.load('http://localhost:5011/api/configuration/oidcsettings');
//   return;
// }


const routes: Routes = [
  {
    path: 'autologin',
    component: AutoLoginComponent,
  }
];

@NgModule({
  declarations: [
    AutoLoginComponent
  ],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ],
  imports: [
    RouterModule.forChild(routes),

    AuthModule.forRoot(),
    CommonModule,
    FormsModule
  ],
  exports: [
  ],
  providers: [
    OidcConfigService,
    AuthenticationService,
    StorageService
    // {
    //   provide: APP_INITIALIZER,
    //   useFactory: loadConfig,
    //   deps: [
    //     OidcConfigService
    //   ],
    //   multi: true
    // },
  ]
})
export class CoreModule {
  constructor(private authenticationService: AuthenticationService) {
    this.authenticationService.configure();
  }
}
```

**Comment by damienbod** [comment]
@FabianGosebrink Any idea here?

**Comment by FabianGosebrink** [comment]
Hey @patelhirn , we have a sample app in this repo which is using the library. https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/sample-code-flow/src/app/app.module.ts . It is not throwing the error. If you still hav ethe issue, can you provide a sample repository that we can have a look and maybe fix the library with that? Thanks.

**Comment by patelhirn** [comment]
Hi  @FabianGosebrink,

Thanks for the sample code and now it's working as expected. but Can you help me with token clear out after few seconds. after successfully authorization, authorizationResult is clearing out.
Am i missing some configuration or need to set something. How can i stop to clear out from the browser store.

![image](https://user-images.githubusercontent.com/9003879/77608387-6d6a1b00-6ef3-11ea-932b-6e04985ee7b2.png)

After few second you can see data is clear out. so in interceptor when i am trying to getToken it returned null.

![image](https://user-images.githubusercontent.com/9003879/77608417-81158180-6ef3-11ea-8f64-03f6926c28e6.png)

Thanks for your support.

Thanks
Hiren

**Comment by FabianGosebrink** [comment]
@damienbod ?

**Comment by OscarMtz-96** [comment]
Hello, im facing the same issue, but for me after setting OidcSecurityService on providers, im getting this error:

```
Failed: R3InjectorError(DynamicTestModule)[OidcSecurityService -> CheckSessionService -> CheckSessionService]:
          NullInjectorError: No provider for CheckSessionService!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'OidcSecurityService', 'CheckSessionService', 'CheckSessionService' ] })
```
        
I've tried following the given URL but its not available anymore, any help on this?

**Comment by FabianGosebrink** [comment]
Did you include the module from the lib into the module you need the service in?

**Comment by KuntadyYathish** [comment]
@FabianGosebrink - We are building an angular based micro front end app(Nx framework). We are creating a library which can provide Open ID connect feature for Azure AD and then import the library in Host app or remote micro front end apps.

1. Created Authentication.service.ts in library 
`@Injectable({
  providedIn: 'root',
})
export class AuthenticationService {
  private user: any;
  private authenticated!: boolean;

  constructor(public oidcSecurityService: OidcSecurityService) {}`  

2. index.ts having an export code 
`export * from './lib/shared-util-oidc.module';
export * from 'angular-auth-oidc-client';
export * from './lib/service/authentication.service';
`
3. If I inject  AuthenticationService in hosting app (i.e., Shell in my case), I'm able to access the all information from OidcSecurityService
4. However, if I inject AuthenticationService in Remote app (i.e., Dashboard, ToDo etc), I'm getting below error 
![image](https://user-images.githubusercontent.com/42120164/150980045-9be17aa3-670c-4fd3-88a0-92e0f53ad26c.png)

Module file
![image](https://user-images.githubusercontent.com/42120164/150980324-4399fe8d-457c-4d03-8ae0-b6ca73410161.png)

![image](https://user-images.githubusercontent.com/42120164/150980427-27192d9f-93c8-4ef9-a8e3-1f229b4a3564.png)

**Comment by Xelit3** [comment]
Dear all those who continue to have this problem,

I'm not an active developer of the tool but I have been implementning in some projects, (thanks for it to the owners and contributors)

Let me explain how I have solved this particular problem that I have faced and you too.

The problem was solved from my side because AuthModule from _angular-auth-oidc-client_ was not imported, I think just as @FabianGosebrink  is trying to say.

```javascript
import { 
   AuthModule, //This was missing
   ConfigResult, 
   OidcConfigService, 
   OidcSecurityService, 
   OpenIdConfiguration } 
from 'angular-auth-oidc-client';
```

```javascript
  imports: [
      [...] //More stuff
      HttpClientModule,
      AuthModule.forRoot(), //This was missing
      [...] //More stuff
  ],
```

I have worked with version 6, 10 and 13, you can follow exxamples here:
- [Version 6](https://github.com/HWouters/ad-b2c-oidc-angular/blob/master/src/app/app.module.ts)
- [Version 10](https://github.com/damienbod/AspNetCoreAngularSignalRSecurity/blob/6274e5f04cea6e3d57137e7bd2fc1fb01e180aa2/DirectMessagesAngular/angularApp/app/app.module.ts)
- [Version 13](https://nice-hill-002425310.azurestaticapps.net/docs/samples/samples)

I hope it works for you all

Best regards

**Comment by KuntadyYathish** [comment]
@Xelit3 , I have imported AuthModule. 

In the latest version .forRoot needs a parameter "passedConfig". Is there any repository for ODIC implementation on monorepo project that can be referred? Thanks

**Comment by Xelit3** [comment]
Are you asking for [that](https://github.com/damienbod/angular-auth-oidc-client/tree/version-13#configuration) ?

You can in fact create your own AuthModule, main documentation helps you with that, you can also use the following command:

> ng add angular-auth-oidc-client

Best regards

**Comment by rd-Lyuben-Petkov** [comment]
> @Xelit3 , I have imported AuthModule.
> 
> In the latest version .forRoot needs a parameter "passedConfig". Is there any repository for ODIC implementation on monorepo project that can be referred? Thanks

I have the same problem with version 13. Do you managed to find a solution?

**Comment by rd-Lyuben-Petkov** [comment]
> @Xelit3 , I have imported AuthModule.
> 
> In the latest version .forRoot needs a parameter "passedConfig". Is there any repository for ODIC implementation on monorepo project that can be referred? Thanks

Hi, I am trying to achieve the same goal with a custom library. Did you find any solution to the problem?
