### ISSUE TITLE
Problem with IE11

### ISSUE THREAD

**Issue by giuliopardi** [damienbod/angular-auth-oidc-client#614]
Hi, I'm having an issue with IE11: after having added the library to my project, in "ng serve" mode, browsing locally on http://localhost:4200 I receive an error SCRIPT1010: Expected identifier vendor.js (134063, 148035)  at this line of code: "const { EDSA } = KJUR.crypto;"
Otherwise, if I build the project in "prod" mode I don't receive any error.
Other browsers (chrome, firefox, edge) work fine.

Thanks for any help.
Giulio

**Comment by damienbod** [comment]
@giuliopardi  You probably need to add a polyfill.  Or maybe you need to fix it like this:

https://github.com/damienbod/angular-auth-oidc-client/issues/520

Also use https and not HTTP. Also consider not supporting IE as Edge is the new windows browser.

Greetings Damien

**Comment by giuliopardi** [comment]
I applied the fix as in #520 
Now it works

Thanks a lot

**Comment by funnyuser2** [comment]
> I applied the fix as in #520
> Now it works
> 
> Thanks a lot

Do you have details on what you done exactly?
