### ISSUE TITLE
IE - Just shows Loading..... Other Browsers are fine

### ISSUE THREAD

**Issue by funnyuser2** [damienbod/angular-auth-oidc-client#618]
Pulled down this to my local but when loading in IE is just shows Loading ... so it is like IE cannot launch the auto login ... All other browsers are fine ... 

Anyone seeing the same issue ?

**Comment by damienbod** [comment]
@funnyuser2 You probably need to add a polyfill. Or maybe you need to fix it like this:

#520

Also use https and not HTTP. Also consider not supporting IE as Edge is the new windows browser.

Greetings Damien

**Comment by funnyuser2** [comment]
here are my polyfills

import 'core-js';
import 'ie-shim';
import 'isomorphic-fetch';
import 'zone.js/dist/zone'; 

i;ve tried that fix also .. still no joy ... It looks to be an IE issue .. Does the redirect work in IE for you?

**Comment by damienbod** [comment]
I only use IE for 1 client, and it works fine, had to use the jsrasign directly with the polyfills. Rest of my clients don't support IE, now using Edge, Firefox, Chrome, Brave, Safari

**Comment by funnyuser2** [comment]
Hum .. Would you have a sample app where the auto-login to STS is working in IE that you could share .... My customer needs to have this working in IE ....

**Comment by funnyuser2** [comment]
@damienbod F12 Developer shows an error

SCRIPT1010: Expected identifier
vendor.js (82607, 148035)
