### ISSUE TITLE
silent-renew with custom baseHref

### ISSUE THREAD

**Issue by sabrinaToulouse** [damienbod/angular-auth-oidc-client#619]
Hi,

My app run with (angular.json) : 
`"baseHref": "/account/",`

I've set up the silent-renew functionnality, this is working fine except that when the token refresh is done, lib tries to navigate on /account path. I've intercepted navigation with : 

```
this.router.events.subscribe(value => {
      console.trace("navigate!", value)
    });
```
Meaning that navigation happen on http://localhost:4200/account/account

Obviously this route doesn't exists and so I get an error in console : 

> ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'account'

What should I do to resolve this?
Thx =)

**Comment by damienbod** [comment]
Hi @sabrinaToulouse 

You should be able to set the URL for this, but I can't remember how I did this. Will try to find this

Greetings Damien

**Comment by damienbod** [comment]
closing this as I believe this to be an angular routing problem.
