### ISSUE TITLE
Error: No provider for Router!

### ISSUE THREAD

**Issue by CesarD** [damienbod/angular-auth-oidc-client#63]
I get this when I try to run my app.
I guess you left this so the developer perforns the configuration by himself, right?
What happens if I'm using another routing provider like ui-router??

**Comment by CesarD** [comment]
Yes, I am using ui-router.

I haven't taken a good look into the code yet, but do you redirect by url or do you really need some api from the angular router?

**Comment by damienbod** [comment]
Yes the router is used after a successful login. You would need to change the router calls in the service

https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.service.ts

Just for my knowlegde, why are you using the ui-router?, I've never considered this

Greetings Damien

**Comment by CesarD** [comment]
Well, to be honest I'm fairly new to Angular 4 since I'm coming from AngularJS 1.6.x, and I'm definitely biased towards ui-router because it was the best routing provider in AngularJS, way better than the built-in one. It handles states instead of routes, allows nested states and views, passing states parameters without url params, amongst many other things. 
Now, I'm not fully versed in the angular 4 router, but I'm more inclined to stick to ui-router rather than with the other.

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink 

Should we support the ui-router? What do you think, the default router is used in almost 99.9% of all Angular 4 apps.

**Comment by FabianGosebrink** [comment]
I have never heard of another router in angular (4) tbh... Angular has a routing system which is officially documented, supported and there are even books about it. Its the way to route in angular. Therefore I am not thinking we should support any other router options than the standard angular one.

**Comment by CesarD** [comment]
I've been digging a bit more about the native routing provider for angular 4 and from what I've read, some people say they took stuff from the AngularJS ui-router to build the new one better and more similar. 
So, stepping a bit aside from the original question, do you think the native one now has less flaws and cons than the one from AngularJS (1.x) and comparable to what ui-router offered in the old angular??

(If I won't be missing anything from one routing provider to the other, of course I'd prefer to stick with what is official and make full use of your library as it's the best one I've found to handle OIDC for Angular 4 ;) )

**Comment by FabianGosebrink** [comment]
From my point of view you will navigate yourself into a position where you stuck if you mix another router with angular. You will have more support, better documentation and a better community feedback if you walk the router way angular suggests you. Maybe do an example app to test if it fits your needs (I am sure it will)

**Comment by CesarD** [comment]
Yeah, from what I've read it SHOULD fit the needs, though I haven't gone very deep into all differences, hence my doubts. And from the (bad) experiences I had with the native routing on AngularJS (1.x), that's why I was sticking with ui-router by default (if you worked with AngularJS you should know it too, for many scenarios there was NO way to go with the native one).

**Comment by FabianGosebrink** [comment]
The router was always a pain point in AngularJS. However the router, or better: The integration of it and getting it back on track was one of the reasons to skip version 3 and go stright to version 4 of angular. Take a look at it, do a sample application and check if it fits your needs. Can we close this with that?

**Comment by CesarD** [comment]
Yeah, sure!
Thanks!
