### ISSUE TITLE
On module Setup cause getIsAuthorized to fire based on what's already in storage

### ISSUE THREAD

**Issue by JohnGalt1717** [damienbod/angular-auth-oidc-client#639]
The docs say the following about getIsAuthorized:

"This method will return an observable that will not emit until after module setup is completed. The emitted value will be set to true if the client and user are authenticated, false otherwise. If silent renew is configured, a silent renew will be attempted before emitting false."

This isn't true. It will absolutely fire before getIsModuleSetup() is true like so:

```
		this.oidcSecurityService
			.getIsModuleSetup()
			.pipe(
				filter((isModuleSetup: boolean) => isModuleSetup),
				take(1)
			)
			.subscribe(async () => {
```

So what I'm trying to do is the following:

After the module is setup I check if there is token information. If there is, then I do:

`oidcSecurityService.authorizedCallbackWithCode(authInfo);`

Which induces a call on getIsAuthorized() which is fine for the case of the user just logged in.

Once that's done, and there is cached information, if you hit refresh on the browser, getIsAuthorized is called and it's called before the module setup is called per above.  

And it NEVER calls in the case of the person not being logged in with cached credentials.

What I'm looking for is an event where nothing is done, but the module is setup. If the token is passed, then I can called authorizedCallbackWithCode and if it isn't passed, I can tell it to load the information from the storage with a function (which I don't know)  I *think* that I can induce it not to lose the userInfo by setting auto_userinfo = false before the setupModule function. Presumably this will also cause getIsAuthorized() to not fire per the docs.

But what I can't figure out is what function I have to call to get it to load whatever is there from storage and have it then call getIsAuthorized in both the case where there is something there and the user is authenticated AND if there is nothing there.

So no matter what, getIsAuthorized needs to be called, and it needs to be called AFTER the module is setup, AND call when:
1. Token info is processed.
2. No user info at all in storage.
3. User info in storage.

How do I induce this behavior?

(and in this behavior I wouldn't need isauthorizedrace_timeout_in_seconds so I'd like to disable it.)

**Comment by damienbod** [comment]
@JohnGalt1717  This has been refactored and changed in verison 11 which we plan to release in the next few days after testing

Greetings Damien
