### ISSUE TITLE
authorizedCallback incorrect state" in browser console

### ISSUE THREAD

**Issue by mrAbdelrahman** [damienbod/angular-auth-oidc-client#658]
The first time I try logging in I get unauthorized but when I retry in the same browser instance it succeeds. I don't know the reason for this error message :(((
![image (1)](https://user-images.githubusercontent.com/59330775/79868518-4f071a80-83e0-11ea-9a6b-9d7ce4761740.png)

**Comment by inpicksys** [comment]
who knows, who knows...

**Comment by OrionDevelopment** [comment]
This happens because something is triggering a clear of the storage during a renew. Use a custom storage implementation and listen for changes then check the stacktrace on the clearing, for what exactly is doing this. I for example had a douple setupModule in there, causing the issue.

**Comment by damienbod** [comment]
This has been refactored and changed in verison 11 which we plan to release in the next few days after testing

@OrionDevelopment thanks for the feedback.

Greetings Damien
