### ISSUE TITLE
Token validation failed and redirect to unauthorized route when accessing with /#/

### ISSUE THREAD

**Issue by CesarD** [damienbod/angular-auth-oidc-client#67]
I have my app that for certain reasons need to use hash on angular-route.
When I access my app directly through http://localhost:4200/#/ it logs the following in the console:

> authorizedCallback Signature validation failed id_token
> authorizedCallback, token(s) validation failed, resetting

I think it **might** be because of the following: https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.service.ts#L185

It checks that if no hash specified, then takes it directly from the url, assuming automatically that it *should* be the redirect from the STS with the `id_token` and other params in the url. But since there isn't any, the whole validation fails.

Please correct me if I'm wrong and if there's some workaround I can implement by myself.
Thanks.

**Comment by damienbod** [comment]
Hi @CesarD 

This is supported.

See this PR for info

https://github.com/damienbod/angular-auth-oidc-client/pull/61


Greetings Damien

**Comment by CesarD** [comment]
How is it supposed to be used? I'm just following the quickstart guide where you indicate the following:

    private doCallbackLogicIfRequired() {
        if (window.location.hash) {
            this.oidcSecurityService.authorizedCallback();
        }
    }

What should I pass to `authorizedCallback()` as hash?

**Comment by elwray** [comment]
This is happened for me when I set a very small access token lifetime.

**Comment by drievkoo** [comment]
I am facing similar issue. Not sure how to resolve it
