### ISSUE TITLE
When trying to build my application with version 11.0.0, getting build errors

### ISSUE THREAD

**Issue by mustafakachwala** [damienbod/angular-auth-oidc-client#709]
**Describe the bug**
When including the new package in my application, I am getting build error in the angular auth oidc client node module. My application is on Angular version 9.

**To Reproduce**
1. Add package 11.0.0 to package.json
2. do npm install and then npm run build

**Expected behavior**
should build successfully

**Log Dump**
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵc in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?).
Can't resolve all parameters for OidcSecurityService in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, ?, [object Object], [object Object], [object Object], [object Object], ?, [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object], ?).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵbb in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], [object Object], [object Object],
?, ?).
Can't resolve all parameters for ɵp in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object]).
Can't resolve all parameters for ɵr in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵy in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: ([object Object], ?, [object Object], ?, ?, [object Object], ?).
Can't resolve all parameters for ɵg in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: ([object Object], ?, ?, [object Object], [object Object], ?, [object Object]).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵo in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], ?, ?, [object Object]).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵt in C:/Users/MKachwala/Source/Repos/V3/delfi_innersource/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], [object Object], [object Object], ?, [object Object]).
Invalid provider for undefined. useClass cannot be undefined.
           Usually it happens when:
           1. There's a circular dependency (might be caused by using index.ts (barrel) files).
           2. Class was used before it was declared. Use forwardRef in this case.

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]

**Additional context**

Error in angular-error.log
[error] Error: Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵc in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?).
Can't resolve all parameters for OidcSecurityService in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, ?, [object Object], [object Object], [object Object], [object Object], ?, [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object], ?).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵbb in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], [object Object], [object Object], ?, ?).
Can't resolve all parameters for ɵp in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object]).
Can't resolve all parameters for ɵr in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵy in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: ([object Object], ?, [object Object], ?, ?, [object Object], ?).
Can't resolve all parameters for ɵg in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: ([object Object], ?, ?, [object Object], [object Object], ?, [object Object]).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵo in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], ?, ?, [object Object]).
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵt in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, [object Object], [object Object], [object Object], ?, [object Object]).
Invalid provider for undefined. useClass cannot be undefined.
           Usually it happens when:
           1. There's a circular dependency (might be caused by using index.ts (barrel) files).
           2. Class was used before it was declared. Use forwardRef in this case.
Can't resolve all parameters for OidcSecurityService in C:/Users/MKachwala/Source/Repos/test/delfi-gui-components/node_modules/angular-auth-oidc-client/angular-auth-oidc-client.d.ts: (?, ?, [object Object], [object Object], [object Object], [object Object], ?, [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object], ?).

    at Object.<anonymous> (C:\Users\MKachwala\Source\Repos\test\delfi-gui-components\node_modules\ng-packagr\lib\ngc\compile-source-files.js:82:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\MKachwala\Source\Repos\test\delfi-gui-components\node_modules\ng-packagr\lib\ngc\compile-source-files.js:5:58)

**Comment by FabianGosebrink** [comment]
Can you please share an example repository? You can also check the imports of your app and see the samples in the repo if they are matching. If you provide a github sample repo we can have a look. Thanks.

**Comment by yuchaosydney** [comment]
My project gets error as :

**Comment by mustafakachwala** [comment]
Thanks @FabianGosebrink . Let me close this bug for now and reopen once I have more details

**Comment by FabianGosebrink** [comment]
Please check out the latest version. could be fixed now.

**Comment by mustafakachwala** [comment]
Thanks @damienbod and @FabianGosebrink , this version does fix the build error.
