### ISSUE TITLE
Authentication fails on mobile browsers.

### ISSUE THREAD

**Issue by jbloem9** [damienbod/angular-auth-oidc-client#71]
I have a website deployed on amazon.  When opening the website on my machine everything works as expected. But when I open the same website on a mobile device through the chrome browser on the device I get Authentication issues.  I have attached 2 screen shots of the console for the mobile and normal machine.  

Machine Console:
![machine_browser](https://user-images.githubusercontent.com/7578265/29906545-d658243a-8e69-11e7-8506-7e3477545347.PNG)

Mobile Device Console:

![mobile_browser](https://user-images.githubusercontent.com/7578265/29906548-da14fc9c-8e69-11e7-8e06-de477ebc8a2f.PNG)

**Comment by damienbod** [comment]
@jbloem9 You need to increase the value in the  max_id_token_iat_offset_allowed_in_seconds property

openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 30;

**Comment by jbloem9** [comment]
Hi Damien.

I have set this value to a larger value in the configuration setup. When I
run it locally on my localhost the I do see the larger value in the debug
console. However when deployed it keeps reventing to 10 seconds.

**Comment by damienbod** [comment]
How do you init the module?

https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#output-onmodulesetup-eventemitter--new-eventemittertrue

Wait for the onModuleSetup event maybe

Greetings Damien

**Comment by jbloem9** [comment]
Thanks Damien, that fixed it.
