### ISSUE TITLE
Unable to build an Angular 8 project with v11.0.0 (TS1086)

### ISSUE THREAD

**Issue by danielbecroft** [damienbod/angular-auth-oidc-client#712]
**Describe the bug**
`npm start` fails when adding `angular-auth-oidc-client@11.0.0` to an Angular 8 project.

**To Reproduce**
The errors received are:

```
ERROR in node_modules/angular-auth-oidc-client/lib/authState/auth-state.service.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     get authorized$(): import("rxjs").Observable<boolean>;
           ~~~~~~~~~~~
node_modules/angular-auth-oidc-client/lib/callback/callback.service.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     get stsCallback$(): Observable<unknown>;
           ~~~~~~~~~~~~
node_modules/angular-auth-oidc-client/lib/config/config.provider.d.ts:9:9 - error TS1086: An accessor cannot be declared in an ambient context.

9     get openIDConfiguration(): OpenIdConfiguration;
          ~~~~~~~~~~~~~~~~~~~
```

Approximately 20-25 files a re failing with the same error (different methods etc).

**Expected behavior**
The build process should work, or if Angular 8 is not supported, then the dependencies should trigger the pacakage being unable to be installed.

**Screenshots**

**Desktop (please complete the following information):**
angular/core = 8.2.11
Node v14.0.0
npm 6.14.5

**Comment by FabianGosebrink** [comment]
Hey @danielbecroft , which typescript version are you using? Have you tried updating typescript?

**Comment by danielbecroft** [comment]
Hi @FabianGosebrink , I'm currently running 3.5.3. The below is the output of `npm ls typescript` for my project. 

```
+-- @angular-devkit/build-angular@0.803.20
| `-- @angular-devkit/build-optimizer@0.803.20
|   `-- typescript@3.5.3
+-- karma-typescript-preprocessor@0.4.0
| `-- typescript@3.5.3  deduped
`-- typescript@3.5.3
```

I've tried to upgrade, but there are packages that won't accept the higher Typescript version. Is downgrading the version of this package the best approach?

**Comment by FabianGosebrink** [comment]
Hey @danielbecroft so I think you have to update your angular (and with this the typecscript) to a higher version to use v11 of this lib. Is updating to Angular 9 possible? We on our side will have to check which version of TS is needed and we will update the readme accordingly.

**Comment by danielbecroft** [comment]
@FabianGosebrink  Unfortunately not, or at least, not easily. I'll downgrade to the v10.x line of the library, and adjust the code changes accordingly.

Upgrading to Angular 9 is on our list, though.

**Comment by FabianGosebrink** [comment]
You can update if you are on the angularCLI easily with https://update.angular.io.
