### ISSUE TITLE
App does not load if STS has an issue, CORS for Example

### ISSUE THREAD

**Issue by paulstelzer** [damienbod/angular-auth-oidc-client#717]
**Describe the bug**
If the sts server has no cors enabled, the application will not start

**To Reproduce**
1. Use a server (stsServer) who has no cors enabled
2. If you add 

```
    OidcConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: configureAuth,
      deps: [OidcConfigService],
      multi: true,
    },
```

to your app-module.ts providers section, you will see that the application will not start anymore.

**Expected behavior**
The application should start anyway.

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by damienbod** [comment]
Hi @paulstelzer Just wondering if this is good or not. Why should the APP start? If the STS is setup incorrectly and you can not authenticate from the Angular APP, then there is no point in having the authn in the Angular APP. 

Greetings Damien

**Comment by FabianGosebrink** [comment]
Have you tried to catch the error in the init and return a resolved (but empty) promise instead?

**Comment by damienbod** [comment]
If CORS is broken on your STS, then you have a bigger problem

**Comment by paulstelzer** [comment]
Cors is enabled now, I only foudn the issue and think it's better to have an application than having a white page :)

**Comment by FabianGosebrink** [comment]
Totally. Thanks for mentioning this. Glad your issue is fixed. Maybe we will tackle this in future versions. But this would be a breaking change again. We have to draw this first, try it out and maybe bring that up in future versions. Thanks for using the lib 🙃

**Comment by FabianGosebrink** [comment]
Hey @paulstelzer , just wanted to let you know that we just merged a PR which gives you the possibility to lazy load the config and so move the error - if there is one at your sts - to the moment when the user clicks login.

https://github.com/damienbod/angular-auth-oidc-client/pull/724/files#diff-e71cfa1c040ef2eea5de14baab837af9

describes the feature. If you set the `eagerLoadAuthWellKnownEndpoints` to false your app will start right away and do the call when you call `authenticate`. Hope this helps.
