### ISSUE TITLE
I have problem with SilentRenew 

### ISSUE THREAD

**Issue by IIIMalakitIII** [damienbod/angular-auth-oidc-client#728]
Every 5 minutes, I am returned to the address localhost:4200, f.e. 
(If I am located at localhost:4200/something after 5 minutes returns me to localhost:4200)
also if I am on a different tab, the silent update doesn't work and I have to log in manually.
I use PKCE flow

**Comment by damienbod** [comment]
Hi @IIIMalakitIII Can you post a bit more info, so we can help. Can you check in the F12, what errors, warnings you get? I guess that your tokens have 5 min expiry and the request fails due to a STS misconfig or something not configured correctl< in the renew request.

Greetings Damien
