### ISSUE TITLE
V11 Force Get New Token

### ISSUE THREAD

**Issue by JohnGalt1717** [damienbod/angular-auth-oidc-client#729]
**Describe the bug**
In v10 you could call refereshSession() which would cause a new token to be retrieved (access and id if you specified that)  V11 doesn't appear to have this.

**Expected behavior**
There still needs to be a function for the client to say "Hey, I know something changed with my token, give me a new one."

**Comment by damienbod** [comment]
@JohnGalt1717 This would be good, sorry about this getting removed.

**Comment by JohnGalt1717** [comment]
Np! For now I'm just calling login again, which causes the idp to force a new token loop, but obviously that's not very efficient. Would be great if it was just an ajax call again.

**Comment by damienbod** [comment]
@JohnGalt1717  Just realized, this should work for you in the same way:

```
refresh() {
    this.oidcSecurityService.authorize({ customParams: { prompt: 'none' });
}
```

If this would work, then we could save adding the new API. Would this work for you?

Greetings Damien

**Comment by JohnGalt1717** [comment]
So my issue with that is that's basically what I'm doing right now. The problem is that it's looping through the idP.  I would really like it to not have to reconstruct the angular site as a result and just do an ajax call to get a new auth and id token on demand and update everything in it so that I can update the interface and security rules etc. without a reload.

Before I could use refreshSession() which did this without a loop through and thus tear down and rebuild of the angular site which was ideal.

**Comment by damienbod** [comment]
yes, good idea. Ok I will add a forceRefreshSession() API which will do this

**Comment by JohnGalt1717** [comment]
Thanks!

**Comment by damienbod** [comment]
Added this to version 11.1.0, should be releasing soon, just what to do some tests tomrrow, thanks for reporting.

Greetings Damien

**Comment by JohnGalt1717** [comment]
You rock! Thanks!

**Comment by teebszet** [comment]
Hi! 

Using this feature with implicit flow, and I run into a problem where redirect_uri query param is not being set on the call to /authorize.

I do have redirectUrl set on my startup config. 

An example request that the forceRefreshSession() tries to make is:

https://leodev.auth0.com/authorize?client_id=u7Kug1OUxsddddFfE2ozPxvAkUunlv8k&redirect_uri=https%3A%2F%2Fplease_set&response_type=id_token%20token&scope=openid%20profile%20&nonce=e7ac3cddef457b8ffeb39d57da27974d5caG49UWT&state=3e5198413ec76dd83789e4cccbcbfc7899wxtj0Ct&prompt=none&audience=http%3A%2F%2Flost%3A34999

**Comment by damienbod** [comment]
Hi @teebszet I'll check this, I assume the authorize woeked? And after you're logged, you call the forceRefreshSession, correct? I'll validate this using this example:

https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects/sample-implicit-flow-silent-renew

Greetings Damien

**Comment by teebszet** [comment]
>I assume the authorize worked? And after you're logged, you call the forceRefreshSession, correct?

Yes exactly. Thanks

**Comment by damienbod** [comment]
Ah, yes the silentRenewUrl  is used for the forceRefreshSession, set this, and it should be fine. Will add validation for this I think.

**Comment by teebszet** [comment]
@damienbod do I also need silentRenew set to true?

**Comment by damienbod** [comment]
yes, for the forceRefreshSession feature. This just gets a new token using the non interactive path. This is only possible if the silent renew is true and if using the iframe flow, then the silentRenewUrl. Otherwise you need to use a UI to renew.  Just must be already logged in for this to work.

It might be possible to change this so that this is possible without an active silent renew. But I would need to investigate this first.

Greetings Damien

**Comment by teebszet** [comment]
@damienbod Ok cool. Didn't realise this feature was so new before I upgraded to v11!

I'm now getting a weird situation where the first first call to forceRefreshSession() works and I can see that a new access token gets added to session storage.

However, a subsequent call to forceRefreshSession() returns a null result. I can't see the exact request it's sending, but it appears something is different between the first and subsequent silent renews. Could be state?

Possibly my STS is returning a 302 redirect response with error=login_required, but I also don't see a way to handle that manually, as no error is emitted to the returned observable, just null.

Thanks
