### ISSUE TITLE
withConfig should return config

### ISSUE THREAD

**Issue by PartyArk** [damienbod/angular-auth-oidc-client#732]
Hi, the `withConfig` promise previously returned the well-known config, but 11.1.0 returns nothing. This was useful for debugging; others might have other uses.

Thanks for the hard work.

PS There is a typo in the docs for "Delay the loading..." - `oidcConfigService.withonfig`

**Comment by FabianGosebrink** [comment]
Hey @PartyArk , thanks for the message. You can get to the config by using 

```
 this.configuration = this.oidcSecurityService.configuration;
```

to get to the configuration. The `withConfig` should only be used when the app is starting and is resolved by angular through the `APP_INITIALIZER`. HTH
