### ISSUE TITLE
CheckAuth does not parse the Url - Stays with all parameters

### ISSUE THREAD

**Issue by jScope** [damienbod/angular-auth-oidc-client#733]
Hello,

I'm currently trying to set the redirect_uri dynamically on login to the current url window.location.href so that I return to the last location after login and not to my default redirect_uri.

With my current version 10.0.15 I can't find a way to do that. I could use SessionStorage here to remember my last location but if I could pass it to the authorization roundtrip as redirect_uri that wouldn't be necessary.

Will it help to update to version 11?

**Comment by jScope** [comment]
I've updated now to version 11.1.0 anyway and my app works so far but after successful login redirect with token I return with ugly session and state:

https://localhost:4200/welcome?state=a97519c61ae5fcb9af4d5cXXXXXXXXX&session_state=9caa1473-5c32-4f7c-XXXXXXX&code=ad77a1e1-d935-4e2b-8c0b-92XXXXXXXX

Shouldn't that disappear after exchange of code against token?

Still unable to modify the redirect_uri.

**Comment by FabianGosebrink** [comment]
Hey @jScope , I dont know if I understand you correctly, but we have an auto login sample which saves the last known location and returns to it when the authentication was successfull. 

https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/sample-code-flow-auto-login/src/app/app.component.ts

Does that help you to solve your case? The app doesnt support this, you have to implement this by yourself.

**Comment by jScope** [comment]
Hello @FabianGosebrink, thank you for your quick reply. According to the URL parameters after login, they still remain. checkAuth() is called in my AppComponent after redirect:

```
ngOnInit() {

    this.oidcSecurityService.checkAuth().subscribe(auth => {
      this.isAuthorized = auth;
      if (this.isAuthorized === true) {
        console.log('URL AFTER LOGIN: ', this.sessionStore.retrieve( 'fssb-login-return-url'));
      }
    });

    this.oidcSecurityService.userData$.subscribe(userData => {
      this.userData = userData;
    });

  }
```
My login method:

```
  login() {
    if (this.sessionStore.browserSupportsSession) {
      this.sessionStore.store(window.location.href, 'fssb-login-return-url');
    }
    this.oidcSecurityService.authorize();
  }
```
And my configuration:

```
    stsServer: 'https://myauthserver/auth/realms/test',
    redirectUrl: window.location.origin,
    clientId: 'angular-test',
    responseType: 'code',
    scope: 'openid profile email some-custom-scope',
    triggerAuthorizationResultEvent: true,
    postLogoutRedirectUri: window.location.origin,
    startCheckSession: true,
    silentRenew: true,
    silentRenewUrl: 'https://localhost:4200/silent-renew.html',
    postLoginRoute: '/',
    forbiddenRoute: '/no-access',
    unauthorizedRoute: '/no-access',
    logLevel: LogLevel.Debug,
    historyCleanupOff: true
```
Where exactly in checkAuth() should the Url be interpreted and cleaned?

Thank you once again for your help!

**Comment by jScope** [comment]
Hello @FabianGosebrink,
the scenario with localStorage and router works now. Thank you! Because I'm calling navigateToStoredEndpoint() my URL gets cleaned after a successful login and redirect to last route but checkAuth() itself still doesn't return to a clean URL for me.

**Comment by FabianGosebrink** [comment]
Hey @jScope , thanks for the message. `checkAuth()` does return a boolean, not a url. Or did I misunderstand you? Does it work now for you?

**Comment by jScope** [comment]
Hey @FabianGosebrink , I use the return value as boolean, please see my first code box above :). The login process works fine and I get a correct boolean response for login, token, user data etc. but still my url keeps the url parameters.

**Comment by damienbod** [comment]
@jScope were you able to get this solved? Tested this using the sample in version 11.1.1, and it seems to work. I'll close this if this ok, please open it again if it is not solved for you.

Thanks Damien
