### ISSUE TITLE
authorizedCallback Signature validation failed id_token

### ISSUE THREAD

**Issue by 709398summer** [damienbod/angular-auth-oidc-client#745]
I cannot get pass authorizeCallback Signature validation.  However, I am able access jwks successfully when hitting URL directly. 

Base on debug console, I am able to retrieve id_token, but the following validation fails.  Below is output from console.  Please advise on how to get this fix.  I am using code flow.

authorizedCallback created, begin token validation
angular-auth-oidc-client.js:161 

Getting signinkeys from  Array(1)0: "https://identityserver1/oauth2/jwks" length: 1__proto__: Array(0)
angular-auth-oidc-client.js:161 

authorizedCallback Signature validation failed id_token
angular-auth-oidc-client.js:161 

AuthorizedCallback token(s) invalid
angular-auth-oidc-client.js:156 

authorizedCallback, token(s) validation failed, resetting. Hash: 
logWarning @ angular-auth-oidc-client.js:156

**Comment by damienbod** [comment]
HI @709398summer This usually happens when your STS server blocks the HTTPS request with CORS, so the request will work in the browser, but not when you call it from an Angaulr app. You can check if this is the case in the errors of the F12.

Greetings Damien

**Comment by 709398summer** [comment]
I was able to bypass CORS and still have same issue with authorizedCallback Signature validation.
Here is the console logging from STS to error:

ConfigLoaded Object
angular-auth-oidc-client.js:161 STS server: https://identityserver1/oauth2/oidcdiscovery
angular-auth-oidc-client.js:161 running validation for callbackhttps://localhost:4200/?code=bc9993ea-7243-5091-9032-e74d284b7e16&state=f54c88645f0ccb2d18be9a28b3306ff6a9qallN5O&session_state=6cb9d827d2af86a6ef396475b4120b25577a4dd0ab4ed157a38218593a1042b1.0Uiujt_WD4kzNET5WVyKMQ
angular-auth-oidc-client.js:161 Wanted to read 'KfrVNHDgLjTawQIs7IkNCl1r9kAa_storageSilentRenewRunning' but nothing was found
core.js:41022 
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
angular-auth-oidc-client.js:161 Object
angular-auth-oidc-client.js:161 authorizedCallback created, begin token validation
angular-auth-oidc-client.js:161 Getting signinkeys from  Array(1)
angular-auth-oidc-client.js:161 authorizedCallback Signature validation failed id_token
angular-auth-oidc-client.js:161 AuthorizedCallback token(s) invalid
angular-auth-oidc-client.js:156 authorizedCallback, token(s) validation failed, resetting. Hash: 
logWarning @ angular-auth-oidc-client.js:156
core.js:6237 ERROR authorizedCallback, token(s) validation failed, resetting. Hash: 
defaultErrorLogger @ core.js:6237

**Comment by damienbod** [comment]
@709398summer  maybe the CORS is blocked for the jwt request. I will close this as I cannot fix CORS on the client side. This needs to be fixed on the STS. Hope this helps

Greetings Damien
