### ISSUE TITLE
Remove the "AuthorizedState" enum in Version 12

### ISSUE THREAD

**Issue by FabianGosebrink** [damienbod/angular-auth-oidc-client#755]
Auth should be yes/no, but not a third value "unknown". COmplete enum can be removed.

**Comment by JerrettDavis** [comment]
Please see PR #1062.

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25299 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] Remove the "AuthorizedState" enum in Version 12 (#755)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25299>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________

**Comment by FabianGosebrink** [comment]
Implemented, will be in Release 12.
