### ISSUE TITLE
Wanted to read 'angularclient_authzData' but nothing was found

### ISSUE THREAD

**Issue by inpicksys** [damienbod/angular-auth-oidc-client#760]
**Describe the bug**
Using one of examples with your sts server - I had this issue. 
And I don't know what wrong & way to fix this to get it working at least

What this error mean? Cors applied "AllowAllOrigins"

console:
STS server: https://localhost:44318
angular-auth-oidc-client.js:161 Wanted to read 'angularclient_authzData' but nothing was found
angular-auth-oidc-client.js:161 checkAuth completed fire events, auth: false

**Comment by FabianGosebrink** [comment]
Hey @inpicksys, which sample did you run? Did you change any config? Did it work but you saw the errors and are confused? Or did it not work at all? Thanks

**Comment by inpicksys** [comment]
@FabianGosebrink 
I'm using this StsServer
https://github.com/damienbod/AspNetCoreAngularSignalRSecurity/tree/master/StsServerIdentity

on client side 
I'm using angular code flow - dotnet core app with 
  `app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "Client";

                if (env.IsDevelopment())
                {
                    // spa.UseAngularCliServer(npmScript: "start");
                    //OR
                    spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
                }
            });
`  
angular side placed in Client folder is exactly as in examples provided in this repo 


What means error when app is started
Wanted to read '<some_client_id>_authzData' but nothing was found?

**Comment by FabianGosebrink** [comment]
Hey @inpicksys , the message means that he tried to read something from the store but did not find anything. This could be normal and is only logged out when you have the corresponding loglevel. This is why I asked the questions in my previous answer 😊

1. **which** sample did you run? 
2. Did it work but you saw the messages and are confused? 
3. Or did it not work at all? 

Thanks

**Comment by inpicksys** [comment]
@FabianGosebrink 
Thank you for quick responses. I'm in desperation with this.
https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects/sample-code-flow-auto-login
this sample integrating in my webspa
& after clicking login... it works.

**Comment by inpicksys** [comment]
@FabianGosebrink thank you

**Comment by joobacca** [comment]
I know it's been a long long time, but any idea on how you might have solved this, @inpicksys ?

**Comment by abdelamine06** [comment]
Same problem any idea ?

**Comment by FabianGosebrink** [comment]
It might be that the auth data was not written yet when using AutoLogin. The AuthData is only written when you are logged in.
