### ISSUE TITLE
Azure B2C Forgotten Password Flow

### ISSUE THREAD

**Issue by luklew** [damienbod/angular-auth-oidc-client#762]
I can't seem to find a way of retrieving error codes. I read through available documentation and I haven't found it. Is there a way of getting error codes back (e.g when I click forgotten password the sts redirects back to the application with an error code)?

**Comment by luklew** [comment]
Hi @damienbod , sorry for late response. 

Basically what I was trying to do was retrieve error codes from the sts. For example when I click forgotten password (using Azure B2C) the STS returns an error code , and my application needs to read that code and swap to forgotten password flow.

What I don't understand is how to get those error codes returned from the STS and then how to change the flow ?

**Comment by RanjeethDyasani** [comment]
Hi @damienbod and @luklew I have the same issue, to elaborate it when I initially open the B2C Sign-in/Sign-up page and click on forgot password link, it returns an error code back to the app. Could you please help us with a sample to capture the error code and call the Forgot Password flow in case the error code is some 'xxxxxxx'. Thanks!
