### ISSUE TITLE
switch-user support for multi-user management

### ISSUE THREAD

**Issue by Zetanova** [damienbod/angular-auth-oidc-client#763]
**Is your feature request related to a problem? Please describe.**
The function to switch the state of the auth-session would be required 
to implement a fast-user-switch on a shared workstation. 

**Describe the solution you'd like**

```
oidcSecurityService.switchSession('userA');
oidcSecurityService.authorize();
```

```
oidcSecurityService.switchSession('userB');
oidcSecurityService.checkAuth().subscribe(isAuth => { ... });
```

```
oidcSecurityService.getSessions().subscribe(session => { ... });
```

**Describe alternatives you've considered**
Maybe it is posisble to user getState and setState for it, but then 
an external user-store would be required.

Most likly it can be implemented over a custom custom-storage-provider
But i didn't find a way  in the public-api 
to reload the state of the `oidcSecurityService` instance.

**Comment by damienbod** [comment]
We won't support this as it's outside the scope of this lib. I would recommend using browser profiles

Greetings Damien

**Comment by Zetanova** [comment]
I managed to do it. Don't remember how.
I implemented a custom SessionStore Provider

This feature is required for POS terminals.
To use browser profiles it's not possible.
