### ISSUE TITLE
Differentiate first time sign in and successive sign in

### ISSUE THREAD

**Issue by mraju2** [damienbod/angular-auth-oidc-client#768]
hi ,

this is not an issue i am trying to understand is there any property or method to differentiate between first-time azure AD b2c sign in and successive sign-In in a web application? . I login to application and closed without logout now I sign in again can we differentiate these 2 cases.

**Comment by Rasetti** [comment]
@mraju2 You can return the new_user claim as part of the id token. It is set to true when the user finished signing up and has still not signed in.
