### ISSUE TITLE
getToken & getIdToken empty immediately after authorization

### ISSUE THREAD

**Issue by Patricksirich** [damienbod/angular-auth-oidc-client#771]
Hi!
First I want to say that I absolutely love this package - been using it for a while, great work!!

Immediately after authorization has gone through and getIsAuthorized returns true, getToken() & getIdToken() returns empty.
In my application, I send the tokens as a bearer to the backend in order to authorize the user on the backend as well. Since there are no tokens, the backend will return a 401 making the user unauthorized on the frontend as well.
So far, the only fix I have found is to intercept and cancel the first request that I make. But since getIsAuthorized returns true, I expect the tokens to have been set. 

I'm using version 10.0.10 - might have been fixed in the newer versions, haven't had time to try and update to a newer version..

I'm using implicit flow with silent renew.

This is my config:

```
const config: OpenIdConfiguration = {
	stsServer: stsServer,
	redirect_url: window.location.origin + '/',
	client_id: 'CLIENT_ID',
	response_type: 'id_token token',
	scope: 'openid email profile',
	trigger_authorization_result_event: true,
	post_logout_redirect_uri: window.location.origin + '/unauthorized',
	start_checksession: false,
	silent_renew: true,
	silent_renew_url: "/silent-renew.html",
	// silent_renew_offset_in_seconds: 4500,
	post_login_route: '/home',
	forbidden_route: '/forbidden',
	unauthorized_route: '/unauthorized',
	log_console_warning_active: false,
	log_console_debug_active: false,
	max_id_token_iat_offset_allowed_in_seconds: 30,
	history_cleanup_off: false,
	auto_userinfo: false,
	auto_clean_state_after_authentication: true,
	isauthorizedrace_timeout_in_seconds: 0.5
};
```

**Comment by damienbod** [comment]
Hi @Patricksirich We don't have the resources to support version 10, sorry about this. We it be possible to update to version 11? 

Greetings Damien

**Comment by Patricksirich** [comment]
I will look into updating to version 11, although it will not be in the near future.
If I find time to update, I will let you know if the issue persists :-)

**Comment by irek14** [comment]
Hi,

I'm using 11.2.0 version and have the same problem. 

This is my config
`    oidcConfigService.withConfig({
      stsServer: StsServer,
      authWellknownEndpoint: authWellknownEndpoint,
      redirectUrl: window.location.origin,
      clientId: environment.clientId,
      scope: `openid profile`,
      responseType: 'code',
      silentRenew: true,
      maxIdTokenIatOffsetAllowedInSeconds: 600,
      issValidationOff: false,
      autoUserinfo: false,
      silentRenewUrl: window.location.origin + '/silent-renew.html',
      logLevel: LogLevel.None,
      storage: localStorage,
    });`
