### ISSUE TITLE
 LogLevel has only 3 level. but cannot disable it in version 11?

### ISSUE THREAD

**Issue by hmheng** [damienbod/angular-auth-oidc-client#777]
**Describe the bug**
LogLevel has only 3 level. but cannot disable it in version 11?

**Expected behavior**
Add disable enum

**Comment by joffarex** [comment]
It is optional parameter, you can not pass it at all so you will not get any logging.

**Comment by hmheng** [comment]
I would have to remove the parameter entirely in the app.module. 
Should we add LogLevel.none to disable it instead so that we don't touch the code in the app.module?

This will be helpful if we would want to debug on dev environment without pushing another changes to the code just to turn on/off the logging.

**Comment by joffarex** [comment]
Well, as of now, you could extract config object and do an property attaching depending on your environment.

**Comment by hmheng** [comment]
yeap, sure. thank you @joffarex

**Comment by FabianGosebrink** [comment]
Is the PR helping you?

**Comment by hmheng** [comment]
@FabianGosebrink seems good to me! Thank you. 
Just one question more for the PR, logLevel in configAuth() is default to none if environment is production right?

**Comment by FabianGosebrink** [comment]
We do not take the switch if you are running in production or not. Therefore we have to enhance the config for that. So the default would be fix for env and dev in this case.  Default is `Warn` if nothing is given.

https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/config/default-config.ts#L25

**Comment by damienbod** [comment]
fixed, will be released in the next version
