### ISSUE TITLE
If unauthorized redirect to login and then back to original page

### ISSUE THREAD

**Issue by jbloem9** [damienbod/angular-auth-oidc-client#78]
On our system a user is trying to access a page and is not authorized.  We have added a call to redirect the user to the login screen. After logging onto the system the user needs to be taken to the original page they were trying to access and not the hard coded startup_route. How can I achieve this?

I have found another issue where it sets trigger_authorization_result_event = true but then I am not sure what event I must subscribe to, where and how to do this?  Please advise.

**Comment by damienbod** [comment]
Hi @jbloem9 

yes you can use the trigger_authorization_result_event for this. The onAuthorizationResult is then returned with a enum which you can use to implement your requirement. 

Event:
https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#output-onauthorizationresult-eventemitter


Enum:
https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/authorization-result.enum.ts

I need to documente this better then.

**Comment by jbloem9** [comment]
Resolved, thanks.

**Comment by jonasbg** [comment]
How is this possible to achieve? The onAuthorizationResult() returns an enum only, but I need to redirect the user back to where the user initially hit our application.

Did you get this to work @jbloem9 ??

**Comment by jbloem9** [comment]
Hi @jonasbg.
All our pages have some API component.  If the user is unauthorized the API will return a 401.  On the angular side we use http interceptors and trap the 401 result.  We then save the URL from the angular router in local storage for later use.  The user is then redirected to the login page;


[ErrorInterceptor.txt](https://github.com/damienbod/angular-auth-oidc-client/files/1809280/ErrorInterceptor.txt)

Then we subscribe to the getIsAuthorized() method and if the user is authorized we then retrieve the URL from local storage and redirect to this.

  // this will allow us to get the user details, needed to get the user permissions
      this.securitySubscription.add(
          this.securityService.getIsAuthorized().subscribe(
              (isAuthorized: boolean) => {
                  this.isAuthorized = isAuthorized;
                  if (this.isAuthorized) {
                     // IF this has a value redirect to where they were trying to go before login
                  const returnUrl = LocalStorageService.read('postLoginURL');

                  if (returnUrl !== null) {
                    // clear this out so that it is not used all the time
                    LocalStorageService.delete('postLoginURL');
                    this.router.navigate(['.' + returnUrl]);
                  }
                  }
              }));

We were already looking at the isAuthorized event and I realized I could use this.

Or you could do the following;

this.securitySubscription.add(
      this.securityService.onAuthorizationResult.subscribe((authResult) => {
        //the enum is not exposed publically BUT 1 is authorized
      if (authResult === 1) {
    
	 const returnUrl = LocalStorageService.read('postLoginURL');

                  if (returnUrl !== null) {
                    // clear this out so that it is not used all the time
                    LocalStorageService.delete('postLoginURL');
                    this.router.navigate(['.' + returnUrl]);
                  }
    }
     }));

// This is an enum, but not exposed in the oidc package, so commented here:
/*
export enum AuthorizationResult {
	authorized = 1,
	forbidden = 2,
	unauthorized = 3
}
*/

Hope this helps.

**Comment by damienbod** [comment]
@jonasbg Thanks for the answer!

The enum should be exposed now.

https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/angular-auth-oidc-client.ts#L9
