### ISSUE TITLE
getToken is invalid and unusable for accessing api.

### ISSUE THREAD

**Issue by hmheng** [damienbod/angular-auth-oidc-client#781]
**Describe the bug**
getToken() doesn't seems to be valid jwt token and it is short. I tried to decode on jwt.io, but failed.
However, I managed to get valid token via getIdtoken().
I am not sure if it is incompatible with my identityserver4 or it is something else. But I am using v10 in my another app with same identityserver4, getToken in v10 is working fine.
I also noticed there is error from identityserver4 as screenshot below. But i dont see the issue with another app with v10.

**Expected behavior**
getToken() should be able to get valid accessToken.

<img width="556" alt="Screenshot 2020-06-06 at 10 57 24 PM" src="https://user-images.githubusercontent.com/11830387/83947388-31cfc380-a849-11ea-96c0-cb8ad657dcb0.png">

**Comment by damienbod** [comment]
Hi@hmheng 

The signin did not complete guessing from reading the logs in your image. Can you use the F12 to find out why the /connect/token request fails? This has nothing to do with the getToken(). The getToken can only be used after the signin completes.

Greetings Damien

**Comment by hmheng** [comment]
Thank you @damienbod you mean F12 in identityserver4 project? I couldn't find anything wrong on identityserver4 side.

On angular side, i couldn't find a clue
<img width="983" alt="Screenshot 2020-06-06 at 11 29 12 PM" src="https://user-images.githubusercontent.com/11830387/83948100-9725b380-a84d-11ea-89ca-79ef524fcea6.png">

**Comment by hmheng** [comment]
the access token is provided ""zy761SD8RGkm8c1u_ohyV8vmJl7J7owRa5pvF3-AEKI"". is this valid to be used as bearer token for accessing API?

**Comment by hmheng** [comment]
@damienbod , i found the rootcause, it is due to checkAuth function was placed in constructor of base component instead of ngOnInit. 

Thank you for the speedy response.
