### ISSUE TITLE
Documentation update for breaking changes

### ISSUE THREAD

**Issue by ntsehaye** [damienbod/angular-auth-oidc-client#783]
It would be great if documentation could be updated with breaking changes for latest 11 release

**Comment by FabianGosebrink** [comment]
Hey @ntsehaye , we have the migration document which should describe how to migrate. Are you aware of this? https://github.com/damienbod/angular-auth-oidc-client/blob/master/docs/migration.md

**Comment by ntsehaye** [comment]
> Hey @ntsehaye , we have the migration document which should describe how to migrate. Are you aware of this? https://github.com/damienbod/angular-auth-oidc-client/blob/master/docs/migration.md

Thank you for the reply, I am migrating from 10.0.2 and have a big breaking change to consider. the actual implementation pattern itself has changed.

**Comment by FabianGosebrink** [comment]
It should not basically. So the properties have changed, we removed the underscore. And some observables to the outside changed. Beside of that the lib should work as before.

**Comment by ntsehaye** [comment]
Lol yes that is pretty much it. However our implementation is multi tenant and lot of testing involved. We also had wrapper fixes for all those issues that have been included since that version. Lot of refactoring the code base I am afraid...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FabianGosebrink** [comment]
We solved a lot of the issues. Hence the breaking changes version. It changed a lot under the hood. You should try it out. Feel free to ask if you need help.

**Comment by ntsehaye** [comment]
Thank you Fabian! It is a remarkable lib. Thank you for the work you guys have done. only some minor edge cases that is all. 
Best,
