### ISSUE TITLE
Which version to use with Angular 6?

### ISSUE THREAD

**Issue by kumarmohe** [damienbod/angular-auth-oidc-client#784]
Hi

We are using Angular 6. What version of this library supports Angular 6? The latest version gives "unkown" is not a object error.

Thanks,
Mohan

**Comment by FabianGosebrink** [comment]
I think you would have to go with version 10 @damienbod any thoughts?

**Comment by kumarmohe** [comment]
Thank you. I think its better to have version compatibility chart showing the list of Angular versions the library was tested for each new version. Just a suggestion.

Thanks for the response.
