### ISSUE TITLE
Silent renew in Chrome incognito

### ISSUE THREAD

**Issue by benjaminandresen** [damienbod/angular-auth-oidc-client#785]
Hi
Silent renew seems to be broken when using latest version of Chrome (83.0.4103.97) in incognito mode. Identity server returns login_required for all renew requests. 
Works outside incognito, tested on several clients.
Brgds Benjamin

**Comment by jeroenheijmans** [comment]
Chrome 83 did indeed start blocking "third party cookies" in Incognito mode, following **Safari which is already doing that in normal mode**.

You are most directly affected if your Identity Server lives on a domain different from where you serve your SPA. This includes running on respectively (for example) https://demo.identityserver.io and http://localhost:4200 (at least I think `localhost` is _not_ exempt from this).

This will break things like iframe-based silent refresh, but also other mechanisms that rely on the cookie and iframes.

Not much the library can do for you here probably. You as an application developer will need to rethink your login flows in SPAs. Some directions for solutions/workarounds include switching to "BFF Architecture", using refresh tokens (with needed precautions/mitigations!), or fixing up the (sub)domain e.g. via DNS where your IDS and SPA are hosted.

**Comment by Miboch** [comment]
Will hosting the identity server and SPA on separate sub-domains on the same domain circumvent this restriction? Herein I'm imagining a setup akin to the following:

SPA url: sub.domain.tld?
Identity url: identity.domain.tld?

**Comment by damienbod** [comment]
still separate domains...

- Use the same domain with a BFF (Same domain) (cookie with server authn)
- use refresh tokens, but this is not so safe, server implementations for this are not supported in most STS, no revocation endpoint, single usage, rotation and so on.
- avoid safari

guessing that with time a solution will be found for this but at present no battle tested solutions exist.
