### ISSUE TITLE
getToken() returns "" 

### ISSUE THREAD

**Issue by kimrunar** [damienbod/angular-auth-oidc-client#787]
**Describe the bug**
I use the Azure AD OIDC Code Flow with PKCE. Set everything up with protected routes and everything works fine. But, when i call the getToken()-method i get a "" in return. 
 
The following code  in my auth-guard returns true as shown in screenshot further down; 

```
return this.oidcSecurityService.isAuthenticated$.pipe(
            map((isAuthorized: boolean) => {
                console.log('AuthorizationGuard, canActivate isAuthorized: ' + isAuthorized);

                if (!isAuthorized) {
                    this.router.navigate(['/unauthorized']);
                    return false;
                }

                return true;
            })
        );
```

**Expected behavior**
I expected the access-code to be returned so i can use it in my http-requests. 

**Screenshots**
Snapshot from runtime (from method inside oicd-package): 

![image](https://user-images.githubusercontent.com/7045229/84386743-22a69800-abf2-11ea-9b55-ec2d2eb1a0d5.png)

Some snapshots from console after route-changing to show that i actually am authorized.:
![image](https://user-images.githubusercontent.com/7045229/84386810-44078400-abf2-11ea-89d4-d94139f1b27c.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome and safari
 

**Additional context**

**Comment by damienbod** [comment]
hi @kimrunar Are you using the getToken before the authorize request is finished? How do you use this, in an inteceptor?

Greetings Damien

**Comment by kimrunar** [comment]
No, i use the getToken in another protected component on ng-init. So i first change routes to check if everything is ok. - Which it is based on the output from the interceptor.. Then i go to the route that runs the getToken that oddly fails to retrieve my token. 

![image](https://user-images.githubusercontent.com/7045229/84468525-5a0f5600-ac7f-11ea-9f9a-343ec6a37baf.png)

**Comment by damienbod** [comment]
The chechAuth completes after the getToken is called, which means you call it before the auth process is complete. 
Use the authenticated event to check if you are authenticated and then call the getToken(). 
Pease check the examples and the docs for appropriate usage

Here's 2 more examples:

https://github.com/damienbod/AzureAD-Auth-MyUI-with-MyAPI/tree/master/MySpaAngularUI

https://github.com/FabianGosebrink/angular-oauth2-oidc-sample/tree/master/client/angular-oidc-oauth2-ngrx

Greetings Damien

**Comment by kimrunar** [comment]
Ok thank you,
so now i tried your example 'MySpaAngularUI' and its the same result.
Why is auth : false in console when im logged in...? Is it something im missing?

![image](https://user-images.githubusercontent.com/7045229/84474139-a613c800-ac8a-11ea-9be0-4115da4ace5d.png)

**Comment by kimrunar** [comment]
Well, after some tinkering, i figured out what was wrong. - typo in my scopes.
