### ISSUE TITLE
More events notifications

### ISSUE THREAD

**Issue by CesarD** [damienbod/angular-auth-oidc-client#79]
I'm dealing with some scenarios where I have my application logged-in, if the access token expires when the application is not running (thus not renewing the token when needed) and when I enter again, the api call will fail because the token is already expired, and there's no way to be notified by the library if this has happened.
Same would apply if there was some error during the token silent renew.

Perhaps you could add some more validation to the token when the library is starting and emit some event or something to better acknowledge of these situations.

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/101

**Comment by fdcastel** [comment]
> if the access token expires when the application is not running (...)

Please, enlighten me: If the app was not running, when you come back and run it will be start in `isAuthorized = false` state. Isn't this enough for you to know that the token needs to be renewed? I can't see a need for another event here.

Now, when the application **is** running, I can see a use for events. In #101 you suggested:

> having some events like "AccessTokenExpiring" or "AccessTokenExpired",

After #101, if silent renew is disabled you will get an `AuthenticationLogout` event. I believe this cover your `AccessTokenExpired` case right?

Now, for `AccessTokenExpiring`, I believe we could emit one [here](https://github.com/damienbod/angular-auth-oidc-client/pull/107/files#diff-3551bf70e40e99dfec0656111f37bf52L573) (and use the already existing `silent_renew_offset_in_seconds` option).

> Same would apply if there was some error during the token silent renew.

This one is also covered: `RefreshTokenError` 😄 (again, after #101).

What you think?

**Comment by CesarD** [comment]
> If the app was not running, when you come back and run it will be start in isAuthorized = false state.

Will it? I think it was returning "true" because the id_token was stored in the browser storage, but that doesn't necessarily reflected that the access_token was still valid. In fact, I don't think there's any place that checks whether the access_token is already expired or not...
A user is "authorized" into the application if his/her token is not expired, otherwise it should be "not authorized" (isAuthorized=false).

> After #101, if silent renew is disabled you will get an AuthenticationLogout event. I believe this cover your AccessTokenExpired case right?

Under what circumstance? 

As for the rest regarding `AccessTokenExpiring` and `RefreshTokenError`, I agree  :)

**Comment by fdcastel** [comment]
> Will it? (...)

Hm. I see. @damienbod ?



> Under what circumstance?

I believe the [code](https://github.com/damienbod/angular-auth-oidc-client/pull/107/files#diff-3551bf70e40e99dfec0656111f37bf52R617) may explain better than me 😉 

> As for the rest regarding `AccessTokenExpiring` and `RefreshTokenError`, I agree :)

👍

**Comment by CesarD** [comment]
> I believe the code may explain better than me 😉

I think that only covers if silent renew is disabled. I've seen current applications I have coded in AngularJs with another OIDC javascript library, that if the browser tab was out of focus (another tab selected) for too many hours, it acted as if it was disabled, not keeping the timers and stuff of the silent renewal process, and when I focus on that tab, then right there the application detects that the access_token is already expired (because there was no renewal) and I have to re-authenticate... Also note that this would not trigger an error event, as the application and the library were never able to detect any...

All in all, it all goes down to the first paragraph I wrote in my previous comment, regarding how the "isAuthenticated" is interpreted. There should be some place in the code of the library where the expiration of the access_token is taken into account to determine its validity, as well as the user status.

**Comment by profet23** [comment]
getIsAuthorized() will now wait until setup is complete and silent renew has had a chance to run (if enabled).

This should alleviate this issue.

I reponded in the above mentioned PR, but if you need to react to token expiration... say a token that will expire in 1 minute, you can use something like the following:

```typescript
        this.oidcSecurityService.getIsAuthorized().pipe(
            filter((isAuthorized) => isAuthorized),
            map(() => this.oidcSecurityService.getPayloadFromIdToken()),
            pluck('exp'),
            delayWhen((exp: number) => {
                const date = new Date(0); // The 0 here is the key, which sets the date to the epoch
                date.setUTCSeconds(exp);

                const timeToExpiration = date.valueOf() - (new Date().valueOf());
                const timeToNotification = timeToExpiration - (60 * 1000)  //1 minute before expiration

                return timer(timeToNotification);
            }),
            filter((exp) => {
                let payload = this.oidcSecurityService.getPayloadFromIdToken();
                return exp === payload.exp;
            })
        ).subscribe(() => {
            //do something when token is 1 minute from expiration
        });
```

@CesarD are we safe to close this issue?
