### ISSUE TITLE
v11 authorizedImplicitFlowCallback

### ISSUE THREAD

**Issue by jdubsmith** [damienbod/angular-auth-oidc-client#791]
In prior versions of OidcSecurityService there was a method named authorizedImplicitFlowCallback().  I can't find this in version 11.

If this has been renamed/moved/deprecated, I can not find it in the change logs.

**Comment by FabianGosebrink** [comment]
Hey @jdubsmith , you can see in the migrations document https://github.com/damienbod/angular-auth-oidc-client/blob/master/docs/migration.md#old-2 that the callback-methods are not need to be called explicitly anymore. This is done via the lib.
