### ISSUE TITLE
OAuth implementation in Angular JS

### ISSUE THREAD

**Issue by VI1916** [damienbod/angular-auth-oidc-client#792]
I am working on an application which is using Angular JS framework. I want to know if Angular-auth-oidc-client will supported if used in Angular JS. 

I am also looking for reference code for Authorization code flow throught PKCE.

**Comment by FabianGosebrink** [comment]
Hey @VI1916 , this lib does not support the AngularJS Framework. Please check the projects for all the examples: https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects
