### ISSUE TITLE
auto logini issue.

### ISSUE THREAD

**Issue by Taranbirbajwa** [damienbod/angular-auth-oidc-client#794]
Hi,
I was going through the code and found that autologin doen't work in start-sample-code-flow-auto-login.However, it works perfectly fine in start-sample-code-flow-azure-b2c.The only difference i noticed in the IDM configuration settings.Can someone comment on this

**Comment by FabianGosebrink** [comment]
So your issue is, that the auto login in the sample "sample-code-flow-auto-login" does not work, but it works in a sample where this is not even implemented? Did I understand you correct? Thanks.

**Comment by FabianGosebrink** [comment]
Closed due to inactivity. Please feel free to reopen if needed.
