### ISSUE TITLE
Silent Renew redirects to main page

### ISSUE THREAD

**Issue by IIIMalakitIII** [damienbod/angular-auth-oidc-client#796]
I have eventlisteners that warn me if I want to refresh the page. If i press 'Ok' redirect me to the main page localhost: 4200. This happens every 5 minutes. How can I fix it. Everything was done according to the tutorial. I use version 10/
![image](https://user-images.githubusercontent.com/47895919/85346578-8a1bec00-b4fe-11ea-9898-edfe7d88a9bd.png)

**Comment by FabianGosebrink** [comment]
Hey @IIIMalakitIII , what do you expect to work? What are you trying to do? What is the wanted behaviour? Do you have a sample repo?

**Comment by IIIMalakitIII** [comment]
Привет @FabianGosebrink I have a eventlistener for updating the page (so that the user does not accidentally refresh the page), the problem is that every five minutes, it redirects me to the main page. I do not know what could be the problem

![image](https://user-images.githubusercontent.com/47895919/85374257-28c73d80-b53d-11ea-9f40-3bf551bbbd0c.png)
![image](https://user-images.githubusercontent.com/47895919/85374331-48f6fc80-b53d-11ea-81d3-c89401e4f8b4.png)
![image](https://user-images.githubusercontent.com/47895919/85374396-6330da80-b53d-11ea-9dff-959e4e9488f7.png)

**Comment by FabianGosebrink** [comment]
I am pretty sure the silent renew also works on version 10 with the correct configuration. We recommend you to update to version 11 asap. We do not support version 10 anymore. @damienbod can you help with the config?

**Comment by IIIMalakitIII** [comment]
Hi @FabianGosebrink I upgraded to version 11 I had this error.
![Screenshot_8](https://user-images.githubusercontent.com/47895919/85576867-7036f200-b641-11ea-803a-bce7644ea27f.png)
![Screenshot_9](https://user-images.githubusercontent.com/47895919/85576888-74630f80-b641-11ea-81a0-19293e84c2f5.png)

**Comment by FabianGosebrink** [comment]
Is this problem still existing?
