### ISSUE TITLE
SSR broken due to use of window object

### ISSUE THREAD

**Issue by ericfowler303** [damienbod/angular-auth-oidc-client#797]
I'm trying to use this in Angular 9 using Angular Universal and running into these types of errors:

```
ReferenceError: window is not defined
    at Object._window [as useFactory] (C:\baf\dist\baf\server\main.js:171890:5)
    at Object.factory (C:\baf\dist\baf\server\main.js:77126:28)
    at R3Injector.hydrate (C:\baf\dist\baf\server\main.js:76993:63)
    at R3Injector.get (C:\baf\dist\baf\server\main.js:76743:33)
    at injectInjectorOnly (C:\baf\dist\baf\server\main.js:62616:33)
    at Module.ɵɵinject (C:\baf\dist\baf\server\main.js:62626:57)
    at Object.UrlService_Factory [as factory] (C:\baf\dist\baf\server\main.js:172173:590)
    at R3Injector.hydrate (C:\baf\dist\baf\server\main.js:76993:63)
    at R3Injector.get (C:\baf\dist\baf\server\main.js:76743:33)
    at injectInjectorOnly (C:\baf\dist\baf\server\main.js:62616:33)
```

This seems to be related to this piece of code:
https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/utils/window/window.reference.ts

which gets put in use here: https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/angular-auth-oidc-client/src/lib/auth.module.ts#L78

I don't know this well enough to know if there is some SSR type of change that can be made to have this function with Angular Universal.

My project is running with the latest Angular 9.1.11 and angular-auth-oidc-client 11.1.3

**Comment by FabianGosebrink** [comment]
SSR is sever rendered, so there no window object is available. Thanks for reporting.

**Comment by ericfowler303** [comment]
I hadn't come across this yet since Angular Universal is new to my experience but domino fixed the build issues completely, at least on my local dev build during runtime.

I am still testing to see that the auth still functions but I can confirm when that's been tested.

Thanks for pointing me in the right direction for this.

**Comment by GabrielGil** [comment]
In my opinion, this is only a patch which actually brings other problems. I tried it myself, and after tweaking it a bit, it is buggy.

Ideally, `angular-auth-oidc-client` makes the appropriate checks using [isPlatformBrowser](https://angular.io/api/common/isPlatformBrowser) where needed. What do you think @FabianGosebrink?

**Comment by FabianGosebrink** [comment]
Hey @GabrielGil , thanks for your message. What pther problems are you facing? Why is it buggy? Thanks

**Comment by GabrielGil** [comment]
It get to work somehow, I mean, to suppress the following error: 

```shell
 Getting auth well known endpoints failed on start [
  ReferenceError: window is not defined
```

If using the domino proposed solution, it does not play well with Angular Material. You can see I'm not the only one complaining about this strange workaround here: 
https://github.com/angular/universal/issues/1675

**Comment by GabrielGil** [comment]
Probably the best solution would pass by preventing the usage of the window object in the server environment, so the library API would be more consistent.

The window session storage is not available either way in the server platform and the user may opt to create a custom storage to use cookies and this way be able to identify the user and perform authenticated intercepted calls in the server side too.

In my opinion it doesn't make sense to create a domino mock object which at the end of the day does not offer any functionality either. The library should take care of controlling this edge cases.

What do you guys think?
