### ISSUE TITLE
when the user reloads the page, silent renew is not executed

### ISSUE THREAD

**Issue by ydg** [damienbod/angular-auth-oidc-client#80]
If the user is logged in and reloads the page, '_isAuthorized' is true in the storage. 

Hence authorizedCallback is never called and so neither is runTokenValidatation. 

If I understand the code correctly this means the timer that checks if the tokens are expired is never started and so the silent renew process is never started.

**Comment by damienbod** [comment]
@ydg sounds correct, would need to catch this somehow. This would mean that once the token expires, the next API call will return a 401 and redirect to the login. Thanks for finding this, we need a way of fixing this.

**Comment by ydg** [comment]
what if we moved the execution of 

`runTokenValidatation()` from `getUserinfo()` to `setupModule()`

I tried it locally and it seems to be behaving as I expect, but is there any bigger picture problem I am not seeing ?

**Comment by vicver82** [comment]
Thanks for raising this issue. I am having the same problem.

**Comment by damienbod** [comment]
@vicver82 @ydg I fix this as soon as possible. Thanks for raising this issue.

**Comment by damienbod** [comment]
@ydg @vicver82 fixed in version 1.3.17

**Comment by vicver82** [comment]
@damienbod Thank you very much. Your library is great!
