### ISSUE TITLE
max_id_token_iat_offset_allowed_in_seconds not working correctly

### ISSUE THREAD

**Issue by CommanderOS** [damienbod/angular-auth-oidc-client#800]
**Describe the bug**
max_id_token_iat_offset_allowed_in_seconds is not working the way it supposed to work,
the token is not invalidated.

**To Reproduce**
1. Set the max_id_token_iat_offset_allowed_in_seconds to 600 seconds.
2. Change the clock on the pc to 10 minutes behind global clock.
or
3.Set the clock on the pc to 10 minutes infront of the global clock.

**Expected behavior**
Expected to get an event that the difference is more than the offset allowed.

**Behaviour**
When time is behind the global clock token always remains active.
When time is after the global clock the token is invalidated only if time difference is below one minute.

**Comment by damienbod** [comment]
@FabianGosebrink Maybe we could add a test to validate this

**Comment by woeterman94** [comment]
Any update on this?

**Comment by FabianGosebrink** [comment]
Since we released new versions since the bug came up: Is this bug still relevant?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
