### ISSUE TITLE
OidcSecurityCheckSession not receiving check session response messages

### ISSUE THREAD

**Issue by avinash-more** [damienbod/angular-auth-oidc-client#804]
i have getting error after login **OidcSecurityCheckSession not receiving check session response messages** can you please provide solution.

and also i have logout from one tab then other tab remain logged in.

expected :- other tab should be logout.

screenshot:- 

![image](https://user-images.githubusercontent.com/45229708/85983052-7abc0780-ba04-11ea-94b8-22567e06f460.png)

version : - 11.1.3

@damienbod  / @FabianGosebrink    please help me out for this issue.

**Comment by avinash-more** [comment]
![image](https://user-images.githubusercontent.com/45229708/86018951-a14d6300-ba43-11ea-9ab5-2a0fa3a8f354.png)
![image](https://user-images.githubusercontent.com/45229708/86019164-e5406800-ba43-11ea-826f-a04db1d530b8.png)
![image](https://user-images.githubusercontent.com/45229708/86019199-f0939380-ba43-11ea-9684-b10dace3d35e.png)

pollServerSession function called and iframe window also loaded.

@damienbod  can you please check issue.

**Comment by damienbod** [comment]
hi @avinash-more  This code does npt looking familiar. Could you not just use the checksession like in the samples?

Greetings Damien

**Comment by avinash-more** [comment]
i have added startup service Which call in APP INITIALIZER and in that load custom configuration from server then initialize oidcConfigService with custom configuration.
After auth service i am trying to listen check session event but it not getting. in console getting error.

if postmessage response getting but at least first time check session event should be called because initial post message called. 

**configuration added in APP initialization startup service: -** 
![image](https://user-images.githubusercontent.com/45229708/86323036-b4d21700-bc59-11ea-86e1-61a8118bc573.png)

**auth service added console log:-** 
![image](https://user-images.githubusercontent.com/45229708/86323162-f19e0e00-bc59-11ea-9e7b-be5ee8fc6162.png)

**Comment by andrew-landsverk-win** [comment]
We are seeing this exact same behavior on `11.1.4` and using KeyCloak as our idP, prior to our upgrade from 10, this was working with no issues :)

**Comment by andrew-landsverk-win** [comment]
Just following up, I only see the error when I'm testing on localhost against a idP hosted elsewhere. Guessing it's due to `SameSite` cookies set by the idP (KeyCloak). When I deploy to production, on the same domain as the idP I don't see the error messages.

**Comment by andrew-landsverk-win** [comment]
Sorry, one last follow up, it's because Keycloak was setting a CSP header that didn't include localhost:4200, now it works everywhere for me :)

**Comment by avinash-more** [comment]
we are using same keyclock with different client so there is any solution to solve this problem? @andrew-landsverk-win

**Comment by andrew-landsverk-win** [comment]
Yes, in your realm settings, under "Security Defenses" you will need to alter the `Content-Security-Policy` section to include a bit about `frame-ancestors 'self'` and then also include http://localhost:4200 for your localhost testing client and also any production URLs for your production client.

![image](https://user-images.githubusercontent.com/60662463/88545462-a371f580-cfe0-11ea-96d6-ea023dd8da90.png)
