### ISSUE TITLE
Implicit Flow with Auto Login

### ISSUE THREAD

**Issue by darge98** [damienbod/angular-auth-oidc-client#806]
Hi,

Today my software use the version 10.0.15 of the library. I want to update to Angular 9 and update the library to version 11.1.3.
I use the implicit flow and I implement the auto-login. After update the library I have an infinite loop and I cannot access my website. It's possibile to have a guide of the autologin implementation with the implicit flow? 

Thanks.

**Comment by FabianGosebrink** [comment]
Have you checked out the samples in this repo?

**Comment by darge98** [comment]
Yes, I started from the project `sample-implicit-flow-silent-renew` and added autologin feature of `sample-code-flow-auto-login`.
At the end I found the problem, I have 2 subscription to `checkAuth` observable, and this will cause an infinite loop (one in AppComponent with a log and one in HomeComponent with autologin procedure).
