### ISSUE TITLE
Is it possible to ide angular-auth-oidc-client with Cordova ?

### ISSUE THREAD

**Issue by ErikParso** [damienbod/angular-auth-oidc-client#807]
Is it this package compatible to use with angular application wrapped with cordova ? If yes, is inappbrowser plugin required ? I managed to redirect back to my app after successfull login, but it is open in system browser instead of application instance. Is there any existing example ?

**Comment by damienbod** [comment]
@FabianGosebrink Do you think we could add a sample for this? I have never done any Cordova stuff. We would need the changed this a bit probably, the native app would be slightly different to the SPA version

**Comment by FabianGosebrink** [comment]
Yes we can do this. But we have more urgent issues and bugs currently so for me this has not the highest prio imho.

**Comment by FabianGosebrink** [comment]
Have you seen this usage in an ionic app? https://stackoverflow.com/questions/62840744/angular-auth-oidc-client-in-a-ionic-android-application

**Comment by ErikParso** [comment]
With custom-scheme plugin i was able to redirect to application after login. This oidc client reads code from current URL (window.location.href) what in case of native application is file path. Code can be parsed from redirect URL using handleOpenUrl method, but there is no way to use it, or to set it in window.location. Hope this information will be helpfull. For now i had to use oidc-client package.

**Comment by FabianGosebrink** [comment]
@ErikParso Can you maybe post an example on this? Working on an example for this library. Thanks!

**Comment by wolfpackt99** [comment]
facing the same issue. I have everything wire up and working to callback my application on andriod as this sample mentions:
https://offering.solutions/blog/articles/2020/09/17/securing-a-cordova-app-implemented-with-angular-using-oidc-and-oauth2/

I can see the full callback url in my application and call checkAuth with the url. Nothing happens. isAuthenticated$ is false.

I am looking in CallbackService at the regular expression handing looking or some parameters and they are there, but it just seems to stop.

**Comment by ErikParso** [comment]
> facing the same issue. I have everything wire up and working to callback my application on andriod as this sample mentions:
> https://offering.solutions/blog/articles/2020/09/17/securing-a-cordova-app-implemented-with-angular-using-oidc-and-oauth2/
> 
> I can see the full callback url in my application and call checkAuth with the url. Nothing happens. isAuthenticated$ is false.
> 
> I am looking in CallbackService at the regular expression handing looking or some parameters and they are there, but it just seems to stop.

Hi, i didnt manage to use this package for my project because of this problem. In final result a ended up using oidc-client package. Chceck my repo specificaly this service and usage in angular https://github.com/ErikParso/IglooSmartHome/blob/master/IglooSmartHome/Client/igloo-smarthome-app/src/app/services/authentication.service.ts
