### ISSUE TITLE
Angular 10 tslib warning

### ISSUE THREAD

**Issue by PartyArk** [damienbod/angular-auth-oidc-client#814]
With Angular 10 (and therefore tslib 2.0) I get this on `npm install `

`npm **WARN** angular-auth-oidc-client@11.1.3 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.`

I think the angular team recommends a new way of depending on tslib for libraries. Doesn't seem to make any difference to the functionality of the code.

**Comment by damienbod** [comment]
hi @PartyArk Thanks for reporting.

@FabianGosebrink any ideas?

**Comment by FabianGosebrink** [comment]
Yeah, we'll check that out and tackle that in the next days. Thanks for reporting!

**Comment by PartyArk** [comment]
Thanks I think this is the relevant doc-  https://angular.io/guide/migration-update-libraries-tslib

**Comment by FabianGosebrink** [comment]
IMHO as the PR is merged, we can close this one. Feel free to re-open if you have any further errors.

**Comment by PartyArk** [comment]
Hi, I think this has regressed for 11.2.1 - the package.json  reference to tslib has reverted back to an old version.

Thanks!
