### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by brentos99** [damienbod/angular-auth-oidc-client#82]
Hey, 

Great work, I really like this library. 

I was wondering if you have a method for forcing login when the Angular app starts. I tried using a Guard and calling _.authorize()_, but I ended up in a huge loop, where the call to _.getIsAuthorized()_ wasn't initialised before I the guard called _.authorize()_ again. :( 

The same code with a button calling _.authorize()_ works perfectly. 

FYI - In my loop I was seeing a lot of **incorrect nonce** errors which was a huge red herring. 

Thanks 

Brent

**Comment by damienbod** [comment]
thanks, I'll have a look this week. (I have implement this for a client this week.

Greetings Damien

**Comment by damienbod** [comment]
@brentos99 @tcrite

Hi Brent

I've implement this here:

https://github.com/damienbod/angular-auth-oidc-sample-google-openid/blob/master/src/AngularClient/angularApp/app/app.component.ts

And the auto-login component is required for the login redirect.

Will blog about it when I get a chance.

Greetings Damien

**Comment by damienbod** [comment]
https://damienbod.com/2017/09/26/auto-redirect-to-an-sts-server-in-an-angular-app-using-oidc-implicit-flow/

**Comment by damienbod** [comment]
@brentos99 Can I close this?
