### ISSUE TITLE
When Silent Renew begin, IE shows strange error message

### ISSUE THREAD

**Issue by daddyschmack** [damienbod/angular-auth-oidc-client#820]
Silent Renew works as expected in Chrome, but IE11 reports: 
```
starting Silent renew
RefreshSession created. adding myautostate:  573d145e65a225472ac49169d11b18ba19Obldm34
   "RefreshSession created. adding myautostate: "
   [
      0: "573d145e65a225472ac49169d11b18ba19Obldm34",
      length: 1
   ]
```
then
```

silent renew failed! periodically check failed
   "silent renew failed!"
   [
      0: "periodically check failed",
      length: 1
   ]
```

I have updated the polyfils.
config:
```
const setupAction$ = httpClient.get<any>( environment.auth.domain + '/.well-known/openid-configuration').pipe(
    map((customConfig) => {
      return {
        startCheckSession: true, 
        silentRenewUrl: redirectURI + '/silent-renew.html', 
        logLevel: LogLevel.Debug,
        historyCleanupOff: true,
        stsServer: environment.auth.domain,
        redirectUrl: redirectURI,
        postLogoutRedirectUrl: redirectURI,
        postLoginRoute: '/home',
        forbiddenRoute: '/forbidden',
        unauthorizedRoute: '/unauthorized',
        trigger_authorization_result_event: true,
        log_console_warning_active: true,
        max_id_token_iat_offset_allowed_in_seconds: 35999,
        renewTimeBeforeTokenExpiresInSeconds:180,
        clientId: 'someClientID',
        scope: 'openid profile email',
        responseType: 'id_token token',
        expires_in: 600,
        responseMode: 'form_post',
        silentRenew: true,
        customParams: {
          pfidpadapterid: 'compKerberosHTMLForm',
          auto_clean_state_after_authentication: true,
          auto_userinfo: true,
        }
      };
    }),
    switchMap((config) => oidcConfigService.withConfig(config))
  );

  return () => setupAction$.toPromise();
```
Please advise, we are so close!

**Comment by FabianGosebrink** [comment]
Can you confirm that it works on other browsers with the same config and code?

**Comment by daddyschmack** [comment]
Absolutely it does.. It work in Chrome.. We only use Chrome and IE..

**Comment by daddyschmack** [comment]
update, I was not importing the custom event polyfill correctly, but then I did, and the error message is now: 
"Object doesn't support this ..."

**Comment by daddyschmack** [comment]
Next Update, now I'm past the "Object doesn't support..." error using this script in the silent renew.
But I did receive a 401 on the network call..  I changes the silent renew html to be this:

    console.log('running the window onload');
    /* The parent window hosts the Angular application */
    var parent = window.parent,
      isIE11 = !!window.MSInputMethodContext && !!document.documentMode,
      event;
    /* Send the id_token information to the oidc message handler */
    debugger;
    if (isIE11) {
      /** Alter*/
      event = document.createEvent('CustomEvent');
      event.initCustomEvent('oidc-silent-renew-message', false, false, window.location);
    } else {
      //  var event = new CustomEvent('oidc-silent-renew-message', { detail: window.location });
      var event = new CustomEvent('oidc-silent-renew-message', {detail: window.location.hash.substr(1)});
      parent.dispatchEvent(event);
    } ;
  }

</script>

**Comment by mluker** [comment]
@daddyschmack You are close (your window.location for ie is wrong), I just fought through all of this for the last 3 hours.... See my post https://github.com/damienbod/angular-auth-oidc-client/issues/886
