### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by anthonynewlineinfo** [damienbod/angular-auth-oidc-client#822]
**Describe the bug**
I have converted mobile app from angular 9 app using capacitor.
I tried to connect identityserver4(for demo: https://demo.identityserver.io) using angular-auth-oidc-client.
its working in web but not working in mobile app. I'm getting CORS issue

**Screenshots**
![image](https://user-images.githubusercontent.com/28350118/87009837-5cfc5880-c1e3-11ea-9917-4d6cd9a6a841.png)

**Comment by jScope** [comment]
Hello @anthonynewlineinfo, I'm not professional with this package here but why do you think this is a CORS error? To me it seems like this package here tries to read the auth data (access_token) from the browsers SessionStorage which should be the default storage location for this package here.

I think you have to implement an alternative fallback storage. Please see here:
https://github.com/damienbod/angular-auth-oidc-client/blob/master/docs/features.md#custom-storage

In your special case capacitor storage API should be the best choice.
https://www.joshmorony.com/using-the-capacitor-storage-api-for-storing-data/

**Comment by damienbod** [comment]
Hi @anthonynewlineinfo  yes CORS needs to be activiated on the server for the client. So if you use the demo STS, then you need t use the same redirect URLs which is configured for this server. Cretae your own STs and you can do this yourself.

Greeitngs Damien
