### ISSUE TITLE
Silent-renew doesn't work after connection return if user goes offline  V11.1.4

### ISSUE THREAD

**Issue by MohammedGomaaS** [damienbod/angular-auth-oidc-client#824]
### Description
if the user goes offline and his token got expired while he is still offline, then after he came back online silent-renew doesn’t work to get him a valid token 

**Scenario**
1- user has a valid token for an hour and during this hour user goes offline
2- silent renew heart beat still working and detecting the token still valid
3- user still offline and his token got expired
4- silent renew mark itself running, and try to get a new token using connect/authorize, and connect/token
5- user return online 
6- the process doesn’t work After the user come online 

**My Config**
```
 let openIdConfiguration: OpenIdConfiguration = {
    stsServer: environment.apiBaseUrl_IDP,
    redirectUrl: getBaseUrl(), //+ 'callback',
    clientId: AppConfig.clientId,
    responseType: 'code',
    scope: 'openid profile qorrect_api IdentityServerApi',
    // postLogoutRedirectUri: postLogoutRedirectUri,
    startCheckSession: true,
    postLoginRoute: getLastRequestedUrl(),
    forbiddenRoute: '/forbidden',
    unauthorizedRoute: '/unauthorized',
    silentRenew: true,
    silentRenewUrl: getBaseUrl() + '/silent-renew.html',
    historyCleanupOff: true,
    autoUserinfo: true,
    logLevel: LogLevel.Debug,
    maxIdTokenIatOffsetAllowedInSeconds: 5,
    renewTimeBeforeTokenExpiresInSeconds: 5,
    // eagerLoadAuthWellKnownEndpoints:true,
    //  useRefreshToken: true,
    // triggerAuthorizationResultEvent: true,
    // autoCleanStateAfterAuthentication:true,
    // disableIatOffsetValidation:true
    // ignoreNonceAfterRefresh:true
    // disableIatOffsetValidation:true,
  };
```

**Comment by PartyArk** [comment]
I can confirm this - it's a bit tricky to reproduce but what you can do is set the `access_token_expires_at`  session variable to something silly like 1000 and you'll see that while silentRenew appears to work and authorization is achieved, userData$ is now empty or invalid.

It's a significant bug because it means that if you have an expired token (for instance, by being offline), then you'll appear to authorize ok, but anything that depends on userData will be broken.

The problem is that in 11.1.4 `codeFlowCallbackSilentRenewIframe` replaced `isRenewProcess: false` to `isRenewProcess: true` . I'm not really sure what this flag is supposed to do, but the essence of the bug is that this flag is now stopping `getAndPersistUserDataInStore` from saving any new data received from the callback.

**Comment by MohammedGomaaS** [comment]
I made the token expires every  5 seconds and when i go offline this error message appeared 
`zone-evergreen.js:2845 POST http://localhost:5000/connect/token net::ERR_INTERNET_DISCONNECTED`
then i came back online and renewing token dies  and stop calling the apis of the renew token 
@PartyArk

**Comment by PartyArk** [comment]
@MohammedGomaaS  There are possibly two separate issues here then.

**Comment by MohammedGomaaS** [comment]
No It is the same but  explained more
@PartyArk

**Comment by MohammedGomaaS** [comment]
@PartyArk 
I created a simple video for the issue, so you can understand it well
[https://drive.google.com/file/d/1D1rTxQktoyP_DhqQt56J8-lvi4zWYocv/view](url)

**Comment by valdian** [comment]
As @PartyArk, I also would like to know whether not renewing user data (i.e. not calling userinfo endpoint of the oidc provider) after silent renew is desired behaviour or not.

In my application, I need to be able to request renewing user data. In version 10, there was a method called `getUserinfo()`, which I used for it. In version 11.1.3 I use `forceRefreshSession()` to renew tokens as well as user data.

If not renewing user data after silent renew is desired behaviour, I would appreciate return of `getUserinfo()`. I can create a PR for it, if you prefer this way.

**Comment by MohammedGomaaS** [comment]
After going offline and  failing to refresh token, the renewing of the auth data (calling any APIs) is stopped  and not working again even return back online.
After return back online and calling `forceRefreshSession()` ,it calls the api of getting token and not working again.
You can see the behavior from this video 
https://drive.google.com/file/d/1D1rTxQktoyP_DhqQt56J8-lvi4zWYocv/view
@valdian

**Comment by valdian** [comment]
@MohammedGomaaS 
Sorry for the confusion, I was talking about a minor thing which was mentioned in this discussion by @PartyArk , but is not directly related to your issue. Please, ignore my comment, I will create a separate issue for it.

**Comment by damienbod** [comment]
Hi @MohammedGomaaS  if you go offline, when the tokens are invalid (expired), then yes you need to login again
