### ISSUE TITLE
New user link creates new browser instance so no local storage. Possible to disable local storage?

### ISSUE THREAD

**Issue by rickers1** [damienbod/angular-auth-oidc-client#827]
My Identity Server sends an email with a link to verify a new user's email address but clicking this creates a new browser instance so we lose the local storage that angular-auth-oidc-client uses once logged in and I get invalid state as the local state is now null.

Is it possible to disable the local storage use or is there a configuration option I've missed to have it not throw an error if there is no local state?
(Using v11.1.4)

**Comment by arv9135** [comment]
As much i know, angular-auth-oidc-client uses session storage by default that gets cleared whenever you open the website in new tab. To fix the issue you can use cookie storage. Please try my solution, if still facing issues. Please comment here.
Source code:
[Cookie storage for angular auth oidc client](https://github.com/arv9135/Angular-IdentityServer-Cookie)
[Medium article](https://medium.com/@arv9135/angular-10-spa-and-identity-server-4-authorization-code-flow-with-pkce-with-cookie-storage-a572a8baa4ea?source=friends_link&sk=1c991960d3b782779fa03b789fe2c797)

**Comment by damienbod** [comment]
And you can implement your own storage as required. @arv9135 Thanks for the links-

Greetings Damien
