### ISSUE TITLE
With SilentRenew set to false, it still tries to run SilentRenew

### ISSUE THREAD

**Issue by StefanSzakacs21** [damienbod/angular-auth-oidc-client#828]
**Describe the bug**
I am trying to use the library without having silentRenew active, but after setting it to false it still tries to create the iframe and run a silent renewal.

**To Reproduce**
1. Set silentRenew to false in config, or delete altogether
2. Run oidcService.authorize()
3. After getting redirected from SSO to app, an iframe is created for the silent renewal

**Expected behavior**
To not have an iframe or anything related to silent renewal run

**Screenshots**
![image](https://user-images.githubusercontent.com/18661429/88153644-57a10400-cc0e-11ea-8f08-964a8cd06f24.png)
![image](https://user-images.githubusercontent.com/18661429/88153822-99ca4580-cc0e-11ea-8427-5e5c1b7fadd7.png)
![imageedit_0_4440874294](https://user-images.githubusercontent.com/18661429/88154331-5e7c4680-cc0f-11ea-9496-ac617d8d1954.png)

**Comment by damienbod** [comment]
Hi @StefanSzakacs21 validated this and cannot reproduce. Using the `this.oidcSecurityService.checkAuth()`^and silentRenew = false, this does not happen.

Greetings Damien

**Comment by ChubbyArse** [comment]
I too have observed this behaviour by creating an new angular app and copying the app/** files in from: https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects/sample-code-flow

Regardless of settings, the iframe is ALWAYS started. My config (some parts redacted):

```
        oidcConfigService.withConfig({
            stsServer: 'https://localhost:XXX',
            redirectUrl: window.location.origin,
            postLogoutRedirectUri: window.location.origin,
            clientId: 'xxxxxxxxx',
            scope: 'openid profile email',
            responseType: 'code',
            silentRenew: false,
            silentRenewUrl: `${window.location.origin}/silent-renew.html`,
            renewTimeBeforeTokenExpiresInSeconds: 10,
            logLevel: environment.production ? LogLevel.None : LogLevel.Debug,
        });
```

**Comment by ChubbyArse** [comment]
Furthermore - if I remove the lines silentRenew and silentRenewUrl - I get a 400 from the identity server as the connect/token call looks like this:
```
XHRPOSThttps://localhost:5011/connect/token
[HTTP/2 400 Bad Request 39ms]

    	
    grant_type	"authorization_code"
    client_id	"xxxxxxxxxxxxxxx"
    code_verifier	"2ad54bd8467b6a9a43b91572e06ff41f843844864a47085b6cbfaf9a3504V7sj1do"
    code	"8FA63BA43F1D33E9D52AA2780F65CD2478FF5FDB5C1E141D543121D2A62C31C3"
    redirect_uri	"https://please_set"

    1

    grant_type=authorization_code&client_id=xxxxx&code_verifier=2ad54bd8467b6a9a43b91572e06ff41f843844864a47085b6cbfaf9a3504V7sj1do&code=8FA63BA43F1D33E9D52AA2780F65CD2478FF5FDB5C1E141D543121D2A62C31C3&redirect_uri=https://please_set
```

**Comment by damienbod** [comment]
This is due to the `checkAuthIncludingServer`  which uses silent renew to check the server. The checkAuth should be used. I'll remove this from the defualt example and maybe document this, thanks for reporting

https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/sample-code-flow/src/app/app.component.ts#L12

**Comment by damienbod** [comment]
fixed
