### ISSUE TITLE
Infinite redirect loop on autologin component - Azure AD - id_token (openid connect)

### ISSUE THREAD

**Issue by radzikp** [damienbod/angular-auth-oidc-client#829]
Similar to:  
- Implementing the auto login is sending it in an endless loop #180
- Auto-Login with PKCE Code Flow Issues #470

> This can be tricky to implement, as you need to know when to redirect and when not

Looks like access token needed...?
I dont want to get access token because I am going to use different token provider based on id_token acquired from Azure AD
Based on azure ad example, here are some details:

**Config:**
```
  "stsServer": "https://login.microsoftonline.com/client_id",
  "authWellknownEndpoint": "https://sts.windows.net/client_id",
  "clientId": "client_id",
  "scope": "openid profile email api://client_id/access_as_user",
  "responseType": "id_token",
  "maxIdTokenIatOffsetAllowedInSeconds": 600,
  "issValidationOff": false,
  "autoUserinfo": false,
  "silentRenew": true,
  "silentRenewHtml": "/silent-renew.html",
  "startCheckSession": false,
  "postLoginRoute": "/some_home_url",
```

**Desktop:**
 - OS: Windows7
 - Browser: Chrome
 - Version: 83.0.4103.116 (Official Build) (32-bit)

**Additional context**
- Angular 9
- Azure AD

**Comment by radzikp** [comment]
It might be something related to : 
`Wanted to read '4dd88a6b-84b3-4c80-a53d-d2ea09e09eee_authzData' but nothing was found` ?

**Comment by damienbod** [comment]
Hi where you able to get this to work?


Greetings Damien

**Comment by lwensveen** [comment]
I have this exact same issue.

**Comment by jjonas3** [comment]
I have this issue also ... 
Has id_token expired: false, 1598282722000 > 1598282530729
node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js:204
at_hash from the server:5Btcjkvnico0pgGZkyRvOw
node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js:204
at_hash client validation not decoded:5Btcjkvnico0pgGZkyRvOw
node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js:204
AuthorizedCallback token(s) validated, continue

then ...
storing the accessToken
node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js:204
HttpCallsInterceptor:intercept:Auth token is available and user is logged in.
src/app/shared/http/http-interceptor.ts:52
ValidateStateFromHashCallback failed, state: 0789a95878d8ab7b58f951d6af74e6b041do0Xk8f local_state:null
node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js:204
authorizedCallback incorrect state
node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js:188
AuthorizedCallback token(s) invalid
node_modules/angular-auth-oidc-client/fesm5/angular-auth-oidc-client.js:204
authorizedCallback, token(s) validation failed, resetting. Hash

**Comment by lwensveen** [comment]
Do you guys also go from Unauthorized > Authorizing > Authorized > Unauthorized?

**Comment by damienbod** [comment]
@lwensveen  Would you not upgrade away from the Implicit Flow? I have exampes of the Implicit Flow, but none with the auto login. This would work, but you would need to configure this a bit different.  Important is that the default return URL is not an auth route so that the callback logic can be executed without another redirect.
