### ISSUE TITLE
Forgot Password Implementation

### ISSUE THREAD

**Issue by mikelunn** [damienbod/angular-auth-oidc-client#83]
Thanks for this contribution. I'm interested in learning how one would handle the forgot password scenario using this module to authenticate to the Azure AD B2C service. For whatever reason, the Azure B2C user interface "forgot password link" seems to always redirect the user back to the app (I guess because it is not part of the SignIn/Sign Up policy). The same issue exists when using [msal.js](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/9). Forgot password seems like such a trivial thing to implement, but I have noticed that it is  not implemented or demonstrated in many of the Azure B2C SPA examples. When using this module, clicking on the "Forgot Password link" on the Azure b2c UI redirects the user back to the app, this module throws the following error
`{error: "access_denied", error_description: "AADB2C90118%253a+The+user+has+forgotten+their+pass…Timestamp%253a+2017-09-20+18%253a16%253a31Z%0D%0A"}error: "access_denied"error_description: "AADB2C90118%253a+The+user+has+forgotten+their+password.%0D%0ACorrelation+ID%253a+f0ec97ad-6aa1-433e-9b33-eb85d9d5715f%0D%0ATimestamp%253a+2017-09-20+18%253a16%253a31Z%0D%0A"__proto__: Object
`
Is there a method on the OidcSecurityService that would allow me to listen for this error?

**Comment by damienbod** [comment]
@mikelunn Hi I'll have a look at this is the next week or so. The forgot password runs with no user logged in  which means the app needs to handle this an allow it. The required API requests should not use the auth header.

Greetings Damien

**Comment by mikelunn** [comment]
@damienbod Figured out all that is needed is to handle the error by the specific code in the error description. Thanks again for your work.

**Comment by luklew** [comment]
@mikelunn Hi , Would you be able to help me out? How did you manage to get the error code using auth-oidc library?

**Comment by mikelunn** [comment]
@luklew I ended up not using a client side lib for authentication. I moved all this logic server side. But if your using msal.js I posted a code sample of accessing the code sample:
[https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/9#issuecomment-611700388](url)
