### ISSUE TITLE
checkAuthIncludingServer stuck with blank page.

### ISSUE THREAD

**Issue by arv9135** [damienbod/angular-auth-oidc-client#830]
**Describe the bug**
this.oidcSecurityService
      .checkAuth() is working fine in every case.

this.oidcSecurityService.checkAuthIncludingServer() works well when user is already logged with identity provider. 
but stuck on blank page when you clear the cookies and session and refresh the page.
Steps are provided below for reproducing

import { Component } from '@angular/core';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
    isAuthenticated: boolean;
  constructor(private oidcSecurityService: OidcSecurityService, private router: Router) { }

  ngOnInit() {
    this.oidcSecurityService
      .checkAuthIncludingServer()
    
      .subscribe((isAuthenticated) => {
        console.log('in auth folder');
        this.isAuthenticated = isAuthenticated;
        if (!isAuthenticated) {
          this.router.navigate(['/login']);
        }
        else {
          this.router.navigate(['/']);
        }
      });
  }
}

**To Reproduce**
1. Implement the code mention above.
2. either clear the cookies and session for the website or open url in new incognito mode.
3. You will stuck with blank page.
4. No error visible in console.
5. use below configuration:
oidcConfigService.withConfig({
      stsServer: <idp url>,
      redirectUrl: `${window.location.origin}/`,
      clientId: 'angular_spa',
      scope: 'openid profile email',
      responseType: 'code',
      triggerAuthorizationResultEvent: true,
      postLogoutRedirectUri: `${window.location.origin}/`,
      startCheckSession: false,
      silentRenew: true,
      silentRenewUrl: `${window.location.origin}/silent-renew.html`,
      postLoginRoute: '/',
      logLevel: LogLevel.Debug,
      historyCleanupOff: true
    });

**Expected behavior**
case 1) If there is a valid session for the website, it should login(working fine in this case)
case 2) if session is invalid but cookies are valid for identity provider, it should create a valid session from there(working fine in this case too)
case 3) If session as well as cookies both are invalid or cleared, it should redirect to login page(not working, stuck with blank page) as it works with method this.oidcSecurityService.checkAuth().

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by Expelz** [comment]
@arv9135 Please indicate which library version do you use? 
I think this issue are related to version 11.1.3 - #779

**Comment by arv9135** [comment]
Using 11.1.4

**Comment by Expelz** [comment]
@arv9135, Could you share your console log?

**Comment by arv9135** [comment]
@Expelz console logs attached.
![image](https://user-images.githubusercontent.com/25680919/89282630-715c3580-d669-11ea-92f0-343c6184054f.png)

**Comment by arv9135** [comment]
![image](https://user-images.githubusercontent.com/25680919/89282998-065f2e80-d66a-11ea-99cb-4dde89269997.png)
@Expelz

**Comment by arv9135** [comment]
![image](https://user-images.githubusercontent.com/25680919/89283116-38709080-d66a-11ea-9ce2-68bdc717014e.png)
@Expelz

**Comment by Expelz** [comment]
@arv9135, It is safe to say that the problem is on the identity server (IS) side. Because your log shows that silent renew process was launched successfully and a very important log that shows it: `removed event listener from Iframe` . This means that the Iframe was created successfully and was redirected to your IS authorize endpoint.

The blank page is displayed because `checkAuthIncludingServer` simply waiting for any response but you don't receive it. Please check the IS logs also look inside `Network` tab (Google Chrome) and check status and response of the next request (highlighted by red line):
![image](https://user-images.githubusercontent.com/33082852/89503831-ca45de00-d7cf-11ea-8271-3bf92d098104.png)

I guess it will be in `pending` status.
