### ISSUE TITLE
CheckSession not firing when session ends

### ISSUE THREAD

**Issue by CobusKruger** [damienbod/angular-auth-oidc-client#831]
I want to be able to share sessions between tabs. To this end, I implemented custom storage around `localStorage`. That part is working just fine. Now I need to have single sign-out for all those tabs, and the way I understand, checkSession is key to that. This is based on [this reply by damienbod](https://github.com/damienbod/angular-auth-oidc-client/issues/233#issuecomment-393774475).

So I took a copy of the sample-code-flow app, enabled SSL in the `angular.json` and passed my storage class to `AuthModule.forRoot`. I also changed the logging code in `app.module.ts` to log all events:

```typescript
export class AppModule {
    constructor(private readonly eventService: PublicEventsService) {
        this.eventService
            .registerForEvents()
            .subscribe(event => {
                switch (event.type) {
                    case 0: console.log('ConfigLoaded', event); break;
                    case 1: console.log('CheckSessionReceived', event); break;
                    case 2: console.log('UserDataChanged', event); break;
                    case 3: console.log('NewAuthorizationResult', event); break;
                    case 4: console.log('TokenExpired', event); break;
                    case 5: console.log('IdTokenExpired', event); break;
                }
            });
    }
}
```

When I sign in, I see the config event and user data event. I also see this often: `CheckSessionReceived {type: 1, value: "changed"}`

When I sign out of any tab, I only see `UserDataChanged {type: 2, value: null}` in the tab where I signed out. Surely, the CheckSession event should detect that the session is now invalid in the other tabs, but that isn't happening. Instead, they simply stop emitting *any* events at all.

So either CheckSession isn't working as described in that comment, or the behavior has changed, or I misunderstood. But whichever way, I don't see how I'm to detect the sign-out in other tabs.

**Expected behavior**
CheckSessionReceived should probably emit *something* when it checks the session and discovers it's no longer valid. Alternatively, I can see that any of these events could emit values useful in this case: UserDataChanged, NewAuthorizationResult, 
TokenExpired or IdTokenExpired.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Chrome
 - Version: 84.0.4147.89

**Comment by CobusKruger** [comment]
This is no longer a problem. The `PublicEventsService` events didn't help me, but I noticed the sample app didn't subscribe to the `OidcSecurityService` observables for `userData$` and `isAuthenticated$` but instead just assigned them to local fields (weird). Once I added subscriptions, I could confirm that both events fired for each tab after sign-out.

**Comment by Angelinsky7** [comment]
@CobusKruger I've got the same issue, what did you do "exactly" to have the other tab receive an event on signout ?
thanks a lot...

**Comment by CobusKruger** [comment]
@Angelinsky7 Sorry, mate. It's been nearly three years, and I've moved on to use another library. But the key was to switch storage to `localStorage`, and then check the result in the `isAuthenticated$` subscription. Unfortunately, there has been changes since, so your milage may vary.
