### ISSUE TITLE
Url is always at localstorage "redirect" even when already authenticated

### ISSUE THREAD

**Issue by xaviergxf** [damienbod/angular-auth-oidc-client#832]
I'm migrating from 9.0.7 to 11.1.4 and the behavior is different. I'm still using implicit flow. 

Before:
1. Not authenticated. localStorage "redirect" persisted with curent url (A) then redirect to autlogin.
2. Authenticated. navigateToStoredEndpoint called, url A retrieved from localstorage and redirected.
3. Manually click at route B.
4. Refresh page with F5
5. App is authenticated, redirected and redirected to page B (Latest page to navigate)

After:
1. Not authenticated. localStorage "redirect" persisted with curent url (A) then redirect to autlogin.
2. Authenticated. navigateToStoredEndpoint called, url A retrieved from localstorage and redirected.
3. Manually click at route B.
4. Refresh page with F5
5. App is authenticated, redirected and redirected to page **A** (First page after login)

Is this a bug? 

Thanks

**Comment by xaviergxf** [comment]
It seems to be working correctly now...

**Comment by xaviergxf** [comment]
It seems this is not working properly...

**Comment by FabianGosebrink** [comment]
Hey @xaviergxf , do you have a sample repo to reproduce the issue? Thanks

**Comment by xaviergxf** [comment]
Its the same as your auto login sample with implicit flow

**Comment by damienbod** [comment]
Hi @xaviergxf We made big changes here. Could you compare you app to the examples?

Greetings Damien

**Comment by Patricksirich** [comment]
Hi,
Not sure if this will help you, but here goes:

I had the same issue - also using implicit flow and the auto login with implicit flow example - I changed the ngOnInit in app.component to: 

`this.oidcSecurityService
            .checkAuth()
            .subscribe((isAuthenticated) => {
                if (!isAuthenticated) {
                    if ('/autologin' !== window.location.pathname) {
                        this.write('redirect', window.location.pathname);
                        this.router.navigate(['/autologin']);
                    }
                } else if (isAuthenticated) {
                    this.isAuthorized = true;
                    this.navigateToStoredEndpoint();
                    localStorage.removeItem('redirect');
                }
            });`

Not the best workaround, but it does its job without introducing any bugs or changes in performance, haven't had any issues with this.
The code that had the "bug" is long gone in our repo, so probably won't be able to find it unfortunately..
