### ISSUE TITLE
Question - Wanted to read 'clientId_storageSilentRenewRunning' but nothing was found

### ISSUE THREAD

**Issue by alvipeo** [damienbod/angular-auth-oidc-client#834]
I made a simple project based on this sample - https://github.com/damienbod/angular-auth-oidc-client/blob/master/projects/sample-code-flow-azure-b2c/src/app/app.module.ts.

When I run it I can log in but then I see this message indefinitely every ~5 sec:
> Wanted to read 'e5c0c3dc-5acc-4f20-9cd8-b71f6ff6d0c3_storageSilentRenewRunning' but nothing was found
> Checking: silentRenewRunning: false id_token: true userData: true
> Has id_token expired: false, 1596155845000 > 1596152449560
> silent renew finished!

Shouldn't it store something and not show this every couple of seconds? Is this normal or does it indicate some config problems?

Thank you.

**Comment by damienbod** [comment]
Hi @alvipeo 

this is just info messages. You could switch to logging to level warning and then it will no longer be displayed.

Greetings Damien

**Comment by alvipeo** [comment]
Got it. Thank you!
