### ISSUE TITLE
OidcSecurityService emits onModuleSetup before authWellKnownEndpoints are loaded

### ISSUE THREAD

**Issue by MovGP0** [damienbod/angular-auth-oidc-client#84]
`OidcSecurityService` is emiting the `onModuleSetup`-Event before the `AuthWellKnownEndpointsService` has loaded the endpoints. 

Instead, it should wait for the `onWellKnownEndpointsLoaded` event before emiting the `onModuleSetup`-Event.

**Comment by damienbod** [comment]
thanks, will test tomorrow and create a new release

**Comment by damienbod** [comment]
@MovGP0 

Thanks a million, this is part of the 1.3.16 package.
