### ISSUE TITLE
Reject parent promise when getAuthWellKnownEndPoints fails in config service

### ISSUE THREAD

**Issue by petersandor** [damienbod/angular-auth-oidc-client#842]
Errors thrown in custom HTTP middleware don't seem to be propagated upwards to the parent `withConfig` promise in the below section of config service:

https://github.com/damienbod/angular-auth-oidc-client/blob/4882457d9343548f9ff642a57691dd54cfecd9ed/projects/angular-auth-oidc-client/src/lib/config/config.service.ts#L58-L70

Note that it only calls the parent promise `resolve`, it's missing a `reject` call and a RxJS `catchError` operator (in case of errors in the underlying HTTP call).

**Comment by damienbod** [comment]
@petersandor Thanks for reporting. @FabianGosebrink I think we could improve this, agree?

Greetings Damien

**Comment by damienbod** [comment]
@FabianGosebrink has this been fixed?

**Comment by FabianGosebrink** [comment]
Yes this has been fixed.

**Comment by SebaM** [comment]
@FabianGosebrink is there any link to the fix? I wondering which version includes it?

**Comment by SebaM** [comment]
never mind I see the code: https://github.com/damienbod/angular-auth-oidc-client/blob/release_11_6_11/projects/angular-auth-oidc-client/src/lib/config/config.service.ts#L58-L76

**Comment by FabianGosebrink** [comment]
In the new version, which is not released yet, we pan to have the AuthWellKnown eager loaded per default, and you can explicitly load it through a separate method. So this config `eagerLoadWellKnownEndpoints` will be gone.
