### ISSUE TITLE
id_token_hint not passed in logoff function

### ISSUE THREAD

**Issue by bsocket** [damienbod/angular-auth-oidc-client#846]
**Describe the bug**
unable to successfully logoff from IDS$ provider directly or even when using  azure b2c with IDS4 as the Identity provider.
https://identityserver4.readthedocs.io/en/latest/endpoints/endsession.html describes correct behaviour. 
**To Reproduce**
login into azure b2c with IDS4as identity provider or even directly to the identity provider4 server.
**Expected behavior**
successful logoff disabling access to the authentication. But instead logoff fails since without id_token_hint the api tries to bring up a user prompt which fails since iframe is not without ancestors. see exact text belw0w

"**_Refused to frame 'https://portaldevidservice-as.azurewebsites.net/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'"._**

**Desktop (please complete the following information):**
 - OS: macpro
 - Browser chrome

**Comment by damienbod** [comment]
Hi @bsocket Yes you need to allow iframes to use the silent renew with iframes. Please allow thison your server (CSP policy) or switch to refreshing with refresh tokens.

**Comment by bsocket** [comment]
silent renew works fine. Its just that we don't want to be asked whether we to logoff. Its the problem with sessionend/logoff which needs the id_token_hint. see https://identityserver4.readthedocs.io/en/latest/endpoints/endsession.html. Also Azure b2C supports it.
