### ISSUE TITLE
oidcSecurityService.getToken() is empty when new browser tab is opened

### ISSUE THREAD

**Issue by hylleonline** [damienbod/angular-auth-oidc-client#851]
Everything is fine in the main browser tab where the authorize procedure took place. 

`this.oidcSecurityService.getToken();` gives me the token just fine:

![image](https://user-images.githubusercontent.com/3962152/92400879-e7523180-f12c-11ea-92d1-a71d23bf63d5.png)

But if I open a new tab (CTRL+T) and go to the same URL (http://localhost:4200 in my case), I get <empty string>
![image](https://user-images.githubusercontent.com/3962152/92401027-2aaca000-f12d-11ea-982a-0d2de289879d.png)

My configureAuth looks like this:
```
export function configureAuth(oidcConfigService: OidcConfigService) {
return () =>
  oidcConfigService.withConfig({
    stsServer: environment.authAuthority,
    redirectUrl: '${window.location.origin}/resolve',
    postLogoutRedirectUri: '${window.location.origin}',
    clientId: 'xxxx',
    scope: 'openid profile xxx',
    responseType: 'id_token token',
    silentRenew: true,
    silentRenewUrl: '${window.location.origin}/assets/silent-renew.html',
    logLevel: LogLevel.Warn,
  });
}
```

I need the token in my AuthInterceptor Class:
```
@Injectable()
export class AuthInterceptor implements HttpInterceptor {

    constructor(private oidcSecurityService: OidcSecurityService, private injector: Injector) { }
    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

        this.oidcSecurityService = this.injector.get(OidcSecurityService);
        const token = this.oidcSecurityService.getToken();

        console.log('token in intercept', token); <== this is the console.log in the screenshos above.


        if (token) {
            request = request.clone({
                setHeaders: {
                    Authorization: `Bearer ${token}`
                }
            });
        }
        return next.handle(request);
    }
}
```
My expectation would be that a new tab would be in the same scope as the main tab, but somehow this is not what I experience. Any help is greatly appreciated. And with this being my first ever post, I apologize if this issue is lacking information. Please let me know, if you need further information to investigate.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox and Chrome and presumeably all other browsers

**Comment by damienbod** [comment]
Hi @hylleonline  this is by design. SessionStorage is used and so per default, you are not in the same session on the client. You could do an auto login, or a silent renew check which would login you in (You are already logged on the server, so this would be automatic) or you cou,d switch to local storage, which would be less secure. 

Greetings Damien

**Comment by hylleonline** [comment]
OK, cool. I'm continuing with the SessionStorage approach and I got it to work with an auto-login approach by calling `this.oidcSecurityService.authorize();` 

But maybe silentRenew is better... How would I implement the silent renew approach? I already set up the config with
 ```
    silentRenew: true,
    silentRenewUrl: '${window.location.origin}/assets/silent-renew.html',
```

Is there a way explicitely call trigger a silentRenew?

**Comment by damienbod** [comment]
depends which silent renew you use. If you use refresh tokens, you just need to request the offline scope and set the silent renew to through. You could use the `checkAuthIncludingServer()` instead of the `checkAuth()` which will then send a silent renew request if starting up

**Comment by hylleonline** [comment]
Thank you for your very useful answers 👍
