### ISSUE TITLE
how to implement azure ad PKCE flow with multiple Api's( Graph, Custom Web Api) scopes

### ISSUE THREAD

**Issue by esvinae** [damienbod/angular-auth-oidc-client#852]
**Describe the bug**
I'm trying to register a ConfigLoaded event using PublicEventsService to load the configuration and get token for custom web api scope dynamically.

**Expected behavior**
I'm getting token and user details from Graph Api with User.read scope but i also need to get token for custom web api scope. can you please let me know how to configure this using PublicEventsService on configuration load and get the scope dynamically or do you have any other approach for multiple scopes.

**Comment by Expelz** [comment]
Hello @esvinae!
The current version of the library doesn't provide such functionalty. Only during configuration loading you can set scopes.
The only possible option is to fetch this scope (`custom web api scope`) before you will pass your oidc configuration to the `OidcConfigService.withConfig()` mehtod. And the you can simply append it to the `scope` property (identity provider should support multiple scopes during authorization process).

**Comment by fengzhihenxs** [comment]
@Expelz I have a similar requirement. Is it true that the scope attribute cannot contain both Microsoft graph and custom api? Besides, I don’t quite understand the method you said

**Comment by damienbod** [comment]
We support this using a backend implementation so not to handle multiple access tokens in the browser.

https://damienbod.com/2020/12/08/using-multiple-apis-in-angular-and-asp-net-core-with-azure-ad-authentication/

Greetings Damien
