### ISSUE TITLE
Add option to request renewing user data

### ISSUE THREAD

**Issue by valdian** [damienbod/angular-auth-oidc-client#855]
**Is your feature request related to a problem? Please describe.**
In my application, a user can update his profile. After he submits the form, his claims in the oidc provider (IdentityServer4) database are updated and the user data in the browser storage becomes outdated. 

Therefore, I need to be able to request renewing user data (i.e. call userinfo endpoint of the oidc provider) after the profile update. In version 10, there was a method called `getUserinfo()`, which I used for it. In version 11 (before 11.1.4), I use `forceRefreshSession()` to renew tokens as well as user data. Since #812, there is no way to do it.

**Describe the solution you'd like**
Add a parameter `renewUserInfoAfterTokenRenew` to `OpenIdConfiguration` and if it is set to `true`, then renew user data after a token renew.

**Describe alternatives you've considered**
1. Refresh user data always after token renew, as it was done in version 11.1.3.
2. Add a boolean parameter `shouldRefreshUserData` to the `forceRefreshSession()` method in `OidcSecurityService`.

**Additional context**
I will create a PR to demonstrate my idea but I am open also to other ways of solving my problem.

**Comment by damienbod** [comment]
I think this os good, thank!

**Comment by valdian** [comment]
Thanks for approving.
@damienbod When do you plan the next release?

**Comment by emresalum1993** [comment]
Any eta for next  release?

**Comment by damienbod** [comment]
Hi @emresalum1993 This has been released in version 11.2.1
