### ISSUE TITLE
Support for Proof Of Possession Tokens (Pop Scheme)

### ISSUE THREAD

**Issue by cvbc2010** [damienbod/angular-auth-oidc-client#859]
**Is your feature request related to a problem? Please describe.**
While going through Microsoft.Identity.Web platform. Got to know access token wrapped unside Proof Of Possession Token, where our tokens are signed based on HttpRequest and the Public Keys of Azure. and which are revalidated on Web Api retrieving from Pop Token.

**Describe the solution you'd like**
have another method(getPopToken()) which returns Pop Token from the Azure.

I think it is still in preview stage. but have a benefit of doubt does Auth Code flow with PKCE support Pop Tokens.

**Additional context**
[https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2](url)

**Comment by damienbod** [comment]
Only see this for mobile or desktop apps, don't see this in SPAs but this library is used for created mobile, desktop apps so..

Will look into this. 

https://tools.ietf.org/html/rfc7800

**Comment by damienbod** [comment]
won't implement, thanks for reporting.
