### ISSUE TITLE
Update HTTP client

### ISSUE THREAD

**Issue by damienbod** [damienbod/angular-auth-oidc-client#86]

**Comment by robisim74** [comment]
There are no changes in v5 about HttpClient, instead Http will be deprecated. So in my opinion is time to switching.

**Comment by damienbod** [comment]
Ok, I will do it tonight

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/tree/dev_httpclient

**Comment by damienbod** [comment]
merged into the master, will create a npm once it's tested
