### ISSUE TITLE
Sileint Renew Adding Custom Headers 

### ISSUE THREAD

**Issue by sashissd** [damienbod/angular-auth-oidc-client#860]
Hi Damien,
I am using  version 10.** as our application is built on angular 7.** ,  
As our APIs are behind gateway that (internal implementation) , In order to access any API it will accept   APIKEY as header for any request. We are able to add the API Key as header for all the requests using interceptor but there is 1 url (authorize for pkce) which is calling from silent renew  with the help of  IFRAME (I guess),  **for this url  I am unable to add the header**  is there any way we can add the header ? any help is highly appreciated. 
URL :
connect/authorize?client_id=***** &redirect_uri=***&response_type=code&scope=openid&nonce=$$$$$$&state=######&code_challenge=********&code_challenge_method=S256&prompt=none

**Comment by FabianGosebrink** [comment]
Hey @sashissd , thanks for the issue. Maybe [Custom Parameters](https://github.com/damienbod/angular-auth-oidc-client/blob/ae9dade2196615e9d39de639111b8ef7e4f167b3/docs/features.md#custom-parameters) is what you are searching for?

**Comment by sashissd** [comment]
Thanks, Fabian I will give it a try
