### ISSUE TITLE
Configure refresh token

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#862]
Hello, how to refresh the token when the token expires when using this library?

For example, after logging in with azure ad, the token expires after a period of time. How to refresh the token?

**Comment by fengzhihenxs** [comment]
My version is:: "angular-auth-oidc-client": "^11.1.3"，angular is v9.
My configuration is (not working):
oidcConfigService.withConfig({ 
      stsServer: 'https://login.microsoftonline.com/7ff95b15-dc21-4ba6-bc92-824856578fc1/v2.0',
      authWellknownEndpoint: 'https://login.microsoftonline.com/common/v2.0',
      redirectUrl: window.location.origin,
      clientId: 'e38ea64a-2962-4cde-bfe7-dd2822fdab32',
      scope: 'openid profile email api://e38ea64a-2962-4cde-bfe7-dd2822fdab32/access_as_user offline_access',
      responseType: 'code',
      silentRenew: true,
      maxIdTokenIatOffsetAllowedInSeconds: 600,
      issValidationOff: true,
      autoUserinfo: false,
      silentRenewUrl: window.location.origin + '/silent-renew.html', 
      useRefreshToken: true 
    });

**Comment by damienbod** [comment]
@fengzhihenxs Can you compare to this:

https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects/sample-code-flow-refresh-tokens

Greetings Damien

**Comment by fengzhihenxs** [comment]
@damienbod hi, I follow the demo configuration of the official refresh token, the console will prompt the following error when logging in and will route to "unauthorized" ,I don't know why?
![image](https://user-images.githubusercontent.com/37610470/95560185-7cf22100-0a4b-11eb-8660-4f510fb84cb6.png)

My configuration is:
oidcConfigService.withConfig({  
            stsServer: 'https://login.microsoftonline.com/97793801-ffc0-4f17-b52f-117effb9e33c/v2.0',
            redirectUrl:  "https://localhost:4200",
            postLogoutRedirectUri:  "https://localhost:4200/home",
            clientId: '3cccc5c0-6604-4c81-a702-9a073bc8b43b',
            scope: 'openid profile email api://58c5f2f4-7d01-4b37-9478-07fd3c73af1b/access_as_user offline_access',
            responseType: 'code',
            silentRenew: true,
            useRefreshToken: true,
            // logLevel: LogLevel.Debug,
        });

**Comment by damienbod** [comment]
Hi @fengzhihenxs   your clock time offset to the azure server is out of sync. Allow more time to accept valid tokens or turn the check off. This is a configuration you can set.

See: https://github.com/damienbod/angular-auth-oidc-client/blob/master/docs/configuration.md

maxIdTokenIatOffsetAllowedInSeconds

and

disableIatOffsetValidation

Greetings Damien

**Comment by fengzhihenxs** [comment]
Thank you very much, it's normal

**Comment by fengzhihenxs** [comment]
@damienbod  Another error occurred. I don't know where the "userinfo" request was initiated? Is the URL incorrect?

![image](https://user-images.githubusercontent.com/37610470/95570057-f80e0400-0a58-11eb-98cd-4b294a778928.png)

**Comment by damienbod** [comment]
Hi @fengzhihenxs Azure is a bit of a problem here... Azure AD is setup to require different access tokens for each API instead of one acces token with multiple scopes. So the access token you use probably is the wrong one for graph API. This is Azure specific. You could avoid using the userinfo request by turning this off and using the id_token for the profile. 

I plan to add support for Azure multiple access tokens in a later version, just missing the time at the moment.

Greetings Damien

**Comment by fengzhihenxs** [comment]
@damienbod  Sorry, I still need to ask you. I configured to refresh the token, and refresh the token when the token expires, and I can request a new token, but there will be this prompt, why?
![image](https://user-images.githubusercontent.com/37610470/95642864-e7ec3800-0add-11eb-9e7e-dc2c4a99e418.png)

The value stored in the session has also become null
![image](https://user-images.githubusercontent.com/37610470/95642955-8bd5e380-0ade-11eb-8018-c85b2032676d.png)
