### ISSUE TITLE
unauthorized in some clients

### ISSUE THREAD

**Issue by marziyedl** [damienbod/angular-auth-oidc-client#863]
hello 
I use version 11 with angular 10. 
sometimes in some clients authorize not working, 
for example between 6  clients ,2 clients not authorize after click on login button and token not set in localStorage and then return 401 error.
we checked api, authorize is valid and api is correct.

  ngOnInit() {
    this.isAuthenticated$ = this.oidcSecurityService.isAuthenticated$;
    this.setLang();
    this.isAuthorizedSubscription = this.oidcSecurityService
      .checkAuth()
      .subscribe((isAuthorized: boolean) => {
        this.isAuthorized = isAuthorized; // ----> this return false in some clients 
        if (isAuthorized) this.router.navigate(["/dashboard"]);
      });
  }

**Comment by Expelz** [comment]
Hello @marziyedl,
To understand your issue please share consol log from these clients. Log level should be `Debug` when you pass configuration for the library (`OidcConfigService.withConfig()`).
