### ISSUE TITLE
isauthorizedrace_timeout_in_seconds Equivalent in Version 11

### ISSUE THREAD

**Issue by chipallen2** [damienbod/angular-auth-oidc-client#865]
Before version 11 we had to use the `isauthorizedrace_timeout_in_seconds` setting in our project to fix some issues for some users.

Is there an equivalent setting we need to use in version 11?

**Comment by damienbod** [comment]
@chipallen2 Do you still need this?

Greetings Damien

**Comment by chipallen2** [comment]
I still haven't figured out what happened to it in V11 or if we still need to know it. Maybe the new code just doesn't have a race? I don't know. Yeah - any insight would be helpful.

**Comment by damienbod** [comment]
@chipallen2 yes we fixed this with the major version 11. WE removed the race issues, was quite a huge update. 

Greetings Damien
