### ISSUE TITLE
getIsAuthorized().subscribe() is taking 5 seconds

### ISSUE THREAD

**Issue by Chiru1610** [damienbod/angular-auth-oidc-client#867]
Hi All, 

First of all, thank you for developing this library. We are using **angular CLI : 8.3.0** with **angular-auth-oidc-client: 10.0.15.**

We observed that in the below code **getIsAuthorized() subscribe is taking around  5 seconds always**. 

_console.log(new Date().toUTCString(), 'Sample app - app.component.ts - ngOnInit() -Before getIsAuthorized');
        this.oidcSecurityService.getIsAuthorized().subscribe(auth => {
            console.log(new Date().toUTCString(), 'Sample app - app.component.ts - ngOnInit() -Before getIsAuthorized', auth);
            this.isAuthenticated = auth;
        });_

Please find the below-attached image as well
![OIDC_getIsAuthorized](https://user-images.githubusercontent.com/51954332/94834536-1c049080-042e-11eb-981f-2462531a8658.png)

**Appreciate your suggestions on how to improve the performance as this is always taking 5 seconds.**

**Comment by damienbod** [comment]
please update to version 11

Greetings Damien
