### ISSUE TITLE
Can't run app with es5

### ISSUE THREAD

**Issue by m3ta113** [damienbod/angular-auth-oidc-client#870]
Hi,

I need to support old browser like Firefox 52 ESR. To do that, i changed my "target" property to "**es5**" in my **tsconfig.json**. 
I can't run my app because i have an error on the login method, it seems that it is not compatible ?

![image](https://user-images.githubusercontent.com/5045238/95446738-00831380-0961-11eb-9e5e-695d0081cfbc.png)

**Comment by damienbod** [comment]
This is an angular issue which can be solved using polyfills 

Sorry for not supporting this better

Greetings Damien
