### ISSUE TITLE
Change token expiration time

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#871]
Hello, I am using azure ad for external login. The angular auth oidc client version is 11.1.3. The default token expiration time of azure ad is one hour. How to change the token expiration time?

**Comment by damienbod** [comment]
@fengzhihenxs This can only be done in Azure AD and as far as I know Azure AD does not allow this, might be incorrect with here.

Greetings Damien

**Comment by fengzhihenxs** [comment]
Thank you, I am looking at the official documentation of Azure AD
