### ISSUE TITLE
return url encoded problem

### ISSUE THREAD

**Issue by crkjl** [damienbod/angular-auth-oidc-client#875]
Hi,

I've a weird problem with angular client and IdentityServer4.
When calling oidcSecurityService.authorize(), the redirectUrl is sent encoded, and IS4 responds with a "malformed redirect_uri" error.

Request:
https://epmid.xxxxxxx.com/connect/authorize?client_id=e3m&redirect_uri=https%253A%252F%252Fe3m.xxxxxxx.com&response_type=code&scope=openid%2520profile%2520roles%2520offline_access%2520E3MApi&nonce=cff811f389293bc3bd905bfdc6c8614a02za6ShIX&state=a72e68d561a3777c10db97fc7898f754acYqmZJK1&code_challenge=qaXRF4swipqQn5ED7uJKAK_I0ErTOkx0Na7hvLaeFRY&code_challenge_method=S256

**Expected behavior**
Send redirectUrl without encoded "https://e3m.xxxxxxxx.com"

Thanks for your help.
Jose

**Comment by valdian** [comment]
Hi, I noticed your issue and try to check what could be wrong.

The request should contain encoded redirectUri. The problem of your request is, that it contains redirectUri encoded twice. I.e. it should contain https%3A%2F%2Fe3m.xxxxxxx.com but it contains https%253A%252F%252Fe3m.xxxxxxx.com.

How does the redirectUri look in your config? Is it possible that the config contains already encoded redirectUri?

**Comment by crkjl** [comment]
Hi Valdian,

Sorry, it has been a copy/paste error. Really, the request is:

https://epmid.xxxxxxx.com/connect/authorize?client_id=e3m&redirect_uri=https%3A%2F%2Fe3m.xxxxxxx.com&response_type=code&scope=openid%20profile%20roles%20offline_access%20E3MApi&nonce=cff811f389293bc3bd905bfdc6c8614a02za6ShIX&state=a72e68d561a3777c10db97fc7898f754acYqmZJK1&code_challenge=qaXRF4swipqQn5ED7uJKAK_I0ErTOkx0Na7hvLaeFRY&code_challenge_method=S256

And the log in IdentityServer:

Oct 21 19:08:42 ubuntu epmid[30450]: [19:08:42 Error] IdentityServer4.Validation.AuthorizeRequestValidator
Oct 21 19:08:42 ubuntu epmid[30450]: malformed redirect_uri: https%3A%2F%2Fe3m.epmtic.com%2Fsignin-callback
