### ISSUE TITLE
how can i change the userinfo endpoint？

### ISSUE THREAD

**Issue by iQiaoQ** [damienbod/angular-auth-oidc-client#878]
**Describe the bug**
I get the config user endpoint is : https://graph.microsoft.com/oidc/userinfo, and i can't get the user's profile (eg. mobilePhone),   but the microsoft document support is: https://graph.microsoft.com/v1.0/me. So how can I change the userinfo endpoint? Thanks.

**Comment by damienbod** [comment]
Hi @iQiaoQ The OIDC User info endpoint is the endpoint provided by the Azure AD you are using and cannot be changed on the client. If you want to use a different user info endpoint, you need to call this yourself. Azure AD says they fully support OIDC so this should work without changes.

Greetings Damien

**Comment by iQiaoQ** [comment]
> Hi @iQiaoQ The OIDC User info endpoint is the endpoint provided by the Azure AD you are using and cannot be changed on the client. If you want to use a different user info endpoint, you need to call this yourself. Azure AD says they fully support OIDC so this should work without changes.
> 
> Greetings Damien

OK, thanks.@Damien
