### ISSUE TITLE
Authorization flow with PKCE with Identity Server 3

### ISSUE THREAD

**Issue by ecampoBilbomatica** [damienbod/angular-auth-oidc-client#879]
**Describe the bug**
Identity Server 3 does allow Authorization flow with PKCE but requires a secret to be sent (regardless of validity of said token). As the plugin does not send a secret, authorization fails if set to flow with PKCE.

INFO  2020-10-26 11:34:05,458 [10] INFO  IdentityServer3.Core.Endpoints.TokenEndpointController [(null)] - Start token request
DEBUG 2020-10-26 11:34:05,459 [10] DEBUG IdentityServer3.Core.Validation.ClientSecretValidator [(null)] - Start client validation
DEBUG 2020-10-26 11:34:05,460 [10] DEBUG IdentityServer3.Core.Validation.BasicAuthenticationSecretParser [(null)] - Start parsing Basic Authentication secret
DEBUG 2020-10-26 11:34:05,460 [10] DEBUG IdentityServer3.Core.Validation.PostBodySecretParser [(null)] - Start parsing for secret in post body
DEBUG 2020-10-26 11:34:05,460 [10] DEBUG IdentityServer3.Core.Validation.PostBodySecretParser [(null)] - No secret in post body found
DEBUG 2020-10-26 11:34:05,461 [10] DEBUG IdentityServer3.Core.Validation.X509CertificateSecretParser [(null)] - Start parsing for X.509 certificate
DEBUG 2020-10-26 11:34:05,461 [10] DEBUG IdentityServer3.Core.Validation.X509CertificateSecretParser [(null)] - X.509 certificate not found.
INFO  2020-10-26 11:34:05,462 [10] INFO  IdentityServer3.Core.Validation.SecretParser [(null)] - Parser found no secret
INFO  2020-10-26 11:34:05,462 [10] INFO  IdentityServer3.Core.Validation.ClientSecretValidator [(null)] - No client secret found
INFO  2020-10-26 11:34:05,462 [10] INFO  IdentityServer3.Core.Endpoints.TokenEndpointController [(null)] - End token request
INFO  2020-10-26 11:34:05,463 [10] INFO  IdentityServer3.Core.Results.TokenErrorResult [(null)] - Returning error: invalid_client

It correctly authorizes the user but it fails when it tries to retrieve the token as it cannot find a secret in the POST request. 

Is there any way (other than updating to IdentityServer4 and setting the ClientRequiresSecret to false) to circumvent the issue?

**Comment by kincerb** [comment]
I had a similar issue recently where getting the token required an authorization header. To fix this I used a `HttpInterceptor`.

Hopefully this helps you.
```typescript
import { Injectable } from '@angular/core';
import {
  HttpEvent,
  HttpHandler,
  HttpRequest,
  HttpInterceptor
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { environment } from '../../environments/environment';

@Injectable()
export class RequestheaderInterceptor implements HttpInterceptor {
  basicAuth = btoa(`${environment.clientId}:${environment.clientSecret}`);

  constructor(public oidcSecurityService: OidcSecurityService) {}

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (request.url.endsWith('v2/token')) {
      let newHeaders = request.headers;
      newHeaders = newHeaders.append('Authorization', `Basic ${this.basicAuth}`);
      console.log(`Caught request to ${request.url}`);
      const newRequest = request.clone({headers: newHeaders});
      return next.handle(newRequest);
    }
    return next.handle(request);
  }
}
```

**Comment by damienbod** [comment]
This is a server issue, don't know how ID3 supports PKCE, but I don't think it does.

Greetings Damien
