### ISSUE TITLE
The access token does not contain the correct resource/scope

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#882]
Hello, I have a requirement to use an access token to call Microsoft Graph to obtain user information. I am prompted when requesting https://graph.microsoft.com/v1.0/me
"Access token validation failure. Invalid audience.". When I decode the access token, I find that the scp attribute is inconsistent with the configured scope. Is it because the resource or scope of the token is incorrect?
![image](https://user-images.githubusercontent.com/37610470/97302179-ac01f280-1893-11eb-821d-ffb6d76e1afa.png)

![image](https://user-images.githubusercontent.com/37610470/97304797-31d36d00-1897-11eb-9ff4-8e778005f79a.png)

**Comment by damienbod** [comment]
This should help

greetings Damien
