### ISSUE TITLE
Get the phone number of the logged-in user

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#889]
Hello, userData$ provides information about the user after logging in. Is it possible to add phone number attributes or other methods to get the phone number?

**Comment by psavva** [comment]
The "Claims" originate from the authrization server (keycloak, IdentityServer, etc).
It's the job of the identity provider to give the claims, such as phone number.

**Comment by damienbod** [comment]
@psavva thanks for answering!
