### ISSUE TITLE
Forbidden route is set to / but it tries to route to /unauthorized

### ISSUE THREAD

**Issue by lwensveen** [damienbod/angular-auth-oidc-client#890]
As the title says.

**Comment by lwensveen** [comment]
So I can see it's a successful login in auth0, yet this lib tries to route to /unauthorized which I guess is the forbidden route, but since the login was successful it makes no sense..

**Comment by lwensveen** [comment]
Is there anything I can provide to help this investigation?

**Comment by damienbod** [comment]
Hi @lwensveen maybe you could check the console messages in the F12 of the browser? Usually a warning is logged why the client side validation failed after the successful auth from the server is returned.

Hope this helps, greetings Damien

**Comment by lwensveen** [comment]
Literally the only thing I get is

`ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'unauthorized'
Error: Cannot match any routes. URL Segment: 'unauthorized'`

And like I've said, I don't even have this route in my config as a forbiddenRoute. Also in the backend I can see my oauth login was succesful.

**Comment by damienbod** [comment]
Hi @lwensveen we have added these as the default routes. You can set them in your configuration to one of your routes. The route gets called when something in invalid in the response.

**Comment by lwensveen** [comment]
@damienbod But shouldn't setting forbiddenRoute to '/' route you to '/' and not to '/unauthorized'? I cannot override this behaviour.

**Comment by damienbod** [comment]
maybe but the routes are set to these. Set the routes in the app.module for the config of this lib to '/' if this is what you requireand it will go to your error route as you defined when the validation fails.

Greetings Damien

**Comment by lwensveen** [comment]
Maybe this helps:

![authtest](https://user-images.githubusercontent.com/4800388/99645963-303d3500-2a50-11eb-8527-f043e10bf00b.png)
