### ISSUE TITLE
getToken & getIdToken empty immediately after authorization

### ISSUE THREAD

**Issue by irek14** [damienbod/angular-auth-oidc-client#892]
**Describe the bug**
When I login and read the token value inside auth interceptor it's empty. I have to reload the page and after that everything is fine.

**Configuration**
I'm using 11.2.0 version. I see that the same problem was reported here: [link](https://github.com/damienbod/angular-auth-oidc-client/issues/771)

This is my config
`    oidcConfigService.withConfig({
      stsServer: StsServer,
      authWellknownEndpoint: authWellknownEndpoint,
      redirectUrl: window.location.origin,
      clientId: environment.clientId,
      scope: 'openid profile',
      responseType: 'code',
      silentRenew: true,
      maxIdTokenIatOffsetAllowedInSeconds: 600,
      issValidationOff: false,
      autoUserinfo: false,
      silentRenewUrl: window.location.origin + '/silent-renew.html',
      logLevel: LogLevel.None,
      storage: localStorage,
    });`

**Desktop:**
 - OS: [Windows 10]
 - Browser [Firefox, Chrome]

**Comment by Expelz** [comment]
Hello @irek14 
Please describe in more details your initialization process: 
- What firstly do you do in your AppComponent (during component initialization)?
- Do you use `checkAuth` or 'checkAuthIncludingServer'?
- How do you notify your App that OIDC has been initialized and user already has been authenticated?

It would be great if you could share some code where is included these steps.

**Comment by irek14** [comment]
Hi, this is my AppComponent ngOnInit function code:
```
ngOnInit() {
    this.authService.checkAuth().subscribe((isAuthenticated) => {
      if (!isAuthenticated) this.authService.signIn();
    });
  }
```
As you can see I use checkAuth(), which inside authService code is here
```
checkAuth() {
    return this.oidcSecurityService.checkAuth();
  }
``` 
If user isn't authenticated he's redirected to AzureAD login page and after succesful login there, he's redirected back to app and isAuthenticated is set to true. 

At the page, where he is redirected, I want to send request to API with autorization header, but my token is empty.
```
intercept(request: HttpRequest<any>, next: HttpHandler) {
    if (!this.secureRoutes.find((x) => request.url.startsWith(x))) {
      return next.handle(request);
    }

    const token = this.authService.token;

    if (!token) {
      return next.handle(request);
    }

    request = request.clone({
      headers: request.headers.set('Authorization', 'Bearer ' + token),
    });

    return next.handle(request);
  }
```

Here is code, which get a token from authService
```
get token() {
    return this.oidcSecurityService.getToken();
  }
```

And if I refresh a page, token have a valid value.

**Comment by Expelz** [comment]
Need some more details about this step: 
> after succesful login there, he's redirected back to app and isAuthenticated is set to true.

Questions:
1. How do you handle this redirect?
2. How do you set `isAuthenticated` to true?
3. Do you check `OidcSecurityService.isAuthenticated$` before sending request to API.

It would be ideal to see the code where is handled this redirect.

**Comment by irek14** [comment]
Ok, third question was just in point. In my app.component.ts I checked if user is authenticated and in fact he was, but before I know that I sent some calls to API with empty token. My bad, everything connected with package works good.
