### ISSUE TITLE
Allow accessing well-known configuration from outside

### ISSUE THREAD

**Issue by Budno** [damienbod/angular-auth-oidc-client#894]
**Is your feature request related to a problem? Please describe.**
I need to read the well-known configuration. In previous versions of the library, I could access this information through oidcConfigService.wellKnownEndpoints. Now the well-known configuration seems not accessible any more from outside the module.

**Describe the solution you'd like**
Add a publicly accessible method to get the current AuthWellKnownEndpoints.

**Describe alternatives you've considered**
It is possible to manually query the well-known endpoint, explicitly convert the result to an object of type AuthWellKnownEndpoints and pass it to oidcConfigService.withConfig(). However, this takes away the advantage of letting the library do it and requires manually adapting the conversion routine if the interface AuthWellKnownEndpoints should be extended in the future.

**Comment by FabianGosebrink** [comment]
Hey @Budno ,

there is a `configuration` property exactly for this usecase.

https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/oidc.security.service.ts#L20-L25

Provides you a configuration which holds 

```
export interface PublicConfiguration {
  configuration: OpenIdConfiguration;
  wellknown: AuthWellKnownEndpoints;
}
```

this should be it.

**Comment by Budno** [comment]
Hey Fabian,

That's good news. Thanks a lot!
