### ISSUE TITLE
Mistake in public api documentation of isAuthenticated

### ISSUE THREAD

**Issue by PhilippSonntagORGADATA** [damienbod/angular-auth-oidc-client#897]
**Describe the bug**
Hello there,
in the public api documentation is a small mistake. It states, that the oidcSecurityServer.isAuthenticated$ [is a boolean](https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/public-api.md#isauthenticated), which [is not the case](https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/oidc.security.service.ts#L36). I didn't try to implement it that way, although it could get confusing.

**Comment by damienbod** [comment]
Hi @PhilippSonntagORGADATA  Would you like to create a PR to fix this? 

Greetings Damien
