### ISSUE TITLE
Session State is lost on Refresh Token

### ISSUE THREAD

**Issue by jamesikanos** [damienbod/angular-auth-oidc-client#899]
**Describe the bug**
When a code pair (AT and RT) is acquired via PKCE Code Flow, a Session State value is set. This is used for the Check Session iFrame.

When a "Refresh Token" flow is performed, the session is lost.

The "Check Session" flow now fails.

**To Reproduce**
1. Acquire an AT/RT key pair
2. Observe that "Check Session" is working as expected
3. Refresh the token
4. Observe that "Check Session" reports error "OidcSecurityCheckSession pollServerSession session_state is blank"

**Expected behavior**
Given that the Refresh Token has come from a Session originally, I would expect the Session State to function, regardless of if the Access Token was acquired from Code flow or Refresh Token flow.

Perhaps an option could exist "retainSessionOverRefresh = true" to persist the session state when acquiring a new token.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86

**Comment by ussamoo** [comment]
Same issue here!

**Comment by psavva** [comment]
+1

**Comment by damienbod** [comment]
Thanks  @valdian for the fix. will be released in the next version
