### ISSUE TITLE
Add loading$ or isLoading$ property

### ISSUE THREAD

**Issue by cedbesafilm** [damienbod/angular-auth-oidc-client#901]
**Is your feature request related to a problem? Please describe.**
Even if for a short time when loading the start page the user data is not available in `this.oidcSecurityService.userData$`
It would be handy to add a loading indicator for example

**Describe the solution you'd like**
It would be convenient to have one or more boolean observables that indicate whether the service is 'working' or not

**Describe alternatives you've considered**
As long as the observable is not resolved` this.oidcSecurityService.userData$ `returns `null`, so you can use this value as a reference

**Comment by FabianGosebrink** [comment]
Hey, we have different events which are fired. Although a `loading` event is not given currently, you can set a loading for yourself and then wait for the `EventTypes.ConfigLoaded` Event. That is thrown if everything is ready iirc. 

https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/features.md#public-events
