### ISSUE TITLE
Force a token refresh

### ISSUE THREAD

**Issue by CobusKruger** [damienbod/angular-auth-oidc-client#903]
My JWT token (with IDS4) contains some information that may change at run time. Short of forcing the user to sign out and back in again, is there a way to force a token refresh that reaches the server?

I figured `checkAuth()` may do it, but it doesn't. Then I tried `checkAuthIncludingServer()`, because it should, well, include the server. It only does so if the user is unauthenticated. And if the user is unauthenticated (because I fudged the value in devtools), it _still_ doesn't hit the `connect/token` endpoint.

Is there a way to accomplish what I'm looking for?

**Edit**
I should add that I am using PKCE with silent renew.

**Comment by valdian** [comment]
@CobusKruger Check `forceRefreshSession()`:
https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/public-api.md#forcerefreshsession-observable

Is this what you are looking for?

**Comment by CobusKruger** [comment]
@valdian thank you, that's exactly what I was looking for. Unfortunately, even though it goes back to the server, it doesn't actually refresh the user data. I figured I could get past that by calling the `userinfo` endpoint and passing the result to `UserService.setUserDataToStore`, but it seems to be impossible to import `UserService`. Do you know of a way to force the user info to be updated?

**Comment by valdian** [comment]
@CobusKruger Add `renewUserInfoAfterTokenRenew: true` to your configuration.

**Comment by CobusKruger** [comment]
@valdian You are the man. This worked perfectly for me.
