### ISSUE TITLE
Code Flow PKCE with Refresh tokens and Auto Login

### ISSUE THREAD

**Issue by cedbesafilm** [damienbod/angular-auth-oidc-client#907]
**Is your feature request related to a problem? Please describe.**
With refresh token i don't found a solution for auto login in a new tab.
Call authorize() is not a good choice because i want the user click login only if is not authenticated.

checkAuthIncludingServer(): Observable is callable only with iframe silent renew as said in the API

Are there any other alternatives besides the silent-renew.html file?

**Comment by damienbod** [comment]
fixed in https://github.com/damienbod/angular-auth-oidc-client/pull/987

release 11.6.1
