### ISSUE TITLE
angular-auth-oidc-client@11.2.3 requires a peer of tslib@^1.10.0

### ISSUE THREAD

**Issue by aangelcc** [damienbod/angular-auth-oidc-client#908]
**Describe the bug**
When installing angular-auth-oidc-client@11.2.3 in a fresh Angular Project (`ng new test` with Angular CLI@11.0.2) I receive the following warning:
```
angular-auth-oidc-client@11.2.3 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
```
This happens as a default angular project depends on `"tslib": "^2.0.0"`.

Anyway when checking the `package.json` for this project in this repo, `tslib` is not listed as a peer dependency, but it is in the `package.json` downloaded from npm (@11.2.3).

**To Reproduce**
1. Create new angular app using at least Angular CLI @ 11.0.2. `ng new test-project`
2. When finish, `cd` into the folder and run `npm i angular-auth-oidc-client`.
3. Check you get the following warning: `npm WARN angular-auth-oidc-client@11.2.3 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.` 

**Expected behavior**
After installing latest angular-auth-oidc-client on a fres Angular Project generated by Angular CLI 11.0.2 this warning will be thrown: `npm WARN angular-auth-oidc-client@11.2.3 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.`

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome but not really relevant
 - Version: 86.0.4240.198

**Comment by damienbod** [comment]
same as this issue:

https://github.com/damienbod/angular-auth-oidc-client/issues/814

We have a problem here targeting the Angualr versions.

**Comment by aangelcc** [comment]
Hi Damien,

I used the search but couldn't find such issue, great to know it's already reported :P

Thank you for the quick answer! Great work 💪 

Greetings,

Antonio

**Comment by damienbod** [comment]
Still need to fix it :)

**Comment by damienbod** [comment]
fixed, with be released in the next version. Just want to get the opened PR finished first.

Thanks for reporting

Greetings Damien

**Comment by aangelcc** [comment]
Thank you so much Damien!! :)
