### ISSUE TITLE
Missing RefreshToken causes erroneous token request

### ISSUE THREAD

**Issue by KluSe** [damienbod/angular-auth-oidc-client#909]
**Describe the bug**
In some cases, the client might not get a RefreshToken when requesting one, e.g. because the OP does not provide one or the user did not consent to the "offline_access" claim. In this case the client will still attempt a refresh with the string value "undefined" as RefreshToken, likely because in [auth-state.service.ts#L77](https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/authState/auth-state.service.ts#L77) `decodeURIComponent()` is called on the Token without a check if the token actually exists. If the token is undefined, the method will return the string "undefined".

**To Reproduce**
- Configure the client with `useRefreshToken: true` and `silentRenew: true`
- Ensure the server does not actually return a RefreshToken
- Wait for the AccessToken to expire
- The client will attempt a token request with grant_type=refresh_token and code=undefined.

**Expected behavior**
If no RefreshToken is present, no attempt to refresh should be made.

**Comment by damienbod** [comment]
fixed will be released in 11.4.3 @KluSe  Thanks for reporting. @juanp3053 thanks for fixing.
