### ISSUE TITLE
Dynamic Custom Params lost on silent-renew

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#912]
**Describe the bug**

It seems that the way custom parameters are done have been refactored in the current version of the library. The way dynamic custom parameters are done is to pass them as an argument to the login function... while this works correct for the initial call ... it seems like the same custom params are not passed to the silent-renew call. 

**Expected behavior**
The custom params passed to the login function should also be passed in the silent renew call.

**Comment by damienbod** [comment]
fixed
