### ISSUE TITLE
Question - Redirecting to STS server from angular app

### ISSUE THREAD

**Issue by bsheriff** [damienbod/angular-auth-oidc-client#914]
Hi, this is a question and not necessarily an issue.  I have an angular application currently using this library.  I am using the pkce code flow with refeesh tokens.  I want the user to be able to change they're password.  I have a route on my STS server "account/changepassword".  So my question is what is the best and safest approach to redirect the user to this route.  Is there a mechanism in this oauth library which does this or is it as simple as calling window.location.href and navigating to the STS route mentioned above?

Thank you

**Comment by damienbod** [comment]
Hi @bsheriff, no. This is simple calling the  window.location.href. The STS is responsible for protecting it's UI. 

Greetings Damien

**Comment by bsheriff** [comment]
Ok thank you for the quick response
