### ISSUE TITLE
Multi Tenant Support

### ISSUE THREAD

**Issue by hamid-riahi** [damienbod/angular-auth-oidc-client#92]
thanks for your great library and all your work you put into it!

I'm wondering does this library support multi tenancy? in javascript version of oidc client, there is a setting name "acr_values" which you can pass tenant information to Identity Server however, I cannot find it in this library configuration.

Do you have any plan to support this?

**Comment by rmcc13** [comment]
I think this is now supported using the [`setCustomParameters` method](https://github.com/damienbod/angular-auth-oidc-client/blob/40790b8909f5218536c6f4f92d7f8329ac5b225d/src/services/oidc.security.service.ts#L150-L152). If you look at the [`createAuthorizeUrl` method](https://github.com/damienbod/angular-auth-oidc-client/blob/40790b8909f5218536c6f4f92d7f8329ac5b225d/src/services/oidc.security.service.ts#L441-L460), it will add parameters added by `setCustomParameters` to the authorize URL's query string.

**Comment by hamid-riahi** [comment]
Oh, Great. Sorry I missed it.
