### ISSUE TITLE
How to handle errors from SSO server?

### ISSUE THREAD

**Issue by VladislavOshkanov** [damienbod/angular-auth-oidc-client#921]
Hi! 
I need to handle errors from SSO server in my app, for example, if I got 404 on SSO url.
How can I handle this error in my app in order to prevent app from crash and show error message to user?
Thanks
![image](https://user-images.githubusercontent.com/15010388/102768187-56d5ef00-43b3-11eb-811c-1825b9c75590.png)

**Comment by FabianGosebrink** [comment]
So my first try would be first: Wrapping the promise in the APP_INITILIZER and catch the errors, then redirect the user or show an alert or something, or in the `main.ts` catch the bootstrap fail of the app and do something there. Hope this helps.

**Comment by mgamal-dev** [comment]
App crash when sso is down why?

**Comment by FabianGosebrink** [comment]
@mgamal-dev have you read my previous answer?

**Comment by mgamal-dev** [comment]
Yeah, but I have some component will be public and not secured it is also crashed 
When I add catch block it doesn't mean the app will show this page correctly

**Comment by FabianGosebrink** [comment]
You can catch the error in a promise with a reject/resolve. You have to wrap it again. Did not try it out but I think this should work.
