### ISSUE TITLE
How to add steam api key to disable cors blocking

### ISSUE THREAD

**Issue by LapitskiyKirill** [damienbod/angular-auth-oidc-client#922]
I am trying to authenticate on my web-site with steam, but i have "Access to XMLHttpRequest at 'https://steamcommunity.com/openid/.well-known/openid-configuration' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." problem. I found that someone tells that it can be because i have not my project deployed. 

May be i can add steam api key (https://steamcommunity.com/dev/registerkey) for something like "localhost" for config?(i am using your example https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/features.md/#custom-parameters).

Or may be you know some examples of working with steamID via angular?

**Comment by damienbod** [comment]
Hi @LapitskiyKirill  the CORS issue is a server issue. I don't know anything about the stream authentication server. If it is OIDC conform, this lib will work with it

Greetings Damien
