### ISSUE TITLE
Missing if  getHeaderFromToken returns an empty object 

### ISSUE THREAD

**Issue by wojtek-fliposports** [damienbod/angular-auth-oidc-client#93]
Lines:

https://github.com/damienbod/angular-auth-oidc-client/blob/e0853e0ea40a332cb774227502bdf74b1259df58/src/services/oidc.security.validation.ts#L225-L233

If `getHeaderFromToken` return an empty object, then `if ('RS256' != alg) ` is always true making log a little bit confusing

**Comment by damienbod** [comment]
hi @wojtek-fliposports I'll look into this, will fix the log then

**Comment by damienbod** [comment]
fixed in 1.3.19

https://www.npmjs.com/package/angular-auth-oidc-client
