### ISSUE TITLE
How to provide client id during logoff

### ISSUE THREAD

**Issue by myronu** [damienbod/angular-auth-oidc-client#932]
There is nothing in the documentation about calling logoff() with a url handler but it shows up as an optional parameter on the method. I am wondering how I could use that to provide additional parameters to the URL, specifically client_id. With our server I am receiving an error calling logout, "Invalid value for 'client_id' parameter."

**Comment by FabianGosebrink** [comment]
Related to #966

**Comment by FabianGosebrink** [comment]
We can use an existing interface as param also on the logoff methods. Would be a breaking change.

**Comment by damienbod** [comment]
Hi @myronu The client_id is not an param used for the endsession endpoint. Why do you need this? Why IdentityProvider do you use?

Can you send me the specs of the endsession endpoint you use?

Greetings Damien

**Comment by myronu** [comment]
This is one of our company's main TID servers and is designed as a multi-tenant solution. I know it is based on Okta but I'm not sure if that parameter comes from Okta or something they added to facilitate redirecting to the correct server.

**Comment by myronu** [comment]
There is another possibility that either logout is not being called properly, or the ID server is not handling it properly. Looking closer I see two calls being made, the first call looks like it includes the token but fails for some reason. The second call does not include the token and gives the error that client_id is not provided.

![image](https://user-images.githubusercontent.com/19538662/110488421-afac4e00-80ab-11eb-9a75-43b460d1dec2.png)

**Comment by FabianGosebrink** [comment]
Implemented, will be in Release 12.
