### ISSUE TITLE
Login fails in Microsoft IE/Edge browser for Azure AD (Microsoft Identity Provider) using OIDC PKCE flow

### ISSUE THREAD

**Issue by vicky-singh** [damienbod/angular-auth-oidc-client#936]
**Describe the bug**
Login fails in Microsoft IE/Edge browser for Azure AD (Microsoft Identity Provider)

**To Reproduce**
1. Configure the app to work with Edge/IE browser using polyfill/browserlist/tsconfig.js for Microsoft Identity Provider (OIDC PKCE Flow)
2. Try to login in the app

**Expected behavior**
App should login and generate the tokens calling /token endpoint

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge/IE
 - angular-auth-oidc-client - 11.2.4

**Additional context**
This works fine in Chrome browser, issue is only in IE/Edge browser. After analyzing this issue for some time, it seems to be related to the underlying storage the plugin uses and the way local/session storage is handled by Edge/IE.

I can see below error in console - 

**ValidateStateFromHashCallback failed, state: a0c7e8a9ac903f4445b09e84385c93e46fpDfEg0p local_state:null**

This is fixed in msal.js by providing a config property - **storeAuthStateInCookie**

_When the storeAuthStateInCookie flag is enabled, MSAL.js will use the browser cookies to store the request state required for validation of the auth flows._

For more details please see - https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-known-issues-ie-edge-browsers

@damienbod Can you please help here... I am stuck at this and need my app to support Edge browser. Let me know if this can be fixed by using CustomStorage and if there is in any sample.

Thanks for your help in advance.

**Comment by damienbod** [comment]
Testing this using version 11.4.0 and it works.

Can you compare your Angualr app to this example?

https://github.com/damienbod/AzureADAuthRazorUiServiceApiCertificate/tree/main/AngularAzureADMultipleApis

Greetings Damien

**Comment by vicky-singh** [comment]
Thanks @damienbod for such a quick response. Same error with this as well - https://github.com/damienbod/AzureADAuthRazorUiServiceApiCertificate/tree/main/AngularAzureADMultipleApis

I just updated the config in app.module.ts as below -
```
    oidcConfigService.withConfig({
            stsServer: 'https://login.microsoftonline.com/<tenant_id>/v2.0',
            authWellknownEndpoint: 'https://login.microsoftonline.com/<tenant_id>/v2.0',
            redirectUrl: window.location.origin + '/home',
            clientId: <client_id>,
            scope: 'openid offline_access',
            responseType: 'code',
            silentRenew: true,
            useRefreshToken: true,
            maxIdTokenIatOffsetAllowedInSeconds: 600,
            issValidationOff: false,
            autoUserinfo: false,
            logLevel: LogLevel.Debug
    });
```
![image](https://user-images.githubusercontent.com/18160188/104110991-4b674b00-5303-11eb-8df5-f434a3e4e355.png)

Edge Version -

![image](https://user-images.githubusercontent.com/18160188/104111008-7487db80-5303-11eb-86b1-5c96801d5147.png)

**Comment by vicky-singh** [comment]
@damienbod What is Edge browser version you are using ?

**Comment by damienbod** [comment]
Hi @vicky-singh 

Microsoft Edge 
Version 87.0.664.75 (Official build) (64-bit)

What does the F12 logs say?

Greeetings Damien

**Comment by eastjie** [comment]
I have also Edge Version 87.0.664.75 (Official build) (64-bit) and it works with AzureAd using PCKE flow. I think, it is not browser problem  and seems to be the scope problem. 

I have following scope: "openid profile offline_access email api://xxxxxxxxxxxxxxxxxxxxxxx949b-aac63456daef/apipkcetestscope" and it works.

**Comment by FabianGosebrink** [comment]
Is the problem solved then when adding the correct scopes?

**Comment by vicky-singh** [comment]
I was able to resolve this issue when I changed from default storage (session storage) to localStorage. 

**storage: localStorage**


But now I am facing another issue. In config I have configured scopes as "openid profile" but the generated access token has scope as "email openid profile User.Read" with aud as "00000003-0000-0000-c000-000000000000". This is an access token for graph api. I am not able to validate this access token signature in my backend api. Is there a way to get the access token without scope "User.Read" ? or else I will have to use ID token.

Actually in my use case I don't really care about what is the scope returned. I just need to validate the user in UI with IdP and pass the access token as Authorization Bearer token to backend and then validate in backend if the token is valid. If valid, get the user id from access token (as part of the claim) and pass the user id to other internal module to get the authorization details.

But since the access token returned is of graph api, signature validation fails. As per Microsoft documentation - **tokens for Microsoft Graph won't validate according to these rules due to their proprietary format**.

Also since both UI and backend are part of the same module but deployed separately, I don't want to register it separately in IdP and expose as an API.

If there is no way to use access token for my scenario and then I think I will have to use id token.

Please let me me know your thoughts or suggestions.

**Comment by damienbod** [comment]
Hi @vicky-singh 

You have a few issues

If you use a bearer token API, then you require an access token for this. To do this, you must expose an API in azure app registrations and add this to your scope “api/XXXXXX/access_as_user”. This can then be validated in your API. Remove the User.Read scope from the authorize request. I would not expose the graph API access to the public SPA. You should care about the scope, because this defines the API access which you make available publicly to the SPA. Expose as little as possible as public APIs.

I would not recommend using multiple access tokens in the SPA as this increases the attack surface. 

You should be able to use session storage, this is a different issue with your implementation which I don’t understand.

Do not expose any other APIs in your UI, use the further APIs from the secure backend.

If you would prefer not to configure APIs like this for you Angular API, you could switch the backend authentication and then use a cookie for the Angular API access (with CRSF protection). This would be more secure again with the correct same site, CORS protection.

Greetings Damien
