### ISSUE TITLE
Check session changed event not stopping after logout

### ISSUE THREAD

**Issue by WolfspiritM** [damienbod/angular-auth-oidc-client#938]
**Describe the bug**
I'm having a strange behaviour when it comes to the check session.
Currently I'm listening for the check session event to call forceRefreshSession to make sure I have the up to date session everytime I receive a check session event. This works as expected, but if the user logs out in another browser window, then I keep receiving "changed: true" events every few seconds causing me to constantly trying to refresh the session.

I'm not sure if that is actually a good thing cause it will result in the user being logged in again if he logs in in another tab, but it's a very inconsistent behaviour as this doesn't happen if the user wasn't logged in in the first place.

The reason is that sessionState is null and therefor
https://github.com/damienbod/angular-auth-oidc-client/blob/a1ea5a7a54524068367d92cfa8411de160279922/projects/angular-auth-oidc-client/src/lib/iframe/check-session.service.ts#L106-L114
keeps emitting changed as true everytime it checks if the session changed

**To Reproduce**
1. Subscribe to checkSessionChanged
2. Log in in two different tabs
3. Log out in one of the tabs
4. Notice checkSessionChanged being fired every few seconds

**Expected behavior**
I think checksession doesn't allow empty session_state (I wonder why, cause it might be very helpful to know when the user logged in (Security?)) so I think the correct way is either:
1. Emit changed event only once if session state ended up being null
2. Emit changed event constantly (as it already does) but also do that as long as the user isn't logged in in the first place to make it consistent

I think I'd prefer option 1 as I think it's up to the application to retry a session update.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Edge Chromium
 - Version [e.g. 22] 87.0.664.66

**Comment by damienbod** [comment]
Hi @WolfspiritM When you receive the changed event from the IDP, then you need to login again which usually requires interaction from the user. So when handling this event, the refeshSession will usually not work. You need to login again. I usually show a message, please login with a login button or popup or whatever you use, and sometimes I log the client out and remove the client session.

Greetings Damien
