### ISSUE TITLE
Azure B2C Implicit Flow - userData is null after token expired and renew.

### ISSUE THREAD

**Issue by carlos-abud** [damienbod/angular-auth-oidc-client#939]
Bug Description
After token has expired, authorize call is triggered oidcSecurityService.authorize() and after authorizing successfully, oidcSecurityService.userData$ returns null. I've checked the session storage for userData and keyValue is right there but for some reason it returns null. Enabling LogLevel.Debug does not reveal any errors. 

1. login to your application
2. wait for token to expire (alternatively manually delete session storage from devtools)
3. autologin / authorize call is triggered
4. oidcSecurityService.userData$ returns null. 

**Expected behavior**
userData$ observable returns logged user info/data.

*** lib version ***
"version": "11.2.0"

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.1 / Windows 10 
 - Browser Chrome, Brave, Edge (Chromium)
 - Version Version 87.0.664.75 (Official build) (64-bit)
 - Angular version:  "@angular/core": "^9.1.12",

**Smartphone (please complete the following information):**
N/A

Side questions: 
- How can I **ensure** that silent-renew is working as expected? aside from enabling LogLevel.Debug and seeing the message every 3 seconds indicating that has finished.
- Any other ways of testing this from dev side?  
```
Checking: silentRenewRunning: true id_token: true userData: true
angular-auth-oidc-client.js:180 silent renew finished!
```

**Comment by FabianGosebrink** [comment]
Hey can we see your config? Did you turn `autoUserinfo` to true?

**Comment by carlos-abud** [comment]
Hello Fabian, thanks for your reply. As it turns out `autoUserInfo` was set to false. I will give it another try having this set to true and see if that fixes the problem.

**Comment by FabianGosebrink** [comment]
Nice, let us know if that worked out for you. Thanks!

**Comment by carlos-abud** [comment]
@FabianGosebrink 
after enabling autoUserInfo to true, the following error is thrown: 
init check session: authWellKnownEndpoints.userinfo_endpoint is undefined; set auto_userinfo = false in config


this is the config file

`export function authConfig(oidcConfigService: OidcConfigService) {
  return () =>
    oidcConfigService.withConfig({
      stsServer: `https://login.microsoftonline.com/${tenantName}.onmicrosoft.com/v2.0`,
      authWellknownEndpoint: `https://${tenantName}.b2clogin.com/${tenantName}.onmicrosoft.com/${policyName}/v2.0/.well-known/openid-configuration`,
      redirectUrl: window.location.origin,
      postLogoutRedirectUri: `${window.location.origin}/logged-out`,
      clientId: clientId,
      scope: `openid ${apiScope}`,
      responseType: 'id_token token',
      silentRenew: true,
      autoUserinfo: true,
      renewTimeBeforeTokenExpiresInSeconds: 60,
      silentRenewUrl: `${window.location.origin}/silent-renew.html`,
      logLevel: LogLevel.Debug
      // useRefreshToken: true, // for refresh renew, but revocation and one time usage is missing from server impl.
      // ignoreNonceAfterRefresh: true,
      // disableRefreshIdTokenAuthTimeValidation: true,
      // unauthorizedRoute: ''
    });
}`

**Comment by carlos-abud** [comment]
here's additional debugging information from the console
```
Wanted to read '9e2c2a79-1ba4-4b37-b950-cef453ce9118_authWellKnownEndPoints' but nothing was found
angular-auth-oidc-client.js:180 Wanted to read '9e2c2a79-1ba4-4b37-b950-cef453ce9118_authWellKnownEndPoints' but nothing was found
client:52 [WDS] Live Reloading enabled.
angular-auth-oidc-client.js:180 STS server: https://login.microsoftonline.com/villasport.onmicrosoft.com/v2.0
angular-auth-oidc-client.js:180 currentUrl to check auth with:  ["http://localhost:6999/"]
angular-auth-oidc-client.js:180 Wanted to read '9e2c2a79-1ba4-4b37-b950-cef453ce9118_authzData' but nothing was found
angular-auth-oidc-client.js:180

**Comment by carlos-abud** [comment]
the key store _authWellKnownEndPoints seems to be available but for some reason is not finding it.

![Screen Shot 2021-01-18 at 11 35 48 AM](https://user-images.githubusercontent.com/77124753/104928718-bb1faa80-5981-11eb-933f-51134c613c52.png)

**Comment by damienbod** [comment]
Hi @carlos-abud Try setting the **renewUserInfoAfterTokenRenew = true;** I would need to investigate this. I see you use Azure B2C with Implicit Flow. 

Greetings Damien
