### ISSUE TITLE
angular-auth-oidc-client login redirect appends # to the end of the URL

### ISSUE THREAD

**Issue by amedida430** [damienbod/angular-auth-oidc-client#943]
The request URL does not contain # when looked in the network tab as shown below
![image](https://user-images.githubusercontent.com/77712940/105128316-c9201900-5ab0-11eb-91d4-ac4a165ef6c0.png)

But my URL in the browser contains # to the end of the URL after redirecting from auth0 
![image](https://user-images.githubusercontent.com/77712940/105128196-8e1de580-5ab0-11eb-8c21-8b63334d4e88.png)

This is causing issues later when authorizing the call back and comparing the states. Since the browser contains # to the state query param, authorizing is failing every time.

**Comment by damienbod** [comment]
Hi @amedida430 This is a server implementation problem. if the # is returned from the auth0 as part of the state then the states do not match. See if you can fix this on the server. Maybe we could add or find a workaround on the client, maybe added a custom dummy param to you auth call might helper as the auth0 server would add it's # to the end of th enext param then which is not used. A bit hacky though :)

Greetings Damien
