### ISSUE TITLE
test faillures: NullInjectorError: No provider for OidcSecurityService!

### ISSUE THREAD

**Issue by 0xdbe** [damienbod/angular-auth-oidc-client#948]
I use angular-auth-oidc-client in my prototype [(source)](https://github.com/0xdbe-example/angular-auth-oidc-client).
This works perfectly with Auth0.

But I don't know how to include `OidcSecurityService` in test files

I run tests in my project:
```
ng test
```

tests fail for all components that require `OidcSecurityService`: guard, interceptor, login component, ...

Example for my login component:
```
LoginComponent > should create
NullInjectorError: R3InjectorError(DynamicTestModule)[OidcSecurityService -> OidcSecurityService]: 
  NullInjectorError: No provider for OidcSecurityService!

error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'OidcSecurityService', 'OidcSecurityService' ] })
NullInjectorError: R3InjectorError(DynamicTestModule)[OidcSecurityService -> OidcSecurityService]: 
  NullInjectorError: No provider for OidcSecurityService!
```

What  should I do to pass test with success ?

**Comment by FabianGosebrink** [comment]
Normally you would mock third party libs away and just test your code. Did you try that?
