### ISSUE TITLE
sample using Authorizing in Popup

### ISSUE THREAD

**Issue by bsocket** [damienbod/angular-auth-oidc-client#953]
Is there a working sample I can use. The return URl after logging in creates my home page on the popup window. Ideally I should be able to destroy the window after login.
login() {

    const urlHandler = (authUrl) => {
        // handle the authorization URL
        window.open(authUrl, '_blank', 'toolbar=0,location=0,menubar=0');
    }

    this.oidcSecurityService.authorize({ urlhandler });
}

**Comment by FabianGosebrink** [comment]
Closing because in relation to #931

**Comment by damienbod** [comment]
release 11.5.0
