### ISSUE TITLE
Support silent renew with refresh tokens without scope offline_access

### ISSUE THREAD

**Issue by Mr-Smith-13** [damienbod/angular-auth-oidc-client#956]
**Is your feature request related to a problem? Please describe.**
In our web application we want to use refresh tokens to perform a silent renewal of the access token.
Because of security reasons we are not allowed to issue tokens with scope `offline_access` in our authorization server.
Our authorization server (Keycloak) issues refresh tokens even in case the scope `offline_access` is not requested.
But unfortunately we are not able to use these refresh tokens as your library prevents this combination of configuration settings.
The configuration is refused with the following error message: "When using silent renew and refresh tokens please set the `offline_access` scope".

**Describe the solution you'd like**
It would be great if your library would allow to use the combination of `useRefreshToken` and `silentRenew` without the need to specify the scope `offline_access`.
This could e.g. be achieved by writing only some warning message to the console but accepting the configuration.
Another option might be to have an additional configuration option which allows to disable the check in rule `use-offline-scope-with-silent-renew.rule.ts`.

**Additional context**
We tested with the most recent version of angular-auth-oidc-client (11.4.5).

**Comment by damienbod** [comment]
The  offline_access is required for this per spec. Why are the refresh tokens disabled? Refresh tokens in the browser has problems and the IDP should implement the extra protections which migrate against some of these.

You could use the iframe silent renew or use the offline_access scope. Seems strange that your keyclock has a workaround, did someone add this because the refresh tokens are not allowed?

Greetings Damien

**Comment by Mr-Smith-13** [comment]
Hi Damien, thank you for the fast response!

We are using iframe-based silent renew at the moment.
The problem with that approach is, that each user of our application (SPA) must activate the third-party cookies manually as our IdP (Keycloak) is hosted on a different domain. This results in a really bad UX.
Therefore we wanted to switch to silent renew via refresh tokens.

As I tried to explain above (but I guess that was not clear enough) the configuration of the used Keycloak server prevents that our SPA requests the scope `offline_access`. The rational behind that is that our security experts see a high risk in using offline tokens (https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/sessions/offline.adoc#_revocation-policy).

Nevertheless the token endpoint of the Keycloak server allows us to retrieve refresh tokens (even if we do not specify the scope `offline_access`).
These refresh tokens seem to be standard tokens (not offline tokens). Nevertheless we could use this tokens for silent renew.
A colleague of mine tested this approach with an older version of your library and told me it was working fine. But this stopped working with the changes introduced in context of https://github.com/damienbod/angular-auth-oidc-client/issues/725.

**Comment by ruifung** [comment]
@damienbod Technically speaking, the offline_access is *not* required for refresh tokens as per the spec stated in section 11

" The use of Refresh Tokens is not exclusive to the offline_access use case. The Authorization Server MAY grant Refresh Tokens in other contexts that are beyond the scope of this specification. "

In the case of keycloak, the offline_access scope will grant a non-expiring refresh token while expiring efresh tokens MAY be granted if the offline_access scope is not specified.

**Comment by damienbod** [comment]
I will add support for and remove the validation.

**Comment by Mr-Smith-13** [comment]
@ruifung Many thanks for your additional input.
@damienbod Thank you for reopening and fixing the issue. This will really help us!

**Comment by damienbod** [comment]
released 11.6.2
