### ISSUE TITLE
Client Offset Time not Considering  in Token Validation in initial load

### ISSUE THREAD

**Issue by sashissd** [damienbod/angular-auth-oidc-client#957]
Hi Team,

We are using this package as port of our application token generation and we have a token which is valid for 10 mins and uses the silent renew to refresh the token.
**Issue :** 
As part the Token Validation if the client  Time have a difference greater then 10 mins then the Token is rejecting from the package as  we are not sending the the offset time from the configuration. Is there any way can we send the offset time  for the below method from the configuration to consider the off set time when validating the token at initial load ? Or we need to tell the each client  that time is different from internet time ?

https://github.com/damienbod/angular-auth-oidc-client/blob/710af82194bc9372d8a5ffedae00d94fc6f5417c/projects/angular-auth-oidc-client/src/lib/validation/state-validation.service.ts#L154

Any Help or fix is really appreciated.

**Comment by damienbod** [comment]
Hi @sashissd the time sync check is defined in the spec like this. You could use a configuration to disable the check, or increase the allowed time. If your tokens are only valid for 10 mins, maybe you could just turn the check off.

See the configuration properties for details.

Greetings Damien

**Comment by sashissd** [comment]
Ok Thankyou.
