### ISSUE TITLE
Angular SPA + .Net api + GraphApi

### ISSUE THREAD

**Issue by medireport-jean** [damienbod/angular-auth-oidc-client#959]
**Describe the bug**
Hello, probably not a bug but a bad usage i guess, following the 2 great resources below

https://damienbod.com/2020/12/08/using-multiple-apis-in-angular-and-asp-net-core-with-azure-ad-authentication/
https://github.com/damienbod/AzureADAuthRazorUiServiceApiCertificate/tree/main/AngularAzureADMultipleApis

I try to get, following the sample, an Angular SPA, doing the login against Azure AD (success), able to talk with the .net Api (success) and to call the GraphApi through the .net Api (Fail).

**To Reproduce**
1. Setup the Spa app and the api in Azure Ad / App registrations, add role to my user
2. Login using the SPA & consent -> Ok
3. Test a direct api call (to the weather controller) -> Ok
4. Test a graph api delegated call, using GraphApiCalls -> Fail

**Expected behavior**
Spa to receive the user details from GraphApi

**Additional context**
StatusCode: 400
        ResponseBody: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'd78f806b-ae0f-4bab-bcb6-d744c46a6490' was not found in the directory '022fcc71-2e48-4e67-a3f8-91d6677a0126'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 8f4673f1-1aed-4e00-8729-cc262ddc1300\r\nCorrelation ID: 1f308a77-7a9f-4623-84e1-2e173971273a\r\nTimestamp: 2021-02-06 21:08:01Z","error_codes":[700016],"timestamp":"2021-02-06 21:08:01Z","trace_id":"8f4673f1-1aed-4e00-8729-cc262ddc1300","correlation_id":"1f308a77-7a9f-4623-84e1-2e173971273a","error_uri":"https://login.microsoftonline.com/error?code=700016"}

022fcc71-2e48-4e67-a3f8-91d6677a0126 is indeed my tenant id, d78f806b-ae0f-4bab-bcb6-d744c46a6490 is the Application ID URI (full=api://d78f806b-ae0f-4bab-bcb6-d744c46a6490/access_as_user). So indeed the api do have a different ID but if i use it in the configuration (appsettings AzureAd/ClientId), the SPA can't talk to the api (seems normal).

Exception here
![image](https://user-images.githubusercontent.com/65670581/107130036-44b00180-68ca-11eb-8a34-2b283b944788.png)

Any idea where i could have made a mistake ?

**Comment by damienbod** [comment]
Hi @medireport-jean The graph API scopes  you request are not allowed or configuration in the API permissions of the Azure App registration or the consent has not be granted, or you use B2C which does not support the OBO flow

Greetings Damien

**Comment by medireport-jean** [comment]
Thanks for the (incredibly) fast answer!

In theory in the api i only need these 2 scopes to play with this method, correct?
![image](https://user-images.githubusercontent.com/65670581/107131065-c8222080-68d3-11eb-9523-ca5ddfc49676.png)

Here is my api permissions
![image](https://user-images.githubusercontent.com/65670581/107131080-f30c7480-68d3-11eb-8919-94b77e254be8.png)

I have added more privileges (User.ReadBasic.All was indeed missing), with the same result:
![image](https://user-images.githubusercontent.com/65670581/107131054-ad4fac00-68d3-11eb-83de-914af9981e4e.png)

And below, the config of the SPA registred app (well, i guess that the graph api scopes here are useless)

![image](https://user-images.githubusercontent.com/65670581/107131171-7ded6f00-68d4-11eb-8c9c-8afc72972432.png)

> or you use B2C which does not support the OBO flow

Not sure to understand sorry, using the exact clone of the tutorial above, same code, just replaced the ids.

**Comment by medireport-jean** [comment]
When i check the user token, i notice that the scope isn't exactly what i expected:

![image](https://user-images.githubusercontent.com/65670581/107131678-f6eec580-68d8-11eb-8ec5-22d56bcd1ec0.png)

SPA config:

![image](https://user-images.githubusercontent.com/65670581/107131682-02da8780-68d9-11eb-91a3-e0cb30d4a826.png)

so, it seems enough to log to the web api but not to allow the api to talk to graphApi right ?

**Comment by guyz92** [comment]
If I recall correctly, Azure AD issue access token at per scope level.
If you need to access Microsoft Graph API, you need to request for an Access Token specifically for Microsoft Graph.
The Access Token used for your "access_as_user" cannot be used to call Microsoft Graph API.

MSAL 2.0 Library maybe applicable for your use case.

**Comment by damienbod** [comment]
hi @guyz92 yes a separate access token is required for Graph API, but this is got from the server backend and not the angular SPA. Using multiple access tokens in the browser has many problems, it would be better to do this in the backend. A single access token for the SPA which uses the dedicated API for the angular application is what I recommend. Then you can make all the other APIs private and reduce the attack surface. 

The different ways of getting the access tokens in Azure is limited and the tokens are persisted to storage in the browser.

logout has problems as does session refresh without reducing the security.

Greetings Damien

**Comment by damienbod** [comment]
@medireport-jean In your backend API do an OBO flow to get the graph data you require. Make this public through your dedicated API. Expose as little as possible in the public domain.

Greetings Damien

**Comment by medireport-jean** [comment]
Hi & thanks
Indeed, i would like to avoid dealing with multiple tokens on the frontend, complex & dirty.
@damienbod, in notice that i have added (during tests i think) the User.Read.All permission to the api, and this one seems particular:
![image](https://user-images.githubusercontent.com/65670581/107203925-598cb200-69fc-11eb-92ba-66693984a3dc.png)

I'll remove it (not needed in fact..) & see if better.

1 question: is it correct to add the permissions as "Delegated" here ?

![image](https://user-images.githubusercontent.com/65670581/107204019-7a550780-69fc-11eb-9882-03bbc28f1d21.png)

**Comment by medireport-jean** [comment]
Hi, still struggling on this since a week, i rechecked everything and fail to have it working :'(
My ABO flow seems to be correctly configured, user granted for both the spa & api, spa & api both have graph permissions, all permissions are consented by admin, spa app registration do have the api access_as_user privilege...

And i still get " AADSTS700016: Application with identifier 'd78f806b-ae0f-4bab-bcb6-d744c46a6490' was not found in the directory" when the api attempt to get a token using OBO flow. 

Allow me to past here all my setup, if you have a moment to tell me if you spot the mistake i would love it !

Config

![Screenshot 2021-02-14 160105](https://user-images.githubusercontent.com/65670581/107880765-3755d100-6ee1-11eb-8c4a-a0d488db0162.jpg)

![Screenshot 2021-02-14 160624](https://user-images.githubusercontent.com/65670581/107880758-3329b380-6ee1-11eb-83cd-57b6809b40ec.jpg)

![Screenshot 2021-02-14 160512](https://user-images.githubusercontent.com/65670581/107880759-34f37700-6ee1-11eb-96cd-7e417f81ef5a.jpg)

![Screenshot 2021-02-14 160256](https://user-images.githubusercontent.com/65670581/107880760-358c0d80-6ee1-11eb-89b6-c73a317caca4.jpg)

![Screenshot 2021-02-14 160242](https://user-images.githubusercontent.com/65670581/107880761-3624a400-6ee1-11eb-8ed1-02425dd0c47b.jpg)

![Screenshot 2021-02-14 160142](https://user-images.githubusercontent.com/65670581/107880763-36bd3a80-6ee1-11eb-9006-dbe5d3f6c3f9.jpg)

SPA

![Screenshot 2021-02-14 160022](https://user-images.githubusercontent.com/65670581/107880766-37ee6780-6ee1-11eb-921b-92b405401fc8.jpg)

API

![Screenshot 2021-02-14 155804](https://user-images.githubusercontent.com/65670581/107880772-39b82b00-6ee1-11eb-8a7a-9741899c8a1c.jpg)

![Screenshot 2021-02-14 155958](https://user-images.githubusercontent.com/65670581/107880767-3886fe00-6ee1-11eb-8df8-fd979b3a8272.jpg)

![Screenshot 2021-02-14 155905](https://user-images.githubusercontent.com/65670581/107880771-391f9480-6ee1-11eb-8677-20cdc5b03760.jpg)

![Screenshot 2021-02-14 160833](https://user-images.githubusercontent.com/65670581/107880757-31f88680-6ee1-11eb-9c53-f65cb2d07c88.jpg)

**Comment by damienbod** [comment]
This looks liek a configuration bug in the Azure App registration. The **Application (client ID)** and the **Application ID URL** should match. Try creating a new one to test.

Greetings Damien

**Comment by medireport-jean** [comment]
It would explain a lot ! Thanks I will try it

**Comment by medireport-jean** [comment]
Working! Made a new app registration, following the same steps, but indeed this time the app id & the app id uri do matches, and everything is working as expected!
What a great way to start a Monday, thanks Damien.

**Comment by damienbod** [comment]
awesome congrats, thanks for closing

Greetings Damien
