### ISSUE TITLE
local_state is always null because is not being set

### ISSUE THREAD

**Issue by wojtek-fliposports** [damienbod/angular-auth-oidc-client#96]
https://github.com/damienbod/angular-auth-oidc-client/blob/29f99cbe98d673f33cc28bf9f7c25b47b254b0d6/src/services/oidc.security.service.ts#L180-L184

First time when you run application `storage_auth_state_control` will be `null` so should be compared to `''`  or to `null`

**Comment by damienbod** [comment]
thanks, I fix this in the next version

**Comment by damienbod** [comment]
fix in 1.3.19

https://www.npmjs.com/package/angular-auth-oidc-client
