### ISSUE TITLE
Logoff from sample-code-flow-auto-login fails intermittent

### ISSUE THREAD

**Issue by hhutzler** [damienbod/angular-auth-oidc-client#964]
**Describe the bug**
Logoff from sample-code-flow-auto-login fails intermittend 

**To Reproduce**
1. Setup  sample-code-flow-auto-login
2. Run multiple logon/logoff operations
3. In my case only the first logoff worke well  -   but this is timing problem.

**Expected behavior**
Logoff should work everytime.

**Screenshots and Debug Details**
![image](https://user-images.githubusercontent.com/25606672/107493697-342fad80-6b8e-11eb-9c93-082cb9af92c4.png)
The problem occurs when the Keylclaok logout was CANCELLED - means the request is not send to the keycloak server 

**Desktop (please complete the following information):**
- Browser       : Chrome Version 88.0.4324.146 (Offizieller Build) (64-Bit)
- OS               : windows 10 64 bits
- Angular CLI : 11.1.4
- Angular     : 11.1.2
- keyloak     : 11.0.2  / Java   11.0.8
- angular-auth-oidc-client: "11.5
 

**Debug Details **
The problem occurs when the Keylclaok logout call was CANCELLED - means the request is not send to the keycloak server.
To fix the problem we removed  the **href parameter**  for the logout button to avoid the **full page reload** for the 
Angular APP ( see navigation.component.html)
- **Old :**  href (click)="logout()"  
- **New**:   (click)="logout()"

After that change the logout worked fine. Also replacing href with routerlink parameter works .
Not sure whether we should have an href attribute within Anglular Navaigation.

**Comment by FabianGosebrink** [comment]
Hey @hhutzler , you're totally correct, that makes absolutely no sense. Thanks

**Comment by hhutzler** [comment]
Not sure maybe other Logoff problem are related to this issue too as many developers will just copy the sample code.
