### ISSUE TITLE
urlHandler callback function parameter in LogoffRevocationService.logoff does nothing

### ISSUE THREAD

**Issue by Lexa-tech** [damienbod/angular-auth-oidc-client#966]
Hello, I'm trying to add state parameter when calling logoff function.

The setState method in oidcService enable to pass this state parameter when calling authorize function, but this state is not added to the request when calling logoff functions.

That's why I'm trying to use urlHandler callback function parameter in logoff function, but it seems that it does nothing.

https://github.com/damienbod/angular-auth-oidc-client/blob/23ed1725030f386a9a3ea9cddeaa02d014bcfeb8/projects/angular-auth-oidc-client/src/lib/logoffRevoke/logoff-revocation.service.ts#L27

**Describe the bug**
Impossible to add customParameter in logoff function.
- setState in OIDCService is not applied when calling logoff function
- urlHandler callback function param does nothing in logoff function

**Expected behavior**
Pass state parameter when calling logoff functions

**Desktop (please complete the following information):**
 - Browser [Chrome]

Thanks for your Help

**Comment by FabianGosebrink** [comment]
Hey @Lexa-tech , So your issue is that you want to add custom params to the logoff url, is that correct? Thanks :)

**Comment by Lexa-tech** [comment]
Exactly, I would like add state parameter when walling logoff function , the same way we can pass this state when calling the authorize function (with with oidcService.setState ). But If we can't use oidcService state, I don't mind using urlHandler callback function of logoff to add customParams.
Thanks.

**Comment by FabianGosebrink** [comment]
So something like `logoff(..., customParams?: { [key: string]: string | number | boolean }`) would be a fit for you? @damienbod what do you think?

**Comment by damienbod** [comment]
just need to check if the endsession endpoint allows custom parameters per spec.

cheers Damien

**Comment by Lexa-tech** [comment]
Couldn't you use the state that is set with the oidcService.setState method when calling logoff function ?
I don't mind using customParams, it's just a question for my comprehension of the oidc flow.

**Comment by Lexa-tech** [comment]
Hi @damienbod , did you find your answer about allowing custom parameters in the endsession endpoint ?

**Comment by FabianGosebrink** [comment]
We will implement that. Just did not find the time until now. This is a breaking change.

**Comment by FabianGosebrink** [comment]
Related #932

**Comment by FabianGosebrink** [comment]
Implemented, will be in Release 12.

**Comment by Lexa-tech** [comment]
> Implemented, will be in Release 12.

Thanks @FabianGosebrink
