### ISSUE TITLE
Remove dependency on jsrsasign

### ISSUE THREAD

**Issue by cgatian** [damienbod/angular-auth-oidc-client#968]
**Is your feature request related to a problem? Please describe.**
For code flow jrasign is no longer needed

**Describe the solution you'd like**
Make dependency optional for implicit flow uses

**Comment by damienbod** [comment]
The jsrsasign is required in the code flow to validate the signature of the tokens, see the OIDC specifications. If the signature is not validated, then any token with the correct claims will work and not just the tokens created for the specific code from the STS. 

Greetings Damien

**Comment by cgatian** [comment]
@damienbod. Sorry the feature listed didnt provide more context. 

It was my understanding that jsrsasign was only required for implicit flow, and code flow paths could omit. Hence Manfreds changes in [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc/commit/77cb37abfd08762a59b221257ed8d5d5b7c795d4) where they remove the dependency and have it as an optional import.

**Comment by damienbod** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

Here's the text: 

If the ID Token is received via direct communication between the Client and the Token Endpoint (which it is in this flow), the TLS server validation MAY be used to validate the issuer in place of checking the token signature. The Client MUST validate the signature of all other ID Tokens according to JWS [JWS] using the algorithm specified in the JWT alg Header Parameter. The Client MUST use the keys provided by the Issuer.

If you don't validate the signature, you don't know that the issuer created the id token.

Greetings Damien

**Comment by cgatian** [comment]
@damienbod thank you for the explanation. I'll have to look into why the other library was able to do this successfully. It sounds like you are saying the other library is incorrectly adhering to the spec.
