### ISSUE TITLE
UserData and IsAuthorized out of sync?

### ISSUE THREAD

**Issue by fdcastel** [damienbod/angular-auth-oidc-client#97]
After a successful login both `_isAuthorized` and `_userData` observables are changed.

But after a successful logout just `_isAuthorized` is changed. And `_userData` keeps its old value.

This is the expected behavior? If yes, please explain.

If no, then may I suggest to keep just *one* `Observable<UserData>` and simply derive `_isAuthorized` from it? (`isAuthorized => !!userData`).

Finally, I believe [this](https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.service.ts#L38) is result from a bad copy & paste and should be removed 😉.

Best regards and thanks for this great piece of code!

**Comment by damienbod** [comment]
@fdcastel thanks, I will look into this, and also clean up the code

Greetings Damien
