### ISSUE TITLE
UserService.resetUserDataInStore() method throws "Uncaught TypeError: Cannot read property 'name' of null" error

### ISSUE THREAD

**Issue by rtmacphail** [damienbod/angular-auth-oidc-client#972]
**Describe the bug**
Using version 11.5.0

When calling the OidcSecurityService logoff() or logoffAndRevokeTokens() methods, the userService resetUserDataInStore() method gets called to remove the userData object from storage. After removing the object, that method fires an event and emits a null value in the userDataInternal$ behavior subject. As a result, the following error is thrown in the console:

(In Chrome)
```
Uncaught TypeError: Cannot read property 'name' of null
    at t._next (main-es2015.js:6)
    at t.__tryOrUnsub (VM10 scripts.js:1)
    at t.next (VM10 scripts.js:1)
    at t._next (VM10 scripts.js:1)
    at t.next (VM10 scripts.js:1)
    at t.next (VM10 scripts.js:1)
    at t.next (VM10 scripts.js:1)
    at e.resetUserDataInStore (main-es2015.js:6)
    at e.resetAuthorizationData (main-es2015.js:6)
    at e.logoff (main-es2015.js:6)
```

(In Firefox)
`TypeError: e is null`

I can prevent this method from being invoked by setting the following property in auth.config.module: `autoUserinfo: false`, but that means the userData object doesn't get removed from storage, which is a worse outcome than an error in the console. The logout flow works fine otherwise: the tokens are revoked and the session invalidated on my identity server, and the tokens and userData are removed from browser storage, so the console error isn't a big deal - just thought I'd bring it to your attention.

Great library!

**Comment by damienbod** [comment]
Thanks @rtmacphail for reporting, I'll loook into this.

**Comment by damienbod** [comment]
Hi @rtmacphail thanks

I try to reproduce this and can't get this error.. Using the start-sample-code-flow-refresh-tokens example.  Can you check again or how does your logout work?

Greetings Damien

**Comment by FabianGosebrink** [comment]
Hey, I just checked the code and we are not referring to the `name` property of the `userData$`. Maybe I missed something but can you show us where you access the `.name` property? Do you have a sample repo or any more code to check? Thanks.
