### ISSUE TITLE
Fix the problem that checkauth() for autologin sample fails when called a first time ( either on Library level or by fixing the sample code)

### ISSUE THREAD

**Issue by hhutzler** [damienbod/angular-auth-oidc-client#973]
**Is your feature request related to a problem? Please describe.**
After playing around with the autologin sample we found out that this sample doesn not working well when protecting the Home component with an AuthorizationGuard

Our Code change: 
  { path: '', pathMatch: 'full', redirectTo: 'home' },
  { path: 'home', component: HomeComponent,  canActivate: [AuthorizationGuard] }
  
After this Code change canActivate() for Home Component  fails  and and AuthorizationGuard  navigates us to the /unauthorized page
Log Entry:
   ____ AuthorizationGuard, canActivate isAuthorized: false - route: Route(url:'home', path:'home')
   ____ AuthorizationGuard navigating to /unauthorized , canActivate isAuthorized: false
It seems the AuthorizationGuard runs this validation before OidcSecurityService has finished its Keycloak Login. 

We don't want this behaviour as we need extra code for dealing with /unauthorized page and we get  an additional Page Reload.

**Describe the solution you'd like**
 Can  APP_INITIALIZER code used  ( see below )  to fix the gerneric Library problem that first checkAuth() fails ?

**Describe alternatives you've considered**
My colleague  @https://github.com/almasch   comes up with  following fix for the autologin sample 
- Use the APP_INITIALIZER code belowe to run the first  checkAuth() call. 
- By using a promise Angular will now wait until resolve() was called, before continuing with the App initialization. 

```
/* following method is there to fix a problem with oidc module
   https://github.com/damienbod/angular-auth-oidc-client/issues/906
   see also corresponding app initializer below*/

**export function initGuard(service: OidcSecurityService): any {
  return (): Promise<any> => {
    return new Promise <void>((resolve, reject) => {
      console.log('____ APP_INITIALIZER::initGuard initial checkAuth()  call started');
      service.checkAuth().subscribe(isAuthenticated => {
        console.log('____ APP_INITIALIZER::initGuard initial checkAuth()  call  finished:  isAuthenticated Status : ' + isAuthenticated );
        resolve();
      });
    });
  };
}**
```

```
@NgModule({
  imports: [AuthModule.forRoot()],
  providers: [
    OidcConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: configureAuth,
      deps: [OidcConfigService],
      multi: true,
    },
    AuthorizationGuard,
    **{
      provide: APP_INITIALIZER,
      deps: [OidcSecurityService],
      useFactory: initGuard,
      multi: true
    }**
  ],
  exports: [AuthModule],
})
```

**Additional context**
Related issue :
 https://github.com/damienbod/angular-auth-oidc-client/issues/906

**Comment by FabianGosebrink** [comment]
Can you give us a sample repo?

**Comment by damienbod** [comment]
The default route should not use a auth guard. Due to how the OIDC specification works, the default route needs to process the callbacks before a guard kicks in. If you guard the default route you will have a race condition on the OIDC callback. 

Greetings Damien

**Comment by damienbod** [comment]
fixed in https://github.com/damienbod/angular-auth-oidc-client/pull/987

release 11.6.1
