### ISSUE TITLE
Logout from one tab and how to subscribe to the event in another tab

### ISSUE THREAD

**Issue by severus1990** [damienbod/angular-auth-oidc-client#977]
I am using version **10.0.15**. I am having the same logout issue. When l logout in one tab, and how can I subscribe to that event in the other tab, so that I can prevent the user from hitting the endsession url. . @damienbod Please help! I am looking for a solution for couple of days.

How to subscribe to session_state

**Comment by FabianGosebrink** [comment]
As Version 10 is not supported anymore please update to the latest version and see if the issue still exists there. Thanks.
