### ISSUE TITLE
Unregister popupService.receivedUrl$

### ISSUE THREAD

**Issue by cam92yz** [damienbod/angular-auth-oidc-client#980]
Hello

If the PopUp is used more than once the "/token" endpoint gets called multiple times.
Please unregister the "receivedUrl$" observable. 

![image](https://user-images.githubusercontent.com/48785301/108837562-b4b0ce00-75d2-11eb-89f5-4e912d4883b3.png)

![image](https://user-images.githubusercontent.com/48785301/108838316-c2b31e80-75d3-11eb-854f-5a08699cb523.png)

**Comment by FabianGosebrink** [comment]
Thanks for the issue. Why closed?

**Comment by cam92yz** [comment]
Sorry, pressed the wrong button : )

**Comment by FabianGosebrink** [comment]
Easy, I know this :) Thanks for the PR! Will look into it but looks fine so far.

**Comment by damienbod** [comment]
released version 11.6.0 Thanks @cam92yz
