### ISSUE TITLE
Support for custom grant types?

### ISSUE THREAD

**Issue by axeleroy** [damienbod/angular-auth-oidc-client#984]
Hello,

I would like to know if the library supports custom OAuth 2.0 grants (in addition to standard grants), and if it does how to use them.
The backend we use has a custom grant for enterprise logins.

Thanks.

**Comment by damienbod** [comment]
Hi @axeleroy At the moment, only standard grants are supported although a lot of customisations are possible using the configuration. What type of custom grant implementation do you have?

Greetings Damien

**Comment by axeleroy** [comment]
The usecase we are looking to implement is the following:

1. User gets directed to our front-end with a single-use token in a query param (ie. `://front-end.tld/?token=<single_use_token>`)
2. The front-end calls `{{authentication-api.url}}/protocol/openid-connect/token` with the following data
```json
{
  "grant_type": "urn:onep:params:oauth:grant-type:sso",
  "single_use_token": "<value of the token query param>",
  "client_id": "<client_id>"
}
```
3. The endpoint returns the object containing the tokens as it would with the usual grants
```json
{
  "scope": "id",
  "access_token": "eyJ...",
  "expires_in": 60,
  "token_type": "Bearer",
  "id_token": "eyJ...",
  "refresh_expires_in": 28800,
  "refresh_token": "eyJ..."
}
```
4. The tokens are stored in the browser and then used by the front-end as normal

**Comment by damienbod** [comment]
This does not sounds very safe, why do you not use a standard? for example the code flow with PKCE? The code is also a one time usage with all the required validations and checks.

Greetings Damien

**Comment by axeleroy** [comment]
Well, we could later change the flow to PKCE, but I still have no clue as to how I can make the request in the first place using the lib.

**Comment by damienbod** [comment]
@axeleroy This custom flow you do is not possible, sorry. You would have to implement this yourself but I would not recommend inventing your own flows.  Maybe you could find code bits in the src which could help you.

Greetings Damien
