### ISSUE TITLE
Silent renew with refersh tokens broken after first failed request - Handle no connection use case

### ISSUE THREAD

**Issue by dome4** [damienbod/angular-auth-oidc-client#985]
**Describe the bug**
The silent renew check seems to be broken after the first request fails e.g. because of a connection problem. The result is  `OidcService code request` to my endpoint with an HTTPErrorResponse. I'm using refresh tokens and just turned the internet connection off. Is someone experiencing the same issue?

**To Reproduce**
1. Log the user in
2. Turn off internet connection in the browser
3. See error

**Expected behavior**
HTTP Error response should be handeled properly. If a *token not valid* response is emitted by the identity server, the user should be logged out. Otherwise,  the request should be retried in a specific intervall.

**Comment by damienbod** [comment]
Hi @dome4 I tested this and it works, Tried with the example by disconnecting the internet and a second test revoking the refresh token. Both works. The authenticated is set to false which you can subscribe to.

Greetings Damien

**Comment by dome4** [comment]
Hey @damienbod, sorry for the late reply and thanks for looking into this. I know it could be in the app's scope and probably not in the auth library, but for a PWA a user should not be set to isAuthenticated=false immediately if a token refresh fails. One reason for this could be the lack of internet connection. I'm thinking about distinguishing between two scenarios:

(1) an *invalid token response* from the auth server (often status code 400) -> isAuthenticated should be set to false and the user should be logged out immediately.
(2) other responses e.g. status code 0 (no internet connection) -> token refresh failed. The app cannot sync with the backend, but the user should be able to use the app as long as they had a valid access token at some point in the past.

Correct me if I'm on the absoultely wrong track, but it might be interesting for other PWA apps.



Translated with www.DeepL.com/Translator (free version)

**Comment by damienbod** [comment]
I would makes sense to handle the no internet connection, thanks for the issue.

Greetings Damien
