### ISSUE TITLE
Handling external logoff event

### ISSUE THREAD

**Issue by JakeSmokie** [damienbod/angular-auth-oidc-client#986]
In our environment we have embedded iframe SPA application.
The problem is that user logouts from website using external logout button in main application without triggering `OidcSecuryService.logoff()`.
Then user logs in and `getToken()` method returns previous token.

Seems like we don't handle session changing. How can we do that?

**Comment by damienbod** [comment]
You could implement this yourself in the parent application. You can clean up the sessionstorage by send an event to the client application, or you can send an endsession request to the STS and the checksession from the child app will pick this up and handle as required. Iframes are being used here which will cause problems in some browsers (ie not work) and soon more browsers will stop working.

Greetings Damien

**Comment by JakeSmokie** [comment]
Thanks for an explanation! Most probably this is implemented in parent application so I'll have to implement events handling in my client
