### ISSUE TITLE
I am getting the same problem while doing the change password flow.

### ISSUE THREAD

**Issue by ankit68543** [damienbod/angular-auth-oidc-client#992]
I am getting the same problem while doing the change password flow.
Can anyone share the sample code? This would help a lot.

_Originally posted by @ankit68543 in https://github.com/damienbod/angular-auth-oidc-client/issues/289#issuecomment-787482702_

**Comment by damienbod** [comment]
Hi @ankit68543 
closing not sure what I need to do here

Greetings Damien
