### ISSUE TITLE
Sign out from all clients is not working (SSO/SLO)

### ISSUE THREAD

**Issue by ebinroy** [damienbod/angular-auth-oidc-client#993]
Hi,
    I am trying to achieve logout from all clients but could not achieve this. oidcSecurityService.logoff() will logoff from the OIDC but could not from all clients because the session of other clients are still active. I am using Identityserver4 as OIDC provider. I have posted a query on stackoverflow. Is there any way to achieve this . Thanks in advance

[https://stackoverflow.com/questions/66416023/angular-angular-auth-oidc-client-identity4-slo-sso-logout-from-all-clients-not-w](https://stackoverflow.com/questions/66416023/angular-angular-auth-oidc-client-identity4-slo-sso-logout-from-all-clients-not-w)

**Comment by damienbod** [comment]
Hi @ebinroy 

depends and a few things.

An SPA can only logout using the endsession and the other instances can recieve the event throuth the frontchannel spec which uses iframes. Iframes are getting blocked sometimes and the instance needs to be open in a tab or whatever. SPAs have no backchannel.

Another problem is that using refresh tokens, each instance has a refresh token and theis will login again even if you are logged out on the STS. You could do some type of local cleanup between your instances which delete all refresh tokens. 

Logout is not simple to solve using SPAs.

**Comment by ebinroy** [comment]
Thanks for the reply.
