### ISSUE TITLE
Cannot jump from the address bar without logging in

### ISSUE THREAD

**Issue by fengzhihenxs** [damienbod/angular-auth-oidc-client#994]
Hello, after using this library, some pages that can be browsed without logging in are automatically redirected to the home page after entering the address in the browser. The address bar address can be redirected normally after logging in. Why? How to solve it?

**Comment by FabianGosebrink** [comment]
Do you have a sample repo/Stackblitz to see usage and your routing?

**Comment by fengzhihenxs** [comment]
@FabianGosebrink No repo at the moment. This is my configuration：
 oidcConfigService.withConfig({
       stsServer: '/identityserver',
       redirectUrl: 'https://localhost:4200',
      postLogoutRedirectUri: 'https://localhost:4200',
       clientId: 'client',
       scope: 'openid profile ApiOne offline_access',
      responseType: 'code',
       silentRenew: true,
       useRefreshToken: true,
       renewTimeBeforeTokenExpiresInSeconds: 10,
      logLevel: LogLevel.Error
     });

**Comment by FabianGosebrink** [comment]
Just tried it with the sample of refresh tokens and I can not reproduce it. Can you please provide a sample repo in your github that we can have a look? Help us to help you :-) Thanks!

**Comment by fengzhihenxs** [comment]
@FabianGosebrink  Hello, I will put the test demo at https://github.com/fengzhihenxs/authentication. If you have time, help me see. Looking forward to your help me find the reason, thank you

**Comment by FabianGosebrink** [comment]
Thanks. I see some redirects in your solution. Do you want to use autologin?

**Comment by fengzhihenxs** [comment]
There is automatic login in the demo, but I should be useless

**Comment by fengzhihenxs** [comment]
@FabianGosebrink  In addition, I found that when using silent update, sometimes the request token is 400 when silent. I don't know if it is the problem of the identity server or other reasons. Thank you
![image](https://user-images.githubusercontent.com/37610470/109774909-ca11a200-7c3b-11eb-880b-a3777b1bc415.png)

**Comment by FabianGosebrink** [comment]
Hey, thanks for the repo, checked your solution. This is related to your actions in ngrx. 

When you run to `unauthorized` which is not protected and youre not authenticated you check the auth with

```
 checkauth$ = createEffect(() =>
    this.actions$.pipe(
      ofType(fromAuthActions.checkAuth),
      switchMap(() =>
        this.authService
          .checkAuth()
          .pipe(
            map((isLoggedIn) =>
              fromAuthActions.checkAuthComplete({ isLoggedIn })
            )
          )
      )
    )
  );
``` 

The `checkAuthComplete` action then fires a `logoutCmplete()` action because youre not authenticated

```
  checkAuthComplete$ = createEffect(() =>
    this.actions$.pipe(
      ofType(fromAuthActions.checkAuthComplete),
      switchMap(({ isLoggedIn }) => {
        if (isLoggedIn) {
          return this.authService.userData.pipe(
            map((profile) =>
              fromAuthActions.loginComplete({ profile, isLoggedIn })
            )
          );
        }
        return of(fromAuthActions.logoutComplete()); // <<< Here
      })
    )
  );

```

and the Logout complete action then redirects you back to root

```
  logoutComplete$ = createEffect(
    () =>
      this.actions$.pipe(
        ofType(fromAuthActions.logoutComplete),
        tap(() => {
          this.router.navigate(['/']);
        })
      ),
    { dispatch: false }
  );
```

And in your routing you configured root to redirect to home.

```

const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  // ...
];
```

So this is not a bug in the lib. You can try to remove the `return of(fromAuthActions.logoutComplete());` action in the `checkAuthComplete` effect.

Thanks for providing the repository!

**Comment by fengzhihenxs** [comment]
@FabianGosebrink  Ok, thank you very much.
In addition, I found that when using silent update, sometimes the request token is 400 when silent. I don't know if it is the problem of the identity server or other reasons. Thank you.

![image](https://user-images.githubusercontent.com/37610470/109787496-3f37a400-7c49-11eb-97a4-ec0b91a3d316.png)

**Comment by FabianGosebrink** [comment]
This should be fixed in the latest version as we gave the autologin some love if you're using this. This can also occur if you call checkauth multiple times.

**Comment by fengzhihenxs** [comment]
@FabianGosebrink Ok, thank you very much

**Comment by FabianGosebrink** [comment]
You are very welcome, happy to help

**Comment by fengzhihenxs** [comment]
@FabianGosebrink  Hello, excuse me. I want to log in as soon as the project starts. There are two ways to do it. 
First, the default entry project is the automatic login component, and the login processing is done in this component. The routing configuration is as follows: Routes = [
  {path:'', redirectTo:'autologin', pathMatch:'full' },
  {
    path:'home', component: HomeComponent,
    canActivate: [AuthorizationGuard]
  },
  {
    path:'protected',
    component: ProtectedComponent,
    canActivate: [AuthorizationGuard],
  },
  {path:'unauthorized', component: UnauthorizedComponent },
  {path:'autologin', component: AutoLoginComponent },
]. 
Second, the default entry project is the home component, and the guard is used in the home, and the guard is used for login processing. The routing configuration is as follows routes: Routes = [
  {path:'', redirectTo:'home', pathMatch:'full' },
  {
    path:'home', component: HomeComponent,
    canActivate: [AuthorizationGuard]
  },
  {
    path:'protected',
    component: ProtectedComponent,
    canActivate: [AuthorizationGuard],
  },
  {path:'unauthorized', component: UnauthorizedComponent },
  {path:'autologin', component: AutoLoginComponent },
]. 
The problem now is that I repeat the jump after logging in. I don't know what's going on. I ask for your help.

https://user-images.githubusercontent.com/37610470/112100079-74764880-8b9c-11eb-834b-312b39f80de9.mp4
