### ISSUE TITLE
offline_access required issue

### ISSUE THREAD

**Issue by KBRETON1** [damienbod/angular-auth-oidc-client#997]
@damienbod  We are using OpenAM and would like to use refresh tokens with silent renew.  However, the OpenAM rejects offline_access scope with this error:
xxxxx?error_description=Unknown%2Finvalid%20scope%28s%29%3A%20%5Boffline_access%5D&xxxxxx&error=invalid_scope

OpenAM is returning refresh tokens without offline_access scope specified.  However, the library requires this scope to be set in order to use the refresh tokens.      I saw the commit that requires offline_access mentioning the spec.    Would it be possible to add a flag to disable this requirement and default to false?   This would allow us and others to override based upon Idp functionality.

Background, without this ability we are running into this issue:
Token expires in 1 hour
Configure the library for silent renew without refresh tokens.    
Ensure renew time is 5 minutes before expiry.
The iframe calls authorize and get response from OpenAM:  error_description=The request requires some interaction that is not allowed.&error=interaction_required.

Support said the session (cookie) expires at 15 minutes.   The authorize needs to be called before 15 minutes or use refresh tokens.

Thank you for any help/input.

**Comment by debottam31** [comment]
@damienbod we are also facing the same issue. Need some suggestion

**Comment by damienbod** [comment]
I will add support for this.

https://github.com/damienbod/angular-auth-oidc-client/issues/956

**Comment by damienbod** [comment]
fixing in PR https://github.com/damienbod/angular-auth-oidc-client/pull/998
