### ISSUE TITLE
Silent refresh token renew does not work

### ISSUE THREAD

**Issue by Manuel-Moya** [damienbod/angular-auth-oidc-client#999]
**Describe the bug**
The token is never renewed, the first time tries to renew and raises an error.

**To Reproduce**
Silent refresh token renw

**Expected behavior**
It should refresh the token

**Screenshots**
![image](https://user-images.githubusercontent.com/70275834/110014759-74182980-7d23-11eb-9947-bc6b3c84736d.png)

**Additional context**
I am using the example AzureAD-Auth-MyUI-with-MyAPI to reproduce the issue and the silent token refresh does not work

**Comment by damienbod** [comment]
The error says interaction required which means you are not logged in on the STS. If you are not logged in, then you can cannot refresh.

Greetings Damien

**Comment by Manuel-Moya** [comment]
I am logged in, and everything works properly until the token as to be refreshed silently.
![image](https://user-images.githubusercontent.com/70275834/110016614-8b581680-7d25-11eb-8957-d2b7932de610.png)

**Comment by damienbod** [comment]
@Manuel-Moya Azure, this could be an iframe bug as well. Can you try using refresh tokens?

Here's an example:

https://github.com/damienbod/AzureADAuthRazorUiServiceApiCertificate/blob/main/AngularAzureADMultipleApis/AngularAzureAD/src/app/app.module.ts#L19-L31

**Comment by Manuel-Moya** [comment]
@damienbod  I have just tried using refresh tokens, but once the token has to be refreshed, it fails.

![image](https://user-images.githubusercontent.com/70275834/110022021-be9da400-7d2b-11eb-89cf-281b6f733a9e.png)

**Comment by damienbod** [comment]
This is a validation problem , disable the nonce validation for the refresh

Add this to your config:

ignoreNonceAfterRefresh: false

**Comment by Manuel-Moya** [comment]
Setting ignoreNonceAfterRefresh: true as you suggested worked.

Thanks a lot for your assistance.

I will play around with my Azure setup to find an explanation about why it was not working.
